Repository kubeflow/pipelines, pull requests merged in 2018-06, with the labels that each got.

#6 Add manifests for CRD, examples
  example/every-minute-cron.yaml
  example/every-minute-periodic.yaml
  install/manifests/pipelines-crd.yaml
Labels: approved, lgtm, needs-ok-to-test, size/M

#9 Fix typo in README.md
  README.md
Labels: size/XS

#10 deplize
  Gopkg.lock
  Gopkg.toml
Labels: approved, lgtm, size/XL

#11 Adding a Dockerfile to create the scheduled workflow container.
  Dockerfile
  README.md
  install/manifests/scheduledworkflow-crd.yaml
Labels: size/M

#13 Fixing bug in parameterized sample.
  example/parameterized.yaml
  resources/scheduledworkflow/util/scheduled_workflow_test.go
Labels: size/M

#14 Improve Dockerfile
  .gitignore
  Dockerfile
  Makefile
Labels: approved, lgtm, size/M
