Repository kubeflow/pipelines, pull requests merged in 2018-12, with the labels that each got.

#435 DSL - return self for .after()
  sdk/python/kfp/dsl/_container_op.py
Labels: approved, lgtm, size/XS

#210 SDK/Components/PythonContainerOp - Simplified GCSHelper by extracting duplicate code
  sdk/python/kfp/compiler/_component_builder.py
Labels: approved, area/sdk/components/python_container_op, lgtm, size/S

#405 Add loading spinner to custom table while loading items
  frontend/src/Css.tsx
  frontend/src/components/CustomTable.test.tsx
  frontend/src/components/CustomTable.tsx
  frontend/src/components/__snapshots__/CustomTable.test.tsx.snap
  frontend/src/pages/RunList.test.tsx
  frontend/src/pages/__snapshots__/RecurringRunsManager.test.tsx.snap
  frontend/src/pages/__snapshots__/RunList.test.tsx.snap
Labels: approved, area/front-end, lgtm, size/XL

#309 SDK/DSL - Added support for conditions: !=, <, <=, >=, >
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/dsl/_ops_group.py
  sdk/python/kfp/dsl/_pipeline_param.py
Labels: approved, area/sdk/dsl/compiler, lgtm, size/S

#442 SDK/PythonContainer - Compiling pipelines without needing kubernetes
  sdk/python/kfp/compiler/_component_builder.py
Labels: approved, area/sdk/components/python_container_op, lgtm, size/XS

#364 SDK - Improve the python package build
  sdk/python/build.sh
Labels: approved, area/sdk, lgtm, size/S

#388 SDK/Components - Removed outputs from task factory function signature
  sdk/python/kfp/components/_components.py
  sdk/python/tests/components/test_components.py
  sdk/python/tests/components/test_python_op.py
Labels: approved, area/sdk/components, lgtm, size/M

#433 Tests - Try fix GCS file being inaccessible right after upload
  test/presubmit-tests.sh
Labels: approved, area/testing, lgtm, size/XS

#430 SDK/GCP - Replaced default_gcp_op with task.apply(use_gcp_secret)
  sdk/python/kfp/dsl/__init__.py
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/kfp/dsl/_default_gcp_op.py
  sdk/python/kfp/gcp.py
Labels: approved, area/sdk, lgtm, size/L

#447 Show pipeline details embedded in runs
  frontend/mock-backend/fixed-data.ts
  frontend/src/components/Router.tsx
  frontend/src/components/__snapshots__/Router.test.tsx.snap
  frontend/src/lib/RunUtils.ts
  frontend/src/lib/URLParser.ts
  frontend/src/pages/AllRunsList.tsx
  frontend/src/pages/Compare.tsx
  frontend/src/pages/ExperimentDetails.test.tsx
  frontend/src/pages/ExperimentDetails.tsx
  frontend/src/pages/ExperimentList.test.tsx
  frontend/src/pages/ExperimentList.tsx
  frontend/src/pages/NewExperiment.test.tsx
  frontend/src/pages/NewExperiment.tsx
  frontend/src/pages/NewRun.test.tsx
  frontend/src/pages/NewRun.tsx
  frontend/src/pages/PipelineDetails.test.tsx
  frontend/src/pages/PipelineDetails.tsx
  frontend/src/pages/PipelineList.test.tsx
  frontend/src/pages/RunDetails.test.tsx
  frontend/src/pages/RunDetails.tsx
  frontend/src/pages/RunList.test.tsx
  frontend/src/pages/RunList.tsx
  frontend/src/pages/__snapshots__/PipelineDetails.test.tsx.snap
  frontend/src/pages/__snapshots__/RunList.test.tsx.snap
Labels: approved, area/front-end, lgtm, size/XL

#463 import bug
  sdk/python/kfp/compiler/_component_builder.py
Labels: approved, lgtm, size/XS

#465 Support cloning runs created with an embedded pipeline
  frontend/src/pages/NewRun.test.tsx
  frontend/src/pages/NewRun.tsx
  frontend/src/pages/__snapshots__/NewRun.test.tsx.snap
Labels: approved, area/front-end, lgtm, size/XL

#459 Wait until logs appear right in e2e test
  test/frontend-integration-test/helloworld.spec.js
Labels: approved, area/front-end, lgtm, size/XS

#472 Refresh while waiting for run to start
  test/frontend-integration-test/helloworld.spec.js
Labels: approved, area/front-end, lgtm, size/S

#424 SDK/Components/PythonContainerOp - Make the local output path configurable
  sdk/python/kfp/compiler/_component_builder.py
  sdk/python/tests/compiler/component_builder_test.py
Labels: approved, area/sdk/components/python_container_op, lgtm, size/M

#474 Fix serializing cloned embedded pipeline
  frontend/mock-backend/fixed-data.ts
  frontend/src/pages/NewRun.test.tsx
  frontend/src/pages/NewRun.tsx
  frontend/src/pages/__snapshots__/NewRun.test.tsx.snap
Labels: approved, area/front-end, lgtm, size/M

#476 Return string from pod logs
  frontend/server/k8s-helper.ts
Labels: approved, area/front-end, lgtm, size/XS

#471 Add article on Jupyter notebooks
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#469 Adds tests for the run comparison page
  frontend/src/components/CollapseButton.test.tsx
  frontend/src/components/CollapseButton.tsx
  frontend/src/pages/Compare.test.tsx
  frontend/src/pages/Compare.tsx
  frontend/src/pages/ExperimentDetails.test.tsx
  frontend/src/pages/__snapshots__/Compare.test.tsx.snap
Labels: approved, area/front-end, area/testing, lgtm, size/XXL

#484 Bump default pipeline version to v0.1.3
  pipeline/pipeline/prototypes/pipeline.jsonnet
Labels: approved, lgtm, size/XS

#483 clean up test - remove unused workflow
  test/e2e_test_gke.yaml
  test/sample_test.yaml
Labels: approved, lgtm, size/XL

#491 support tpu settings in dsl
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/kfp/gcp.py
  sdk/python/tests/compiler/testdata/basic.py
  sdk/python/tests/compiler/testdata/basic.yaml
Labels: approved, lgtm, size/M

#470 Add notebook sample test: tfx sample
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
  samples/notebooks/Lightweight Python components - basics.ipynb
  sdk/python/kfp/_client.py
  test/sample-test/Dockerfile
  test/sample-test/check_notebook_results.py
  test/sample-test/clean_cmle_models.py
  test/sample-test/run_basic_test.py
  test/sample-test/run_test.sh
  test/sample_test_v2.yaml
Labels: approved, lgtm, size/L

#486 Add experiment selector to NewRun
  frontend/src/TestUtils.tsx
  frontend/src/components/Trigger.tsx
  frontend/src/components/__snapshots__/Trigger.test.tsx.snap
  frontend/src/pages/NewRun.test.tsx
  frontend/src/pages/NewRun.tsx
  frontend/src/pages/PipelineDetails.tsx
  frontend/src/pages/PipelineSelector.test.tsx
  frontend/src/pages/PipelineSelector.tsx
  frontend/src/pages/ResourceSelector.test.tsx
  frontend/src/pages/ResourceSelector.tsx
  frontend/src/pages/__snapshots__/NewRun.test.tsx.snap
  frontend/src/pages/__snapshots__/ResourceSelector.test.tsx.snap
  test/frontend-integration-test/helloworld.spec.js
Labels: approved, area/front-end, lgtm, size/XXL

#496 Show all run outputs in dedicated tab
  frontend/src/lib/WorkflowParser.ts
  frontend/src/pages/RunDetails.test.tsx
  frontend/src/pages/RunDetails.tsx
  frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
Labels: approved, lgtm, size/L

#498 Move pipeline name to request body for create pipeline API
  backend/api/go_client/pipeline.pb.go
  backend/api/go_client/pipeline.pb.gw.go
  backend/api/go_http_client/pipeline_client/pipeline_service/create_pipeline_parameters.go
  backend/api/go_http_client/pipeline_model/api_pipeline.go
  backend/api/pipeline.proto
  backend/api/swagger/pipeline.swagger.json
  backend/src/apiserver/server/pipeline_server.go
  backend/src/apiserver/server/pipeline_server_test.go
  backend/src/cmd/ml/cmd/pipeline.go
  backend/src/common/client/api_server/pipeline_client.go
  backend/src/common/client/api_server/pipeline_client_fake.go
  backend/test/cli_test.go
  backend/test/pipeline_api_test.go
Labels: approved, lgtm, size/L

#511 SDK/Components - Do not crash on non-hashable objects
  sdk/python/kfp/components/_components.py
Labels: approved, lgtm, size/S

#518 Improve TFX Taxi Sample and Components.
  components/dataflow/tfdv/src/validate.py
  components/local/confusion_matrix/src/confusion_matrix.py
  components/local/roc/src/roc.py
  samples/tfx/taxi-cab-classification-pipeline.py
Labels: approved, lgtm, size/L

#508 Improve get_experiment and list_runs in the python sdk
  sdk/python/kfp/_client.py
  test/sample-test/check_notebook_results.py
Labels: approved, lgtm, size/M

#517 Improve the notebook TFX sample
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
Labels: approved, lgtm, size/S

#507 Add new run button to pipeline details
  frontend/src/pages/NewRun.test.tsx
  frontend/src/pages/NewRun.tsx
  frontend/src/pages/PipelineDetails.test.tsx
  frontend/src/pages/PipelineDetails.tsx
  frontend/src/pages/RunList.tsx
  frontend/src/pages/__snapshots__/NewRun.test.tsx.snap
  frontend/src/pages/__snapshots__/RunList.test.tsx.snap
Labels: approved, area/front-end, lgtm, size/XL

#524 Regenerate swagger APIs
  frontend/src/apis/experiment/api.ts
  frontend/src/apis/pipeline/api.ts
  frontend/src/apis/run/api.ts
Labels: approved, area/front-end, lgtm, size/L

#526 Remove the workaround in confusion matrix component for correctly handling boolean cases.
  components/local/confusion_matrix/src/confusion_matrix.py
Labels: approved, lgtm, size/S

#519 SDK/Components - Made component search locations configurable
  sdk/python/kfp/components/__init__.py
  sdk/python/kfp/components/_component_store.py
Labels: approved, lgtm, size/M

#523 Add metric and ui-metadata samples
  components/local/roc/src/roc.py
  samples/notebooks/Lightweight Python components - basics.ipynb
Labels: approved, lgtm, size/M

#531 Add hongye-sun to OWNERS of samples, components, and sdk directories.
  components/OWNERS
  samples/OWNERS
  sdk/OWNERS
Labels: approved, lgtm, size/XS

#529 Change "namespace" param to "host" in kfp client so we can use Jupyter outside cluster.
  sdk/python/kfp/_client.py
  test/sample-test/run_basic_test.py
  test/sample-test/run_kubeflow_test.py
  test/sample-test/run_tfx_test.py
  test/sample-test/run_xgboost_test.py
Labels: approved, lgtm, size/S

#535 Support Kaniko job in a outside-cluster jupyter.
  sdk/python/kfp/compiler/_k8s_helper.py
Labels: approved, lgtm, size/XS

#499 Add lightweight sample test
  test/sample_test_v2.yaml
Labels: approved, lgtm, size/M

#536 Samples - Moved secret application to the pipeline definition
  samples/kubeflow-tf/kubeflow-training-classification.py
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
  samples/tfx/taxi-cab-classification-pipeline.py
Labels: approved, lgtm, size/M

#538 fix persistence agent to use in cluster DNS instead of kube proxy to access API
  backend/src/agent/persistence/client/pipeline_client.go
  backend/src/agent/persistence/main.go
  backend/src/common/util/service.go
Labels: approved, lgtm, size/L

#541 Hides TaskGroup nodes from runtime graphs and removes unnecessary edges in static graphs
  frontend/src/lib/StaticGraphParser.ts
  frontend/src/lib/WorkflowParser.ts
  frontend/third_party/argo-ui/argo_template.ts
Labels: approved, lgtm, size/S

#522 bump up the sdk version to 0.1.4
  bootstrapper.yaml
  components/kubeflow/launcher/kubeflow_tfjob_launcher_op.py
  components/kubeflow/launcher/src/train.template.yaml
  samples/kubeflow-tf/kubeflow-training-classification.py
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
  samples/notebooks/Lightweight Python components - basics.ipynb
  samples/tfx/taxi-cab-classification-pipeline.py
  samples/xgboost-spark/xgboost-training-cm.py
  uninstaller.yaml
Labels: approved, lgtm, size/M

#527 Skip backend integration tests when cli flag isn't passed
  backend/test/cli_test.go
  backend/test/experiment_api_test.go
  backend/test/job_api_test.go
  backend/test/pipeline_api_test.go
  backend/test/run_api_test.go
  backend/test/test_utils.go
  test/api-integration-test/run_test.sh
  test/backend-unit-test/run_test.sh
Labels: approved, area/back-end, lgtm, size/M

#509 add job to load sample
  backend/Dockerfile
  backend/src/apiserver/main.go
  pipeline/pipeline/pipeline-apiserver.libsonnet
Labels: approved, lgtm, size/M

#542 Restructure dataproc components
  .cloudbuild.yaml
  components/README.md
  components/dataproc/analyze/Dockerfile
  components/dataproc/analyze/build_image.sh
  components/dataproc/analyze/src/analyze.py
  components/dataproc/analyze/src/analyze_run.py
  components/dataproc/base/Dockerfile
  components/dataproc/base/build_image.sh
  components/dataproc/common/__init__.py
  components/dataproc/common/_utils.py
  components/dataproc/containers/base/build.sh
  components/dataproc/create_cluster/Dockerfile
  components/dataproc/create_cluster/build_image.sh
  components/dataproc/create_cluster/src/create_cluster.py
  components/dataproc/create_cluster/src/initialization_actions.sh
  components/dataproc/delete_cluster/Dockerfile
  components/dataproc/delete_cluster/build_image.sh
  components/dataproc/delete_cluster/src/delete_cluster.py
  components/dataproc/predict/Dockerfile
  components/dataproc/predict/build_image.sh
  components/dataproc/predict/src/predict.py
  components/dataproc/train/Dockerfile
  components/dataproc/train/build_image.sh
  components/dataproc/train/src/README.md
  components/dataproc/train/src/XGBoostPredictor.scala
  components/dataproc/train/src/XGBoostTrainer.scala
  components/dataproc/train/src/train.py
  components/dataproc/train/src/xgb4j_build.sh
  components/dataproc/transform/Dockerfile
  components/dataproc/transform/build_image.sh
  components/dataproc/transform/src/transform.py
  components/dataproc/transform/src/transform_run.py
  samples/tfx/taxi-cab-classification-pipeline.py
  samples/xgboost-spark/README.md
  test/sample_test_v2.yaml
Labels: approved, lgtm, size/L

#553 Fixes await bug in create new run
  frontend/src/pages/NewRun.test.tsx
  frontend/src/pages/NewRun.tsx
  frontend/src/pages/__snapshots__/NewRun.test.tsx.snap
Labels: approved, area/front-end, kind/bug, lgtm, size/S

#559 Fix ROC Component
  components/local/roc/src/roc.py
Labels: approved, lgtm, size/S

#558 remove duplicate volumes
  sdk/python/kfp/compiler/compiler.py
Labels: approved, lgtm, size/XS

#562 update dockerfile and build steps
  backend/Dockerfile
  backend/Dockerfile.persistenceagent
  backend/Dockerfile.scheduledworkflow
  developer_guide.md
Labels: approved, lgtm, ok-to-test, size/M

#554 Enables uploading a pipeline via a URL
  frontend/mock-backend/mock-api-middleware.ts
  frontend/src/components/UploadPipelineDialog.test.tsx
  frontend/src/components/UploadPipelineDialog.tsx
  frontend/src/components/__snapshots__/UploadPipelineDialog.test.tsx.snap
  frontend/src/pages/PipelineList.test.tsx
  frontend/src/pages/PipelineList.tsx
Labels: approved, area/front-end, lgtm, size/XXL

#564 Fix frontend mock data after proto changes
  frontend/mock-backend/fixed-data.ts
Labels: approved, area/front-end, lgtm, size/XS

#530 Support GPU image for dnntrainer component
  .cloudbuild.yaml
  .release.cloudbuild.yaml
  components/kubeflow/dnntrainer/Dockerfile
  components/kubeflow/dnntrainer/build_image.sh
  components/third_party_licenses.csv
Labels: approved, lgtm, size/M

#565 Fix XGB Sample with the new ROC component.
  samples/xgboost-spark/xgboost-training-cm.py
  samples/xgboost-spark/xgboost-training-cm.py.tar.gz
Labels: approved, lgtm, size/S

#548 Fix sample test failure
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
  test/sample-test/check_notebook_results.py
  test/sample-test/run_test.sh
Labels: approved, lgtm, size/M

#552 Support archiving/unarchiving runs on the backend
  backend/api/go_client/run.pb.go
  backend/api/go_client/run.pb.gw.go
  backend/api/go_http_client/run_client/run_service/archive_run_parameters.go
  backend/api/go_http_client/run_client/run_service/archive_run_responses.go
  backend/api/go_http_client/run_client/run_service/run_service_client.go
  backend/api/go_http_client/run_client/run_service/unarchive_run_parameters.go
  backend/api/go_http_client/run_client/run_service/unarchive_run_responses.go
  backend/api/go_http_client/run_model/api_run.go
  backend/api/go_http_client/run_model/run_storage_state.go
  backend/api/run.proto
  backend/api/swagger/run.swagger.json
  backend/src/apiserver/model/run.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/server/api_converter.go
  backend/src/apiserver/server/api_converter_test.go
  backend/src/apiserver/server/run_server.go
  backend/src/apiserver/server/run_server_test.go
  backend/src/apiserver/storage/run_store.go
  backend/src/apiserver/storage/run_store_test.go
  backend/src/common/client/api_server/run_client.go
  backend/src/common/client/api_server/run_client_fake.go
  backend/test/pipeline_api_test.go
  backend/test/run_api_test.go
Labels: approved, lgtm, size/XXL

#572 Allow creating runs with no experiments
  backend/src/apiserver/server/run_server.go
  backend/src/apiserver/server/run_server_test.go
Labels: approved, area/back-end, lgtm, size/S

#576 remove xgboost compiled sample
  samples/xgboost-spark/xgboost-training-cm.py.tar.gz
Labels: approved, lgtm, size/XS

#575 Add a gpu sample
  components/release.sh
  samples/kubeflow-tf/kubeflow-training-classification.py
Labels: approved, lgtm, size/S

#500 Tests - Updated image-builder Makefile
  test/imagebuilder/Makefile
Labels: approved, lgtm, size/S

#582 retry on create table in api server
  backend/src/apiserver/client_manager.go
  backend/src/apiserver/config/config.json
Labels: approved, lgtm, size/S

#583 Fix the List run to get all runs
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/server/run_server_test.go
  backend/src/apiserver/server/test_util.go
  backend/src/apiserver/storage/job_store.go
  backend/src/apiserver/storage/run_store.go
Labels: approved, lgtm, size/M

#567 update dockerfile and add build step of frontend
  developer_guide.md
  frontend/Dockerfile
Labels: approved, area/front-end, lgtm, ok-to-test, size/S

#601 Initial version of BigQuery query execution component.
  components/bigquery/base/Dockerfile
  components/bigquery/base/build_image.sh
  components/bigquery/query/Dockerfile
  components/bigquery/query/build_image.sh
  components/bigquery/query/src/query.py
Labels: approved, lgtm, ok-to-test, size/L

#602 fix for boostrapp problem
  pipeline/pipeline/all.libsonnet
Labels: approved, lgtm, ok-to-test, size/XS
