Repository kubeflow/pipelines, pull requests merged in 2018-11, with the labels that each got.

#130 Updated the kubeflow-tf sample README
  samples/kubeflow-tf/README.md
Labels: approved, lgtm, size/S

#147 Prevents '0' from showing up on RunDetails config tab when pipeline has no parameters
  frontend/src/pages/RunDetails.tsx
Labels: approved, area/front-end, lgtm, size/XS

#121 Adjusts the size and position of the pipelines icon
  frontend/src/icons/pipelines.tsx
Labels: approved, area/front-end, lgtm, size/XS

#124 Consolidate UI of toolbars for AllRunsList and ExperimentList
  frontend/src/components/SideNav.test.tsx
  frontend/src/components/SideNav.tsx
  frontend/src/components/__snapshots__/SideNav.test.tsx.snap
  frontend/src/pages/AllRunsList.tsx
  frontend/src/pages/ExperimentList.tsx
  frontend/src/pages/__snapshots__/AllRunsList.test.tsx.snap
Labels: approved, area/front-end, lgtm, size/XL

#136 Require full function signatures
  frontend/src/Css.tsx
  frontend/src/TestUtils.tsx
  frontend/src/atoms/BusyButton.tsx
  frontend/src/atoms/MD2Tabs.tsx
  frontend/src/components/Banner.tsx
  frontend/src/components/CustomTable.tsx
  frontend/src/components/Graph.test.tsx
  frontend/src/components/Graph.tsx
  frontend/src/components/LogViewer.tsx
  frontend/src/components/PlotCard.tsx
  frontend/src/components/Router.tsx
  frontend/src/components/SideNav.tsx
  frontend/src/components/Toolbar.tsx
  frontend/src/components/Trigger.test.tsx
  frontend/src/components/Trigger.tsx
  frontend/src/components/UploadPipelineDialog.tsx
  frontend/src/components/__snapshots__/CustomTable.test.tsx.snap
  frontend/src/components/viewers/ConfusionMatrix.tsx
  frontend/src/components/viewers/HTMLViewer.tsx
  frontend/src/components/viewers/PagedTable.tsx
  frontend/src/components/viewers/ROCCurve.tsx
  frontend/src/components/viewers/Tensorboard.tsx
  frontend/src/components/viewers/Viewer.ts
  frontend/src/components/viewers/ViewerContainer.tsx
  frontend/src/icons/experiments.tsx
  frontend/src/icons/kubeflowLogo.tsx
  frontend/src/icons/pipelines.tsx
  frontend/src/icons/statusRunning.tsx
  frontend/src/lib/LocalStorage.ts
  frontend/src/lib/TriggerUtils.test.ts
  frontend/src/lib/Utils.ts
  frontend/src/lib/WorkflowParser.ts
  frontend/src/pages/AllRunsList.test.tsx
  frontend/src/pages/AllRunsList.tsx
  frontend/src/pages/Compare.tsx
  frontend/src/pages/ExperimentDetails.tsx
  frontend/src/pages/ExperimentList.test.tsx
  frontend/src/pages/ExperimentList.tsx
  frontend/src/pages/ExperimentsAndRuns.tsx
  frontend/src/pages/NewExperiment.tsx
  frontend/src/pages/NewRun.tsx
  frontend/src/pages/Page.tsx
  frontend/src/pages/PipelineDetails.tsx
  frontend/src/pages/PipelineList.test.tsx
  frontend/src/pages/PipelineList.tsx
  frontend/src/pages/PipelineSelector.tsx
  frontend/src/pages/RecurringRunDetails.tsx
  frontend/src/pages/RecurringRunsManager.tsx
  frontend/src/pages/RunDetails.tsx
  frontend/src/pages/RunList.tsx
  frontend/src/pages/Status.tsx
  frontend/tslint.json
Labels: approved, area/front-end, lgtm, size/L

#153 activate public prow service account
  test/api-integration-test/run_test.sh
  test/backend-unit-test/run_test.sh
  test/build_image.yaml
  test/e2e_test_gke.yaml
  test/imagebuilder/build.sh
  test/presubmit-tests-gce-minikube.sh
  test/presubmit-tests.gke.sh
  test/presubmit-tests.sh
  test/sample-test/run_test.sh
  test/sample_test.yaml
  test/unit_test_gke.yaml
Labels: approved, lgtm, size/M

#157 Acknowledge Argo.
  README.md
Labels: approved, lgtm, size/XS

#138 add todos for the image tag update for new releases
  bootstrapper.yaml
  components/kubeflow/launcher/kubeflow_tfjob_launcher_op.py
  components/kubeflow/launcher/train.template.yaml
  samples/kubeflow-tf/kubeflow-training-classification.py
  samples/tfx/taxi-cab-classification-pipeline.py
  samples/xgboost-spark/xgboost-training-cm.py
  sdk/python/kfp/dsl/components/kubeflow_tfjob_launcher_op.py
  uninstaller.yaml
Labels: approved, lgtm, size/M

#155 Update a sample notebook.
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
Labels: approved, lgtm, size/M

#152 sample tests using the dataset in the corresponding test project
  test/sample-test/run_kubeflow_test.py
Labels: approved, lgtm, size/XS

#159 Adding support for experiments in the CLI.
  backend/src/cmd/ml/cmd/client_factory.go
  backend/src/cmd/ml/cmd/client_factory_fake.go
  backend/src/cmd/ml/cmd/experiment.go
  backend/src/cmd/ml/cmd/experiment_test.go
  backend/src/cmd/ml/cmd/job.go
  backend/src/cmd/ml/cmd/job_test.go
  backend/src/cmd/ml/cmd/pipeline.go
  backend/src/cmd/ml/cmd/pipeline_test.go
  backend/src/cmd/ml/cmd/pipeline_upload_test.go
  backend/src/cmd/ml/cmd/root.go
  backend/src/cmd/ml/cmd/run.go
  backend/src/cmd/ml/cmd/run_test.go
  backend/src/common/client/api_server/experiment_client.go
  backend/src/common/client/api_server/experiment_client_fake.go
  backend/src/common/client/api_server/job_client.go
  backend/src/common/client/api_server/pipeline_client.go
  backend/src/common/client/api_server/pipeline_upload_client.go
  backend/src/common/client/api_server/run_client.go
  backend/test/cli_test.go
Labels: approved, size/XL

#151 SDK/Tests - Removed sys.path manipulations.
  sdk/python/tests/components/test_components.py
  sdk/python/tests/components/test_python_op.py
Labels: approved, lgtm, size/S

#167 Sets min height/width of all fullscreen viewers to 80%
  frontend/src/components/PlotCard.tsx
Labels: approved, area/front-end, lgtm, size/XS

#176 Add coveralls for frontend code coverage
  .travis.yml
  README.md
  frontend/package-lock.json
  frontend/package.json
Labels: approved, lgtm, size/XXL

#181 Modify sample notebook.
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
Labels: approved, lgtm, size/XS

#183 Tests - Upgrade Minikube and Kubernetes for new Docker release
  test/minikube/install_and_start_minikube_without_vm.sh
  test/minikube/install_docker_minikube_argo.sh
Labels: approved, area/testing, lgtm, size/XS

#87 Presubmit tests - Added presubmit SDK Components tests to Travis
  .travis.yml
Labels: approved, lgtm, size/XS

#185 Update experimental/OWNERS
  experimental/OWNERS
Labels: approved, lgtm, size/XS

#188 Marked scripts as executable
  components/dataproc/xgboost/create_cluster/initialization_actions.sh
  components/dataproc/xgboost/train/xgb4j_build.sh
  test/api-integration-test/run_test.sh
  test/backend-unit-test/run_test.sh
  test/frontend-integration-test/run_test.sh
  test/imagebuilder/build.sh
Labels: approved, lgtm, size/XS

#112 Add integration tests for API servers
  backend/api/Makefile
  backend/api/experiment.proto
  backend/api/go_client/experiment.pb.go
  backend/api/go_client/experiment.pb.gw.go
  backend/api/go_client/run.pb.go
  backend/api/go_client/run.pb.gw.go
  backend/api/go_http_client/experiment_client/experiment_service/delete_experiment_parameters.go
  backend/api/go_http_client/experiment_client/experiment_service/delete_experiment_responses.go
  backend/api/go_http_client/experiment_client/experiment_service/experiment_service_client.go
  backend/api/go_http_client/experiment_model/protobuf_empty.go
  backend/api/go_http_client/pipeline_upload_model/text_marshmaller_hack.go
  backend/api/go_http_client/run_client/run_service/delete_run_parameters.go
  backend/api/go_http_client/run_client/run_service/delete_run_responses.go
  backend/api/go_http_client/run_client/run_service/run_service_client.go
  backend/api/go_http_client/run_model/api_run.go
  backend/api/go_http_client/run_model/protobuf_empty.go
  backend/api/run.proto
  backend/api/swagger/experiment.swagger.json
  backend/api/swagger/run.swagger.json
  backend/api/text_marshmaller_hack.txt
  backend/src/apiserver/resource/client_manager_fake.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/resource/workflow_fake.go
  backend/src/apiserver/server/api_converter.go
  backend/src/apiserver/server/api_converter_test.go
  backend/src/apiserver/server/experiment_server.go
  backend/src/apiserver/server/experiment_server_test.go
  backend/src/apiserver/server/pipeline_upload_server.go
  backend/src/apiserver/server/run_server.go
  backend/src/apiserver/storage/experiment_store.go
  backend/src/apiserver/storage/experiment_store_test.go
  backend/src/apiserver/storage/job_store_test.go
  backend/src/apiserver/storage/run_store.go
  backend/src/apiserver/storage/run_store_test.go
  backend/src/common/client/api_server/experiment_client.go
  backend/src/common/client/api_server/run_client.go
  backend/test/cli_test.go
  backend/test/experiment_api_test.go
  backend/test/job_api_test.go
  backend/test/pipeline_api_test.go
  backend/test/resources/zip-arguments.tar.gz
  backend/test/run_api_test.go
  backend/test/test_utils.go
  ml-pipeline/ml-pipeline/pipeline-apiserver.libsonnet
Labels: approved, lgtm, size/XXL

#172 SDK/DSL-compiler - Compile without temporary files
  sdk/python/kfp/compiler/compiler.py
Labels: approved, area/sdk/dsl/compiler, lgtm, size/S

#156 SDK - Relative imports
  sdk/python/kfp/compiler/_component_builder.py
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/components/_dsl_bridge.py
  sdk/python/kfp/dsl/_component.py
  sdk/python/kfp/notebook/_magic.py
Labels: approved, lgtm, size/S

#168 SDK/Components - Removed the old argument syntax
  sdk/python/kfp/components/_components.py
  sdk/python/tests/components/test_components.py
Labels: approved, area/sdk/components, lgtm, size/L

#173 SDK/Components - Switched the generated inputs/outputs structure from dict to list
  sdk/python/kfp/components/_structures.py
Labels: approved, lgtm, size/XS

#150 Removes the magic in Input, reducing it to a styled TextField
  frontend/src/atoms/Input.test.tsx
  frontend/src/atoms/Input.tsx
  frontend/src/atoms/__snapshots__/Input.test.tsx.snap
  frontend/src/components/Trigger.tsx
  frontend/src/components/UploadPipelineDialog.tsx
  frontend/src/components/__snapshots__/Trigger.test.tsx.snap
  frontend/src/components/__snapshots__/UploadPipelineDialog.test.tsx.snap
  frontend/src/pages/NewExperiment.tsx
  frontend/src/pages/NewRun.tsx
  frontend/src/pages/__snapshots__/NewExperiment.test.tsx.snap
Labels: approved, area/front-end, lgtm, size/XXL

#148 Remove token from travis badge
  README.md
Labels: approved, lgtm, size/XS

#201 Update check experiment condition
  samples/notebooks/Lightweight Python components - basics.ipynb
Labels: approved, lgtm, size/XS

#211 Use kubeflow as default namespace for tf serving
  components/kubeflow/container/deployer/deploy.sh
Labels: approved, lgtm, size/XS

#217 minor fixes
  sdk/python/tests/compiler/component_builder_test.py
  sdk/python/tests/components/test_python_op.py
Labels: approved, lgtm, size/XS

#135 404 page
  frontend/src/components/Router.tsx
  frontend/src/components/Toolbar.test.tsx
  frontend/src/components/Toolbar.tsx
  frontend/src/components/__snapshots__/Router.test.tsx.snap
  frontend/src/components/__snapshots__/Toolbar.test.tsx.snap
  frontend/src/pages/404.tsx
Labels: approved, area/front-end, lgtm, size/M

#230 Tests - Simplified test/sample-test/run_tests.sh a bit
  test/sample-test/run_test.sh
Labels: approved, area/testing, lgtm, size/M

#235 Move basic sample tests to e2e tests
  test/e2e_test_gke.yaml
  test/frontend-integration-test/helloworld.spec.js
  test/sample_test.yaml
Labels: approved, lgtm, size/L

#242 Adds NewRun tests
  frontend/mock-backend/package-lock.json
  frontend/server/package-lock.json
  frontend/src/components/UploadPipelineDialog.test.tsx
  frontend/src/lib/Utils.ts
  frontend/src/pages/NewExperiment.test.tsx
  frontend/src/pages/NewRun.test.tsx
  frontend/src/pages/NewRun.tsx
  frontend/src/pages/PipelineSelector.tsx
  frontend/src/pages/__snapshots__/NewExperiment.test.tsx.snap
  frontend/src/pages/__snapshots__/NewRun.test.tsx.snap
  test/frontend-integration-test/helloworld.spec.js
Labels: approved, area/front-end, area/testing, lgtm, size/XXL

#202 Recurring run details tests
  frontend/src/components/Router.tsx
  frontend/src/pages/Page.tsx
  frontend/src/pages/RecurringRunDetails.test.tsx
  frontend/src/pages/RecurringRunDetails.tsx
  frontend/src/pages/__snapshots__/RecurringRunDetails.test.tsx.snap
Labels: approved, area/front-end, area/testing, lgtm, size/XL

#273 attach service account to tensorboard pod
  frontend/server/k8s-helper.ts
Labels: approved, lgtm, size/S

#127 Refactor RunList, add test suite
  frontend/src/lib/RunUtils.ts
  frontend/src/pages/ExperimentList.tsx
  frontend/src/pages/PipelineSelector.tsx
  frontend/src/pages/RecurringRunsManager.tsx
  frontend/src/pages/RunList.test.tsx
  frontend/src/pages/RunList.tsx
  frontend/src/pages/__snapshots__/RunList.test.tsx.snap
Labels: approved, area/front-end, area/testing, lgtm, size/XXL

#276 Fix build badge
  README.md
Labels: approved, lgtm, size/XS

#261 Add gcp secret parameter to container op
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/secret.py
  sdk/python/tests/compiler/testdata/secret.yaml
Labels: approved, lgtm, size/L

#277 Revert sample test to mitigate test flakiness
  test/e2e_test_gke.yaml
Labels: approved, lgtm, size/L

#228 enable component build unit test
  sdk/python/kfp/compiler/_component_builder.py
  sdk/python/tests/compiler/component_builder_test.py
  sdk/python/tests/compiler/main.py
Labels: approved, lgtm, size/L

#292 configure logger such that it shows correct colors for the logs
  sdk/python/kfp/compiler/_component_builder.py
Labels: approved, lgtm, size/S

#271 Upgrade @kubernetes/client-node
  frontend/server/package-lock.json
  frontend/server/package.json
Labels: approved, area/front-end, lgtm, size/L

#262 create secret for default service account
  ml-pipeline/Dockerfile
  ml-pipeline/deploy.sh
  ml-pipeline/ml-pipeline/pipeline-apiserver.libsonnet
Labels: approved, lgtm, size/L

#283 Update frontend tensorboard spec
  frontend/server/k8s-helper.ts
Labels: approved, lgtm, size/XS

#232 Components - Reorganized components/kubeflow
  .cloudbuild.yaml
  components/kubeflow/deployer/Dockerfile
  components/kubeflow/deployer/src/deploy.sh
  components/kubeflow/dnntrainer/Dockerfile
  components/kubeflow/dnntrainer/build_image.sh
  components/kubeflow/dnntrainer/src/__init__.py
  components/kubeflow/dnntrainer/src/setup.py
  components/kubeflow/dnntrainer/src/trainer/__init__.py
  components/kubeflow/dnntrainer/src/trainer/task.py
  components/kubeflow/launcher/Dockerfile
  components/kubeflow/launcher/build_image.sh
  components/kubeflow/launcher/src/__init__.py
  components/kubeflow/launcher/src/launch_tf_job.py
  components/kubeflow/launcher/src/train.template.yaml
  components/kubeflow/launcher/test/__init__.py
  components/kubeflow/launcher/test/test_launcher.py
  components/kubeflow/launcher/test/testdata/train.template.yaml
  components/kubeflow/launcher/test/testdata/train_basic.yaml
  components/kubeflow/launcher/test/testdata/train_zero_worker.yaml
  samples/kubeflow-tf/README.md
  samples/tfx/README.md
  test/sample_test.yaml
Labels: approved, lgtm, size/M

#302 Allows copying of pipeline source from pipeline details page
  frontend/src/pages/PipelineDetails.tsx
Labels: approved, area/front-end, lgtm, problems/bug, size/XS

#180 openvino predict component and pipeline example
  contrib/components/openvino/predict/README.md
  contrib/components/openvino/predict/containers/Dockerfile
  contrib/components/openvino/predict/containers/predict.py
  contrib/components/openvino/predict/containers/requirements.txt
  contrib/samples/openvino/predict/README.md
  contrib/samples/openvino/predict/numpy_predict.py
Labels: approved, lgtm, needs-ok-to-test, size/L

#178 OpenVINO model optimizer component and example pipeline
  contrib/components/openvino/model_convert/README.md
  contrib/components/openvino/model_convert/containers/Dockerfile
  contrib/components/openvino/model_convert/containers/convert_model.py
  contrib/samples/openvino/model_optimizer/README.md
  contrib/samples/openvino/model_optimizer/convert_model_pipeline.py
Labels: approved, lgtm, needs-ok-to-test, size/L

#293 Update frontend handling of graphs
  frontend/mock-backend/mock-conditional-template.yaml
  frontend/src/lib/StaticGraphParser.test.ts
  frontend/src/lib/StaticGraphParser.ts
  frontend/src/pages/PipelineDetails.tsx
  frontend/third_party/argo-ui/argo_template.ts
Labels: approved, area/front-end, lgtm, size/XXL

#300 Add volume, volumemount and env to container op
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/volume.py
  sdk/python/tests/compiler/testdata/volume.yaml
Labels: approved, lgtm, size/L

#85 SDK/Components/Python - Removed python_op in favor of python_component
  sdk/python/kfp/compiler/_component_builder.py
  sdk/python/kfp/components/_python_op.py
  sdk/python/kfp/dsl/__init__.py
  sdk/python/kfp/dsl/_component.py
  sdk/python/tests/components/test_python_op.py
Labels: approved, lgtm, size/L

#219 add support for dependencies in the component image building
  sdk/python/kfp/compiler/__init__.py
  sdk/python/kfp/compiler/_component_builder.py
  sdk/python/tests/compiler/component_builder_test.py
Labels: approved, lgtm, size/L

#234 switch default tag to strongly typed version number
  components/dataflow/containers/predict/build.sh
  components/dataflow/containers/tfdv/build.sh
  components/dataflow/containers/tfma/build.sh
  components/dataflow/containers/tft/build.sh
  components/dataproc/containers/analyze/build.sh
  components/dataproc/containers/create_cluster/build.sh
  components/dataproc/containers/delete_cluster/build.sh
  components/dataproc/containers/predict/build.sh
  components/dataproc/containers/train/build.sh
  components/dataproc/containers/transform/build.sh
  components/kubeflow/dnntrainer/build_image.sh
  components/kubeflow/launcher/build_image.sh
  components/local/containers/confusion_matrix/build.sh
  components/local/containers/roc/build.sh
  components/resnet-cmle/containers/deploy/build.sh
  components/resnet-cmle/containers/preprocess/build.sh
  components/resnet-cmle/containers/train/build.sh
Labels: approved, lgtm, size/M

#291 Update default pipeline version in ks package
  ml-pipeline/ml-pipeline/prototypes/ml-pipeline.jsonnet
Labels: approved, lgtm, size/XS

#306 configurable namespaces in sample test and python SDK
  sdk/python/kfp/_client.py
  test/e2e_test_gke.yaml
  test/sample-test/run_basic_test.py
  test/sample-test/run_kubeflow_test.py
  test/sample-test/run_test.sh
  test/sample-test/run_tfx_test.py
  test/sample-test/run_xgboost_test.py
  test/sample_test.yaml
Labels: approved, lgtm, size/M

#299 add ngao to test owner because frequent contributions to this directory, including e2e, sample tests and imagebuilder.
  test/OWNERS
Labels: approved, lgtm, size/XS

#264 Update button styling for new experiment and new run
  frontend/src/components/Toolbar.test.tsx
  frontend/src/components/Toolbar.tsx
  frontend/src/components/__snapshots__/Toolbar.test.tsx.snap
  frontend/src/pages/ExperimentDetails.tsx
  frontend/src/pages/PipelineDetails.tsx
Labels: approved, area/front-end, lgtm, size/L, ux-improvements

#298 reenable basic sample tests, serially after frontend integ tests(triggering 5 times, successful always)
  test/e2e_test_gke.yaml
  test/sample-test/run_test.sh
Labels: approved, lgtm, size/L

#177 SDK/DSL/Compiler - Improved compilation of dsl.Conditional - UX support done
  frontend/mock-backend/mock-conditional-template.yaml
  frontend/src/lib/StaticGraphParser.test.ts
  frontend/src/lib/StaticGraphParser.ts
  frontend/src/pages/PipelineDetails.tsx
  frontend/third_party/argo-ui/argo_template.ts
  sdk/python/kfp/compiler/compiler.py
  sdk/python/tests/compiler/testdata/coin.yaml
Labels: approved, area/sdk/dsl/compiler, lgtm, size/XXL

#312 switch set() to add() for better inheritance.
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/volume.py
  sdk/python/tests/compiler/testdata/volume.yaml
Labels: approved, lgtm, size/M

#317 Use latest npm and node on travis, fix tests
  .travis.yml
  frontend/mock-backend/package-lock.json
  frontend/package-lock.json
  frontend/server/package-lock.json
  frontend/src/components/viewers/Tensorboard.test.tsx
  frontend/src/pages/__snapshots__/PipelineList.test.tsx.snap
  frontend/src/pages/__snapshots__/RecurringRunDetails.test.tsx.snap
Labels: approved, area/front-end, lgtm, size/XXL

#313 return self for container op initialization methods to allow chaining the construction
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/volume.py
Labels: approved, lgtm, size/M

#316 add metric image file for wiki
  docs/images/metric.png
Labels: approved, area/docs, lgtm, size/XS

#314 Add default_gcp_op
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/kfp/dsl/components/__init__.py
  sdk/python/kfp/dsl/components/default_gcp_op.py
Labels: approved, lgtm, size/M

#326 Use ks env for pipeline namespace
  ml-pipeline/deploy.sh
  ml-pipeline/ml-pipeline/all.libsonnet
  ml-pipeline/ml-pipeline/prototypes/ml-pipeline.jsonnet
Labels: approved, lgtm, size/S

#323 SDK/Components - Renamed DockerContainer spec to to Container
  sdk/python/kfp/compiler/_component_builder.py
  sdk/python/kfp/components/_components.py
  sdk/python/kfp/components/_python_op.py
  sdk/python/kfp/components/_structures.py
  sdk/python/tests/components/test_components.py
  sdk/python/tests/components/test_data/python_add.component.yaml
  sdk/python/tests/components/test_python_op.py
Labels: approved, lgtm, size/M

#333 formating jsonnet registry
  ml-pipeline/deploy.sh
  ml-pipeline/ml-pipeline/all.libsonnet
  ml-pipeline/ml-pipeline/argo.libsonnet
  ml-pipeline/ml-pipeline/minio.libsonnet
  ml-pipeline/ml-pipeline/mysql.libsonnet
  ml-pipeline/ml-pipeline/parts.yaml
  ml-pipeline/ml-pipeline/pipeline-apiserver.libsonnet
  ml-pipeline/ml-pipeline/pipeline-persistenceagent.libsonnet
  ml-pipeline/ml-pipeline/pipeline-scheduledworkflow.libsonnet
  ml-pipeline/ml-pipeline/pipeline-ui.libsonnet
  ml-pipeline/ml-pipeline/spartakus.libsonnet
Labels: approved, lgtm, size/L

#320 fix bug for the component build with requirements
  sdk/python/kfp/compiler/_component_builder.py
  sdk/python/tests/compiler/component_builder_test.py
Labels: approved, lgtm, size/XS

#340 rename ks registry ml-pipeline -> pipeline
  .cloudbuild.yaml
  ml-pipeline/README.md
  pipeline/Dockerfile
  pipeline/OWNERS
  pipeline/bootstrapper.sh
  pipeline/deploy.sh
  pipeline/kf_deploy.sh
  pipeline/license.txt
  pipeline/pipeline/all.libsonnet
  pipeline/pipeline/argo.libsonnet
  pipeline/pipeline/minio.libsonnet
  pipeline/pipeline/mysql.libsonnet
  pipeline/pipeline/parts.yaml
  pipeline/pipeline/pipeline-apiserver.libsonnet
  pipeline/pipeline/pipeline-persistenceagent.libsonnet
  pipeline/pipeline/pipeline-scheduledworkflow.libsonnet
  pipeline/pipeline/pipeline-ui.libsonnet
  pipeline/pipeline/prototypes/pipeline.jsonnet
  pipeline/pipeline/spartakus.libsonnet
  pipeline/registry.yaml
  test/build_image.yaml
Labels: approved, lgtm, size/M

#305 Changes "Hide" button on Pipeline summary to fully hide the paper card
  frontend/src/Css.tsx
  frontend/src/pages/PipelineDetails.tsx
Labels: approved, area/front-end, lgtm, size/M, ux-bug

#287 Add run status to page title
  frontend/src/components/Router.tsx
  frontend/src/components/Toolbar.test.tsx
  frontend/src/components/Toolbar.tsx
  frontend/src/components/__snapshots__/Toolbar.test.tsx.snap
  frontend/src/pages/404.tsx
  frontend/src/pages/AllRunsList.tsx
  frontend/src/pages/Compare.tsx
  frontend/src/pages/ExperimentDetails.tsx
  frontend/src/pages/ExperimentList.tsx
  frontend/src/pages/ExperimentsAndRuns.tsx
  frontend/src/pages/NewExperiment.test.tsx
  frontend/src/pages/NewExperiment.tsx
  frontend/src/pages/NewRun.test.tsx
  frontend/src/pages/NewRun.tsx
  frontend/src/pages/PipelineDetails.tsx
  frontend/src/pages/PipelineList.tsx
  frontend/src/pages/PipelineSelector.tsx
  frontend/src/pages/RecurringRunDetails.test.tsx
  frontend/src/pages/RecurringRunDetails.tsx
  frontend/src/pages/RecurringRunsManager.tsx
  frontend/src/pages/RunDetails.tsx
  frontend/src/pages/Status.tsx
  frontend/src/pages/__snapshots__/AllRunsList.test.tsx.snap
  frontend/src/pages/__snapshots__/ExperimentList.test.tsx.snap
  frontend/src/pages/__snapshots__/NewRun.test.tsx.snap
  frontend/src/pages/__snapshots__/RunList.test.tsx.snap
  frontend/src/pages/__snapshots__/Status.test.tsx.snap
Labels: approved, area/front-end, lgtm, size/XL

#260 refactor component build codes
  sdk/python/kfp/compiler/_component_builder.py
  sdk/python/tests/compiler/component_builder_test.py
Labels: approved, lgtm, size/M

#324 Tests - Fixed the argo submit failure not failing the script
  test/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#343 mount gcp credentials for kaniko worker
  sdk/python/kfp/compiler/_component_builder.py
  sdk/python/tests/compiler/testdata/kaniko.basic.yaml
Labels: approved, lgtm, size/M

#338 restructure dataflow component structure
  .cloudbuild.yaml
  components/dataflow/base/Dockerfile
  components/dataflow/base/build_image.sh
  components/dataflow/predict/Dockerfile
  components/dataflow/predict/build_image.sh
  components/dataflow/predict/src/predict.py
  components/dataflow/predict/src/setup.py
  components/dataflow/tfdv/Dockerfile
  components/dataflow/tfdv/build_image.sh
  components/dataflow/tfdv/src/validate.py
  components/dataflow/tfdv/src/validation/setup.py
  components/dataflow/tfma/Dockerfile
  components/dataflow/tfma/build_image.sh
  components/dataflow/tfma/src/analysis/setup.py
  components/dataflow/tfma/src/model_analysis.py
  components/dataflow/tft/Dockerfile
  components/dataflow/tft/build_image.sh
  components/dataflow/tft/src/transform.py
  samples/kubeflow-tf/README.md
  samples/tfx/README.md
  test/sample_test.yaml
Labels: approved, lgtm, size/M

#350 PipelineDetails cleanup
  frontend/mock-backend/package-lock.json
  frontend/package-lock.json
  frontend/server/package-lock.json
  frontend/src/atoms/MD2Tabs.tsx
  frontend/src/components/DetailsTable.test.tsx
  frontend/src/components/DetailsTable.tsx
  frontend/src/components/SidePanel.tsx
  frontend/src/components/StaticNodeDetails.tsx
  frontend/src/components/__snapshots__/DetailsTable.test.tsx.snap
  frontend/src/pages/NewRun.tsx
  frontend/src/pages/PipelineDetails.tsx
  frontend/src/pages/RecurringRunDetails.tsx
  frontend/src/pages/RunDetails.tsx
  frontend/src/pages/RunList.test.tsx
  frontend/src/pages/__snapshots__/RecurringRunDetails.test.tsx.snap
Labels: approved, area/front-end, lgtm, size/XXL

#353 Fixes issue with footer overlapping side panel and fixes summary layout
  frontend/src/pages/PipelineDetails.tsx
Labels: approved, area/front-end, lgtm, size/M

#346 Add support for nvidia gpu limit
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/tests/compiler/testdata/basic.py
  sdk/python/tests/compiler/testdata/basic.yaml
Labels: approved, lgtm, size/L

#366 Tests - Stop repeating the logs three times
  test/presubmit-tests.sh
Labels: approved, area/testing, lgtm, size/S

#319 PipelineSelector, RecurringRunsManager, and 404Page tests
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/404.test.tsx
  frontend/src/pages/PipelineSelector.test.tsx
  frontend/src/pages/PipelineSelector.tsx
  frontend/src/pages/RecurringRunsManager.test.tsx
  frontend/src/pages/RecurringRunsManager.tsx
  frontend/src/pages/__snapshots__/404.test.tsx.snap
  frontend/src/pages/__snapshots__/PipelineSelector.test.tsx.snap
  frontend/src/pages/__snapshots__/RecurringRunsManager.test.tsx.snap
Labels: approved, area/front-end, area/testing, lgtm, size/XXL

#377 Disables back button when there is no history
  frontend/server/package-lock.json
  frontend/src/components/Toolbar.test.tsx
  frontend/src/components/Toolbar.tsx
  frontend/src/components/__snapshots__/Toolbar.test.tsx.snap
Labels: approved, area/front-end, lgtm, size/L

#376 move default gcp op to dsl/
  sdk/python/kfp/dsl/__init__.py
  sdk/python/kfp/dsl/_default_gcp_op.py
  sdk/python/kfp/dsl/components/__init__.py
Labels: approved, lgtm, size/S

#384 remove fire dependency in the component image build
  sdk/python/kfp/compiler/_component_builder.py
  sdk/python/tests/compiler/component_builder_test.py
Labels: approved, lgtm, size/M

#110 Now pipeline function takes direct default values rather than dsp.PipelineParam.
  backend/Dockerfile
  samples/basic/exit_handler.py
  samples/basic/parallel_join.py
  samples/basic/sequential.py
  samples/kubeflow-tf/kubeflow-training-classification.py
  samples/tfx/taxi-cab-classification-pipeline.py
  sdk/python/kfp/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/basic.py
  sdk/python/tests/compiler/testdata/compose.py
  sdk/python/tests/compiler/testdata/default_value.py
  sdk/python/tests/compiler/testdata/testpackage/mypipeline/compose.py
Labels: approved, lgtm, size/L

#375 Add Amy and Lak's Blogs Link to README
  README.md
Labels: approved, lgtm, size/XS

#367 Tests - Improve Minikube source code copy process
  test/presubmit-tests-gce-minikube.sh
Labels: approved, area/testing, lgtm, size/XS

#386 Add finish timestamp to backend API interceptor
  backend/src/apiserver/interceptor.go
Labels: approved, lgtm, size/XS

#378 update samples with dependency requirement in the component image build
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
Labels: approved, lgtm, size/L

#390 Clean up vendor directory
  Gopkg.lock
  vendor/OWNERS
  vendor/gopkg.in/square/go-jose.v2/LICENSE
  vendor/gopkg.in/square/go-jose.v2/json/LICENSE
  vendor/gopkg.in/square/go-jose.v2/json/README.md
  vendor/gopkg.in/square/go-jose.v2/json/decode.go
  vendor/gopkg.in/square/go-jose.v2/json/encode.go
  vendor/gopkg.in/square/go-jose.v2/json/indent.go
  vendor/gopkg.in/square/go-jose.v2/json/scanner.go
  vendor/gopkg.in/square/go-jose.v2/json/stream.go
  vendor/gopkg.in/square/go-jose.v2/json/tags.go
Labels: approved, lgtm, size/XXL

#391 Delete kf_deploy.sh
  pipeline/kf_deploy.sh
Labels: approved, lgtm, size/S

#392 Increase timeout waiting for test run to start
  test/frontend-integration-test/helloworld.spec.js
Labels: approved, area/front-end, lgtm, size/XS

#389 Add support for minio hosted artifacts
  frontend/src/lib/WorkflowParser.test.ts
  frontend/src/lib/WorkflowParser.ts
Labels: approved, lgtm, ok-to-test, size/M

#398 Pointed doc links to Kubeflow website instead of wiki.
  README.md
  components/README.md
  samples/README.md
  samples/basic/README.md
  samples/kubeflow-tf/README.md
  samples/tfx/README.md
  samples/xgboost-spark/README.md
Labels: approved, lgtm, size/S

#394 RunDetails test suite, bug fixes
  frontend/src/lib/OutputArtifactLoader.test.ts
  frontend/src/lib/OutputArtifactLoader.ts
  frontend/src/pages/Compare.tsx
  frontend/src/pages/RunDetails.test.tsx
  frontend/src/pages/RunDetails.tsx
  frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
Labels: approved, area/front-end, lgtm, size/XXL

#387 Backend - Fixed handling of sample compilation failure
  backend/Dockerfile
Labels: approved, area/back-end, lgtm, size/S

#380 PipelineDetails page tests
  frontend/src/components/Graph.tsx
  frontend/src/components/__snapshots__/Graph.test.tsx.snap
  frontend/src/pages/PipelineDetails.test.tsx
  frontend/src/pages/PipelineDetails.tsx
  frontend/src/pages/__snapshots__/PipelineDetails.test.tsx.snap
Labels: approved, area/front-end, lgtm, size/XXL

#401 Removed unused docs directory including OWNERS file and images.
  docs/OWNERS
  docs/images/cm.png
  docs/images/job.png
  docs/images/metric.png
  docs/images/predict.png
  docs/images/roc.png
  docs/images/run.png
Labels: approved, lgtm, size/S

#335 added component with tf slim model generator and pipeline adjustments
  contrib/components/openvino/model_convert/README.md
  contrib/components/openvino/model_convert/containers/Dockerfile
  contrib/components/openvino/model_convert/containers/convert_model.py
  contrib/components/openvino/tf-slim/README.md
  contrib/components/openvino/tf-slim/containers/Dockerfile
  contrib/components/openvino/tf-slim/containers/slim_model.py
  contrib/samples/openvino/model_optimizer/convert_model_pipeline.py
  contrib/samples/openvino/tf-slim/README.md
  contrib/samples/openvino/tf-slim/tf-slim.py
Labels: approved, lgtm, needs-ok-to-test, size/XL

#410 Clean up the resource after test finish
  test/presubmit-tests-with-pipeline-deployment.sh
Labels: approved, lgtm, size/XS

#423 Propagate secret to kaniko
  sdk/python/kfp/compiler/_k8s_helper.py
Labels: approved, lgtm, size/S

#417 Failed the sample tests when it should
  test/sample-test/run_basic_test.py
  test/sample-test/run_kubeflow_test.py
  test/sample-test/run_tfx_test.py
  test/sample-test/run_xgboost_test.py
Labels: approved, lgtm, size/M

#427 Fix tb viewer test
  frontend/src/components/viewers/Tensorboard.test.tsx
Labels: approved, area/front-end, lgtm, size/XS

#411 Fix for k8s dict parsing
  sdk/python/kfp/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
Labels: approved, lgtm, ok-to-test, size/S

#214 SDK/Components - Support for optional inputs
  sdk/python/kfp/components/_components.py
  sdk/python/kfp/components/_structures.py
  sdk/python/tests/components/test_components.py
Labels: approved, area/sdk/components, lgtm, size/L

#396 SDK/Components/PythonContainerOp - Switch from dict to ComponentSpec
  sdk/python/kfp/compiler/_component_builder.py
Labels: approved, area/sdk/components/python_container_op, lgtm, size/M

#425 SDK/Client - Removed import six
  sdk/python/kfp/_client.py
Labels: approved, area/sdk/client, lgtm, size/XS

#432 Testing - Fix Travis tests (SDK/Components)
  sdk/python/tests/components/test_components.py
Labels: approved, area/testing, lgtm, size/XS
