Repository kubeflow/pipelines, pull requests merged in 2019-05, with the labels that each got.

#1258 Changelog for v0.1.18
  CHANGELOG.md
Labels: approved, area/build-release, lgtm, size/M

#1261 Properly alternate sorting in PagedTable between ascending and descending
  frontend/src/components/viewers/PagedTable.test.tsx
  frontend/src/components/viewers/PagedTable.tsx
  frontend/src/components/viewers/__snapshots__/PagedTable.test.tsx.snap
Labels: approved, area/front-end, kind/bug, lgtm, size/L

#1262 Pulls most functions out of Status and into StatusUtils
  frontend/src/lib/StatusUtils.test.tsx
  frontend/src/lib/StatusUtils.ts
  frontend/src/lib/Utils.test.ts
  frontend/src/lib/Utils.ts
  frontend/src/lib/WorkflowParser.test.ts
  frontend/src/lib/WorkflowParser.ts
  frontend/src/pages/ExperimentList.test.tsx
  frontend/src/pages/ExperimentList.tsx
  frontend/src/pages/RunDetails.test.tsx
  frontend/src/pages/RunDetails.tsx
  frontend/src/pages/RunList.test.tsx
  frontend/src/pages/RunList.tsx
  frontend/src/pages/Status.test.tsx
  frontend/src/pages/Status.tsx
Labels: approved, area/front-end, kind/bug, lgtm, size/L

#1267 update the image in the samples to use the new component images
  test/postsubmit-tests-with-pipeline-deployment.sh
  test/sample-test/run_test.sh
Labels: approved, lgtm, size/M

#1280 Component Release 727c48c690c081b505c1f0979d11930bf1ef07c0
  component_sdk/python/setup.py
  components/dataflow/predict/component.yaml
  components/dataflow/tfdv/component.yaml
  components/dataflow/tfma/component.yaml
  components/dataflow/tft/component.yaml
  components/gcp/bigquery/query/component.yaml
  components/gcp/dataflow/launch_python/component.yaml
  components/gcp/dataflow/launch_template/component.yaml
  components/gcp/dataproc/create_cluster/component.yaml
  components/gcp/dataproc/delete_cluster/component.yaml
  components/gcp/dataproc/submit_hadoop_job/component.yaml
  components/gcp/dataproc/submit_hive_job/component.yaml
  components/gcp/dataproc/submit_pig_job/component.yaml
  components/gcp/dataproc/submit_pyspark_job/component.yaml
  components/gcp/dataproc/submit_spark_job/component.yaml
  components/gcp/dataproc/submit_sparksql_job/component.yaml
  components/gcp/ml_engine/batch_predict/component.yaml
  components/gcp/ml_engine/deploy/component.yaml
  components/gcp/ml_engine/train/component.yaml
  components/kubeflow/deployer/component.yaml
  components/kubeflow/dnntrainer/component.yaml
  components/kubeflow/launcher/kubeflow_tfjob_launcher_op.py
  components/kubeflow/launcher/src/train.template.yaml
  components/local/confusion_matrix/component.yaml
  components/local/roc/component.yaml
  samples/kubeflow-tf/kubeflow-training-classification.py
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
  samples/xgboost-spark/xgboost-training-cm.py
  sdk/python/setup.py
Labels: approved, lgtm, size/M

#1172 Automated the component image release script
  components/release.sh
Labels: approved, area/build-release, lgtm, size/M

#1282 Update component yaml reference to eb830cd73ca148e5a1a6485a9374c2dc068314bc
  components/gcp/bigquery/query/README.md
  components/gcp/bigquery/query/sample.ipynb
  components/gcp/dataflow/launch_python/README.md
  components/gcp/dataflow/launch_python/sample.ipynb
  components/gcp/dataflow/launch_template/README.md
  components/gcp/dataflow/launch_template/sample.ipynb
  components/gcp/dataproc/create_cluster/README.md
  components/gcp/dataproc/create_cluster/sample.ipynb
  components/gcp/dataproc/delete_cluster/README.md
  components/gcp/dataproc/delete_cluster/sample.ipynb
  components/gcp/dataproc/submit_hadoop_job/README.md
  components/gcp/dataproc/submit_hadoop_job/sample.ipynb
  components/gcp/dataproc/submit_hive_job/README.md
  components/gcp/dataproc/submit_hive_job/sample.ipynb
  components/gcp/dataproc/submit_pig_job/README.md
  components/gcp/dataproc/submit_pig_job/sample.ipynb
  components/gcp/dataproc/submit_pyspark_job/README.md
  components/gcp/dataproc/submit_pyspark_job/sample.ipynb
  components/gcp/dataproc/submit_spark_job/README.md
  components/gcp/dataproc/submit_spark_job/sample.ipynb
  components/gcp/dataproc/submit_sparksql_job/README.md
  components/gcp/dataproc/submit_sparksql_job/sample.ipynb
  components/gcp/ml_engine/batch_predict/README.md
  components/gcp/ml_engine/batch_predict/sample.ipynb
  components/gcp/ml_engine/deploy/README.md
  components/gcp/ml_engine/deploy/sample.ipynb
  components/gcp/ml_engine/train/README.md
  components/gcp/ml_engine/train/sample.ipynb
  components/ibm-components/ffdl/serve/README.md
  components/ibm-components/ffdl/train/README.md
  samples/arena-samples/README.md
  samples/ibm-samples/ffdl-seldon/ffdl_pipeline.ipynb
  samples/ibm-samples/ffdl-seldon/ffdl_pipeline.py
  samples/ibm-samples/watson/watson_train_serve_pipeline.py
  samples/kubeflow-tf/kubeflow-training-classification.py
  samples/resnet-cmle/resnet-train-pipeline.py
  samples/tfx/taxi-cab-classification-pipeline.py
  samples/xgboost-spark/xgboost-training-cm.py
  sdk/python/tests/components/test_components.py
Labels: approved, lgtm, size/L

#1281 Sets the background color for KFP pages
  frontend/src/index.tsx
Labels: approved, area/front-end, kind/bug, lgtm, size/XS

#1276 Add SageMaker components and example pipeline
  components/aws/sagemaker/Dockerfile
  components/aws/sagemaker/batch_transform/component.yaml
  components/aws/sagemaker/batch_transform/src/batch_transform.py
  components/aws/sagemaker/common/__init__.py
  components/aws/sagemaker/common/_utils.py
  components/aws/sagemaker/deploy/component.yaml
  components/aws/sagemaker/deploy/src/deploy.py
  components/aws/sagemaker/model/component.yaml
  components/aws/sagemaker/model/src/create_model.py
  components/aws/sagemaker/train/component.yaml
  components/aws/sagemaker/train/src/train.py
  samples/aws-samples/mnist-kmeans-sagemaker/README.md
  samples/aws-samples/mnist-kmeans-sagemaker/mnist-classification-pipeline.py
Labels: approved, lgtm, needs-ok-to-test, size/XL

#1272 spark components
  components/ibm-components/spark/data_preprocess_spark/Dockerfile
  components/ibm-components/spark/data_preprocess_spark/component.yaml
  components/ibm-components/spark/data_preprocess_spark/src/data_preprocess_spark.py
  components/ibm-components/spark/train_spark/Dockerfile
  components/ibm-components/spark/train_spark/component.yaml
  components/ibm-components/spark/train_spark/src/spark-submit.sh
  components/ibm-components/spark/train_spark/src/train_spark.py
  components/ibm-components/spark/train_spark/src/wrapper.py
Labels: approved, lgtm, size/XXL

#1090 Retaining the component url, digest or tag when loading
  sdk/python/kfp/components/_component_store.py
  sdk/python/kfp/components/_components.py
Labels: approved, area/sdk/components, lgtm, size/S

#1279 keep the api image name consistent between the presubmit test and staging
  test/deploy-pipeline.sh
  test/presubmit-tests-with-pipeline-deployment.sh
Labels: approved, lgtm, size/XS

#1274 Adds a toggle between one-off and recurring runs to NewRun page
  frontend/src/pages/NewRun.test.tsx
  frontend/src/pages/NewRun.tsx
  frontend/src/pages/__snapshots__/NewRun.test.tsx.snap
  test/frontend-integration-test/helloworld.spec.js
Labels: approved, area/front-end, kind/feature, lgtm, size/XXL

#1268 make pending timeout customizable
  components/arena/docker/arena_launcher.py
  components/arena/python/arena/_arena_distributed_tf_op.py
  components/arena/python/arena/_arena_mpi_op.py
  components/arena/python/arena/_arena_standalone_op.py
Labels: approved, lgtm, size/S

#901 Allow to specify informers namespace in persistence agent
  backend/src/agent/persistence/main.go
Labels: approved, lgtm, ok-to-test, size/S

#1278 Frontend - Add support for artifacts stored in S3
  frontend/server/server.ts
  frontend/src/lib/WorkflowParser.test.ts
  frontend/src/lib/WorkflowParser.ts
Labels: approved, lgtm, ok-to-test, size/M

#1283 Components - Updating component versions in samples during release
  components/release.sh
Labels: approved, area/build-release, lgtm, size/S

#1207 SDK/Client - Supporting pipeline packages with multiple files
  sdk/python/kfp/_client.py
Labels: approved, area/sdk/client, lgtm, size/M

#1286 Add AWS EMR and Athena components
  components/aws/athena/Dockerfile
  components/aws/athena/query/component.yaml
  components/aws/athena/query/src/query.py
  components/aws/emr/Dockerfile
  components/aws/emr/common/__init__.py
  components/aws/emr/common/_utils.py
  components/aws/emr/create_cluster/component.yaml
  components/aws/emr/create_cluster/src/create_cluster.py
  components/aws/emr/delete_cluster/component.yaml
  components/aws/emr/delete_cluster/src/delete_cluster.py
  components/aws/emr/submit_pyspark_job/component.yaml
  components/aws/emr/submit_pyspark_job/src/submit_pyspark_job.py
  components/aws/emr/submit_spark_job/component.yaml
  components/aws/emr/submit_spark_job/src/submit_spark_job.py
  samples/aws-samples/titanic-survival-prediction/README.md
  samples/aws-samples/titanic-survival-prediction/titanic-survival-prediction.py
Labels: approved, lgtm, size/XL

#1290 SDK - Renamed ModelBase.from_struct/to_struct to from_dict/to_dict
  sdk/python/kfp/compiler/_component_builder.py
  sdk/python/kfp/components/_components.py
  sdk/python/kfp/components/_python_op.py
  sdk/python/kfp/components/modelbase.py
  sdk/python/tests/components/test_graph_components.py
  sdk/python/tests/components/test_structure_model_base.py
Labels: approved, area/sdk/components, lgtm, size/L

#1295 add nuclio components (to build/deploy, delete, invoke functions)
  components/nuclio/README.md
  components/nuclio/delete/component.yaml
  components/nuclio/deploy/component.yaml
  components/nuclio/invoker/component.yaml
Labels: approved, area/components, lgtm, ok-to-test, size/L

#1296 changelog for v0.1.19
  CHANGELOG.md
Labels: approved, lgtm, size/M

#1291 SDK - Failing faster in python_op tests
  sdk/python/tests/components/test_python_op.py
Labels: approved, area/testing, lgtm, size/XS

#1299 Add -p to mkdir in quickstart
  samples/notebooks/quickstart.ipynb
Labels: approved, area/samples/notebooks, kind/bug, lgtm, size/XS

#1285 Make confusion_matrix and roc generic
  components/local/confusion_matrix/src/confusion_matrix.py
  components/local/roc/src/roc.py
Labels: approved, lgtm, size/S

#1275 Tests/Travis - Simplified the Python SDK package installation
  .travis.yml
Labels: approved, area/testing, lgtm, size/XS

#1277 Release - Simplified python package building
  .cloudbuild.yaml
Labels: approved, area/build-release, lgtm, size/S

#1289 Backend - Marking auto-added artifacts as optional
  WORKSPACE
  backend/src/apiserver/resource/resource_manager.go
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#1302 Update quickstart sample
  samples/notebooks/Local Development Quickstart.ipynb
Labels: approved, lgtm, size/S

#1300 Fix PipelineParam pattern bug
  sdk/python/kfp/dsl/_pipeline_param.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/param_substitutions.py
  sdk/python/tests/compiler/testdata/param_substitutions.yaml
Labels: approved, lgtm, needs-ok-to-test, size/L

#1269 support tolerations for ContainerOps
  sdk/python/kfp/compiler/_op_to_template.py
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/tolerations.yaml
Labels: approved, lgtm, ok-to-test, size/L

#1298 Remove cops and rops pipeline attributes
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/dsl/_pipeline.py
Labels: approved, lgtm, needs-ok-to-test, size/M

#1308 expose namespace config for persistent agent
  backend/Dockerfile.persistenceagent
Labels: approved, lgtm, size/XS

#1309 expose namespace config for scheduled workflow
  backend/Dockerfile.scheduledworkflow
Labels: approved, lgtm, size/XS

#1310 Shows link to Stackdriver logs if logs retrieval fails and cluster is running in GKE
  frontend/server/server.ts
  frontend/src/lib/Apis.ts
  frontend/src/pages/RunDetails.test.tsx
  frontend/src/pages/RunDetails.tsx
  frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
Labels: approved, area/front-end, lgtm, size/XXL

#1311 Testing - Clean up the Argo controller that was used to build images
  test/install-argo.sh
  test/postsubmit-tests-with-pipeline-deployment.sh
  test/presubmit-tests-with-pipeline-deployment.sh
Labels: approved, area/testing, lgtm, size/S

#1312 Adding myself to test owners
  test/OWNERS
Labels: approved, area/testing, lgtm, size/XS

#1297 SDK - Stopped hard-coding artifact storage configuration in the pipeline packages
  sdk/python/kfp/compiler/_op_to_template.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/basic.yaml
  sdk/python/tests/compiler/testdata/coin.yaml
  sdk/python/tests/compiler/testdata/compose.yaml
  sdk/python/tests/compiler/testdata/default_value.yaml
  sdk/python/tests/compiler/testdata/imagepullsecret.yaml
  sdk/python/tests/compiler/testdata/immediate_value.yaml
  sdk/python/tests/compiler/testdata/param_substitutions.yaml
  sdk/python/tests/compiler/testdata/pipelineparams.yaml
  sdk/python/tests/compiler/testdata/recursive_do_while.yaml
  sdk/python/tests/compiler/testdata/recursive_while.yaml
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
  sdk/python/tests/compiler/testdata/retry.yaml
  sdk/python/tests/compiler/testdata/sidecar.yaml
  sdk/python/tests/compiler/testdata/tolerations.yaml
  sdk/python/tests/compiler/testdata/volume.yaml
  sdk/python/tests/compiler/testdata/volume_snapshotop_rokurl.yaml
  sdk/python/tests/compiler/testdata/volume_snapshotop_sequential.yaml
  sdk/python/tests/compiler/testdata/volumeop_basic.yaml
  sdk/python/tests/compiler/testdata/volumeop_dag.yaml
  sdk/python/tests/compiler/testdata/volumeop_parallel.yaml
  sdk/python/tests/compiler/testdata/volumeop_sequential.yaml
Labels: approved, area/sdk, area/sdk/dsl/compiler, lgtm, size/XXL

#1314 Fix typo in ContainerOp contructor's help string
  sdk/python/kfp/dsl/_container_op.py
Labels: approved, lgtm, ok-to-test, size/XS

#1306 Add dsl support for preemptible vm/gpus
  sdk/python/kfp/gcp.py
Labels: approved, lgtm, size/S

#1315 update tf version to 1.12.1
  components/dataflow/predict/src/setup.py
  components/dataflow/tfdv/src/validation/setup.py
  components/dataflow/tfma/src/analysis/setup.py
  components/kubeflow/dnntrainer/src/setup.py
Labels: approved, lgtm, size/XS

#1305 kustomize kf pipeline
  manifests/README.md
  manifests/base/argo/kustomization.yaml
  manifests/base/argo/workflow-controller-configmap.yaml
  manifests/base/argo/workflow-controller-deployment.yaml
  manifests/base/argo/workflow-controller-role.yaml
  manifests/base/argo/workflow-controller-rolebinding.yaml
  manifests/base/argo/workflow-controller-sa.yaml
  manifests/base/crds/kustomization.yaml
  manifests/base/crds/scheduled-workflow-crd.yaml
  manifests/base/crds/viewer-crd.yaml
  manifests/base/crds/workflow-crd.yaml
  manifests/base/kustomization.yaml
  manifests/base/minio/kustomization.yaml
  manifests/base/minio/minio-artifact-secret.yaml
  manifests/base/minio/minio-deployment.yaml
  manifests/base/minio/minio-pvc.yaml
  manifests/base/minio/minio-service.yaml
  manifests/base/mysql/kustomization.yaml
  manifests/base/mysql/mysql-deployment.yaml
  manifests/base/mysql/mysql-pv-claim.yaml
  manifests/base/mysql/mysql-service.yaml
  manifests/base/pipeline/kustomization.yaml
  manifests/base/pipeline/ml-pipeline-apiserver-deployment.yaml
  manifests/base/pipeline/ml-pipeline-apiserver-role.yaml
  manifests/base/pipeline/ml-pipeline-apiserver-rolebinding.yaml
  manifests/base/pipeline/ml-pipeline-apiserver-sa.yaml
  manifests/base/pipeline/ml-pipeline-apiserver-service.yaml
  manifests/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml
  manifests/base/pipeline/ml-pipeline-persistenceagent-role.yaml
  manifests/base/pipeline/ml-pipeline-persistenceagent-rolebinding.yaml
  manifests/base/pipeline/ml-pipeline-persistenceagent-sa.yaml
  manifests/base/pipeline/ml-pipeline-scheduledworkflow-deployment.yaml
  manifests/base/pipeline/ml-pipeline-scheduledworkflow-role.yaml
  manifests/base/pipeline/ml-pipeline-scheduledworkflow-rolebinding.yaml
  manifests/base/pipeline/ml-pipeline-scheduledworkflow-sa.yaml
  manifests/base/pipeline/ml-pipeline-ui-deployment.yaml
  manifests/base/pipeline/ml-pipeline-ui-role.yaml
  manifests/base/pipeline/ml-pipeline-ui-rolebinding.yaml
  manifests/base/pipeline/ml-pipeline-ui-sa.yaml
  manifests/base/pipeline/ml-pipeline-ui-service.yaml
  manifests/base/pipeline/ml-pipeline-viewer-crd-deployment.yaml
  manifests/base/pipeline/ml-pipeline-viewer-crd-role.yaml
  manifests/base/pipeline/ml-pipeline-viewer-crd-rolebinding.yaml
  manifests/base/pipeline/ml-pipeline-viewer-crd-sa.yaml
  manifests/base/pipeline/pipeline-runner-role.yaml
  manifests/base/pipeline/pipeline-runner-rolebinding.yaml
  manifests/base/pipeline/pipeline-runner-sa.yaml
  manifests/namespaced-install.yaml
  manifests/namespaced-install/README.md
  manifests/namespaced-install/kustomization.yaml
  manifests/namespaced-install/kustomizeconfig/namespace.yaml
  manifests/namespaced-install/ml-pipeline-persistenceagent-deployment-patch.yaml
  manifests/namespaced-install/ml-pipeline-scheduledworkflow-deployment-patch.yaml
  manifests/namespaced-install/namespace.yaml
  manifests/namespaced-install/workflow-controller-configmap.yaml
Labels: approved, lgtm, size/XXL

#1317 add patch for metric collection
  component_sdk/python/patches/http.patch
  components/gcp/container/Dockerfile
Labels: approved, lgtm, size/S

#1328 switch the release script from staging to test
  components/release.sh
Labels: lgtm, size/XS

#1322 ml-pipeline-test has a cb job
  test/postsubmit-tests-with-pipeline-deployment.sh
Labels: approved, lgtm, size/XS

#1330 bump kfp version in sdk
  sdk/python/setup.py
Labels: approved, lgtm, size/XS

#1323 Clean up repo - delete unnecessary top level folders
  .vscode/OWNERS
  .vscode/launch.json
  experimental/OWNERS
  experimental/bootstrapper/bootstrap.sh
  tools/OWNERS
  tools/collector/Dockerfile
  tools/collector/README.md
  tools/collector/app.yaml
Labels: approved, lgtm, size/L

#1325 Add proxy agent as optional kustomize component
  manifests/README.md
  manifests/base/kustomization.yaml
  manifests/base/proxy/kustomization.yaml
  manifests/base/proxy/proxy-deployment.yaml
  manifests/base/proxy/proxy-role.yaml
  manifests/base/proxy/proxy-rolebinding.yaml
  manifests/base/proxy/proxy-sa.yaml
  proxy/attempt-register-vm-on-proxy.sh
Labels: approved, lgtm, size/M

#1329 bump kfp version in component sdk
  component_sdk/python/setup.py
Labels: approved, lgtm, size/XS

#1331 Release c3235d725eb1d1eb06b5600a8291967aa6cf518f
  components/dataflow/predict/component.yaml
  components/dataflow/tfdv/component.yaml
  components/dataflow/tfma/component.yaml
  components/dataflow/tft/component.yaml
  components/gcp/bigquery/query/README.md
  components/gcp/bigquery/query/component.yaml
  components/gcp/bigquery/query/sample.ipynb
  components/gcp/dataflow/launch_python/README.md
  components/gcp/dataflow/launch_python/component.yaml
  components/gcp/dataflow/launch_python/sample.ipynb
  components/gcp/dataflow/launch_template/README.md
  components/gcp/dataflow/launch_template/component.yaml
  components/gcp/dataflow/launch_template/sample.ipynb
  components/gcp/dataproc/create_cluster/README.md
  components/gcp/dataproc/create_cluster/component.yaml
  components/gcp/dataproc/create_cluster/sample.ipynb
  components/gcp/dataproc/delete_cluster/README.md
  components/gcp/dataproc/delete_cluster/component.yaml
  components/gcp/dataproc/delete_cluster/sample.ipynb
  components/gcp/dataproc/submit_hadoop_job/README.md
  components/gcp/dataproc/submit_hadoop_job/component.yaml
  components/gcp/dataproc/submit_hadoop_job/sample.ipynb
  components/gcp/dataproc/submit_hive_job/README.md
  components/gcp/dataproc/submit_hive_job/component.yaml
  components/gcp/dataproc/submit_hive_job/sample.ipynb
  components/gcp/dataproc/submit_pig_job/README.md
  components/gcp/dataproc/submit_pig_job/component.yaml
  components/gcp/dataproc/submit_pig_job/sample.ipynb
  components/gcp/dataproc/submit_pyspark_job/README.md
  components/gcp/dataproc/submit_pyspark_job/component.yaml
  components/gcp/dataproc/submit_pyspark_job/sample.ipynb
  components/gcp/dataproc/submit_spark_job/README.md
  components/gcp/dataproc/submit_spark_job/component.yaml
  components/gcp/dataproc/submit_spark_job/sample.ipynb
  components/gcp/dataproc/submit_sparksql_job/README.md
  components/gcp/dataproc/submit_sparksql_job/component.yaml
  components/gcp/dataproc/submit_sparksql_job/sample.ipynb
  components/gcp/ml_engine/batch_predict/README.md
  components/gcp/ml_engine/batch_predict/component.yaml
  components/gcp/ml_engine/batch_predict/sample.ipynb
  components/gcp/ml_engine/deploy/README.md
  components/gcp/ml_engine/deploy/component.yaml
  components/gcp/ml_engine/deploy/sample.ipynb
  components/gcp/ml_engine/train/README.md
  components/gcp/ml_engine/train/component.yaml
  components/gcp/ml_engine/train/sample.ipynb
  components/kubeflow/deployer/component.yaml
  components/kubeflow/dnntrainer/component.yaml
  components/kubeflow/launcher/kubeflow_tfjob_launcher_op.py
  components/kubeflow/launcher/src/train.template.yaml
  components/local/confusion_matrix/component.yaml
  components/local/roc/component.yaml
  samples/kubeflow-tf/kubeflow-training-classification.py
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
  samples/resnet-cmle/resnet-train-pipeline.py
  samples/tfx/taxi-cab-classification-pipeline.py
  samples/xgboost-spark/xgboost-training-cm.py
Labels: approved, lgtm, size/L

#1324 [Frontend] minio client in API server can be configured with environment variables
  frontend/server/server.ts
  manifests/namespaced-install.yaml
  manifests/namespaced-install/kustomization.yaml
  manifests/namespaced-install/ml-pipeline-ui-deployment-patch.yaml
Labels: approved, lgtm, ok-to-test, size/M

#1333 add argo install in postsubmit
  test/postsubmit-tests-with-pipeline-deployment.sh
Labels: approved, lgtm, size/XS

#1229 SDK - Removing unneeded uses of dsl.Pipeline
  sdk/python/kfp/components/_dsl_bridge.py
  sdk/python/tests/components/test_components.py
  sdk/python/tests/dsl/aws_extensions_tests.py
  sdk/python/tests/dsl/component_tests.py
  sdk/python/tests/dsl/container_op_tests.py
  sdk/python/tests/dsl/test_azure_extensions.py
Labels: approved, area/sdk, lgtm, size/L

#1064 [Feature] Supports parameterized S3Artifactory for Pipeline and ContainerOp in kfp package
  sdk/python/kfp/compiler/_k8s_helper.py
  sdk/python/kfp/compiler/_op_to_template.py
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/dsl/__init__.py
  sdk/python/kfp/dsl/_artifact_location.py
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/kfp/dsl/_pipeline.py
  sdk/python/kfp/dsl/_pipeline_param.py
  sdk/python/setup.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/artifact_location.py
  sdk/python/tests/compiler/testdata/artifact_location.yaml
  sdk/python/tests/dsl/artifact_location_tests.py
  sdk/python/tests/dsl/aws_extensions_tests.py
  sdk/python/tests/dsl/main.py
Labels: approved, lgtm, ok-to-test, size/XL

#1307 Add mpi job into arena launcher
  components/arena/docker/Dockerfile
  components/arena/docker/arena_launcher.py
  components/arena/docker/job_generator.py
  components/arena/docker/utils.py
  components/arena/python/arena/_arena_distributed_tf_op.py
  components/arena/python/arena/_arena_mpi_op.py
  components/arena/python/arena/_arena_standalone_op.py
  components/arena/python/build.sh
  components/arena/python/setup.py
  samples/arena-samples/README.md
  samples/arena-samples/mpi/README.md
  samples/arena-samples/mpi/choose_pipelines.jpg
  samples/arena-samples/mpi/demo.jpg
  samples/arena-samples/mpi/mpi_run.py
  samples/arena-samples/mpi/submit_run.jpg
  samples/arena-samples/mpi/upload_pipelines.jpg
Labels: approved, lgtm, size/XL

#1332 Removes redundant npm install from FE Dockerfile
  frontend/Dockerfile
Labels: approved, area/front-end, lgtm, size/XS

#1337 check if data and env format
  components/arena/docker/job_generator.py
Labels: approved, lgtm, size/S

#1336 update proxy image build path
  .cloudbuild.yaml
Labels: approved, lgtm, size/XS

#1341 rename sample_test to component_test and sample_test_v2 to sample_test
  test/component_test.yaml
  test/sample_test.yaml
  test/sample_test_v2.yaml
Labels: approved, lgtm, size/XL

#1335 SDK - Made description and name parameters optional in the @pipeline decorator
  sdk/python/kfp/dsl/_pipeline.py
Labels: approved, area/sdk/dsl, lgtm, size/XS

#1284 Adds metrics table to Compare page, creates Metric component
  frontend/src/components/Metric.test.tsx
  frontend/src/components/Metric.tsx
  frontend/src/components/__snapshots__/Metric.test.tsx.snap
  frontend/src/lib/CompareUtils.test.ts
  frontend/src/lib/CompareUtils.ts
  frontend/src/lib/MetricUtils.test.ts
  frontend/src/lib/MetricUtils.ts
  frontend/src/lib/RunUtils.ts
  frontend/src/pages/Compare.test.tsx
  frontend/src/pages/Compare.tsx
  frontend/src/pages/RunList.test.tsx
  frontend/src/pages/RunList.tsx
  frontend/src/pages/__snapshots__/Compare.test.tsx.snap
  frontend/src/pages/__snapshots__/RunList.test.tsx.snap
Labels: approved, area/front-end, lgtm, size/XXL

#1346 SDK/Compiler: Fix Ops after() method to handle multiple arguments
  sdk/python/kfp/dsl/_container_op.py
Labels: approved, lgtm, ok-to-test, size/XS

#1338 [kfp sdk] Added examples for ArtifactLocation, ResourceOp, VolumeOp, and Sidecar.
  samples/basic/artifact_location.py
  samples/basic/sidecar.py
Labels: approved, lgtm, ok-to-test, size/M

#1350 update kfp ui rbac permission
  manifests/base/pipeline/ml-pipeline-ui-role.yaml
Labels: approved, lgtm, size/S

#1348 Pretty print inputs and outputs json
  frontend/src/components/DetailsTable.test.tsx
  frontend/src/components/DetailsTable.tsx
  frontend/src/components/__snapshots__/DetailsTable.test.tsx.snap
  frontend/src/lib/WorkflowParser.ts
  frontend/src/pages/RunDetails.tsx
Labels: approved, area/front-end, lgtm, size/L

#1349 Trim the file extension from suggested pipeline names
  frontend/src/components/UploadPipelineDialog.test.tsx
  frontend/src/components/UploadPipelineDialog.tsx
Labels: approved, area/front-end, lgtm, size/S

#1347 Release components
  components/dataflow/predict/component.yaml
  components/dataflow/tfdv/component.yaml
  components/dataflow/tfma/component.yaml
  components/dataflow/tft/component.yaml
  components/gcp/bigquery/query/README.md
  components/gcp/bigquery/query/component.yaml
  components/gcp/bigquery/query/sample.ipynb
  components/gcp/dataflow/launch_python/README.md
  components/gcp/dataflow/launch_python/component.yaml
  components/gcp/dataflow/launch_python/sample.ipynb
  components/gcp/dataflow/launch_template/README.md
  components/gcp/dataflow/launch_template/component.yaml
  components/gcp/dataflow/launch_template/sample.ipynb
  components/gcp/dataproc/create_cluster/README.md
  components/gcp/dataproc/create_cluster/component.yaml
  components/gcp/dataproc/create_cluster/sample.ipynb
  components/gcp/dataproc/delete_cluster/README.md
  components/gcp/dataproc/delete_cluster/component.yaml
  components/gcp/dataproc/delete_cluster/sample.ipynb
  components/gcp/dataproc/submit_hadoop_job/README.md
  components/gcp/dataproc/submit_hadoop_job/component.yaml
  components/gcp/dataproc/submit_hadoop_job/sample.ipynb
  components/gcp/dataproc/submit_hive_job/README.md
  components/gcp/dataproc/submit_hive_job/component.yaml
  components/gcp/dataproc/submit_hive_job/sample.ipynb
  components/gcp/dataproc/submit_pig_job/README.md
  components/gcp/dataproc/submit_pig_job/component.yaml
  components/gcp/dataproc/submit_pig_job/sample.ipynb
  components/gcp/dataproc/submit_pyspark_job/README.md
  components/gcp/dataproc/submit_pyspark_job/component.yaml
  components/gcp/dataproc/submit_pyspark_job/sample.ipynb
  components/gcp/dataproc/submit_spark_job/README.md
  components/gcp/dataproc/submit_spark_job/component.yaml
  components/gcp/dataproc/submit_spark_job/sample.ipynb
  components/gcp/dataproc/submit_sparksql_job/README.md
  components/gcp/dataproc/submit_sparksql_job/component.yaml
  components/gcp/dataproc/submit_sparksql_job/sample.ipynb
  components/gcp/ml_engine/batch_predict/README.md
  components/gcp/ml_engine/batch_predict/component.yaml
  components/gcp/ml_engine/batch_predict/sample.ipynb
  components/gcp/ml_engine/deploy/README.md
  components/gcp/ml_engine/deploy/component.yaml
  components/gcp/ml_engine/deploy/sample.ipynb
  components/gcp/ml_engine/train/README.md
  components/gcp/ml_engine/train/component.yaml
  components/gcp/ml_engine/train/sample.ipynb
  components/kubeflow/deployer/component.yaml
  components/kubeflow/dnntrainer/component.yaml
  components/kubeflow/launcher/kubeflow_tfjob_launcher_op.py
  components/kubeflow/launcher/src/train.template.yaml
  components/local/confusion_matrix/component.yaml
  components/local/roc/component.yaml
  samples/kubeflow-tf/kubeflow-training-classification.py
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
  samples/resnet-cmle/resnet-train-pipeline.py
  samples/tfx/taxi-cab-classification-pipeline.py
  samples/xgboost-spark/xgboost-training-cm.py
Labels: approved, lgtm, size/L

#1256 Added the auto-generated python SDK docs
  docs/Makefile
  docs/OWNERS
  docs/conf.py
  docs/index.rst
  docs/make.bat
  docs/source/kfp.client.rst
  docs/source/kfp.compiler.rst
  docs/source/kfp.components.rst
  docs/source/kfp.components.structures.kubernetes.rst
  docs/source/kfp.components.structures.rst
  docs/source/kfp.dsl.rst
  docs/source/kfp.dsl.types.rst
  docs/source/kfp.extensions.rst
  docs/source/kfp.notebook.rst
  docs/source/kfp.rst
  docs/source/modules.rst
  sdk/python/requirements.txt
Labels: approved, area/sdk, lgtm, size/L

#1339 Add HTTP/HTTPS support in FE
  frontend/server/server.ts
  frontend/src/lib/WorkflowParser.test.ts
  frontend/src/lib/WorkflowParser.ts
Labels: approved, area/front-end, lgtm, ok-to-test, size/M

#1358 Update CHANGELOG.md
  CHANGELOG.md
Labels: approved, lgtm, size/M

#1226 SDK/DSL - ContainerOp.apply method now supports functions that do not return anything
  sdk/python/kfp/dsl/_container_op.py
Labels: approved, area/sdk/dsl, lgtm, size/XS

#1356 Fix docstring for _ops_group Condition
  sdk/python/kfp/dsl/_ops_group.py
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1366 Do not render primitives as json
  frontend/src/components/DetailsTable.test.tsx
  frontend/src/components/DetailsTable.tsx
  frontend/src/components/__snapshots__/DetailsTable.test.tsx.snap
Labels: approved, area/front-end, lgtm, size/L

#1367 SDK - Added the argo-models to requirements.txt
  sdk/python/requirements.txt
Labels: approved, area/sdk, kind/bug, lgtm, size/XS

#1209 SDK/Compiler - Added the ability to apply a function to all ops in a pipeline
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/dsl/_pipeline.py
  sdk/python/tests/compiler/compiler_tests.py
Labels: approved, area/sdk/dsl/compiler, lgtm, size/M

#1259 Fix watson train component
  components/ibm-components/watson/train/component.yaml
  components/ibm-components/watson/train/src/wml-train.py
  samples/ibm-samples/watson/README.md
Labels: approved, lgtm, needs-ok-to-test, size/M

#1386 Fix naming from sagamaker to sagemaker
  components/aws/sagemaker/deploy/component.yaml
  components/aws/sagemaker/model/component.yaml
  components/aws/sagemaker/train/component.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1393 expose configuration for setting the max number of tensorboard
  backend/Dockerfile.viewercontroller
  manifests/base/pipeline/ml-pipeline-viewer-crd-deployment.yaml
  manifests/namespaced-install.yaml
Labels: approved, lgtm, size/S

#1394 Cleanup code - Kaniko pod parameterization
  sdk/python/kfp/compiler/_component_builder.py
Labels: approved, lgtm, size/S

#1372 SDK - Capturing function dependencies when creating lightweight components
  sdk/python/kfp/components/_python_op.py
  sdk/python/setup.py
  sdk/python/tests/components/test_python_op.py
Labels: approved, area/sdk/components, lgtm, size/M

#1398 Added the link to the SDK reference docs to README.md
  README.md
Labels: approved, area/docs, lgtm, size/XS

#1400 Fix auto generated resource link for DSL
  sdk/python/kfp/_client.py
Labels: approved, lgtm, size/XS

#1404 Fix API package names and regenerate checked-in proto files.
  WORKSPACE
  backend/Dockerfile
  backend/api/BUILD.bazel
  backend/api/error.proto
  backend/api/experiment.proto
  backend/api/filter.proto
  backend/api/go_client/error.pb.go
  backend/api/go_client/experiment.pb.go
  backend/api/go_client/experiment.pb.gw.go
  backend/api/go_client/filter.pb.go
  backend/api/go_client/job.pb.go
  backend/api/go_client/job.pb.gw.go
  backend/api/go_client/parameter.pb.go
  backend/api/go_client/pipeline.pb.go
  backend/api/go_client/pipeline.pb.gw.go
  backend/api/go_client/pipeline_spec.pb.go
  backend/api/go_client/report.pb.go
  backend/api/go_client/report.pb.gw.go
  backend/api/go_client/resource_reference.pb.go
  backend/api/go_client/run.pb.go
  backend/api/go_client/run.pb.gw.go
  backend/api/go_http_client/experiment_model/protobuf_any.go
  backend/api/go_http_client/job_model/protobuf_any.go
  backend/api/go_http_client/pipeline_model/protobuf_any.go
  backend/api/go_http_client/run_model/api_run.go
  backend/api/go_http_client/run_model/protobuf_any.go
  backend/api/job.proto
  backend/api/parameter.proto
  backend/api/pipeline.proto
  backend/api/pipeline_spec.proto
  backend/api/report.proto
  backend/api/resource_reference.proto
  backend/api/run.proto
  backend/api/swagger/experiment.swagger.json
  backend/api/swagger/job.swagger.json
  backend/api/swagger/pipeline.swagger.json
  backend/api/swagger/run.swagger.json
  backend/src/apiserver/BUILD.bazel
  backend/test/initialization/BUILD.bazel
Labels: approved, lgtm, size/XL

#1406 Add doc for API
  backend/api/experiment.proto
  backend/api/generate_api.sh
  backend/api/go_http_client/experiment_client/experiment_service/create_experiment_parameters.go
  backend/api/go_http_client/experiment_client/experiment_service/delete_experiment_parameters.go
  backend/api/go_http_client/experiment_client/experiment_service/get_experiment_parameters.go
  backend/api/go_http_client/experiment_model/api_list_experiments_response.go
  backend/api/go_http_client/job_client/job_service/create_job_parameters.go
  backend/api/go_http_client/job_client/job_service/delete_job_parameters.go
  backend/api/go_http_client/job_client/job_service/disable_job_parameters.go
  backend/api/go_http_client/job_client/job_service/enable_job_parameters.go
  backend/api/go_http_client/job_client/job_service/get_job_parameters.go
  backend/api/go_http_client/job_model/api_cron_schedule.go
  backend/api/go_http_client/job_model/api_job.go
  backend/api/go_http_client/job_model/api_list_jobs_response.go
  backend/api/go_http_client/job_model/api_periodic_schedule.go
  backend/api/go_http_client/job_model/api_trigger.go
  backend/api/go_http_client/pipeline_model/api_pipeline.go
  backend/api/job.proto
  backend/api/pipeline.proto
  backend/api/swagger/experiment.swagger.json
  backend/api/swagger/job.swagger.json
  backend/api/swagger/kfp_api.html
  backend/api/swagger/kfp_api_single_file.swagger.json
  backend/api/swagger/pipeline.swagger.json
Labels: size/XXL

#1408 add single API swagger json file
  backend/api/swagger/kfp_api_single_file.swagger.json
Labels: size/XXL

#1377 Add HyperParameters back to SageMaker training job
  components/aws/sagemaker/common/_utils.py
Labels: approved, lgtm, size/XS

#1403 update DSL client documentation
  sdk/python/kfp/_client.py
Labels: approved, lgtm, size/XS

#1410 update the API doc description
  backend/api/generate_api.sh
  backend/api/swagger/kfp_api_single_file.swagger.json
Labels: approved, size/S
