Repository kubeflow/pipelines, pull requests merged in 2019-03, with the labels that each got.

#883 add missing dependency in bazel BUILD
  backend/src/apiserver/storage/BUILD.bazel
Labels: approved, lgtm, size/XS

#874 support .zip pipeline package
  backend/src/apiserver/server/test/arguments_tarball/arguments-parameters.yaml
  backend/src/apiserver/server/test/arguments_zip/arguments-parameters.zip
  backend/src/apiserver/server/test/empty_zip/empty.zip
  backend/src/apiserver/server/test/malformated_zip.zip
  backend/src/apiserver/server/test/non_yaml_zip/non_yaml_file.foo
  backend/src/apiserver/server/test/non_yaml_zip/non_yaml_file.zip
  backend/src/apiserver/server/util.go
  backend/src/apiserver/server/util_test.go
  backend/test/pipeline_api_test.go
  backend/test/resources/zip-arguments.tar.gz
  backend/test/resources/zip-arguments.zip
Labels: approved, lgtm, size/L

#877 Passing the environment variables to container op
  sdk/python/kfp/components/_dsl_bridge.py
  sdk/python/tests/components/test_components.py
Labels: approved, area/sdk/components, lgtm, size/S

#887 GCPcomponents yaml spec
  components/gcp/bigquery/query/component.yaml
  components/gcp/dataflow/launch_python/component.yaml
  components/gcp/dataflow/launch_template/component.yaml
  components/gcp/ml_engine/batch_predict/component.yaml
  components/gcp/ml_engine/deploy/component.yaml
  components/gcp/ml_engine/train/component.yaml
Labels: approved, lgtm, size/L

#859 apiserver glog uses -alsologtostderr
  backend/Dockerfile
  developer_guide.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#889 Added support for default values to load_component
  sdk/python/kfp/components/_components.py
  sdk/python/tests/components/test_components.py
Labels: approved, area/sdk/components, lgtm, size/S

#890 Added support for default values to Lightweight python components
  sdk/python/kfp/components/_python_op.py
  sdk/python/tests/components/test_python_op.py
Labels: approved, area/sdk/components, lgtm, size/S

#888 move integration test to sub dir
  backend/test/BUILD.bazel
  backend/test/integration/BUILD.bazel
  backend/test/integration/cli_test.go
  backend/test/integration/experiment_api_test.go
  backend/test/integration/flags.go
  backend/test/integration/job_api_test.go
  backend/test/integration/pipeline_api_test.go
  backend/test/integration/run_api_test.go
  backend/test/test_utils.go
  test/api-integration-test/run_test.sh
Labels: approved, lgtm, size/L

#896 Added license for google-cloud-bigtable
  components/third_party_licenses.csv
Labels: approved, lgtm, size/XS

#878 Dump job id and change output to /tmp/kfp/output
  component_sdk/python/kfp_component/google/dataflow/_common_ops.py
  component_sdk/python/kfp_component/google/dataflow/_launch_template.py
  component_sdk/python/tests/google/dataflow/test__launch_python.py
  component_sdk/python/tests/google/dataflow/test__launch_template.py
Labels: approved, lgtm, size/S

#892 Create experiment only if it's not exist.
  sdk/python/kfp/_client.py
Labels: approved, lgtm, size/S

#754 add katib studyjob launcher
  components/kubeflow/katib-launcher/Dockerfile
  components/kubeflow/katib-launcher/build_image.sh
  components/kubeflow/katib-launcher/kubeflow_katib_launcher_op.py
  components/kubeflow/katib-launcher/src/__init__.py
  components/kubeflow/katib-launcher/src/hp.template.yaml
  components/kubeflow/katib-launcher/src/launch_study_job.py
Labels: approved, lgtm, size/L

#897 Add markdown viewer
  frontend/mock-backend/model-output/metadata.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/CSSReset.tsx
  frontend/src/components/viewers/MarkdownViewer.test.tsx
  frontend/src/components/viewers/MarkdownViewer.tsx
  frontend/src/components/viewers/Viewer.ts
  frontend/src/components/viewers/ViewerContainer.tsx
  frontend/src/components/viewers/__snapshots__/MarkdownViewer.test.tsx.snap
  frontend/src/components/viewers/__snapshots__/ViewerContainer.test.tsx.snap
  frontend/src/lib/OutputArtifactLoader.test.ts
  frontend/src/lib/OutputArtifactLoader.ts
  frontend/src/pages/NewExperiment.test.tsx
  frontend/src/pages/RecurringRunDetails.test.tsx
  frontend/src/pages/RecurringRunsManager.test.tsx
  frontend/src/pages/__snapshots__/RecurringRunsManager.test.tsx.snap
Labels: approved, area/front-end, lgtm, size/XXL

#904 Deflake frontend e2e test
  test/frontend-integration-test/helloworld.spec.js
Labels: approved, area/front-end, area/testing, lgtm, size/XS

#895 Change viewer to markdown instead of html according to FE changes.
  component_sdk/python/kfp_component/core/_display.py
  component_sdk/python/tests/core/test__display.py
Labels: approved, lgtm, size/M

#886 add core types and type checking function
  sdk/python/kfp/dsl/_types.py
  sdk/python/tests/dsl/main.py
  sdk/python/tests/dsl/type_tests.py
Labels: approved, lgtm, size/L

#903 Support customized export TF model folder names.
  component_sdk/python/kfp_component/google/ml_engine/_deploy.py
  component_sdk/python/tests/google/ml_engine/test__deploy.py
Labels: approved, lgtm, size/M

#909 Create README.md
  samples/tfx-oss/README.md
Labels: approved, lgtm, size/M

#899 Add sample notebook and readme markdown for GCP components.
  components/gcp/bigquery/query/README.md
  components/gcp/bigquery/query/component.yaml
  components/gcp/bigquery/query/sample.ipynb
  components/gcp/dataflow/launch_python/README.md
  components/gcp/dataflow/launch_python/component.yaml
  components/gcp/dataflow/launch_python/sample.ipynb
  components/gcp/dataflow/launch_template/README.md
  components/gcp/dataflow/launch_template/component.yaml
  components/gcp/dataflow/launch_template/sample.ipynb
  components/gcp/ml_engine/batch_predict/README.md
  components/gcp/ml_engine/batch_predict/component.yaml
  components/gcp/ml_engine/batch_predict/sample.ipynb
  components/gcp/ml_engine/deploy/README.md
  components/gcp/ml_engine/deploy/component.yaml
  components/gcp/ml_engine/deploy/sample.ipynb
  components/gcp/ml_engine/train/README.md
  components/gcp/ml_engine/train/component.yaml
  components/gcp/ml_engine/train/sample.ipynb
Labels: approved, lgtm, size/XXL

#914 Add online prediction instructions and print friendly msg in console.
  component_sdk/python/kfp_component/core/_display.py
  component_sdk/python/kfp_component/google/ml_engine/_create_version.py
  component_sdk/python/tests/core/test__display.py
Labels: approved, lgtm, size/M

#885 Add bigquery docstring and dump output path.
  component_sdk/python/kfp_component/google/bigquery/_query.py
  component_sdk/python/tests/google/bigquery/test__query.py
Labels: approved, lgtm, size/L

#891 Add component metadata
  sdk/python/kfp/dsl/__init__.py
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/kfp/dsl/_metadata.py
  sdk/python/kfp/dsl/_types.py
  sdk/python/tests/dsl/container_op_tests.py
  sdk/python/tests/dsl/main.py
  sdk/python/tests/dsl/metadata_tests.py
Labels: approved, lgtm, size/L

#913 Create TFX Example.ipynb
  samples/tfx-oss/TFX Example.ipynb
Labels: approved, lgtm, size/L

#917 fix license links
  components/third_party_licenses.csv
Labels: approved, lgtm, size/XS

#900 Configure artifact name and path separately
  sdk/python/kfp/compiler/compiler.py
Labels: approved, lgtm, size/XS

#921 Fix bugs in bigquery component
  component_sdk/python/kfp_component/google/bigquery/_query.py
  components/gcp/bigquery/query/component.yaml
Labels: approved, lgtm, size/S

#916 Update README.md
  samples/tfx-oss/README.md
Labels: approved, lgtm, size/XS

#884 Record TFX output artifacts in Metadata store
  .travis.yml
  BUILD.bazel
  WORKSPACE
  backend/Dockerfile
  backend/src/apiserver/BUILD.bazel
  backend/src/apiserver/client_manager.go
  backend/src/apiserver/main.go
  backend/src/apiserver/metadata/BUILD.bazel
  backend/src/apiserver/metadata/metadata_store.go
  backend/src/apiserver/metadata/metadata_store_test.go
  backend/src/apiserver/resource/client_manager_fake.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/storage/BUILD.bazel
  backend/src/apiserver/storage/run_store.go
  backend/src/apiserver/storage/run_store_test.go
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#905 Pass meta to containerop and pipeline
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/components/_dsl_bridge.py
  sdk/python/kfp/dsl/_component.py
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/kfp/dsl/_metadata.py
  sdk/python/kfp/dsl/_pipeline.py
  sdk/python/kfp/dsl/_types.py
  sdk/python/tests/dsl/component_tests.py
  sdk/python/tests/dsl/metadata_tests.py
  sdk/python/tests/dsl/pipeline_tests.py
  sdk/python/tests/dsl/type_tests.py
Labels: approved, lgtm, size/L

#923 Fixed small bug in DSL code that generates unique names for ops
  sdk/python/kfp/dsl/_pipeline.py
Labels: approved, area/sdk, lgtm, size/XS

#925 update changelog for 0.1.12
  CHANGELOG.md
Labels: approved, lgtm, size/M

#716 SDK/Components - Added naming.generate_unique_name_conversion_table
  sdk/python/kfp/components/_components.py
  sdk/python/kfp/components/_dsl_bridge.py
  sdk/python/kfp/components/_naming.py
Labels: approved, area/sdk/components, lgtm, size/M

#931 Added support for loading zip-packed components
  sdk/python/kfp/components/_component_store.py
  sdk/python/kfp/components/_components.py
  sdk/python/tests/components/test_components.py
  sdk/python/tests/components/test_data/python_add.component.zip
Labels: approved, area/sdk/components, lgtm, size/M

#922 Improved the TFX OSS notebook and README
  samples/tfx-oss/README.md
  samples/tfx-oss/TFX Example.ipynb
Labels: approved, area/samples/notebooks, lgtm, size/M

#932 Add notebook instructions on how to query ML Metadata for output artifacts
  samples/tfx-oss/TFX Example.ipynb
Labels: approved, lgtm, size/M

#933 Keras - Train classifier: Changed the types to conform to the chosen type system
  components/sample/keras/train_classifier/component.yaml
Labels: approved, area/components, lgtm, size/S

#915 Add Tommy as the approver for the IBM components and samples.
  components/ibm-components/OWNERS
  samples/ibm-samples/OWNERS
Labels: approved, lgtm, ok-to-test, size/XS

#937 Fixed typo: Replaced cencus with census
  components/gcp/ml_engine/batch_predict/README.md
  components/gcp/ml_engine/batch_predict/sample.ipynb
  components/gcp/ml_engine/deploy/README.md
  components/gcp/ml_engine/deploy/sample.ipynb
  components/gcp/ml_engine/train/README.md
  components/gcp/ml_engine/train/sample.ipynb
Labels: approved, area/samples/notebooks, lgtm, size/S

#943 SDK/DSL/Compiler - Fixed compilation when using ContainerOp.after
  sdk/python/kfp/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
Labels: approved, area/sdk/dsl/compiler, lgtm, size/S

#935 Add code formatting to markdown viewer
  frontend/src/CSSReset.tsx
  frontend/src/components/viewers/MarkdownViewer.tsx
  frontend/src/components/viewers/__snapshots__/MarkdownViewer.test.tsx.snap
Labels: approved, area/front-end, lgtm, size/M

#956 Add dataproc component yaml files
  components/gcp/dataproc/create_cluster/component.yaml
  components/gcp/dataproc/delete_cluster/component.yaml
  components/gcp/dataproc/submit_hadoop_job/component.yaml
  components/gcp/dataproc/submit_hive_job/component.yaml
  components/gcp/dataproc/submit_pig_job/component.yaml
  components/gcp/dataproc/submit_pyspark_job/component.yaml
  components/gcp/dataproc/submit_spark_job/component.yaml
  components/gcp/dataproc/submit_sparksql_job/component.yaml
Labels: approved, lgtm, size/XL

#952 Fixing the broken links for components source code in XGBoost Spark P…
  samples/xgboost-spark/README.md
Labels: approved, lgtm, size/S

#962 Set default values for payload objects in case of empty.
  component_sdk/python/kfp_component/google/dataproc/_submit_hadoop_job.py
  component_sdk/python/kfp_component/google/dataproc/_submit_hive_job.py
  component_sdk/python/kfp_component/google/dataproc/_submit_pig_job.py
  component_sdk/python/kfp_component/google/dataproc/_submit_pyspark_job.py
  component_sdk/python/kfp_component/google/dataproc/_submit_spark_job.py
  component_sdk/python/kfp_component/google/dataproc/_submit_sparksql_job.py
Labels: approved, lgtm, size/S

#966 Add missing main_class arg to spark job and set default values.
  component_sdk/python/kfp_component/google/dataproc/_submit_spark_job.py
  components/gcp/dataproc/submit_hadoop_job/component.yaml
  components/gcp/dataproc/submit_spark_job/component.yaml
Labels: approved, lgtm, size/S

#954 helper fn to add az secrets to container
  sdk/python/kfp/azure.py
  sdk/python/tests/dsl/test_azure_extensions.py
Labels: approved, lgtm, needs-ok-to-test, size/L

#967 Fix cancellation bug for dataproc job.
  component_sdk/python/kfp_component/core/_kfp_execution_context.py
  component_sdk/python/kfp_component/google/dataproc/_client.py
  component_sdk/python/kfp_component/google/dataproc/_submit_job.py
  component_sdk/python/tests/google/dataproc/test__submit_job.py
Labels: approved, lgtm, size/M

#971 Add documentation and sample notebook for dataproc components.
  component_sdk/python/kfp_component/google/dataproc/_submit_spark_job.py
  components/gcp/dataproc/create_cluster/README.md
  components/gcp/dataproc/create_cluster/sample.ipynb
  components/gcp/dataproc/delete_cluster/README.md
  components/gcp/dataproc/delete_cluster/sample.ipynb
  components/gcp/dataproc/submit_hadoop_job/README.md
  components/gcp/dataproc/submit_hadoop_job/sample.ipynb
  components/gcp/dataproc/submit_hive_job/README.md
  components/gcp/dataproc/submit_hive_job/sample.ipynb
  components/gcp/dataproc/submit_pig_job/README.md
  components/gcp/dataproc/submit_pig_job/sample.ipynb
  components/gcp/dataproc/submit_pyspark_job/README.md
  components/gcp/dataproc/submit_pyspark_job/sample.ipynb
  components/gcp/dataproc/submit_spark_job/README.md
  components/gcp/dataproc/submit_spark_job/component.yaml
  components/gcp/dataproc/submit_spark_job/sample.ipynb
  components/gcp/dataproc/submit_sparksql_job/README.md
  components/gcp/dataproc/submit_sparksql_job/sample.ipynb
Labels: approved, lgtm, size/XXL

#950 Watson Openscale Components to manage models
  components/ibm-components/watson/manage/monitor_fairness/Dockerfile
  components/ibm-components/watson/manage/monitor_fairness/component.yaml
  components/ibm-components/watson/manage/monitor_fairness/src/monitor_fairness.py
  components/ibm-components/watson/manage/monitor_quality/Dockerfile
  components/ibm-components/watson/manage/monitor_quality/component.yaml
  components/ibm-components/watson/manage/monitor_quality/src/monitor_quality.py
  components/ibm-components/watson/manage/subscribe/Dockerfile
  components/ibm-components/watson/manage/subscribe/component.yaml
  components/ibm-components/watson/manage/subscribe/src/subscribe.py
Labels: approved, lgtm, size/L

#972 Fix sample test failure because of the type information in the pipelineparam
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/dsl/_metadata.py
  sdk/python/kfp/dsl/_pipeline_param.py
  sdk/python/tests/dsl/pipeline_param_tests.py
Labels: approved, lgtm, size/M

#975 Add unit tests pipelineparam
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/dsl/_metadata.py
  sdk/python/kfp/dsl/_pipeline_param.py
  sdk/python/tests/dsl/metadata_tests.py
  sdk/python/tests/dsl/pipeline_param_tests.py
Labels: approved, lgtm, size/L

#991 Ignore not found error in delete cluster
  component_sdk/python/kfp_component/google/dataproc/_delete_cluster.py
  component_sdk/python/tests/google/dataproc/test__delete_cluster.py
Labels: approved, lgtm, size/S

#978 well-defined parameter types
  sdk/python/kfp/dsl/_pipeline_param.py
  sdk/python/kfp/dsl/_types.py
  sdk/python/tests/components/test_components.py
  sdk/python/tests/dsl/component_tests.py
  sdk/python/tests/dsl/type_tests.py
Labels: approved, lgtm, size/L

#986 Add job_dir.txt as output files of CMLE trainning job.
  component_sdk/python/kfp_component/google/ml_engine/_create_job.py
Labels: approved, lgtm, size/XS

#985 Improve dataflow job to use GCS to keep temp job states.
  component_sdk/python/kfp_component/google/dataflow/_client.py
  component_sdk/python/kfp_component/google/dataflow/_common_ops.py
  component_sdk/python/kfp_component/google/dataflow/_launch_python.py
  component_sdk/python/kfp_component/google/dataflow/_launch_template.py
  component_sdk/python/tests/google/dataflow/test__launch_python.py
  component_sdk/python/tests/google/dataflow/test__launch_template.py
Labels: approved, lgtm, size/L

#987 Update component.yaml for dataflow and cmle with recent changes.
  components/gcp/bigquery/query/component.yaml
  components/gcp/dataflow/launch_python/component.yaml
  components/gcp/dataflow/launch_template/component.yaml
  components/gcp/dataproc/create_cluster/component.yaml
  components/gcp/dataproc/delete_cluster/component.yaml
  components/gcp/dataproc/submit_hadoop_job/component.yaml
  components/gcp/dataproc/submit_hive_job/component.yaml
  components/gcp/dataproc/submit_pig_job/component.yaml
  components/gcp/dataproc/submit_pyspark_job/component.yaml
  components/gcp/dataproc/submit_spark_job/component.yaml
  components/gcp/dataproc/submit_sparksql_job/component.yaml
  components/gcp/ml_engine/batch_predict/component.yaml
  components/gcp/ml_engine/deploy/component.yaml
  components/gcp/ml_engine/train/component.yaml
Labels: approved, lgtm, size/L

#984 Add component.yaml to every ibm-components
  components/ibm-components/commons/config/component.yaml
  components/ibm-components/ffdl/serve/component.yaml
  components/ibm-components/ffdl/train/component.yaml
  components/ibm-components/watson/deploy/component.yaml
  components/ibm-components/watson/manage/monitor_fairness/component.yaml
  components/ibm-components/watson/manage/monitor_quality/component.yaml
  components/ibm-components/watson/manage/subscribe/component.yaml
  components/ibm-components/watson/store/component.yaml
  components/ibm-components/watson/train/component.yaml
Labels: approved, lgtm, ok-to-test, size/L

#968 Add optional pipeline_id to run_pipeline api
  sdk/python/kfp/_client.py
Labels: approved, lgtm, size/S

#976 Added the component name to the docstring
  sdk/python/kfp/components/_components.py
  sdk/python/tests/components/test_components.py
Labels: approved, area/sdk/components, lgtm, size/XS

#994 use pending commit id for cluster and source code name
  test/deploy-kubeflow.sh
  test/test-prep.sh
Labels: approved, lgtm, size/XS

#1006 Fix dataflow and mlengine samples with recent changes
  components/gcp/dataflow/launch_python/README.md
  components/gcp/dataflow/launch_python/sample.ipynb
  components/gcp/dataflow/launch_template/README.md
  components/gcp/dataflow/launch_template/sample.ipynb
  components/gcp/ml_engine/train/README.md
  components/gcp/ml_engine/train/sample.ipynb
Labels: approved, lgtm, size/L

#1002 Updating the description for model_uid param
  components/ibm-components/watson/deploy/component.yaml
Labels: approved, lgtm, size/XS

#981 Add instruction on building viewer CRD controller image
  developer_guide.md
Labels: approved, lgtm, size/XS

#997 Adjustments for OpenVINO v5
  contrib/components/openvino/model_convert/containers/Dockerfile
  contrib/components/openvino/predict/README.md
  contrib/components/openvino/predict/containers/Dockerfile
  contrib/components/openvino/predict/containers/classes.py
  contrib/components/openvino/predict/containers/predict.py
  contrib/components/openvino/tf-slim/containers/Dockerfile
  contrib/samples/openvino/model_optimizer/convert_model_pipeline.py
  contrib/samples/openvino/predict/numpy_predict.py
  contrib/samples/openvino/tf-slim/README.md
  contrib/samples/openvino/tf-slim/tf-slim.py
Labels: approved, lgtm, ok-to-test, size/XXL

#1011 Update TFX Pipeline Example Readme
  samples/tfx-oss/README.md
Labels: approved, lgtm, needs-ok-to-test, size/S

#958 Add fake metadata store and fix tests.
  backend/README.md
  backend/src/apiserver/resource/BUILD.bazel
  backend/src/apiserver/resource/client_manager_fake.go
  backend/src/apiserver/storage/db.go
  backend/src/apiserver/storage/run_store.go
Labels: approved, lgtm, size/M

#1010 Update sidebar styling
  frontend/src/components/SideNav.tsx
  frontend/src/components/__snapshots__/SideNav.test.tsx.snap
Labels: approved, area/front-end, lgtm, size/XL

#1015 Fix hard-coded model export dir name
  component_sdk/python/kfp_component/google/ml_engine/_deploy.py
  component_sdk/python/tests/google/ml_engine/test__deploy.py
Labels: approved, lgtm, size/M

#1012 Fixed bug in docstring construction
  sdk/python/kfp/components/_components.py
Labels: approved, area/sdk/components, lgtm, size/XS

#1009 SDK/DSL/Compiler - Fixed handling of empty pipeline name
  sdk/python/kfp/compiler/compiler.py
Labels: approved, area/sdk/dsl/compiler, lgtm, size/XS

#528 Added the ability to terminate a run
  backend/api/generate_api.sh
  backend/api/go_client/run.pb.go
  backend/api/go_client/run.pb.gw.go
  backend/api/go_http_client/run_client/run_service/BUILD.bazel
  backend/api/go_http_client/run_client/run_service/run_service_client.go
  backend/api/go_http_client/run_client/run_service/terminate_run_parameters.go
  backend/api/go_http_client/run_client/run_service/terminate_run_responses.go
  backend/api/run.proto
  backend/api/swagger/run.swagger.json
  backend/src/apiserver/resource/BUILD.bazel
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/resource/workflow_fake.go
  backend/src/apiserver/server/run_server.go
  backend/src/apiserver/storage/BUILD.bazel
  backend/src/apiserver/storage/run_store.go
  backend/src/apiserver/storage/run_store_test.go
  backend/src/cmd/ml/cmd/run.go
  backend/src/common/client/api_server/run_client.go
  backend/src/common/client/api_server/run_client_fake.go
  backend/test/integration/run_api_test.go
  backend/test/resources/long-running.yaml
Labels: approved, lgtm, size/XXL

#1021 Release component image version f98ec68488cfbac022893a87c5bca083f03f2065
  components/gcp/bigquery/query/component.yaml
  components/gcp/dataflow/launch_python/component.yaml
  components/gcp/dataflow/launch_template/component.yaml
  components/gcp/dataproc/create_cluster/component.yaml
  components/gcp/dataproc/delete_cluster/component.yaml
  components/gcp/dataproc/submit_hadoop_job/component.yaml
  components/gcp/dataproc/submit_hive_job/component.yaml
  components/gcp/dataproc/submit_pig_job/component.yaml
  components/gcp/dataproc/submit_pyspark_job/component.yaml
  components/gcp/dataproc/submit_spark_job/component.yaml
  components/gcp/dataproc/submit_sparksql_job/component.yaml
  components/gcp/ml_engine/batch_predict/component.yaml
  components/gcp/ml_engine/deploy/component.yaml
  components/gcp/ml_engine/train/component.yaml
  components/kubeflow/launcher/kubeflow_tfjob_launcher_op.py
  components/kubeflow/launcher/src/train.template.yaml
  samples/kubeflow-tf/kubeflow-training-classification.py
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
  samples/resnet-cmle/resnet-train-pipeline.py
  samples/tfx/taxi-cab-classification-pipeline.py
  samples/xgboost-spark/xgboost-training-cm.py
Labels: approved, lgtm, size/M

#988 Add proxy agent runner for kubeflow pipeline
  proxy/Dockerfile
  proxy/OWNERS
  proxy/attempt-register-vm-on-proxy.sh
  proxy/get_proxy_url.py
  proxy/get_proxy_url_test.py
Labels: approved, lgtm, size/L

#1020 openvino demo pipeline documentation updates
  contrib/components/openvino/model_convert/README.md
  contrib/components/openvino/predict/containers/predict.py
  contrib/components/openvino/tf-slim/containers/slim_model.py
  contrib/samples/openvino/tf-slim/README.md
  contrib/samples/openvino/tf-slim/demo_pipeline1.png
  contrib/samples/openvino/tf-slim/demo_pipeline2.png
  contrib/samples/openvino/tf-slim/demo_pipeline3.png
  contrib/samples/openvino/tf-slim/tf-slim.py
Labels: approved, lgtm, ok-to-test, size/L

#1008 OpenVINO Model Server deployer
  contrib/components/openvino/ovms-deployer/README.md
  contrib/components/openvino/ovms-deployer/containers/Dockerfile
  contrib/components/openvino/ovms-deployer/containers/apply_template.py
  contrib/components/openvino/ovms-deployer/containers/classes.py
  contrib/components/openvino/ovms-deployer/containers/deploy.sh
  contrib/components/openvino/ovms-deployer/containers/evaluate.py
  contrib/components/openvino/ovms-deployer/containers/ovms.j2
  contrib/components/openvino/ovms-deployer/containers/requirements.txt
  contrib/samples/openvino/deployer/README.md
  contrib/samples/openvino/deployer/component.yaml
  contrib/samples/openvino/deployer/deployer.png
  contrib/samples/openvino/deployer/deployer.py
Labels: approved, lgtm, ok-to-test, size/XXL

#1028 Fix a missing precheck in create cluster component
  component_sdk/python/kfp_component/google/dataproc/_create_cluster.py
Labels: approved, lgtm, size/XS

#1023 Added the metadata property to ComponentSpec
  sdk/python/kfp/components/_structures.py
Labels: approved, area/sdk/components, lgtm, size/XS

#1032 Release components to include fix #1028.
  components/gcp/bigquery/query/component.yaml
  components/gcp/dataflow/launch_python/component.yaml
  components/gcp/dataflow/launch_template/component.yaml
  components/gcp/dataproc/create_cluster/component.yaml
  components/gcp/dataproc/delete_cluster/component.yaml
  components/gcp/dataproc/submit_hadoop_job/component.yaml
  components/gcp/dataproc/submit_hive_job/component.yaml
  components/gcp/dataproc/submit_pig_job/component.yaml
  components/gcp/dataproc/submit_pyspark_job/component.yaml
  components/gcp/dataproc/submit_spark_job/component.yaml
  components/gcp/dataproc/submit_sparksql_job/component.yaml
  components/gcp/ml_engine/batch_predict/component.yaml
  components/gcp/ml_engine/deploy/component.yaml
  components/gcp/ml_engine/train/component.yaml
  components/kubeflow/launcher/kubeflow_tfjob_launcher_op.py
  components/kubeflow/launcher/src/train.template.yaml
  samples/kubeflow-tf/kubeflow-training-classification.py
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
  samples/resnet-cmle/resnet-train-pipeline.py
  samples/tfx/taxi-cab-classification-pipeline.py
  samples/xgboost-spark/xgboost-training-cm.py
Labels: approved, lgtm, size/M

#1037 Pin the component.yaml version in all the samples.
  components/gcp/bigquery/query/README.md
  components/gcp/bigquery/query/sample.ipynb
  components/gcp/dataflow/launch_python/README.md
  components/gcp/dataflow/launch_python/sample.ipynb
  components/gcp/dataflow/launch_template/README.md
  components/gcp/dataflow/launch_template/sample.ipynb
  components/gcp/dataproc/create_cluster/README.md
  components/gcp/dataproc/create_cluster/sample.ipynb
  components/gcp/dataproc/delete_cluster/README.md
  components/gcp/dataproc/delete_cluster/sample.ipynb
  components/gcp/dataproc/submit_hadoop_job/README.md
  components/gcp/dataproc/submit_hadoop_job/sample.ipynb
  components/gcp/dataproc/submit_hive_job/README.md
  components/gcp/dataproc/submit_hive_job/sample.ipynb
  components/gcp/dataproc/submit_pig_job/README.md
  components/gcp/dataproc/submit_pig_job/sample.ipynb
  components/gcp/dataproc/submit_pyspark_job/README.md
  components/gcp/dataproc/submit_pyspark_job/sample.ipynb
  components/gcp/dataproc/submit_spark_job/README.md
  components/gcp/dataproc/submit_spark_job/sample.ipynb
  components/gcp/dataproc/submit_sparksql_job/README.md
  components/gcp/dataproc/submit_sparksql_job/sample.ipynb
  components/gcp/ml_engine/batch_predict/README.md
  components/gcp/ml_engine/batch_predict/sample.ipynb
  components/gcp/ml_engine/deploy/README.md
  components/gcp/ml_engine/deploy/sample.ipynb
  components/gcp/ml_engine/train/README.md
  components/gcp/ml_engine/train/sample.ipynb
Labels: approved, lgtm, size/L

#1030 Add more tests for metadata store.
  backend/src/apiserver/metadata/BUILD.bazel
  backend/src/apiserver/metadata/metadata_store.go
  backend/src/apiserver/metadata/metadata_store_test.go
  backend/src/apiserver/storage/BUILD.bazel
Labels: approved, lgtm, size/L

#1042 Revert "Register proxy agent using the service account endpoint"
  proxy/attempt-register-vm-on-proxy.sh
Labels: approved, lgtm, size/XS

#1041 changelog for v0.1.13
  CHANGELOG.md
Labels: approved, lgtm, size/M

#989 Update developer_guide.md
  developer_guide.md
Labels: approved, lgtm, ok-to-test, size/XS

#934 Keras - Train classifier: Improved the README.md
  components/sample/keras/train_classifier/README.md
Labels: approved, area/components, lgtm, size/M

#1004 SDK/Tests - Simplified type compatibility tests
  sdk/python/tests/components/test_components.py
Labels: approved, area/sdk, lgtm, size/XL

#1022 exposing type checking
  sdk/python/kfp/components/_components.py
  sdk/python/kfp/dsl/__init__.py
  sdk/python/kfp/dsl/_component.py
  sdk/python/kfp/dsl/_metadata.py
  sdk/python/kfp/dsl/types.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/components/test_components.py
  sdk/python/tests/dsl/component_tests.py
  sdk/python/tests/dsl/pipeline_tests.py
  sdk/python/tests/dsl/type_tests.py
Labels: approved, lgtm, size/S

#1014 Support recursions in a function
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/dsl/__init__.py
  sdk/python/kfp/dsl/_component.py
  sdk/python/kfp/dsl/_ops_group.py
  sdk/python/kfp/dsl/_pipeline.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/recursive.py
  sdk/python/tests/compiler/testdata/recursive.yaml
  sdk/python/tests/dsl/component_tests.py
  sdk/python/tests/dsl/ops_group_tests.py
Labels: approved, lgtm, size/XL

#855 dsl generate zip file
  samples/basic/condition.py
  samples/basic/exit_handler.py
  samples/basic/immediate_value.py
  samples/basic/parallel_join.py
  samples/basic/retry.py
  samples/basic/sequential.py
  samples/ibm-samples/ffdl-seldon/ffdl_pipeline.py
  samples/ibm-samples/watson/watson_train_serve_pipeline.py
  samples/kubeflow-tf/kubeflow-training-classification.py
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
  samples/notebooks/Lightweight Python components - basics.ipynb
  samples/resnet-cmle/resnet-train-pipeline.py
  samples/tfx/taxi-cab-classification-pipeline.py
  samples/xgboost-spark/xgboost-training-cm.py
  sdk/python/kfp/_client.py
  sdk/python/kfp/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  test/sample-test/run_test.sh
Labels: approved, lgtm, size/L

#1048 Fix compiler unit test bug
  sdk/python/tests/compiler/compiler_tests.py
Labels: approved, lgtm, size/XS

#1047 Fixed handling parameters with default values in task factory construction
  sdk/python/kfp/components/_components.py
  sdk/python/tests/components/test_components.py
Labels: approved, area/sdk/components, kind/bug, lgtm, size/M

#1005 upgrade ks in deployer to fix one block issue
  components/kubeflow/deployer/Dockerfile
Labels: approved, lgtm, size/S

#1043 Register proxy agent using the service account endpoint
  proxy/attempt-register-vm-on-proxy.sh
Labels: approved, lgtm, size/XS

#1054 add license file to proxy agent docker image
  proxy/Dockerfile
Labels: approved, lgtm, size/XS

#955 Add type check samples
  samples/notebooks/DSL Static Type Checking.ipynb
  sdk/python/kfp/_config.py
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/compiler/main.py
Labels: approved, lgtm, size/XL

#1016 Add a recursion sample
  samples/basic/recursion.py
  test/e2e_test_gke_v2.yaml
  test/sample-test/run_test.sh
Labels: approved, lgtm, size/M

#1056 add licenses for katib-launcher
  components/third_party_licenses.csv
Labels: approved, area/components, lgtm, size/XS

#879 Feature: sidecar for ContainerOp
  sdk/python/kfp/compiler/_k8s_helper.py
  sdk/python/kfp/compiler/_op_to_template.py
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/components/_dsl_bridge.py
  sdk/python/kfp/dsl/__init__.py
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/kfp/dsl/_pipeline_param.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/pipelineparams.py
  sdk/python/tests/compiler/testdata/pipelineparams.yaml
  sdk/python/tests/compiler/testdata/sidecar.py
  sdk/python/tests/compiler/testdata/sidecar.yaml
  sdk/python/tests/components/test_components.py
  sdk/python/tests/components/test_python_op.py
  sdk/python/tests/dsl/container_op_tests.py
  sdk/python/tests/dsl/pipeline_param_tests.py
Labels: approved, lgtm, ok-to-test, size/XXL

#939 Enable pipeline packages with multiple files
  backend/src/apiserver/server/test/arguments_tarball/arguments.tar.gz
  backend/src/apiserver/server/test/arguments_zip/arguments-parameters.zip
  backend/src/apiserver/server/test/pipeline_plus_component/component.yaml
  backend/src/apiserver/server/test/pipeline_plus_component/pipeline.yaml
  backend/src/apiserver/server/test/pipeline_plus_component/pipeline_plus_component.tar.gz
  backend/src/apiserver/server/test/pipeline_plus_component/pipeline_plus_component.zip
  backend/src/apiserver/server/util.go
  backend/src/apiserver/server/util_test.go
  backend/test/integration/pipeline_api_test.go
  backend/test/resources/arguments.pipeline.broken_file.zip
  backend/test/resources/arguments.pipeline.zip
Labels: approved, area/back-end, lgtm, size/L

#1057 SDK/Components - Handling public GCS URIs in load_component_from_url
  sdk/python/kfp/components/_components.py
Labels: approved, area/sdk/components, lgtm, size/XS

#1044 Allow passing comma-delimited column names
  components/dataflow/tfma/src/model_analysis.py
Labels: approved, area/components, lgtm, size/XS

#1059 Improve runtime graph exit-handler node name
  frontend/src/Css.tsx
  frontend/src/components/Graph.tsx
  frontend/src/components/__snapshots__/Graph.test.tsx.snap
  frontend/src/lib/WorkflowParser.test.ts
  frontend/src/lib/WorkflowParser.ts
Labels: approved, area/front-end, lgtm, size/L

#1063 Release 03/28/2019
  components/gcp/bigquery/query/component.yaml
  components/gcp/dataflow/launch_python/component.yaml
  components/gcp/dataflow/launch_template/component.yaml
  components/gcp/dataproc/create_cluster/component.yaml
  components/gcp/dataproc/delete_cluster/component.yaml
  components/gcp/dataproc/submit_hadoop_job/component.yaml
  components/gcp/dataproc/submit_hive_job/component.yaml
  components/gcp/dataproc/submit_pig_job/component.yaml
  components/gcp/dataproc/submit_pyspark_job/component.yaml
  components/gcp/dataproc/submit_spark_job/component.yaml
  components/gcp/dataproc/submit_sparksql_job/component.yaml
  components/gcp/ml_engine/batch_predict/component.yaml
  components/gcp/ml_engine/deploy/component.yaml
  components/gcp/ml_engine/train/component.yaml
  components/kubeflow/launcher/kubeflow_tfjob_launcher_op.py
  components/kubeflow/launcher/src/train.template.yaml
  samples/kubeflow-tf/kubeflow-training-classification.py
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
  samples/resnet-cmle/resnet-train-pipeline.py
  samples/tfx/taxi-cab-classification-pipeline.py
  samples/xgboost-spark/xgboost-training-cm.py
Labels: size/M

#1068 Fixed a bug in tarball handling
  backend/src/apiserver/server/util.go
  backend/src/apiserver/server/util_test.go
Labels: approved, area/back-end, lgtm, size/S

#1069 Add Bazel build/test to Travis run.
  .travis.yml
Labels: approved, lgtm, size/S

#996 add proxy agent image to cloud builder
  .cloudbuild.yaml
  .release.cloudbuild.yaml
Labels: approved, lgtm, size/S

#1046 remove jupyter hub link from UI
  frontend/src/components/SideNav.test.tsx
  frontend/src/components/SideNav.tsx
  frontend/src/components/__snapshots__/SideNav.test.tsx.snap
Labels: approved, lgtm, size/M

#1062 Allow bigquery component to export to table only
  component_sdk/python/kfp_component/google/bigquery/_query.py
  component_sdk/python/tests/google/bigquery/test__query.py
Labels: approved, lgtm, size/M

#995 Pin specific version of kubeflow instead of using master
  test/deploy-kubeflow.sh
Labels: approved, lgtm, size/XS
