Repository kubeflow/pipelines, pull requests merged in 2019-01, with the labels that each got.

#588 Deployment - Minikube support - Passing the platform parameter to kfctl
  test/presubmit-tests-with-pipeline-deployment.sh
Labels: approved, lgtm, size/XS

#589 Move backend unit tests to Travis
  .travis.yml
  test/backend-unit-test/Dockerfile
  test/backend-unit-test/OWNERS
  test/backend-unit-test/run_test.sh
  test/unit_test_gke.yaml
Labels: approved, lgtm, size/L

#599 First step to bring back CMLE sample.
  components/resnet-cmle/resnet/resnet_model/trainer/resnet_main.py
  sdk/python/kfp/gcp.py
Labels: approved, lgtm, size/XS

#607 Improve condition sample to demonstrate ==, >= and <.
  samples/basic/condition.py
Labels: approved, lgtm, size/M

#578 Add sample test without image build
  samples/kubeflow-tf/kubeflow-training-classification.py
  test/sample-test/run_kubeflow_test.py
  test/sample-test/run_test.sh
  test/sample_test_components.yaml
  test/sample_test_v2.yaml
Labels: approved, lgtm, size/XXL

#620 URLEncode instead of base64 encode the filter string
  backend/src/apiserver/server/list_request_util.go
  backend/src/apiserver/server/list_request_util_test.go
Labels: approved, lgtm, size/S

#598 Compare perf - pure components, disable ROC curve thumbnail animations
  frontend/src/components/CompareTable.tsx
  frontend/src/components/PlotCard.tsx
  frontend/src/components/viewers/ROCCurve.tsx
  frontend/src/components/viewers/__snapshots__/ROCCurve.test.tsx.snap
  frontend/src/pages/Compare.tsx
  frontend/src/pages/RunList.tsx
  frontend/src/pages/__snapshots__/Compare.test.tsx.snap
Labels: approved, area/front-end, lgtm, size/L

#622 Update sample notebook to clean up deployed models.
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
  sdk/python/kfp/_client.py
  test/sample-test/run_test.sh
Labels: approved, lgtm, size/XL

#628 Generate pipeline and job python client as part of SDK
  sdk/python/build.sh
Labels: approved, lgtm, size/XS

#630 Updates material-ui and react npm libraries
  frontend/package-lock.json
  frontend/package.json
  frontend/server/package-lock.json
  frontend/src/Css.tsx
  frontend/src/atoms/Input.test.tsx
  frontend/src/atoms/Input.tsx
  frontend/src/atoms/__snapshots__/BusyButton.test.tsx.snap
  frontend/src/atoms/__snapshots__/MD2Tabs.test.tsx.snap
  frontend/src/components/Trigger.tsx
  frontend/src/components/UploadPipelineDialog.tsx
  frontend/src/components/__snapshots__/Trigger.test.tsx.snap
  frontend/src/components/__snapshots__/UploadPipelineDialog.test.tsx.snap
  frontend/src/pages/NewExperiment.tsx
  frontend/src/pages/NewRun.test.tsx
  frontend/src/pages/NewRun.tsx
  frontend/src/pages/__snapshots__/NewExperiment.test.tsx.snap
  frontend/src/pages/__snapshots__/NewRun.test.tsx.snap
  frontend/src/pages/__snapshots__/RecurringRunsManager.test.tsx.snap
  frontend/src/pages/__snapshots__/RunList.test.tsx.snap
  frontend/src/pages/__snapshots__/Status.test.tsx.snap
Labels: approved, lgtm, size/XXL

#627 Fix gpu sample issues
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
Labels: approved, lgtm, size/L

#634 Expose pipeline/job API through setup.py
  sdk/python/setup.py
Labels: approved, lgtm, size/XS

#636 fix deploy model name conflict in case of concurrent notebook sample test
  test/sample-test/run_test.sh
Labels: approved, lgtm, size/XS

#633 Fix retrying logic which was causing persistenceagent to crash loop.
  backend/src/common/util/service.go
  backend/test/test_utils.go
Labels: approved, lgtm, size/M

#623 Support replacable arguments in command as well (besides arguments) in container op.
  samples/basic/condition.py
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/components/_components.py
  sdk/python/kfp/components/_dsl_bridge.py
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/tests/compiler/testdata/coin.py
  sdk/python/tests/compiler/testdata/coin.yaml
Labels: approved, lgtm, size/M

#635 Print sample test logs in case of exception throw
  test/sample-test/run_basic_test.py
  test/sample-test/run_kubeflow_test.py
  test/sample-test/run_tfx_test.py
  test/sample-test/run_xgboost_test.py
Labels: approved, lgtm, size/M

#632 Add resnet-cmle sample back. Update all component images.
  components/kubeflow/launcher/kubeflow_tfjob_launcher_op.py
  components/kubeflow/launcher/src/train.template.yaml
  samples/kubeflow-tf/kubeflow-training-classification.py
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
  samples/resnet-cmle/resnet-train-pipeline.py
  samples/tfx/taxi-cab-classification-pipeline.py
  samples/xgboost-spark/xgboost-training-cm.py
Labels: approved, lgtm, size/L

#639 Update WORKSPACE and BUILD files incoporating recent changes
  WORKSPACE
  backend/src/apiserver/model/BUILD.bazel
  backend/src/apiserver/storage/BUILD.bazel
  backend/src/crd/controller/viewer/BUILD.bazel
  backend/src/crd/controller/viewer/main.go
  backend/src/crd/controller/viewer/reconciler/BUILD.bazel
  backend/src/crd/pkg/apis/viewer/BUILD.bazel
  backend/src/crd/pkg/apis/viewer/v1alpha1/BUILD.bazel
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#644 Add changelog to pipeline repo
  CHANGELOG.md
Labels: approved, lgtm, size/XL

#626 Run `go vet` as part of the Travis CI.
  .travis.yml
  backend/src/agent/persistence/worker/metrics_reporter_test.go
  backend/src/apiserver/client/scheduled_workflow.go
  backend/src/apiserver/main.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/server/api_converter_test.go
  backend/src/apiserver/storage/db_status_store.go
  backend/src/cmd/ml/cmd/root.go
  backend/src/common/util/error.go
  backend/src/crd/pkg/apis/scheduledworkflow/v1alpha1/types.go
Labels: approved, lgtm, size/M

#616 Expose that the python API is Python3.5+ only
  sdk/python/setup.py
Labels: approved, lgtm, ok-to-test, size/S

#648 Fix shadowing errors in Viewer reconciler
  backend/src/crd/controller/viewer/reconciler/reconciler.go
Labels: approved, lgtm, size/S

#652 Use linguist annotations to skip diffing generated files
  .gitattributes
Labels: approved, lgtm, size/S

#645 Add IS_SUBSTRING operator for use in API resource filtering.
  WORKSPACE
  backend/api/filter.proto
  backend/api/generate_api.sh
  backend/api/go_client/filter.pb.go
  backend/api/swagger/filter.swagger.json
  backend/src/apiserver/filter/filter.go
  backend/src/apiserver/filter/filter_test.go
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#654 Correctly ignore src/apis when building frontend
  frontend/tsconfig.json
Labels: approved, area/front-end, lgtm, size/XS

#619 DSL refactor
  sdk/python/kfp/_client.py
  sdk/python/kfp/compiler/_k8s_helper.py
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/kfp/dsl/_pipeline.py
  sdk/python/kfp/dsl/_pipeline_param.py
  sdk/python/tests/dsl/main.py
  sdk/python/tests/dsl/pipeline_param_tests.py
Labels: approved, lgtm, size/L

#625 Sanity check filtering/sorting options in list requests.
  WORKSPACE
  backend/src/apiserver/filter/BUILD.bazel
  backend/src/apiserver/list/BUILD.bazel
  backend/src/apiserver/list/list.go
  backend/src/apiserver/list/list_test.go
  backend/src/apiserver/server/experiment_server.go
  backend/src/apiserver/server/job_server.go
  backend/src/apiserver/server/list_request_util.go
  backend/src/apiserver/server/list_request_util_test.go
  backend/src/apiserver/server/pipeline_server.go
  backend/src/apiserver/server/run_server.go
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#650 Use "create" rather than "start" except when initiating a run
  frontend/src/pages/ExperimentDetails.tsx
  frontend/src/pages/NewRun.test.tsx
  frontend/src/pages/NewRun.tsx
  frontend/src/pages/PipelineDetails.test.tsx
  frontend/src/pages/PipelineDetails.tsx
  frontend/src/pages/__snapshots__/ExperimentDetails.test.tsx.snap
  frontend/src/pages/__snapshots__/NewRun.test.tsx.snap
  test/frontend-integration-test/helloworld.spec.js
Labels: approved, area/front-end, lgtm, size/XL

#655 Release component image version d3c4add0a95e930c70a330466d0923827784eb9a
  components/kubeflow/launcher/kubeflow_tfjob_launcher_op.py
  components/kubeflow/launcher/src/train.template.yaml
  samples/kubeflow-tf/kubeflow-training-classification.py
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
  samples/resnet-cmle/resnet-train-pipeline.py
  samples/tfx/taxi-cab-classification-pipeline.py
  samples/xgboost-spark/xgboost-training-cm.py
Labels: approved, lgtm, size/M

#642 SDK/Components - Reworked the component model structures.
  sdk/python/kfp/compiler/_component_builder.py
  sdk/python/kfp/components/_components.py
  sdk/python/kfp/components/_python_op.py
  sdk/python/kfp/components/_structures.py
  sdk/python/kfp/components/modelbase.py
  sdk/python/kfp/components/structures/__init__.py
  sdk/python/kfp/components/structures/kubernetes/__init__.py
  sdk/python/kfp/components/structures/kubernetes/v1.py
  sdk/python/setup.py
  sdk/python/tests/components/test_components.py
  sdk/python/tests/components/test_graph_components.py
  sdk/python/tests/components/test_structure_model_base.py
Labels: approved, lgtm, size/XXL

#556 SDK - Fixed the unittest script
  sdk/python/tests/run_tests.sh
Labels: approved, lgtm, size/XS

#659 SDK/Components - Renamed serialized command-line argument tokens
  sdk/python/kfp/components/_structures.py
  sdk/python/tests/components/test_components.py
  sdk/python/tests/components/test_data/python_add.component.yaml
Labels: approved, lgtm, size/M

#657 update change log
  CHANGELOG.md
Labels: approved, lgtm, size/S

#656 Add simple filtering by name to CustomTable
  frontend/mock-backend/mock-api-middleware.ts
  frontend/src/apis/filter/api.ts
  frontend/src/atoms/Input.tsx
  frontend/src/components/CustomTable.test.tsx
  frontend/src/components/CustomTable.tsx
  frontend/src/components/__snapshots__/CustomTable.test.tsx.snap
  frontend/src/lib/Apis.ts
  frontend/src/pages/ExperimentList.test.tsx
  frontend/src/pages/ExperimentList.tsx
  frontend/src/pages/NewRun.tsx
  frontend/src/pages/PipelineList.test.tsx
  frontend/src/pages/PipelineList.tsx
  frontend/src/pages/RecurringRunsManager.test.tsx
  frontend/src/pages/RecurringRunsManager.tsx
  frontend/src/pages/ResourceSelector.test.tsx
  frontend/src/pages/ResourceSelector.tsx
  frontend/src/pages/RunList.test.tsx
  frontend/src/pages/RunList.tsx
  frontend/src/pages/__snapshots__/ExperimentList.test.tsx.snap
  frontend/src/pages/__snapshots__/NewRun.test.tsx.snap
  frontend/src/pages/__snapshots__/PipelineList.test.tsx.snap
  frontend/src/pages/__snapshots__/RecurringRunsManager.test.tsx.snap
  frontend/src/pages/__snapshots__/ResourceSelector.test.tsx.snap
  frontend/src/pages/__snapshots__/RunList.test.tsx.snap
Labels: approved, area/front-end, lgtm, size/XXL

#664 SDK/Tests - Fixed the output ordering instability in tests
  sdk/python/tests/components/test_python_op.py
Labels: approved, area/sdk/components, lgtm, size/S

#629 Support filtering on storage state
  .gitattributes
  backend/api/go_client/run.pb.go
  backend/api/go_http_client/job_model/api_job.go--
  backend/api/go_http_client/job_model/api_periodic_schedule.go--
  backend/api/go_http_client/run_model/api_run.go
  backend/api/run.proto
  backend/api/swagger/run.swagger.json
  backend/src/apiserver/model/run.go
  frontend/src/apis/experiment/api.ts
  frontend/src/apis/experiment/configuration.ts
  frontend/src/apis/experiment/index.ts
  frontend/src/apis/filter/api.ts
  frontend/src/apis/filter/configuration.ts
  frontend/src/apis/filter/index.ts
  frontend/src/apis/job/api.ts
  frontend/src/apis/job/configuration.ts
  frontend/src/apis/job/index.ts
  frontend/src/apis/pipeline/api.ts
  frontend/src/apis/pipeline/configuration.ts
  frontend/src/apis/pipeline/index.ts
  frontend/src/apis/run/api.ts
  frontend/src/apis/run/configuration.ts
  frontend/src/apis/run/index.ts
  go.mod
  go.sum
Labels: approved, area/back-end, lgtm, size/XL

#670 Add build version to side nav
  frontend/mock-backend/mock-api-middleware.ts
  frontend/src/components/SideNav.test.tsx
  frontend/src/components/SideNav.tsx
  frontend/src/components/__snapshots__/SideNav.test.tsx.snap
  frontend/src/lib/Apis.test.ts
  frontend/src/lib/Apis.ts
Labels: approved, area/front-end, lgtm, size/XXL

#662 SDK/Components - Simplified _create_task_factory_from_component_spec function
  sdk/python/kfp/components/_components.py
  sdk/python/kfp/components/_dsl_bridge.py
Labels: approved, area/sdk/components, lgtm, size/L

#682 Adds a link in the side nav to the KF 'usage-reporting' doc
  frontend/src/components/SideNav.tsx
  frontend/src/components/__snapshots__/SideNav.test.tsx.snap
Labels: approved, area/front-end, lgtm, size/L

#671 Include date in run status tooltips
  frontend/src/lib/WorkflowParser.ts
  frontend/src/pages/ExperimentList.test.tsx
  frontend/src/pages/ExperimentList.tsx
  frontend/src/pages/RunDetails.test.tsx
  frontend/src/pages/RunDetails.tsx
  frontend/src/pages/RunList.test.tsx
  frontend/src/pages/Status.test.tsx
  frontend/src/pages/Status.tsx
  frontend/src/pages/__snapshots__/ExperimentList.test.tsx.snap
  frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
  frontend/src/pages/__snapshots__/RunList.test.tsx.snap
  frontend/src/pages/__snapshots__/Status.test.tsx.snap
Labels: approved, area/front-end, lgtm, size/XXL

#687 improve the list run query
  backend/src/apiserver/storage/job_store.go
  backend/src/apiserver/storage/run_store.go
Labels: approved, lgtm, size/M

#663 SDK/Components - Added /data to the generated file paths
  sdk/python/kfp/components/_components.py
Labels: approved, area/sdk/components, lgtm, size/XS

#689 add gcp credential for tf-job template
  components/kubeflow/launcher/src/train.template.yaml
Labels: approved, lgtm, size/M

#694 Components release 2ed60100d1db9efeb38c6c358f90b21c144179be
  components/kubeflow/launcher/kubeflow_tfjob_launcher_op.py
  components/kubeflow/launcher/src/train.template.yaml
  samples/kubeflow-tf/kubeflow-training-classification.py
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
  samples/resnet-cmle/resnet-train-pipeline.py
  samples/tfx/taxi-cab-classification-pipeline.py
  samples/xgboost-spark/xgboost-training-cm.py
Labels: approved, lgtm, size/M

#697 Update changelog for release 0.1.8
  CHANGELOG.md
Labels: approved, lgtm, size/M

#720 create nonexistent directory for roc and confusion_matrix component
  components/local/confusion_matrix/src/confusion_matrix.py
  components/local/roc/src/roc.py
Labels: approved, lgtm, size/XS

#704 randomize the deployment name to avoid collision
  samples/tfx/taxi-cab-classification-pipeline.py
Labels: approved, lgtm, size/XS

#691 SDK - Update minimum Python version to 3.5.3
  sdk/python/setup.py
Labels: approved, area/sdk, lgtm, size/XS

#724 Add CMLE sample test script.
  test/sample-test/run_resnet_cmle_test.py
Labels: approved, lgtm, size/L

#693 bump ks version in presubmit test
  pipeline/Dockerfile
  test/presubmit-tests-with-pipeline-deployment.sh
Labels: approved, lgtm, size/XS

#717 SDK/Components/Python - Made the typing.NamedTuple import optional
  sdk/python/kfp/components/_python_op.py
Labels: approved, area/sdk/components, lgtm, size/S

#723 Add "set_retry()" on ContainerOp.
  samples/basic/retry.py
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/retry.py
  sdk/python/tests/compiler/testdata/retry.yaml
Labels: approved, lgtm, size/L

#722 Auto-refreshes the run details page
  frontend/mock-backend/fixed-data.ts
  frontend/src/components/SideNav.test.tsx
  frontend/src/components/UploadPipelineDialog.test.tsx
  frontend/src/pages/Compare.test.tsx
  frontend/src/pages/ExperimentDetails.test.tsx
  frontend/src/pages/ExperimentList.test.tsx
  frontend/src/pages/NewRun.test.tsx
  frontend/src/pages/PipelineDetails.test.tsx
  frontend/src/pages/PipelineList.test.tsx
  frontend/src/pages/ResourceSelector.test.tsx
  frontend/src/pages/RunDetails.test.tsx
  frontend/src/pages/RunDetails.tsx
  frontend/src/pages/Status.test.tsx
  frontend/src/pages/Status.tsx
  frontend/src/pages/__snapshots__/Status.test.tsx.snap
Labels: approved, area/front-end, lgtm, size/L

#718 SDK/Components/Python - Improved Python2 compatibility
  sdk/python/kfp/components/_python_op.py
Labels: approved, area/sdk/components, lgtm, size/XS

#715 SDK/Components - Added _naming._convert_to_human_name function
  sdk/python/kfp/components/_components.py
  sdk/python/kfp/components/_dsl_bridge.py
  sdk/python/kfp/components/_naming.py
Labels: approved, area/sdk/components, lgtm, size/L

#710 SDK/Components - More meaningful error when trying to convert graph component to ContainerOp
  sdk/python/kfp/components/_dsl_bridge.py
Labels: approved, area/sdk/components, lgtm, size/XS

#711 SDK/Components - Command line args can only be strings or placeholders
  sdk/python/kfp/components/_structures.py
  sdk/python/tests/components/test_components.py
Labels: approved, area/sdk/components, lgtm, size/M

#733 SDK/Components - convert_object_to_struct now uses __init__ to get field list
  sdk/python/kfp/components/modelbase.py
Labels: approved, area/sdk/components, lgtm, size/XS

#696 Add gpu pool to test deployment and enable gpu in sample test
  test/presubmit-tests-with-pipeline-deployment.sh
  test/sample-test/run_test.sh
Labels: approved, lgtm, size/XS

#732 SDK/Components - Improved error when type checking fails in constructor
  sdk/python/kfp/components/modelbase.py
Labels: approved, area/sdk/components, lgtm, size/XS

#735 fix dataproc cluster version
  components/dataproc/common/_utils.py
Labels: approved, lgtm, size/XS

#743 Updated dev guide for apiserver build with minikube.
  developer_guide.md
Labels: approved, lgtm, size/XS

#747 Releasing components fixing xgboost
  components/kubeflow/launcher/kubeflow_tfjob_launcher_op.py
  components/kubeflow/launcher/src/train.template.yaml
  samples/kubeflow-tf/kubeflow-training-classification.py
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
  samples/resnet-cmle/resnet-train-pipeline.py
  samples/tfx/taxi-cab-classification-pipeline.py
  samples/xgboost-spark/xgboost-training-cm.py
Labels: approved, lgtm, size/M

#729 Create kfp componet sdk
  .gitignore
  component_sdk/python/kfp_component/__init__.py
  component_sdk/python/kfp_component/_base_op.py
  component_sdk/python/requirements.txt
  component_sdk/python/run_test.sh
  component_sdk/python/setup.py
  component_sdk/python/test-requirements.txt
  component_sdk/python/tests/__init__.py
  component_sdk/python/tests/test_base_op.py
  component_sdk/python/tox.ini
Labels: approved, lgtm, size/L

#740 Add Dockerfile for building Viewer CRD controller.
  .cloudbuild.yaml
  backend/Dockerfile.viewercontroller
Labels: approved, lgtm, size/S

#734 Improve runtime graph starting and running experience
  frontend/src/Css.tsx
  frontend/src/atoms/IconWithTooltip.test.tsx
  frontend/src/atoms/IconWithTooltip.tsx
  frontend/src/atoms/__snapshots__/IconWithTooltip.test.tsx.snap
  frontend/src/components/Graph.test.tsx
  frontend/src/components/Graph.tsx
  frontend/src/components/__snapshots__/Graph.test.tsx.snap
  frontend/src/lib/WorkflowParser.test.ts
  frontend/src/lib/WorkflowParser.ts
  frontend/src/pages/PipelineDetails.tsx
  frontend/src/pages/RunDetails.test.tsx
  frontend/src/pages/RunDetails.tsx
  frontend/src/pages/__snapshots__/ExperimentList.test.tsx.snap
  frontend/src/pages/__snapshots__/PipelineDetails.test.tsx.snap
  frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
  frontend/src/pages/__snapshots__/Status.test.tsx.snap
Labels: approved, area/front-end, lgtm, size/XXL

#595 Return resource count from ListXXX calls
  backend/README.md
  backend/api/experiment.proto
  backend/api/go_client/experiment.pb.go
  backend/api/go_client/job.pb.go
  backend/api/go_client/pipeline.pb.go
  backend/api/go_client/run.pb.go
  backend/api/go_http_client/experiment_model/api_list_experiments_response.go
  backend/api/go_http_client/job_model/api_list_jobs_response.go
  backend/api/go_http_client/pipeline_model/api_list_pipelines_response.go
  backend/api/go_http_client/run_model/api_list_runs_response.go
  backend/api/job.proto
  backend/api/pipeline.proto
  backend/api/run.proto
  backend/api/swagger/experiment.swagger.json
  backend/api/swagger/job.swagger.json
  backend/api/swagger/pipeline.swagger.json
  backend/api/swagger/run.swagger.json
  backend/src/apiserver/list/BUILD.bazel
  backend/src/apiserver/list/list.go
  backend/src/apiserver/list/list_test.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/server/experiment_server.go
  backend/src/apiserver/server/job_server.go
  backend/src/apiserver/server/pipeline_server.go
  backend/src/apiserver/server/pipeline_upload_server_test.go
  backend/src/apiserver/server/run_server.go
  backend/src/apiserver/storage/BUILD.bazel
  backend/src/apiserver/storage/db_status_store.go
  backend/src/apiserver/storage/experiment_store.go
  backend/src/apiserver/storage/experiment_store_test.go
  backend/src/apiserver/storage/job_store.go
  backend/src/apiserver/storage/job_store_test.go
  backend/src/apiserver/storage/list_util.go
  backend/src/apiserver/storage/list_util_test.go
  backend/src/apiserver/storage/pipeline_store.go
  backend/src/apiserver/storage/pipeline_store_test.go
  backend/src/apiserver/storage/run_store.go
  backend/src/apiserver/storage/run_store_test.go
  backend/src/common/client/api_server/experiment_client.go
  backend/src/common/client/api_server/experiment_client_fake.go
  backend/src/common/client/api_server/job_client.go
  backend/src/common/client/api_server/job_client_fake.go
  backend/src/common/client/api_server/pipeline_client.go
  backend/src/common/client/api_server/pipeline_client_fake.go
  backend/src/common/client/api_server/run_client.go
  backend/src/common/client/api_server/run_client_fake.go
  backend/test/experiment_api_test.go
  backend/test/job_api_test.go
  backend/test/pipeline_api_test.go
  backend/test/run_api_test.go
  backend/test/test_utils.go
Labels: approved, area/back-end, lgtm, size/XXL

#757 Regenerate frontend API files now that listCount APIs are merged
  frontend/src/apis/experiment/api.ts
  frontend/src/apis/filter/api.ts
  frontend/src/apis/job/api.ts
  frontend/src/apis/pipeline/api.ts
  frontend/src/apis/run/api.ts
Labels: approved, area/front-end, lgtm, size/M

#758 Add UI actions to Buttons module
  frontend/src/TestUtils.tsx
  frontend/src/lib/Buttons.ts
  frontend/src/pages/AllRunsList.tsx
  frontend/src/pages/Compare.test.tsx
  frontend/src/pages/Compare.tsx
  frontend/src/pages/ExperimentDetails.test.tsx
  frontend/src/pages/ExperimentDetails.tsx
  frontend/src/pages/ExperimentList.test.tsx
  frontend/src/pages/ExperimentList.tsx
  frontend/src/pages/PipelineDetails.test.tsx
  frontend/src/pages/PipelineDetails.tsx
  frontend/src/pages/PipelineList.test.tsx
  frontend/src/pages/PipelineList.tsx
  frontend/src/pages/RecurringRunDetails.test.tsx
  frontend/src/pages/RecurringRunDetails.tsx
  frontend/src/pages/RunDetails.tsx
  frontend/src/pages/__snapshots__/Compare.test.tsx.snap
  frontend/src/pages/__snapshots__/ExperimentDetails.test.tsx.snap
Labels: approved, area/front-end, lgtm, size/XXL
