Repository kubeflow/pipelines, pull requests merged in 2019-02, with the labels that each got.

#760 Fix Dockerfile for viewer CRD image.
  backend/Dockerfile.viewercontroller
Labels: approved, lgtm, size/S

#761 Add component_sdk tests to travis tests
  .travis.yml
  component_sdk/python/requirements.txt
  component_sdk/python/tox.ini
Labels: approved, lgtm, size/M

#755 Enhance deploy.sh to support local storage
  components/kubeflow/deployer/src/deploy.sh
Labels: approved, lgtm, size/S

#778 Revert GPU tests to unblock release
  test/presubmit-tests-with-pipeline-deployment.sh
  test/sample-test/run_test.sh
Labels: approved, lgtm, size/XS

#745 support pipeline level imagepullsecret in DSL
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/dsl/__init__.py
  sdk/python/kfp/dsl/_pipeline.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/imagepullsecret.py
  sdk/python/tests/compiler/testdata/imagepullsecret.yaml
Labels: approved, lgtm, size/L

#786 Creating ROADMAP.md
  ROADMAP.md
Labels: approved, lgtm, size/M

#777 Modifications done by the execution of the release script.
  components/kubeflow/launcher/kubeflow_tfjob_launcher_op.py
  components/kubeflow/launcher/src/train.template.yaml
  samples/kubeflow-tf/kubeflow-training-classification.py
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
  samples/resnet-cmle/resnet-train-pipeline.py
  samples/tfx/taxi-cab-classification-pipeline.py
  samples/xgboost-spark/xgboost-training-cm.py
Labels: approved, lgtm, size/M

#731 placeholder for ibm sample pipelines and corresponding components
  components/ibm-components/OWNERS
  components/ibm-components/ffdl/serve/Dockerfile
  components/ibm-components/ffdl/serve/src/app.py
  components/ibm-components/ffdl/serve/src/kube/seldon.json
  components/ibm-components/ffdl/serve/src/serve.py
  components/ibm-components/ffdl/train/Dockerfile
  components/ibm-components/ffdl/train/src/train.py
  samples/ibm-samples/OWNERS
  samples/ibm-samples/ffdl-seldon/README.md
  samples/ibm-samples/ffdl-seldon/credentials/creds.ini
  samples/ibm-samples/ffdl-seldon/credentials/github-creds.ini
  samples/ibm-samples/ffdl-seldon/ffdl_pipeline.ipynb
  samples/ibm-samples/ffdl-seldon/ffdl_pipeline.py
  samples/ibm-samples/ffdl-seldon/source/README.md
  samples/ibm-samples/ffdl-seldon/source/manifest.yml
  samples/ibm-samples/ffdl-seldon/source/model-source-code/gender_classification.py
  samples/ibm-samples/ffdl-seldon/source/seldon-pytorch-serving-image/.s2i/environment
  samples/ibm-samples/ffdl-seldon/source/seldon-pytorch-serving-image/README.md
  samples/ibm-samples/ffdl-seldon/source/seldon-pytorch-serving-image/Serving.py
  samples/ibm-samples/ffdl-seldon/source/seldon-pytorch-serving-image/model_files/__init__.py
  samples/ibm-samples/ffdl-seldon/source/seldon-pytorch-serving-image/requirements.txt
Labels: approved, lgtm, ok-to-test, size/XXL

#782 Update Basic Pipeline example notebook
  samples/notebooks/Lightweight Python components - basics.ipynb
Labels: approved, lgtm, size/S

#771 update developer guide to renew deployment section
  developer_guide.md
Labels: approved, lgtm, size/M

#797 Update changelog for release 0.19
  CHANGELOG.md
Labels: approved, lgtm, size/M

#799 merge build image to test suit
  test/build_image.yaml
  test/check-argo-status.sh
  test/presubmit-tests-with-pipeline-deployment.sh
  test/presubmit-tests.sh
Labels: approved, lgtm, size/L

#779 Support to send default service account jwt token for pipeline client.
  sdk/python/build.sh
  sdk/python/kfp/_auth.py
  sdk/python/kfp/_client.py
  sdk/python/setup.py
Labels: approved, lgtm, size/L

#806 add trainer license to unblock release
  components/third_party_licenses.csv
Labels: approved, lgtm, size/XS

#808 switch test to us-west1
  test/presubmit-tests-with-pipeline-deployment.sh
Labels: approved, lgtm, size/XS

#810 add pyarrow in license csv.
  components/third_party_licenses.csv
Labels: approved, lgtm, size/XS

#813 Increase disk size and use high CPU machine type in cloud build
  .cloudbuild.yaml
Labels: approved, lgtm, size/XS

#816 Sample updates for release v0.1.10
  components/kubeflow/launcher/kubeflow_tfjob_launcher_op.py
  components/kubeflow/launcher/src/train.template.yaml
  samples/kubeflow-tf/kubeflow-training-classification.py
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
  samples/resnet-cmle/resnet-train-pipeline.py
  samples/tfx/taxi-cab-classification-pipeline.py
  samples/xgboost-spark/xgboost-training-cm.py
Labels: approved, lgtm, size/M

#815 Improve docker image build perf by leveraging docker cache
  components/bigquery/query/build_image.sh
  components/build_image.sh
  components/dataflow/predict/build_image.sh
  components/dataflow/tfdv/build_image.sh
  components/dataflow/tfma/build_image.sh
  components/dataflow/tft/build_image.sh
  components/dataproc/analyze/build_image.sh
  components/dataproc/create_cluster/build_image.sh
  components/dataproc/delete_cluster/build_image.sh
  components/dataproc/predict/build_image.sh
  components/dataproc/train/build_image.sh
  components/dataproc/transform/build_image.sh
  components/local/confusion_matrix/build_image.sh
  components/local/roc/build_image.sh
Labels: approved, lgtm, size/XL

#803 Updates lodash to version 4.17.11
  frontend/package.json
  frontend/server/package-lock.json
  frontend/server/package.json
  test/frontend-integration-test/package-lock.json
  test/frontend-integration-test/package.json
Labels: approved, lgtm, size/XL

#826 Fixed validation in new run form when filling name then pipeline
  frontend/src/pages/NewRun.tsx
Labels: approved, lgtm, ok-to-test, size/XS

#772 Updates frontend to Typescript to 3.3.1
  frontend/package-lock.json
  frontend/package.json
  frontend/server/package-lock.json
  frontend/server/package.json
  frontend/src/components/CustomTable.tsx
  frontend/src/pages/ExperimentList.test.tsx
  frontend/src/pages/ExperimentList.tsx
  frontend/src/pages/PipelineList.tsx
  frontend/src/pages/RecurringRunsManager.test.tsx
  frontend/src/pages/RecurringRunsManager.tsx
  frontend/src/pages/RunList.test.tsx
  frontend/src/pages/RunList.tsx
  frontend/src/pages/Status.test.tsx
  frontend/src/pages/Status.tsx
  frontend/src/pages/__snapshots__/ExperimentList.test.tsx.snap
  frontend/src/pages/__snapshots__/RecurringRunsManager.test.tsx.snap
  frontend/src/pages/__snapshots__/RunList.test.tsx.snap
  frontend/src/pages/__snapshots__/Status.test.tsx.snap
  frontend/tsconfig.json
Labels: approved, area/front-end, lgtm, size/XXL

#822 Adds a local volume sample for the Viewer CRD
  backend/src/crd/README.md
  backend/src/crd/samples/viewer/tensorboard-local-volume.yaml
Labels: approved, lgtm, size/M

#817 Revert dataflow component version in samples to unblock release
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
  samples/tfx/taxi-cab-classification-pipeline.py
Labels: approved, lgtm, size/S

#828 fix apache-beam and pandas versions in tfdv image
  components/dataflow/tfdv/Dockerfile
Labels: approved, lgtm, size/XS

#770 Cleanup pipeline bootstrapper
  .gitignore
Labels: approved, lgtm, ok-to-test, size/XS

#830 Sets 'Choose file' button width to avoid wrap
  frontend/src/components/UploadPipelineDialog.tsx
  frontend/src/components/__snapshots__/UploadPipelineDialog.test.tsx.snap
Labels: approved, area/front-end, lgtm, size/XS

#837 add container image uris support in train API
  component_sdk/python/kfp_component/google/ml_engine/_train.py
  component_sdk/python/tests/google/ml_engine/test__train.py
Labels: approved, lgtm, size/M

#840 Update change log for v0.1.10 release
  CHANGELOG.md
Labels: approved, lgtm, size/M

#823 Enhance hard code for export dir in deploy component
  components/kubeflow/deployer/src/deploy.sh
Labels: approved, lgtm, size/S

#829 Update graph styling
  frontend/package-lock.json
  frontend/src/Css.tsx
  frontend/src/components/CompareTable.tsx
  frontend/src/components/CustomTable.tsx
  frontend/src/components/Graph.tsx
  frontend/src/components/SidePanel.tsx
  frontend/src/components/Toolbar.tsx
  frontend/src/components/UploadPipelineDialog.tsx
  frontend/src/components/__snapshots__/Graph.test.tsx.snap
  frontend/src/components/__snapshots__/PlotCard.test.tsx.snap
  frontend/src/lib/Constants.ts
  frontend/src/lib/StaticGraphParser.ts
  frontend/src/lib/WorkflowParser.test.ts
  frontend/src/lib/WorkflowParser.ts
  frontend/src/pages/ExperimentDetails.tsx
  frontend/src/pages/PipelineDetails.tsx
  frontend/src/pages/Status.test.tsx
  frontend/src/pages/Status.tsx
  frontend/src/pages/__snapshots__/ExperimentList.test.tsx.snap
  frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
  frontend/src/pages/__snapshots__/Status.test.tsx.snap
Labels: approved, area/front-end, lgtm, size/XXL

#839 Update swagger codegen version
  .cloudbuild.yaml
  .travis.yml
  backend/Dockerfile
  frontend/README.md
  test/sample-test/Dockerfile
Labels: approved, lgtm, size/S

#838 Add owner file under component_sdk.
  component_sdk/OWNERS
Labels: approved, lgtm, size/XS

#847 Move e2e tests to us-east1
  test/presubmit-tests-with-pipeline-deployment.sh
Labels: approved, lgtm, size/XS

#846 ROADMAP.md cosmetic changes
  ROADMAP.md
Labels: approved, lgtm, size/M

#836 Support BigQuery command to query and export to GCS
  component_sdk/python/kfp_component/google/bigquery/__init__.py
  component_sdk/python/kfp_component/google/bigquery/_query.py
  component_sdk/python/requirements.txt
  component_sdk/python/tests/google/bigquery/test__query.py
Labels: approved, lgtm, size/L

#852 freeze tfdv dependency
  components/dataflow/tfdv/Dockerfile
Labels: approved, lgtm, size/M

#800 Training and Serving Pipeline leveraging WML
  components/ibm-components/OWNERS
  components/ibm-components/commons/config/Dockerfile
  components/ibm-components/commons/config/src/config.py
  components/ibm-components/watson/deploy/Dockerfile
  components/ibm-components/watson/deploy/src/wml-deploy.py
  components/ibm-components/watson/store/Dockerfile
  components/ibm-components/watson/store/src/wml-store.py
  components/ibm-components/watson/train/Dockerfile
  components/ibm-components/watson/train/src/wml-train.py
  samples/ibm-samples/OWNERS
  samples/ibm-samples/watson/README.md
  samples/ibm-samples/watson/credentials/creds.ini
  samples/ibm-samples/watson/credentials/github-creds.ini
  samples/ibm-samples/watson/source/model-source-code/tf-mnist-test-payload.json
  samples/ibm-samples/watson/source/model-source-code/tf-model/convolutional_network.py
  samples/ibm-samples/watson/source/model-source-code/tf-model/input_data.py
  samples/ibm-samples/watson/watson_train_serve_pipeline.py
Labels: approved, lgtm, needs-ok-to-test, size/XL

#809 Added the "Keras - Train classifier" component
  components/sample/keras/train_classifier/Dockerfile
  components/sample/keras/train_classifier/README.md
  components/sample/keras/train_classifier/build_image.sh
  components/sample/keras/train_classifier/component.yaml
  components/sample/keras/train_classifier/run_tests.sh
  components/sample/keras/train_classifier/src/train.py
  components/sample/keras/train_classifier/tests/test_component.py
  components/sample/keras/train_classifier/tests/testdata/model_config.json
  components/sample/keras/train_classifier/tests/testdata/training_set_features.tsv
  components/sample/keras/train_classifier/tests/testdata/training_set_labels.tsv
Labels: approved, lgtm, size/L

#856 Removes accidental package from TFDV Dockerfile
  components/dataflow/tfdv/Dockerfile
Labels: approved, lgtm, size/XS

#730 component build support for both python2 and python3
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
  sdk/python/kfp/compiler/_component_builder.py
  sdk/python/tests/compiler/component_builder_test.py
  test/sample-test/run_test.sh
Labels: approved, lgtm, size/L

#841 extract the pipelineparam deserialize function
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/kfp/dsl/_pipeline_param.py
  sdk/python/tests/dsl/pipeline_param_tests.py
Labels: approved, lgtm, size/M

#857 add attrs and pyrsistent
  components/third_party_licenses.csv
Labels: approved, lgtm, size/XS

#860 fix typo in cloud build
  .cloudbuild.yaml
Labels: approved, lgtm, size/XS

#845 Support rendering recursive static DAGs
  frontend/mock-backend/fixed-data.ts
  frontend/mock-backend/mock-api-middleware.ts
  frontend/mock-backend/mock-recursive-template.yaml
  frontend/src/components/Graph.tsx
  frontend/src/lib/StaticGraphParser.test.ts
  frontend/src/lib/StaticGraphParser.ts
Labels: approved, area/front-end, lgtm, size/L

#861 fix bug in the gcp oob
  .cloudbuild.yaml
  components/third_party_licenses.csv
Labels: approved, lgtm, size/XS

#849 release new components: deployer
  components/kubeflow/launcher/kubeflow_tfjob_launcher_op.py
  components/kubeflow/launcher/src/train.template.yaml
  samples/kubeflow-tf/kubeflow-training-classification.py
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
  samples/resnet-cmle/resnet-train-pipeline.py
  samples/tfx/taxi-cab-classification-pipeline.py
  samples/xgboost-spark/xgboost-training-cm.py
Labels: approved, lgtm, size/M

#863 add sigint sigterm to the test
  test/deploy-kubeflow.sh
Labels: approved, lgtm, size/XS

#871 sample test image build failure
  test/sample-test/Dockerfile
Labels: approved, lgtm, size/XS

#866 fix bunch of issues in prow test
  test/check-argo-status.sh
  test/deploy-kubeflow.sh
  test/deploy-pipeline.sh
  test/install-argo.sh
  test/postsubmit-tests-with-pipeline-deployment.sh
  test/presubmit-tests-with-pipeline-deployment.sh
  test/test-prep.sh
Labels: approved, lgtm, size/M

#783 Adds a modifier function to simplify addition of local volumes to containerop
  sdk/python/kfp/onprem.py
Labels: approved, lgtm, size/S

#870 Fix bugs in dataflow component
  component_sdk/python/kfp_component/google/dataflow/_launch_python.py
  component_sdk/python/kfp_component/google/storage/_download_blob.py
  component_sdk/python/tests/google/storage/test__download_blob.py
Labels: approved, lgtm, size/XS

#876 Switch to python 2.7 and install beam for the gcp image.
  components/gcp/container/Dockerfile
Labels: approved, lgtm, size/XS

#835 Fixing grammatical errors and references
  samples/ibm-samples/ffdl-seldon/README.md
Labels: approved, lgtm, ok-to-test, size/S

#851 Allow users to specify namespace for Kubernetes informers
  backend/src/crd/controller/scheduledworkflow/main.go
Labels: approved, lgtm, ok-to-test, size/S

#853 link anchor text nit
  developer_guide.md
Labels: approved, lgtm, ok-to-test, size/XS

#858 Added a README for Getting Started with the Pipelines CLI
  backend/src/cmd/ml/README.md
Labels: approved, lgtm, size/M
