Repository kubeflow/pipelines, pull requests merged in 2019-12, with the labels that each got.

#2639 SDK - Python support for arbitrary secret, similar to ".use_gcp_secret('user-gcp-sa')"
  sdk/python/kfp/dsl/extensions/__init__.py
  sdk/python/kfp/dsl/extensions/kubernetes.py
  sdk/python/setup.py
  sdk/python/tests/dsl/extensions/__init__.py
  sdk/python/tests/dsl/extensions/test_kubernetes.py
  sdk/python/tests/dsl/main.py
Labels: approved, lgtm, ok-to-test, size/L

#2651 add namespace to the resourcereference
  backend/api/go_client/resource_reference.pb.go
  backend/api/go_http_client/job_model/api_job.go--
  backend/api/go_http_client/job_model/api_periodic_schedule.go--
  backend/api/go_http_client/job_model/api_resource_type.go
  backend/api/go_http_client/pipeline_model/api_resource_type.go
  backend/api/go_http_client/run_model/api_resource_type.go
  backend/api/resource_reference.proto
  backend/api/swagger/job.swagger.json
  backend/api/swagger/kfp_api_single_file.swagger.json
  backend/api/swagger/pipeline.swagger.json
  backend/api/swagger/run.swagger.json
  backend/src/apiserver/client_manager.go
  backend/src/apiserver/common/config.go
  backend/src/apiserver/common/const.go
  backend/src/apiserver/main.go
  backend/src/apiserver/resource/model_converter.go
  backend/src/apiserver/resource/model_converter_test.go
  backend/src/apiserver/resource/resource_manager_util_test.go
  backend/src/apiserver/resource/workflow_fake.go
  manifests/kustomize/base/argo/minio-artifact-secret.yaml
Labels: approved, lgtm, size/L

#2681 fix visualization-server doc link
  developer_guide.md
Labels: approved, lgtm, size/XS

#2671 Components - TFX
  components/tfx/Evaluator/component.py
  components/tfx/Evaluator/component.yaml
  components/tfx/ExampleGen/BigQueryExampleGen/component.py
  components/tfx/ExampleGen/BigQueryExampleGen/component.yaml
  components/tfx/ExampleGen/CsvExampleGen/component.py
  components/tfx/ExampleGen/CsvExampleGen/component.yaml
  components/tfx/ExampleGen/CsvExampleGen/with_URI_IO/component.py
  components/tfx/ExampleGen/CsvExampleGen/with_URI_IO/component.yaml
  components/tfx/ExampleGen/ImportExampleGen/component.py
  components/tfx/ExampleGen/ImportExampleGen/component.yaml
  components/tfx/ExampleValidator/component.py
  components/tfx/ExampleValidator/component.yaml
  components/tfx/SchemaGen/component.py
  components/tfx/SchemaGen/component.yaml
  components/tfx/StatisticsGen/component.py
  components/tfx/StatisticsGen/component.yaml
  components/tfx/Trainer/component.py
  components/tfx/Trainer/component.yaml
  components/tfx/Transform/component.py
  components/tfx/Transform/component.yaml
  components/tfx/_samples/TFX_pipeline.ipynb
Labels: approved, area/components, lgtm, size/XXL

#2700 release-b63472062bd80737c7f39e0eda901db0fe23a5e0
  components/gcp/bigquery/query/README.md
  components/gcp/bigquery/query/component.yaml
  components/gcp/bigquery/query/sample.ipynb
  components/gcp/container/component_sdk/python/setup.py
  components/gcp/dataflow/launch_python/README.md
  components/gcp/dataflow/launch_python/component.yaml
  components/gcp/dataflow/launch_python/sample.ipynb
  components/gcp/dataflow/launch_template/README.md
  components/gcp/dataflow/launch_template/component.yaml
  components/gcp/dataflow/launch_template/sample.ipynb
  components/gcp/dataproc/create_cluster/README.md
  components/gcp/dataproc/create_cluster/component.yaml
  components/gcp/dataproc/create_cluster/sample.ipynb
  components/gcp/dataproc/delete_cluster/README.md
  components/gcp/dataproc/delete_cluster/component.yaml
  components/gcp/dataproc/delete_cluster/sample.ipynb
  components/gcp/dataproc/submit_hadoop_job/README.md
  components/gcp/dataproc/submit_hadoop_job/component.yaml
  components/gcp/dataproc/submit_hadoop_job/sample.ipynb
  components/gcp/dataproc/submit_hive_job/README.md
  components/gcp/dataproc/submit_hive_job/component.yaml
  components/gcp/dataproc/submit_hive_job/sample.ipynb
  components/gcp/dataproc/submit_pig_job/README.md
  components/gcp/dataproc/submit_pig_job/component.yaml
  components/gcp/dataproc/submit_pig_job/sample.ipynb
  components/gcp/dataproc/submit_pyspark_job/README.md
  components/gcp/dataproc/submit_pyspark_job/component.yaml
  components/gcp/dataproc/submit_pyspark_job/sample.ipynb
  components/gcp/dataproc/submit_spark_job/README.md
  components/gcp/dataproc/submit_spark_job/component.yaml
  components/gcp/dataproc/submit_spark_job/sample.ipynb
  components/gcp/dataproc/submit_sparksql_job/README.md
  components/gcp/dataproc/submit_sparksql_job/component.yaml
  components/gcp/dataproc/submit_sparksql_job/sample.ipynb
  components/gcp/ml_engine/batch_predict/README.md
  components/gcp/ml_engine/batch_predict/component.yaml
  components/gcp/ml_engine/batch_predict/sample.ipynb
  components/gcp/ml_engine/deploy/README.md
  components/gcp/ml_engine/deploy/component.yaml
  components/gcp/ml_engine/deploy/sample.ipynb
  components/gcp/ml_engine/train/README.md
  components/gcp/ml_engine/train/component.yaml
  components/gcp/ml_engine/train/sample.ipynb
  components/kubeflow/deployer/component.yaml
  components/kubeflow/dnntrainer/component.yaml
  components/kubeflow/launcher/kubeflow_tfjob_launcher_op.py
  components/kubeflow/launcher/src/train.template.yaml
  components/local/confusion_matrix/component.yaml
  components/local/roc/component.yaml
  samples/core/ai_platform/ai_platform.ipynb
  samples/core/dataflow/dataflow.ipynb
  samples/core/kubeflow_tf_serving/kubeflow_tf_serving.ipynb
  samples/core/xgboost_training_cm/xgboost_training_cm.py
Labels: approved, lgtm, size/L

#2698 Store ns in db
  backend/src/apiserver/resource/model_converter.go
  backend/src/apiserver/resource/model_converter_test.go
  backend/src/apiserver/server/api_converter.go
  backend/src/apiserver/storage/resource_reference_store.go
Labels: approved, lgtm, size/S

#2701 update server and sdk version to 0.1.37
  manifests/kustomize/base/kustomization.yaml
  sdk/python/kfp/__init__.py
  sdk/python/kfp/_client.py
  sdk/python/setup.py
Labels: size/S

#2665 Add ns in sdk
  sdk/python/kfp/_client.py
Labels: approved, lgtm, size/M

#1555 SDK/Compiler - Preventing pipeline entrypoint template name from clashing with other template names
  sdk/python/kfp/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
Labels: approved, area/sdk/dsl/compiler, lgtm, size/M

#2667 Add pipeline version support to frontend
  frontend/package-lock.json
  frontend/server/package-lock.json
  frontend/src/components/CustomTable.tsx
  frontend/src/components/Router.tsx
  frontend/src/components/__snapshots__/CustomTable.test.tsx.snap
  frontend/src/components/__snapshots__/Router.test.tsx.snap
  frontend/src/lib/Apis.ts
  frontend/src/lib/Buttons.ts
  frontend/src/lib/RunUtils.ts
  frontend/src/pages/NewPipelineVersion.test.tsx
  frontend/src/pages/NewPipelineVersion.tsx
  frontend/src/pages/NewRun.test.tsx
  frontend/src/pages/NewRun.tsx
  frontend/src/pages/PipelineDetails.test.tsx
  frontend/src/pages/PipelineDetails.tsx
  frontend/src/pages/PipelineList.test.tsx
  frontend/src/pages/PipelineList.tsx
  frontend/src/pages/PipelineVersionList.test.tsx
  frontend/src/pages/PipelineVersionList.tsx
  frontend/src/pages/RunList.test.tsx
  frontend/src/pages/RunList.tsx
  frontend/src/pages/__snapshots__/NewPipelineVersion.test.tsx.snap
  frontend/src/pages/__snapshots__/NewRun.test.tsx.snap
  frontend/src/pages/__snapshots__/PipelineDetails.test.tsx.snap
  frontend/src/pages/__snapshots__/PipelineList.test.tsx.snap
  frontend/src/pages/__snapshots__/PipelineVersionList.test.tsx.snap
  frontend/src/pages/__snapshots__/RunList.test.tsx.snap
  frontend/tsconfig.json
  test/frontend-integration-test/helloworld.spec.js
Labels: approved, lgtm, size/XXL

#2707 Improve golang license CLI tools README
  third_party/cli/README.md
Labels: approved, area/docs, lgtm, size/XS

#2677 TFjob v1 launcher
  components/kubeflow/common/launch_crd.py
  components/kubeflow/katib-launcher/build_image.sh
  components/kubeflow/launcher/Dockerfile
  components/kubeflow/launcher/OWNERS
  components/kubeflow/launcher/build_image.sh
  components/kubeflow/launcher/component.yaml
  components/kubeflow/launcher/kubeflow_tfjob_launcher_op.py
  components/kubeflow/launcher/sample.py
  components/kubeflow/launcher/src/__init__.py
  components/kubeflow/launcher/src/launch_tf_job.py
  components/kubeflow/launcher/src/launch_tfjob.py
  components/kubeflow/launcher/src/train.template.yaml
  components/kubeflow/launcher/test/__init__.py
  components/kubeflow/launcher/test/test_launcher.py
  components/kubeflow/launcher/test/testdata/train.template.yaml
  components/kubeflow/launcher/test/testdata/train_basic.yaml
  components/kubeflow/launcher/test/testdata/train_zero_worker.yaml
Labels: approved, area/components, lgtm, size/XL

#2688 SDK - Fixed the capitalization in _python_function_name_to_component_name
  sdk/python/kfp/components/_python_op.py
Labels: approved, area/sdk/components, lgtm, size/XS

#2695 [Sample test] Add parameterized_tfx_oss to 'normal' sample test corpus
  backend/Dockerfile
  backend/src/apiserver/config/sample_config.json
  samples/contrib/parameterized_tfx_oss/parameterized_tfx_oss.tar.gz
  samples/core/artifact_location/artifact_location.py
  samples/core/condition/condition.py
  samples/core/execution_order/execution_order.py
  samples/core/exit_handler/exit_handler.py
  samples/core/helloworld/hello_world.py
  samples/core/imagepullsecrets/imagepullsecrets.py
  samples/core/loop_output/loop_output.py
  samples/core/loop_parameter/loop_parameter.py
  samples/core/loop_static/loop_static.py
  samples/core/parallel_join/parallel_join.py
  samples/core/parameterized_tfx_oss/README.md
  samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py
  samples/core/pipeline_transformers/pipeline_transformers.py
  samples/core/preemptible_tpu_gpu/preemptible_tpu_gpu.py
  samples/core/recursion/recursion.py
  samples/core/resource_ops/resource_ops.py
  samples/core/retry/retry.py
  samples/core/secret/secret.py
  samples/core/sequential/sequential.py
  samples/core/sidecar/sidecar.py
  samples/core/volume_ops/volume_ops.py
  samples/core/volume_snapshot_ops/volume_snapshot_ops.py
  samples/core/xgboost_training_cm/xgboost_training_cm.py
  test/sample-test/Dockerfile
  test/sample-test/sample_test_launcher.py
Labels: approved, lgtm, size/L

#2663 Authorize create run requests
  backend/src/apiserver/client/BUILD.bazel
  backend/src/apiserver/client/kfam.go
  backend/src/apiserver/client/kfam_fake.go
  backend/src/apiserver/client/kfam_test.go
  backend/src/apiserver/client_manager.go
  backend/src/apiserver/common/config.go
  backend/src/apiserver/common/const.go
  backend/src/apiserver/main.go
  backend/src/apiserver/resource/BUILD.bazel
  backend/src/apiserver/resource/client_manager_fake.go
  backend/src/apiserver/resource/model_converter.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/server/BUILD.bazel
  backend/src/apiserver/server/run_server.go
  backend/src/apiserver/server/run_server_test.go
  backend/src/apiserver/server/test_util.go
  backend/src/apiserver/server/util.go
  backend/src/apiserver/server/util_test.go
Labels: approved, lgtm, size/L

#2703 Improve test cloudbuild yaml readability
  test/cloudbuild/api_server.yaml
  test/cloudbuild/batch_build.yaml
Labels: approved, area/testing, lgtm, size/S

#2712 Fix combined unique keys
  backend/src/apiserver/client_manager.go
  backend/src/apiserver/model/pipeline_version.go
Labels: approved, size/S

#2717 Format other frontend code using prettier
  frontend/.prettierignore
  frontend/backstop.ts
  frontend/mock-backend/hello-world-runtime.ts
  frontend/mock-backend/hello-world-with-steps-runtime.ts
  frontend/mock-backend/integration-test-runtime.ts
  frontend/mock-backend/json-runtime.ts
  frontend/mock-backend/mock-api-middleware.ts
  frontend/mock-backend/mock-coinflip-runtime.ts
  frontend/mock-backend/mock-error-runtime.ts
  frontend/mock-backend/mock-xgboost-runtime.ts
  frontend/mock-backend/mock-xgboost-small-runtime.ts
  frontend/package.json
  frontend/server/aws-helper.ts
  frontend/server/k8s-helper.ts
  frontend/server/minio-helper.ts
  frontend/server/proxy-middleware.ts
  frontend/server/server.ts
  frontend/server/utils.ts
  frontend/server/workflow-helper.ts
  frontend/third_party/argo-ui/argo_template.ts
  frontend/third_party/argo-ui/kubernetes.ts
Labels: approved, area/engprod, area/frontend, lgtm, size/XXL

#2715 update kfam service host env variable
  backend/src/apiserver/client_manager.go
Labels: approved, lgtm, size/XS

#2633 [manifest] Added manifest for deploying on aws using s3
  manifests/kustomize/README.md
  manifests/kustomize/env/aws/README.md
Labels: approved, area/kfctl, lgtm, ok-to-test, size/S

#2723 Metadata: Adding metadata-grpc config map
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/metadata.yaml
  manifests/kustomize/base/metadata/metadata-configmap.yaml
  manifests/kustomize/base/metadata/metadata-deployment.yaml
Labels: approved, lgtm, size/M

#2724 [UI] Fix npm vulnerabilities
  frontend/package-lock.json
  frontend/server/package-lock.json
Labels: approved, area/engprod, area/frontend, lgtm, size/L

#2722 [Doc] Fix links in preload sample
  backend/src/apiserver/config/sample_config.json
Labels: approved, lgtm, size/S

#2709 Add samples to manage Azure Databricks in Kubeflow Pipelines
  samples/contrib/azure-samples/databricks-pipelines/.gitignore
  samples/contrib/azure-samples/databricks-pipelines/README.md
  samples/contrib/azure-samples/databricks-pipelines/databricks_cluster_pipeline.py
  samples/contrib/azure-samples/databricks-pipelines/databricks_job_pipeline.py
  samples/contrib/azure-samples/databricks-pipelines/databricks_run_pipeline.py
  samples/contrib/azure-samples/databricks-pipelines/pipeline_cli.py
  samples/contrib/azure-samples/databricks-pipelines/requirements.txt
  samples/contrib/azure-samples/kfp-azure-databricks/README.md
  samples/contrib/azure-samples/kfp-azure-databricks/databricks/__init__.py
  samples/contrib/azure-samples/kfp-azure-databricks/databricks/_cluster_op.py
  samples/contrib/azure-samples/kfp-azure-databricks/databricks/_job_op.py
  samples/contrib/azure-samples/kfp-azure-databricks/databricks/_run_op.py
  samples/contrib/azure-samples/kfp-azure-databricks/setup.py
  samples/contrib/azure-samples/kfp-azure-databricks/tests/__init__.py
  samples/contrib/azure-samples/kfp-azure-databricks/tests/cluster_spec.json
  samples/contrib/azure-samples/kfp-azure-databricks/tests/job_spec.json
  samples/contrib/azure-samples/kfp-azure-databricks/tests/run_spec.json
  samples/contrib/azure-samples/kfp-azure-databricks/tests/run_tests.sh
  samples/contrib/azure-samples/kfp-azure-databricks/tests/test_cluster_op.py
  samples/contrib/azure-samples/kfp-azure-databricks/tests/test_job_op.py
  samples/contrib/azure-samples/kfp-azure-databricks/tests/test_run_op.py
Labels: approved, area/components, area/samples, lgtm, ok-to-test, size/XXL

#2740 [Test] Pin the versions of coverage and coveralls
  .travis.yml
Labels: approved, lgtm, size/XS

#2733 temporarily disable the jobservice in the multi-user mode
  backend/src/apiserver/server/job_server.go
  backend/src/apiserver/server/visualization_server.go
Labels: approved, lgtm, size/S

#2736 Build - Fix building TF images
  .cloudbuild.yaml
  components/release.sh
Labels: approved, area/testing, lgtm, size/XS

#2694 Separate run resources in namespaces
  backend/src/apiserver/client/BUILD.bazel
  backend/src/apiserver/client/argo.go
  backend/src/apiserver/client/argo_fake.go
  backend/src/apiserver/client/workflow.go
  backend/src/apiserver/client/workflow_fake.go
  backend/src/apiserver/client_manager.go
  backend/src/apiserver/common/BUILD.bazel
  backend/src/apiserver/common/util.go
  backend/src/apiserver/common/util_test.go
  backend/src/apiserver/resource/BUILD.bazel
  backend/src/apiserver/resource/client_manager_fake.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/server/util.go
  backend/src/apiserver/server/util_test.go
  backend/src/common/util/consts.go
  backend/src/common/util/workflow.go
Labels: approved, lgtm, size/L

#2738 Fix obsolete image cache when the same PR commit is tested with a new master
  test/README.md
  test/build-images.sh
  test/postsubmit-tests-with-pipeline-deployment.sh
  test/presubmit-tests-with-pipeline-deployment.sh
Labels: approved, area/testing, kind/bug, lgtm, size/S

#2619 Migrate standalone deployment to workload identity on GCP
  frontend/server/k8s-helper.ts
  manifests/kustomize/gcp-workload-identity-setup.sh
  manifests/kustomize/wi-utils.sh
  samples/contrib/parameterized_tfx_oss/parameterized_tfx_oss.yaml
  samples/core/ai_platform/ai_platform.ipynb
  samples/core/dataflow/dataflow.ipynb
  samples/core/exit_handler/exit_handler.py
  samples/core/kubeflow_tf_serving/kubeflow_tf_serving.ipynb
  samples/core/parallel_join/parallel_join.py
  samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py
  samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py.yaml
  samples/core/secret/secret.py
  samples/core/sequential/sequential.py
  samples/core/volume_snapshot_ops/volume_snapshot_ops.py
  samples/core/xgboost_training_cm/xgboost_training_cm.py
  samples/core/xgboost_training_cm/xgboost_training_cm.yaml
  sdk/python/kfp/containers/_container_builder.py
  sdk/python/kfp/containers/_k8s_job_helper.py
  sdk/python/tests/compiler/testdata/kaniko.basic.yaml
  sdk/python/tests/compiler/testdata/volume_snapshotop_sequential.py
  sdk/python/tests/compiler/testdata/volume_snapshotop_sequential.yaml
  test/build_image.yaml
  test/component_test.yaml
  test/deploy-cluster.sh
  test/deploy-pipeline-lite.sh
  test/e2e_test_gke_v2.yaml
  test/install-argo.sh
  test/postsubmit-tests-with-pipeline-deployment.sh
  test/presubmit-tests-with-pipeline-deployment.sh
  test/sample-test/Dockerfile
  test/sample_test.yaml
  test/test-prep.sh
Labels: approved, area/deployment/standalone, area/testing, lgtm, size/XXL

#2731 Suggest run name based on the pipeline version used to create run
  frontend/src/pages/NewRun.test.tsx
  frontend/src/pages/NewRun.tsx
  frontend/src/pages/__snapshots__/NewRun.test.tsx.snap
Labels: approved, area/frontend, area/ux, lgtm, size/L

#2676 [UI] Pass namespace to APIs
  frontend/server/k8s-helper.ts
  frontend/server/server.ts
  frontend/server/workflow-helper.ts
  frontend/src/apis/job/api.ts
  frontend/src/apis/pipeline/api.ts
  frontend/src/apis/run/api.ts
  frontend/src/lib/Apis.test.ts
  frontend/src/lib/Apis.ts
  frontend/src/lib/KubeflowClient.tsx
  frontend/src/lib/RunUtils.ts
  frontend/src/pages/NewRun.test.tsx
  frontend/src/pages/NewRun.tsx
  frontend/src/pages/PipelineList.test.tsx
  frontend/src/pages/RunDetails.test.tsx
  frontend/src/pages/RunDetails.tsx
  frontend/src/pages/__snapshots__/NewRun.test.tsx.snap
Labels: approved, area/frontend, kind/feature, lgtm, size/XXL

#2734 SDK - Bump version to 0.1.38
  sdk/python/kfp/__init__.py
Labels: approved, area/sdk, lgtm, size/XS

#2683 2682: Support a custom kube config location in K8sJobHelper
  sdk/python/kfp/containers/_k8s_job_helper.py
Labels: approved, area/sdk/client, lgtm, ok-to-test, size/S

#2729 [Sample] Add a notebook sample under parameterized_tfx_oss
  samples/core/parameterized_tfx_oss/taxi_pipeline_notebook.ipynb
Labels: approved, lgtm, size/L

#2748 Move go license tools
  third_party/cli/README.md
  third_party/cli/concatenate_license.py
  third_party/cli/get_github_license_info.py
  third_party/cli/get_github_repo.py
  third_party/cli/parse_toml_dep.py
  third_party/cli/setup.py
Labels: approved, area/engprod, lgtm, size/XL

#2749 Added alpha notice to READMEs for KFP Marketplace
  manifests/gcp_marketplace/README.md
  manifests/gcp_marketplace/guide.md
Labels: approved, lgtm, size/S

#2697 Components - De-hardcoded the UI metadata file path in GCP components
  components/gcp/bigquery/query/component.yaml
  components/gcp/container/component_sdk/python/kfp_component/launcher/__main__.py
  components/gcp/dataflow/launch_python/component.yaml
  components/gcp/dataflow/launch_template/component.yaml
  components/gcp/dataproc/create_cluster/component.yaml
  components/gcp/dataproc/submit_hadoop_job/component.yaml
  components/gcp/dataproc/submit_hive_job/component.yaml
  components/gcp/dataproc/submit_pig_job/component.yaml
  components/gcp/dataproc/submit_pyspark_job/component.yaml
  components/gcp/dataproc/submit_spark_job/component.yaml
  components/gcp/dataproc/submit_sparksql_job/component.yaml
  components/gcp/ml_engine/batch_predict/component.yaml
  components/gcp/ml_engine/deploy/component.yaml
  components/gcp/ml_engine/train/component.yaml
Labels: approved, area/components, lgtm, size/M

#2739 SDK/DSL: Fix PipelineVolume name length
  sdk/python/kfp/dsl/_pipeline_volume.py
  sdk/python/tests/dsl/pipeline_volume_tests.py
Labels: approved, lgtm, size/S

#2727 [Doc] Fix link validation complaint.
  CONTRIBUTING.md
  samples/README.md
Labels: approved, area/docs, lgtm, size/XS

#2759 Revert "Components - De-hardcoded the UI metadata file path in GCP co…
  components/gcp/bigquery/query/component.yaml
  components/gcp/container/component_sdk/python/kfp_component/launcher/__main__.py
  components/gcp/dataflow/launch_python/component.yaml
  components/gcp/dataflow/launch_template/component.yaml
  components/gcp/dataproc/create_cluster/component.yaml
  components/gcp/dataproc/submit_hadoop_job/component.yaml
  components/gcp/dataproc/submit_hive_job/component.yaml
  components/gcp/dataproc/submit_pig_job/component.yaml
  components/gcp/dataproc/submit_pyspark_job/component.yaml
  components/gcp/dataproc/submit_spark_job/component.yaml
  components/gcp/dataproc/submit_sparksql_job/component.yaml
  components/gcp/ml_engine/batch_predict/component.yaml
  components/gcp/ml_engine/deploy/component.yaml
  components/gcp/ml_engine/train/component.yaml
Labels: approved, lgtm, size/M

#2761 Release a8fcec5f702fc2528c87ed6fd698b9cfca8b509e
  components/gcp/bigquery/query/README.md
  components/gcp/bigquery/query/component.yaml
  components/gcp/bigquery/query/sample.ipynb
  components/gcp/container/component_sdk/python/setup.py
  components/gcp/dataflow/launch_python/README.md
  components/gcp/dataflow/launch_python/component.yaml
  components/gcp/dataflow/launch_python/sample.ipynb
  components/gcp/dataflow/launch_template/README.md
  components/gcp/dataflow/launch_template/component.yaml
  components/gcp/dataflow/launch_template/sample.ipynb
  components/gcp/dataproc/create_cluster/README.md
  components/gcp/dataproc/create_cluster/component.yaml
  components/gcp/dataproc/create_cluster/sample.ipynb
  components/gcp/dataproc/delete_cluster/README.md
  components/gcp/dataproc/delete_cluster/component.yaml
  components/gcp/dataproc/delete_cluster/sample.ipynb
  components/gcp/dataproc/submit_hadoop_job/README.md
  components/gcp/dataproc/submit_hadoop_job/component.yaml
  components/gcp/dataproc/submit_hadoop_job/sample.ipynb
  components/gcp/dataproc/submit_hive_job/README.md
  components/gcp/dataproc/submit_hive_job/component.yaml
  components/gcp/dataproc/submit_hive_job/sample.ipynb
  components/gcp/dataproc/submit_pig_job/README.md
  components/gcp/dataproc/submit_pig_job/component.yaml
  components/gcp/dataproc/submit_pig_job/sample.ipynb
  components/gcp/dataproc/submit_pyspark_job/README.md
  components/gcp/dataproc/submit_pyspark_job/component.yaml
  components/gcp/dataproc/submit_pyspark_job/sample.ipynb
  components/gcp/dataproc/submit_spark_job/README.md
  components/gcp/dataproc/submit_spark_job/component.yaml
  components/gcp/dataproc/submit_spark_job/sample.ipynb
  components/gcp/dataproc/submit_sparksql_job/README.md
  components/gcp/dataproc/submit_sparksql_job/component.yaml
  components/gcp/dataproc/submit_sparksql_job/sample.ipynb
  components/gcp/ml_engine/batch_predict/README.md
  components/gcp/ml_engine/batch_predict/component.yaml
  components/gcp/ml_engine/batch_predict/sample.ipynb
  components/gcp/ml_engine/deploy/README.md
  components/gcp/ml_engine/deploy/component.yaml
  components/gcp/ml_engine/deploy/sample.ipynb
  components/gcp/ml_engine/train/README.md
  components/gcp/ml_engine/train/component.yaml
  components/gcp/ml_engine/train/sample.ipynb
  components/kubeflow/deployer/component.yaml
  components/kubeflow/dnntrainer/component.yaml
  components/local/confusion_matrix/component.yaml
  components/local/roc/component.yaml
  samples/core/ai_platform/ai_platform.ipynb
  samples/core/dataflow/dataflow.ipynb
  samples/core/kubeflow_tf_serving/kubeflow_tf_serving.ipynb
  samples/core/xgboost_training_cm/xgboost_training_cm.py
  samples/core/xgboost_training_cm/xgboost_training_cm.yaml
Labels: approved, lgtm, size/L

#2762 update manifest
  manifests/kustomize/base/kustomization.yaml
Labels: approved, lgtm, size/S

#2763 update release changelog
  CHANGELOG.md
Labels: approved, lgtm, size/M

#2760 [Component] Rollforward of PR#2697
  components/gcp/bigquery/query/component.yaml
  components/gcp/container/component_sdk/python/kfp_component/launcher/__main__.py
  components/gcp/container/component_sdk/python/kfp_component/launcher/launcher.py
  components/gcp/dataflow/launch_python/component.yaml
  components/gcp/dataflow/launch_template/component.yaml
  components/gcp/dataproc/create_cluster/component.yaml
  components/gcp/dataproc/submit_hadoop_job/component.yaml
  components/gcp/dataproc/submit_hive_job/component.yaml
  components/gcp/dataproc/submit_pig_job/component.yaml
  components/gcp/dataproc/submit_pyspark_job/component.yaml
  components/gcp/dataproc/submit_spark_job/component.yaml
  components/gcp/dataproc/submit_sparksql_job/component.yaml
  components/gcp/ml_engine/batch_predict/component.yaml
  components/gcp/ml_engine/deploy/component.yaml
  components/gcp/ml_engine/train/component.yaml
Labels: approved, lgtm, size/M

#2752 Add min and max lines for displaying json editor
  frontend/src/components/DetailsTable.tsx
  frontend/src/components/__snapshots__/DetailsTable.test.tsx.snap
Labels: approved, lgtm, ok-to-test, size/M

#2766 [UI] Succeed snackbar shouldn't show when there is an error
  frontend/src/lib/Buttons.ts
  frontend/src/pages/RunDetails.test.tsx
Labels: approved, area/frontend, kind/bug, lgtm, size/S

#2770 Update version in generate_api.sh
  backend/api/generate_api.sh
  backend/api/swagger/kfp_api_single_file.swagger.json
  backend/src/apiserver/BUILD.bazel
  backend/src/apiserver/client/BUILD.bazel
  backend/src/apiserver/common/BUILD.bazel
  backend/src/apiserver/model/BUILD.bazel
  backend/src/apiserver/resource/BUILD.bazel
  backend/src/apiserver/server/BUILD.bazel
Labels: lgtm, size/M

#2668 support extra parameters for mysql connection
  backend/src/apiserver/client/sql.go
  backend/src/apiserver/client/sql_test.go
  backend/src/apiserver/client_manager.go
  backend/src/apiserver/common/config.go
Labels: approved, lgtm, size/L

#2772 [Standalone] Fix GCP cloudsql manifest
  manifests/kustomize/env/gcp/gcp-configurations-patch.yaml
Labels: approved, area/deployment/standalone, kind/bug, lgtm, size/S

#2774 [UI] Fix UI crash when invalid pipeline uploaded
  frontend/src/components/Graph.test.tsx
  frontend/src/components/Graph.tsx
  frontend/src/components/__snapshots__/Graph.test.tsx.snap
  frontend/src/pages/PipelineDetails.test.tsx
  frontend/src/pages/PipelineDetails.tsx
  frontend/src/pages/RunDetails.test.tsx
  frontend/src/pages/RunDetails.tsx
  frontend/src/pages/__snapshots__/PipelineDetails.test.tsx.snap
  frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
Labels: approved, area/frontend, kind/bug, lgtm, size/XL

#2776 Fix vscode README of prettier integration
  frontend/README.md
Labels: approved, lgtm, size/XS

#2775 [Sample] Clean up accidentally committed file
  samples/contrib/parameterized_tfx_oss/parameterized_tfx_oss.yaml
  samples/core/xgboost_training_cm/xgboost_training_cm.yaml
Labels: approved, kind/process, lgtm, size/XXL

#2689 SDK - Unified the function signature parsing implementations
  sdk/python/kfp/components/_python_op.py
  sdk/python/kfp/dsl/_component.py
  sdk/python/kfp/dsl/_metadata.py
  sdk/python/kfp/dsl/_pipeline.py
  sdk/python/kfp/dsl/types.py
  sdk/python/tests/compiler/testdata/artifact_location.yaml
  sdk/python/tests/compiler/testdata/basic.yaml
  sdk/python/tests/compiler/testdata/imagepullsecrets.yaml
  sdk/python/tests/components/test_python_op.py
  sdk/python/tests/dsl/component_tests.py
  sdk/python/tests/dsl/pipeline_tests.py
  sdk/python/tests/dsl/type_tests.py
Labels: approved, area/sdk/dsl, area/sdk/dsl/compiler, lgtm, size/L

#2779 [Components] Roll forward of #2697 for real.
  components/gcp/container/component_sdk/python/kfp_component/launcher/__main__.py
  components/gcp/container/component_sdk/python/kfp_component/launcher/launcher.py
Labels: approved, lgtm, size/XS

#2711 [SDK/compiler] Sanitize op name for PipelineParam
  sdk/python/kfp/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/loop_over_lightweight_output.py
  sdk/python/tests/compiler/testdata/loop_over_lightweight_output.yaml
Labels: approved, lgtm, size/L

#2785 [Manifest] Bump standalone deployment version in doc
  manifests/kustomize/README.md
Labels: approved, lgtm, size/XS

#2777 Use new K8s version to improve workload identity stability
  test/deploy-cluster.sh
Labels: approved, area/deployment/standalone, area/testing, lgtm, size/XS
