Repository kubeflow/pipelines, pull requests merged in 2019-07, with the labels that each got.

#1579 Pass dataset_location to container
  components/gcp/bigquery/query/component.yaml
Labels: approved, lgtm, size/XS

#1581 Release 2d0d8619507743ec4ff1e213735a8f82d3913281
  components/dataflow/predict/component.yaml
  components/dataflow/tfdv/component.yaml
  components/dataflow/tfma/component.yaml
  components/dataflow/tft/component.yaml
  components/gcp/bigquery/query/README.md
  components/gcp/bigquery/query/component.yaml
  components/gcp/bigquery/query/sample.ipynb
  components/gcp/dataflow/launch_python/README.md
  components/gcp/dataflow/launch_python/component.yaml
  components/gcp/dataflow/launch_python/sample.ipynb
  components/gcp/dataflow/launch_template/README.md
  components/gcp/dataflow/launch_template/component.yaml
  components/gcp/dataflow/launch_template/sample.ipynb
  components/gcp/dataproc/create_cluster/README.md
  components/gcp/dataproc/create_cluster/component.yaml
  components/gcp/dataproc/create_cluster/sample.ipynb
  components/gcp/dataproc/delete_cluster/README.md
  components/gcp/dataproc/delete_cluster/component.yaml
  components/gcp/dataproc/delete_cluster/sample.ipynb
  components/gcp/dataproc/submit_hadoop_job/README.md
  components/gcp/dataproc/submit_hadoop_job/component.yaml
  components/gcp/dataproc/submit_hadoop_job/sample.ipynb
  components/gcp/dataproc/submit_hive_job/README.md
  components/gcp/dataproc/submit_hive_job/component.yaml
  components/gcp/dataproc/submit_hive_job/sample.ipynb
  components/gcp/dataproc/submit_pig_job/README.md
  components/gcp/dataproc/submit_pig_job/component.yaml
  components/gcp/dataproc/submit_pig_job/sample.ipynb
  components/gcp/dataproc/submit_pyspark_job/README.md
  components/gcp/dataproc/submit_pyspark_job/component.yaml
  components/gcp/dataproc/submit_pyspark_job/sample.ipynb
  components/gcp/dataproc/submit_spark_job/README.md
  components/gcp/dataproc/submit_spark_job/component.yaml
  components/gcp/dataproc/submit_spark_job/sample.ipynb
  components/gcp/dataproc/submit_sparksql_job/README.md
  components/gcp/dataproc/submit_sparksql_job/component.yaml
  components/gcp/dataproc/submit_sparksql_job/sample.ipynb
  components/gcp/ml_engine/batch_predict/README.md
  components/gcp/ml_engine/batch_predict/component.yaml
  components/gcp/ml_engine/batch_predict/sample.ipynb
  components/gcp/ml_engine/deploy/README.md
  components/gcp/ml_engine/deploy/component.yaml
  components/gcp/ml_engine/deploy/sample.ipynb
  components/gcp/ml_engine/train/README.md
  components/gcp/ml_engine/train/component.yaml
  components/gcp/ml_engine/train/sample.ipynb
  components/kubeflow/deployer/component.yaml
  components/kubeflow/dnntrainer/component.yaml
  components/kubeflow/launcher/kubeflow_tfjob_launcher_op.py
  components/kubeflow/launcher/src/train.template.yaml
  components/local/confusion_matrix/component.yaml
  components/local/roc/component.yaml
  samples/ai-platform/Chicago Crime Pipeline.ipynb
  samples/kubeflow-tf/kubeflow-training-classification.py
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
  samples/resnet-cmle/resnet-train-pipeline.py
  samples/tfx/taxi-cab-classification-pipeline.py
  samples/xgboost-spark/xgboost-training-cm.py
Labels: approved, lgtm, size/L

#1583 fix recursion bug
  sdk/python/kfp/compiler/compiler.py
  sdk/python/tests/compiler/testdata/recursive_while.py
  sdk/python/tests/compiler/testdata/recursive_while.yaml
Labels: approved, lgtm, size/M

#1576 Add PV/PVC admin permission for pipeline runner
  manifests/base/pipeline/pipeline-runner-role.yaml
Labels: approved, lgtm, size/XS

#1570 Manifests: Update pipeline-runner permissions
  manifests/base/pipeline/pipeline-runner-role.yaml
Labels: approved, lgtm, size/XS

#1587 Update Watson training component to output model location UID
  components/ibm-components/watson/train/component.yaml
  components/ibm-components/watson/train/src/wml-train.py
  samples/ibm-samples/watson/watson_train_serve_pipeline.py
Labels: approved, lgtm, needs-ok-to-test, size/S

#1562 Viewer CRD controller running under namespace
  backend/Dockerfile.viewercontroller
  backend/src/crd/controller/viewer/BUILD.bazel
  backend/src/crd/controller/viewer/main.go
  manifests/namespaced-install.yaml
  manifests/namespaced-install/kustomization.yaml
  manifests/namespaced-install/ml-pipeline-viewer-crd-deployment-patch.yaml
Labels: approved, lgtm, size/M

#1540 add_pod_env op handler
  sdk/python/kfp/compiler/_default_transformers.py
  sdk/python/kfp/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/add_pod_env.py
  sdk/python/tests/compiler/testdata/add_pod_env.yaml
Labels: approved, lgtm, size/L

#1603 Set user credentials when creating viewer object
  frontend/server/k8s-helper.ts
Labels: approved, lgtm, size/S

#1588 List pipelines
  sdk/python/kfp/_client.py
Labels: approved, lgtm, size/M

#1565 Add Visualization API endpoint
  backend/api/visualization.proto
Labels: approved, lgtm, size/L

#1614 Release ac833a084b32324b56ca56e9109e05cde02816a4
  components/dataflow/predict/component.yaml
  components/dataflow/tfdv/component.yaml
  components/dataflow/tfma/component.yaml
  components/dataflow/tft/component.yaml
  components/gcp/bigquery/query/README.md
  components/gcp/bigquery/query/component.yaml
  components/gcp/bigquery/query/sample.ipynb
  components/gcp/dataflow/launch_python/README.md
  components/gcp/dataflow/launch_python/component.yaml
  components/gcp/dataflow/launch_python/sample.ipynb
  components/gcp/dataflow/launch_template/README.md
  components/gcp/dataflow/launch_template/component.yaml
  components/gcp/dataflow/launch_template/sample.ipynb
  components/gcp/dataproc/create_cluster/README.md
  components/gcp/dataproc/create_cluster/component.yaml
  components/gcp/dataproc/create_cluster/sample.ipynb
  components/gcp/dataproc/delete_cluster/README.md
  components/gcp/dataproc/delete_cluster/component.yaml
  components/gcp/dataproc/delete_cluster/sample.ipynb
  components/gcp/dataproc/submit_hadoop_job/README.md
  components/gcp/dataproc/submit_hadoop_job/component.yaml
  components/gcp/dataproc/submit_hadoop_job/sample.ipynb
  components/gcp/dataproc/submit_hive_job/README.md
  components/gcp/dataproc/submit_hive_job/component.yaml
  components/gcp/dataproc/submit_hive_job/sample.ipynb
  components/gcp/dataproc/submit_pig_job/README.md
  components/gcp/dataproc/submit_pig_job/component.yaml
  components/gcp/dataproc/submit_pig_job/sample.ipynb
  components/gcp/dataproc/submit_pyspark_job/README.md
  components/gcp/dataproc/submit_pyspark_job/component.yaml
  components/gcp/dataproc/submit_pyspark_job/sample.ipynb
  components/gcp/dataproc/submit_spark_job/README.md
  components/gcp/dataproc/submit_spark_job/component.yaml
  components/gcp/dataproc/submit_spark_job/sample.ipynb
  components/gcp/dataproc/submit_sparksql_job/README.md
  components/gcp/dataproc/submit_sparksql_job/component.yaml
  components/gcp/dataproc/submit_sparksql_job/sample.ipynb
  components/gcp/ml_engine/batch_predict/README.md
  components/gcp/ml_engine/batch_predict/component.yaml
  components/gcp/ml_engine/batch_predict/sample.ipynb
  components/gcp/ml_engine/deploy/README.md
  components/gcp/ml_engine/deploy/component.yaml
  components/gcp/ml_engine/deploy/sample.ipynb
  components/gcp/ml_engine/train/README.md
  components/gcp/ml_engine/train/component.yaml
  components/gcp/ml_engine/train/sample.ipynb
  components/kubeflow/deployer/component.yaml
  components/kubeflow/dnntrainer/component.yaml
  components/kubeflow/launcher/kubeflow_tfjob_launcher_op.py
  components/kubeflow/launcher/src/train.template.yaml
  components/local/confusion_matrix/component.yaml
  components/local/roc/component.yaml
  samples/ai-platform/Chicago Crime Pipeline.ipynb
  samples/kubeflow-tf/kubeflow-training-classification.py
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
  samples/resnet-cmle/resnet-train-pipeline.py
  samples/tfx/taxi-cab-classification-pipeline.py
  samples/xgboost-spark/xgboost-training-cm.py
Labels: approved, lgtm, size/L

#1616 fix dependency bug in the recursion support
  sdk/python/kfp/compiler/compiler.py
Labels: approved, lgtm, size/XS

#1617 update manifest and sdk version
  component_sdk/python/setup.py
  manifests/base/kustomization.yaml
  manifests/namespaced-install.yaml
  sdk/python/setup.py
Labels: approved, lgtm, size/L

#1607 Update samples to use the latest versions of the python SDK
  samples/ai-platform/Chicago Crime Pipeline.ipynb
  samples/ibm-samples/ffdl-seldon/ffdl_pipeline.ipynb
  samples/notebooks/DSL Static Type Checking.ipynb
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
  samples/notebooks/Lightweight Python components - basics.ipynb
  samples/notebooks/Local Development Quickstart.ipynb
  samples/nvidia-resnet/pipeline/Dockerfile
  samples/tfx-oss/README.md
  samples/tfx-oss/TFX Example.ipynb
Labels: approved, lgtm, size/M

#1623 viewer controller is now namespaced so no need for cluster role
  backend/src/crd/controller/viewer/reconciler/reconciler.go
  manifests/base/pipeline/ml-pipeline-viewer-crd-role.yaml
  manifests/base/pipeline/ml-pipeline-viewer-crd-rolebinding.yaml
  manifests/namespaced-install.yaml
Labels: approved, lgtm, size/S

#1625 Removed duplicate CircularProgress within UI
  frontend/src/pages/RunDetails.tsx
  frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
Labels: approved, lgtm, size/XS

#1622 switch third party images to GCR
  developer_guide.md
  manifests/base/argo/workflow-controller-configmap.yaml
  manifests/base/argo/workflow-controller-deployment.yaml
  manifests/base/minio/minio-deployment.yaml
  manifests/base/mysql/mysql-deployment.yaml
  manifests/namespaced-install.yaml
  manifests/namespaced-install/workflow-controller-configmap.yaml
Labels: approved, lgtm, size/S

#1293 add support for flexible config (via env var) for the pipline service and UI, fix broken links (pointed to API vs UI service)
  sdk/python/kfp/_client.py
Labels: approved, lgtm, ok-to-test, size/S

#1633 Add OWNERS file in aws components and examples
  components/aws/OWNERS
  samples/aws-samples/OWNERS
Labels: approved, lgtm, size/S

#1627 propagate database password when init db connection
  backend/src/apiserver/client/sql.go
Labels: approved, lgtm, size/XS

#1605 Trims whitespace from pipeline params on creation of new run
  frontend/src/pages/NewRun.test.tsx
  frontend/src/pages/NewRun.tsx
Labels: approved, area/front-end, lgtm, size/M

#1618 update changelog
  CHANGELOG.md
Labels: approved, lgtm, size/M

#1595 SDK/DSL: Fix bug when specifying custom resource for VolumeOp
  sdk/python/kfp/dsl/_volume_op.py
Labels: approved, lgtm, size/XS

#1542 Add gcp-connector label and remove pod name
  components/gcp/bigquery/query/component.yaml
  components/gcp/dataflow/launch_python/component.yaml
  components/gcp/dataflow/launch_template/component.yaml
  components/gcp/dataproc/create_cluster/component.yaml
  components/gcp/dataproc/delete_cluster/component.yaml
  components/gcp/dataproc/submit_hadoop_job/component.yaml
  components/gcp/dataproc/submit_hive_job/component.yaml
  components/gcp/dataproc/submit_pig_job/component.yaml
  components/gcp/dataproc/submit_pyspark_job/component.yaml
  components/gcp/dataproc/submit_spark_job/component.yaml
  components/gcp/dataproc/submit_sparksql_job/component.yaml
  components/gcp/ml_engine/batch_predict/component.yaml
  components/gcp/ml_engine/deploy/component.yaml
  components/gcp/ml_engine/train/component.yaml
Labels: approved, lgtm, size/M

#1636 Changed arguments parameter type and built visualization pb and swagger files
  backend/api/BUILD.bazel
  backend/api/go_client/BUILD.bazel
  backend/api/go_client/visualization.pb.go
  backend/api/go_client/visualization.pb.gw.go
  backend/api/swagger/visualization.swagger.json
  backend/api/visualization.proto
Labels: approved, lgtm, size/XL

#1635 Add recurring run column to run lists
  frontend/src/lib/RunUtils.ts
  frontend/src/pages/RunList.test.tsx
  frontend/src/pages/RunList.tsx
  frontend/src/pages/__snapshots__/RunList.test.tsx.snap
Labels: approved, area/front-end, lgtm, size/XXL

#1649 update python test to use python3
  .travis.yml
Labels: approved, lgtm, size/XS

#1634 update persistent agence to only store the argo spec
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/common/util/workflow.go
  backend/src/common/util/workflow_test.go
Labels: approved, lgtm, size/S

#1577 tox.ini: Add flake8 tests to find Python syntax errors and undefined names
  component_sdk/python/test-requirements.txt
  component_sdk/python/tox.ini
Labels: approved, lgtm, ok-to-test, size/XS

#1502 Remove legacy hardcoded version of TFX
  samples/tfx-oss/README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1650 add init container for container op
  sdk/python/kfp/compiler/_op_to_template.py
  sdk/python/kfp/dsl/__init__.py
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/dsl/container_op_tests.py
Labels: approved, lgtm, size/L

#1631 Samples - Cleaned up unnecessary usage of PipelineParam
  contrib/samples/openvino/deployer/deployer.py
  contrib/samples/openvino/predict/numpy_predict.py
  contrib/samples/openvino/tf-slim/tf-slim.py
  samples/ai-platform/Chicago Crime Pipeline.ipynb
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
  samples/notebooks/Local Development Quickstart.ipynb
  sdk/python/tests/compiler/testdata/param_op_transform.py
  sdk/python/tests/components/test_python_op.py
Labels: approved, area/samples, lgtm, size/L

#1652 update kaniko executor version to speed up image build
  sdk/python/kfp/compiler/_component_builder.py
  sdk/python/tests/compiler/testdata/kaniko.basic.yaml
Labels: approved, lgtm, size/XS

#1591 Added image captioning sample to samples/notebooks
  samples/notebooks/image-captioning-gcp/Image Captioning TF 2.0.ipynb
  samples/notebooks/image-captioning-gcp/README.md
  samples/notebooks/image-captioning-gcp/src/Dockerfile
  samples/notebooks/image-captioning-gcp/src/models.py
Labels: approved, lgtm, ok-to-test, size/XXL

#1630 Samples - Removed the immediate_value sample
  samples/basic/immediate_value.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/immediate_value.py
  sdk/python/tests/compiler/testdata/immediate_value.yaml
  test/e2e_test_gke_v2.yaml
  test/sample-test/run_test.sh
Labels: approved, area/samples, lgtm, size/L

#1655 Fix broken license link
  components/third_party_licenses.csv
Labels: approved, lgtm, size/XS

#1594 [Feature] Set ttlSecondsAfterFinished in argo workflow with PipelineConf
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/dsl/_pipeline.py
  sdk/python/tests/compiler/compiler_tests.py
Labels: approved, lgtm, needs-ok-to-test, size/M

#1637 Sets min widths for buttons to avoid text wrapping
  frontend/src/components/Toolbar.tsx
  frontend/src/lib/Buttons.ts
  frontend/src/pages/__snapshots__/AllRunsList.test.tsx.snap
  frontend/src/pages/__snapshots__/ExperimentDetails.test.tsx.snap
Labels: approved, area/front-end, lgtm, size/M

#1658 move gcshelper out of component_builder
  sdk/python/kfp/compiler/_component_builder.py
  sdk/python/kfp/compiler/_gcs_helper.py
  sdk/python/tests/compiler/component_builder_test.py
Labels: approved, lgtm, size/M

#1665 Fix exit handler sample
  samples/basic/exit_handler.py
Labels: approved, lgtm, size/XS

#1666 Adding kfp.cil to kfp setup.py.
  sdk/python/setup.py
Labels: approved, lgtm, size/XS

#1647 Add visualization server and unit tests for visualization server
  backend/src/apiserver/main.go
  backend/src/apiserver/server/BUILD.bazel
  backend/src/apiserver/server/visualization_server.go
  backend/src/apiserver/server/visualization_server_test.go
Labels: approved, lgtm, size/L

#1663 Add visualization swagger files to frontend
  frontend/package.json
  frontend/src/apis/visualization/.gitignore
  frontend/src/apis/visualization/.swagger-codegen-ignore
  frontend/src/apis/visualization/.swagger-codegen/VERSION
  frontend/src/apis/visualization/api.ts
  frontend/src/apis/visualization/configuration.ts
  frontend/src/apis/visualization/custom.d.ts
  frontend/src/apis/visualization/git_push.sh
  frontend/src/apis/visualization/index.ts
Labels: approved, lgtm, size/L

#1672 Release fe639f41661d8e17fcda64ff8242127620b80ba0
  components/dataflow/predict/component.yaml
  components/dataflow/tfdv/component.yaml
  components/dataflow/tfma/component.yaml
  components/dataflow/tft/component.yaml
  components/gcp/bigquery/query/README.md
  components/gcp/bigquery/query/component.yaml
  components/gcp/bigquery/query/sample.ipynb
  components/gcp/dataflow/launch_python/README.md
  components/gcp/dataflow/launch_python/component.yaml
  components/gcp/dataflow/launch_python/sample.ipynb
  components/gcp/dataflow/launch_template/README.md
  components/gcp/dataflow/launch_template/component.yaml
  components/gcp/dataflow/launch_template/sample.ipynb
  components/gcp/dataproc/create_cluster/README.md
  components/gcp/dataproc/create_cluster/component.yaml
  components/gcp/dataproc/create_cluster/sample.ipynb
  components/gcp/dataproc/delete_cluster/README.md
  components/gcp/dataproc/delete_cluster/component.yaml
  components/gcp/dataproc/delete_cluster/sample.ipynb
  components/gcp/dataproc/submit_hadoop_job/README.md
  components/gcp/dataproc/submit_hadoop_job/component.yaml
  components/gcp/dataproc/submit_hadoop_job/sample.ipynb
  components/gcp/dataproc/submit_hive_job/README.md
  components/gcp/dataproc/submit_hive_job/component.yaml
  components/gcp/dataproc/submit_hive_job/sample.ipynb
  components/gcp/dataproc/submit_pig_job/README.md
  components/gcp/dataproc/submit_pig_job/component.yaml
  components/gcp/dataproc/submit_pig_job/sample.ipynb
  components/gcp/dataproc/submit_pyspark_job/README.md
  components/gcp/dataproc/submit_pyspark_job/component.yaml
  components/gcp/dataproc/submit_pyspark_job/sample.ipynb
  components/gcp/dataproc/submit_spark_job/README.md
  components/gcp/dataproc/submit_spark_job/component.yaml
  components/gcp/dataproc/submit_spark_job/sample.ipynb
  components/gcp/dataproc/submit_sparksql_job/README.md
  components/gcp/dataproc/submit_sparksql_job/component.yaml
  components/gcp/dataproc/submit_sparksql_job/sample.ipynb
  components/gcp/ml_engine/batch_predict/README.md
  components/gcp/ml_engine/batch_predict/component.yaml
  components/gcp/ml_engine/batch_predict/sample.ipynb
  components/gcp/ml_engine/deploy/README.md
  components/gcp/ml_engine/deploy/component.yaml
  components/gcp/ml_engine/deploy/sample.ipynb
  components/gcp/ml_engine/train/README.md
  components/gcp/ml_engine/train/component.yaml
  components/gcp/ml_engine/train/sample.ipynb
  components/kubeflow/deployer/component.yaml
  components/kubeflow/dnntrainer/component.yaml
  components/kubeflow/launcher/kubeflow_tfjob_launcher_op.py
  components/kubeflow/launcher/src/train.template.yaml
  components/local/confusion_matrix/component.yaml
  components/local/roc/component.yaml
  samples/ai-platform/Chicago Crime Pipeline.ipynb
  samples/kubeflow-tf/kubeflow-training-classification.py
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
  samples/resnet-cmle/resnet-train-pipeline.py
  samples/tfx/taxi-cab-classification-pipeline.py
  samples/xgboost-spark/xgboost-training-cm.py
Labels: approved, lgtm, size/L

#1675 Add visualization API service to frontend
  frontend/src/lib/Apis.test.ts
  frontend/src/lib/Apis.ts
Labels: approved, lgtm, size/S

#1656 Remove redundant import.
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
Labels: approved, lgtm, ok-to-test, size/XS

#1626 SDK - Lightweight - Added support for "None" default values
  sdk/python/kfp/components/_python_op.py
  sdk/python/kfp/components/_structures.py
  sdk/python/tests/components/test_python_op.py
Labels: approved, area/sdk, lgtm, size/M

#1674 Increase KFP version in (1) sdk/python/setup.py (2) component_sdk/python/setup.py (3) manifests/base/kustomization.yaml
  component_sdk/python/setup.py
  manifests/base/kustomization.yaml
  sdk/python/setup.py
Labels: approved, lgtm, size/S

#1684 Increase version in namespaced-install.yaml too
  manifests/namespaced-install.yaml
Labels: approved, lgtm, size/L

#1677 Add new PlotType to Allow for Visualization Creation
  frontend/src/components/viewers/Viewer.ts
  frontend/src/components/viewers/ViewerContainer.tsx
  frontend/src/components/viewers/VisualizationCreator.test.tsx
  frontend/src/components/viewers/VisualizationCreator.tsx
  frontend/src/components/viewers/__snapshots__/ViewerContainer.test.tsx.snap
  frontend/src/components/viewers/__snapshots__/VisualizationCreator.test.tsx.snap
Labels: approved, lgtm, size/XL

#1689 Clears the workflow's name in GetWorkflowSpec and uses it for the GenerateName
  backend/src/common/util/workflow.go
  backend/src/common/util/workflow_test.go
Labels: approved, area/back-end, lgtm, size/M

#1679 Separate codegen from containerbuild
  sdk/python/kfp/compiler/_component_builder.py
  sdk/python/tests/compiler/component_builder_test.py
Labels: approved, lgtm, size/XL

#1682 Update SageMaker components and sample pipeline
  components/aws/sagemaker/batch_transform/component.yaml
  components/aws/sagemaker/batch_transform/src/batch_transform.py
  components/aws/sagemaker/common/_utils.py
  components/aws/sagemaker/common/endpoint_config.template.yaml
  components/aws/sagemaker/common/model.template.yaml
  components/aws/sagemaker/common/train.template.yaml
  components/aws/sagemaker/common/transform.template.yaml
  components/aws/sagemaker/deploy/component.yaml
  components/aws/sagemaker/deploy/src/deploy.py
  components/aws/sagemaker/hyperparameter_tuning/Dockerfile
  components/aws/sagemaker/hyperparameter_tuning/README.md
  components/aws/sagemaker/hyperparameter_tuning/component.yaml
  components/aws/sagemaker/hyperparameter_tuning/src/hyperparameter_tuning.py
  components/aws/sagemaker/model/component.yaml
  components/aws/sagemaker/model/src/create_model.py
  components/aws/sagemaker/train/component.yaml
  components/aws/sagemaker/train/src/train.py
  samples/aws-samples/mnist-kmeans-sagemaker/README.md
  samples/aws-samples/mnist-kmeans-sagemaker/mnist-classification-pipeline.py
Labels: approved, lgtm, ok-to-test, size/XXL

#1680 Separate codegen from containerbuild 2
  sdk/python/kfp/compiler/_component_builder.py
  sdk/python/kfp/compiler/_container_builder.py
  sdk/python/tests/compiler/component_builder_test.py
  sdk/python/tests/compiler/container_builder_test.py
  sdk/python/tests/compiler/main.py
Labels: approved, lgtm, size/L

#1695 Changelog 0.1.25
  CHANGELOG.md
Labels: approved, lgtm, size/M

#1709 Simplify sample_test.yaml
  test/sample_test.yaml
Labels: approved, lgtm, size/L

#1705 add jxzheng to the reviewers for samples
  samples/OWNERS
Labels: approved, lgtm, size/XS

#1703 Component build fix
  sdk/python/kfp/compiler/_container_builder.py
  sdk/python/tests/compiler/container_builder_test.py
Labels: approved, lgtm, size/S
