Repository kubeflow/pipelines, pull requests merged in 2019-09, with the labels that each got.

#1993 add connection for inverse proxy
  sdk/python/kfp/_auth.py
  sdk/python/kfp/_client.py
Labels: approved, lgtm, size/S

#2022 update release cb yaml
  .release.cloudbuild.yaml
Labels: approved, lgtm, size/M

#2023 update service account for non managed storage case
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml
Labels: approved, lgtm, size/XS

#2009 Change schema.yaml to v2
  manifests/gcp_marketplace/chart/kubeflow-pipelines/values.yaml
  manifests/gcp_marketplace/deployer/Dockerfile
  manifests/gcp_marketplace/schema.yaml
Labels: approved, lgtm, size/L

#1521 SDK - Added kfp.run_pipeline_func_on_cluster function (alias)
  sdk/python/kfp/__init__.py
  sdk/python/kfp/_runners.py
Labels: approved, area/sdk, lgtm, size/M

#2021 Add readme and update application parameter
  manifests/gcp_marketplace/README.md
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/argo.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/metadata.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/mysql.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/proxy.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/values.yaml
  manifests/gcp_marketplace/schema.yaml
  manifests/kustomize/env/gcp/gcp-configurations-patch.yaml
  manifests/kustomize/env/gcp/mysql/cloudsql-proxy-deployment.yaml
Labels: approved, lgtm, size/L

#2017 api: fix generate_api.sh script with bash shebang
  backend/api/generate_api.sh
Labels: approved, lgtm, size/XS

#2026 Add guideline for including a sample in sample test
  samples/README.md
Labels: approved, lgtm, size/S

#2006 remove the bigquery components to fabvor the new gcp components
  components/bigquery/base/Dockerfile
  components/bigquery/base/build_image.sh
  components/bigquery/query/Dockerfile
  components/bigquery/query/build_image.sh
  components/bigquery/query/src/query.py
Labels: approved, lgtm, size/L

#1973 manifest/metadata: Switching to use metadata grpc server
  manifests/kustomize/base/metadata/kustomization.yaml
  manifests/kustomize/base/metadata/metadata-deployment.yaml
  manifests/kustomize/base/metadata/mlmd-server-configmap.yaml
Labels: approved, lgtm, size/M

#1889 SDK - Switching python container components to Lightweight components code generator
  sdk/python/kfp/compiler/_component_builder.py
  sdk/python/tests/compiler/component_builder_test.py
Labels: approved, area/sdk/components/python_container_op, lgtm, size/L

#1989 Print cloud build logs when the task fails
  test/check-build-image-status.sh
  test/presubmit-tests-with-pipeline-deployment.sh
Labels: approved, area/testing, lgtm, size/XS

#2019 Extend E2E tests: Add VolumeOp test
  samples/core/volume_ops/volume_ops.py
  test/e2e_test_gke_v2.yaml
  test/sample-test/configs/volume_ops.config.yaml
Labels: approved, area/testing, lgtm, size/S

#2025 SDK: fix setting pipeline-wide artifact_location for ResourceOp and VolumeOp classes and add description field for create_experiment() function
  sdk/python/kfp/_client.py
  sdk/python/kfp/compiler/compiler.py
Labels: approved, lgtm, needs-ok-to-test, size/S

#2037 Fix Local Development Quickstart sample
  samples/contrib/local_development_quickstart/Local Development Quickstart.ipynb
Labels: approved, lgtm, size/M

#2018 SDK/DSL: Fix bug when using PipelineParam in `pvc` of PipelineVolume
  sdk/python/kfp/dsl/_pipeline_volume.py
  sdk/python/tests/dsl/pipeline_volume_tests.py
Labels: approved, lgtm, size/S

#2038 SDK - Testing - Make dsl and compiler tests discoverable by unittest
  sdk/python/tests/compiler/__init__.py
  sdk/python/tests/dsl/__init__.py
Labels: approved, area/sdk, lgtm, size/XS

#2034 SDK - Refactoring - Reduced the usage of dsl.Pipeline context
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/dsl/_metadata.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/dsl/aws_extensions_tests.py
  sdk/python/tests/dsl/container_op_tests.py
  sdk/python/tests/dsl/pipeline_volume_tests.py
  sdk/python/tests/dsl/resource_op_tests.py
  sdk/python/tests/dsl/test_azure_extensions.py
  sdk/python/tests/dsl/volume_op_tests.py
  sdk/python/tests/dsl/volume_snapshotop_tests.py
Labels: approved, area/sdk, lgtm, size/XL

#2053 Removing ResNet-CMLE sample
  samples/contrib/resnet-cmle/README.md
  samples/contrib/resnet-cmle/build_pipeline.sh
  samples/contrib/resnet-cmle/preprocess/preprocess.py
  samples/contrib/resnet-cmle/preprocess/requirements.txt
  samples/contrib/resnet-cmle/resnet-train-pipeline.py
  samples/contrib/resnet-cmle/resnet_model/setup.py
  samples/contrib/resnet-cmle/resnet_model/trainer/__init__.py
  samples/contrib/resnet-cmle/resnet_model/trainer/imagenet_input.py
  samples/contrib/resnet-cmle/resnet_model/trainer/resnet_main.py
  samples/contrib/resnet-cmle/resnet_model/trainer/resnet_model.py
  samples/contrib/resnet-cmle/resnet_model/trainer/resnet_preprocessing.py
Labels: approved, lgtm, size/XXL

#1972 Fix python syntax of TFMA visualization
  backend/src/apiserver/visualization/types/tfma.py
Labels: approved, lgtm, size/XS

#2042 SDK - Compiler - Fixed handling of PipelineParams in artifact arguments
  sdk/python/kfp/compiler/_op_to_template.py
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/tests/compiler/testdata/input_artifact_raw_value.yaml
Labels: approved, area/sdk/components, lgtm, size/M

#2046 SDK - Compiler - Stopped adding mlpipeline artifacts to every compiled template
  components/arena/docker/arena_launcher.py
  components/dataflow/predict/component.yaml
  components/dataflow/tfma/component.yaml
  components/gcp/bigquery/query/component.yaml
  components/gcp/dataflow/launch_python/component.yaml
  components/gcp/dataflow/launch_template/component.yaml
  components/gcp/dataproc/create_cluster/component.yaml
  components/gcp/dataproc/submit_hadoop_job/component.yaml
  components/gcp/dataproc/submit_hive_job/component.yaml
  components/gcp/dataproc/submit_pig_job/component.yaml
  components/gcp/dataproc/submit_pyspark_job/component.yaml
  components/gcp/dataproc/submit_spark_job/component.yaml
  components/gcp/dataproc/submit_sparksql_job/component.yaml
  components/gcp/ml_engine/batch_predict/component.yaml
  components/gcp/ml_engine/deploy/component.yaml
  components/gcp/ml_engine/train/component.yaml
  components/kubeflow/dnntrainer/component.yaml
  components/kubeflow/launcher/kubeflow_tfjob_launcher_op.py
  components/local/confusion_matrix/component.yaml
  components/local/roc/component.yaml
  samples/contrib/local_development_quickstart/Local Development Quickstart.ipynb
  samples/core/lightweight_component/Lightweight Python components - basics.ipynb
  samples/core/tfx_cab_classification/tfx_cab_classification.py
  samples/core/xgboost_training_cm/xgboost_training_cm.py
  sdk/python/kfp/compiler/_op_to_template.py
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/add_pod_env.yaml
  sdk/python/tests/compiler/testdata/artifact_location.py
  sdk/python/tests/compiler/testdata/artifact_location.yaml
  sdk/python/tests/compiler/testdata/basic.yaml
  sdk/python/tests/compiler/testdata/coin.yaml
  sdk/python/tests/compiler/testdata/compose.yaml
  sdk/python/tests/compiler/testdata/default_value.yaml
  sdk/python/tests/compiler/testdata/imagepullsecrets.yaml
  sdk/python/tests/compiler/testdata/input_artifact_raw_value.yaml
  sdk/python/tests/compiler/testdata/param_op_transform.yaml
  sdk/python/tests/compiler/testdata/param_substitutions.yaml
  sdk/python/tests/compiler/testdata/pipelineparams.yaml
  sdk/python/tests/compiler/testdata/preemptible_tpu_gpu.yaml
  sdk/python/tests/compiler/testdata/recursive_do_while.yaml
  sdk/python/tests/compiler/testdata/recursive_while.yaml
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
  sdk/python/tests/compiler/testdata/sidecar.yaml
  sdk/python/tests/compiler/testdata/timeout.yaml
  sdk/python/tests/compiler/testdata/tolerations.yaml
  sdk/python/tests/compiler/testdata/volume.yaml
  sdk/python/tests/compiler/testdata/volume_snapshotop_rokurl.yaml
  sdk/python/tests/compiler/testdata/volume_snapshotop_sequential.yaml
  sdk/python/tests/compiler/testdata/volumeop_basic.yaml
  sdk/python/tests/compiler/testdata/volumeop_dag.yaml
  sdk/python/tests/compiler/testdata/volumeop_parallel.yaml
  sdk/python/tests/compiler/testdata/volumeop_sequential.yaml
  sdk/python/tests/compiler/testdata/withitem_basic.yaml
  sdk/python/tests/compiler/testdata/withitem_nested.yaml
Labels: approved, area/sdk/dsl/compiler, lgtm, size/XL

#2045 SDK - Components - Hiding signature attribute from CloudPickle
  sdk/python/kfp/components/_python_op.py
Labels: approved, area/sdk/components, lgtm, size/XS

#2030 add more core samples in the sample test
  samples/core/pipeline_transformers/pipeline_transformers.py
  samples/core/resource_ops/resource_ops.py
  samples/core/sidecar/sidecar.py
  samples/core/volume_snapshot_ops/volume_snapshot_ops.py
  test/sample_test.yaml
Labels: approved, lgtm, size/S

#2057 Adds Metadata Artifacts to UI
  envoy-entrypoint.sh
  envoy.Dockerfile
  envoy.yaml
  frontend/package-lock.json
  frontend/package.json
  frontend/server/server.ts
  frontend/src/Css.tsx
  frontend/src/apis/metadata/metadata_store.proto
  frontend/src/apis/metadata/metadata_store_service.proto
  frontend/src/components/CustomTable.test.tsx
  frontend/src/components/CustomTable.tsx
  frontend/src/components/CustomTableRow.test.tsx
  frontend/src/components/CustomTableRow.tsx
  frontend/src/components/ResourceInfo.tsx
  frontend/src/components/Router.tsx
  frontend/src/components/SideNav.tsx
  frontend/src/components/__snapshots__/CustomTable.test.tsx.snap
  frontend/src/components/__snapshots__/CustomTableRow.test.tsx.snap
  frontend/src/components/__snapshots__/Router.test.tsx.snap
  frontend/src/components/__snapshots__/SideNav.test.tsx.snap
  frontend/src/generated/src/apis/metadata/metadata_store_pb.d.ts
  frontend/src/generated/src/apis/metadata/metadata_store_pb.js
  frontend/src/generated/src/apis/metadata/metadata_store_pb_service.d.ts
  frontend/src/generated/src/apis/metadata/metadata_store_pb_service.js
  frontend/src/generated/src/apis/metadata/metadata_store_service_pb.d.ts
  frontend/src/generated/src/apis/metadata/metadata_store_service_pb.js
  frontend/src/generated/src/apis/metadata/metadata_store_service_pb_service.d.ts
  frontend/src/generated/src/apis/metadata/metadata_store_service_pb_service.js
  frontend/src/generated/src/apis/metadata/package-lock.json
  frontend/src/generated/src/apis/metadata/package.json
  frontend/src/lib/Apis.ts
  frontend/src/lib/Buttons.ts
  frontend/src/lib/CompareUtils.ts
  frontend/src/lib/Utils.ts
  frontend/src/lib/Utils.tsx
  frontend/src/pages/ArtifactDetails.tsx
  frontend/src/pages/ArtifactList.tsx
  frontend/src/pages/ExperimentDetails.tsx
  frontend/tsconfig.json
  manifests/kustomize/base/metadata/kustomization.yaml
  manifests/kustomize/base/metadata/metadata-envoy-deployment.yaml
  manifests/kustomize/base/metadata/metadata-envoy-service.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-scheduledworkflow-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-ui-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-viewer-crd-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-visualization-deployment.yaml
Labels: approved, area/front-end, lgtm, size/XXL

#2052 Refactor kfp.compiler for better modularity
  sdk/python/kfp/compiler/compiler.py
Labels: approved, lgtm, size/M

#2058 update sample readme for the new structure
  samples/README.md
  test/sample_test.yaml
Labels: approved, lgtm, size/L

#2055 SDK - Compiler - Failing when PipelineParam is unresolved
  sdk/python/kfp/compiler/compiler.py
Labels: approved, area/sdk/dsl/compiler, lgtm, size/XS

#2031 move old gcp components to deprecated folder
  .cloudbuild.yaml
  components/README.md
  components/deprecated/dataflow/base/Dockerfile
  components/deprecated/dataflow/base/build_image.sh
  components/deprecated/dataflow/predict/Dockerfile
  components/deprecated/dataflow/predict/build_image.sh
  components/deprecated/dataflow/predict/component.yaml
  components/deprecated/dataflow/predict/src/predict.py
  components/deprecated/dataflow/predict/src/setup.py
  components/deprecated/dataflow/tfdv/Dockerfile
  components/deprecated/dataflow/tfdv/build_image.sh
  components/deprecated/dataflow/tfdv/component.yaml
  components/deprecated/dataflow/tfdv/src/validate.py
  components/deprecated/dataflow/tfdv/src/validation/setup.py
  components/deprecated/dataflow/tfma/Dockerfile
  components/deprecated/dataflow/tfma/build_image.sh
  components/deprecated/dataflow/tfma/component.yaml
  components/deprecated/dataflow/tfma/src/analysis/setup.py
  components/deprecated/dataflow/tfma/src/model_analysis.py
  components/deprecated/dataflow/tft/Dockerfile
  components/deprecated/dataflow/tft/build_image.sh
  components/deprecated/dataflow/tft/component.yaml
  components/deprecated/dataflow/tft/src/transform.py
  components/deprecated/dataproc/analyze/Dockerfile
  components/deprecated/dataproc/analyze/build_image.sh
  components/deprecated/dataproc/analyze/src/analyze.py
  components/deprecated/dataproc/analyze/src/analyze_run.py
  components/deprecated/dataproc/base/Dockerfile
  components/deprecated/dataproc/base/build_image.sh
  components/deprecated/dataproc/common/__init__.py
  components/deprecated/dataproc/common/_utils.py
  components/deprecated/dataproc/create_cluster/Dockerfile
  components/deprecated/dataproc/create_cluster/build_image.sh
  components/deprecated/dataproc/create_cluster/src/create_cluster.py
  components/deprecated/dataproc/create_cluster/src/initialization_actions.sh
  components/deprecated/dataproc/delete_cluster/Dockerfile
  components/deprecated/dataproc/delete_cluster/build_image.sh
  components/deprecated/dataproc/delete_cluster/src/delete_cluster.py
  components/deprecated/dataproc/predict/Dockerfile
  components/deprecated/dataproc/predict/build_image.sh
  components/deprecated/dataproc/predict/src/predict.py
  components/deprecated/dataproc/train/Dockerfile
  components/deprecated/dataproc/train/build_image.sh
  components/deprecated/dataproc/train/src/README.md
  components/deprecated/dataproc/train/src/XGBoostPredictor.scala
  components/deprecated/dataproc/train/src/XGBoostTrainer.scala
  components/deprecated/dataproc/train/src/train.py
  components/deprecated/dataproc/train/src/xgb4j_build.sh
  components/deprecated/dataproc/transform/Dockerfile
  components/deprecated/dataproc/transform/build_image.sh
  components/deprecated/dataproc/transform/src/transform.py
  components/deprecated/dataproc/transform/src/transform_run.py
  samples/core/tfx_cab_classification/README.md
  samples/core/xgboost_training_cm/README.md
Labels: approved, lgtm, size/M

#2043 SDK - Compiler - Fixed dsl.Condition when parameter resolves to string with spaces
  sdk/python/kfp/compiler/compiler.py
  sdk/python/tests/compiler/testdata/coin.yaml
  sdk/python/tests/compiler/testdata/recursive_do_while.yaml
  sdk/python/tests/compiler/testdata/recursive_while.yaml
Labels: approved, area/sdk/dsl/compiler, lgtm, size/S

#2062 Release - Creating the release branch from the specified commit
  components/release.sh
Labels: approved, area/release, lgtm, size/XS

#2039 Add parameter for service account credential
  manifests/gcp_marketplace/README.md
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/gcp_secret.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/metadata.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/minio.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/mysql.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/values.yaml
  manifests/gcp_marketplace/schema.yaml
Labels: approved, lgtm, size/M

#2065 fixes name inconsistency for marketplace manifest and bump kfp version
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml
  manifests/gcp_marketplace/schema.yaml
Labels: approved, lgtm, size/M

#2066 Chang object store naming for marketplace deployment
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml
Labels: approved, lgtm, size/XS

#2069 Make wget quieter
  .travis.yml
  backend/api/build_kfp_server_api_python_package.sh
  components/arena/docker/Dockerfile
  components/deprecated/dataproc/train/src/xgb4j_build.sh
  components/kubeflow/deployer/Dockerfile
  contrib/components/openvino/ovms-deployer/containers/Dockerfile
  frontend/Dockerfile
  samples/contrib/aws-samples/ground_truth_pipeline_demo/README.md
  samples/contrib/nvidia-resnet/install_kubeflow_and_dependencies.sh
  samples/contrib/nvidia-resnet/prepare_test_inference_data.sh
  test/deploy-pipeline-lite.sh
Labels: approved, area/release, lgtm, size/M

#2063 Release - Fixed the deprecated component image build
  components/deprecated/dataflow/base/build_image.sh
  components/deprecated/dataflow/predict/build_image.sh
  components/deprecated/dataflow/tfdv/build_image.sh
  components/deprecated/dataflow/tfma/build_image.sh
  components/deprecated/dataflow/tft/build_image.sh
  components/deprecated/dataproc/analyze/build_image.sh
  components/deprecated/dataproc/base/build_image.sh
  components/deprecated/dataproc/create_cluster/build_image.sh
  components/deprecated/dataproc/delete_cluster/build_image.sh
  components/deprecated/dataproc/predict/build_image.sh
  components/deprecated/dataproc/train/build_image.sh
  components/deprecated/dataproc/transform/build_image.sh
Labels: approved, area/release, lgtm, size/S

#2067 Store DB password as K8s secret for marketplace deployment
  manifests/gcp_marketplace/chart/kubeflow-pipelines/Chart.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/mysql.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/values.yaml
Labels: approved, lgtm, size/M

#2074 Add cmle tpu sample link
  samples/core/ai-platform/README.md
Labels: approved, lgtm, size/XS

#2077 Fix sample test result upload failure.
  test/sample-test/sample_test_launcher.py
  test/sample-test/utils.py
Labels: approved, lgtm, size/S

#2079 Expose DB username to marketplace schema.yaml
  manifests/gcp_marketplace/schema.yaml
Labels: approved, lgtm, size/XS

#2012 Fix bug where source and variables are not accessible to visualization
  backend/src/apiserver/visualization/exporter.py
  backend/src/apiserver/visualization/snapshots/snap_test_exporter.py
  backend/src/apiserver/visualization/test_exporter.py
  backend/src/apiserver/visualization/types/test.py
Labels: approved, lgtm, size/M

#2036 SDK - Testing - Run some unit-tests in a more correct way
  sdk/python/tests/components/test_components.py
  sdk/python/tests/components/test_graph_components.py
  sdk/python/tests/components/test_python_op.py
Labels: approved, area/sdk, lgtm, size/M

#2078 Use GCSHelper to upload test result
  test/sample-test/sample_test_launcher.py
  test/sample-test/utils.py
Labels: approved, lgtm, size/S

#2082 Expose an API for appending params/names/descriptions in a programmable way.
  sdk/python/kfp/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/basic_no_decorator.py
  sdk/python/tests/compiler/testdata/basic_no_decorator.yaml
Labels: approved, lgtm, size/L

#2041 manifests/metadata: Metadata server invocation change
  manifests/kustomize/base/metadata/kustomization.yaml
  manifests/kustomize/base/metadata/metadata-deployment.yaml
  manifests/kustomize/base/metadata/mlmd-server-configmap.yaml
Labels: approved, lgtm, size/M

#1969 SDK - Stop adding empty descriptions and inputs
  sdk/python/kfp/dsl/_metadata.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/dsl/component_tests.py
  sdk/python/tests/dsl/pipeline_tests.py
Labels: approved, area/sdk, lgtm, size/S

#2016 Add warning message when there are empty parameters in NewRun.tsx
  frontend/src/pages/NewRun.test.tsx
  frontend/src/pages/NewRun.tsx
  frontend/src/pages/__snapshots__/NewRun.test.tsx.snap
Labels: approved, lgtm, size/M

#2087 Remove broken environment variables in namespace install
  manifests/kustomize/namespaced-install.yaml
Labels: approved, lgtm, size/XS

#2100 update sdk versions
  components/gcp/container/component_sdk/python/setup.py
  sdk/python/setup.py
Labels: approved, lgtm, size/XS

#2099 Release 1449d08aeeeb47731d019ea046d90904d9c77953
  components/deprecated/dataflow/predict/component.yaml
  components/deprecated/dataflow/tfdv/component.yaml
  components/deprecated/dataflow/tfma/component.yaml
  components/deprecated/dataflow/tft/component.yaml
  components/gcp/bigquery/query/README.md
  components/gcp/bigquery/query/component.yaml
  components/gcp/bigquery/query/sample.ipynb
  components/gcp/dataflow/launch_python/README.md
  components/gcp/dataflow/launch_python/component.yaml
  components/gcp/dataflow/launch_python/sample.ipynb
  components/gcp/dataflow/launch_template/README.md
  components/gcp/dataflow/launch_template/component.yaml
  components/gcp/dataflow/launch_template/sample.ipynb
  components/gcp/dataproc/create_cluster/README.md
  components/gcp/dataproc/create_cluster/component.yaml
  components/gcp/dataproc/create_cluster/sample.ipynb
  components/gcp/dataproc/delete_cluster/README.md
  components/gcp/dataproc/delete_cluster/component.yaml
  components/gcp/dataproc/delete_cluster/sample.ipynb
  components/gcp/dataproc/submit_hadoop_job/README.md
  components/gcp/dataproc/submit_hadoop_job/component.yaml
  components/gcp/dataproc/submit_hadoop_job/sample.ipynb
  components/gcp/dataproc/submit_hive_job/README.md
  components/gcp/dataproc/submit_hive_job/component.yaml
  components/gcp/dataproc/submit_hive_job/sample.ipynb
  components/gcp/dataproc/submit_pig_job/README.md
  components/gcp/dataproc/submit_pig_job/component.yaml
  components/gcp/dataproc/submit_pig_job/sample.ipynb
  components/gcp/dataproc/submit_pyspark_job/README.md
  components/gcp/dataproc/submit_pyspark_job/component.yaml
  components/gcp/dataproc/submit_pyspark_job/sample.ipynb
  components/gcp/dataproc/submit_spark_job/README.md
  components/gcp/dataproc/submit_spark_job/component.yaml
  components/gcp/dataproc/submit_spark_job/sample.ipynb
  components/gcp/dataproc/submit_sparksql_job/README.md
  components/gcp/dataproc/submit_sparksql_job/component.yaml
  components/gcp/dataproc/submit_sparksql_job/sample.ipynb
  components/gcp/ml_engine/batch_predict/README.md
  components/gcp/ml_engine/batch_predict/component.yaml
  components/gcp/ml_engine/batch_predict/sample.ipynb
  components/gcp/ml_engine/deploy/README.md
  components/gcp/ml_engine/deploy/component.yaml
  components/gcp/ml_engine/deploy/sample.ipynb
  components/gcp/ml_engine/train/README.md
  components/gcp/ml_engine/train/component.yaml
  components/gcp/ml_engine/train/sample.ipynb
  components/kubeflow/deployer/component.yaml
  components/kubeflow/dnntrainer/component.yaml
  components/kubeflow/launcher/kubeflow_tfjob_launcher_op.py
  components/kubeflow/launcher/src/train.template.yaml
  components/local/confusion_matrix/component.yaml
  components/local/roc/component.yaml
  samples/core/ai-platform/Chicago Crime Pipeline.ipynb
  samples/core/kubeflow_tf_serving/kubeflow_tf_serving.ipynb
  samples/core/tfx_cab_classification/tfx_cab_classification.py
  samples/core/xgboost_training_cm/xgboost_training_cm.py
Labels: approved, lgtm, size/L

#2107 fix bug: list.pop() is not expecting keyword arg
  sdk/python/kfp/compiler/_component_builder.py
Labels: approved, lgtm, size/XS

#2111 update kustomize(for 0.1.30 release)
  manifests/kustomize/namespaced-install.yaml
Labels: approved, lgtm, size/L

#2035 SDK - Lightweigh - Made wrapper code compatible with python2
  sdk/python/kfp/components/_python_op.py
Labels: approved, area/sdk/components, lgtm, size/S

#2113 Add imagepullsecrets sample into sample test
  test/sample-test/configs/imagepullsecrets.config.yaml
  test/sample_test.yaml
Labels: approved, lgtm, size/S

#2117 SDK - Started to explicitly import submodules into kfp namespace
  sdk/python/kfp/__init__.py
Labels: approved, area/sdk, lgtm, size/XS

#2122 A few fixes for Marketplace manifests
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/argo.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/metadata.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/proxy.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/values.yaml
  manifests/gcp_marketplace/schema.yaml
Labels: approved, lgtm, size/XL

#2084 Close the streams after getting gcloud auth token
  sdk/python/kfp/_auth.py
Labels: approved, lgtm, size/XS

#2104 Add script that automatically proxies backend servers for frontend dev server
  frontend/README.md
  frontend/package.json
  frontend/start-proxies.sh
Labels: approved, lgtm, size/M

#2126 Workaround error thrown from metadata server when there is no record
  frontend/src/pages/ArtifactList.tsx
  frontend/src/pages/ExecutionList.tsx
Labels: approved, area/front-end, kind/bug, lgtm, size/S

#2127 Fix execution detail page fetch params.
  frontend/src/pages/ExecutionDetails.tsx
Labels: approved, area/front-end, kind/bug, lgtm, size/XS

#2114 Add execution order sample test
  test/sample_test.yaml
Labels: approved, lgtm, size/XS

#2132 Fix the test name of image pull secrets sample test.
  test/sample-test/configs/imagepullsecrets.config.yaml
Labels: approved, lgtm, size/XS

#2119 SDK - Python components - Fixed the base_image default value
  sdk/python/kfp/components/_python_op.py
Labels: approved, area/sdk/components, lgtm, size/S

#2123 Update gitignore to ignore all .iml files
  .gitignore
Labels: approved, lgtm, size/XS

#2096 add dataflow sample with the new GCP component
  samples/core/dataflow/dataflow.ipynb
  test/sample-test/configs/dataflow.config.yaml
  test/sample_test.yaml
Labels: approved, lgtm, size/L

#2116 SDK - Containers - Fixed kfp.containers.get_default_image_builder
  sdk/python/kfp/containers/_build_image_api.py
Labels: approved, kind/bug, lgtm, sdk/containers, size/XS

#2118 SDK - Components - Fixed kfp.components.set_default_base_image
  sdk/python/kfp/components/_python_op.py
Labels: approved, area/sdk/components, lgtm, size/XS

#1944 SDK - Refactoring - Replaced the *Meta classes with the *Spec classes
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/components/_dsl_bridge.py
  sdk/python/kfp/dsl/_component.py
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/kfp/dsl/_metadata.py
  sdk/python/kfp/dsl/_pipeline.py
  sdk/python/tests/dsl/component_tests.py
  sdk/python/tests/dsl/metadata_tests.py
  sdk/python/tests/dsl/pipeline_tests.py
Labels: approved, area/sdk/components, lgtm, size/L

#2134 SDK - Persisting all output values
  sdk/python/kfp/compiler/_op_to_template.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/basic.yaml
  sdk/python/tests/compiler/testdata/basic_no_decorator.yaml
  sdk/python/tests/compiler/testdata/coin.yaml
  sdk/python/tests/compiler/testdata/compose.yaml
  sdk/python/tests/compiler/testdata/default_value.yaml
  sdk/python/tests/compiler/testdata/imagepullsecrets.yaml
  sdk/python/tests/compiler/testdata/pipelineparams.yaml
  sdk/python/tests/compiler/testdata/preemptible_tpu_gpu.yaml
  sdk/python/tests/compiler/testdata/recursive_do_while.yaml
  sdk/python/tests/compiler/testdata/recursive_while.yaml
  sdk/python/tests/compiler/testdata/sidecar.yaml
  sdk/python/tests/compiler/testdata/tolerations.yaml
  sdk/python/tests/compiler/testdata/volume.yaml
  sdk/python/tests/compiler/testdata/withparam_global.yaml
  sdk/python/tests/compiler/testdata/withparam_global_dict.yaml
  sdk/python/tests/compiler/testdata/withparam_output.yaml
  sdk/python/tests/compiler/testdata/withparam_output_dict.yaml
Labels: approved, area/sdk/dsl/compiler, lgtm, size/M

#2128 Add documentation for Marketplace CLI deployment
  manifests/gcp_marketplace/README.md
Labels: approved, lgtm, size/L

#2105 Artifact list column creation time
  frontend/src/lib/MetadataUtils.ts
  frontend/src/pages/ArtifactList.tsx
Labels: approved, area/front-end, lgtm, size/M

#2129 Fix permission issue running GCP pipelines
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/gcp_secret.yaml
Labels: approved, lgtm, size/XS

#2138 Small fixes to the kfp marketplace
  manifests/gcp_marketplace/README.md
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml
  manifests/gcp_marketplace/schema.yaml
Labels: approved, lgtm, size/XS

#2106 Add sidecar sample test
  test/sample-test/configs/sidecar.config.yaml
  test/sample_test.yaml
Labels: approved, lgtm, size/S

#2137 SDK - Fix pipeline metadata serialization
  sdk/python/kfp/dsl/_metadata.py
  sdk/python/tests/compiler/testdata/pipelineparams.yaml
  sdk/python/tests/compiler/testdata/recursive_while.yaml
  sdk/python/tests/compiler/testdata/withitem_basic.yaml
  sdk/python/tests/compiler/testdata/withitem_nested.yaml
  sdk/python/tests/compiler/testdata/withparam_global.yaml
  sdk/python/tests/compiler/testdata/withparam_global_dict.yaml
  sdk/python/tests/dsl/component_tests.py
  sdk/python/tests/dsl/pipeline_tests.py
Labels: approved, area/sdk, kind/bug, lgtm, priority/p0, size/S

#2142 add artifact location tests
  samples/core/artifact_location/artifact_location.py
  test/sample_test.yaml
Labels: approved, lgtm, size/S

#2143 SDK - Components - Fixed build_python_component
  sdk/python/kfp/compiler/_component_builder.py
Labels: approved, area/sdk/components/python_container_op, lgtm, size/XS

#2112 Add a convention to make sure experiment_name is parameterized in notebook sample.
  samples/README.md
  samples/core/lightweight_component/lightweight_component.ipynb
  test/sample-test/configs/lightweight_component.config.yaml
  test/sample-test/sample_test_launcher.py
Labels: approved, lgtm, size/M

#2145 SDK - Testing - Fix metadata comparison instability
  sdk/python/tests/compiler/compiler_tests.py
Labels: approved, area/sdk, area/testing, lgtm, size/S

#2136 Remove envoy related from root directory
  envoy.Dockerfile
  envoy.yaml
Labels: approved, lgtm, size/M

#2144 SDK - Containers - Raise exception on job failure
  sdk/python/kfp/compiler/_k8s_helper.py
Labels: approved, lgtm, sdk/containers, size/XS

#2135 Fix missing execution name in execution list/detail page.
  frontend/src/lib/Apis.ts
  frontend/src/pages/ExecutionDetails.tsx
  frontend/src/pages/ExecutionList.tsx
Labels: approved, area/front-end, kind/bug, lgtm, size/S

#2141 add retry tests
  test/sample-test/configs/retry.config.yaml
  test/sample-test/run_sample_test.py
  test/sample_test.yaml
Labels: approved, lgtm, size/S

#2152 Fix presubmit test failure -- build job in QUEUED state
  test/check-build-image-status.sh
Labels: approved, lgtm, size/XS

#2153 Utils to convert metadata api from callback paradigm to promise paradigm
  frontend/src/lib/Apis.ts
  frontend/src/lib/MetadataUtils.ts
  frontend/src/pages/ExecutionDetails.tsx
Labels: approved, area/front-end, lgtm, size/L

#1940 configure db host and port from from config file
  backend/src/apiserver/client_manager.go
Labels: approved, lgtm, ok-to-test, size/S

#2151 Removing the unnecessary trunk when generating the DB name
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/metadata.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/values.yaml
  manifests/gcp_marketplace/schema.yaml
Labels: approved, lgtm, size/S

#2163 add kubeflow serving sample test
  samples/core/kubeflow_tf_serving/kubeflow_tf_serving.ipynb
  test/sample-test/configs/kubeflow_tf_serving.config.yaml
  test/sample_test.yaml
Labels: approved, lgtm, size/L

#2162 SDK - Components - Fixed the output types for outputs with converted names
  sdk/python/kfp/components/_dsl_bridge.py
Labels: approved, area/sdk/components, kind/bug, lgtm, size/XS

#2164 Update backend owner file
  backend/OWNERS
Labels: approved, lgtm, size/XS

#2157 Add URI to artifact details page
  frontend/src/components/ResourceInfo.tsx
  frontend/src/pages/ArtifactDetails.tsx
  frontend/src/pages/ExecutionDetails.tsx
Labels: approved, area/front-end, kind/feature, lgtm, size/M

#2160 remove tfx-taxi sample in favor of the tfx oss sample
  backend/src/apiserver/config/sample_config.json
  samples/README.md
  samples/core/tfx_cab_classification/README.md
  samples/core/tfx_cab_classification/taxi-cab-classification/column-names.json
  samples/core/tfx_cab_classification/taxi-cab-classification/eval.csv
  samples/core/tfx_cab_classification/taxi-cab-classification/preprocessing.py
  samples/core/tfx_cab_classification/taxi-cab-classification/schema.json
  samples/core/tfx_cab_classification/taxi-cab-classification/train.csv
  samples/core/tfx_cab_classification/tfx_cab_classification.py
  test/component_test.yaml
  test/sample-test/configs/tfx_cab_classification.config.yaml
  test/sample-test/sample_test_launcher.py
  test/sample_test.yaml
Labels: approved, lgtm, size/XXL

#2165 Pretty print json value in execution/artifact detail page
  frontend/src/components/ResourceInfo.tsx
Labels: approved, area/front-end, kind/feature, lgtm, size/S

#2166 Add Bobgy to test infra owner
  test/OWNERS
Labels: approved, lgtm, size/XS

#2158 Fix more typos in KFP marketplace application
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml
  manifests/gcp_marketplace/schema.yaml
Labels: approved, lgtm, size/XS

#2170 [Test/sample] Fix the model version in kubeflow_tf_serving sample to avoid potential conflict.
  samples/core/kubeflow_tf_serving/kubeflow_tf_serving.ipynb
Labels: approved, lgtm, size/XS

#2047 add us to OWNERS for SHA
  frontend/OWNERS
Labels: approved, lgtm, size/XS

#2102 kfserving pipeline update
  components/kubeflow/kfserving/component.yaml
  components/kubeflow/kfserving/src/kfservingdeployer.py
Labels: approved, lgtm, size/M

#2167 Make gs:// links in metadata UI point to GCS console page
  frontend/src/components/GcsLink.tsx
  frontend/src/components/ResourceInfo.tsx
  frontend/src/lib/Utils.tsx
  frontend/src/pages/ArtifactList.tsx
  frontend/tslint.json
Labels: approved, area/front-end, kind/feature, lgtm, size/M

#2155 Execution detail page shows inputs and outputs
  frontend/src/components/Router.tsx
  frontend/src/lib/Apis.ts
  frontend/src/lib/MetadataUtils.ts
  frontend/src/pages/ArtifactList.tsx
  frontend/src/pages/ExecutionDetails.tsx
  frontend/tsconfig.json
Labels: approved, area/front-end, kind/feature, lgtm, size/L

#2147 Tests - Samples - Added the component_build sample test
  samples/core/component_build/component_build.ipynb
  test/sample-test/configs/component_build.config.yaml
  test/sample_test.yaml
Labels: approved, area/testing, lgtm, size/M

#2173 SDK - Compiler - Fix large data passing
  sdk/python/kfp/compiler/_data_passing_rewriter.py
  sdk/python/kfp/compiler/compiler.py
  sdk/python/tests/compiler/testdata/coin.yaml
  sdk/python/tests/compiler/testdata/imagepullsecrets.yaml
  sdk/python/tests/compiler/testdata/preemptible_tpu_gpu.yaml
  sdk/python/tests/compiler/testdata/recursive_do_while.yaml
  sdk/python/tests/compiler/testdata/recursive_while.yaml
Labels: approved, area/sdk/dsl/compiler, lgtm, size/L

#2179 [MKP/misc] Update help info for service account.
  manifests/gcp_marketplace/schema.yaml
Labels: approved, lgtm, size/XS

#2180 metadata: Deployment scripts update
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/metadata.yaml
  manifests/kustomize/base/metadata/kustomization.yaml
  manifests/kustomize/base/metadata/metadata-configmap.yaml
  manifests/kustomize/base/metadata/metadata-deployment.yaml
Labels: approved, lgtm, size/M

#2168 Update owner for thirdparty
  third_party/OWNERS
Labels: lgtm, size/XS

#2093 pipeline-lite/metadata: Update readme
  manifests/kustomize/base/metadata/kustomization.yaml
  manifests/kustomize/base/metadata/metadata-mysql-secret.yaml
Labels: approved, lgtm, size/XS

#2140 Use latest Tensorflow image for Tensorboard.
  backend/src/crd/controller/viewer/reconciler/reconciler.go
  backend/src/crd/controller/viewer/reconciler/reconciler_test.go
Labels: approved, lgtm, size/XS

#2178 metadata-envoy: Build script for metadata-envoy docker image
  .cloudbuild.yaml
  .release.cloudbuild.yaml
  third_party/metadata_envoy/Dockerfile
  third_party/metadata_envoy/README.md
  third_party/metadata_envoy/dependencies.json
  third_party/metadata_envoy/dependency_helper.py
  third_party/metadata_envoy/envoy.yaml
Labels: approved, lgtm, size/L

#2187 Build inverse proxy image as part of the presubmit test
  test/build-images.sh
  test/cloudbuild/batch_build.yaml
  test/deploy-pipeline-lite.sh
Labels: approved, lgtm, size/XS

#2184 Release 57d9f7f1cfd458e945d297957621716062d89a49
  components/deprecated/dataflow/predict/component.yaml
  components/deprecated/dataflow/tfdv/component.yaml
  components/deprecated/dataflow/tfma/component.yaml
  components/deprecated/dataflow/tft/component.yaml
  components/gcp/bigquery/query/README.md
  components/gcp/bigquery/query/component.yaml
  components/gcp/bigquery/query/sample.ipynb
  components/gcp/container/component_sdk/python/setup.py
  components/gcp/dataflow/launch_python/README.md
  components/gcp/dataflow/launch_python/component.yaml
  components/gcp/dataflow/launch_python/sample.ipynb
  components/gcp/dataflow/launch_template/README.md
  components/gcp/dataflow/launch_template/component.yaml
  components/gcp/dataflow/launch_template/sample.ipynb
  components/gcp/dataproc/create_cluster/README.md
  components/gcp/dataproc/create_cluster/component.yaml
  components/gcp/dataproc/create_cluster/sample.ipynb
  components/gcp/dataproc/delete_cluster/README.md
  components/gcp/dataproc/delete_cluster/component.yaml
  components/gcp/dataproc/delete_cluster/sample.ipynb
  components/gcp/dataproc/submit_hadoop_job/README.md
  components/gcp/dataproc/submit_hadoop_job/component.yaml
  components/gcp/dataproc/submit_hadoop_job/sample.ipynb
  components/gcp/dataproc/submit_hive_job/README.md
  components/gcp/dataproc/submit_hive_job/component.yaml
  components/gcp/dataproc/submit_hive_job/sample.ipynb
  components/gcp/dataproc/submit_pig_job/README.md
  components/gcp/dataproc/submit_pig_job/component.yaml
  components/gcp/dataproc/submit_pig_job/sample.ipynb
  components/gcp/dataproc/submit_pyspark_job/README.md
  components/gcp/dataproc/submit_pyspark_job/component.yaml
  components/gcp/dataproc/submit_pyspark_job/sample.ipynb
  components/gcp/dataproc/submit_spark_job/README.md
  components/gcp/dataproc/submit_spark_job/component.yaml
  components/gcp/dataproc/submit_spark_job/sample.ipynb
  components/gcp/dataproc/submit_sparksql_job/README.md
  components/gcp/dataproc/submit_sparksql_job/component.yaml
  components/gcp/dataproc/submit_sparksql_job/sample.ipynb
  components/gcp/ml_engine/batch_predict/README.md
  components/gcp/ml_engine/batch_predict/component.yaml
  components/gcp/ml_engine/batch_predict/sample.ipynb
  components/gcp/ml_engine/deploy/README.md
  components/gcp/ml_engine/deploy/component.yaml
  components/gcp/ml_engine/deploy/sample.ipynb
  components/gcp/ml_engine/train/README.md
  components/gcp/ml_engine/train/component.yaml
  components/gcp/ml_engine/train/sample.ipynb
  components/kubeflow/deployer/component.yaml
  components/kubeflow/dnntrainer/component.yaml
  components/kubeflow/launcher/kubeflow_tfjob_launcher_op.py
  components/kubeflow/launcher/src/train.template.yaml
  components/local/confusion_matrix/component.yaml
  components/local/roc/component.yaml
  samples/core/ai-platform/Chicago Crime Pipeline.ipynb
  samples/core/dataflow/dataflow.ipynb
  samples/core/kubeflow_tf_serving/kubeflow_tf_serving.ipynb
  samples/core/xgboost_training_cm/xgboost_training_cm.py
  sdk/python/setup.py
Labels: approved, lgtm, size/L

#2189 Update pipeline-lite to v0.1.31
  manifests/kustomize/base/kustomization.yaml
Labels: approved, lgtm, size/S

#2186 push pipeline-lite YAML as part of release CB
  .release.cloudbuild.yaml
Labels: approved, lgtm, size/S

#2181 Added generated Python SDK documentation to .gitignore
  .gitignore
Labels: approved, lgtm, size/XS

#2197 update dockerfile for envoy
  third_party/metadata_envoy/Dockerfile
Labels: approved, lgtm, size/XS

#2200 fix envoy dockerfile
  third_party/metadata_envoy/Dockerfile
Labels: approved, lgtm, size/XS

#2161 Remove dataflow components
  .cloudbuild.yaml
  components/deprecated/dataflow/base/Dockerfile
  components/deprecated/dataflow/base/build_image.sh
  components/deprecated/dataflow/predict/Dockerfile
  components/deprecated/dataflow/predict/build_image.sh
  components/deprecated/dataflow/predict/src/predict.py
  components/deprecated/dataflow/predict/src/setup.py
  components/deprecated/dataflow/tfdv/Dockerfile
  components/deprecated/dataflow/tfdv/build_image.sh
  components/deprecated/dataflow/tfdv/src/validate.py
  components/deprecated/dataflow/tfdv/src/validation/setup.py
  components/deprecated/dataflow/tfma/Dockerfile
  components/deprecated/dataflow/tfma/build_image.sh
  components/deprecated/dataflow/tfma/src/analysis/setup.py
  components/deprecated/dataflow/tfma/src/model_analysis.py
  components/deprecated/dataflow/tft/Dockerfile
  components/deprecated/dataflow/tft/build_image.sh
  components/deprecated/dataflow/tft/src/transform.py
  components/release.sh
  test/component_test.yaml
  test/sample-test/sample_test_launcher.py
Labels: approved, lgtm, size/XXL

#2194 SDK - Removed some dead code
  sdk/python/kfp/components/_python_op.py
Labels: approved, area/sdk/components, lgtm, size/XS

#2198 SDK - Python components - Properly serializing outputs
  sdk/python/kfp/components/_python_op.py
  sdk/python/tests/components/test_python_op.py
Labels: approved, area/sdk/components, lgtm, size/M

#2204 fix release CB and update readme
  .release.cloudbuild.yaml
  manifests/kustomize/README.md
Labels: approved, lgtm, size/XS

#2193 SDK - Components - Simplified arg-parsing code using argparse.SUPPRESS
  sdk/python/kfp/components/_python_op.py
Labels: approved, area/sdk, area/sdk/components, lgtm, size/XS

#2205 add support for hard and soft constraint in the preemptible nodepools
  sdk/python/kfp/gcp.py
  sdk/python/tests/compiler/testdata/preemptible_tpu_gpu.yaml
Labels: approved, lgtm, size/M

#2176 Testing - Output Argo workflow information when the workflow times out
  test/check-argo-status.sh
Labels: approved, area/testing, lgtm, size/M

#2207 SDK - Lightweight - Added support for file inputs
  sdk/python/kfp/components/_python_op.py
  sdk/python/tests/components/test_python_op.py
Labels: approved, area/sdk/components, lgtm, size/L

#2217 Fix pipeline lite README
  manifests/kustomize/README.md
Labels: approved, lgtm, size/XS

#2182 Docs - Added kfp.containers module
  docs/source/kfp.containers.rst
  docs/source/kfp.rst
  sdk/python/kfp/containers/_build_image_api.py
Labels: approved, area/docs, lgtm, size/S

#2218 Add samples for loops
  samples/core/loop_output/loop_output.py
  samples/core/loop_parameter/loop_parameter.py
  samples/core/loop_static/loop_static.py
  test/sample_test.yaml
Labels: approved, lgtm, size/L

#2213 [Component] Fix the image version specification in create cluster component.
  components/gcp/container/component_sdk/python/kfp_component/google/dataproc/_create_cluster.py
  components/gcp/container/component_sdk/python/tests/google/dataproc/test__create_cluster.py
Labels: approved, lgtm, size/S

#2221 SDK - Lightweight - Added support for file outputs
  sdk/python/kfp/components/_python_op.py
  sdk/python/tests/components/test_python_op.py
Labels: approved, area/sdk/components, lgtm, size/L

#2214 fix release cloud build YAML to generate pipeline-lite YAML
  .release.cloudbuild.yaml
Labels: approved, lgtm, size/XS

#2212 SDK - Components - Fixed serialization of lists and dicts containing `PipelineParam` items
  sdk/python/kfp/components/_data_passing.py
  sdk/python/kfp/dsl/_pipeline_param.py
  sdk/python/tests/components/test_python_op.py
Labels: approved, area/sdk/components, lgtm, size/S

#1938 SDK - Containers - Do not create GCS bucket unless building the image
  sdk/python/kfp/compiler/_container_builder.py
Labels: approved, lgtm, sdk/containers, size/L

#2231 Fix publishing deploy YAML in .release.cloudbuild.yaml
  .release.cloudbuild.yaml
Labels: approved, lgtm, size/XS

#2228 Updated README Swagger CodeGen version
  frontend/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#2232 Update changelog for release 0.1.31. (And also for 0.1.30 and 0.1.29, whose are not added before)
  CHANGELOG.md
Labels: approved, lgtm, size/L

#2174 Components - Added AutoML Tables components and tests
  components/gcp/automl/create_dataset_for_tables/component.py
  components/gcp/automl/create_dataset_for_tables/component.yaml
  components/gcp/automl/create_model_for_tables/component.py
  components/gcp/automl/create_model_for_tables/component.yaml
  components/gcp/automl/import_data_from_bigquery/component.py
  components/gcp/automl/import_data_from_bigquery/component.yaml
  components/gcp/automl/import_data_from_gcs/component.py
  components/gcp/automl/import_data_from_gcs/component.yaml
  components/gcp/automl/prediction_service_batch_predict/component.py
  components/gcp/automl/prediction_service_batch_predict/component.yaml
  components/gcp/automl/split_dataset_table_column_names/component.py
  components/gcp/automl/split_dataset_table_column_names/component.yaml
  samples/core/AutoML tables/AutoML Tables - Retail product stockout prediction.ipynb
Labels: approved, area/components, area/samples, area/samples/notebooks, lgtm, size/XXL

#2192 SDK - Moved the _container_builder from kfp.compiler to kfp.containers
  sdk/python/kfp/compiler/__init__.py
  sdk/python/kfp/containers/_build_image_api.py
  sdk/python/kfp/containers/_component_builder.py
  sdk/python/kfp/containers/_container_builder.py
  sdk/python/kfp/containers/_gcs_helper.py
  sdk/python/tests/compiler/component_builder_test.py
  sdk/python/tests/compiler/container_builder_test.py
  test/sample-test/sample_test_launcher.py
Labels: approved, lgtm, sdk/containers, size/S

#2227 SDK - Components - Fix - Stop serializing string values
  sdk/python/kfp/components/_data_passing.py
Labels: approved, area/sdk/components, kind/bug, lgtm, size/XS

#1873 Add necessary data types to api and database to support pipeline version.
  backend/api/pipeline.proto
  backend/api/resource_reference.proto
  backend/src/apiserver/BUILD.bazel
  backend/src/apiserver/client_manager.go
  backend/src/apiserver/list/list.go
  backend/src/apiserver/list/list_test.go
  backend/src/apiserver/model/BUILD.bazel
  backend/src/apiserver/model/experiment.go
  backend/src/apiserver/model/job.go
  backend/src/apiserver/model/pipeline.go
  backend/src/apiserver/model/pipeline_version.go
  backend/src/apiserver/model/pipeline_version_test.go
  backend/src/apiserver/model/run.go
  backend/src/apiserver/resource/model_converter.go
  backend/src/apiserver/resource/model_converter_test.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/server/api_converter.go
  backend/src/apiserver/server/api_converter_test.go
  backend/src/apiserver/server/list_request_util_test.go
  backend/src/apiserver/server/pipeline_upload_server_test.go
  backend/src/apiserver/server/util_test.go
  backend/src/apiserver/storage/db_fake.go
  backend/src/apiserver/storage/pipeline_store.go
  backend/src/apiserver/storage/pipeline_store_test.go
  backend/src/apiserver/storage/run_store.go
  backend/src/apiserver/storage/run_store_test.go
Labels: approved, lgtm, size/XXL

#2243 SDK: fix label check for ContainerOP entities
  sdk/python/kfp/compiler/_default_transformers.py
Labels: approved, lgtm, needs-ok-to-test, size/XS

#2224 third_party/metadata_envoy: Modify license file
  third_party/metadata_envoy/Dockerfile
  third_party/metadata_envoy/README.md
  third_party/metadata_envoy/dependencies.json
  third_party/metadata_envoy/dependency_helper.py
  third_party/metadata_envoy/license.txt
Labels: approved, lgtm, size/XXL

#2250 remove default namespace
  sdk/python/kfp/containers/_component_builder.py
Labels: approved, lgtm, size/S

#1031 Use Remote Build Execution for Bazel builds.
  WORKSPACE
  backend/Dockerfile
  backend/README.md
  backend/build_api_server.sh
  test/build_image.yaml
  tools/bazel_builder/BUILD
  tools/bazel_builder/Dockerfile
  tools/bazel_builder/OWNERS
  tools/bazel_builder/README.md
  tools/bazel_builder/bazelrc
Labels: approved, lgtm, size/L

#2266 SDK - Notebooks - Deprecated the docker magic
  sdk/python/kfp/notebook/_magic.py
Labels: approved, area/sdk, lgtm, size/XS

#2265 SDK - Components - component_ref.name should only be set when component was loaded by name
  sdk/python/kfp/components/_components.py
Labels: approved, area/sdk/components, lgtm, size/XS

#2260 SDK - Lightweight - Convert the names of file inputs and outputs
  sdk/python/kfp/components/_python_op.py
  sdk/python/tests/components/test_python_op.py
Labels: approved, area/sdk/components, lgtm, size/L
