Repository kubeflow/pipelines, pull requests merged in 2019-10, with the labels that each got.

#2269 SDK - Components - Fixed small bugs in graph component resolving
  sdk/python/kfp/components/_components.py
Labels: approved, area/sdk/components, kind/bug, lgtm, size/S

#2245 SDK - Lightweight - Added package installation support to func_to_container_op
  sdk/python/kfp/components/_python_op.py
  sdk/python/tests/components/test_python_op.py
Labels: approved, area/sdk/components, lgtm, size/M

#2242 Update doc for MKP release
  manifests/gcp_marketplace/guide.md
  manifests/gcp_marketplace/schema.yaml
Labels: approved, lgtm, size/L

#2259 SDK - Compiler - Fixed small bug in data passing rewriter
  sdk/python/kfp/compiler/_data_passing_rewriter.py
Labels: approved, area/sdk/dsl/compiler, kind/bug, lgtm, size/XS

#2201 Add third party license + source code to argo and minio images to comply with their license
  .release.cloudbuild.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/values.yaml
  manifests/kustomize/base/argo/workflow-controller-configmap.yaml
  manifests/kustomize/base/argo/workflow-controller-deployment.yaml
  manifests/kustomize/base/kustomization.yaml
  manifests/kustomize/env/dev/minio/minio-deployment.yaml
  manifests/kustomize/env/gcp/kustomization.yaml
  manifests/kustomize/env/gcp/minio/minio-gcs-gateway-deployment.yaml
  manifests/kustomize/namespaced-install.yaml
  manifests/kustomize/namespaced/workflow-controller-configmap.yaml
  third_party/README.md
  third_party/argo/Dockerfile.argoexec
  third_party/argo/Dockerfile.workflow-controller
  third_party/argo/cloudbuild.yaml
  third_party/argo/license.txt
  third_party/argo/release.sh
  third_party/argo/repo-MPL.txt
  third_party/download_source.sh
  third_party/minio/Dockerfile
  third_party/minio/cloudbuild.yaml
  third_party/minio/license.txt
  third_party/minio/release.sh
  third_party/minio/repo-MPL.txt
Labels: approved, lgtm, size/XXL

#2272 SDK - Components - Verify the object type when serializing primitive arguments
  sdk/python/kfp/components/_data_passing.py
Labels: approved, area/sdk/components, kind/bug, lgtm, size/M

#2258 Samples - Added the data passing tutorial
  samples/tutorials/Data passing in python components.ipynb
Labels: approved, area/samples, area/samples/notebooks, lgtm, size/L

#2284 Disable cloudsql and update to v0.1.31
  manifests/gcp_marketplace/README.md
  manifests/gcp_marketplace/chart/kubeflow-pipelines/values.yaml
  manifests/gcp_marketplace/guide.md
  manifests/gcp_marketplace/schema.yaml
Labels: approved, lgtm, size/M

#2280 Remove usage of deprecated ContainerOp methods in use_gcp_secret
  sdk/python/kfp/gcp.py
Labels: approved, lgtm, needs-ok-to-test, size/M

#2288 fix for MKP
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/metadata.yaml
Labels: approved, lgtm, size/XS

#2274 Refactor resource op sample for sample test coverage
  samples/core/resource_ops/resource_ops.py
  test/sample_test.yaml
Labels: approved, lgtm, size/M

#2289 [MKP] Fix gcr paths in values.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/values.yaml
Labels: approved, lgtm, size/S

#2273 SDK - Components - Creating graph components from python pipeline function
  sdk/python/kfp/components/__init__.py
  sdk/python/kfp/components/_python_to_graph_component.py
  sdk/python/tests/components/test_data/component_with_0_inputs_and_2_outputs.component.yaml
  sdk/python/tests/components/test_data/component_with_2_inputs_and_0_outputs.component.yaml
  sdk/python/tests/components/test_data/component_with_2_inputs_and_2_outputs.component.yaml
  sdk/python/tests/components/test_python_pipeline_to_graph_component.py
Labels: approved, area/sdk/components, lgtm, size/L

#2270 SDK - Components - Reorganized TaskSpec execution options
  sdk/python/kfp/components/_structures.py
  sdk/python/tests/components/test_graph_components.py
Labels: approved, area/sdk/components, lgtm, size/M

#2271 SDK - Compiler - Make it possible to create more portable pipelines
  sdk/python/kfp/_client.py
  sdk/python/kfp/_runners.py
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/dsl/__init__.py
Labels: approved, area/sdk/dsl/compiler, lgtm, size/M

#2282 tech writer edits
  components/gcp/dataproc/submit_spark_job/README.md
Labels: approved, lgtm, ok-to-test, size/M

#2285 tech writer edits
  components/gcp/dataproc/create_cluster/README.md
Labels: approved, lgtm, ok-to-test, size/M

#2291 tech writer edits
  components/gcp/dataproc/submit_pig_job/README.md
Labels: approved, lgtm, ok-to-test, size/M

#2219 [Component] Add Managed Spot Training Support for SageMaker
  components/aws/sagemaker/Dockerfile
  components/aws/sagemaker/batch_transform/component.yaml
  components/aws/sagemaker/common/_utils.py
  components/aws/sagemaker/common/hpo.template.yaml
  components/aws/sagemaker/common/train.template.yaml
  components/aws/sagemaker/deploy/component.yaml
  components/aws/sagemaker/ground_truth/component.yaml
  components/aws/sagemaker/hyperparameter_tuning/README.md
  components/aws/sagemaker/hyperparameter_tuning/component.yaml
  components/aws/sagemaker/hyperparameter_tuning/src/hyperparameter_tuning.py
  components/aws/sagemaker/model/component.yaml
  components/aws/sagemaker/run_tests.py
  components/aws/sagemaker/test/__init__.py
  components/aws/sagemaker/test/test_hpo.py
  components/aws/sagemaker/test/test_train.py
  components/aws/sagemaker/train/component.yaml
  components/aws/sagemaker/train/src/train.py
  components/aws/sagemaker/workteam/component.yaml
  samples/contrib/aws-samples/mnist-kmeans-sagemaker/kmeans-hpo-pipeline.py
  samples/contrib/aws-samples/mnist-kmeans-sagemaker/mnist-classification-pipeline.py
Labels: approved, lgtm, ok-to-test, size/L

#2264 SDK - Components - Added the ComponentSpec.save method
  sdk/python/kfp/components/_python_op.py
  sdk/python/kfp/components/_structures.py
  sdk/python/kfp/containers/_component_builder.py
Labels: approved, area/sdk/components, lgtm, size/S

#2296 Add CMLE deploy comment missing parameters
  components/gcp/ml_engine/deploy/component.yaml
Labels: approved, lgtm, size/XS

#2146 [SDK-compiler] Refactor Compiler to expose an API to write out yaml spec of pipeline.
  sdk/python/kfp/compiler/compiler.py
Labels: approved, lgtm, size/L

#2299 [Component] Add VPC Interface Endpoint Support for SageMaker
  components/aws/sagemaker/batch_transform/component.yaml
  components/aws/sagemaker/batch_transform/src/batch_transform.py
  components/aws/sagemaker/common/_utils.py
  components/aws/sagemaker/deploy/component.yaml
  components/aws/sagemaker/deploy/src/deploy.py
  components/aws/sagemaker/ground_truth/README.md
  components/aws/sagemaker/ground_truth/component.yaml
  components/aws/sagemaker/ground_truth/src/ground_truth.py
  components/aws/sagemaker/hyperparameter_tuning/README.md
  components/aws/sagemaker/hyperparameter_tuning/component.yaml
  components/aws/sagemaker/hyperparameter_tuning/src/hyperparameter_tuning.py
  components/aws/sagemaker/model/component.yaml
  components/aws/sagemaker/model/src/create_model.py
  components/aws/sagemaker/train/component.yaml
  components/aws/sagemaker/train/src/train.py
  components/aws/sagemaker/workteam/README.md
  components/aws/sagemaker/workteam/component.yaml
  components/aws/sagemaker/workteam/src/workteam.py
  samples/contrib/aws-samples/mnist-kmeans-sagemaker/kmeans-hpo-pipeline.py
  samples/contrib/aws-samples/mnist-kmeans-sagemaker/mnist-classification-pipeline.py
Labels: approved, lgtm, ok-to-test, size/L

#2303 SDK - Compiler - Fixed deprecation warning when calling compile
  sdk/python/kfp/compiler/compiler.py
Labels: approved, area/sdk/dsl/compiler, lgtm, size/XS

#2276 SDK - Containers - Deprecated build_docker_image
  sdk/python/kfp/containers/_component_builder.py
Labels: approved, lgtm, sdk/containers, size/XS

#2257 SDK - Components - Deprecate the get and set methods for default image in favor of plain variable
  sdk/python/kfp/components/_python_op.py
Labels: approved, area/sdk/components, lgtm, size/S

#2293 Samples - Simplified pipeline submission code in samples
  samples/contrib/arena-samples/standalonejob/standalone_pipeline.ipynb
  samples/contrib/arena-samples/standalonejob/standalone_pipeline.py
  samples/contrib/ibm-samples/ffdl-seldon/ffdl_pipeline.ipynb
  samples/contrib/ibm-samples/openscale/README.md
  samples/contrib/image-captioning-gcp/Image Captioning TF 2.0.ipynb
  samples/core/ai-platform/Chicago Crime Pipeline.ipynb
  samples/core/dataflow/dataflow.ipynb
  samples/core/kubeflow_tf_serving/kubeflow_tf_serving.ipynb
  samples/core/lightweight_component/lightweight_component.ipynb
  samples/core/multiple_outputs/Multiple outputs - basics.ipynb
  samples/core/tfx-oss/TFX Example.ipynb
Labels: approved, area/samples, area/samples/notebooks, lgtm, size/L

#2279 Samples - Switched the build_component sample to the new container API
  samples/core/component_build/component_build.ipynb
  samples/core/component_build/requirements.txt
Labels: approved, area/samples, lgtm, size/L

#2309 [MKP/doc] Update doc for changes of service account credential.
  manifests/gcp_marketplace/README.md
  manifests/gcp_marketplace/guide.md
Labels: approved, lgtm, size/M

#2306 SDK/DSL: ContainerOp.add_pvolume - Fix volume passed in add_volume
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/tests/dsl/container_op_tests.py
Labels: approved, lgtm, size/S

#2316 SDK - Containers - Made python package installation more robust
  sdk/python/kfp/containers/_component_builder.py
  sdk/python/tests/compiler/component_builder_test.py
Labels: approved, lgtm, sdk/containers, size/XS

#2321 [SDK/Compiler] Add _create_and_write_workflow method
  sdk/python/kfp/compiler/compiler.py
Labels: approved, lgtm, size/M

#2315 Extend KFServing component with autoscaling and server mode
  components/kubeflow/kfserving/Dockerfile
  components/kubeflow/kfserving/component.yaml
  components/kubeflow/kfserving/sample-pipeline.py
  components/kubeflow/kfserving/src/app.py
  components/kubeflow/kfserving/src/kfservingdeployer.py
Labels: approved, area/components, lgtm, size/L

#2229 SDK - Compiler - Move Argo volume specifications to templates
  sdk/python/kfp/compiler/_data_passing_rewriter.py
  sdk/python/kfp/compiler/_op_to_template.py
  sdk/python/kfp/compiler/compiler.py
  sdk/python/tests/compiler/testdata/param_substitutions.yaml
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
  sdk/python/tests/compiler/testdata/volume.yaml
  sdk/python/tests/compiler/testdata/volume_snapshotop_rokurl.yaml
  sdk/python/tests/compiler/testdata/volume_snapshotop_sequential.yaml
  sdk/python/tests/compiler/testdata/volumeop_basic.yaml
  sdk/python/tests/compiler/testdata/volumeop_dag.yaml
  sdk/python/tests/compiler/testdata/volumeop_parallel.yaml
  sdk/python/tests/compiler/testdata/volumeop_sequential.yaml
Labels: approved, area/sdk/dsl/compiler, lgtm, size/L

#2297 SDK - Compiler - Fix bugs in the data passing rewriter
  sdk/python/kfp/compiler/_data_passing_rewriter.py
Labels: approved, lgtm, needs-ok-to-test, size/XS

#2263 Components - Removed trailing whitespace from AutoML components code
  components/gcp/automl/create_model_for_tables/component.py
  components/gcp/automl/split_dataset_table_column_names/component.py
Labels: approved, area/components, lgtm, size/XS

#2277 SDK - Components - Deprecated build_python_component
  sdk/python/kfp/containers/_component_builder.py
Labels: approved, area/sdk/components/python_container_op, lgtm, size/XS

#1683 SDK - Hiding Argo's workflow.uid placeholder behind DSL
  components/sample/keras/train_classifier/README.md
  samples/core/xgboost_training_cm/xgboost_training_cm.py
  sdk/python/kfp/dsl/__init__.py
Labels: approved, area/sdk/dsl, lgtm, size/XS

#2183 Docs - Added the direct kfp module members to documentation
  docs/source/kfp.rst
Labels: approved, area/docs, lgtm, size/XS

#2262 SDK - Components - Restored attribute order when generating component.yaml files
  components/gcp/automl/create_dataset_for_tables/component.yaml
  components/gcp/automl/create_model_for_tables/component.yaml
  components/gcp/automl/import_data_from_bigquery/component.yaml
  components/gcp/automl/import_data_from_gcs/component.yaml
  components/gcp/automl/prediction_service_batch_predict/component.yaml
  components/gcp/automl/split_dataset_table_column_names/component.yaml
  sdk/python/kfp/components/_yaml_utils.py
Labels: approved, area/sdk/components, lgtm, size/XL

#2323 SDK - Compiler - Added the component spec annotations to the compiled workflow
  sdk/python/kfp/compiler/_op_to_template.py
Labels: approved, area/sdk/dsl/compiler, lgtm, size/XS

#2301 tech writer edits
  components/gcp/dataproc/submit_pyspark_job/README.md
Labels: approved, area/components, lgtm, ok-to-test, size/M

#2313 tech writer edits
  components/gcp/dataproc/delete_cluster/README.md
Labels: approved, lgtm, ok-to-test, size/M

#2314 SDK - Tests - Test creating component from the real AutoML pipeline
  sdk/python/tests/components/test_data/retail_product_stockout_prediction_pipeline.component.yaml
  sdk/python/tests/components/test_data/retail_product_stockout_prediction_pipeline.py
  sdk/python/tests/components/test_python_pipeline_to_graph_component.py
Labels: approved, area/sdk/tests, lgtm, size/L

#2344 [License] Fix third-party license
  backend/src/apiserver/visualization/third_party_licenses.csv
Labels: approved, lgtm, size/XS

#2342 [Doc] Fix a typo in MKP guide
  manifests/gcp_marketplace/guide.md
Labels: approved, lgtm, size/XS

#2308 [MKP] Remove service account credential from deployment page.
  manifests/gcp_marketplace/chart/kubeflow-pipelines/values.yaml
  manifests/gcp_marketplace/schema.yaml
Labels: approved, lgtm, size/S

#2319 [Sample] Add new TFX::OSS sample
  backend/src/apiserver/config/sample_config.json
  samples/contrib/parameterized_tfx_oss/README.md
  samples/contrib/parameterized_tfx_oss/parameterized_tfx_oss.py
  samples/contrib/parameterized_tfx_oss/parameterized_tfx_oss.tar.gz
  test/sample-test/configs/parameterized_tfx_oss.config.yaml
  test/sample-test/run_sample_test.py
  test/sample-test/sample_test_launcher.py
  test/sample_test.yaml
Labels: approved, lgtm, size/L

#2325 Tests - When testing SDK install it using pip
  .travis.yml
Labels: approved, area/testing, lgtm, size/XS

#2339 enlarge MKP cluster constraint
  manifests/gcp_marketplace/schema.yaml
Labels: approved, area/deployment/marketplace, lgtm, size/XS

#2327 add ai_platform test
  samples/core/ai_platform/README.md
  samples/core/ai_platform/ai_platform.ipynb
  samples/core/ai_platform/images/chicago_crime_pipeline.png
  samples/core/ai_platform/images/chicago_crime_predictions.png
  samples/core/ai_platform/local/Chicago Crime Research.ipynb
  samples/core/ai_platform/training/.gitignore
  samples/core/ai_platform/training/.python-version
  samples/core/ai_platform/training/requirements.txt
  samples/core/ai_platform/training/setup.py
  samples/core/ai_platform/training/trainer/model.py
  samples/core/ai_platform/training/trainer/task.py
  samples/core/ai_platform/training/trainer/util.py
  test/sample-test/configs/ai_platform.config.yaml
  test/sample_test.yaml
Labels: approved, lgtm, size/M

#2328 Add sample test for multiple output
  samples/core/multiple_outputs/multiple_outputs.ipynb
  test/sample-test/configs/multiple_outputs.config.yaml
  test/sample_test.yaml
Labels: approved, lgtm, size/M

#2349 Fix potential issue of the ai platform sample when running it in the ai platform notebook
  samples/core/ai_platform/ai_platform.ipynb
Labels: approved, lgtm, size/XS

#2347 Typo in Data passing in python components.ipynb
  samples/tutorials/Data passing in python components.ipynb
Labels: approved, lgtm, needs-ok-to-test, size/XS

#2256 SDK - Containers - Getting namespace lazily
  sdk/python/kfp/containers/_container_builder.py
Labels: approved, lgtm, sdk/containers, size/S

#2346 [Test] Add unittest against TFX
  .travis.yml
Labels: approved, area/testing, lgtm, size/M

#2366 Components - Updated the gcp dataproc create_cluster component image
  components/gcp/dataproc/create_cluster/README.md
  components/gcp/dataproc/create_cluster/component.yaml
  components/gcp/dataproc/create_cluster/sample.ipynb
Labels: approved, area/components, lgtm, size/XS

#2355 add cloud-platform scope in the test to reclaim the ai platform sample models
  samples/contrib/parameterized_tfx_oss/README.md
  samples/core/ai_platform/ai_platform.ipynb
  samples/core/xgboost_training_cm/README.md
  sdk/python/kfp/_client.py
  test/deploy-cluster.sh
Labels: approved, lgtm, size/S

#2331 tech writer edits
  components/gcp/dataproc/submit_sparksql_job/README.md
Labels: approved, lgtm, ok-to-test, size/M

#2360 [Sample] Improve tfx oss sample
  samples/contrib/parameterized_tfx_oss/README.md
  samples/contrib/parameterized_tfx_oss/parameterized_tfx_oss.py
  samples/contrib/parameterized_tfx_oss/parameterized_tfx_oss.tar.gz
  test/sample-test/run_sample_test.py
Labels: approved, area/samples, area/samples/notebooks, lgtm, size/S

#2371 [Samples] Add numerology as samples/OWNERS
  samples/OWNERS
Labels: approved, lgtm, size/XS

#2216 SDK - Containers - Added support for container image cache
  sdk/python/kfp/containers/_build_image_api.py
  sdk/python/kfp/containers/_cache.py
  sdk/python/tests/containers/test_build_image_api.py
Labels: approved, lgtm, sdk/containers, size/L

#2361 [Doc] Fix some description of preload samples
  backend/src/apiserver/config/sample_config.json
Labels: approved, lgtm, size/XS

#1578 SDK - Improve errors when ContainerOp.output is unavailable
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/tests/compiler/compiler_tests.py
Labels: approved, area/sdk/dsl, lgtm, size/M

#2370 [Frontend] Fix cannot copy logs in LogViewer when scrolling
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/LogViewer.test.tsx
  frontend/src/components/LogViewer.tsx
  frontend/src/components/__snapshots__/LogViewer.test.tsx.snap
  frontend/tsconfig.json
Labels: approved, area/front-end, kind/bug, lgtm, size/XL

#2380 add animesh to the approvers of the kfserving
  components/kubeflow/kfserving/OWNERS
Labels: approved, lgtm, size/XS

#2369 KFServing move to v1alpha2
  components/kubeflow/kfserving/Dockerfile
  components/kubeflow/kfserving/component.yaml
  components/kubeflow/kfserving/sample-pipeline.py
  components/kubeflow/kfserving/src/app.py
  components/kubeflow/kfserving/src/kfservingdeployer.py
Labels: approved, lgtm, size/L

#2381 [Frontend] Script and documentation to start a frontend dev env that works with all API endpoints
  frontend/README.md
  frontend/package.json
  frontend/start-proxy-standalone-and-server.sh
  frontend/start-proxy-standalone.sh
Labels: approved, area/front-end, lgtm, size/M

#2382 move favicon path, root is override by inverse proxy
  frontend/public/index.html
  frontend/public/static/favicon.ico
  frontend/public/static/manifest.json
Labels: approved, lgtm, size/XS

#2292 SDK - Client - Added a way to set experiment name using environment variables
  samples/README.md
  samples/contrib/arena-samples/standalonejob/standalone_pipeline.ipynb
  samples/contrib/ibm-samples/ffdl-seldon/ffdl_pipeline.ipynb
  samples/contrib/image-captioning-gcp/Image Captioning TF 2.0.ipynb
  samples/core/ai_platform/ai_platform.ipynb
  samples/core/component_build/component_build.ipynb
  samples/core/dataflow/dataflow.ipynb
  samples/core/dsl_static_type_checking/dsl_static_type_checking.ipynb
  samples/core/kubeflow_tf_serving/kubeflow_tf_serving.ipynb
  samples/core/lightweight_component/lightweight_component.ipynb
  samples/core/multiple_outputs/multiple_outputs.ipynb
  samples/core/tfx-oss/TFX Example.ipynb
  sdk/python/kfp/_client.py
  test/sample-test/check_notebook_results.py
  test/sample-test/configs/ai_platform.config.yaml
  test/sample-test/configs/component_build.config.yaml
  test/sample-test/configs/dataflow.config.yaml
  test/sample-test/configs/kubeflow_tf_serving.config.yaml
  test/sample-test/configs/multiple_outputs.config.yaml
  test/sample-test/run_sample_test.py
  test/sample-test/sample_test_launcher.py
Labels: approved, area/sdk/client, area/testing, lgtm, size/L

#2374 SDK - Added version
  sdk/python/kfp/__init__.py
  sdk/python/setup.py
  sdk/python/tests/test_kfp.py
Labels: approved, area/sdk, lgtm, size/S

#2305 [Frontend] Node detail view now can show workflow input/output artifacts
  frontend/src/components/DetailsTable.test.tsx
  frontend/src/components/DetailsTable.tsx
  frontend/src/components/MinioArtifactLink.test.tsx
  frontend/src/components/MinioArtifactLink.tsx
  frontend/src/components/__snapshots__/DetailsTable.test.tsx.snap
  frontend/src/components/__snapshots__/MinioArtifactLink.test.tsx.snap
  frontend/src/lib/StaticGraphParser.ts
  frontend/src/lib/WorkflowParser.test.ts
  frontend/src/lib/WorkflowParser.ts
  frontend/src/pages/RecurringRunDetails.tsx
  frontend/src/pages/RunDetails.tsx
  frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
  frontend/third_party/argo-ui/kubernetes.ts
Labels: approved, area/front-end, lgtm, ok-to-test, priority/p0, size/XL

#2156 GUI: should pop-up a correct info when delete more than one pipeline
  frontend/src/lib/Buttons.ts
Labels: approved, area/front-end, lgtm, ok-to-test, size/XS

#2220 [Sample] update XGBoost sample
  samples/core/xgboost_training_cm/README.md
  samples/core/xgboost_training_cm/xgboost_training_cm.py
  test/component_test.yaml
  test/sample-test/run_sample_test.py
  test/sample-test/sample_test_launcher.py
Labels: approved, lgtm, size/XL

#2387 enable the check for dataflow
  test/sample-test/configs/dataflow.config.yaml
Labels: approved, lgtm, size/XS

#2396 Add Tomcli as kfs component reviewer
  components/kubeflow/kfserving/OWNERS
  components/kubeflow/kfserving/sample-pipeline.py
Labels: approved, lgtm, size/M

#2398 Update Watson ML default framework version
  components/ibm-components/watson/train/component.yaml
  components/ibm-components/watson/train/src/wml-train.py
  samples/contrib/ibm-samples/watson/watson_train_serve_pipeline.py
Labels: approved, lgtm, size/S

#2390 quick custom spec fix
  components/kubeflow/kfserving/src/kfservingdeployer.py
Labels: approved, lgtm, size/XS

#2389 add test config comment
  test/sample-test/configs/schema.config.yaml
Labels: approved, lgtm, size/XS

#2385 Update samples/core/tfx-oss to tfx==0.14.0 and kfp=0.1.31
  samples/core/tfx-oss/README.md
  samples/core/tfx-oss/TFX Example.ipynb
  samples/core/tfx-oss/utils/taxi_utils.py
Labels: approved, lgtm, ok-to-test, size/M

#2388 Remove jingzhang36 and rmgogogo from frontend reviewer list
  frontend/OWNERS
Labels: approved, lgtm, size/XS

#2400 [Test/Sample test] Fix model version in AI platform sample
  samples/core/ai_platform/ai_platform.ipynb
Labels: approved, lgtm, size/XS

#2341 Fix pipeline cannot run bug when using marketplace managed storage
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/argo.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/values.yaml
Labels: approved, kind/bug, lgtm, size/S

#2345 SDK - Python components - Fixed handling multiline decorators
  sdk/python/kfp/components/_python_op.py
  sdk/python/tests/components/test_python_op.py
Labels: approved, area/sdk/components, lgtm, size/M

#2411 SDK - DSL - Make is_exit_handler unnecessary in ContainerOp
  samples/core/exit_handler/exit_handler.py
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/kfp/dsl/_ops_group.py
  sdk/python/kfp/dsl/_pipeline.py
  sdk/python/kfp/dsl/_resource_op.py
  sdk/python/tests/compiler/testdata/basic.yaml
  sdk/python/tests/compiler/testdata/basic_no_decorator.yaml
Labels: approved, area/sdk/dsl, lgtm, size/M

#2190 Added the backend Go module cache to .gitignote
  .gitignore
Labels: approved, lgtm, size/XS

#2384 [Sample] Add back visualization in XGBoost sample
  samples/core/xgboost_training_cm/README.md
  samples/core/xgboost_training_cm/xgboost_training_cm.py
  test/sample-test/run_sample_test.py
Labels: approved, lgtm, size/M

#2409 [Frontend] Prettier config to be consistent with existing code style
  frontend/.prettierrc.yaml
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/GcsLink.tsx
  frontend/tslint.json
Labels: approved, area/front-end, lgtm, size/XXL

#1643 Allows uploading a pipeline in new run form
  frontend/src/pages/NewRun.tsx
  frontend/src/pages/ResourceSelector.tsx
  frontend/src/pages/__snapshots__/NewRun.test.tsx.snap
Labels: approved, area/front-end, lgtm, size/L

#2338 Add pipeline version api methods
  backend/api/pipeline.proto
  backend/src/apiserver/BUILD.bazel
  backend/src/apiserver/model/BUILD.bazel
  backend/src/apiserver/resource/client_manager_fake.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/server/BUILD.bazel
  backend/src/apiserver/server/pipeline_server.go
  backend/src/apiserver/server/pipeline_server_test.go
  backend/src/apiserver/server/util.go
  backend/src/apiserver/storage/pipeline_store.go
  backend/src/apiserver/storage/pipeline_store_test.go
Labels: approved, lgtm, size/XXL

#2373 tech writer edits
  components/gcp/ml_engine/train/README.md
Labels: approved, lgtm, ok-to-test, size/L

#2278 Components - Added the "AutoML Export data to GCS" component
  components/gcp/automl/export_data_to_gcs/component.py
  components/gcp/automl/export_data_to_gcs/component.yaml
Labels: approved, area/components, lgtm, size/L

#2324 tech writer edits
  components/gcp/dataproc/submit_hadoop_job/README.md
Labels: approved, lgtm, ok-to-test, size/L

#2222 [SDK/Client] Improve the url format check for kfp.Client
  sdk/python/kfp/_client.py
Labels: approved, area/sdk/client, lgtm, size/XS

#2428 [Frontend] Upgrade typescript to 3.6
  frontend/package-lock.json
  frontend/package.json
  frontend/src/TestUtils.tsx
Labels: approved, area/front-end, lgtm, size/M

#2431 [Frontend] Configure tslint for better DX
  frontend/package.json
  frontend/tsconfig.json
  frontend/tsconfig.prod.json
  frontend/tslint.json
  frontend/tslint.prod.json
Labels: approved, area/front-end, lgtm, size/S

#2433 Release e9b96de317989a9673ef88d88fb9dab9dac3005f
  components/gcp/bigquery/query/README.md
  components/gcp/bigquery/query/component.yaml
  components/gcp/bigquery/query/sample.ipynb
  components/gcp/dataflow/launch_python/README.md
  components/gcp/dataflow/launch_python/component.yaml
  components/gcp/dataflow/launch_python/sample.ipynb
  components/gcp/dataflow/launch_template/README.md
  components/gcp/dataflow/launch_template/component.yaml
  components/gcp/dataflow/launch_template/sample.ipynb
  components/gcp/dataproc/create_cluster/README.md
  components/gcp/dataproc/create_cluster/component.yaml
  components/gcp/dataproc/create_cluster/sample.ipynb
  components/gcp/dataproc/delete_cluster/README.md
  components/gcp/dataproc/delete_cluster/component.yaml
  components/gcp/dataproc/delete_cluster/sample.ipynb
  components/gcp/dataproc/submit_hadoop_job/README.md
  components/gcp/dataproc/submit_hadoop_job/component.yaml
  components/gcp/dataproc/submit_hadoop_job/sample.ipynb
  components/gcp/dataproc/submit_hive_job/README.md
  components/gcp/dataproc/submit_hive_job/component.yaml
  components/gcp/dataproc/submit_hive_job/sample.ipynb
  components/gcp/dataproc/submit_pig_job/README.md
  components/gcp/dataproc/submit_pig_job/component.yaml
  components/gcp/dataproc/submit_pig_job/sample.ipynb
  components/gcp/dataproc/submit_pyspark_job/README.md
  components/gcp/dataproc/submit_pyspark_job/component.yaml
  components/gcp/dataproc/submit_pyspark_job/sample.ipynb
  components/gcp/dataproc/submit_spark_job/README.md
  components/gcp/dataproc/submit_spark_job/component.yaml
  components/gcp/dataproc/submit_spark_job/sample.ipynb
  components/gcp/dataproc/submit_sparksql_job/README.md
  components/gcp/dataproc/submit_sparksql_job/component.yaml
  components/gcp/dataproc/submit_sparksql_job/sample.ipynb
  components/gcp/ml_engine/batch_predict/README.md
  components/gcp/ml_engine/batch_predict/component.yaml
  components/gcp/ml_engine/batch_predict/sample.ipynb
  components/gcp/ml_engine/deploy/README.md
  components/gcp/ml_engine/deploy/component.yaml
  components/gcp/ml_engine/deploy/sample.ipynb
  components/gcp/ml_engine/train/README.md
  components/gcp/ml_engine/train/component.yaml
  components/gcp/ml_engine/train/sample.ipynb
  components/kubeflow/deployer/component.yaml
  components/kubeflow/dnntrainer/component.yaml
  components/kubeflow/launcher/kubeflow_tfjob_launcher_op.py
  components/kubeflow/launcher/src/train.template.yaml
  components/local/confusion_matrix/component.yaml
  components/local/roc/component.yaml
  samples/core/ai_platform/ai_platform.ipynb
  samples/core/dataflow/dataflow.ipynb
  samples/core/kubeflow_tf_serving/kubeflow_tf_serving.ipynb
  samples/core/xgboost_training_cm/xgboost_training_cm.py
Labels: approved, lgtm, size/L

#2434 Update sdk release version
  components/gcp/container/component_sdk/python/setup.py
  manifests/kustomize/base/kustomization.yaml
  sdk/python/kfp/__init__.py
Labels: approved, lgtm, size/S

#2332 tech writer edits
  components/gcp/dataproc/submit_hive_job/README.md
Labels: approved, lgtm, ok-to-test, size/M

#2340 SDK/CLI: Implement kfp pipeline group
  sdk/python/kfp/__main__.py
  sdk/python/kfp/_client.py
  sdk/python/kfp/cli/cli.py
  sdk/python/kfp/cli/pipeline.py
Labels: approved, area/cli, lgtm, size/L

#2439 [Test] Fix post-submit test
  test/sample-test/sample_test_launcher.py
Labels: approved, area/testing, lgtm, size/XS

#2438 SDK - Client - Makes the create_run output nicer
  sdk/python/kfp/_client.py
Labels: approved, area/sdk/client, lgtm, size/XS

#2436 Add owner files for marketplace deployment
  manifests/gcp_marketplace/OWNERS
Labels: approved, lgtm, size/XS

#2376 [Frontend] Make links in pipeline description clickable
  backend/src/apiserver/config/sample_config.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Description.test.tsx
  frontend/src/components/Description.tsx
  frontend/src/components/__snapshots__/Description.test.tsx.snap
  frontend/src/components/viewers/MarkdownViewer.test.tsx
  frontend/src/components/viewers/MarkdownViewer.tsx
  frontend/src/components/viewers/__snapshots__/MarkdownViewer.test.tsx.snap
  frontend/src/pages/PipelineDetails.tsx
  frontend/src/pages/PipelineList.tsx
  frontend/src/pages/__snapshots__/PipelineDetails.test.tsx.snap
  frontend/src/pages/__snapshots__/PipelineList.test.tsx.snap
Labels: approved, area/front-end, kind/feature, lgtm, size/XL

#2441 Add --bind_all option for tensorboard
  backend/src/crd/controller/viewer/reconciler/reconciler.go
  backend/src/crd/controller/viewer/reconciler/reconciler_test.go
Labels: approved, lgtm, ok-to-test, size/XS

#2446 [Request for comments] Add config for yapf and pylintrc
  .pylintrc
  .style.yapf
  CONTRIBUTING.md
Labels: approved, lgtm, size/L

#2333 SDK - Refactoring - Split the K8sHelper class
  sdk/python/kfp/_client.py
  sdk/python/kfp/compiler/_k8s_helper.py
  sdk/python/kfp/compiler/_op_to_template.py
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/containers/_container_builder.py
  sdk/python/kfp/containers/_k8s_job_helper.py
  sdk/python/tests/compiler/k8s_helper_tests.py
  sdk/python/tests/dsl/artifact_location_tests.py
Labels: approved, lgtm, sdk/containers, size/L

#2437 SDK - Setup - Added cloudpickle to requirements
  sdk/python/requirements.txt
  sdk/python/setup.py
Labels: approved, area/sdk, lgtm, size/XS

#2444 Fix CustomTable.tsx layout problems
  frontend/src/components/CustomTable.tsx
  frontend/src/components/CustomTableRow.tsx
  frontend/src/components/__snapshots__/CustomTable.test.tsx.snap
  frontend/src/pages/PipelineList.tsx
  frontend/src/pages/__snapshots__/RunList.test.tsx.snap
Labels: approved, area/front-end, kind/bug, lgtm, priority/p0, size/XL

#2459 [Frontend] UI shows specified task display name in PipelineDetail page
  frontend/src/lib/StaticGraphParser.test.ts
  frontend/src/lib/StaticGraphParser.ts
  frontend/src/lib/WorkflowParser.ts
Labels: approved, area/front-end, kind/feature, lgtm, size/L

#2463 [Frontend] Check format in travis CI
  .travis.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/scripts/check-format-error-info.js
  frontend/tslint.json
Labels: approved, area/front-end, kind/code-quality, lgtm, size/M

#2336 SDK - Tests - Fixed most of the test warnings
  sdk/python/kfp/aws.py
  sdk/python/kfp/azure.py
  sdk/python/tests/compiler/testdata/withitem_basic.py
  sdk/python/tests/compiler/testdata/withitem_basic.yaml
  sdk/python/tests/compiler/testdata/withitem_nested.py
  sdk/python/tests/compiler/testdata/withitem_nested.yaml
  sdk/python/tests/compiler/testdata/withparam_global.py
  sdk/python/tests/compiler/testdata/withparam_global.yaml
  sdk/python/tests/compiler/testdata/withparam_global_dict.py
  sdk/python/tests/compiler/testdata/withparam_global_dict.yaml
  sdk/python/tests/components/test_components.py
  sdk/python/tests/components/test_graph_components.py
  sdk/python/tests/components/test_python_op.py
  sdk/python/tests/dsl/aws_extensions_tests.py
  sdk/python/tests/dsl/test_azure_extensions.py
Labels: approved, area/sdk/tests, lgtm, size/M

#2465 Release notes for 0.1.32
  CHANGELOG.md
Labels: approved, lgtm, size/L

#2464 [Frontend] Update CONTRIBUTING.md with frontend code style info
  CONTRIBUTING.md
Labels: approved, area/docs, kind/doc, lgtm, size/XS

#190 Tests - Use base image for frontend tests
  test/frontend-integration-test/Dockerfile
  test/frontend-integration-test/run_test.sh
  test/frontend-integration-test/selenium-standalone-chrome-gcloud-nodejs.Docker/Dockerfile
  test/frontend-integration-test/selenium-standalone-chrome-gcloud-nodejs.Docker/Makefile
Labels: approved, area/front-end, area/testing, lgtm, size/L

#2453 Use string literals for reference resource relation and for reference resource type in frontend
  frontend/src/apis/experiment/.swagger-codegen/VERSION
  frontend/src/apis/experiment/api.ts
  frontend/src/apis/experiment/custom.d.ts
  frontend/src/apis/filter/.swagger-codegen/VERSION
  frontend/src/apis/filter/api.ts
  frontend/src/apis/filter/custom.d.ts
  frontend/src/apis/job/.swagger-codegen/VERSION
  frontend/src/apis/job/api.ts
  frontend/src/apis/job/custom.d.ts
  frontend/src/apis/pipeline/.swagger-codegen/VERSION
  frontend/src/apis/pipeline/api.ts
  frontend/src/apis/pipeline/custom.d.ts
  frontend/src/apis/run/.swagger-codegen/VERSION
  frontend/src/apis/run/api.ts
  frontend/src/apis/run/custom.d.ts
  frontend/src/apis/visualization/.swagger-codegen/VERSION
  frontend/src/apis/visualization/api.ts
  frontend/src/apis/visualization/custom.d.ts
  frontend/src/pages/ExperimentDetails.test.tsx
  frontend/src/pages/ExperimentDetails.tsx
  frontend/src/pages/ExperimentList.test.tsx
  frontend/src/pages/ExperimentList.tsx
  frontend/src/pages/RecurringRunsManager.tsx
  frontend/src/pages/RunList.test.tsx
  frontend/src/pages/RunList.tsx
  frontend/tsconfig.prod.json
Labels: approved, lgtm, size/L

#2466 Add option to hide tensorboard artifact
  components/gcp/container/component_sdk/python/kfp_component/google/ml_engine/_common_ops.py
  components/gcp/container/component_sdk/python/kfp_component/google/ml_engine/_wait_job.py
Labels: approved, lgtm, ok-to-test, size/S

#2425 Diagnose me dev env
  sdk/python/kfp/cli/diagnose_me/dev_env.py
  sdk/python/kfp/cli/diagnose_me/dev_env_test.py
Labels: approved, lgtm, size/L

#2451 SDK - Components - Added type to graph input references
  sdk/python/kfp/components/_components.py
  sdk/python/kfp/components/_python_to_graph_component.py
  sdk/python/kfp/components/_structures.py
  sdk/python/tests/components/test_data/retail_product_stockout_prediction_pipeline.component.yaml
  sdk/python/tests/components/test_graph_components.py
Labels: approved, area/sdk/components, lgtm, size/M

#2417 Adding the core libraries for diagnose_me tool.
  sdk/python/kfp/cli/diagnose_me/__init__.py
  sdk/python/kfp/cli/diagnose_me/gcp.py
  sdk/python/kfp/cli/diagnose_me/gcp_test.py
  sdk/python/kfp/cli/diagnose_me/kubernetes_cluster.py
  sdk/python/kfp/cli/diagnose_me/kubernetes_cluster_test.py
  sdk/python/kfp/cli/diagnose_me/utility.py
  sdk/python/kfp/cli/diagnose_me/utility_test.py
Labels: approved, area/cli, lgtm, size/XL

#2473 SDK - Python components - Fixed bug when mixing file outputs with return value outputs
  sdk/python/kfp/components/_python_op.py
  sdk/python/tests/components/test_python_op.py
Labels: approved, area/sdk/components, kind/bug, lgtm, priority/p0, size/M

#2476 [Sample] Update pre-load TFX::OSS sample
  backend/src/apiserver/config/sample_config.json
  samples/contrib/parameterized_tfx_oss/README.md
  samples/contrib/parameterized_tfx_oss/parameterized_tfx_oss.py
  samples/contrib/parameterized_tfx_oss/parameterized_tfx_oss.tar.gz
Labels: approved, lgtm, size/S

#2394 [Doc] Minor doc update
  manifests/gcp_marketplace/guide.md
Labels: approved, lgtm, size/M

#2480 [Frontend] Fix log viewer double scrollbar bug + not scrolling to bottom bug
  frontend/src/components/LogViewer.tsx
  frontend/src/pages/RunDetails.tsx
  frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
Labels: approved, area/front-end, kind/bug, lgtm, size/L

#2377 update link so that user can easily jump to CAIP after deployment
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml
Labels: approved, lgtm, size/XS

#2481 better doc for MKP-KFP deployment
  manifests/gcp_marketplace/README.md
  manifests/gcp_marketplace/cli.md
  manifests/gcp_marketplace/guide.md
Labels: approved, lgtm, size/L

#2486 Fix inverse proxy matching regex
  sdk/python/kfp/_client.py
Labels: approved, lgtm, size/XS

#2484 update base image to fix the GKE GC issue for marketplace deployment
  manifests/gcp_marketplace/deployer/Dockerfile
Labels: approved, lgtm, size/XS

#2491 [MKP] Fix metadata DB configmap
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/metadata.yaml
Labels: approved, lgtm, size/XS

#2492 Fix pipeline description 255 characters length limit
  backend/src/apiserver/client_manager.go
  backend/src/apiserver/model/pipeline.go
Labels: approved, area/back-end, kind/bug, lgtm, size/XS

#2458 clusterrole for pipeline-runner with seldondeployments
  manifests/kustomize/base/pipeline/pipeline-runner-role.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#2393 License crawler for third party golang libraries
  .gitignore
  third_party/argo/license-intermediate-data/dep.txt
  third_party/argo/license-intermediate-data/dep_repo.manual.csv
  third_party/argo/license-intermediate-data/license_info.csv
  third_party/argo/license-intermediate-data/repo.txt
  third_party/cli/README.md
  third_party/cli/concatenate_license.py
  third_party/cli/get_github_license_info.py
  third_party/cli/get_github_repo.py
  third_party/cli/parse_toml_dep.py
  third_party/cli/setup.py
  third_party/minio/license-intermediate-data/dep.txt
  third_party/minio/license-intermediate-data/dep_repo.manual.csv
  third_party/minio/license-intermediate-data/license_info.csv
  third_party/minio/license-intermediate-data/repo.txt
Labels: approved, lgtm, size/XXL

#2493 update inverse proxy custom permission setting and role setting
  manifests/gcp_marketplace/guide.md
Labels: approved, lgtm, size/S

#2494 Enlarge choose pipeline dialog to show more description
  frontend/mock-backend/fixed-data.ts
  frontend/src/components/Description.test.tsx
  frontend/src/components/Description.tsx
  frontend/src/pages/NewRun.tsx
  frontend/src/pages/PipelineDetails.tsx
  frontend/src/pages/PipelineList.tsx
  frontend/src/pages/__snapshots__/NewRun.test.tsx.snap
Labels: approved, area/front-end, lgtm, size/L

#2496 Samples - Renamed component build to container build
  samples/core/container_build/container_build.ipynb
  samples/core/container_build/requirements.txt
  test/sample-test/configs/container_build.config.yaml
  test/sample_test.yaml
Labels: approved, area/samples/notebooks, lgtm, size/XS

#2499 [Sample] Replace deprecated KubeflowRunner in TFX sample
  samples/core/tfx-oss/README.md
  samples/core/tfx-oss/TFX Example.ipynb
Labels: approved, lgtm, size/XS

#2487 [Sample] Add the run ID place holder to TFX sample, fix metadb config in preload sample as well
  samples/contrib/parameterized_tfx_oss/README.md
  samples/contrib/parameterized_tfx_oss/parameterized_tfx_oss.py
  samples/contrib/parameterized_tfx_oss/parameterized_tfx_oss.tar.gz
Labels: approved, lgtm, size/M

#2508 [UI] Fix metadata tabs loading state
  frontend/mock-backend/mock-api-server.ts
  frontend/src/lib/Apis.ts
  frontend/src/pages/ArtifactList.tsx
  frontend/src/pages/ExecutionList.tsx
Labels: approved, area/front-end, kind/bug, lgtm, size/L

#2422 [Doc] Update permission requirement in README
  manifests/gcp_marketplace/guide.md
  samples/contrib/parameterized_tfx_oss/README.md
  samples/core/xgboost_training_cm/README.md
Labels: approved, size/M

#2506 Regenerate api since https://github.com/kubeflow/pipelines/pull/2445 changed api proto
  backend/api/go_client/pipeline.pb.go
  backend/api/go_client/resource_reference.pb.go
  backend/api/go_http_client/job_model/api_resource_type.go
  backend/api/go_http_client/pipeline_model/api_pipeline.go
  backend/api/go_http_client/pipeline_model/api_resource_type.go
  backend/api/go_http_client/run_model/api_resource_type.go
  backend/api/swagger/job.swagger.json
  backend/api/swagger/kfp_api_single_file.swagger.json
  backend/api/swagger/pipeline.swagger.json
  backend/api/swagger/run.swagger.json
  backend/test/integration/pipeline_api_test.go
Labels: approved, lgtm, size/L

#2513 Pin tensorboard version to 1.13.2
  backend/src/crd/controller/viewer/reconciler/reconciler.go
  backend/src/crd/controller/viewer/reconciler/reconciler_test.go
Labels: approved, lgtm, size/S

#2511 clean up viewer crd spec
  manifests/kustomize/base/crds/viewer-crd.yaml
Labels: approved, lgtm, size/XS

#2510 remove unnecessary namespace in UI rolebinding spec
  manifests/kustomize/base/pipeline/ml-pipeline-ui-rolebinding.yaml
Labels: approved, lgtm, size/XS

#2472 Update samples/core/ai_platform pipeline to follow data dependency
  samples/core/ai_platform/ai_platform.ipynb
Labels: approved, lgtm, ok-to-test, size/S

#2519 [MKP] Reduce the logo image size.
  manifests/gcp_marketplace/guide.md
  manifests/gcp_marketplace/logo.png
Labels: lgtm, size/XS
