Repository kubeflow/pipelines, pull requests merged in 2019-08, with the labels that each got.

#1686 API - Updated swagger-codegen-cli version
  backend/api/build_kfp_server_api_python_package.sh
Labels: approved, area/api, lgtm, size/XS

#1651 Add code for python visualization service
  .travis.yml
  backend/Dockerfile.visualization
  backend/src/apiserver/visualization/.gitignore
  backend/src/apiserver/visualization/exporter.py
  backend/src/apiserver/visualization/license.sh
  backend/src/apiserver/visualization/requirements-test.txt
  backend/src/apiserver/visualization/requirements.txt
  backend/src/apiserver/visualization/roc_curve.py
  backend/src/apiserver/visualization/server.py
  backend/src/apiserver/visualization/snapshots/snap_test_exporter.py
  backend/src/apiserver/visualization/templates/basic.tpl
  backend/src/apiserver/visualization/templates/full.tpl
  backend/src/apiserver/visualization/test.py
  backend/src/apiserver/visualization/test_exporter.py
  backend/src/apiserver/visualization/test_server.py
  backend/src/apiserver/visualization/tfdv.py
  backend/src/apiserver/visualization/third_party_licenses.csv
Labels: approved, lgtm, size/XXL

#1433 Reorganize ResourceOp samples
  samples/basic/resourceop_basic.py
  samples/snapshots/README.md
  samples/snapshots/volume_snapshotop_rokurl.py
  samples/snapshots/volume_snapshotop_sequential.py
  samples/volumes/README.md
  samples/volumes/volumeop_basic.py
  samples/volumes/volumeop_dag.py
  samples/volumes/volumeop_parallel.py
  samples/volumes/volumeop_sequential.py
Labels: approved, lgtm, size/L

#1667 Adding multiple outputs into sdk with sample
  samples/notebooks/Multiple outputs - basics.ipynb
  sdk/python/kfp/compiler/_component_builder.py
  sdk/python/tests/compiler/component_builder_test.py
Labels: approved, lgtm, ok-to-test, size/L

#1699 Backend - Starting the api-server container build from scratch
  backend/Dockerfile
  backend/Dockerfile.persistenceagent
  backend/Dockerfile.scheduledworkflow
  backend/Dockerfile.viewercontroller
Labels: approved, area/back-end, area/build-release, lgtm, size/S

#1702 Allows creation of jobs without experiments
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/server/job_server.go
  backend/src/apiserver/server/job_server_test.go
Labels: approved, area/back-end, lgtm, size/L

#1523 SDK/Client - Added the create_run_from_pipeline_package method
  sdk/python/kfp/_client.py
Labels: approved, area/sdk/client, lgtm, size/M

#1725 Backend - Updated the version of the ml metadata package
  WORKSPACE
  go.mod
Labels: approved, area/back-end, lgtm, size/XS

#1671 SDK/Lightweight - Updated default image to tensorflow:1.13.2-py3
  sdk/python/kfp/components/_python_op.py
Labels: approved, area/sdk/components, lgtm, size/XS

#1483 SDK - Using Airflow ops in Pipelines
  sdk/python/kfp/components/__init__.py
  sdk/python/kfp/components/_airflow_op.py
Labels: approved, area/sdk/components, lgtm, size/L

#1668 Adding a sample for explicitly defining the execution order
  samples/basic/execution_order.py
Labels: approved, area/samples, lgtm, size/M

#1676 Container op mount secret sample
  samples/Contrib/Secret/secret.py
Labels: approved, lgtm, size/M

#1713 Support Single part PutFile
  backend/src/apiserver/client_manager.go
  backend/src/apiserver/config.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/storage/object_store.go
  backend/src/apiserver/storage/object_store_fake.go
Labels: approved, lgtm, ok-to-test, size/M

#1717 Rename InputPath -> Source for Visualization API definition
  backend/api/go_client/visualization.pb.go
  backend/api/swagger/visualization.swagger.json
  backend/api/visualization.proto
  backend/src/apiserver/server/visualization_server.go
  backend/src/apiserver/server/visualization_server_test.go
  backend/src/apiserver/visualization/roc_curve.py
  backend/src/apiserver/visualization/server.py
  backend/src/apiserver/visualization/snapshots/snap_test_exporter.py
  backend/src/apiserver/visualization/test_exporter.py
  backend/src/apiserver/visualization/test_server.py
  backend/src/apiserver/visualization/tfdv.py
  frontend/src/apis/visualization/api.ts
  frontend/src/components/viewers/VisualizationCreator.test.tsx
  frontend/src/components/viewers/VisualizationCreator.tsx
  frontend/src/components/viewers/__snapshots__/VisualizationCreator.test.tsx.snap
Labels: approved, lgtm, size/L

#1734 Moving samples to match the new folder structure
  samples/core/execution_order/execution_order.py
  samples/core/multiple_outputs/Multiple outputs - basics.ipynb
  samples/core/secret/secret.py
Labels: approved, lgtm, size/XS

#1733 fix cloudbuild failure
  backend/Dockerfile
Labels: approved, lgtm, size/XS

#1716 Add SageMaker create workteam and Ground Truth components, sample demo pipeline, other minor updates
  components/aws/sagemaker/Dockerfile
  components/aws/sagemaker/batch_transform/component.yaml
  components/aws/sagemaker/common/_utils.py
  components/aws/sagemaker/common/gt.template.yaml
  components/aws/sagemaker/common/workteam.template.yaml
  components/aws/sagemaker/deploy/component.yaml
  components/aws/sagemaker/ground_truth/README.md
  components/aws/sagemaker/ground_truth/component.yaml
  components/aws/sagemaker/ground_truth/src/ground_truth.py
  components/aws/sagemaker/hyperparameter_tuning/README.md
  components/aws/sagemaker/hyperparameter_tuning/component.yaml
  components/aws/sagemaker/hyperparameter_tuning/src/hyperparameter_tuning.py
  components/aws/sagemaker/model/component.yaml
  components/aws/sagemaker/train/component.yaml
  components/aws/sagemaker/train/src/train.py
  components/aws/sagemaker/workteam/README.md
  components/aws/sagemaker/workteam/component.yaml
  components/aws/sagemaker/workteam/src/workteam.py
  samples/contrib/aws-samples/ground_truth_pipeline_demo/README.md
  samples/contrib/aws-samples/ground_truth_pipeline_demo/mini-image-classification-pipeline.py
  samples/contrib/aws-samples/ground_truth_pipeline_demo/prep_inputs.py
Labels: approved, lgtm, ok-to-test, size/XXL

#1740 Components - Added the pymongo license URL
  components/third_party_licenses.csv
Labels: approved, area/components, lgtm, size/XS

#1718 SDK - ContainerOp.set_display_name should return self
  sdk/python/kfp/dsl/_container_op.py
Labels: approved, area/sdk, lgtm, size/XS

#1726 SDK - Lightweight - Fixed regression for components without outputs
  sdk/python/kfp/components/_python_op.py
Labels: approved, area/sdk/components, lgtm, size/XS

#1741 Refactor aws samples to match new folder structure
  components/aws/sagemaker/ground_truth/README.md
  components/aws/sagemaker/hyperparameter_tuning/README.md
  components/aws/sagemaker/workteam/README.md
  samples/contrib/aws-samples/ground_truth_pipeline_demo/README.md
  samples/contrib/aws-samples/ground_truth_pipeline_demo/mini-image-classification-pipeline.py
  samples/contrib/aws-samples/mnist-kmeans-sagemaker/kmeans-hpo-pipeline.py
  samples/contrib/aws-samples/mnist-kmeans-sagemaker/mnist-classification-pipeline.py
Labels: approved, lgtm, ok-to-test, size/M

#1712 Fixes cloning of recurring runs
  frontend/src/components/NewRunParameters.test.tsx
  frontend/src/components/NewRunParameters.tsx
  frontend/src/components/Router.tsx
  frontend/src/components/__snapshots__/NewRunParameters.test.tsx.snap
  frontend/src/lib/Buttons.ts
  frontend/src/lib/RunUtils.ts
  frontend/src/pages/NewRun.test.tsx
  frontend/src/pages/NewRun.tsx
  frontend/src/pages/RecurringRunDetails.test.tsx
  frontend/src/pages/RecurringRunDetails.tsx
  frontend/src/pages/__snapshots__/NewRun.test.tsx.snap
Labels: approved, area/front-end, kind/bug, lgtm, size/XXL

#1747 Revert "Backend - Updated the version of the ml metadata package"
  WORKSPACE
  go.mod
Labels: approved, area/back-end, lgtm, size/XS

#1742 Revert "Backend - Starting the api-server container build from scratch"
  backend/Dockerfile
  backend/Dockerfile.persistenceagent
  backend/Dockerfile.scheduledworkflow
  backend/Dockerfile.viewercontroller
Labels: approved, area/back-end, area/build-release, lgtm, size/S

#1720 Add API to rerun the pipeline
  backend/api/go_client/run.pb.go
  backend/api/go_client/run.pb.gw.go
  backend/api/go_http_client/run_client/run_service/BUILD.bazel
  backend/api/go_http_client/run_client/run_service/retry_run_parameters.go
  backend/api/go_http_client/run_client/run_service/retry_run_responses.go
  backend/api/go_http_client/run_client/run_service/run_service_client.go
  backend/api/run.proto
  backend/api/swagger/kfp_api_single_file.swagger.json
  backend/api/swagger/run.swagger.json
  backend/src/agent/persistence/worker/metrics_reporter.go
  backend/src/agent/persistence/worker/metrics_reporter_test.go
  backend/src/apiserver/BUILD.bazel
  backend/src/apiserver/client/BUILD.bazel
  backend/src/apiserver/client/pod.go
  backend/src/apiserver/client_manager.go
  backend/src/apiserver/resource/BUILD.bazel
  backend/src/apiserver/resource/client_manager_fake.go
  backend/src/apiserver/resource/model_converter.go
  backend/src/apiserver/resource/model_converter_test.go
  backend/src/apiserver/resource/pod_fake.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/resource/resource_manager_util.go
  backend/src/apiserver/resource/resource_manager_util_test.go
  backend/src/apiserver/resource/workflow_fake.go
  backend/src/apiserver/server/run_server.go
  backend/src/apiserver/server/run_server_test.go
  backend/src/apiserver/server/util.go
  backend/src/apiserver/server/util_test.go
  backend/src/common/util/uuid.go
  backend/src/common/util/workflow.go
  backend/src/common/util/workflow_test.go
  backend/src/crd/controller/scheduledworkflow/controller.go
  backend/src/crd/controller/scheduledworkflow/util/scheduled_workflow.go
  backend/src/crd/controller/scheduledworkflow/util/scheduled_workflow_test.go
  manifests/kustomize/base/pipeline/ml-pipeline-apiserver-role.yaml
Labels: approved, lgtm, size/XXL

#1736 Delete KFP component before reinstalling again
  test/deploy-pipeline.sh
Labels: approved, lgtm, size/XS

#1759 Move samples to the correct location
  samples/contrib/ai-platform/__init__.py
  samples/contrib/volume_ops/volumeop_dag.py
  samples/contrib/volume_ops/volumeop_parallel.py
  samples/contrib/volume_ops/volumeop_sequential.py
  samples/contrib/volume_snapshot_ops/volume_snapshotop_rokurl.py
  samples/core/ai-platform/Chicago Crime Pipeline.ipynb
  samples/core/ai-platform/README.md
  samples/core/ai-platform/images/chicago_crime_pipeline.png
  samples/core/ai-platform/images/chicago_crime_predictions.png
  samples/core/ai-platform/local/Chicago Crime Research.ipynb
  samples/core/ai-platform/training/.gitignore
  samples/core/ai-platform/training/.python-version
  samples/core/ai-platform/training/requirements.txt
  samples/core/ai-platform/training/setup.py
  samples/core/ai-platform/training/trainer/model.py
  samples/core/ai-platform/training/trainer/task.py
  samples/core/ai-platform/training/trainer/util.py
  samples/core/artifact_location/artifact_location.py
  samples/core/volume_ops/volumeop.py
  samples/core/volume_snapshot_ops/volume_snapshot_op.py
Labels: approved, lgtm, size/XS

#1737 Update Watson Machine Learning auth with IAM
  components/ibm-components/spark/store_spark_model/src/store_spark_model.py
  components/ibm-components/watson/deploy/src/wml-deploy.py
  components/ibm-components/watson/manage/subscribe/src/subscribe.py
  components/ibm-components/watson/store/src/wml-store.py
  components/ibm-components/watson/train/src/wml-train.py
  samples/contrib/ibm-samples/openscale/README.md
  samples/contrib/ibm-samples/openscale/credentials/creds.ini
  samples/contrib/ibm-samples/watson/README.md
  samples/contrib/ibm-samples/watson/credentials/creds.ini
Labels: approved, lgtm, needs-ok-to-test, size/M

#1681 Basic component build sample
  samples/core/component_build/component_build.ipynb
Labels: approved, lgtm, size/L

#1764 remove copying the samples since we are not releasing the samples in the GCS
  .cloudbuild.yaml
  .release.cloudbuild.yaml
Labels: approved, lgtm, size/S

#1738 Add Visualization Server to Cloud Build yaml Files
  .cloudbuild.yaml
  .release.cloudbuild.yaml
  backend/src/apiserver/visualization/third_party_licenses.csv
Labels: approved, lgtm, size/S

#1769 fix api server sort test
  backend/test/integration/job_api_test.go
  backend/test/integration/run_api_test.go
Labels: approved, lgtm, size/S

#1765 Not return error if run update doesn't change DB entry
  backend/src/apiserver/storage/run_store.go
Labels: approved, lgtm, size/M

#1749 Add preemtptible gpu sample
  samples/core/preemptible_tpu_gpu/preemptible_tpu_gpu.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/preemptible_tpu_gpu.yaml
Labels: approved, lgtm, size/L

#1760 Backend - Docker build should fail on sample compilation failures
  backend/Dockerfile
Labels: approved, area/build-release, lgtm, size/XS

#1767 Move imagepullsecrets sample to samples/core
  samples/core/imagepullsecrets/imagepullsecrets.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/imagepullsecrets.yaml
Labels: approved, lgtm, size/S

#1783 Fixed Dockerfile used for buildVisualizationServer in Cloud Build
  backend/Dockerfile.visualization
Labels: approved, lgtm, size/XS

#1787 Remove yebrahim from approvers/reviewers
  frontend/OWNERS
  test/frontend-integration-test/OWNERS
  third_party/OWNERS
Labels: do-not-merge/invalid-owners-file, lgtm, size/XS

#1730 Refactor sample tests configuration to reduce the efforts of adding samples.
  samples/core/kubeflow_training_classification/README.md
  samples/core/kubeflow_training_classification/kubeflow_training_classification.py
  samples/core/tfx_cab_classification/README.md
  samples/core/tfx_cab_classification/taxi-cab-classification/column-names.json
  samples/core/tfx_cab_classification/taxi-cab-classification/eval.csv
  samples/core/tfx_cab_classification/taxi-cab-classification/preprocessing.py
  samples/core/tfx_cab_classification/taxi-cab-classification/schema.json
  samples/core/tfx_cab_classification/taxi-cab-classification/train.csv
  samples/core/tfx_cab_classification/tfx_cab_classification.py
  samples/core/xgboost_training_cm/README.md
  samples/core/xgboost_training_cm/xgboost_training_cm.py
  test/component_test.yaml
  test/e2e_test_gke_v2.yaml
  test/sample-test/check_notebook_results.py
  test/sample-test/clean_cmle_models.py
  test/sample-test/run_basic_test.py
  test/sample-test/run_kubeflow_test.py
  test/sample-test/run_sample_test.py
  test/sample-test/run_test.sh
  test/sample-test/run_tfx_test.py
  test/sample-test/run_xgboost_test.py
  test/sample_test.yaml
Labels: approved, lgtm, size/XXL

#1774 Container builder
  sdk/python/kfp/compiler/_container_builder.py
  sdk/python/kfp/compiler/_k8s_helper.py
  sdk/python/tests/compiler/testdata/kaniko.basic.yaml
Labels: approved, lgtm, size/S

#1778 Update images, bug fixes, clean up code
  components/aws/sagemaker/batch_transform/component.yaml
  components/aws/sagemaker/batch_transform/src/batch_transform.py
  components/aws/sagemaker/common/_utils.py
  components/aws/sagemaker/deploy/component.yaml
  components/aws/sagemaker/deploy/src/deploy.py
  components/aws/sagemaker/ground_truth/component.yaml
  components/aws/sagemaker/ground_truth/src/ground_truth.py
  components/aws/sagemaker/hyperparameter_tuning/component.yaml
  components/aws/sagemaker/hyperparameter_tuning/src/hyperparameter_tuning.py
  components/aws/sagemaker/model/component.yaml
  components/aws/sagemaker/model/src/create_model.py
  components/aws/sagemaker/train/component.yaml
  components/aws/sagemaker/train/src/train.py
  components/aws/sagemaker/workteam/component.yaml
  components/aws/sagemaker/workteam/src/workteam.py
  samples/contrib/aws-samples/ground_truth_pipeline_demo/mini-image-classification-pipeline.py
  samples/contrib/aws-samples/ground_truth_pipeline_demo/prep_inputs.py
  samples/contrib/aws-samples/titanic-survival-prediction/titanic-survival-prediction.py
Labels: approved, lgtm, ok-to-test, size/M

#1768 SDK - Containers - Returning image name with digest
  sdk/python/kfp/compiler/_component_builder.py
  sdk/python/kfp/compiler/_container_builder.py
  sdk/python/kfp/compiler/_k8s_helper.py
  sdk/python/tests/compiler/testdata/kaniko.basic.yaml
Labels: approved, lgtm, sdk/containers, size/M

#1795 ContainerBuilder loading kube config
  sdk/python/kfp/compiler/_container_builder.py
  sdk/python/kfp/compiler/_gcs_helper.py
  sdk/python/kfp/compiler/_k8s_helper.py
  sdk/python/tests/compiler/container_builder_test.py
Labels: approved, lgtm, size/M

#1788 skip storing log to files
  backend/Dockerfile
  backend/Dockerfile.persistenceagent
  backend/Dockerfile.scheduledworkflow
  backend/Dockerfile.viewercontroller
Labels: approved, lgtm, size/XS

#1805 Fix the broken sample path in API
  backend/src/apiserver/config/sample_config.json
Labels: approved, lgtm, size/XS

#1798 Fix github security alert.
  frontend/server/package-lock.json
  frontend/server/package.json
  test/frontend-integration-test/package-lock.json
  test/frontend-integration-test/package.json
Labels: approved, lgtm, size/XXL

#1696 SDK - Lightweight - Added support for complex default values
  sdk/python/kfp/components/_components.py
  sdk/python/kfp/components/_python_op.py
  sdk/python/tests/components/test_python_op.py
Labels: approved, area/sdk/components, lgtm, size/M

#1809 Disable flaky tests temporarily
  backend/test/integration/run_api_test.go
Labels: approved, lgtm, size/XS

#1789 fix sample reference link
  components/gcp/dataproc/delete_cluster/README.md
  components/gcp/dataproc/delete_cluster/sample.ipynb
Labels: approved, lgtm, size/S

#1793 Move TF installation to notebooks
  samples/core/kubeflow_pipeline_using_TFX_OSS_components/KubeFlow Pipeline Using TFX OSS Components.ipynb
  samples/core/lightweight_component/Lightweight Python components - basics.ipynb
  test/sample-test/run_test.sh
Labels: approved, lgtm, size/S

#1812 Refactors toolbar buttons to use a map rather than an array
  frontend/src/TestUtils.tsx
  frontend/src/components/Toolbar.test.tsx
  frontend/src/components/Toolbar.tsx
  frontend/src/components/__snapshots__/Toolbar.test.tsx.snap
  frontend/src/lib/Buttons.ts
  frontend/src/pages/404.tsx
  frontend/src/pages/AllRunsList.test.tsx
  frontend/src/pages/AllRunsList.tsx
  frontend/src/pages/Archive.test.tsx
  frontend/src/pages/Archive.tsx
  frontend/src/pages/Compare.test.tsx
  frontend/src/pages/Compare.tsx
  frontend/src/pages/ExperimentDetails.test.tsx
  frontend/src/pages/ExperimentDetails.tsx
  frontend/src/pages/ExperimentList.test.tsx
  frontend/src/pages/ExperimentList.tsx
  frontend/src/pages/ExperimentsAndRuns.tsx
  frontend/src/pages/NewExperiment.test.tsx
  frontend/src/pages/NewExperiment.tsx
  frontend/src/pages/NewRun.test.tsx
  frontend/src/pages/NewRun.tsx
  frontend/src/pages/PipelineDetails.test.tsx
  frontend/src/pages/PipelineDetails.tsx
  frontend/src/pages/PipelineList.test.tsx
  frontend/src/pages/PipelineList.tsx
  frontend/src/pages/RecurringRunDetails.test.tsx
  frontend/src/pages/RecurringRunDetails.tsx
  frontend/src/pages/RecurringRunsManager.tsx
  frontend/src/pages/ResourceSelector.tsx
  frontend/src/pages/RunDetails.test.tsx
  frontend/src/pages/RunDetails.tsx
  frontend/src/pages/__snapshots__/AllRunsList.test.tsx.snap
  frontend/src/pages/__snapshots__/Archive.test.tsx.snap
  frontend/src/pages/__snapshots__/Compare.test.tsx.snap
  frontend/src/pages/__snapshots__/ExperimentDetails.test.tsx.snap
  frontend/src/pages/__snapshots__/NewRun.test.tsx.snap
  frontend/src/pages/__snapshots__/RecurringRunsManager.test.tsx.snap
  frontend/src/pages/__snapshots__/ResourceSelector.test.tsx.snap
Labels: approved, area/front-end, lgtm, size/XXL

#1807 Fix test loophole for loading samples during KFP startup
  test/deploy-pipeline.sh
Labels: approved, lgtm, size/S

#1802 Garbage collect the completed workflow after persisted to database
  backend/Dockerfile.persistenceagent
  backend/src/agent/persistence/main.go
  backend/src/agent/persistence/persistence_agent.go
  backend/src/agent/persistence/worker/persistence_worker_test.go
  backend/src/agent/persistence/worker/workflow_saver.go
  backend/src/agent/persistence/worker/workflow_saver_test.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/resource/resource_manager_util.go
  backend/src/apiserver/resource/workflow_fake.go
  backend/src/apiserver/server/report_server_test.go
  backend/src/common/util/consts.go
  backend/src/common/util/workflow.go
Labels: approved, lgtm, size/L

#1819 Update npm test to not use coverall
  .travis.yml
Labels: approved, lgtm, size/XS

#1781 add reference name to resource reference API proto
  backend/api/go_client/resource_reference.pb.go
  backend/api/go_http_client/job_model/api_resource_reference.go
  backend/api/go_http_client/run_model/api_resource_reference.go
  backend/api/resource_reference.proto
  backend/api/swagger/job.swagger.json
  backend/api/swagger/kfp_api_single_file.swagger.json
  backend/api/swagger/run.swagger.json
  backend/src/apiserver/model/experiment.go
  backend/src/apiserver/model/resource_reference.go
  backend/src/apiserver/resource/model_converter.go
  backend/src/apiserver/resource/model_converter_test.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/server/api_converter.go
  backend/src/apiserver/server/api_converter_test.go
  backend/src/apiserver/server/run_server_test.go
  backend/src/apiserver/storage/job_store_test.go
  backend/src/apiserver/storage/resource_reference_store.go
  backend/src/apiserver/storage/resource_reference_store_test.go
  backend/src/apiserver/storage/run_store_test.go
  backend/test/integration/job_api_test.go
  backend/test/integration/run_api_test.go
  sdk/python/setup.py
Labels: approved, lgtm, size/XL

#1657 SDK - Removed the build_image parameter from build_python_component function
  sdk/python/kfp/compiler/_component_builder.py
Labels: approved, area/sdk/components/python_container_op, lgtm, size/M

#1719 Remove outdated argo install instruction
  test/README.md
Labels: approved, lgtm, size/XS

#1785 update owner files in samples and test
  samples/OWNERS
  test/OWNERS
  test/sample-test/OWNERS
Labels: approved, lgtm, size/S

#1792 Move argo installation to dockerfile from bash script.
  test/sample-test/Dockerfile
  test/sample-test/run_test.sh
Labels: approved, lgtm, size/S

#1816 Build - Fix CloudBuild bug
  .cloudbuild.yaml
Labels: approved, area/build-release, kind/bug, lgtm, size/XS

#1836 Create composite indexes [ResourceType, ReferenceUUID, ReferenceType]
  backend/src/apiserver/model/resource_reference.go
Labels: approved, lgtm, size/XS

#1806 Container builder default gcr
  sdk/python/kfp/compiler/_component_builder.py
  sdk/python/kfp/compiler/_container_builder.py
Labels: approved, lgtm, size/M

#1835 Improve sql efficiency for getting the run
  backend/src/apiserver/storage/run_store.go
Labels: approved, lgtm, size/XS

#1828 Update for sample repo restructuring
  samples/contrib/image-captioning-gcp/README.md
Labels: approved, lgtm, ok-to-test, size/S

#1817 Add subprocess pip install example in lightweight component example notebook
  samples/core/lightweight_component/Lightweight Python components - basics.ipynb
Labels: approved, lgtm, size/S

#1842 Propagate pipeline name in pipeline spec
  backend/api/go_client/pipeline_spec.pb.go
  backend/api/go_http_client/job_model/api_pipeline_spec.go
  backend/api/go_http_client/run_model/api_pipeline_spec.go
  backend/api/pipeline_spec.proto
  backend/api/swagger/job.swagger.json
  backend/api/swagger/kfp_api_single_file.swagger.json
  backend/api/swagger/run.swagger.json
  backend/src/apiserver/model/pipeline_spec.go
  backend/src/apiserver/resource/model_converter.go
  backend/src/apiserver/resource/model_converter_test.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/resource/resource_manager_util.go
  backend/src/apiserver/server/api_converter.go
  backend/src/apiserver/server/api_converter_test.go
  backend/src/apiserver/storage/job_store.go
  backend/src/apiserver/storage/job_store_test.go
  backend/src/apiserver/storage/run_store.go
  backend/test/integration/job_api_test.go
  backend/test/integration/run_api_test.go
Labels: approved, lgtm, size/L

#1782 Add retry button in Pipeline UI
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  frontend/src/apis/experiment/api.ts
  frontend/src/apis/filter/api.ts
  frontend/src/apis/job/api.ts
  frontend/src/apis/pipeline/api.ts
  frontend/src/apis/run/api.ts
  frontend/src/lib/Buttons.ts
  frontend/src/lib/WorkflowParser.ts
  frontend/src/pages/RunDetails.tsx
Labels: approved, lgtm, size/L

#1852 Reduce getPipeline calls in RunList
  frontend/mock-backend/fixed-data.ts
  frontend/src/apis/job/api.ts
  frontend/src/apis/run/api.ts
  frontend/src/lib/RunUtils.ts
  frontend/src/pages/ExperimentDetails.tsx
  frontend/src/pages/NewRun.tsx
  frontend/src/pages/PipelineDetails.tsx
  frontend/src/pages/RunList.test.tsx
  frontend/src/pages/RunList.tsx
  frontend/src/pages/__snapshots__/RunList.test.tsx.snap
Labels: approved, area/front-end, lgtm, size/L

#1849 Add back coveralls.
  .travis.yml
Labels: approved, lgtm, size/XS

#1754 Change how Variables are Provided to Visualizations
  backend/src/apiserver/visualization/exporter.py
  backend/src/apiserver/visualization/roc_curve.py
  backend/src/apiserver/visualization/server.py
  backend/src/apiserver/visualization/snapshots/snap_test_exporter.py
  backend/src/apiserver/visualization/test_exporter.py
  backend/src/apiserver/visualization/test_server.py
Labels: approved, lgtm, size/L

#1381 SDK - Preserving the pipeline input information in the compiled Workflow
  sdk/python/kfp/compiler/compiler.py
  sdk/python/tests/compiler/testdata/add_pod_env.yaml
  sdk/python/tests/compiler/testdata/artifact_location.yaml
  sdk/python/tests/compiler/testdata/basic.yaml
  sdk/python/tests/compiler/testdata/coin.yaml
  sdk/python/tests/compiler/testdata/compose.yaml
  sdk/python/tests/compiler/testdata/default_value.yaml
  sdk/python/tests/compiler/testdata/imagepullsecrets.yaml
  sdk/python/tests/compiler/testdata/param_op_transform.yaml
  sdk/python/tests/compiler/testdata/param_substitutions.yaml
  sdk/python/tests/compiler/testdata/pipelineparams.yaml
  sdk/python/tests/compiler/testdata/preemptible_tpu_gpu.yaml
  sdk/python/tests/compiler/testdata/recursive_do_while.yaml
  sdk/python/tests/compiler/testdata/recursive_while.yaml
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
  sdk/python/tests/compiler/testdata/retry.yaml
  sdk/python/tests/compiler/testdata/sidecar.yaml
  sdk/python/tests/compiler/testdata/timeout.yaml
  sdk/python/tests/compiler/testdata/volume.yaml
  sdk/python/tests/compiler/testdata/volume_snapshotop_rokurl.yaml
  sdk/python/tests/compiler/testdata/volume_snapshotop_sequential.yaml
  sdk/python/tests/compiler/testdata/volumeop_basic.yaml
  sdk/python/tests/compiler/testdata/volumeop_dag.yaml
  sdk/python/tests/compiler/testdata/volumeop_parallel.yaml
  sdk/python/tests/compiler/testdata/volumeop_sequential.yaml
Labels: approved, area/sdk, lgtm, size/M

#1827 Fix run duration bug
  frontend/mock-backend/fixed-data.ts
  frontend/src/lib/Utils.test.ts
  frontend/src/lib/Utils.ts
  frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
Labels: approved, area/front-end, kind/bug, lgtm, size/M

#1469 SDK - Cleanup - Serialized PipelineParamTuple does not need value or type
  sdk/python/kfp/dsl/_pipeline_param.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/dsl/pipeline_param_tests.py
Labels: approved, area/sdk, lgtm, size/M

#1830 Adding a sample for serving component
  samples/core/model_serving_component/model_serving_component.ipynb
Labels: approved, lgtm, size/L

#1405 Seldon examples
  samples/contrib/seldon/README.md
  samples/contrib/seldon/iris_storagebucket.py
  samples/contrib/seldon/mabdeploy_seldon.py
  samples/contrib/seldon/mnist_tf.py
  samples/contrib/seldon/mnist_tf_volume.py
Labels: approved, lgtm, ok-to-test, size/XL

#1863 update gcloud ml-engine to ai-platform
  components/gcp/container/component_sdk/python/kfp_component/google/ml_engine/_create_version.py
  samples/core/kubeflow_pipeline_using_TFX_OSS_components/KubeFlow Pipeline Using TFX OSS Components.ipynb
Labels: approved, lgtm, size/S

#1859 Release 0517114dc2b365a4a6d95424af6157ead774eff3
  components/dataflow/predict/component.yaml
  components/dataflow/tfdv/component.yaml
  components/dataflow/tfma/component.yaml
  components/dataflow/tft/component.yaml
  components/gcp/bigquery/query/README.md
  components/gcp/bigquery/query/component.yaml
  components/gcp/bigquery/query/sample.ipynb
  components/gcp/dataflow/launch_python/README.md
  components/gcp/dataflow/launch_python/component.yaml
  components/gcp/dataflow/launch_python/sample.ipynb
  components/gcp/dataflow/launch_template/README.md
  components/gcp/dataflow/launch_template/component.yaml
  components/gcp/dataflow/launch_template/sample.ipynb
  components/gcp/dataproc/create_cluster/README.md
  components/gcp/dataproc/create_cluster/component.yaml
  components/gcp/dataproc/create_cluster/sample.ipynb
  components/gcp/dataproc/delete_cluster/README.md
  components/gcp/dataproc/delete_cluster/component.yaml
  components/gcp/dataproc/delete_cluster/sample.ipynb
  components/gcp/dataproc/submit_hadoop_job/README.md
  components/gcp/dataproc/submit_hadoop_job/component.yaml
  components/gcp/dataproc/submit_hadoop_job/sample.ipynb
  components/gcp/dataproc/submit_hive_job/README.md
  components/gcp/dataproc/submit_hive_job/component.yaml
  components/gcp/dataproc/submit_hive_job/sample.ipynb
  components/gcp/dataproc/submit_pig_job/README.md
  components/gcp/dataproc/submit_pig_job/component.yaml
  components/gcp/dataproc/submit_pig_job/sample.ipynb
  components/gcp/dataproc/submit_pyspark_job/README.md
  components/gcp/dataproc/submit_pyspark_job/component.yaml
  components/gcp/dataproc/submit_pyspark_job/sample.ipynb
  components/gcp/dataproc/submit_spark_job/README.md
  components/gcp/dataproc/submit_spark_job/component.yaml
  components/gcp/dataproc/submit_spark_job/sample.ipynb
  components/gcp/dataproc/submit_sparksql_job/README.md
  components/gcp/dataproc/submit_sparksql_job/component.yaml
  components/gcp/dataproc/submit_sparksql_job/sample.ipynb
  components/gcp/ml_engine/batch_predict/README.md
  components/gcp/ml_engine/batch_predict/component.yaml
  components/gcp/ml_engine/batch_predict/sample.ipynb
  components/gcp/ml_engine/deploy/README.md
  components/gcp/ml_engine/deploy/component.yaml
  components/gcp/ml_engine/deploy/sample.ipynb
  components/gcp/ml_engine/train/README.md
  components/gcp/ml_engine/train/component.yaml
  components/gcp/ml_engine/train/sample.ipynb
  components/kubeflow/deployer/component.yaml
  components/kubeflow/dnntrainer/component.yaml
  components/kubeflow/launcher/kubeflow_tfjob_launcher_op.py
  components/kubeflow/launcher/src/train.template.yaml
  components/local/confusion_matrix/component.yaml
  components/local/roc/component.yaml
  samples/contrib/resnet-cmle/resnet-train-pipeline.py
  samples/core/ai-platform/Chicago Crime Pipeline.ipynb
  samples/core/kubeflow_pipeline_using_TFX_OSS_components/KubeFlow Pipeline Using TFX OSS Components.ipynb
  samples/core/kubeflow_training_classification/kubeflow_training_classification.py
  samples/core/tfx_cab_classification/tfx_cab_classification.py
  samples/core/xgboost_training_cm/xgboost_training_cm.py
Labels: approved, lgtm, size/L

#1860 Update Python SDK versions for release.
  components/gcp/container/component_sdk/python/setup.py
  sdk/python/setup.py
Labels: approved, lgtm, size/M

#1866 add compile step in the samples to generate zip files
  samples/core/ai-platform/Chicago Crime Pipeline.ipynb
  samples/core/artifact_location/artifact_location.py
  samples/core/condition/condition.py
  samples/core/dsl_static_type_checking/DSL Static Type Checking.ipynb
  samples/core/imagepullsecrets/imagepullsecrets.py
  samples/core/kubeflow_tf_serving/kubeflow_tf_serving.ipynb
  samples/core/recursion/recursion.py
  samples/core/resource_ops/resourceop_basic.py
  samples/core/sidecar/sidecar.py
  samples/core/volume_ops/volumeop.py
  samples/core/volume_snapshot_ops/volume_snapshot_op.py
  samples/core/xgboost_training_cm/README.md
Labels: approved, lgtm, size/M

#1871 Remove copying of tfx data for cloudbuild release steps.
  .release.cloudbuild.yaml
Labels: approved, lgtm, size/XS

#1756 SDK - Fixed string comparisons
  sdk/python/kfp/compiler/_component_builder.py
Labels: approved, area/sdk, lgtm, size/XS

#1872 Update changelog for 0.1.26
  CHANGELOG.md
Labels: approved, lgtm, size/M

#1843 SDK - Tests - Improved the "ContainerOp.set_retry" test
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/retry.py
  sdk/python/tests/compiler/testdata/retry.yaml
Labels: approved, area/sdk/dsl/compiler, area/testing, lgtm, size/L

#1870 Update manifests to point to 0.26 release.
  manifests/kustomize/base/kustomization.yaml
  manifests/kustomize/namespaced-install.yaml
Labels: approved, lgtm, size/M

#1732 Refactor presubmit-tests-with-pipeline-deployment.sh to run in other projects
  test/README.md
  test/build_image.yaml
  test/component_test.yaml
  test/deploy-kubeflow.sh
  test/e2e_test_gke_v2.yaml
  test/presubmit-tests-with-pipeline-deployment.sh
  test/sample_test.yaml
  test/test-prep.sh
Labels: approved, lgtm, size/M

#1857 test/project-cleanup: Support to cleanup gke-clusters in test project
  go.mod
  go.sum
  test/tools/project-cleaner/main.go
  test/tools/project-cleaner/project_cleaner.sh
  test/tools/project-cleaner/resource_spec.yaml
Labels: approved, lgtm, ok-to-test, size/L

#1751 'core' folder included to parameters related On-Premise cluster
  samples/core/tfx_cab_classification/README.md
Labels: approved, lgtm, ok-to-test, size/S

#1714 Let backend apiserver mysql dbname configurable
  backend/src/apiserver/client_manager.go
  backend/src/apiserver/config/config.json
  go.mod
  go.sum
Labels: approved, lgtm, ok-to-test, size/S

#1384 gcp cred bug fix for multiple credentials in single pipeline
  sdk/python/kfp/gcp.py
Labels: approved, lgtm, ok-to-test, size/S

#1892 fix unit tests and address some comments
  sdk/python/kfp/compiler/_container_builder.py
  sdk/python/tests/compiler/container_builder_test.py
Labels: approved, lgtm, size/XS

#1877 IBM Watson samples: from six.moves import xrange
  samples/contrib/ibm-samples/watson/source/model-source-code/tf-model/input_data.py
Labels: approved, lgtm, ok-to-test, size/XS

#1893 Use single part as default
  backend/src/apiserver/client_manager.go
Labels: approved, lgtm, size/XS

#1808 Use KFP lite deployment for presubmit tests
  test/.gitignore
  test/README.md
  test/build-images.sh
  test/check-argo-status.sh
  test/deploy-cluster.sh
  test/deploy-pipeline-lite.sh
  test/install-argo.sh
  test/manifests/kustomization.yaml
  test/presubmit-tests-with-pipeline-deployment.sh
Labels: approved, lgtm, size/L

#1855 Created extensible code editor based on react-ace
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Editor.test.tsx
  frontend/src/components/Editor.tsx
  frontend/src/components/__snapshots__/Editor.test.tsx.snap
Labels: approved, lgtm, size/L

#1876 Undefined name 'e' in openvino
  contrib/components/openvino/ovms-deployer/containers/evaluate.py
Labels: approved, lgtm, ok-to-test, size/XS

#1902 remove kubeflow training to favor tfx components
  samples/core/kubeflow_training_classification/README.md
  samples/core/kubeflow_training_classification/kubeflow_training_classification.py
  test/sample-test/run_sample_test.py
  test/sample-test/run_test.sh
  test/sample_test.yaml
Labels: approved, lgtm, size/L

#1908 remove tfx notebook sample in favor of the TFX OSS sample
  samples/core/kubeflow_pipeline_using_TFX_OSS_components/KubeFlow Pipeline Using TFX OSS Components.ipynb
  test/sample-test/run_test.sh
  test/sample_test.yaml
Labels: approved, lgtm, size/XL

#1909 Enable error propagation from nbconvert to frontend
  backend/src/apiserver/visualization/exporter.py
Labels: approved, lgtm, size/XS

#1905 Change the type of resource reference payload column
  backend/src/apiserver/client_manager.go
Labels: approved, lgtm, size/XS

#1887 Simplified the build_docker_image function
  sdk/python/kfp/compiler/_component_builder.py
Labels: approved, area/sdk/component_build, lgtm, size/M

#1904 apiserver: Remove TFX output artifact recording to metadatastore
  BUILD.bazel
  WORKSPACE
  backend/src/apiserver/BUILD.bazel
  backend/src/apiserver/client_manager.go
  backend/src/apiserver/main.go
  backend/src/apiserver/metadata/BUILD.bazel
  backend/src/apiserver/metadata/metadata_store.go
  backend/src/apiserver/metadata/metadata_store_test.go
  backend/src/apiserver/resource/BUILD.bazel
  backend/src/apiserver/resource/client_manager_fake.go
  backend/src/apiserver/storage/BUILD.bazel
  backend/src/apiserver/storage/run_store.go
  backend/src/apiserver/storage/run_store_test.go
  go.mod
  go.sum
Labels: approved, lgtm, ok-to-test, size/XL

#1721 Lint Python code for undefined names
  .travis.yml
  backend/src/apiserver/visualization/roc_curve.py
  backend/src/apiserver/visualization/snapshots/snap_test_exporter.py
  backend/src/apiserver/visualization/test_exporter.py
  backend/src/apiserver/visualization/tfdv.py
  components/arena/python/arena/_arena_distributed_tf_op.py
  components/aws/emr/create_cluster/src/create_cluster.py
  components/aws/emr/submit_pyspark_job/src/submit_pyspark_job.py
  components/aws/emr/submit_spark_job/src/submit_spark_job.py
  components/aws/sagemaker/batch_transform/src/batch_transform.py
  proxy/get_proxy_url.py
  samples/contrib/aws-samples/ground_truth_pipeline_demo/mini-image-classification-pipeline.py
  samples/contrib/resnet-cmle/resnet-train-pipeline.py
  sdk/python/kfp/components/_dynamic.py
  sdk/python/kfp/dsl/_pipeline.py
  sdk/python/tests/dsl/component_tests.py
Labels: approved, lgtm, ok-to-test, size/L

#1916 Release 151c5349f13bea9d626c988563c04c0a86210c21
  components/dataflow/predict/component.yaml
  components/dataflow/tfdv/component.yaml
  components/dataflow/tfma/component.yaml
  components/dataflow/tft/component.yaml
  components/gcp/bigquery/query/README.md
  components/gcp/bigquery/query/component.yaml
  components/gcp/bigquery/query/sample.ipynb
  components/gcp/container/component_sdk/python/setup.py
  components/gcp/dataflow/launch_python/README.md
  components/gcp/dataflow/launch_python/component.yaml
  components/gcp/dataflow/launch_python/sample.ipynb
  components/gcp/dataflow/launch_template/README.md
  components/gcp/dataflow/launch_template/component.yaml
  components/gcp/dataflow/launch_template/sample.ipynb
  components/gcp/dataproc/create_cluster/README.md
  components/gcp/dataproc/create_cluster/component.yaml
  components/gcp/dataproc/create_cluster/sample.ipynb
  components/gcp/dataproc/delete_cluster/README.md
  components/gcp/dataproc/delete_cluster/component.yaml
  components/gcp/dataproc/delete_cluster/sample.ipynb
  components/gcp/dataproc/submit_hadoop_job/README.md
  components/gcp/dataproc/submit_hadoop_job/component.yaml
  components/gcp/dataproc/submit_hadoop_job/sample.ipynb
  components/gcp/dataproc/submit_hive_job/README.md
  components/gcp/dataproc/submit_hive_job/component.yaml
  components/gcp/dataproc/submit_hive_job/sample.ipynb
  components/gcp/dataproc/submit_pig_job/README.md
  components/gcp/dataproc/submit_pig_job/component.yaml
  components/gcp/dataproc/submit_pig_job/sample.ipynb
  components/gcp/dataproc/submit_pyspark_job/README.md
  components/gcp/dataproc/submit_pyspark_job/component.yaml
  components/gcp/dataproc/submit_pyspark_job/sample.ipynb
  components/gcp/dataproc/submit_spark_job/README.md
  components/gcp/dataproc/submit_spark_job/component.yaml
  components/gcp/dataproc/submit_spark_job/sample.ipynb
  components/gcp/dataproc/submit_sparksql_job/README.md
  components/gcp/dataproc/submit_sparksql_job/component.yaml
  components/gcp/dataproc/submit_sparksql_job/sample.ipynb
  components/gcp/ml_engine/batch_predict/README.md
  components/gcp/ml_engine/batch_predict/component.yaml
  components/gcp/ml_engine/batch_predict/sample.ipynb
  components/gcp/ml_engine/deploy/README.md
  components/gcp/ml_engine/deploy/component.yaml
  components/gcp/ml_engine/deploy/sample.ipynb
  components/gcp/ml_engine/train/README.md
  components/gcp/ml_engine/train/component.yaml
  components/gcp/ml_engine/train/sample.ipynb
  components/kubeflow/deployer/component.yaml
  components/kubeflow/dnntrainer/component.yaml
  components/kubeflow/launcher/kubeflow_tfjob_launcher_op.py
  components/kubeflow/launcher/src/train.template.yaml
  components/local/confusion_matrix/component.yaml
  components/local/roc/component.yaml
  samples/contrib/resnet-cmle/resnet-train-pipeline.py
  samples/core/ai-platform/Chicago Crime Pipeline.ipynb
  samples/core/kubeflow_tf_serving/kubeflow_tf_serving.ipynb
  samples/core/tfx_cab_classification/tfx_cab_classification.py
  samples/core/xgboost_training_cm/xgboost_training_cm.py
  sdk/python/setup.py
Labels: approved, lgtm, size/L

#1911 SDK - Airflow - Fixed bug in AirFlow op creation
  sdk/python/kfp/components/_airflow_op.py
Labels: approved, area/sdk/components, kind/bug, lgtm, priority/p0, size/XS

#1910 Add cloud sql and gcs connection for pipeline-lite deployment
  manifests/kustomize/README.md
  manifests/kustomize/base/argo/kustomization.yaml
  manifests/kustomize/base/argo/minio-artifact-secret.yaml
  manifests/kustomize/base/kustomization.yaml
  manifests/kustomize/env/dev/kustomization.yaml
  manifests/kustomize/env/dev/minio/kustomization.yaml
  manifests/kustomize/env/dev/minio/minio-deployment.yaml
  manifests/kustomize/env/dev/minio/minio-pvc.yaml
  manifests/kustomize/env/dev/minio/minio-service.yaml
  manifests/kustomize/env/dev/mysql/kustomization.yaml
  manifests/kustomize/env/dev/mysql/mysql-deployment.yaml
  manifests/kustomize/env/dev/mysql/mysql-pv-claim.yaml
  manifests/kustomize/env/dev/mysql/mysql-service.yaml
  manifests/kustomize/env/gcp/.gitignore
  manifests/kustomize/env/gcp/kustomization.yaml
  manifests/kustomize/env/gcp/minio/kustomization.yaml
  manifests/kustomize/env/gcp/minio/minio-gcs-gateway-deployment.yaml
  manifests/kustomize/env/gcp/minio/minio-gcs-gateway-service.yaml
  manifests/kustomize/env/gcp/ml-pipeline-apiserver-deployment-patch.yaml
  manifests/kustomize/env/gcp/mysql/cloudsql-proxy-deployment.yaml
  manifests/kustomize/env/gcp/mysql/kustomization.yaml
  manifests/kustomize/env/gcp/mysql/mysql-service.yaml
  manifests/kustomize/namespaced-install/README.md
  manifests/kustomize/namespaced/kustomization.yaml
  manifests/kustomize/namespaced/kustomizeconfig/namespace.yaml
  manifests/kustomize/namespaced/ml-pipeline-persistenceagent-deployment-patch.yaml
  manifests/kustomize/namespaced/ml-pipeline-scheduledworkflow-deployment-patch.yaml
  manifests/kustomize/namespaced/ml-pipeline-ui-deployment-patch.yaml
  manifests/kustomize/namespaced/ml-pipeline-viewer-crd-deployment-patch.yaml
  manifests/kustomize/namespaced/namespace.yaml
  manifests/kustomize/namespaced/workflow-controller-configmap.yaml
  test/manifests/kustomization.yaml
Labels: approved, lgtm, size/L

#1875 SDK - Lightweight - Fixed custom types in multi-output case
  sdk/python/kfp/components/_python_op.py
  sdk/python/tests/components/test_python_op.py
Labels: approved, area/sdk/components, lgtm, size/M

#1914 cleanup test directory
  test/deploy-kubeflow.sh
  test/deploy-pipeline.sh
  test/minikube/OWNERS
  test/minikube/install_and_start_minikube_without_vm.sh
  test/minikube/install_argo_client.sh
  test/minikube/install_docker.sh
  test/minikube/install_docker_minikube_argo.sh
  test/presubmit-tests-gce-minikube.sh
Labels: approved, lgtm, size/L

#1874 SDK - Components - Fixed ModelBase comparison bug
  sdk/python/kfp/components/modelbase.py
  sdk/python/tests/components/test_structure_model_base.py
Labels: approved, area/sdk/components, lgtm, size/S

#898 Collecting coverage when running python tests
  .travis.yml
  sdk/python/tests/components/test_components.py
  sdk/python/tests/components/test_graph_components.py
Labels: approved, lgtm, size/S

#1822 [Bug Fix] Delete ResourceOp should not have output parameters
  sdk/python/kfp/dsl/_resource_op.py
  sdk/python/tests/compiler/compiler_tests.py
Labels: approved, lgtm, needs-ok-to-test, size/M

#1844 Add visualization-server service to lightweight deployment
  backend/src/apiserver/client_manager.go
  backend/src/apiserver/main.go
  backend/src/apiserver/server/BUILD.bazel
  backend/src/apiserver/server/visualization_server.go
  backend/src/apiserver/server/visualization_server_test.go
  manifests/kustomize/base/kustomization.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-visualization-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-visualization-service.yaml
Labels: approved, lgtm, size/L

#1890 Replace codemirror editor react component with react-ace editor component
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/DetailsTable.tsx
  frontend/src/components/__snapshots__/DetailsTable.test.tsx.snap
  frontend/src/pages/PipelineDetails.tsx
  frontend/src/pages/__snapshots__/PipelineDetails.test.tsx.snap
Labels: approved, lgtm, size/L

#1895 Add run with json data as input within fixed-data.ts for UI testing and development
  frontend/mock-backend/fixed-data.ts
  frontend/mock-backend/json-runtime.ts
Labels: approved, lgtm, size/L

#1922 Fix lint related issue
  sdk/python/tests/components/test_python_op.py
Labels: approved, lgtm, size/XS

#1920 Allow visualization kernel timeout to be specifiable via environment variables
  backend/src/apiserver/visualization/server.py
Labels: approved, lgtm, size/XS

#1921 Cleanup pipeline-lite deployment
  manifests/kustomize/README.md
  manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-scheduledworkflow-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-ui-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-viewer-crd-deployment.yaml
  manifests/kustomize/env/gcp/README.md
  manifests/kustomize/env/gcp/gcp-configurations-patch.yaml
  manifests/kustomize/env/gcp/kustomization.yaml
  manifests/kustomize/env/gcp/minio/minio-gcs-gateway-deployment.yaml
  manifests/kustomize/env/gcp/ml-pipeline-apiserver-deployment-patch.yaml
  manifests/kustomize/env/gcp/mysql/cloudsql-proxy-deployment.yaml
  manifests/kustomize/namespaced-install.yaml
  manifests/kustomize/namespaced/kustomization.yaml
  manifests/kustomize/namespaced/ml-pipeline-persistenceagent-deployment-patch.yaml
  manifests/kustomize/namespaced/ml-pipeline-scheduledworkflow-deployment-patch.yaml
  manifests/kustomize/namespaced/ml-pipeline-ui-deployment-patch.yaml
  manifests/kustomize/namespaced/ml-pipeline-viewer-crd-deployment-patch.yaml
Labels: approved, lgtm, size/L

#1906 [front-end-server] Allow viewer:tensorboard podTemplateSpec to be customizable
  frontend/server/k8s-helper.ts
  frontend/server/server.ts
  frontend/server/utils.ts
Labels: approved, lgtm, ok-to-test, size/M

#1926 update namespaced-install.yaml
  manifests/kustomize/namespaced-install.yaml
Labels: approved, lgtm, size/M

#1840 pipeline-lite: Introduce metadata component to pipeline-lite
  manifests/kustomize/base/kustomization.yaml
  manifests/kustomize/base/metadata/kustomization.yaml
  manifests/kustomize/base/metadata/metadata-deployment.yaml
  manifests/kustomize/base/metadata/metadata-service.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
Labels: approved, lgtm, ok-to-test, size/M

#1898 Add TFDV, TFMA, and Table visualization support for Python based visualizations
  backend/api/go_client/visualization.pb.go
  backend/api/swagger/visualization.swagger.json
  backend/api/visualization.proto
  backend/src/apiserver/visualization/requirements.txt
  backend/src/apiserver/visualization/table.py
  backend/src/apiserver/visualization/tfma.py
  backend/src/apiserver/visualization/third_party_licenses.csv
  frontend/src/apis/visualization/api.ts
  frontend/src/components/viewers/VisualizationCreator.test.tsx
  frontend/src/components/viewers/VisualizationCreator.tsx
  frontend/src/components/viewers/__snapshots__/VisualizationCreator.test.tsx.snap
Labels: approved, lgtm, size/L

#1927 Add pipeline id to pipeline summary card
  frontend/src/pages/PipelineDetails.tsx
  frontend/src/pages/__snapshots__/PipelineDetails.test.tsx.snap
Labels: approved, lgtm, size/M

#1928 clean up owner file
  OWNERS
  backend/OWNERS
  components/OWNERS
  sdk/OWNERS
  test/api-integration-test/OWNERS
  test/imagebuilder/OWNERS
  test/initialization-test/OWNERS
  third_party/OWNERS
Labels: approved, lgtm, size/S

#1930 SDK - Refactoring - Replaced the TypeMeta class
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/components/_components.py
  sdk/python/kfp/components/_dsl_bridge.py
  sdk/python/kfp/dsl/_component.py
  sdk/python/kfp/dsl/_metadata.py
  sdk/python/kfp/dsl/_pipeline_param.py
  sdk/python/kfp/dsl/types.py
  sdk/python/tests/dsl/component_tests.py
  sdk/python/tests/dsl/metadata_tests.py
  sdk/python/tests/dsl/pipeline_param_tests.py
  sdk/python/tests/dsl/pipeline_tests.py
Labels: approved, area/sdk, lgtm, size/L

#1918 upgrade backend image versions
  manifests/kustomize/base/kustomization.yaml
  manifests/kustomize/namespaced-install.yaml
Labels: approved, lgtm, size/S

#1838 Initial kfserving pipeline component
  components/kubeflow/kfserving/Dockerfile
  components/kubeflow/kfserving/component.yaml
  components/kubeflow/kfserving/sample-pipeline.py
  components/kubeflow/kfserving/src/kfservingdeployer.py
Labels: approved, lgtm, size/L

#1886 Support Affinity for ContainerOps
  sdk/python/kfp/compiler/_op_to_template.py
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/tests/compiler/compiler_tests.py
Labels: approved, lgtm, ok-to-test, size/M

#1932 sync namespaced install file
  manifests/kustomize/namespaced-install.yaml
Labels: approved, lgtm, size/M

#1935 Update changelog for 0.1.27
  CHANGELOG.md
Labels: approved, lgtm, size/M

#1923 Use cloud build to build images instead
  test/build-images.sh
  test/check-build-image-status.sh
  test/cloudbuild/api_server.yaml
  test/cloudbuild/batch_build.yaml
  test/install-argo.sh
  test/presubmit-tests-with-pipeline-deployment.sh
Labels: approved, lgtm, size/L

#1939 Move postsubmit tests to lite deployment
  .gitignore
  test/.gitignore
  test/deploy-cluster.sh
  test/deploy-pipeline-lite.sh
  test/postsubmit-tests-with-pipeline-deployment.sh
  test/presubmit-tests-with-pipeline-deployment.sh
Labels: approved, lgtm, size/M

#1897 Sample test improvement - using python fire to launch sample test
  test/component_test.yaml
  test/e2e_test_gke_v2.yaml
  test/sample-test/Dockerfile
  test/sample-test/run_test.sh
  test/sample-test/sample_test_launcher.py
  test/sample-test/utils.py
  test/sample_test.yaml
Labels: approved, lgtm, size/XL

#1925 Exclude visualization types from flake8 testing
  .travis.yml
  backend/src/apiserver/visualization/server.py
  backend/src/apiserver/visualization/test_exporter.py
  backend/src/apiserver/visualization/types/roc_curve.py
  backend/src/apiserver/visualization/types/table.py
  backend/src/apiserver/visualization/types/test.py
  backend/src/apiserver/visualization/types/tfdv.py
  backend/src/apiserver/visualization/types/tfma.py
Labels: approved, lgtm, size/S

#1934 SDK - Components - Improved serialization and deserialization of arguments and defaults
  sdk/python/kfp/components/_components.py
  sdk/python/kfp/components/_data_passing.py
  sdk/python/kfp/components/_python_op.py
  sdk/python/kfp/dsl/types.py
  sdk/python/tests/components/test_python_op.py
Labels: approved, area/sdk/components, lgtm, size/L

#1936 SDK - Components - Add support for the Boolean type
  sdk/python/kfp/components/_data_passing.py
  sdk/python/tests/components/test_python_op.py
Labels: approved, area/sdk/components, lgtm, size/M

#1945 SDK - Components - Add support for the List, Dict and Json types
  sdk/python/kfp/components/_data_passing.py
  sdk/python/tests/components/test_python_op.py
Labels: approved, area/sdk/components, lgtm, size/S

#1868 WithItems Support
  .gitignore
  sdk/python/kfp/compiler/_op_to_template.py
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/dsl/__init__.py
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/kfp/dsl/_for_loop.py
  sdk/python/kfp/dsl/_metadata.py
  sdk/python/kfp/dsl/_ops_group.py
  sdk/python/kfp/dsl/_pipeline_param.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/default_value.py
  sdk/python/tests/compiler/testdata/pipelineparams.py
  sdk/python/tests/compiler/testdata/withitem_basic.py
  sdk/python/tests/compiler/testdata/withitem_basic.yaml
  sdk/python/tests/compiler/testdata/withitem_nested.py
  sdk/python/tests/compiler/testdata/withitem_nested.yaml
Labels: approved, lgtm, size/XL

#1929 Add custom visualization support for Python based visualizations
  backend/api/go_client/visualization.pb.go
  backend/api/swagger/visualization.swagger.json
  backend/api/visualization.proto
  frontend/src/apis/visualization/api.ts
  frontend/src/components/viewers/VisualizationCreator.test.tsx
  frontend/src/components/viewers/VisualizationCreator.tsx
  frontend/src/components/viewers/__snapshots__/VisualizationCreator.test.tsx.snap
Labels: approved, lgtm, size/XL

#1975 Update GCP marketplace deployer dockerfile
  manifests/gcp_marketplace/deployer/Dockerfile
Labels: approved, lgtm, size/S

#1982 SDK - Tests - Fixed bug in the Artifact location test pipeline
  sdk/python/tests/compiler/testdata/artifact_location.py
  sdk/python/tests/compiler/testdata/artifact_location.yaml
Labels: approved, area/testing, kind/bug, lgtm, size/S

#1980 update kubeflow pipelines application name
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml
Labels: approved, lgtm, size/XS

#1985 Refactor tedious redefinition using withItem.
  test/e2e_test_gke_v2.yaml
Labels: approved, lgtm, size/M

#1986 Disable TFMA visualization
  frontend/src/components/viewers/VisualizationCreator.tsx
  frontend/src/components/viewers/__snapshots__/VisualizationCreator.test.tsx.snap
Labels: approved, lgtm, size/M

#791 SDK - Added support for raw input artifact argument values to ContainerOp
  sdk/python/kfp/compiler/_op_to_template.py
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/components/_dsl_bridge.py
  sdk/python/kfp/dsl/__init__.py
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/input_artifact_raw_value.py
  sdk/python/tests/compiler/testdata/input_artifact_raw_value.txt
  sdk/python/tests/compiler/testdata/input_artifact_raw_value.yaml
  sdk/python/tests/components/test_components.py
Labels: approved, area/sdk/dsl/compiler, lgtm, size/L

#1983 Remove service account from helm chart
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/argo.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/proxy.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/values.yaml
  manifests/gcp_marketplace/schema.yaml
Labels: approved, lgtm, size/XL

#1959 Add frontend support for Python based visualizations
  frontend/src/components/viewers/VisualizationCreator.tsx
  frontend/src/lib/Apis.ts
  frontend/src/pages/RunDetails.test.tsx
  frontend/src/pages/RunDetails.tsx
  frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
Labels: approved, lgtm, size/L

#1991 SDK - Components - Added output references to TaskSpec
  sdk/python/kfp/components/_components.py
  sdk/python/kfp/components/_dsl_bridge.py
  sdk/python/kfp/components/_structures.py
  sdk/python/tests/components/test_components.py
Labels: approved, area/sdk/components, lgtm, size/M

#1988 move pipeline runner service account to backend
  backend/src/apiserver/BUILD.bazel
  backend/src/apiserver/client_manager.go
  backend/src/apiserver/common/BUILD.bazel
  backend/src/apiserver/common/config.go
  backend/src/apiserver/config/config.json
  backend/src/apiserver/main.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/server/run_server_test.go
  backend/src/common/util/workflow.go
  backend/src/crd/controller/scheduledworkflow/controller.go
  backend/src/crd/controller/scheduledworkflow/main.go
  go.mod
  go.sum
  test/tools/project-cleaner/BUILD.bazel
Labels: approved, lgtm, size/L

#1987 Change sample test to read test arguments from yaml config file
  test/sample-test/check_notebook_results.py
  test/sample-test/configs/default.config.yaml
  test/sample-test/configs/tfx_cab_classification.config.yaml
  test/sample-test/configs/xgboost_training_cm.config.yaml
  test/sample-test/constants.py
  test/sample-test/run_sample_test.py
  test/sample-test/sample_test_launcher.py
Labels: approved, lgtm, size/L

#1996 pass pipeline runner service account to api server
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml
Labels: approved, lgtm, size/XS

#1771 SDK - Components - Added component properties to the task factory function
  sdk/python/kfp/components/_components.py
  sdk/python/tests/components/test_components.py
Labels: approved, area/sdk/components, lgtm, size/S
