Repository kubeflow/pipelines, pull requests merged in 2019-04, with the labels that each got.

#1039 Add run termination controls to ui
  backend/src/cmd/ml/cmd/run.go
  frontend/src/Css.tsx
  frontend/src/apis/run/api.ts
  frontend/src/components/Banner.tsx
  frontend/src/icons/statusTerminated.tsx
  frontend/src/lib/Buttons.ts
  frontend/src/lib/WorkflowParser.ts
  frontend/src/pages/Page.tsx
  frontend/src/pages/RunDetails.test.tsx
  frontend/src/pages/RunDetails.tsx
  frontend/src/pages/Status.test.tsx
  frontend/src/pages/Status.tsx
  frontend/src/pages/__snapshots__/AllRunsList.test.tsx.snap
  frontend/src/pages/__snapshots__/Archive.test.tsx.snap
  frontend/src/pages/__snapshots__/Status.test.tsx.snap
  test/frontend-integration-test/helloworld.spec.js
  test/frontend-integration-test/tensorboard-example.spec.js
Labels: approved, area/front-end, lgtm, size/XXL

#1074 Removes link to Kubeflow privacy links as KFP no longer runs Spartakus
  frontend/src/components/SideNav.tsx
  frontend/src/components/__snapshots__/SideNav.test.tsx.snap
Labels: approved, area/front-end, lgtm, size/L

#1076 Fix wrong indentation in extract_pipelineparams_from_any()
  sdk/python/kfp/dsl/_pipeline_param.py
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1045 Test loading all component.yaml definitions
  .travis.yml
  components/test_load_all_components.sh
Labels: approved, area/testing, lgtm, size/M

#1038 Fixed some typos
  components/gcp/ml_engine/deploy/README.md
  components/gcp/ml_engine/deploy/component.yaml
Labels: approved, lgtm, ok-to-test, size/M

#1071 metadata for ibm components targeting opensource
  components/ibm-components/ffdl/serve/component.yaml
  components/ibm-components/ffdl/train/component.yaml
Labels: approved, lgtm, size/XS

#1072 metadata tag for watson components
  components/ibm-components/watson/deploy/component.yaml
  components/ibm-components/watson/manage/monitor_fairness/component.yaml
  components/ibm-components/watson/manage/monitor_quality/component.yaml
  components/ibm-components/watson/manage/subscribe/component.yaml
  components/ibm-components/watson/store/component.yaml
  components/ibm-components/watson/train/component.yaml
Labels: approved, lgtm, size/S

#539 Added component definition files for our components
  components/dataflow/predict/component.yaml
  components/dataflow/tfdv/component.yaml
  components/dataflow/tfma/component.yaml
  components/dataflow/tft/component.yaml
  components/kubeflow/deployer/component.yaml
  components/kubeflow/dnntrainer/component.yaml
  components/kubeflow/katib-launcher/component.yaml
  components/local/confusion_matrix/component.yaml
  components/local/roc/component.yaml
  samples/kubeflow-tf/kubeflow-training-classification.py
  samples/xgboost-spark/xgboost-training-cm.py
Labels: approved, area/components, lgtm, size/L

#1049 Improve doc for gcp components.
  components/gcp/bigquery/query/README.md
  components/gcp/bigquery/query/component.yaml
  components/gcp/bigquery/query/sample.ipynb
  components/gcp/dataflow/launch_python/README.md
  components/gcp/dataflow/launch_python/sample.ipynb
  components/gcp/dataflow/launch_template/README.md
  components/gcp/dataflow/launch_template/sample.ipynb
  components/gcp/dataproc/create_cluster/README.md
  components/gcp/dataproc/create_cluster/sample.ipynb
  components/gcp/dataproc/delete_cluster/README.md
  components/gcp/dataproc/delete_cluster/sample.ipynb
  components/gcp/dataproc/submit_hadoop_job/README.md
  components/gcp/dataproc/submit_hadoop_job/sample.ipynb
  components/gcp/dataproc/submit_hive_job/README.md
  components/gcp/dataproc/submit_hive_job/sample.ipynb
  components/gcp/dataproc/submit_pig_job/README.md
  components/gcp/dataproc/submit_pig_job/sample.ipynb
  components/gcp/dataproc/submit_pyspark_job/README.md
  components/gcp/dataproc/submit_pyspark_job/sample.ipynb
  components/gcp/dataproc/submit_spark_job/README.md
  components/gcp/dataproc/submit_spark_job/sample.ipynb
  components/gcp/dataproc/submit_sparksql_job/README.md
  components/gcp/dataproc/submit_sparksql_job/sample.ipynb
  components/gcp/ml_engine/batch_predict/README.md
  components/gcp/ml_engine/batch_predict/sample.ipynb
  components/gcp/ml_engine/deploy/README.md
  components/gcp/ml_engine/deploy/component.yaml
  components/gcp/ml_engine/deploy/sample.ipynb
  components/gcp/ml_engine/train/README.md
  components/gcp/ml_engine/train/component.yaml
  components/gcp/ml_engine/train/sample.ipynb
  components/gcp/release.sh
Labels: approved, lgtm, size/XXL

#1067 SDK - Configure artifact name and path separately (again)
  sdk/python/kfp/compiler/_op_to_template.py
Labels: approved, area/sdk/dsl/compiler, lgtm, size/S

#1027 Improved the "IBM - Create kubernetes secret" component
  components/ibm-components/commons/config/component.yaml
  components/ibm-components/commons/config/src/config.py
Labels: approved, area/components, lgtm, size/S

#1082 Release component image version a277f87ea1d4707bf860d080d06639b7caf9a1cf
  components/dataflow/predict/component.yaml
  components/dataflow/tfdv/component.yaml
  components/dataflow/tfma/component.yaml
  components/dataflow/tft/component.yaml
  components/gcp/bigquery/query/component.yaml
  components/gcp/dataflow/launch_python/component.yaml
  components/gcp/dataflow/launch_template/component.yaml
  components/gcp/dataproc/create_cluster/component.yaml
  components/gcp/dataproc/delete_cluster/component.yaml
  components/gcp/dataproc/submit_hadoop_job/component.yaml
  components/gcp/dataproc/submit_hive_job/component.yaml
  components/gcp/dataproc/submit_pig_job/component.yaml
  components/gcp/dataproc/submit_pyspark_job/component.yaml
  components/gcp/dataproc/submit_spark_job/component.yaml
  components/gcp/dataproc/submit_sparksql_job/component.yaml
  components/gcp/ml_engine/batch_predict/component.yaml
  components/gcp/ml_engine/deploy/component.yaml
  components/gcp/ml_engine/train/component.yaml
  components/kubeflow/deployer/component.yaml
  components/kubeflow/dnntrainer/component.yaml
  components/kubeflow/launcher/kubeflow_tfjob_launcher_op.py
  components/kubeflow/launcher/src/train.template.yaml
  components/local/confusion_matrix/component.yaml
  components/local/roc/component.yaml
  samples/kubeflow-tf/kubeflow-training-classification.py
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
  samples/resnet-cmle/resnet-train-pipeline.py
  samples/tfx/taxi-cab-classification-pipeline.py
  samples/xgboost-spark/xgboost-training-cm.py
Labels: approved, lgtm, size/L

#1083 Update CHANGELOG for release 0.1.15
  CHANGELOG.md
Labels: approved, lgtm, size/M

#1088 SDK - Fix obj name in K8s -> json conversion util
  sdk/python/kfp/compiler/_k8s_helper.py
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1085 optimize UX for loading pipeline pages
  .gitignore
  backend/src/apiserver/list/list.go
  backend/src/apiserver/storage/job_store.go
  backend/src/apiserver/storage/run_store.go
Labels: approved, lgtm, size/M

#1091 Added "Target lambda" parameter to "Confusion matrix" component
  components/local/confusion_matrix/component.yaml
Labels: approved, area/components, lgtm, size/XS

#1094 Fixed bug in TFMA component code
  components/dataflow/tfma/src/model_analysis.py
Labels: approved, area/components, lgtm, size/XS

#1095 Rolling back TFMA image
  components/dataflow/tfma/component.yaml
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
  samples/tfx/taxi-cab-classification-pipeline.py
Labels: approved, area/samples, area/samples/notebooks, lgtm, size/XS

#1093 Fixed bug in ROC component definition
  components/local/roc/component.yaml
  samples/xgboost-spark/xgboost-training-cm.py
Labels: approved, area/components, lgtm, size/S

#1096 Fixed Kubeflow sample test
  test/sample-test/run_kubeflow_test.py
  test/sample-test/utils.py
Labels: approved, area/testing, lgtm, size/S

#1018 Rewrite ResNet sample by GCP components
  components/resnet-cmle/containers/deploy/Dockerfile
  components/resnet-cmle/containers/deploy/build.sh
  components/resnet-cmle/containers/preprocess/Dockerfile
  components/resnet-cmle/containers/preprocess/build.sh
  components/resnet-cmle/containers/train/Dockerfile
  components/resnet-cmle/containers/train/build.sh
  components/resnet-cmle/resnet/deploy.py
  components/resnet-cmle/resnet/preprocess.py
  components/resnet-cmle/resnet/resnet_model/trainer/preprocess.py
  components/resnet-cmle/resnet/train.py
  samples/resnet-cmle/README.md
  samples/resnet-cmle/build_pipeline.sh
  samples/resnet-cmle/preprocess/preprocess.py
  samples/resnet-cmle/preprocess/requirements.txt
  samples/resnet-cmle/resnet-train-pipeline.py
  samples/resnet-cmle/resnet_model/setup.py
  samples/resnet-cmle/resnet_model/trainer/__init__.py
  samples/resnet-cmle/resnet_model/trainer/imagenet_input.py
  samples/resnet-cmle/resnet_model/trainer/resnet_main.py
  samples/resnet-cmle/resnet_model/trainer/resnet_model.py
  samples/resnet-cmle/resnet_model/trainer/resnet_preprocessing.py
Labels: approved, lgtm, size/XXL

#1103 uprade tf-serving in deployer component
  components/kubeflow/deployer/Dockerfile
  components/kubeflow/deployer/src/deploy.sh
Labels: approved, lgtm, size/XS

#1107 incremented app version
  sdk/python/setup.py
Labels: approved, area/sdk, lgtm, needs-ok-to-test, size/XS

#1097 Stabilized the artifact ordering during the compilation
  sdk/python/kfp/compiler/_op_to_template.py
Labels: approved, area/sdk/dsl/compiler, lgtm, size/XS

#1077 Passing the annotations and labels to the ContainerOp
  sdk/python/kfp/components/_dsl_bridge.py
  sdk/python/tests/components/test_components.py
Labels: approved, area/sdk/components, lgtm, size/S

#1118 update katib laucher
  components/kubeflow/katib-launcher/Dockerfile
  components/kubeflow/katib-launcher/OWNERS
  components/kubeflow/katib-launcher/component.yaml
  components/kubeflow/katib-launcher/kubeflow_katib_launcher_op.py
  components/kubeflow/katib-launcher/src/launch_study_job.py
Labels: approved, lgtm, size/S

#1122 Surface workflow finished time in list run API
  backend/api/go_client/run.pb.go
  backend/api/go_http_client/run_model/api_run.go
  backend/api/run.proto
  backend/api/swagger/run.swagger.json
  backend/src/apiserver/list/list.go
  backend/src/apiserver/list/list_test.go
  backend/src/apiserver/model/run.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/server/api_converter.go
  backend/src/apiserver/server/api_converter_test.go
  backend/src/apiserver/server/run_server_test.go
  backend/src/apiserver/storage/job_store.go
  backend/src/apiserver/storage/run_store.go
  backend/src/apiserver/storage/run_store_test.go
  backend/src/cmd/ml/cmd/run_test.go
  backend/src/common/util/workflow.go
  backend/test/integration/run_api_test.go
Labels: approved, lgtm, size/L

#1140 Set run model default timestamp to 0
  backend/src/apiserver/model/run.go
Labels: approved, lgtm, size/XS

#964 Add a ResNet example from NVIDIA
  samples/nvidia-resnet/LICENSE
  samples/nvidia-resnet/README.md
  samples/nvidia-resnet/build_pipeline.sh
  samples/nvidia-resnet/clean_utils/delete_all_previous_resources.sh
  samples/nvidia-resnet/clean_utils/remove_minikube_and_kubeflow.sh
  samples/nvidia-resnet/components/inference_server_launcher/Dockerfile
  samples/nvidia-resnet/components/inference_server_launcher/build.sh
  samples/nvidia-resnet/components/inference_server_launcher/src/deploy_trtis.py
  samples/nvidia-resnet/components/inference_server_launcher/src/trtis-service-template.yaml
  samples/nvidia-resnet/components/preprocess/Dockerfile
  samples/nvidia-resnet/components/preprocess/build.sh
  samples/nvidia-resnet/components/preprocess/src/preprocess.py
  samples/nvidia-resnet/components/train/Dockerfile
  samples/nvidia-resnet/components/train/build.sh
  samples/nvidia-resnet/components/train/src/train.py
  samples/nvidia-resnet/components/train/src/trtis_resource/config.pbtxt
  samples/nvidia-resnet/components/train/src/trtis_resource/labels.txt
  samples/nvidia-resnet/components/webapp/Dockerfile
  samples/nvidia-resnet/components/webapp/build.sh
  samples/nvidia-resnet/components/webapp/src/README.md
  samples/nvidia-resnet/components/webapp/src/flask_server.py
  samples/nvidia-resnet/components/webapp/src/static/scripts/material.min.js
  samples/nvidia-resnet/components/webapp/src/static/styles/demo.css
  samples/nvidia-resnet/components/webapp/src/static/styles/material.deep_purple-pink.min.css
  samples/nvidia-resnet/components/webapp/src/templates/index.html
  samples/nvidia-resnet/components/webapp/src/trtis_client.py
  samples/nvidia-resnet/components/webapp_launcher/Dockerfile
  samples/nvidia-resnet/components/webapp_launcher/build.sh
  samples/nvidia-resnet/components/webapp_launcher/src/deploy_webapp.py
  samples/nvidia-resnet/components/webapp_launcher/src/webapp-service-template.yaml
  samples/nvidia-resnet/install_kubeflow_and_dependencies.sh
  samples/nvidia-resnet/pipeline/Dockerfile
  samples/nvidia-resnet/pipeline/build.sh
  samples/nvidia-resnet/pipeline/src/persistent-volume-claim.yaml
  samples/nvidia-resnet/pipeline/src/persistent-volume.yaml
  samples/nvidia-resnet/pipeline/src/pipeline.py
  samples/nvidia-resnet/prepare_test_inference_data.sh
Labels: approved, lgtm, ok-to-test, size/XXL

#1124 Fixed CloudBuild failure
  .cloudbuild.yaml
Labels: approved, area/build-release, lgtm, size/S

#1126 Updated descriptions of pre-installed samples
  backend/src/apiserver/config/sample_config.json
Labels: approved, area/samples, lgtm, size/S

#1144 Removes unnecessary API calls
  frontend/src/apis/run/api.ts
  frontend/src/lib/Utils.test.ts
  frontend/src/lib/Utils.ts
  frontend/src/pages/ExperimentDetails.test.tsx
  frontend/src/pages/ExperimentDetails.tsx
  frontend/src/pages/ExperimentList.test.tsx
  frontend/src/pages/ExperimentList.tsx
  frontend/src/pages/RunDetails.tsx
  frontend/src/pages/RunList.test.tsx
  frontend/src/pages/RunList.tsx
  frontend/src/pages/__snapshots__/ExperimentDetails.test.tsx.snap
  frontend/src/pages/__snapshots__/RunList.test.tsx.snap
Labels: approved, area/front-end, lgtm, size/L

#1109 Updated the "Basic - Exit handler" sample
  samples/basic/exit_handler.py
Labels: approved, area/samples, lgtm, size/M

#1111 Updated the "Basic - Retry" sample
  samples/basic/retry.py
Labels: approved, area/samples, lgtm, size/M

#1117 Updated the package version in the notebooks
  samples/notebooks/DSL Static Type Checking.ipynb
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
  samples/notebooks/Lightweight Python components - basics.ipynb
  samples/tfx-oss/TFX Example.ipynb
Labels: approved, area/samples/notebooks, lgtm, size/XS

#1129 add type checking sample to sample tests
  samples/notebooks/DSL Static Type Checking.ipynb
  test/sample-test/check_notebook_results.py
  test/sample-test/run_test.sh
  test/sample_test_v2.yaml
Labels: approved, lgtm, size/L

#1143 use kubeflow/pipelines branch for deployment in test
  test/deploy-kubeflow.sh
Labels: approved, lgtm, size/S

#1137 Allow later versions of dependencies to be used with Python KFP package.
  sdk/python/setup.py
Labels: approved, lgtm, size/M

#1151 fix missing filter for list call
  backend/src/apiserver/storage/job_store.go
  backend/src/apiserver/storage/job_store_test.go
  backend/src/apiserver/storage/run_store.go
  backend/src/apiserver/storage/run_store_test.go
Labels: approved, lgtm, size/M

#1154 bug fix in resnet sample
  samples/resnet-cmle/resnet-train-pipeline.py
Labels: approved, lgtm, size/XS

#1120 SDK - Simplified the @pipeline decorator
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/compiler/main.py
  sdk/python/kfp/dsl/_metadata.py
  sdk/python/kfp/dsl/_pipeline.py
  sdk/python/tests/dsl/pipeline_tests.py
Labels: approved, area/sdk/dsl, area/sdk/dsl/compiler, lgtm, size/M

#1153 Add filter to next page token so it applies to subsequently requested pages
  backend/src/apiserver/filter/BUILD.bazel
  backend/src/apiserver/filter/filter.go
  backend/src/apiserver/filter/filter_test.go
  backend/src/apiserver/list/list.go
  backend/src/apiserver/list/list_test.go
  backend/src/apiserver/storage/experiment_store_test.go
Labels: approved, lgtm, size/L

#1133 Add helper to easily add aws secrets
  sdk/python/kfp/aws.py
  sdk/python/tests/dsl/aws_extensions_tests.py
Labels: approved, lgtm, needs-ok-to-test, size/L

#1139 Allow adding pipeline with name and description.
  sdk/python/kfp/dsl/_pipeline.py
Labels: approved, lgtm, size/S

#1136 Expose service-type as parameter
  components/kubeflow/deployer/component.yaml
  components/kubeflow/deployer/src/deploy.sh
Labels: approved, lgtm, needs-ok-to-test, size/S

#1148 using comp yaml for ffdl pipeline
  samples/ibm-samples/ffdl-seldon/ffdl_pipeline.py
Labels: approved, lgtm, size/M

#1147 component readmes
  components/ibm-components/ffdl/serve/README.md
  components/ibm-components/ffdl/train/README.md
Labels: approved, lgtm, size/L

#1159 new kubernetes packages contain breaking change, thus fixing the version in the sample test image
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
  sdk/python/kfp/compiler/_k8s_helper.py
  sdk/python/setup.py
  test/sample-test/Dockerfile
Labels: approved, lgtm, size/XS

#1165 delete the resnet image items
  .cloudbuild.yaml
Labels: approved, lgtm, size/XS

#1161 Adding myself as a reviewer for components
  components/OWNERS
Labels: approved, lgtm, size/XS

#1058 Build Pipeline leveraging Arena
  components/arena/docker/Dockerfile
  components/arena/docker/arena_launcher.py
  components/arena/docker/requirements.txt
  components/arena/python/arena/__init__.py
  components/arena/python/arena/_arena_distributed_tf_op.py
  components/arena/python/arena/_arena_mpi_op.py
  components/arena/python/arena/_arena_standalone_op.py
  components/arena/python/arena/_utils.py
  components/arena/python/build.sh
  components/arena/python/setup.py
  samples/arena-samples/README.md
  samples/arena-samples/arena.yaml
  samples/arena-samples/arena_launcher_rbac.yaml
  samples/arena-samples/mpi/mpi_run.py
  samples/arena-samples/standalonejob/README.md
  samples/arena-samples/standalonejob/demo.jpg
  samples/arena-samples/standalonejob/standalone_pipeline.ipynb
  samples/arena-samples/standalonejob/standalone_pipeline.py
Labels: approved, lgtm, ok-to-test, size/XXL

#1166 SDK - Simplified the @component decorator
  sdk/python/kfp/dsl/_component.py
  sdk/python/kfp/dsl/_metadata.py
Labels: approved, area/sdk, lgtm, size/M

#1171 Component releasing for 0.1.17
  components/dataflow/predict/component.yaml
  components/dataflow/tfdv/component.yaml
  components/dataflow/tfma/component.yaml
  components/dataflow/tft/component.yaml
  components/gcp/bigquery/query/component.yaml
  components/gcp/dataflow/launch_python/component.yaml
  components/gcp/dataflow/launch_template/component.yaml
  components/gcp/dataproc/create_cluster/component.yaml
  components/gcp/dataproc/delete_cluster/component.yaml
  components/gcp/dataproc/submit_hadoop_job/component.yaml
  components/gcp/dataproc/submit_hive_job/component.yaml
  components/gcp/dataproc/submit_pig_job/component.yaml
  components/gcp/dataproc/submit_pyspark_job/component.yaml
  components/gcp/dataproc/submit_spark_job/component.yaml
  components/gcp/dataproc/submit_sparksql_job/component.yaml
  components/gcp/ml_engine/batch_predict/component.yaml
  components/gcp/ml_engine/deploy/component.yaml
  components/gcp/ml_engine/train/component.yaml
  components/kubeflow/deployer/component.yaml
  components/kubeflow/dnntrainer/component.yaml
  components/kubeflow/launcher/kubeflow_tfjob_launcher_op.py
  components/kubeflow/launcher/src/train.template.yaml
  components/local/confusion_matrix/component.yaml
  components/local/roc/component.yaml
  components/release.sh
  samples/kubeflow-tf/kubeflow-training-classification.py
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
  samples/tfx/taxi-cab-classification-pipeline.py
  samples/xgboost-spark/xgboost-training-cm.py
Labels: approved, lgtm, size/M

#1176 release 0.1.17: update yaml tag in samples
  samples/arena-samples/README.md
  samples/ibm-samples/ffdl-seldon/ffdl_pipeline.py
  samples/kubeflow-tf/kubeflow-training-classification.py
  samples/resnet-cmle/resnet-train-pipeline.py
  samples/xgboost-spark/xgboost-training-cm.py
Labels: approved, lgtm, size/S

#1178 SDK/Client - Stopped extracting pipeline file to disk during submission
  sdk/python/kfp/_client.py
Labels: approved, area/sdk/client, lgtm, size/XS

#1174 adding myself as reviewer for samples
  samples/OWNERS
Labels: approved, lgtm, size/XS

#1128 Apply latest doc review changes to github docs
  components/gcp/bigquery/query/README.md
  components/gcp/bigquery/query/sample.ipynb
  components/gcp/dataflow/launch_python/README.md
  components/gcp/dataflow/launch_python/sample.ipynb
  components/gcp/dataflow/launch_template/README.md
  components/gcp/dataflow/launch_template/sample.ipynb
  components/gcp/dataproc/create_cluster/README.md
  components/gcp/dataproc/create_cluster/sample.ipynb
  components/gcp/dataproc/delete_cluster/README.md
  components/gcp/dataproc/delete_cluster/sample.ipynb
  components/gcp/dataproc/submit_hadoop_job/README.md
  components/gcp/dataproc/submit_hadoop_job/sample.ipynb
  components/gcp/dataproc/submit_hive_job/README.md
  components/gcp/dataproc/submit_hive_job/sample.ipynb
  components/gcp/dataproc/submit_pig_job/README.md
  components/gcp/dataproc/submit_pig_job/sample.ipynb
  components/gcp/dataproc/submit_pyspark_job/README.md
  components/gcp/dataproc/submit_pyspark_job/sample.ipynb
  components/gcp/dataproc/submit_spark_job/README.md
  components/gcp/dataproc/submit_spark_job/sample.ipynb
  components/gcp/dataproc/submit_sparksql_job/README.md
  components/gcp/dataproc/submit_sparksql_job/sample.ipynb
  components/gcp/ml_engine/batch_predict/README.md
  components/gcp/ml_engine/batch_predict/sample.ipynb
  components/gcp/ml_engine/deploy/README.md
  components/gcp/ml_engine/deploy/sample.ipynb
  components/gcp/ml_engine/train/README.md
  components/gcp/ml_engine/train/sample.ipynb
Labels: approved, lgtm, size/XXL

#1184 update changelog
  CHANGELOG.md
Labels: approved, lgtm, size/M

#1186 Make Python Client robust to existing IPython installations
  sdk/python/kfp/_client.py
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1167 SDK - Got rid of the global variable collecting all created pipelines
  sdk/python/kfp/compiler/main.py
  sdk/python/kfp/dsl/_pipeline.py
Labels: approved, area/sdk, area/sdk/dsl/compiler, lgtm, size/M

#1108 Updated the "Basic - Conditional" sample
  samples/basic/condition.py
Labels: approved, area/samples, lgtm, size/M

#1110 Updated the "Basic - Parallel execution" sample
  samples/basic/parallel_join.py
Labels: approved, area/samples, lgtm, size/M

#1112 Updated the "Basic - Sequential execution" sample
  samples/basic/sequential.py
Labels: approved, area/samples, lgtm, size/M

#1113 Updated the "Basic - Recursive loop" sample
  samples/basic/recursion.py
Labels: approved, area/samples, lgtm, size/M

#1115 Updated the "TFX Taxi Cab Classification Pipeline" sample
  samples/tfx/taxi-cab-classification-pipeline.py
Labels: approved, area/samples, lgtm, size/L

#1179 Update arena component with git support
  components/arena/docker/arena_launcher.py
  components/arena/python/arena/_arena_mpi_op.py
  components/arena/python/arena/_arena_standalone_op.py
  samples/arena-samples/standalonejob/standalone_pipeline.py
Labels: approved, lgtm, size/M

#1116 Updated the "XGBoost Trainer'" sample
  samples/xgboost-spark/xgboost-training-cm.py
Labels: approved, area/samples, lgtm, size/L

#1192 Return error when ml-metadata serialized format does not match expected format.
  backend/src/apiserver/metadata/metadata_store.go
  backend/src/apiserver/metadata/metadata_store_test.go
Labels: approved, lgtm, size/M

#1114 Updated the "Kubeflow training and classification" sample
  samples/kubeflow-tf/kubeflow-training-classification.py
Labels: approved, area/samples, lgtm, size/L

#1193 Updated vulnerable package
  contrib/components/openvino/ovms-deployer/containers/requirements.txt
Labels: approved, area/components, lgtm, size/XS

#1185 Fixes deletion of recurring runs
  frontend/src/lib/Buttons.ts
  frontend/src/pages/PipelineDetails.tsx
  frontend/src/pages/PipelineList.tsx
  frontend/src/pages/RecurringRunDetails.tsx
Labels: approved, area/front-end, kind/bug, lgtm, size/M

#1175 Allow creating runs without experiments
  frontend/src/components/CustomTable.tsx
  frontend/src/components/__snapshots__/CustomTable.test.tsx.snap
  frontend/src/lib/Buttons.ts
  frontend/src/pages/AllRunsList.tsx
  frontend/src/pages/ExperimentList.test.tsx
  frontend/src/pages/ExperimentList.tsx
  frontend/src/pages/PipelineDetails.test.tsx
  frontend/src/pages/__snapshots__/AllRunsList.test.tsx.snap
  frontend/src/pages/__snapshots__/RunList.test.tsx.snap
  test/frontend-integration-test/helloworld.spec.js
  test/frontend-integration-test/run_test.sh
Labels: approved, area/front-end, area/testing, lgtm, size/L

#1201 Fix package version conflict
  component_sdk/python/requirements.txt
  sdk/python/setup.py
Labels: approved, lgtm, size/XS

#1206 update types to defined core type names
  components/dataflow/predict/component.yaml
  components/dataflow/tfdv/component.yaml
  components/dataflow/tfma/component.yaml
  components/dataflow/tft/component.yaml
  components/gcp/dataflow/launch_python/README.md
  components/gcp/dataflow/launch_python/sample.ipynb
  components/gcp/dataproc/submit_hive_job/README.md
  components/gcp/dataproc/submit_hive_job/sample.ipynb
  components/kubeflow/deployer/component.yaml
  components/kubeflow/dnntrainer/component.yaml
  components/kubeflow/katib-launcher/component.yaml
  components/local/confusion_matrix/component.yaml
  components/local/roc/component.yaml
Labels: approved, lgtm, size/L

#1168 SDK - Decoupling ContainerOp from compiler
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/kfp/dsl/_pipeline.py
Labels: approved, area/sdk/dsl, lgtm, size/S

#1169 SDK/Tests - Properly closing tar files opened for writing
  sdk/python/tests/compiler/component_builder_test.py
Labels: approved, area/sdk, lgtm, size/M

#1170 SDK - Replaced insecure yaml.load with yaml.safe_load
  components/ibm-components/ffdl/train/src/train.py
  components/kubeflow/katib-launcher/src/launch_study_job.py
  components/kubeflow/launcher/src/launch_tf_job.py
  components/kubeflow/launcher/test/test_launcher.py
  sdk/python/kfp/_client.py
  sdk/python/kfp/components/_yaml_utils.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/component_builder_test.py
Labels: approved, area/sdk, lgtm, size/M

#1177 Marked all scripts as executable
  components/sample/keras/train_classifier/build_image.sh
  frontend/src/apis/filter/git_push.sh
  test/check-argo-status.sh
  test/install-argo.sh
  test/test-prep.sh
Labels: approved, area/testing, lgtm, size/XS

#1119 SDK - Removed SourceSpec structure
  sdk/python/kfp/components/_structures.py
Labels: approved, area/sdk/components, lgtm, size/S

#1188 SDK - Made ComponentSpec.implementation field optional
  sdk/python/kfp/components/_dsl_bridge.py
  sdk/python/kfp/components/_structures.py
Labels: approved, area/sdk/components, lgtm, size/XS

#867 Allow more flexible way to config the api server addr in persistence agent
  backend/src/agent/persistence/client/pipeline_client.go
  backend/src/agent/persistence/main.go
Labels: approved, lgtm, ok-to-test, size/S

#1202 Moving the component 'verbs' ahead of 'product/project'
  components/ibm-components/watson/deploy/component.yaml
  components/ibm-components/watson/manage/monitor_fairness/component.yaml
  components/ibm-components/watson/manage/monitor_quality/component.yaml
  components/ibm-components/watson/manage/subscribe/component.yaml
  components/ibm-components/watson/store/component.yaml
  components/ibm-components/watson/train/component.yaml
  samples/ibm-samples/ffdl-seldon/ffdl_pipeline.py
Labels: approved, lgtm, size/S

#1221 update a broken link
  samples/notebooks/DSL Static Type Checking.ipynb
Labels: approved, lgtm, size/XS

#821 Kubeflow pipelines quickstart notebooks added.
  samples/notebooks/quickstart.ipynb
  samples/notebooks/quickstart_iris.csv
Labels: approved, lgtm, ok-to-test, size/XL

#1210 Testing - Fixed the postsubmit tests
  test/postsubmit-tests-with-pipeline-deployment.sh
Labels: approved, area/testing, lgtm, size/XS

#926 Extend the DSL to implement the design of #801
  frontend/src/components/StaticNodeDetails.tsx
  frontend/src/lib/StaticGraphParser.test.ts
  frontend/src/lib/StaticGraphParser.ts
  frontend/src/lib/WorkflowParser.test.ts
  frontend/src/lib/WorkflowParser.ts
  frontend/src/pages/RunDetails.test.tsx
  frontend/src/pages/RunDetails.tsx
  frontend/src/pages/__snapshots__/PipelineDetails.test.tsx.snap
  frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
  samples/resourceops/resourceop_basic.py
  samples/resourceops/volume_snapshotop_rokurl.py
  samples/resourceops/volume_snapshotop_sequential.py
  samples/resourceops/volumeop_basic.py
  samples/resourceops/volumeop_dag.py
  samples/resourceops/volumeop_parallel.py
  samples/resourceops/volumeop_sequential.py
  sdk/python/kfp/compiler/_op_to_template.py
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/dsl/__init__.py
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/kfp/dsl/_ops_group.py
  sdk/python/kfp/dsl/_pipeline.py
  sdk/python/kfp/dsl/_pipeline_volume.py
  sdk/python/kfp/dsl/_resource_op.py
  sdk/python/kfp/dsl/_volume_op.py
  sdk/python/kfp/dsl/_volume_snapshot_op.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/resourceop_basic.py
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
  sdk/python/tests/compiler/testdata/volume_snapshotop_rokurl.py
  sdk/python/tests/compiler/testdata/volume_snapshotop_rokurl.yaml
  sdk/python/tests/compiler/testdata/volume_snapshotop_sequential.py
  sdk/python/tests/compiler/testdata/volume_snapshotop_sequential.yaml
  sdk/python/tests/compiler/testdata/volumeop_basic.py
  sdk/python/tests/compiler/testdata/volumeop_basic.yaml
  sdk/python/tests/compiler/testdata/volumeop_dag.py
  sdk/python/tests/compiler/testdata/volumeop_dag.yaml
  sdk/python/tests/compiler/testdata/volumeop_parallel.py
  sdk/python/tests/compiler/testdata/volumeop_parallel.yaml
  sdk/python/tests/compiler/testdata/volumeop_sequential.py
  sdk/python/tests/compiler/testdata/volumeop_sequential.yaml
  sdk/python/tests/dsl/container_op_tests.py
  sdk/python/tests/dsl/main.py
  sdk/python/tests/dsl/pipeline_volume_tests.py
  sdk/python/tests/dsl/resource_op_tests.py
  sdk/python/tests/dsl/volume_op_tests.py
  sdk/python/tests/dsl/volume_snapshotop_tests.py
Labels: approved, lgtm, ok-to-test, size/XXL

#998 Parameterize the artifact path for mlpipeline ui-metadata and metrics
  sdk/python/kfp/compiler/_op_to_template.py
  sdk/python/kfp/dsl/_container_op.py
Labels: approved, lgtm, ok-to-test, size/XS

#1227 modernize-wml-pipeline
  samples/ibm-samples/watson/watson_train_serve_pipeline.py
Labels: approved, lgtm, size/M

#1230 simplifying-ffdl-params
  samples/ibm-samples/ffdl-seldon/ffdl_pipeline.py
Labels: approved, lgtm, size/S

#1225 Swagger - Specifying content types on the route level
  backend/api/swagger/pipeline.upload.swagger.json
Labels: approved, area/back-end, lgtm, size/S

#1191 Expose step id and step name
  components/arena/docker/arena_launcher.py
  components/arena/python/arena/_arena_distributed_tf_op.py
  components/arena/python/arena/_arena_mpi_op.py
  components/arena/python/arena/_arena_standalone_op.py
  components/arena/python/build.sh
  components/arena/python/setup.py
  samples/arena-samples/standalonejob/README.md
  samples/arena-samples/standalonejob/standalone_pipeline.py
Labels: approved, lgtm, size/L

#1196 Testing/Sample - Made checking confusion matrix data more robust
  test/sample-test/run_kubeflow_test.py
  test/sample-test/run_xgboost_test.py
Labels: approved, area/testing, lgtm, size/M

#1232 clean up quickstart sample a bit
  samples/notebooks/quickstart.ipynb
Labels: approved, lgtm, size/M

#1197 SDK - Fixed the non-string items in the command-line arguments
  sdk/python/kfp/dsl/_container_op.py
Labels: approved, area/sdk/dsl, lgtm, size/S

#969 Minor fix on samples/tfx-oss/README.md
  samples/tfx-oss/README.md
Labels: approved, lgtm, ok-to-test, size/S

#1238 Release b0147bdbed9f25212408e0468a475289e80e0406
  components/dataflow/predict/component.yaml
  components/dataflow/tfdv/component.yaml
  components/dataflow/tfma/component.yaml
  components/dataflow/tft/component.yaml
  components/gcp/bigquery/query/README.md
  components/gcp/bigquery/query/component.yaml
  components/gcp/bigquery/query/sample.ipynb
  components/gcp/dataflow/launch_python/README.md
  components/gcp/dataflow/launch_python/component.yaml
  components/gcp/dataflow/launch_python/sample.ipynb
  components/gcp/dataflow/launch_template/README.md
  components/gcp/dataflow/launch_template/component.yaml
  components/gcp/dataflow/launch_template/sample.ipynb
  components/gcp/dataproc/create_cluster/README.md
  components/gcp/dataproc/create_cluster/component.yaml
  components/gcp/dataproc/create_cluster/sample.ipynb
  components/gcp/dataproc/delete_cluster/README.md
  components/gcp/dataproc/delete_cluster/component.yaml
  components/gcp/dataproc/delete_cluster/sample.ipynb
  components/gcp/dataproc/submit_hadoop_job/README.md
  components/gcp/dataproc/submit_hadoop_job/component.yaml
  components/gcp/dataproc/submit_hadoop_job/sample.ipynb
  components/gcp/dataproc/submit_hive_job/README.md
  components/gcp/dataproc/submit_hive_job/component.yaml
  components/gcp/dataproc/submit_hive_job/sample.ipynb
  components/gcp/dataproc/submit_pig_job/README.md
  components/gcp/dataproc/submit_pig_job/component.yaml
  components/gcp/dataproc/submit_pig_job/sample.ipynb
  components/gcp/dataproc/submit_pyspark_job/README.md
  components/gcp/dataproc/submit_pyspark_job/component.yaml
  components/gcp/dataproc/submit_pyspark_job/sample.ipynb
  components/gcp/dataproc/submit_spark_job/README.md
  components/gcp/dataproc/submit_spark_job/component.yaml
  components/gcp/dataproc/submit_spark_job/sample.ipynb
  components/gcp/dataproc/submit_sparksql_job/README.md
  components/gcp/dataproc/submit_sparksql_job/component.yaml
  components/gcp/dataproc/submit_sparksql_job/sample.ipynb
  components/gcp/ml_engine/batch_predict/README.md
  components/gcp/ml_engine/batch_predict/component.yaml
  components/gcp/ml_engine/batch_predict/sample.ipynb
  components/gcp/ml_engine/deploy/README.md
  components/gcp/ml_engine/deploy/component.yaml
  components/gcp/ml_engine/deploy/sample.ipynb
  components/gcp/ml_engine/train/README.md
  components/gcp/ml_engine/train/component.yaml
  components/gcp/ml_engine/train/sample.ipynb
  components/kubeflow/deployer/component.yaml
  components/kubeflow/dnntrainer/component.yaml
  components/kubeflow/launcher/kubeflow_tfjob_launcher_op.py
  components/kubeflow/launcher/src/train.template.yaml
  components/local/confusion_matrix/component.yaml
  components/local/roc/component.yaml
  samples/kubeflow-tf/kubeflow-training-classification.py
  samples/notebooks/KubeFlow Pipeline Using TFX OSS Components.ipynb
  samples/resnet-cmle/resnet-train-pipeline.py
  samples/tfx/taxi-cab-classification-pipeline.py
  samples/xgboost-spark/xgboost-training-cm.py
  sdk/python/setup.py
Labels: approved, area/build-release, lgtm, size/L

#1239 Fixing comp names
  components/ibm-components/commons/config/component.yaml
  components/ibm-components/ffdl/serve/component.yaml
  components/ibm-components/ffdl/train/component.yaml
  samples/ibm-samples/ffdl-seldon/ffdl_pipeline.py
Labels: approved, lgtm, size/S

#1245 fix the link for tfx taxi example
  samples/tfx-oss/README.md
Labels: approved, lgtm, size/XS

#1241 updated ffdl notebook using component yaml file
  samples/ibm-samples/ffdl-seldon/ffdl_pipeline.ipynb
Labels: approved, lgtm, size/L

#1246 Fix Watson pipeline example
  components/ibm-components/commons/config/src/config.py
  components/ibm-components/ffdl/serve/component.yaml
  components/ibm-components/ffdl/train/component.yaml
  components/ibm-components/watson/deploy/component.yaml
  components/ibm-components/watson/manage/monitor_fairness/component.yaml
  components/ibm-components/watson/manage/monitor_quality/component.yaml
  components/ibm-components/watson/manage/subscribe/component.yaml
  components/ibm-components/watson/store/component.yaml
  components/ibm-components/watson/train/component.yaml
  components/ibm-components/watson/train/src/wml-train.py
  samples/ibm-samples/watson/watson_train_serve_pipeline.py
Labels: approved, lgtm, ok-to-test, size/M

#1199 Clear default exp table on delete and create default exp on run create if none exists
  backend/src/apiserver/main.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/storage/db_status_store.go
  backend/src/apiserver/storage/default_experiment_store.go
  backend/src/apiserver/storage/default_experiment_store_test.go
  backend/src/apiserver/storage/experiment_store.go
  backend/src/apiserver/storage/job_store.go
  backend/src/apiserver/storage/run_store.go
  test/frontend-integration-test/helloworld.spec.js
Labels: approved, area/api, area/testing, lgtm, size/L

#1247 display kaniko log if failed
  sdk/python/kfp/compiler/_component_builder.py
  sdk/python/kfp/compiler/_k8s_helper.py
Labels: approved, lgtm, size/XS

#1249 remove unnecessary args
  test/presubmit-tests-with-pipeline-deployment.sh
Labels: approved, lgtm, size/XS

#1248 fix postsubmit bugs
  test/deploy-pipeline.sh
  test/postsubmit-tests-with-pipeline-deployment.sh
  test/test-prep.sh
Labels: approved, lgtm, size/XS

#1214 SDK - Separated the generated api client package
  backend/api/build_kfp_server_api_python_package.sh
  sdk/python/build.sh
  sdk/python/kfp/_client.py
  sdk/python/setup.py
Labels: approved, area/sdk/client, lgtm, size/L

#1251 Update arena SDK version
  components/arena/python/arena/_arena_distributed_tf_op.py
  components/arena/python/arena/_arena_mpi_op.py
  components/arena/python/arena/_arena_standalone_op.py
  components/arena/python/build.sh
  samples/arena-samples/standalonejob/README.md
Labels: approved, lgtm, size/M

#1260 Marking the UI-metadata and Metrics artifacts as optional
  sdk/python/kfp/compiler/_op_to_template.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/basic.yaml
  sdk/python/tests/compiler/testdata/coin.yaml
  sdk/python/tests/compiler/testdata/compose.yaml
  sdk/python/tests/compiler/testdata/default_value.yaml
  sdk/python/tests/compiler/testdata/imagepullsecret.yaml
  sdk/python/tests/compiler/testdata/immediate_value.yaml
  sdk/python/tests/compiler/testdata/pipelineparams.yaml
  sdk/python/tests/compiler/testdata/recursive_do_while.yaml
  sdk/python/tests/compiler/testdata/recursive_while.yaml
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
  sdk/python/tests/compiler/testdata/retry.yaml
  sdk/python/tests/compiler/testdata/sidecar.yaml
  sdk/python/tests/compiler/testdata/volume.yaml
  sdk/python/tests/compiler/testdata/volume_snapshotop_rokurl.yaml
  sdk/python/tests/compiler/testdata/volume_snapshotop_sequential.yaml
  sdk/python/tests/compiler/testdata/volumeop_basic.yaml
  sdk/python/tests/compiler/testdata/volumeop_dag.yaml
  sdk/python/tests/compiler/testdata/volumeop_parallel.yaml
  sdk/python/tests/compiler/testdata/volumeop_sequential.yaml
Labels: approved, area/sdk/dsl/compiler, lgtm, size/L

#1215 SDK - Preventing errors when importing kfp.notebook
  sdk/python/kfp/notebook/_magic.py
Labels: approved, area/sdk, lgtm, size/S
