Repository kubeflow/pipelines, pull requests merged in 2019-11, with the labels that each got.

#2521 [Test] Fix TFX related Travis tests
  .travis.yml
Labels: approved, lgtm, size/S

#2522 SDK - Compiler - Fixed failures on Jinja placeholders
  sdk/python/kfp/compiler/_data_passing_rewriter.py
Labels: approved, area/sdk/dsl/compiler, lgtm, size/S

#2526 [Sample] Align preload TFX sample with TFX head
  samples/contrib/parameterized_tfx_oss/README.md
  samples/contrib/parameterized_tfx_oss/parameterized_tfx_oss.py
Labels: approved, lgtm, size/XS

#2517 Frontend - Added support for https artifact links
  frontend/src/components/ArtifactLink.tsx
  frontend/src/components/GcsLink.tsx
  frontend/src/components/ResourceInfo.tsx
  frontend/src/pages/ArtifactList.tsx
Labels: approved, area/front-end, lgtm, size/M

#2527 Update __init__.py
  sdk/python/kfp/__init__.py
Labels: approved, lgtm, size/XS

#2520 update location for logo
  manifests/gcp_marketplace/chart/kubeflow-pipelines/logo.png
  manifests/gcp_marketplace/logo.png
Labels: approved, lgtm, size/XS

#2528 Update setup.py
  components/gcp/container/component_sdk/python/setup.py
Labels: approved, lgtm, size/XS

#2530 Update kustomization.yaml
  manifests/kustomize/base/kustomization.yaml
Labels: approved, lgtm, size/S

#2418 SDK - Client - Added API models to the generated API
  sdk/python/kfp/_client.py
Labels: approved, area/sdk/client, lgtm, size/XS

#2525 Frontend format check should be before linting.
  frontend/package.json
Labels: approved, area/front-end, lgtm, size/XS

#2524 SDK - Client - Fixed client on Windows
  sdk/python/kfp/_client.py
Labels: approved, area/sdk/client, lgtm, size/XS

#2541 Update CHANGELOG.md
  CHANGELOG.md
Labels: approved, lgtm, size/M

#2546 Fix broken license link for jupyter notebook
  backend/src/apiserver/visualization/third_party_licenses.csv
Labels: approved, kind/bug, lgtm, size/XS

#2549 [Misc] Add releasing note
  release/OWNERS
  release/RELEASE.md
Labels: approved, lgtm, size/M

#2543 Adding diagnose_me to CLI tool
  sdk/python/kfp/cli/cli.py
  sdk/python/kfp/cli/diagnose_me_cli.py
Labels: approved, lgtm, size/M

#2326 SDK - DSL - Deprecated ArtifactLocation
  sdk/python/kfp/dsl/_artifact_location.py
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/tests/compiler/testdata/artifact_location.py
  sdk/python/tests/compiler/testdata/artifact_location.yaml
Labels: approved, area/sdk/dsl, lgtm, size/M

#2068 Add external links that make some content easier to discover
  frontend/src/assets.d.ts
  frontend/src/atoms/ExternalLink.tsx
  frontend/src/components/Description.tsx
  frontend/src/components/Router.tsx
  frontend/src/components/SideNav.tsx
  frontend/src/components/UploadPipelineDialog.tsx
  frontend/src/components/__snapshots__/SideNav.test.tsx.snap
  frontend/src/components/__snapshots__/UploadPipelineDialog.test.tsx.snap
  frontend/src/icons/GitHub-Mark-120px-plus.png
Labels: approved, lgtm, size/L

#2552 Fix more notebook license issues
  components/third_party_licenses.csv
Labels: approved, kind/bug, lgtm, size/XS

#2554 [Testing] Describe unhealthy pods when tests clean up.
  test/deploy-cluster.sh
Labels: approved, area/testing, lgtm, size/S

#2553 Release d6d9d8da19f7110fff3a5ba713710402edaeee65
  components/gcp/bigquery/query/README.md
  components/gcp/bigquery/query/component.yaml
  components/gcp/bigquery/query/sample.ipynb
  components/gcp/dataflow/launch_python/README.md
  components/gcp/dataflow/launch_python/component.yaml
  components/gcp/dataflow/launch_python/sample.ipynb
  components/gcp/dataflow/launch_template/README.md
  components/gcp/dataflow/launch_template/component.yaml
  components/gcp/dataflow/launch_template/sample.ipynb
  components/gcp/dataproc/create_cluster/README.md
  components/gcp/dataproc/create_cluster/component.yaml
  components/gcp/dataproc/create_cluster/sample.ipynb
  components/gcp/dataproc/delete_cluster/README.md
  components/gcp/dataproc/delete_cluster/component.yaml
  components/gcp/dataproc/delete_cluster/sample.ipynb
  components/gcp/dataproc/submit_hadoop_job/README.md
  components/gcp/dataproc/submit_hadoop_job/component.yaml
  components/gcp/dataproc/submit_hadoop_job/sample.ipynb
  components/gcp/dataproc/submit_hive_job/README.md
  components/gcp/dataproc/submit_hive_job/component.yaml
  components/gcp/dataproc/submit_hive_job/sample.ipynb
  components/gcp/dataproc/submit_pig_job/README.md
  components/gcp/dataproc/submit_pig_job/component.yaml
  components/gcp/dataproc/submit_pig_job/sample.ipynb
  components/gcp/dataproc/submit_pyspark_job/README.md
  components/gcp/dataproc/submit_pyspark_job/component.yaml
  components/gcp/dataproc/submit_pyspark_job/sample.ipynb
  components/gcp/dataproc/submit_spark_job/README.md
  components/gcp/dataproc/submit_spark_job/component.yaml
  components/gcp/dataproc/submit_spark_job/sample.ipynb
  components/gcp/dataproc/submit_sparksql_job/README.md
  components/gcp/dataproc/submit_sparksql_job/component.yaml
  components/gcp/dataproc/submit_sparksql_job/sample.ipynb
  components/gcp/ml_engine/batch_predict/README.md
  components/gcp/ml_engine/batch_predict/component.yaml
  components/gcp/ml_engine/batch_predict/sample.ipynb
  components/gcp/ml_engine/deploy/README.md
  components/gcp/ml_engine/deploy/component.yaml
  components/gcp/ml_engine/deploy/sample.ipynb
  components/gcp/ml_engine/train/README.md
  components/gcp/ml_engine/train/component.yaml
  components/gcp/ml_engine/train/sample.ipynb
  components/kubeflow/deployer/component.yaml
  components/kubeflow/dnntrainer/component.yaml
  components/kubeflow/launcher/kubeflow_tfjob_launcher_op.py
  components/kubeflow/launcher/src/train.template.yaml
  components/local/confusion_matrix/component.yaml
  components/local/roc/component.yaml
  samples/core/ai_platform/ai_platform.ipynb
  samples/core/dataflow/dataflow.ipynb
  samples/core/kubeflow_tf_serving/kubeflow_tf_serving.ipynb
  samples/core/xgboost_training_cm/xgboost_training_cm.py
Labels: approved, lgtm, size/L

#2551 Fix wrong kfserving url
  components/kubeflow/kfserving/src/kfservingdeployer.py
Labels: approved, lgtm, size/XS

#2557 Fix postsubmit test which times out
  test/component_test.yaml
Labels: approved, area/testing, kind/bug, lgtm, size/XS

#2565 Increase kfp version in component sdk
  components/gcp/container/component_sdk/python/setup.py
Labels: approved, lgtm, size/XS

#2563 Fixes test flakiness caused by "unsupported operand type(s) for -=: 'Retry' and 'int'"
  test/sample-test/Dockerfile
Labels: approved, area/testing, kind/bug, lgtm, size/XS

#2566 Fix inverse proxy agent in e2e tests
  test/cloudbuild/batch_build.yaml
Labels: approved, area/testing, kind/bug, lgtm, size/XS

#2568 Fix inverse-proxy test cloudbuild yaml
  test/cloudbuild/batch_build.yaml
Labels: approved, area/testing, kind/bug, lgtm, size/XS

#2497 Set DB GroupConcatMaxLen config to default of 4MB
  backend/src/apiserver/client/sql.go
  backend/src/apiserver/client_manager.go
  backend/src/apiserver/config/config.json
Labels: approved, lgtm, ok-to-test, size/S

#2567 Increase kfp version in kustomize and sdk init
  manifests/kustomize/base/kustomization.yaml
  sdk/python/kfp/__init__.py
Labels: approved, lgtm, size/S

#2529 SDK - Components - Fixed YAML formatting for some components
  sdk/python/kfp/components/_python_op.py
Labels: approved, area/sdk/components, lgtm, size/XS

#2550 MDez patch 1
  backend/api/experiment.proto
  backend/api/job.proto
  backend/api/pipeline.proto
  backend/api/run.proto
Labels: approved, lgtm, ok-to-test, size/S

#2255 SDK - Containers - Getting rid of _get_default_image_builder
  sdk/python/kfp/containers/_build_image_api.py
Labels: approved, lgtm, sdk/containers, size/S

#2261 SDK - Containers - Renamed constructor parameter in the private ContainerBuilder class
  sdk/python/kfp/containers/_container_builder.py
  sdk/python/tests/compiler/container_builder_test.py
Labels: approved, lgtm, sdk/containers, size/S

#2081 [pipeline-ui] Retrieve pod logs from argo archive
  frontend/server/aws-helper.ts
  frontend/server/k8s-helper.ts
  frontend/server/minio-helper.ts
  frontend/server/package-lock.json
  frontend/server/package.json
  frontend/server/server.ts
  frontend/server/workflow-helper.ts
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-ui-role.yaml
Labels: approved, area/front-end, lgtm, ok-to-test, size/XL

#2507 Add arm64 support for ml-pipeline
  backend/Dockerfile
  backend/Dockerfile.bazel
  backend/build_api_server.sh
  developer_guide.md
  frontend/Dockerfile
Labels: approved, lgtm, ok-to-test, size/L

#2532 Components - Google Cloud Storage
  components/google-cloud/storage/download/component.yaml
  components/google-cloud/storage/download_blob/component.yaml
  components/google-cloud/storage/download_dir/component.yaml
  components/google-cloud/storage/list/component.yaml
  components/google-cloud/storage/upload_to_explicit_uri/component.yaml
  components/google-cloud/storage/upload_to_unique_uri/component.yaml
  release/RELEASE.md
Labels: approved, area/components, lgtm, size/L

#2572 [SDK] Fix withItem loop
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/dsl/_for_loop.py
Labels: approved, lgtm, size/S

#2580 [UI] Fix firefox compatibility
  frontend/src/lib/Apis.ts
Labels: approved, area/front-end, kind/bug, lgtm, size/M

#2576 [Doc] Minor fix to MKP secret setup guide
  manifests/gcp_marketplace/guide.md
Labels: approved, lgtm, size/XS

#2583 Add a minimum sample to print hello world
  samples/core/helloworld/hello_world.py
Labels: approved, lgtm, size/M

#2586 0.1.34 changelog
  CHANGELOG.md
Labels: approved, lgtm, size/S

#2587 [UI] Simplify firefox fix in pull/2580
  frontend/src/lib/Apis.ts
Labels: approved, area/front-end, kind/code-quality, lgtm, size/M

#2584 Fix missing run and pipeline id when buttons are clicked before content load
  frontend/mock-backend/mock-api-middleware.ts
  frontend/src/pages/PipelineDetails.test.tsx
  frontend/src/pages/PipelineDetails.tsx
  frontend/src/pages/RunDetails.test.tsx
  frontend/src/pages/RunDetails.tsx
Labels: approved, lgtm, ok-to-test, size/L

#2559 fix slow query when get runs
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/storage/run_store.go
Labels: approved, lgtm, ok-to-test, size/M

#2594 [Sample] Lint and clean up parameterized TFX sample
  samples/contrib/parameterized_tfx_oss/parameterized_tfx_oss.py
Labels: approved, lgtm, size/M

#669 SDK/Components - Added Json Schema spec for the component format
  sdk/python/kfp/components/structures/components.json_schema.json
  sdk/python/kfp/components/structures/components.json_schema.outline.yaml
Labels: approved, lgtm, size/L

#2592 Fix transformer sample message
  samples/core/pipeline_transformers/pipeline_transformers.py
Labels: approved, lgtm, size/XS

#2599 Release 9670cc1aadfbbed9c52b84ea859ea97aa81213ad
  components/gcp/bigquery/query/README.md
  components/gcp/bigquery/query/component.yaml
  components/gcp/bigquery/query/sample.ipynb
  components/gcp/dataflow/launch_python/README.md
  components/gcp/dataflow/launch_python/component.yaml
  components/gcp/dataflow/launch_python/sample.ipynb
  components/gcp/dataflow/launch_template/README.md
  components/gcp/dataflow/launch_template/component.yaml
  components/gcp/dataflow/launch_template/sample.ipynb
  components/gcp/dataproc/create_cluster/README.md
  components/gcp/dataproc/create_cluster/component.yaml
  components/gcp/dataproc/create_cluster/sample.ipynb
  components/gcp/dataproc/delete_cluster/README.md
  components/gcp/dataproc/delete_cluster/component.yaml
  components/gcp/dataproc/delete_cluster/sample.ipynb
  components/gcp/dataproc/submit_hadoop_job/README.md
  components/gcp/dataproc/submit_hadoop_job/component.yaml
  components/gcp/dataproc/submit_hadoop_job/sample.ipynb
  components/gcp/dataproc/submit_hive_job/README.md
  components/gcp/dataproc/submit_hive_job/component.yaml
  components/gcp/dataproc/submit_hive_job/sample.ipynb
  components/gcp/dataproc/submit_pig_job/README.md
  components/gcp/dataproc/submit_pig_job/component.yaml
  components/gcp/dataproc/submit_pig_job/sample.ipynb
  components/gcp/dataproc/submit_pyspark_job/README.md
  components/gcp/dataproc/submit_pyspark_job/component.yaml
  components/gcp/dataproc/submit_pyspark_job/sample.ipynb
  components/gcp/dataproc/submit_spark_job/README.md
  components/gcp/dataproc/submit_spark_job/component.yaml
  components/gcp/dataproc/submit_spark_job/sample.ipynb
  components/gcp/dataproc/submit_sparksql_job/README.md
  components/gcp/dataproc/submit_sparksql_job/component.yaml
  components/gcp/dataproc/submit_sparksql_job/sample.ipynb
  components/gcp/ml_engine/batch_predict/README.md
  components/gcp/ml_engine/batch_predict/component.yaml
  components/gcp/ml_engine/batch_predict/sample.ipynb
  components/gcp/ml_engine/deploy/README.md
  components/gcp/ml_engine/deploy/component.yaml
  components/gcp/ml_engine/deploy/sample.ipynb
  components/gcp/ml_engine/train/README.md
  components/gcp/ml_engine/train/component.yaml
  components/gcp/ml_engine/train/sample.ipynb
  components/kubeflow/deployer/component.yaml
  components/kubeflow/dnntrainer/component.yaml
  components/kubeflow/launcher/kubeflow_tfjob_launcher_op.py
  components/kubeflow/launcher/src/train.template.yaml
  components/local/confusion_matrix/component.yaml
  components/local/roc/component.yaml
  samples/core/ai_platform/ai_platform.ipynb
  samples/core/dataflow/dataflow.ipynb
  samples/core/kubeflow_tf_serving/kubeflow_tf_serving.ipynb
  samples/core/xgboost_training_cm/xgboost_training_cm.py
Labels: approved, lgtm, size/L

#2598 Bump version to 0.1.35
  components/gcp/container/component_sdk/python/setup.py
  manifests/kustomize/base/kustomization.yaml
  sdk/python/kfp/__init__.py
Labels: approved, lgtm, size/S

#2600 Add Bobgy to OWNERS of kustomize manifests
  manifests/kustomize/OWNERS
Labels: approved, lgtm, size/XS

#2577 Katib experiment launcher
  components/kubeflow/katib-launcher/Dockerfile
  components/kubeflow/katib-launcher/build_image.sh
  components/kubeflow/katib-launcher/component.yaml
  components/kubeflow/katib-launcher/kubeflow_katib_launcher_op.py
  components/kubeflow/katib-launcher/sample.py
  components/kubeflow/katib-launcher/sample2.py
  components/kubeflow/katib-launcher/src/__init__.py
  components/kubeflow/katib-launcher/src/hp.template.yaml
  components/kubeflow/katib-launcher/src/launch_crd.py
  components/kubeflow/katib-launcher/src/launch_experiment.py
  components/kubeflow/katib-launcher/src/launch_study_job.py
Labels: approved, lgtm, size/XL

#2611 Fix a few bugs in delete pipeline version that are discovered in integration test
  backend/src/apiserver/storage/pipeline_store.go
Labels: approved, lgtm, size/XS

#2608 Changelog of 0.1.35 release
  CHANGELOG.md
Labels: approved, lgtm, size/S

#2610 Adding missing kfp.cli.diagnose_me package to setup.py Fixes #2609
  sdk/python/setup.py
Labels: approved, lgtm, needs-ok-to-test, size/XS

#2616 casting job_config to QueryJobConfig if supplied by user
  components/gcp/container/component_sdk/python/kfp_component/google/bigquery/_query.py
Labels: approved, lgtm, ok-to-test, size/XS

#2614 Enable inverse proxy to access host network
  manifests/kustomize/base/proxy/proxy-deployment.yaml
Labels: approved, lgtm, size/XS

#2544 Add a new field "TensorflowImage" to KFP viewer CRD file template.
  backend/src/crd/controller/viewer/reconciler/reconciler.go
  backend/src/crd/controller/viewer/reconciler/reconciler_test.go
  backend/src/crd/pkg/apis/viewer/v1beta1/types.go
  frontend/server/k8s-helper.ts
  manifests/kustomize/env/dev/kustomization.yaml
Labels: approved, lgtm, size/M

#2613 add community meeting/slack onto README
  README.md
Labels: approved, lgtm, size/S

#2618 Modernize samples/core/tfx-oss Notebook
  samples/core/tfx-oss/TFX Example.ipynb
Labels: approved, lgtm, ok-to-test, size/L

#2591 [fix] default yaml.dump to block style
  sdk/python/kfp/compiler/compiler.py
Labels: approved, lgtm, ok-to-test, size/XS

#2622 [UI] Separate page state for each page instance
  frontend/src/components/Router.test.tsx
  frontend/src/components/Router.tsx
  frontend/src/components/Toolbar.tsx
  frontend/src/components/__snapshots__/Router.test.tsx.snap
  frontend/src/components/__snapshots__/Toolbar.test.tsx.snap
  frontend/src/index.tsx
  frontend/tslint.json
Labels: approved, area/frontend, kind/bug, lgtm, size/XL

#2597 Fix error tfjob definition
  samples/contrib/seldon/mnist_tf.py
  samples/contrib/seldon/mnist_tf_volume.py
Labels: approved, lgtm, size/XS

#2630 [UI] Trim pipeline upload url before sending to backend
  frontend/src/components/UploadPipelineDialog.test.tsx
  frontend/src/components/UploadPipelineDialog.tsx
Labels: approved, area/frontend, kind/feature, lgtm, size/S

#2635 MDez patch 2
  backend/api/experiment.proto
  backend/api/job.proto
  backend/api/pipeline.proto
  backend/api/run.proto
Labels: approved, lgtm, needs-ok-to-test, size/M

#2636 SDK - Protobuf version of the component schema
  sdk/python/kfp/components/structures/components.proto
  sdk/python/kfp/components/structures/generate_proto_code.sh
Labels: approved, area/sdk/components, lgtm, size/L

#2626 Add support for user account auth with IAP
  sdk/python/kfp/_auth.py
  sdk/python/kfp/_client.py
  sdk/python/kfp/cli/cli.py
Labels: approved, lgtm, size/M

#2637 Move frontend unit tests to prow
  frontend/package-lock.json
  frontend/package.json
  frontend/scripts/get-coveralls-repo-token.js
  frontend/scripts/report-coveralls.sh
Labels: approved, area/frontend, area/testing, lgtm, priority/p0, size/XL

#2648 api resource type conversion needs to convert pipeline version type
  backend/src/apiserver/server/api_converter.go
  backend/src/apiserver/server/api_converter_test.go
Labels: approved, lgtm, size/XS

#2631 Frontend server: add feature flag for kubeflow deployment
  frontend/public/index.html
  frontend/server/server.ts
Labels: approved, lgtm, size/M

#2656 Mkp better release - SemVersion
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/minio.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/mysql.yaml
  manifests/gcp_marketplace/cli.md
  manifests/gcp_marketplace/schema.yaml
Labels: approved, lgtm, size/M

#2634 [SDK] Relax k8s sanitization
  samples/core/loop_static/loop_static.py
  samples/core/volume_ops/volume_ops.py
  sdk/python/kfp/_client.py
  sdk/python/kfp/compiler/_k8s_helper.py
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/dsl/_pipeline_param.py
  sdk/python/tests/compiler/testdata/pipelineparams.yaml
  sdk/python/tests/compiler/testdata/recursive_while.yaml
  sdk/python/tests/compiler/testdata/volume_snapshotop_rokurl.yaml
  sdk/python/tests/compiler/testdata/withitem_basic.yaml
  sdk/python/tests/compiler/testdata/withitem_nested.yaml
  sdk/python/tests/compiler/testdata/withparam_global.yaml
  sdk/python/tests/compiler/testdata/withparam_global_dict.yaml
  test/sample-test/configs/xgboost_training_cm.config.yaml
Labels: approved, lgtm, size/L

#2646 SDK - Client - Fixed client on Windows
  sdk/python/kfp/_auth.py
Labels: approved, area/sdk/client, lgtm, size/XS

#2660 Release 9ad7d7dd9776ce75a83712f5723db2ef93ba5c26
  components/gcp/bigquery/query/README.md
  components/gcp/bigquery/query/component.yaml
  components/gcp/bigquery/query/sample.ipynb
  components/gcp/container/component_sdk/python/setup.py
  components/gcp/dataflow/launch_python/README.md
  components/gcp/dataflow/launch_python/component.yaml
  components/gcp/dataflow/launch_python/sample.ipynb
  components/gcp/dataflow/launch_template/README.md
  components/gcp/dataflow/launch_template/component.yaml
  components/gcp/dataflow/launch_template/sample.ipynb
  components/gcp/dataproc/create_cluster/README.md
  components/gcp/dataproc/create_cluster/component.yaml
  components/gcp/dataproc/create_cluster/sample.ipynb
  components/gcp/dataproc/delete_cluster/README.md
  components/gcp/dataproc/delete_cluster/component.yaml
  components/gcp/dataproc/delete_cluster/sample.ipynb
  components/gcp/dataproc/submit_hadoop_job/README.md
  components/gcp/dataproc/submit_hadoop_job/component.yaml
  components/gcp/dataproc/submit_hadoop_job/sample.ipynb
  components/gcp/dataproc/submit_hive_job/README.md
  components/gcp/dataproc/submit_hive_job/component.yaml
  components/gcp/dataproc/submit_hive_job/sample.ipynb
  components/gcp/dataproc/submit_pig_job/README.md
  components/gcp/dataproc/submit_pig_job/component.yaml
  components/gcp/dataproc/submit_pig_job/sample.ipynb
  components/gcp/dataproc/submit_pyspark_job/README.md
  components/gcp/dataproc/submit_pyspark_job/component.yaml
  components/gcp/dataproc/submit_pyspark_job/sample.ipynb
  components/gcp/dataproc/submit_spark_job/README.md
  components/gcp/dataproc/submit_spark_job/component.yaml
  components/gcp/dataproc/submit_spark_job/sample.ipynb
  components/gcp/dataproc/submit_sparksql_job/README.md
  components/gcp/dataproc/submit_sparksql_job/component.yaml
  components/gcp/dataproc/submit_sparksql_job/sample.ipynb
  components/gcp/ml_engine/batch_predict/README.md
  components/gcp/ml_engine/batch_predict/component.yaml
  components/gcp/ml_engine/batch_predict/sample.ipynb
  components/gcp/ml_engine/deploy/README.md
  components/gcp/ml_engine/deploy/component.yaml
  components/gcp/ml_engine/deploy/sample.ipynb
  components/gcp/ml_engine/train/README.md
  components/gcp/ml_engine/train/component.yaml
  components/gcp/ml_engine/train/sample.ipynb
  components/kubeflow/deployer/component.yaml
  components/kubeflow/dnntrainer/component.yaml
  components/kubeflow/launcher/kubeflow_tfjob_launcher_op.py
  components/kubeflow/launcher/src/train.template.yaml
  components/local/confusion_matrix/component.yaml
  components/local/roc/component.yaml
  samples/core/ai_platform/ai_platform.ipynb
  samples/core/dataflow/dataflow.ipynb
  samples/core/kubeflow_tf_serving/kubeflow_tf_serving.ipynb
  samples/core/xgboost_training_cm/xgboost_training_cm.py
Labels: approved, lgtm, size/L

#2661 Bump version to 0.1.36
  manifests/kustomize/base/kustomization.yaml
  sdk/python/kfp/__init__.py
Labels: approved, lgtm, size/S

#2666 [Release] update changelog
  CHANGELOG.md
Labels: approved, lgtm, size/XXL

#2647 Remove travis CI frontend tests
  .travis.yml
Labels: approved, area/frontend, area/testing, lgtm, size/S

#2620 Open version api in BE proto and auto-generate BE/FE api methods
  backend/api/go_client/pipeline.pb.go
  backend/api/go_client/pipeline.pb.gw.go
  backend/api/go_http_client/experiment_client/experiment_service/create_experiment_parameters.go
  backend/api/go_http_client/experiment_client/experiment_service/experiment_service_client.go
  backend/api/go_http_client/experiment_client/experiment_service/get_experiment_parameters.go
  backend/api/go_http_client/experiment_client/experiment_service/list_experiment_parameters.go
  backend/api/go_http_client/job_client/job_service/job_service_client.go
  backend/api/go_http_client/job_client/job_service/list_jobs_parameters.go
  backend/api/go_http_client/job_model/api_job.go--
  backend/api/go_http_client/job_model/api_periodic_schedule.go--
  backend/api/go_http_client/pipeline_client/pipeline_service/BUILD.bazel
  backend/api/go_http_client/pipeline_client/pipeline_service/create_pipeline_version_parameters.go
  backend/api/go_http_client/pipeline_client/pipeline_service/create_pipeline_version_responses.go
  backend/api/go_http_client/pipeline_client/pipeline_service/delete_pipeline_version_parameters.go
  backend/api/go_http_client/pipeline_client/pipeline_service/delete_pipeline_version_responses.go
  backend/api/go_http_client/pipeline_client/pipeline_service/get_pipeline_version_parameters.go
  backend/api/go_http_client/pipeline_client/pipeline_service/get_pipeline_version_responses.go
  backend/api/go_http_client/pipeline_client/pipeline_service/get_pipeline_version_template_parameters.go
  backend/api/go_http_client/pipeline_client/pipeline_service/get_pipeline_version_template_responses.go
  backend/api/go_http_client/pipeline_client/pipeline_service/list_pipeline_versions_parameters.go
  backend/api/go_http_client/pipeline_client/pipeline_service/list_pipeline_versions_responses.go
  backend/api/go_http_client/pipeline_client/pipeline_service/list_pipelines_parameters.go
  backend/api/go_http_client/pipeline_client/pipeline_service/pipeline_service_client.go
  backend/api/go_http_client/run_client/run_service/list_runs_parameters.go
  backend/api/go_http_client/run_client/run_service/run_service_client.go
  backend/api/pipeline.proto
  backend/api/swagger/experiment.swagger.json
  backend/api/swagger/job.swagger.json
  backend/api/swagger/kfp_api_single_file.swagger.json
  backend/api/swagger/pipeline.swagger.json
  backend/api/swagger/run.swagger.json
  frontend/src/apis/experiment/api.ts
  frontend/src/apis/job/api.ts
  frontend/src/apis/pipeline/api.ts
  frontend/src/apis/run/api.ts
Labels: approved, lgtm, size/XXL

#2658 Components - Git clone
  components/git/clone/component.yaml
Labels: approved, area/components, lgtm, size/S

#2659 Components - Filesystem
  components/filesystem/get_file/component.yaml
  components/filesystem/get_subdirectory/component.yaml
  components/filesystem/list_items/component.yaml
Labels: approved, area/components, lgtm, size/M

#2645 Frontend - Add support for Minio artifact URIs
  frontend/src/components/ArtifactLink.tsx
  frontend/src/lib/Utils.test.ts
  frontend/src/lib/Utils.tsx
Labels: approved, area/frontend, lgtm, size/M

#2672 Configure jest to hide noisy message about no coverage data on .d.ts files
  frontend/package.json
Labels: approved, area/frontend, area/testing, kind/bug, lgtm, size/XS

#2673 Add readable step id for test cloudbuild steps
  test/cloudbuild/api_server.yaml
  test/cloudbuild/batch_build.yaml
Labels: approved, area/testing, lgtm, size/XS

#2655 [UI] Get kubeflow namespace from kfp UI
  frontend/public/index.html
  frontend/server/server.ts
  frontend/src/index.tsx
  frontend/src/lib/Flags.ts
  frontend/src/lib/KubeflowClient.tsx
  frontend/tslint.json
Labels: approved, area/frontend, lgtm, size/L
