Repository kubeflow/pipelines, pull requests merged in 2020-10, with the labels that each got.

#4566 feat(sdk): Support to print the cli command output in json format
  sdk/python/kfp/cli/cli.py
  sdk/python/kfp/cli/experiment.py
  sdk/python/kfp/cli/output.py
  sdk/python/kfp/cli/pipeline.py
  sdk/python/kfp/cli/run.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#4590 fix(samples): Updated and fixed the secrets sample
  samples/core/secret/secret.py
Labels: approved, area/samples, cla: yes, lgtm, size/M

#4583 fix(components): use default python version for launching dataflow jobs. Fixes #2601
  components/gcp/container/component_sdk/python/kfp_component/google/dataflow/_launch_python.py
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#4585 test: Fixed the sample test
  samples/core/lightweight_component/lightweight_component.ipynb
Labels: approved, area/samples, area/testing, cla: yes, lgtm, size/XS

#4570 fix(sdk): use a meaningful link text in ipython
  sdk/python/kfp/_client.py
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#4577 feat(sdk): Added optional argument to specify description for pipeline upload
  sdk/python/kfp/cli/pipeline.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#4594 update kfp installation instructions for a number of gcp components
  components/gcp/bigquery/query/sample.ipynb
  components/gcp/bigquery/query/to_CSV/README.md
  components/gcp/bigquery/query/to_gcs/README.md
  components/gcp/bigquery/query/to_table/README.md
  components/gcp/dataflow/launch_python/README.md
  components/gcp/dataflow/launch_python/sample.ipynb
  components/gcp/dataflow/launch_template/README.md
  components/gcp/dataflow/launch_template/sample.ipynb
  components/gcp/dataproc/create_cluster/README.md
  components/gcp/dataproc/create_cluster/sample.ipynb
  components/gcp/dataproc/delete_cluster/README.md
  components/gcp/dataproc/delete_cluster/sample.ipynb
  components/gcp/dataproc/submit_hadoop_job/README.md
  components/gcp/dataproc/submit_hadoop_job/sample.ipynb
  components/gcp/dataproc/submit_hive_job/README.md
  components/gcp/dataproc/submit_hive_job/sample.ipynb
  components/gcp/dataproc/submit_pig_job/README.md
  components/gcp/dataproc/submit_pig_job/sample.ipynb
  components/gcp/dataproc/submit_pyspark_job/README.md
  components/gcp/dataproc/submit_pyspark_job/sample.ipynb
  components/gcp/dataproc/submit_spark_job/README.md
  components/gcp/dataproc/submit_spark_job/sample.ipynb
  components/gcp/dataproc/submit_sparksql_job/README.md
  components/gcp/dataproc/submit_sparksql_job/sample.ipynb
  components/gcp/ml_engine/batch_predict/README.md
  components/gcp/ml_engine/batch_predict/sample.ipynb
  components/gcp/ml_engine/deploy/README.md
  components/gcp/ml_engine/deploy/sample.ipynb
  components/gcp/ml_engine/train/README.md
  components/gcp/ml_engine/train/sample.ipynb
Labels: approved, cla: yes, lgtm, size/M

#4587 feat(components): Add yaml support to kfserving component
  components/kubeflow/kfserving/component.yaml
  components/kubeflow/kfserving/src/app.py
  components/kubeflow/kfserving/src/kfservingdeployer.py
Labels: approved, cla: yes, lgtm, size/L

#4595 chore(components): SageMaker integ tests, fix for unbound variable
  components/aws/sagemaker/tests/integration_tests/component_tests/test_groundtruth_component.py
Labels: approved, cla: yes, lgtm, size/M

#4597 feat(sdk): Components - Added Bool as a known type name
  sdk/python/kfp/components/_data_passing.py
Labels: approved, area/sdk/components, cla: yes, lgtm, size/XS

#4593 fix(components): fix ml_engine/train interface
  components/gcp/container/component_sdk/python/kfp_component/google/ml_engine/_train.py
  components/gcp/container/component_sdk/python/tests/google/ml_engine/test__train.py
Labels: approved, cla: yes, lgtm, size/L

#4603 chore(components): SageMaker integ test changes
  components/aws/sagemaker/tests/integration_tests/component_tests/test_groundtruth_component.py
  components/aws/sagemaker/tests/integration_tests/component_tests/test_model_component.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#4509 sample azure components
  components/azure/OWNERS
  components/azure/azuredevops/queue-pipeline/Dockerfile
  components/azure/azuredevops/queue-pipeline/build_image.sh
  components/azure/azuredevops/queue-pipeline/component.yaml
  components/azure/azuredevops/queue-pipeline/readme.md
  components/azure/azuredevops/queue-pipeline/src/queue_pipeline.py
  components/azure/azuredevops/readme.md
  components/azure/azureml/aml-register-model/Dockerfile
  components/azure/azureml/aml-register-model/README.MD
  components/azure/azureml/aml-register-model/build.sh
  components/azure/azureml/aml-register-model/component.yaml
  components/azure/azureml/aml-register-model/requirements.txt
  components/azure/azureml/aml-register-model/src/register.py
Labels: approved, cla: yes, lgtm, size/L

#4605 chore: update @kubeflow/frontend to include MLMD client upgrade to 0.22.1
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
Labels: approved, cla: yes, lgtm, size/XS

#4604 feat(sdk): Adds missing short options to the cli
  sdk/python/kfp/cli/experiment.py
  sdk/python/kfp/cli/pipeline.py
  sdk/python/kfp/cli/run.py
Labels: approved, cherrypick-approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#4606 build: update proxy agent to fix CVE vulnerabilities. Fixes #4531
  proxy/Dockerfile
Labels: approved, cherrypick-approved, cla: yes, lgtm, size/XS

#4563 feat(sdk): Preserve parameter arguments and input names
  sdk/python/kfp/compiler/_op_to_template.py
  sdk/python/kfp/dsl/_component_bridge.py
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/tests/compiler/compiler_tests.py
Labels: approved, area/sdk, area/sdk/dsl, area/sdk/dsl/compiler, cherrypick-approved, cla: yes, lgtm, size/M

#4609 fix(doc): Use Managed NodeGroup for EKS Cluster
  manifests/kustomize/env/aws/README.md
Labels: approved, cla: yes, lgtm, size/M

#4567 feat(deployment): Kustomize manifest for Azure deployments
  manifests/kustomize/env/azure/OWNERS
  manifests/kustomize/env/azure/kustomization.yaml
  manifests/kustomize/env/azure/minio-azure-gateway/kustomization.yaml
  manifests/kustomize/env/azure/minio-azure-gateway/minio-artifact-secret.env
  manifests/kustomize/env/azure/minio-azure-gateway/minio-azure-gateway-deployment.yaml
  manifests/kustomize/env/azure/minio-azure-gateway/minio-azure-gateway-service.yaml
  manifests/kustomize/env/azure/mysql-secret.env
  manifests/kustomize/env/azure/params.env
  manifests/kustomize/env/azure/readme.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/L

#4578 feat(components): Added the Run notebook using papermill component. Fixes #497
  components/notebooks/Run_notebook_using_papermill/component.yaml
  components/notebooks/samples/sample_pipeline.py
  components/notebooks/samples/test_notebook.ipynb
Labels: approved, area/components, cla: yes, lgtm, size/L

#4601 feat(components): Added JSON query components
  components/json/Get_element_by_index/component.yaml
  components/json/Get_element_by_key/component.yaml
  components/json/Query/component.yaml
Labels: approved, area/components, cla: yes, lgtm, size/M

#4613 fix(sdk): Components - Fixed ModelBase handling of open generic types in Python 3.9
  sdk/python/kfp/components/modelbase.py
  sdk/python/kfp/components_tests/test_structure_model_base.py
Labels: approved, area/sdk/components, cla: yes, lgtm, size/M

#4615 test(sdk): Components - Tests - Made python component tests use the same python executable to run the components
  sdk/python/kfp/components_tests/test_python_op.py
Labels: approved, area/sdk/components, cla: yes, lgtm, size/S

#4608 chore(sdk): Components - Simplified graph component child task resolving
  sdk/python/kfp/components/_components.py
Labels: approved, area/sdk/components, cla: yes, lgtm, size/M

#4619 Update IR ExecutorOutput message to use ArtifactList for artifacts field.
  api/v2alpha1/pipeline_spec.proto
  sdk/python/kfp/v2/proto/pipeline_spec_pb2.py
Labels: approved, cla: yes, lgtm, size/M

#4621 feat(components): Added the Google Cloud Optimizer components
  components/google-cloud/Optimizer/Add_measurement_for_trial/component.py
  components/google-cloud/Optimizer/Add_measurement_for_trial/component.yaml
  components/google-cloud/Optimizer/Create_study/component.py
  components/google-cloud/Optimizer/Create_study/component.yaml
  components/google-cloud/Optimizer/Suggest_trials/component.py
  components/google-cloud/Optimizer/Suggest_trials/component.yaml
  components/google-cloud/Optimizer/_samples/multi_stage_optimization_pipeline.py
Labels: approved, area/components, cla: yes, lgtm, size/XL

#4623 doc(release): drop python 3.5 support. Part of #4584
  RELEASE.md
Labels: approved, cla: yes, lgtm, size/XS

#4529 compiler for IR
  sdk/python/kfp/components/_components.py
  sdk/python/kfp/v2/__init__.py
  sdk/python/kfp/v2/compiler/__init__.py
  sdk/python/kfp/v2/compiler/compiler.py
  sdk/python/kfp/v2/compiler/compiler_test.py
  sdk/python/kfp/v2/compiler/importer_node.py
  sdk/python/kfp/v2/compiler/importer_node_test.py
  sdk/python/kfp/v2/compiler/main.py
  sdk/python/kfp/v2/compiler_cli_tests/__init__.py
  sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/component_yaml/serving_component.yaml
  sdk/python/kfp/v2/compiler_cli_tests/test_data/component_yaml/trainer_component.yaml
  sdk/python/kfp/v2/compiler_cli_tests/test_data/simple_pipeline_without_importer.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/simple_pipeline_without_importer.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/two_step_pipeline_with_importer.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/two_step_pipeline_with_importer.py
  sdk/python/kfp/v2/dsl/__init__.py
  sdk/python/kfp/v2/dsl/_pipeline.py
  sdk/python/kfp/v2/dsl/component_bridge.py
  sdk/python/kfp/v2/dsl/type_utils.py
  sdk/python/kfp/v2/dsl/type_utils_test.py
  sdk/python/setup.py
  sdk/python/tests/compiler/main.py
  test/presubmit-tests-sdk.sh
Labels: approved, cla: yes, lgtm, size/XXL

#4625 SDK - Restored module decoupling
  sdk/python/kfp/components/_components.py
  sdk/python/kfp/v2/dsl/component_bridge.py
Labels: approved, area/sdk/components, cla: yes, lgtm, size/S

#4406 feat(API): exposing api for setting the default version of pipeline. Fixes #4049
  backend/api/go_client/pipeline.pb.go
  backend/api/go_client/pipeline.pb.gw.go
  backend/api/go_http_client/pipeline_client/pipeline_service/BUILD.bazel
  backend/api/go_http_client/pipeline_client/pipeline_service/pipeline_service_client.go
  backend/api/go_http_client/pipeline_client/pipeline_service/update_pipeline_default_version_parameters.go
  backend/api/go_http_client/pipeline_client/pipeline_service/update_pipeline_default_version_responses.go
  backend/api/pipeline.proto
  backend/api/swagger/kfp_api_single_file.swagger.json
  backend/api/swagger/pipeline.swagger.json
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/server/pipeline_server.go
  backend/src/common/client/api_server/pipeline_client.go
  backend/src/common/client/api_server/pipeline_client_fake.go
  backend/test/integration/pipeline_version_api_test.go
Labels: approved, cla: yes, lgtm, size/XL

#4180 fix(frontend): fix parsing large workflow graph. Fixes #4179
  frontend/mock-backend/fixed-data.ts
  frontend/mock-backend/large-graph-runtime.ts
  frontend/src/lib/Utils.test.ts
  frontend/src/lib/Utils.tsx
  frontend/src/pages/RunDetails.test.tsx
  frontend/src/pages/RunDetails.tsx
Labels: approved, cherrypick-approved, cla: yes, lgtm, ok-to-test, size/XXL

#4614 fix(sdk): Components - Fixed handling of typing.NamedTuple in Python 3.9
  sdk/python/kfp/components/_python_op.py
Labels: approved, area/sdk/components, cla: yes, lgtm, size/XS

#4476 feat(backend): allow configuring if default version should be updated when uploading new pipeline version. Fixes #4049
  backend/src/apiserver/common/config.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/resource/resource_manager_util_test.go
  backend/src/apiserver/server/pipeline_server.go
  backend/src/apiserver/server/pipeline_server_test.go
  backend/src/apiserver/server/pipeline_upload_server.go
  backend/src/apiserver/server/pipeline_upload_server_test.go
  backend/src/apiserver/server/test_util.go
  backend/src/apiserver/storage/pipeline_store.go
  backend/src/apiserver/storage/pipeline_store_test.go
  manifests/kustomize/base/params.env
  manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
Labels: approved, cla: yes, lgtm, size/L

#4633 feat(components): Google Cloud Optimizer - Added the "Suggest parameter sets from measurements" component
  components/google-cloud/Optimizer/Suggest_parameter_sets_based_on_measurements/component.py
  components/google-cloud/Optimizer/Suggest_parameter_sets_based_on_measurements/component.yaml
  components/google-cloud/Optimizer/_samples/multi_stage_optimization_atomic_pipeline.py
Labels: approved, area/components, area/samples, cla: yes, lgtm, size/XL

#4632 fix(backend): Caching - Fixed deployer failure on Kubernetes v1.16+. Fixes #4627
  backend/src/cache/deployer/cache-webhook-config.v1.yaml.template
  backend/src/cache/deployer/cache-webhook-config.v1beta1.v1.15.yaml.template
  backend/src/cache/deployer/cache-webhook-config.v1beta1.yaml.template
Labels: approved, area/execution_cache, cherrypick-approved, cla: yes, lgtm, size/XS

#4646 chore: Add more semantically expressive artifact ontology to IR compiler.
  sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/component_yaml/fancy_trainer_component.yaml
  sdk/python/kfp/v2/compiler_cli_tests/test_data/component_yaml/ingestion_component.yaml
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_ontology.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_ontology.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/simple_pipeline_without_importer.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/two_step_pipeline_with_importer.json
  sdk/python/kfp/v2/dsl/type_utils.py
  sdk/python/kfp/v2/dsl/type_utils_test.py
Labels: approved, cla: yes, lgtm, size/L

#4656 test: Updated base image version for sample tests. Fixes #4653
  test/sample-test/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#4626 test: use GCP cluster regular channel
  test/deploy-cluster.sh
Labels: approved, cla: yes, lgtm, size/XS

#4647 fix(components): Move output path as arguments for ibm components
  components/ibm-components/ffdl/serve/component.yaml
  components/ibm-components/ffdl/serve/src/serve.py
  components/ibm-components/ffdl/train/component.yaml
  components/ibm-components/ffdl/train/src/train.py
  components/ibm-components/spark/data_preprocess_spark/component.yaml
  components/ibm-components/spark/data_preprocess_spark/src/data_preprocess_spark.py
  components/ibm-components/spark/store_spark_model/component.yaml
  components/ibm-components/spark/store_spark_model/src/store_spark_model.py
  components/ibm-components/spark/train_spark/component.yaml
  components/ibm-components/spark/train_spark/src/train_spark.py
  components/ibm-components/watson/manage/subscribe/component.yaml
  components/ibm-components/watson/manage/subscribe/src/subscribe.py
Labels: approved, cla: yes, lgtm, size/M

#4634 test(sdk): Testing the component library
  test/presubmit-tests-sdk.sh
Labels: approved, area/testing, cla: yes, lgtm, size/XS

#4498 fix(backend): updated the argo version too 2.7.7. Fixes #4392
  backend/Dockerfile.cacheserver
  backend/Dockerfile.persistenceagent
  backend/Dockerfile.scheduledworkflow
  backend/src/agent/persistence/persistence_agent.go
  backend/src/apiserver/client/pod_fake.go
  backend/src/apiserver/resource/resource_manager_util.go
  backend/src/apiserver/resource/resource_manager_util_test.go
  backend/src/apiserver/server/experiment_server_test.go
  backend/src/apiserver/server/job_server_test.go
  backend/src/apiserver/server/run_server_test.go
  backend/src/cache/client/pod_fake.go
  backend/src/common/util/workflow_test.go
  backend/src/crd/controller/viewer/main.go
  backend/src/crd/controller/viewer/reconciler/reconciler.go
  backend/src/crd/controller/viewer/reconciler/reconciler_test.go
  backend/src/crd/pkg/apis/scheduledworkflow/v1beta1/zz_generated.deepcopy.go
  backend/src/crd/pkg/apis/viewer/v1beta1/zz_generated.deepcopy.go
  backend/src/crd/pkg/client/clientset/versioned/clientset.go
  backend/src/crd/pkg/client/clientset/versioned/fake/clientset_generated.go
  backend/src/crd/pkg/client/clientset/versioned/fake/register.go
  backend/src/crd/pkg/client/clientset/versioned/scheme/register.go
  backend/src/crd/pkg/client/clientset/versioned/typed/scheduledworkflow/v1beta1/fake/fake_scheduledworkflow.go
  backend/src/crd/pkg/client/clientset/versioned/typed/scheduledworkflow/v1beta1/scheduledworkflow.go
  backend/src/crd/pkg/client/clientset/versioned/typed/scheduledworkflow/v1beta1/scheduledworkflow_client.go
  backend/src/crd/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  go.mod
  go.sum
  test/api-integration-test/Dockerfile
  test/initialization-test/Dockerfile
  tools/tools.go
Labels: approved, area/backend, cla: yes, lgtm, size/XXL

#4658 fix(sdk): fixes dsl.ContainerOp deprecation warning not shown
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/tests/dsl/component_bridge_tests.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#4651 chore(sdk): Add test for concat placeholder
  sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/component_yaml/concat_placeholder_component.yaml
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_concat_placeholder.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_concat_placeholder.py
Labels: approved, cla: yes, lgtm, size/M

#4663 feat(frontend): Show full node names. Fixes #3989
  frontend/src/components/Graph.tsx
Labels: approved, area/frontend, cla: yes, lgtm, size/XS

#4648 chore(sdk): Support if placeholder in v2 compiler
  sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/component_yaml/if_placeholder_component.yaml
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_if_placeholder.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_if_placeholder.py
  sdk/python/kfp/v2/dsl/component_bridge.py
Labels: approved, cla: yes, lgtm, size/L

#4650 chore(sdk): Raises error on unsupported features in v2 compiler
  sdk/python/kfp/v2/compiler/compiler_test.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_ontology.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/simple_pipeline_without_importer.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/two_step_pipeline_with_importer.py
  sdk/python/kfp/v2/dsl/__init__.py
  sdk/python/kfp/v2/dsl/_component.py
  sdk/python/kfp/v2/dsl/_ops_group.py
Labels: approved, cla: yes, lgtm, size/L

#4670 fix(backend): Metadata Writer - Fixed setting execution custom properties
  backend/metadata_writer/src/metadata_helpers.py
Labels: approved, area/metadata-writer, cherrypick-approved, cla: yes, lgtm, size/S

#4672 fix(sdk): Fixed UI metadata and metrics
  sdk/python/kfp/compiler/_op_to_template.py
  sdk/python/kfp/dsl/_container_op.py
Labels: approved, area/sdk/dsl, area/sdk/dsl/compiler, cherrypick-approved, cla: yes, kind/bug, lgtm, size/XS

#4631 feat(components): JSON - Added the "Build dict", "Build list" and "Combine lists" components
  components/json/Build_dict/component.py
  components/json/Build_dict/component.yaml
  components/json/Build_list/component.py
  components/json/Build_list/component.yaml
  components/json/Combine_lists/component.py
  components/json/Combine_lists/component.yaml
Labels: approved, area/components, cla: yes, lgtm, size/L

#4669 chore: Support resource spec in v2 compiler
  api/v2alpha1/pipeline_spec.proto
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/kfp/v2/compiler/compiler.py
  sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_resource_spec.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_resource_spec.py
  sdk/python/kfp/v2/dsl/component_bridge.py
  sdk/python/kfp/v2/dsl/container_op.py
  sdk/python/kfp/v2/dsl/container_op_test.py
  sdk/python/kfp/v2/proto/pipeline_spec_pb2.py
Labels: approved, cla: yes, lgtm, size/XXL

#4564 feat(backend): Metadata Writer - Record parameter argument values to MLMD
  backend/metadata_writer/src/metadata_writer.py
Labels: approved, area/metadata-writer, cherrypick-approved, cla: yes, lgtm, size/S

#4679 chore(sdk): Allow arbitrary input/output types in v2 compiler
  sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_various_io_types.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_various_io_types.py
  sdk/python/kfp/v2/dsl/component_bridge.py
  sdk/python/kfp/v2/dsl/type_utils.py
  sdk/python/kfp/v2/dsl/type_utils_test.py
Labels: approved, cla: yes, lgtm, size/L

#4680 test: make details log url easier to select
  test/deploy-cluster.sh
Labels: approved, cla: yes, lgtm, size/XS

#4210 doc: versioning policy and feature stages docs. Part of #4533
  README.md
  docs/release/feature-stages.md
  docs/release/versioning-policy.md
  docs/releases/release-1.0.md
  docs/releases/versioning-policy.md
Labels: approved, cla: yes, lgtm, size/L

#4678 test(proxy): use inverse proxy staging env for presubmit tests. Part of #4667
  proxy/attempt-register-vm-on-proxy.sh
  test/manifests/dev/kustomization.yaml
  test/manifests/dev/proxy-agent-patch.yaml
  test/sample-test/README.md
  test/sample-test/check_notebook_results.py
  test/sample-test/requirements.in
  test/sample-test/run_sample_test.py
  test/sample-test/sample_test_launcher.py
Labels: approved, cla: yes, lgtm, size/M
