Repository kubeflow/pipelines, pull requests merged in 2020-07, with the labels that each got.

#4108 fix(component): Add new apply action to kfserving component
  components/kubeflow/kfserving/component.yaml
  components/kubeflow/kfserving/src/kfservingdeployer.py
Labels: approved, cla: yes, lgtm, size/S

#4111 chore: remove inactive reviewers
  backend/OWNERS
  components/OWNERS
  manifests/kustomize/OWNERS
  proxy/OWNERS
  samples/OWNERS
  sdk/OWNERS
  test/OWNERS
  third_party/OWNERS
Labels: approved, cla: yes, lgtm, size/S

#4122 test: postsubmit - fix cloudbuild job filtering. Part of #4046
  .cloudbuild.yaml
  .release.cloudbuild.yaml
  test/postsubmit-tests-with-pipeline-deployment.sh
Labels: cherrypick-approved, cla: yes, size/XS

#3932 [AWS SageMaker] GroundTruth Pre/Post Lambda function region additions
  components/aws/sagemaker/Changelog.md
  components/aws/sagemaker/THIRD-PARTY-LICENSES.txt
  components/aws/sagemaker/batch_transform/component.yaml
  components/aws/sagemaker/common/_utils.py
  components/aws/sagemaker/deploy/component.yaml
  components/aws/sagemaker/ground_truth/component.yaml
  components/aws/sagemaker/hyperparameter_tuning/component.yaml
  components/aws/sagemaker/model/component.yaml
  components/aws/sagemaker/process/component.yaml
  components/aws/sagemaker/tests/unit_tests/tests/test_ground_truth.py
  components/aws/sagemaker/train/component.yaml
  components/aws/sagemaker/workteam/component.yaml
Labels: approved, lgtm, ok-to-test, size/M

#4055 SDK - Compiler - Removed the deprecated dsl-compile --package command
  sdk/python/kfp/compiler/main.py
  sdk/python/tests/compiler/compiler_tests.py
Labels: approved, area/sdk, area/sdk/dsl/compiler, cherrypick-approved, cla: yes, lgtm, size/M

#4127 chore: fix kjd/idna license location change
  backend/src/apiserver/visualization/third_party_licenses.csv
  components/third_party_licenses.csv
Labels: cla: yes, size/XS

#4112 feat(deployment): marketplace - allow specifying gcs bucket directly
  VERSION
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/argo.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/gcp_secret.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/minio.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/mysql.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/values.yaml
  manifests/gcp_marketplace/schema.yaml
Labels: approved, cherrypick-approved, cla: yes, lgtm, size/M

#4121 test(sdk): Components tests - Made test_load_component_from_url hermetic
  sdk/python/kfp/components_tests/test_components.py
Labels: approved, area/sdk/components, area/sdk/tests, cla: yes, lgtm, size/S

#4130 fix(sdk): SDK - Components - Fixed the error message format string
  sdk/python/kfp/components/_python_to_graph_component.py
Labels: approved, area/sdk/components, cla: yes, lgtm, size/XS

#4133 fix: increase TFX version from 0.20.2 to 0.22.0. Fixes #4084, fixes #4114
  backend/requirements.in
  backend/requirements.txt
  samples/core/iris/iris.py
  samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py
  samples/core/parameterized_tfx_oss/taxi_pipeline_notebook.ipynb
  test/sample-test/requirements.in
  test/sample-test/requirements.txt
Labels: approved, cla: yes, lgtm, size/L

#4132 test(sdk): SDK - Added the mock package to the test requirements
  sdk/python/requirements-test.txt
  sdk/python/setup.py
Labels: approved, area/sdk, cla: yes, lgtm, size/XS

#4131 tests: Presubmits - Added presubmit unit tests for KFP SDK
  test/presubmit-tests-sdk.sh
Labels: approved, area/testing, cla: yes, lgtm, size/M

#4136 test: Added presubmit unit tests for the backend visualizations
  test/presubmit-backend-visualization.sh
Labels: approved, area/testing, cla: yes, lgtm, size/S

#4119 [AWS SageMaker] De-hardcode output paths in AWS components
  components/aws/sagemaker/Changelog.md
  components/aws/sagemaker/THIRD-PARTY-LICENSES.txt
  components/aws/sagemaker/batch_transform/component.yaml
  components/aws/sagemaker/batch_transform/src/batch_transform.py
  components/aws/sagemaker/common/_utils.py
  components/aws/sagemaker/deploy/component.yaml
  components/aws/sagemaker/deploy/src/deploy.py
  components/aws/sagemaker/ground_truth/component.yaml
  components/aws/sagemaker/ground_truth/src/ground_truth.py
  components/aws/sagemaker/hyperparameter_tuning/component.yaml
  components/aws/sagemaker/hyperparameter_tuning/src/hyperparameter_tuning.py
  components/aws/sagemaker/model/component.yaml
  components/aws/sagemaker/model/src/create_model.py
  components/aws/sagemaker/process/component.yaml
  components/aws/sagemaker/process/src/process.py
  components/aws/sagemaker/tests/integration_tests/README.md
  components/aws/sagemaker/tests/integration_tests/component_tests/test_batch_transform_component.py
  components/aws/sagemaker/tests/integration_tests/component_tests/test_deploy_component.py
  components/aws/sagemaker/tests/integration_tests/component_tests/test_hpo_component.py
  components/aws/sagemaker/tests/integration_tests/component_tests/test_model_component.py
  components/aws/sagemaker/tests/integration_tests/component_tests/test_processing_component.py
  components/aws/sagemaker/tests/integration_tests/component_tests/test_train_component.py
  components/aws/sagemaker/tests/integration_tests/component_tests/test_workteam_component.py
  components/aws/sagemaker/tests/integration_tests/utils/__init__.py
  components/aws/sagemaker/tests/integration_tests/utils/sagemaker_utils.py
  components/aws/sagemaker/tests/unit_tests/tests/test_batch_transform.py
  components/aws/sagemaker/tests/unit_tests/tests/test_deploy.py
  components/aws/sagemaker/tests/unit_tests/tests/test_ground_truth.py
  components/aws/sagemaker/tests/unit_tests/tests/test_hpo.py
  components/aws/sagemaker/tests/unit_tests/tests/test_model.py
  components/aws/sagemaker/tests/unit_tests/tests/test_process.py
  components/aws/sagemaker/tests/unit_tests/tests/test_train.py
  components/aws/sagemaker/tests/unit_tests/tests/test_utils.py
  components/aws/sagemaker/tests/unit_tests/tests/test_workteam.py
  components/aws/sagemaker/train/component.yaml
  components/aws/sagemaker/train/src/train.py
  components/aws/sagemaker/workteam/component.yaml
  components/aws/sagemaker/workteam/src/workteam.py
Labels: approved, cla: yes, lgtm, size/L

#4139 docs(release): introduce needed actions before release
  RELEASE.md
  hack/release.sh
Labels: approved, cherrypick-approved, cla: yes, lgtm, size/M

#4104 feat(sdk): DSL - Added support for volatile components
  components/diagnostics/diagnose_me/component.yaml
  components/git/clone/component.yaml
  components/google-cloud/storage/list/component.yaml
  sdk/python/kfp/dsl/_component_bridge.py
  sdk/python/tests/dsl/component_bridge_tests.py
Labels: approved, area/sdk/dsl, cherrypick-approved, cla: yes, lgtm, size/M

#4118 chore(backend): Only compiling the preloaded samples. Fixes #4117
  backend/Dockerfile
  samples/core/iris/iris.py
Labels: approved, area/backend, cherrypick-approved, cla: yes, lgtm, size/M

#4151 docs(deployment): Suggested wording changes for schema.yaml.
  manifests/gcp_marketplace/schema.yaml
Labels: approved, cla: yes, lgtm, size/M

#4158 fix(backend): fix the google-api-core to 1.16.0 for backend visualization server.
  backend/src/apiserver/visualization/requirements.txt
Labels: cherrypick-approved, cla: yes, lgtm, size/XS

#4087 feat(sdk): CLI - Allow upload_version by the pipeline's name. Fixes #3901
  sdk/python/kfp/_client.py
  sdk/python/kfp/cli/pipeline.py
Labels: approved, cla: yes, lgtm, size/M

#4124 test: Presubmits - Added presubmit tests against TFX
  test/presubmit-tests-tfx.sh
Labels: approved, area/testing, cla: yes, lgtm, size/M

#4171 fix(cache): Fix cache deployer not regenerating secrets when secret not present
  backend/src/cache/deployer/deploy-cache-service.sh
Labels: approved, cherrypick-approved, cla: yes, kind/bug, lgtm, size/S

#4120 fix(sdk): Compiler - Fixed input artifact name sanitization when using raw string arguments. Fixes #4110
  sdk/python/kfp/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
Labels: approved, area/sdk, area/sdk/dsl/compiler, cla: yes, lgtm, size/M

#4149 feat: add parallelism for dsl.ParallelFor. Fixes #4089
  samples/core/loop_parallelism/loop_parallelism.py
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/dsl/_ops_group.py
Labels: approved, area/sdk, area/sdk/dsl, cla: yes, lgtm, size/M

#4177 fix(sdk): Fix get_experiment when there are no experiments. Fixes #4176
  sdk/python/kfp/_client.py
Labels: approved, cla: yes, lgtm, size/XS

#4166 feat(sdk): SDK - Deprecation warning when using ContainerOp
  sdk/python/kfp/dsl/_component_bridge.py
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/tests/dsl/component_bridge_tests.py
Labels: approved, area/sdk/dsl, cherrypick-approved, cla: yes, lgtm, size/M

#4059 A brief release announcement/note for KFP 1.0
  docs/releases/release-1.0.md
  docs/releases/versioning-policy.md
Labels: approved, cla: yes, lgtm, size/M

#4186 fix(cache): cache-deployer should check both secret and config
  backend/src/cache/deployer/deploy-cache-service.sh
Labels: approved, cherrypick-approved, cla: yes, lgtm, size/XS

#4188 fix(deployment): gcp - add service account to deployments that need workload identity. Fixes #4183
  manifests/kustomize/env/gcp/cloudsql-proxy/cloudsql-proxy-deployment.yaml
  manifests/kustomize/env/gcp/cloudsql-proxy/cloudsql-proxy-sa.yaml
  manifests/kustomize/env/gcp/cloudsql-proxy/kustomization.yaml
  manifests/kustomize/env/gcp/minio-gcs-gateway/kustomization.yaml
  manifests/kustomize/env/gcp/minio-gcs-gateway/minio-gcs-gateway-deployment.yaml
  manifests/kustomize/env/gcp/minio-gcs-gateway/minio-gcs-gateway-sa.yaml
  manifests/kustomize/gcp-workload-identity-setup.sh
Labels: cherrypick-approved, cla: yes, size/S

#4190 fix(components): AWS SageMaker - Fix MinIO PID early exit
  components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests
Labels: approved, cla: yes, lgtm, size/XS

#4056 [AWS SageMaker] Integ test to check CloudWatch logs print feature
  components/aws/sagemaker/Changelog.md
  components/aws/sagemaker/THIRD-PARTY-LICENSES.txt
  components/aws/sagemaker/batch_transform/component.yaml
  components/aws/sagemaker/common/_utils.py
  components/aws/sagemaker/deploy/component.yaml
  components/aws/sagemaker/ground_truth/component.yaml
  components/aws/sagemaker/hyperparameter_tuning/component.yaml
  components/aws/sagemaker/model/component.yaml
  components/aws/sagemaker/process/component.yaml
  components/aws/sagemaker/tests/integration_tests/component_tests/test_batch_transform_component.py
  components/aws/sagemaker/tests/integration_tests/component_tests/test_processing_component.py
  components/aws/sagemaker/tests/integration_tests/component_tests/test_train_component.py
  components/aws/sagemaker/tests/integration_tests/utils/argo_utils.py
  components/aws/sagemaker/train/component.yaml
  components/aws/sagemaker/workteam/component.yaml
Labels: approved, cla: yes, lgtm, size/M

#4195 fix(sdk): fixes the default value for _is_refresh_token. Fixes #4189
  sdk/python/kfp/_client.py
Labels: approved, cla: yes, lgtm, size/XS

#4164 feat(sdk): SDK - Enable placeholders in task display names. Fixes #4163
  sdk/python/kfp/compiler/_op_to_template.py
  sdk/python/tests/compiler/compiler_tests.py
Labels: approved, area/sdk/dsl/compiler, cla: yes, lgtm, size/S

#4196 test: fix postsubmit test component image injection. Part of #4189
  test/sample-test/sample_test_launcher.py
Labels: approved, cherrypick-approved, cherrypicked, cla: yes, lgtm, size/S

#4198 fix(deployment): fix database name prefix description
  manifests/gcp_marketplace/schema.yaml
Labels: approved, cherrypick-approved, cla: yes, lgtm, size/XS

#4181 fix(sample): Fix syntax error in openvino sample component
  contrib/samples/openvino/deployer/component.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3874 SDK - Compiler - Validating Argo validator
  sdk/python/kfp/compiler/compiler.py
Labels: approved, area/sdk/dsl/compiler, cla: yes, lgtm, size/S

#4044 Components - tables - Remove_header
  components/tables/Remove_header/component.yaml
Labels: approved, area/components, lgtm, size/S

#4154 feat(sdk): SDK - Components - Added annotations to InputSpec and OutputSpec
  sdk/python/kfp/components/_structures.py
Labels: approved, area/sdk/components, cherrypick-approved, cla: yes, lgtm, size/XS

#4153 feat(sdk): SDK - Components - Added annotations to TaskSpec
  sdk/python/kfp/components/_structures.py
Labels: approved, area/sdk/components, cherrypick-approved, cla: yes, lgtm, size/XS

#4203 feat(backend): sorting on run metrics - step 1
  backend/src/apiserver/storage/run_store.go
Labels: approved, cla: yes, lgtm, size/S

#4074 SDK - Components - Fixed examples in docstrings
  sdk/python/kfp/components/_python_op.py
  sdk/python/kfp/components/_python_to_graph_component.py
Labels: approved, area/sdk/components, lgtm, size/XS

#4134 fix(sdk): SDK - Avoiding deprecated ContainerOp methods
  samples/tutorials/gpu/gpu.ipynb
  sdk/python/kfp/gcp.py
  sdk/python/tests/compiler/testdata/basic.py
  sdk/python/tests/compiler/testdata/basic_no_decorator.py
Labels: approved, area/sdk, area/sdk/tests, cla: yes, lgtm, size/S

#4135 test: Added presubmit unit tests for the component.yaml definitions
  test/presubmit-component-yaml.sh
Labels: approved, area/testing, cla: yes, lgtm, size/S

#4137 test: Added presubmit unit tests for the GCP components
  components/gcp/container/component_sdk/python/tox.ini
  test/presubmit-components-gcp.sh
Labels: approved, area/testing, cla: yes, lgtm, size/S

#2679 feat(sdk/client): add cookie configuration to kfp client
  sdk/python/kfp/_client.py
Labels: approved, area/sdk/client, cla: yes, lgtm, ok-to-test, size/XS

#4211 test: Fix KFP SDK TFX tests by specifying transitive dependency to resolve google-auth mismatch
  .travis.yml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2254 Add myself as approver/reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#4220 test(backend): prepares a test/presubmit-backend-test.sh script. Part of #3436
  test/presubmit-backend-test.sh
Labels: approved, cherrypick-approved, cla: yes, lgtm, size/S

#4201 fix(backend): fixes useless error message when visualization-server is not accessible. Fixes #4157
  backend/src/apiserver/server/visualization_server.go
  backend/src/apiserver/server/visualization_server_test.go
Labels: approved, cla: yes, lgtm, size/M

#4230 SDK - Components - Temporary removed Kubernetes options from ComponentSpec
  sdk/python/kfp/components/_structures.py
  sdk/python/kfp/components/structures/components.json_schema.json
  sdk/python/kfp/components/structures/components.json_schema.outline.yaml
  sdk/python/kfp/components/structures/components.proto
  sdk/python/kfp/components/structures/kubernetes/__init__.py
  sdk/python/kfp/components/structures/kubernetes/v1.py
  sdk/python/kfp/components_tests/test_graph_components.py
  sdk/python/setup.py
Labels: approved, area/sdk/components, cherrypick-approved, cla: yes, lgtm, size/XL

#4232 feat(deployment): GCP managed storage - detailed instructions to set up workload identity bindings before deployment
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-ui-configmap.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-ui-deployment.yaml
  manifests/kustomize/base/pipeline/viewer-sa.yaml
  manifests/kustomize/gcp-workload-identity-setup.sh
  manifests/kustomize/sample/README.md
  test/deploy-pipeline-lite.sh
Labels: approved, cla: yes, lgtm, size/L

#4231 fix(backend): Metadata Writer - Fixed regression with artifact type retrieval. Fixes #3971
  backend/metadata_writer/src/metadata_writer.py
Labels: approved, area/metadata-writer, cherrypick-approved, cla: yes, lgtm, size/XS

#4234 test: Fixed the presubmit TFX test by switching from protoc to Bazel
  test/presubmit-tests-tfx.sh
Labels: approved, area/testing, cla: yes, lgtm, size/S

#4233 test: Fixed the Travis TFX tests since TFX now requires Bazel. Fixes #4221
  .travis.yml
Labels: approved, area/testing, cla: yes, lgtm, size/XS

#4146 feat(sdk): Expose upload pipeline version
  sdk/python/kfp/_client.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#4192 feat(components): [AWS SageMaker] Minimize inputs for mnist classification pipeline
  samples/contrib/aws-samples/README.md
  samples/contrib/aws-samples/mnist-kmeans-sagemaker/README.md
  samples/contrib/aws-samples/mnist-kmeans-sagemaker/mnist-classification-pipeline.py
Labels: approved, cla: yes, lgtm, size/L

#4167 feat(components): AWS SageMaker - Add functionality to stop SageMaker jobs on run termination
  components/aws/sagemaker/Changelog.md
  components/aws/sagemaker/THIRD-PARTY-LICENSES.txt
  components/aws/sagemaker/batch_transform/component.yaml
  components/aws/sagemaker/batch_transform/src/batch_transform.py
  components/aws/sagemaker/common/_utils.py
  components/aws/sagemaker/deploy/component.yaml
  components/aws/sagemaker/ground_truth/component.yaml
  components/aws/sagemaker/ground_truth/src/ground_truth.py
  components/aws/sagemaker/hyperparameter_tuning/component.yaml
  components/aws/sagemaker/hyperparameter_tuning/src/hyperparameter_tuning.py
  components/aws/sagemaker/model/component.yaml
  components/aws/sagemaker/process/component.yaml
  components/aws/sagemaker/process/src/process.py
  components/aws/sagemaker/tests/integration_tests/component_tests/test_batch_transform_component.py
  components/aws/sagemaker/tests/integration_tests/component_tests/test_groundtruth_component.py
  components/aws/sagemaker/tests/integration_tests/component_tests/test_hpo_component.py
  components/aws/sagemaker/tests/integration_tests/component_tests/test_processing_component.py
  components/aws/sagemaker/tests/integration_tests/component_tests/test_train_component.py
  components/aws/sagemaker/tests/integration_tests/resources/definition/hpo_pipeline.py
  components/aws/sagemaker/tests/integration_tests/resources/definition/training_pipeline.py
  components/aws/sagemaker/tests/integration_tests/utils/kfp_client_utils.py
  components/aws/sagemaker/tests/unit_tests/tests/test_batch_transform.py
  components/aws/sagemaker/tests/unit_tests/tests/test_ground_truth.py
  components/aws/sagemaker/tests/unit_tests/tests/test_hpo.py
  components/aws/sagemaker/tests/unit_tests/tests/test_process.py
  components/aws/sagemaker/tests/unit_tests/tests/test_train.py
  components/aws/sagemaker/train/component.yaml
  components/aws/sagemaker/train/src/train.py
Labels: approved, cla: yes, lgtm, size/L

#4244 Components - XGBoost - Added the Cross_validation_for_regression component
  components/XGBoost/Cross_validation_for_regression/from_CSV/component.py
  components/XGBoost/Cross_validation_for_regression/from_CSV/component.yaml
Labels: approved, area/components, cla: yes, lgtm, size/L

#4245 Components - XGBoost - Added Train_and_cross-validate_regression component
  components/XGBoost/Train_and_cross-validate_regression/from_CSV/component.py
  components/XGBoost/Train_and_cross-validate_regression/from_CSV/component.yaml
  components/XGBoost/_samples/training_with_cross_validation.py
Labels: approved, area/components, cla: yes, lgtm, size/L

#4243 Components - XGBoost - Added the Train_regression_and_calculate_metrics component
  components/XGBoost/Train_regression_and_calculate_metrics/from_CSV/component.py
  components/XGBoost/Train_regression_and_calculate_metrics/from_CSV/component.yaml
Labels: approved, area/components, cla: yes, lgtm, size/L

#4240 Components - ml_metrics - Added the Aggregate_regression_metrics component
  components/ml_metrics/Aggregate_regression_metrics/component.py
  components/ml_metrics/Aggregate_regression_metrics/component.yaml
Labels: approved, area/components, cla: yes, lgtm, size/L

#4250 doc(release): instructions for update master branch version and etc
  RELEASE.md
Labels: approved, cla: yes, lgtm, size/S

#4235 feat(backend): sort by run metrics - step 2
  backend/src/apiserver/list/BUILD.bazel
  backend/src/apiserver/list/list.go
  backend/src/apiserver/list/list_test.go
  backend/src/apiserver/model/experiment.go
  backend/src/apiserver/model/job.go
  backend/src/apiserver/model/pipeline.go
  backend/src/apiserver/model/pipeline_version.go
  backend/src/apiserver/model/run.go
  backend/src/apiserver/server/list_request_util_test.go
  backend/src/apiserver/storage/run_store.go
  backend/src/apiserver/storage/run_store_test.go
Labels: approved, cla: yes, lgtm, size/L

#4246 fix(cache): adds certificate approver permission to kubeflow-pipelines-cache-deployer-role. Fixes #4138
  manifests/kustomize/base/cache-deployer/cluster-scoped/cache-deployer-clusterrole.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#4215 feat(sdk): support HTTP/S PROXY for SDK client
  sdk/python/kfp/_client.py
Labels: approved, cherrypick-approved, cla: yes, lgtm, size/S

#4260 Update README.md
  README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#4255 doc(sdk): Fixed documentation by updating the kfp-server-api dependency
  sdk/python/requirements.txt
Labels: approved, area/docs, area/sdk, cherrypick-approved, cla: yes, lgtm, size/XS

#4266 fix: all big enough ui proxy requests fail with error proxying with partial data
  frontend/server/app.ts
  frontend/server/consts.ts
  frontend/server/handlers/artifacts.ts
  frontend/server/proxy-middleware.ts
Labels: approved, cherrypick-approved, cla: yes, lgtm, size/S

#4285 fix(sdk/client): reserve the host protocal (http or https) so that http host can work. Fixes #4277
  sdk/python/kfp/_client.py
Labels: approved, cherrypick-approved, cla: yes, lgtm, size/XS

#4303 test: identity-namespace no longer works and replace it with workload-pool
  test/deploy-cluster.sh
Labels: approved, cherrypick-approved, cla: yes, lgtm, size/XS

#4251 feat(backend): sort by run metrics - step 3. Part of #3591
  backend/src/apiserver/list/list.go
  backend/src/apiserver/list/list_test.go
  backend/src/apiserver/model/BUILD.bazel
  backend/src/apiserver/model/experiment.go
  backend/src/apiserver/model/job.go
  backend/src/apiserver/model/pipeline.go
  backend/src/apiserver/model/pipeline_version.go
  backend/src/apiserver/model/pipeline_version_test.go
  backend/src/apiserver/model/resource_reference_test.go
  backend/src/apiserver/model/run.go
  backend/src/apiserver/model/run_test.go
  backend/src/apiserver/server/list_request_util.go
  backend/src/apiserver/server/list_request_util_test.go
  backend/src/apiserver/storage/run_store.go
Labels: approved, cla: yes, lgtm, size/XL

#4298 fix(components): Add explicit image tag and fix variable references.
  components/gcp/bigquery/query/sample.ipynb
  components/gcp/bigquery/query/to_CSV/component.yaml
  components/gcp/bigquery/query/to_gcs/README.md
  components/gcp/bigquery/query/to_gcs/component.yaml
  components/gcp/bigquery/query/to_table/component.yaml
Labels: approved, cherrypick-approved, cla: yes, lgtm, size/S
