Repository kubeflow/pipelines, pull requests merged in 2020-04, with the labels that each got.

#3343 [Manifest]Cache - mkp deployment
  backend/src/cache/client_manager.go
  backend/src/cache/main.go
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/cache.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/values.yaml
  manifests/gcp_marketplace/schema.yaml
  manifests/kustomize/base/cache-deployer/cache-deployer-clusterrole.yaml
  manifests/kustomize/base/cache-deployer/cache-deployer-rolebinding.yaml
  manifests/kustomize/base/cache-deployer/cache-deployer-secret-clusterrole.yaml
  manifests/kustomize/base/cache-deployer/kustomization.yaml
Labels: approved, lgtm, size/L

#3395 [Sample] Change preloaded TFX samples to use GCR images
  samples/core/iris/iris.py
  samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py
  samples/core/parameterized_tfx_oss/taxi_pipeline_notebook.ipynb
Labels: approved, lgtm, size/XS

#3413 quick fix envoy proxy service name
  third_party/metadata_envoy/envoy.yaml
Labels: size/XS

#3414 [Manifest]Fix - Cache mkp deployment
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/cache.yaml
Labels: approved, lgtm, size/XS

#3403 [UI] No longer pass namespace to createRun api
  frontend/src/pages/NewRun.test.tsx
  frontend/src/pages/NewRun.tsx
Labels: approved, area/frontend, cuj/multi-user, kind/feature, lgtm, size/M

#3416 revert kfp-cache from Hosted/MKP
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/cache.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/values.yaml
  manifests/gcp_marketplace/schema.yaml
Labels: approved, lgtm, size/L

#3409 enable native Keras + TFMA
  samples/core/iris/iris.py
Labels: approved, lgtm, size/XS

#3376 [Manifest] Cache - Enable cache and cache deployer in base kustomization file
  manifests/kustomize/README.md
  manifests/kustomize/base/cache-deployer/cache-deployer-rolebinding.yaml
  manifests/kustomize/base/cache-deployer/cache-deployer-secret-role.yaml
  manifests/kustomize/base/cache-deployer/cluster/cache-deployer-clusterrole.yaml
  manifests/kustomize/base/cache-deployer/cluster/cache-deployer-clusterrolebinding.yaml
  manifests/kustomize/base/cache-deployer/cluster/kustomization.yaml
  manifests/kustomize/base/cache-deployer/kustomization.yaml
  manifests/kustomize/base/cache/cache-deployment.yaml
  manifests/kustomize/base/kustomization.yaml
  manifests/kustomize/cluster-scoped-resources/kustomization.yaml
  test/deploy-pipeline-lite.sh
  test/manifests/cluster-scoped-resources/kustomization.yaml
  test/manifests/dev/kustomization.yaml
Labels: approved, area/deployment/standalone, lgtm, size/M

#3384 [Backend][Multi-user] support multi-user mode for job APIs
  backend/src/apiserver/BUILD.bazel
  backend/src/apiserver/client/BUILD.bazel
  backend/src/apiserver/client/scheduled_workflow_fake.go
  backend/src/apiserver/client/swf.go
  backend/src/apiserver/client/swf_fake.go
  backend/src/apiserver/client_manager.go
  backend/src/apiserver/resource/BUILD.bazel
  backend/src/apiserver/resource/client_manager_fake.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/server/job_server.go
  backend/src/apiserver/server/job_server_test.go
  backend/src/apiserver/storage/job_store.go
  backend/src/apiserver/storage/job_store_test.go
Labels: approved, area/backend, kind/feature, lgtm, size/XL

#3427 [SDK] Skip host name preprocess for the IAP case
  sdk/python/kfp/_client.py
Labels: approved, lgtm, size/XS

#3429 [Backend]Cache - Fix flag parse
  backend/src/cache/main.go
Labels: approved, lgtm, size/XS

#3400 Add new instructions to ensure compatibility for managed ai platform …
  samples/tutorials/mnist/00_Kubeflow_Cluster_Setup.ipynb
  samples/tutorials/mnist/01_Lightweight_Python_Components.ipynb
  samples/tutorials/mnist/02_Local_Development_with_Docker_Image_Components.ipynb
  samples/tutorials/mnist/03_Reusable_Components.ipynb
  samples/tutorials/mnist/04_Reusable_and_Pre-build_Components_as_Pipeline.ipynb
Labels: approved, lgtm, size/L

#3433 [Fix]Cache - Revert objectSelector in mutatingwebhookconfiguration
  backend/src/cache/deployer/cache-configmap.yaml.template
  backend/src/cache/server/mutation.go
  backend/src/cache/server/mutation_test.go
  test/e2e_test_gke_v2.yaml
Labels: approved, lgtm, size/M

#3421 Update deployment resource version from /v1beta1 -> /v1
  manifests/kustomize/base/application/application-controller-deployment.yaml
  manifests/kustomize/base/argo/workflow-controller-deployment.yaml
  manifests/kustomize/base/metadata/metadata-envoy-deployment.yaml
  manifests/kustomize/base/metadata/metadata-grpc-deployment.yaml
  manifests/kustomize/base/pipeline-application.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-scheduledworkflow-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-ui-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-viewer-crd-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-visualization-deployment.yaml
  manifests/kustomize/base/proxy/proxy-deployment.yaml
  manifests/kustomize/env/dev/minio/minio-deployment.yaml
  manifests/kustomize/env/dev/mysql/mysql-deployment.yaml
  manifests/kustomize/env/gcp/gcp-configurations-patch.yaml
  manifests/kustomize/env/gcp/minio/minio-gcs-gateway-deployment.yaml
  manifests/kustomize/env/gcp/mysql/cloudsql-proxy-deployment.yaml
  manifests/kustomize/namespaced/kustomization.yaml
Labels: approved, lgtm, size/M

#3378 enable CloudSQL+GCSObjStore without default credential
  manifests/gcp_marketplace/README.md
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/metadata.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/minio.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/mysql.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/values.yaml
  manifests/gcp_marketplace/schema.yaml
Labels: approved, lgtm, size/L

#3417 [SDK][Multi-user] refine sdk for multi-user support
  sdk/python/kfp/_client.py
Labels: approved, lgtm, size/M

#3411 [Backend]Cache - Max cache staleness support
  backend/src/cache/server/mutation.go
  backend/src/cache/server/mutation_test.go
  backend/src/cache/server/watcher.go
  backend/src/cache/storage/execution_cache_store.go
  backend/src/cache/storage/execution_cache_store_test.go
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#3339 [SDK/CLI] Add version param to run_pipeline
  sdk/python/kfp/_client.py
  sdk/python/kfp/cli/run.py
Labels: approved, lgtm, ok-to-test, size/S

#3446 SDK - Components - Fixed bug in loading input-less graph components
  sdk/python/kfp/components/_components.py
Labels: approved, area/sdk/components, lgtm, size/XS

#3430 [Manifest] Cache - MKP deployment
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/cache.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/values.yaml
  manifests/gcp_marketplace/schema.yaml
  manifests/kustomize/base/cache-deployer/cache-deployer-deployment.yaml
  manifests/kustomize/base/cache-deployer/cache-deployer-role.yaml
  manifests/kustomize/base/cache-deployer/cache-deployer-rolebinding.yaml
  manifests/kustomize/base/cache-deployer/kustomization.yaml
  test/deploy-pipeline-lite.sh
Labels: approved, lgtm, size/L

#3456 [Cache] Change cache-deployer deployment to strategy recreate
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/cache.yaml
  manifests/kustomize/base/cache-deployer/cache-deployer-deployment.yaml
Labels: approved, deployment, kind/bug, lgtm

#3397 AWS sagemaker : Added license files and updated Dockerfile to use AmazonLinux
  components/aws/sagemaker/Dockerfile
  components/aws/sagemaker/LICENSE.txt
  components/aws/sagemaker/NOTICE.txt
  components/aws/sagemaker/THIRD-PARTY-LICENSES.txt
Labels: approved, lgtm, ok-to-test, size/XXL

#3435 [Backend] Keep workflow service account when not default or empty
  backend/src/apiserver/common/config.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/server/run_server_test.go
Labels: approved, area/backend, kind/feature, lgtm, size/M

#3437 Refactor the legacy way of using pipeline id to create run in KFP backend
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/resource/resource_manager_util.go
  backend/src/apiserver/resource/resource_manager_util_test.go
  backend/test/integration/upgrade_test.go
  go.sum
Labels: size/L

#3440 AWS Sagemaker : Updated documents
  components/aws/sagemaker/train/README.md
  samples/contrib/aws-samples/mnist-kmeans-sagemaker/README.md
  samples/contrib/aws-samples/simple_train_pipeline/README.md
  samples/contrib/aws-samples/simple_train_pipeline/training-pipeline.py
Labels: approved, lgtm, ok-to-test, size/L

#3466 Release eb69a6b8ae2d82cd8574ed11f04af4607756061c
  components/gcp/bigquery/query/README.md
  components/gcp/bigquery/query/component.yaml
  components/gcp/bigquery/query/sample.ipynb
  components/gcp/container/component_sdk/python/setup.py
  components/gcp/dataflow/launch_python/README.md
  components/gcp/dataflow/launch_python/component.yaml
  components/gcp/dataflow/launch_python/sample.ipynb
  components/gcp/dataflow/launch_template/README.md
  components/gcp/dataflow/launch_template/component.yaml
  components/gcp/dataflow/launch_template/sample.ipynb
  components/gcp/dataproc/create_cluster/README.md
  components/gcp/dataproc/create_cluster/component.yaml
  components/gcp/dataproc/create_cluster/sample.ipynb
  components/gcp/dataproc/delete_cluster/README.md
  components/gcp/dataproc/delete_cluster/component.yaml
  components/gcp/dataproc/delete_cluster/sample.ipynb
  components/gcp/dataproc/submit_hadoop_job/README.md
  components/gcp/dataproc/submit_hadoop_job/component.yaml
  components/gcp/dataproc/submit_hadoop_job/sample.ipynb
  components/gcp/dataproc/submit_hive_job/README.md
  components/gcp/dataproc/submit_hive_job/component.yaml
  components/gcp/dataproc/submit_hive_job/sample.ipynb
  components/gcp/dataproc/submit_pig_job/README.md
  components/gcp/dataproc/submit_pig_job/component.yaml
  components/gcp/dataproc/submit_pig_job/sample.ipynb
  components/gcp/dataproc/submit_pyspark_job/README.md
  components/gcp/dataproc/submit_pyspark_job/component.yaml
  components/gcp/dataproc/submit_pyspark_job/sample.ipynb
  components/gcp/dataproc/submit_spark_job/README.md
  components/gcp/dataproc/submit_spark_job/component.yaml
  components/gcp/dataproc/submit_spark_job/sample.ipynb
  components/gcp/dataproc/submit_sparksql_job/README.md
  components/gcp/dataproc/submit_sparksql_job/component.yaml
  components/gcp/dataproc/submit_sparksql_job/sample.ipynb
  components/gcp/ml_engine/batch_predict/README.md
  components/gcp/ml_engine/batch_predict/component.yaml
  components/gcp/ml_engine/batch_predict/sample.ipynb
  components/gcp/ml_engine/deploy/README.md
  components/gcp/ml_engine/deploy/component.yaml
  components/gcp/ml_engine/deploy/sample.ipynb
  components/gcp/ml_engine/train/README.md
  components/gcp/ml_engine/train/component.yaml
  components/gcp/ml_engine/train/sample.ipynb
  components/kubeflow/deployer/component.yaml
  components/kubeflow/dnntrainer/component.yaml
  components/local/confusion_matrix/component.yaml
  components/local/roc/component.yaml
  samples/core/ai_platform/ai_platform.ipynb
  samples/core/dataflow/dataflow.ipynb
  samples/core/kubeflow_tf_serving/kubeflow_tf_serving.ipynb
  samples/core/xgboost_training_cm/xgboost_training_cm.py
  samples/tutorials/mnist/04_Reusable_and_Pre-build_Components_as_Pipeline.ipynb
Labels: approved, lgtm, size/L

#3374 AWS sagemaker : Make 'endpoint_url' argument default to None instead of empty string
  components/aws/sagemaker/batch_transform/component.yaml
  components/aws/sagemaker/common/_utils.py
  components/aws/sagemaker/deploy/component.yaml
  components/aws/sagemaker/ground_truth/component.yaml
  components/aws/sagemaker/hyperparameter_tuning/component.yaml
  components/aws/sagemaker/model/component.yaml
  components/aws/sagemaker/train/component.yaml
  components/aws/sagemaker/workteam/component.yaml
Labels: approved, lgtm, ok-to-test, size/S

#3467 [Release] update version
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml
  manifests/gcp_marketplace/schema.yaml
  manifests/kustomize/README.md
  manifests/kustomize/base/kustomization.yaml
  manifests/kustomize/base/pipeline-application.yaml
  sdk/python/kfp/__init__.py
Labels: approved, lgtm, size/M

#3438 presubmit for MKP/Hosted
  test/presubmit-tests-mkp.sh
Labels: approved, lgtm, size/S

#3472 version bump fix
  VERSION
Labels: approved, lgtm, size/XS

#3468 Release 0.4.0: Update change log
  CHANGELOG.md
Labels: approved, lgtm, size/M

#3469 [Test] fix upgrade test
  test/deploy-pipeline-lite.sh
Labels: approved, lgtm, size/XS

#3477 [UI - multiuser] Fix pod log namespace source
  frontend/src/lib/RunUtils.ts
  frontend/src/pages/RunDetails.test.tsx
  frontend/src/pages/RunDetails.tsx
Labels: approved, area/frontend, cuj/multi-user, kind/bug, lgtm, size/S

#3410 Update documentation for AWS components
  components/aws/sagemaker/batch_transform/README.md
  components/aws/sagemaker/deploy/README.md
  components/aws/sagemaker/model/README.md
Labels: approved, lgtm, ok-to-test, size/L

#3476 [Fix]Fix release
  .release.cloudbuild.yaml
Labels: approved, lgtm, size/XS

#3408 backend/metadata_writer: Pin python dependencies
  backend/metadata_writer/Dockerfile
  backend/metadata_writer/README.md
  backend/metadata_writer/requirements.in
  backend/metadata_writer/requirements.txt
Labels: approved, lgtm, size/M

#3480 [Frontend] Fix npm reported vulnerabilities
  frontend/package-lock.json
  frontend/package.json
  frontend/server/package-lock.json
Labels: approved, area/engprod, area/frontend, kind/bug, lgtm, size/XXL

#3457 [UI] Show execution details in Run Details Page ML Metadata tab of steps
  frontend/src/components/Router.tsx
  frontend/src/lib/MlmdUtils.ts
  frontend/src/pages/ExecutionDetails.tsx
  frontend/src/pages/ExecutionList.tsx
  frontend/src/pages/Page.tsx
  frontend/src/pages/RunDetails.test.tsx
  frontend/src/pages/RunDetails.tsx
  frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
Labels: approved, area/frontend, kind/feature, lgtm, size/L

#3488 SDK - Components - Restored the yaml formatting style
  sdk/python/kfp/components/_yaml_utils.py
Labels: approved, area/sdk/components, lgtm, size/XS

#3471 [Test]Fix e2e test
  samples/core/recursion/recursion.py
  sdk/python/kfp/dsl/_component.py
  test/e2e_test_gke_v2.yaml
Labels: approved, lgtm, size/S

#3483 [UI] Redirect to experiment list page when namespace changes in RunDetails or Compare page
  frontend/src/lib/KubeflowClient.tsx
  frontend/src/pages/Compare.test.tsx
  frontend/src/pages/Compare.tsx
  frontend/src/pages/ExperimentDetails.tsx
  frontend/src/pages/RunDetails.test.tsx
  frontend/src/pages/RunDetails.tsx
Labels: approved, area/frontend, cuj/multi-user, kind/feature, lgtm, size/L

#3486 Components - Add model URL to AutoML - Create model/dataset for tables
  components/gcp/automl/create_dataset_for_tables/component.py
  components/gcp/automl/create_dataset_for_tables/component.yaml
  components/gcp/automl/create_model_for_tables/component.py
  components/gcp/automl/create_model_for_tables/component.yaml
Labels: approved, area/components, lgtm, size/L

#3423 Qwiklab caip updates
  samples/core/ai_platform/ai_platform.ipynb
  samples/core/lightweight_component/lightweight_component.ipynb
Labels: approved, lgtm, needs-ok-to-test, size/M

#3455 Upadate backend BUILD files
  WORKSPACE
  backend/src/apiserver/client/BUILD.bazel
  backend/src/apiserver/server/BUILD.bazel
  backend/src/cache/BUILD.bazel
  backend/src/cache/client/BUILD.bazel
  backend/src/cache/model/BUILD.bazel
  backend/src/cache/server/BUILD.bazel
  backend/src/cache/storage/BUILD.bazel
Labels: approved, lgtm, size/L

#3475 [Backend][Multi-user] Reenable visualization server in multi-user mode
  backend/src/apiserver/server/visualization_server.go
Labels: approved, lgtm, size/S

#3498 [Deployment] Move crds to cluster-scoped kustomize folders
  manifests/kustomize/STRUCTURE.md
  manifests/kustomize/base/application/cluster-scoped/application-crd.yaml
  manifests/kustomize/base/application/cluster-scoped/kustomization.yaml
  manifests/kustomize/base/argo/cluster-scoped/kustomization.yaml
  manifests/kustomize/base/argo/cluster-scoped/workflow-crd.yaml
  manifests/kustomize/base/cache-deployer/cluster-scoped/cache-deployer-clusterrole.yaml
  manifests/kustomize/base/cache-deployer/cluster-scoped/cache-deployer-clusterrolebinding.yaml
  manifests/kustomize/base/cache-deployer/cluster-scoped/kustomization.yaml
  manifests/kustomize/base/pipeline/cluster-scoped/kustomization.yaml
  manifests/kustomize/base/pipeline/cluster-scoped/scheduled-workflow-crd.yaml
  manifests/kustomize/base/pipeline/cluster-scoped/viewer-crd.yaml
  manifests/kustomize/cluster-scoped-resources/kustomization.yaml
Labels: approved, area/deployment/standalone, kind/process, lgtm, size/M

#3478 one GCP project share one default bucket
  manifests/gcp_marketplace/deployer/init_action.sh
Labels: approved, lgtm, size/S

#3458 pass projectID from env/configmap without user input
  manifests/gcp_marketplace/README.md
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/minio.yaml
  manifests/gcp_marketplace/schema.yaml
Labels: approved, lgtm, size/S

#3479 Metadata Writer - Log pod names
  backend/metadata_writer/src/metadata_helpers.py
  backend/metadata_writer/src/metadata_writer.py
Labels: approved, area/backend, lgtm, size/XS

#3492 [Testing] Reduce image build flakiness by share and retry cloudbuild jobs
  test/build-images.sh
  test/check-build-image-status.sh
  test/deploy-pipeline-lite.sh
Labels: approved, area/engprod, area/testing, lgtm, size/L

#3485 [UI] Groups executions by run if it exists
  frontend/src/lib/MlmdUtils.ts
  frontend/src/pages/ArtifactList.tsx
  frontend/src/pages/ExecutionList.tsx
Labels: approved, area/frontend, kind/feature, lgtm, size/S

#3504 [Test] Fix concurrent IAM policy changes flakiness
  test/deploy-pipeline-lite.sh
  test/install-argo.sh
Labels: approved, area/engprod, area/testing, kind/bug, lgtm, size/XS

#3314 Enable binding new PVC to specific PV
  sdk/python/kfp/dsl/_volume_op.py
Labels: approved, lgtm, size/XS

#3484 GPU with Kubeflow Pipeline Standalone
  samples/tutorials/gpu/README.md
  samples/tutorials/gpu/gpu.ipynb
Labels: approved, lgtm, size/L

#3502 [Deployment] Fix metadata envoy configuration
  manifests/kustomize/base/metadata/metadata-envoy-deployment.yaml
Labels: approved, kind/bug, lgtm, priority/p0, size/XS

#3474 AWS sagemaker: fixed a bug in ground_truth and updated all components to use images from new docker hub repo
  components/aws/sagemaker/batch_transform/component.yaml
  components/aws/sagemaker/common/_utils.py
  components/aws/sagemaker/deploy/component.yaml
  components/aws/sagemaker/ground_truth/component.yaml
  components/aws/sagemaker/hyperparameter_tuning/component.yaml
  components/aws/sagemaker/model/component.yaml
  components/aws/sagemaker/train/component.yaml
  components/aws/sagemaker/workteam/component.yaml
  samples/contrib/aws-samples/ground_truth_pipeline_demo/README.md
Labels: approved, lgtm, ok-to-test, size/M

#3487 add user agent header to boto3 client for aws components
  components/aws/sagemaker/common/_utils.py
Labels: approved, lgtm, ok-to-test, size/S

#3359 Add archive experiment feature in backend
  backend/api/experiment.proto
  backend/api/go_client/experiment.pb.go
  backend/api/go_client/experiment.pb.gw.go
  backend/api/go_http_client/experiment_client/experiment_service/BUILD.bazel
  backend/api/go_http_client/experiment_client/experiment_service/archive_experiment_parameters.go
  backend/api/go_http_client/experiment_client/experiment_service/archive_experiment_responses.go
  backend/api/go_http_client/experiment_client/experiment_service/experiment_service_client.go
  backend/api/go_http_client/experiment_client/experiment_service/unarchive_experiment_parameters.go
  backend/api/go_http_client/experiment_client/experiment_service/unarchive_experiment_responses.go
  backend/api/go_http_client/experiment_model/BUILD.bazel
  backend/api/go_http_client/experiment_model/api_experiment.go
  backend/api/go_http_client/experiment_model/experiment_storage_state.go
  backend/api/swagger/experiment.swagger.json
  backend/api/swagger/kfp_api_single_file.swagger.json
  backend/src/apiserver/model/experiment.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/server/api_converter.go
  backend/src/apiserver/server/api_converter_test.go
  backend/src/apiserver/server/experiment_server.go
  backend/src/apiserver/server/experiment_server_test.go
  backend/src/apiserver/storage/experiment_store.go
  backend/src/apiserver/storage/experiment_store_test.go
  backend/src/common/client/api_server/experiment_client.go
  backend/src/common/client/api_server/experiment_client_fake.go
  backend/test/integration/experiment_api_test.go
  frontend/src/apis/experiment/api.ts
Labels: lgtm, size/XXL

#3529 add missing licenses for viz server
  backend/src/apiserver/visualization/third_party_licenses.csv
  backend/src/apiserver/visualization/third_party_licenses/google-cloud-dlp.LICENSE
  backend/src/apiserver/visualization/third_party_licenses/google-cloud-language.LICENSE
  backend/src/apiserver/visualization/third_party_licenses/google-cloud-spanner.LICENSE
  backend/src/apiserver/visualization/third_party_licenses/google-cloud-videointelligence.LICENSE
  backend/src/apiserver/visualization/third_party_licenses/google-cloud-vision.LICENSE
  backend/src/apiserver/visualization/third_party_licenses/grpcio-gcp.LICENSE
  backend/src/apiserver/visualization/third_party_licenses/typing.LICENSE
Labels: size/XXL

#3520 SDK - Made YAML dumping more awesome
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/components/_yaml_utils.py
Labels: approved, area/sdk/components, area/sdk/dsl/compiler, lgtm, size/S

#3514 Components - Fixed BigQuery - Query component
  components/gcp/container/component_sdk/python/kfp_component/google/bigquery/_query.py
Labels: approved, area/components, lgtm, size/XS

#3506 Revise run_pipeline comment (as expected)
  sdk/python/kfp/_client.py
Labels: approved, size/XS

#3511 Upload pipeline/pipeline version with a description
  backend/api/go_http_client/pipeline_upload_client/pipeline_upload_service/upload_pipeline_parameters.go
  backend/api/swagger/kfp_api_single_file.swagger.json
  backend/api/swagger/pipeline.upload.swagger.json
Labels: approved, size/M

#3536 Testing - Fixed python requirements for sample tests
  test/sample-test/requirements.in
  test/sample-test/requirements.txt
Labels: approved, area/testing, lgtm, size/L

#3535 Infra - Improved the update_requirements script
  backend/README.md
  backend/update_requirements.sh
  test/sample-test/README.md
Labels: approved, area/testing, lgtm, size/S

#3546 [Test] fix TestRunApi integration test
  backend/test/integration/run_api_test.go
Labels: lgtm, size/XS

#3539 [SDK] Fixing bug where client.list_runs filters on empty namespace by default.
  sdk/python/kfp/_client.py
Labels: approved, lgtm, size/XS

#3543 add missing license for component image
  components/third_party_licenses.csv
Labels: approved, size/XS

#3495 [Backend][Multi-user] Support creating visualization in user namespace
  backend/api/go_client/visualization.pb.go
  backend/api/go_client/visualization.pb.gw.go
  backend/api/visualization.proto
  backend/src/apiserver/server/visualization_server.go
  backend/src/apiserver/server/visualization_server_test.go
Labels: approved, lgtm, size/L

#3533 [Testing] Fix not waiting for api server cloudbuild
  test/check-build-image-status.sh
Labels: approved, area/testing, kind/bug, lgtm, size/XS

#3556 Services - Metadata Writer - Added support for custom_properties in all helper methods
  backend/metadata_writer/src/metadata_helpers.py
Labels: approved, area/metadata-writer, lgtm, size/S

#3547 [Test] Fix api-integration-tests flakyness
  backend/test/integration/run_api_test.go
Labels: approved, lgtm, size/S

#3558 Manifest sample: use better sample name
  manifests/kustomize/sample/params.env
Labels: size/XS

#3572 Fix test which uses Kustomize edit image but can't work with valueRef
  manifests/kustomize/base/cache-deployer/cache-deployer-deployment.yaml
  manifests/kustomize/base/cache/cache-deployment.yaml
  manifests/kustomize/base/kustomization.yaml
  manifests/kustomize/base/metadata/metadata-writer-deployment.yaml
  manifests/kustomize/base/params.env
  manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-scheduledworkflow-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-ui-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-viewer-crd-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-visualization-deployment.yaml
  manifests/kustomize/env/gcp/inverse-proxy/proxy-deployment.yaml
  test/deploy-pipeline-lite.sh
  test/manifests/cluster-scoped-resources/kustomization.yaml
  test/manifests/dev/kustomization.yaml
  test/manifests/dev/params.env
Labels: size/M

#3573 Clusterrolebinding is using namespace which not parametrized
  manifests/kustomize/base/cache-deployer/cluster-scoped/cache-deployer-clusterrolebinding.yaml
  manifests/kustomize/env/dev/kustomization.yaml
  manifests/kustomize/env/gcp/kustomization.yaml
  manifests/kustomize/env/platform-agnostic/kustomization.yaml
  manifests/kustomize/sample/README.md
  manifests/kustomize/sample/kustomization.yaml
Labels: size/S

#3586 [Testing] Fix frontend integration test broken by #3540
  manifests/kustomize/base/pipeline/ml-pipeline-ui-deployment.yaml
Labels: approved, lgtm, size/XS

#3544 [Backend] In signle-user mode, reject experiment API requests with non-empty user namespace
  backend/src/apiserver/server/experiment_server.go
  backend/src/apiserver/server/experiment_server_test.go
Labels: approved, lgtm, size/M

#3582 [Testing] pipeline-install-config should be in kubeflow namespace
  test/manifests/dev/kustomization.yaml
Labels: approved, kind/bug, lgtm, size/XS

#3428 Minor updates to packages
  samples/core/ai_platform/local/Chicago Crime Research.ipynb
Labels: approved, lgtm, needs-ok-to-test, size/XS

#3512 Qwiklab caip updates
  samples/core/ai_platform/ai_platform.ipynb
  samples/core/lightweight_component/lightweight_component.ipynb
Labels: approved, lgtm, ok-to-test, size/XS

#3567 SDK - CLI - Fixed incompatibility with Python 3.5
  sdk/python/kfp/cli/pipeline.py
Labels: approved, area/cli, lgtm, size/XS

#3574 Enable cache-deployer as fixed the root cause in other PR
  backend/src/cache/deployer/deploy-cache-service.sh
  manifests/kustomize/base/cache/cache-deployment.yaml
  manifests/kustomize/base/kustomization.yaml
Labels: approved, lgtm, size/XS

#3560 Release ad9bd5648dd0453005225779f25d8cebebc7ca00
  components/gcp/bigquery/query/README.md
  components/gcp/bigquery/query/component.yaml
  components/gcp/bigquery/query/sample.ipynb
  components/gcp/dataflow/launch_python/README.md
  components/gcp/dataflow/launch_python/component.yaml
  components/gcp/dataflow/launch_python/sample.ipynb
  components/gcp/dataflow/launch_template/README.md
  components/gcp/dataflow/launch_template/component.yaml
  components/gcp/dataflow/launch_template/sample.ipynb
  components/gcp/dataproc/create_cluster/README.md
  components/gcp/dataproc/create_cluster/component.yaml
  components/gcp/dataproc/create_cluster/sample.ipynb
  components/gcp/dataproc/delete_cluster/README.md
  components/gcp/dataproc/delete_cluster/component.yaml
  components/gcp/dataproc/delete_cluster/sample.ipynb
  components/gcp/dataproc/submit_hadoop_job/README.md
  components/gcp/dataproc/submit_hadoop_job/component.yaml
  components/gcp/dataproc/submit_hadoop_job/sample.ipynb
  components/gcp/dataproc/submit_hive_job/README.md
  components/gcp/dataproc/submit_hive_job/component.yaml
  components/gcp/dataproc/submit_hive_job/sample.ipynb
  components/gcp/dataproc/submit_pig_job/README.md
  components/gcp/dataproc/submit_pig_job/component.yaml
  components/gcp/dataproc/submit_pig_job/sample.ipynb
  components/gcp/dataproc/submit_pyspark_job/README.md
  components/gcp/dataproc/submit_pyspark_job/component.yaml
  components/gcp/dataproc/submit_pyspark_job/sample.ipynb
  components/gcp/dataproc/submit_spark_job/README.md
  components/gcp/dataproc/submit_spark_job/component.yaml
  components/gcp/dataproc/submit_spark_job/sample.ipynb
  components/gcp/dataproc/submit_sparksql_job/README.md
  components/gcp/dataproc/submit_sparksql_job/component.yaml
  components/gcp/dataproc/submit_sparksql_job/sample.ipynb
  components/gcp/ml_engine/batch_predict/README.md
  components/gcp/ml_engine/batch_predict/component.yaml
  components/gcp/ml_engine/batch_predict/sample.ipynb
  components/gcp/ml_engine/deploy/README.md
  components/gcp/ml_engine/deploy/component.yaml
  components/gcp/ml_engine/deploy/sample.ipynb
  components/gcp/ml_engine/train/README.md
  components/gcp/ml_engine/train/component.yaml
  components/gcp/ml_engine/train/sample.ipynb
  components/kubeflow/deployer/component.yaml
  components/kubeflow/dnntrainer/component.yaml
  components/local/confusion_matrix/component.yaml
  components/local/roc/component.yaml
  samples/core/ai_platform/ai_platform.ipynb
  samples/core/dataflow/dataflow.ipynb
  samples/core/kubeflow_tf_serving/kubeflow_tf_serving.ipynb
  samples/core/xgboost_training_cm/xgboost_training_cm.py
  samples/tutorials/mnist/04_Reusable_and_Pre-build_Components_as_Pipeline.ipynb
Labels: size/L

#3566 update version to 0.5.0
  VERSION
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml
  manifests/gcp_marketplace/schema.yaml
  manifests/kustomize/base/params.env
  sdk/python/kfp/__init__.py
  sdk/python/setup.py
Labels: size/S

#3563 Metadata Writer - Fixed pod name property setting
  backend/metadata_writer/src/metadata_helpers.py
  backend/metadata_writer/src/metadata_writer.py
Labels: approved, area/metadata-writer, lgtm, size/S

#3592 [Release] Fix cloudbuild: remove compiled manifests
  .release.cloudbuild.yaml
Labels: lgtm, size/S

#3522 [UI] Multi user permission separation for artifact api
  frontend/server/.gitignore
  frontend/server/app.ts
  frontend/server/configs.ts
  frontend/server/handlers/artifacts.ts
  frontend/server/integration-tests/artifact-proxy.test.ts
  frontend/server/integration-tests/test-helper.ts
  frontend/server/package.json
  frontend/src/components/DetailsTable.test.tsx
  frontend/src/components/DetailsTable.tsx
  frontend/src/components/MinioArtifactLink.test.tsx
  frontend/src/components/MinioArtifactLink.tsx
  frontend/src/components/__snapshots__/DetailsTable.test.tsx.snap
  frontend/src/components/__snapshots__/MinioArtifactLink.test.tsx.snap
  frontend/src/lib/Apis.ts
  frontend/src/lib/OutputArtifactLoader.test.ts
  frontend/src/lib/OutputArtifactLoader.ts
  frontend/src/lib/Utils.tsx
  frontend/src/pages/RunDetails.tsx
Labels: approved, area/frontend, cuj/multi-user, lgtm, size/XL

#3553 [UI] Get execution details from metadata writer
  frontend/src/lib/MlmdUtils.ts
  frontend/src/pages/RunDetails.tsx
Labels: approved, area/frontend, kind/feature, lgtm, size/S

#3559 [UI] fix - create run missing-param warning not reacting to param value changes
  frontend/README.md
  frontend/src/pages/NewRun.test.tsx
  frontend/src/pages/NewRun.tsx
Labels: approved, lgtm, needs-ok-to-test, size/S

#3517 SDK - Removed the ArtifactLocation feature
  samples/core/artifact_location/artifact_location.py
  sdk/python/kfp/compiler/_op_to_template.py
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/dsl/__init__.py
  sdk/python/kfp/dsl/_artifact_location.py
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/kfp/dsl/_pipeline.py
  sdk/python/requirements.in
  sdk/python/requirements.txt
  sdk/python/setup.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/artifact_location.py
  sdk/python/tests/compiler/testdata/artifact_location.yaml
  sdk/python/tests/dsl/artifact_location_tests.py
  sdk/python/tests/dsl/main.py
  test/sample_test.yaml
Labels: approved, area/sdk/dsl, lgtm, size/XL

#3534 fix #2802: Set ImagePullPolicy per pipeline.
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/dsl/_pipeline.py
  sdk/python/tests/compiler/compiler_tests.py
Labels: approved, lgtm, size/M

#2978 Add method to schedule a recurring run to python client
  sdk/python/kfp/_client.py
Labels: approved, lgtm, ok-to-test, size/L

#3593 [UI Server] Enable strict type checking and fix errors
  frontend/package-lock.json
  frontend/package.json
  frontend/server/app.test.ts
  frontend/server/app.ts
  frontend/server/aws-helper.test.ts
  frontend/server/handlers/artifacts.ts
  frontend/server/integration-tests/artifact-proxy.test.ts
  frontend/server/minio-helper.test.ts
  frontend/server/minio-helper.ts
  frontend/server/package-lock.json
  frontend/server/package.json
  frontend/server/proxy-middleware.ts
  frontend/server/tsconfig.json
  frontend/server/untyped-modules.d.ts
  frontend/server/utils.ts
  frontend/server/workflow-helper.ts
Labels: approved, area/engprod, area/frontend, lgtm, size/XL

#3518 AWS Sagemaker : Use json.dumps() to better organize the input and remove data_locations
  components/aws/sagemaker/Changelog.md
  components/aws/sagemaker/THIRD-PARTY-LICENSES.txt
  components/aws/sagemaker/batch_transform/component.yaml
  components/aws/sagemaker/common/_utils.py
  components/aws/sagemaker/deploy/component.yaml
  components/aws/sagemaker/ground_truth/component.yaml
  components/aws/sagemaker/hyperparameter_tuning/README.md
  components/aws/sagemaker/hyperparameter_tuning/component.yaml
  components/aws/sagemaker/hyperparameter_tuning/src/hyperparameter_tuning.py
  components/aws/sagemaker/model/component.yaml
  components/aws/sagemaker/train/README.md
  components/aws/sagemaker/train/component.yaml
  components/aws/sagemaker/train/src/train.py
  components/aws/sagemaker/workteam/component.yaml
  samples/contrib/aws-samples/ground_truth_pipeline_demo/mini-image-classification-pipeline.py
  samples/contrib/aws-samples/mnist-kmeans-sagemaker/kmeans-hpo-pipeline.py
  samples/contrib/aws-samples/mnist-kmeans-sagemaker/mnist-classification-pipeline.py
  samples/contrib/aws-samples/simple_train_pipeline/README.md
  samples/contrib/aws-samples/simple_train_pipeline/training-pipeline.py
Labels: approved, lgtm, ok-to-test, size/L

#3588 [API] Include namespace in visualization.swagger.json
  backend/api/go_client/visualization.pb.go
  backend/api/go_client/visualization.pb.gw.go
  backend/api/go_http_client/visualization_client/visualization_service/create_visualization_parameters.go
  backend/api/go_http_client/visualization_client/visualization_service/create_visualization_responses.go
  backend/api/go_http_client/visualization_client/visualization_service/visualization_service_client.go
  backend/api/swagger/visualization.swagger.json
  backend/api/visualization.proto
Labels: approved, lgtm, size/L

#3603 [UI] Migrate to namespaced visualization request
  frontend/src/apis/experiment/api.ts
  frontend/src/apis/visualization/api.ts
  frontend/src/lib/Apis.ts
  frontend/src/lib/OutputArtifactLoader.ts
  frontend/src/pages/RunDetails.tsx
Labels: approved, area/frontend, cuj/multi-user, kind/feature, lgtm

#3602 [UI] Show cached steps
  frontend/src/lib/StatusUtils.test.tsx
  frontend/src/lib/StatusUtils.ts
  frontend/src/lib/WorkflowParser.ts
  frontend/src/pages/Status.tsx
  frontend/src/pages/__snapshots__/Status.test.tsx.snap
Labels: approved, area/frontend, kind/feature, lgtm, size/XL

#3610 Add index on run details on experiment UUID & conditions & finished time
  backend/src/apiserver/client_manager.go
Labels: approved, lgtm, needs-ok-to-test, size/XS

#3583 SDK - Compiler - Include the SDK version information in the compiled workflows
  sdk/python/kfp/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
Labels: approved, area/sdk, area/sdk/dsl/compiler, lgtm, size/M

#3501 [UI] get run id from both property and custom property
  frontend/src/lib/MlmdUtils.ts
Labels: approved, lgtm, size/XS

#3605 [UI] Fix artifact url for multi namespace
  frontend/src/components/MinioArtifactLink.test.tsx
  frontend/src/components/MinioArtifactLink.tsx
Labels: approved, area/frontend, kind/bug, lgtm, size/XS

#3598 Fixing volume size default value from 1 to 30
  components/aws/sagemaker/hyperparameter_tuning/README.md
  components/aws/sagemaker/hyperparameter_tuning/component.yaml
  components/aws/sagemaker/train/README.md
  components/aws/sagemaker/train/component.yaml
Labels: approved, lgtm, ok-to-test, size/S

#3622 SDK - Components - Task objects now have the .output attribute when component has only one output
  sdk/python/kfp/components/_structures.py
  sdk/python/tests/components/test_components.py
Labels: approved, area/sdk/components, lgtm, size/M

#3623 [Caching] Add a cached label for cached pods
  backend/src/cache/server/mutation.go
Labels: approved, area/backend, area/execution_cache, lgtm, size/XS

#3626 fix issue of creating default bucket
  manifests/gcp_marketplace/deployer/init_action.sh
Labels: approved, lgtm, size/S

#3619 [Viewer] Service needs port name for istio
  backend/src/crd/controller/viewer/reconciler/reconciler.go
  backend/src/crd/controller/viewer/reconciler/reconciler_test.go
Labels: approved, area/backend, lgtm, size/XS

#3627 [Backend] Authorization service
  backend/api/BUILD.bazel
  backend/api/auth.proto
  backend/api/go_client/BUILD.bazel
  backend/api/go_client/auth.pb.go
  backend/api/go_client/auth.pb.gw.go
  backend/api/swagger/auth.swagger.json
  backend/src/apiserver/main.go
  backend/src/apiserver/server/BUILD.bazel
  backend/src/apiserver/server/auth_server.go
  backend/src/apiserver/server/auth_server_test.go
  backend/src/apiserver/server/util.go
Labels: approved, area/backend, cuj/multi-user, kind/feature, lgtm, size/XL

#3578 [SDK] Add pod labels for telemetry purpose.
  sdk/python/kfp/compiler/_default_transformers.py
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/compiler/main.py
  sdk/python/tests/compiler/testdata/add_pod_env.yaml
  sdk/python/tests/compiler/testdata/artifact_location.yaml
  sdk/python/tests/compiler/testdata/basic.yaml
  sdk/python/tests/compiler/testdata/basic_no_decorator.yaml
  sdk/python/tests/compiler/testdata/coin.yaml
  sdk/python/tests/compiler/testdata/compose.yaml
  sdk/python/tests/compiler/testdata/default_value.yaml
  sdk/python/tests/compiler/testdata/imagepullsecrets.yaml
  sdk/python/tests/compiler/testdata/input_artifact_raw_value.yaml
  sdk/python/tests/compiler/testdata/loop_over_lightweight_output.yaml
  sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving.yaml
  sdk/python/tests/compiler/testdata/param_op_transform.yaml
  sdk/python/tests/compiler/testdata/param_substitutions.yaml
  sdk/python/tests/compiler/testdata/pipelineparams.yaml
  sdk/python/tests/compiler/testdata/preemptible_tpu_gpu.yaml
  sdk/python/tests/compiler/testdata/recursive_do_while.yaml
  sdk/python/tests/compiler/testdata/recursive_while.yaml
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
  sdk/python/tests/compiler/testdata/sidecar.yaml
  sdk/python/tests/compiler/testdata/timeout.yaml
  sdk/python/tests/compiler/testdata/volume.yaml
  sdk/python/tests/compiler/testdata/volume_snapshotop_rokurl.yaml
  sdk/python/tests/compiler/testdata/volume_snapshotop_sequential.yaml
  sdk/python/tests/compiler/testdata/volumeop_basic.yaml
  sdk/python/tests/compiler/testdata/volumeop_dag.yaml
  sdk/python/tests/compiler/testdata/volumeop_parallel.yaml
  sdk/python/tests/compiler/testdata/volumeop_sequential.yaml
  sdk/python/tests/compiler/testdata/withitem_basic.yaml
  sdk/python/tests/compiler/testdata/withitem_nested.yaml
  sdk/python/tests/compiler/testdata/withparam_global.yaml
  sdk/python/tests/compiler/testdata/withparam_global_dict.yaml
  sdk/python/tests/compiler/testdata/withparam_output.yaml
  sdk/python/tests/compiler/testdata/withparam_output_dict.yaml
Labels: approved, lgtm, size/L

#3620 SDK - Enabled file inputs to be optional
  sdk/python/kfp/components/_python_op.py
  sdk/python/tests/components/test_python_op.py
Labels: approved, area/sdk/components, lgtm, size/M

#3637 Components - Added readme for TFX components
  components/tfx/README.md
Labels: approved, area/components, lgtm, size/S

#3587 Add two scripts to load test our api endpoints with measurement of run durations and api call latencies
  tools/benchmarks/pipeline_service_api.ipynb
  tools/benchmarks/run_service_api.ipynb
Labels: lgtm, size/L

#3639 [UI] authorize tensorboard actions
  frontend/README.md
  frontend/package.json
  frontend/scripts/start-proxy-and-server.sh
  frontend/server/app.test.ts
  frontend/server/app.ts
  frontend/server/configs.ts
  frontend/server/handlers/artifacts.ts
  frontend/server/handlers/tensorboard.ts
  frontend/server/k8s-helper.ts
  frontend/server/package-lock.json
  frontend/server/package.json
  frontend/server/src/generated/apis/auth/.gitignore
  frontend/server/src/generated/apis/auth/.swagger-codegen-ignore
  frontend/server/src/generated/apis/auth/.swagger-codegen/VERSION
  frontend/server/src/generated/apis/auth/api.ts
  frontend/server/src/generated/apis/auth/configuration.ts
  frontend/server/src/generated/apis/auth/custom.d.ts
  frontend/server/src/generated/apis/auth/git_push.sh
  frontend/server/src/generated/apis/auth/index.ts
  frontend/server/tsconfig.json
  frontend/server/utils.ts
  frontend/src/components/viewers/Tensorboard.tsx
Labels: approved, area/frontend, cuj/multi-user, lgtm, size/XXL

#3641 Components - Upgraded the TFX components to 0.21.4
  components/tfx/Evaluator/component.py
  components/tfx/Evaluator/component.yaml
  components/tfx/ExampleGen/BigQueryExampleGen/component.py
  components/tfx/ExampleGen/BigQueryExampleGen/component.yaml
  components/tfx/ExampleGen/CsvExampleGen/component.py
  components/tfx/ExampleGen/CsvExampleGen/component.yaml
  components/tfx/ExampleGen/CsvExampleGen/with_URI_IO/component.py
  components/tfx/ExampleGen/CsvExampleGen/with_URI_IO/component.yaml
  components/tfx/ExampleGen/ImportExampleGen/component.py
  components/tfx/ExampleGen/ImportExampleGen/component.yaml
  components/tfx/ExampleValidator/component.py
  components/tfx/ExampleValidator/component.yaml
  components/tfx/SchemaGen/component.py
  components/tfx/SchemaGen/component.yaml
  components/tfx/StatisticsGen/component.py
  components/tfx/StatisticsGen/component.yaml
  components/tfx/Trainer/component.py
  components/tfx/Trainer/component.yaml
  components/tfx/Transform/component.py
  components/tfx/Transform/component.yaml
  components/tfx/_samples/TFX_pipeline.ipynb
Labels: approved, area/components, lgtm, size/XXL

#3561 [Test] Sort job resource references before equality check
  backend/test/integration/job_api_test.go
  backend/test/integration/run_api_test.go
Labels: approved, lgtm, size/M

#3634 Cache - Stabilized the deployer script
  backend/src/cache/deployer/deploy-cache-service.sh
Labels: approved, area/execution_cache, kind/bug, lgtm, priority/p0, size/M

#3653 Fix container.set_image_pull_policy documentation string
  sdk/python/kfp/dsl/_container_op.py
Labels: approved, lgtm, ok-to-test, size/XS

#3652 kfp_client: fix wrong check
  sdk/python/kfp/_client.py
Labels: approved, lgtm, ok-to-test, size/XS

#3614 SDK - Components - Split load_component functions into loading the spec and creating task factory
  sdk/python/kfp/components/_component_store.py
  sdk/python/kfp/components/_components.py
Labels: approved, area/sdk/components, lgtm, size/L

#3422 [Sample] Update base images used in pre-built samples
  backend/Dockerfile
Labels: approved, lgtm, size/S

#3657 Backend - Upgraded MLMD client to fix Metadata Writer
  backend/metadata_writer/requirements.in
  backend/metadata_writer/requirements.txt
Labels: approved, area/metadata-writer, size/XS

#3649 [Backend] Add service account field to run and job api objects
  backend/api/go_client/job.pb.go
  backend/api/go_client/run.pb.go
  backend/api/go_http_client/job_model/api_job.go
  backend/api/go_http_client/run_model/api_run.go
  backend/api/job.proto
  backend/api/run.proto
  backend/api/swagger/job.swagger.json
  backend/api/swagger/kfp_api_single_file.swagger.json
  backend/api/swagger/run.swagger.json
Labels: approved, area/backend, kind/feature, lgtm, size/L

#3662 Move namespace to cluster-scoped
  manifests/kustomize/base/cache-deployer/cluster-scoped/cache-deployer-clusterrolebinding.yaml
  manifests/kustomize/base/kustomization.yaml
  manifests/kustomize/base/params.yaml
  manifests/kustomize/cluster-scoped-resources/kustomization.yaml
  manifests/kustomize/cluster-scoped-resources/namespace.yaml
  manifests/kustomize/cluster-scoped-resources/params.env
  manifests/kustomize/cluster-scoped-resources/params.yaml
  manifests/kustomize/env/dev/kustomization.yaml
  manifests/kustomize/sample/README.md
  manifests/kustomize/sample/cluster-scoped-resources/kustomization.yaml
  manifests/kustomize/sample/cluster-scoped-resources/params.env
  manifests/kustomize/sample/kustomization.yaml
Labels: approved, lgtm, size/M

#3642 AWS Sagemaker : Add unit tests
  components/aws/sagemaker/Dockerfile
  components/aws/sagemaker/common/_utils.py
  components/aws/sagemaker/run_tests.py
  components/aws/sagemaker/tests/unit_tests/.gitignore
  components/aws/sagemaker/tests/unit_tests/Dockerfile
  components/aws/sagemaker/tests/unit_tests/README.md
  components/aws/sagemaker/tests/unit_tests/requirements.txt
  components/aws/sagemaker/tests/unit_tests/run_all_tests.sh
  components/aws/sagemaker/tests/unit_tests/tests/__init__.py
  components/aws/sagemaker/tests/unit_tests/tests/test_batch_transform.py
  components/aws/sagemaker/tests/unit_tests/tests/test_deploy.py
  components/aws/sagemaker/tests/unit_tests/tests/test_ground_truth.py
  components/aws/sagemaker/tests/unit_tests/tests/test_hpo.py
  components/aws/sagemaker/tests/unit_tests/tests/test_model.py
  components/aws/sagemaker/tests/unit_tests/tests/test_train.py
  components/aws/sagemaker/tests/unit_tests/tests/test_utils.py
  components/aws/sagemaker/tests/unit_tests/tests/test_workteam.py
Labels: approved, lgtm, ok-to-test, size/L

#3663 fix proxy URL issue
  proxy/attempt-register-vm-on-proxy.sh
Labels: approved, lgtm, size/S

#3665 continue #3663, sleep a while to wait for configmap
  proxy/attempt-register-vm-on-proxy.sh
Labels: approved, lgtm, size/XS
