Repository kubeflow/pipelines, pull requests merged in 2020-06, with the labels that each got.

#3758 More documentation on backend API methods
  backend/api/experiment.proto
  backend/api/generate_api.sh
  backend/api/go_http_client/experiment_client/experiment_service/archive_experiment_parameters.go
  backend/api/go_http_client/experiment_client/experiment_service/experiment_service_client.go
  backend/api/go_http_client/experiment_client/experiment_service/list_experiment_parameters.go
  backend/api/go_http_client/experiment_client/experiment_service/unarchive_experiment_parameters.go
  backend/api/go_http_client/experiment_model/api_experiment.go
  backend/api/go_http_client/job_client/job_service/list_jobs_parameters.go
  backend/api/go_http_client/job_model/api_list_jobs_response.go
  backend/api/go_http_client/pipeline_client/pipeline_service/delete_pipeline_parameters.go
  backend/api/go_http_client/pipeline_client/pipeline_service/delete_pipeline_version_parameters.go
  backend/api/go_http_client/pipeline_client/pipeline_service/get_pipeline_parameters.go
  backend/api/go_http_client/pipeline_client/pipeline_service/get_pipeline_version_parameters.go
  backend/api/go_http_client/pipeline_client/pipeline_service/get_pipeline_version_template_parameters.go
  backend/api/go_http_client/pipeline_client/pipeline_service/get_template_parameters.go
  backend/api/go_http_client/pipeline_client/pipeline_service/list_pipeline_versions_parameters.go
  backend/api/go_http_client/pipeline_client/pipeline_service/list_pipelines_parameters.go
  backend/api/go_http_client/pipeline_client/pipeline_service/pipeline_service_client.go
  backend/api/go_http_client/pipeline_model/api_get_template_response.go
  backend/api/go_http_client/pipeline_model/api_list_pipeline_versions_response.go
  backend/api/go_http_client/pipeline_model/api_list_pipelines_response.go
  backend/api/go_http_client/pipeline_model/api_url.go
  backend/api/go_http_client/run_client/run_service/archive_run_parameters.go
  backend/api/go_http_client/run_client/run_service/delete_run_parameters.go
  backend/api/go_http_client/run_client/run_service/get_run_parameters.go
  backend/api/go_http_client/run_client/run_service/list_runs_parameters.go
  backend/api/go_http_client/run_client/run_service/retry_run_parameters.go
  backend/api/go_http_client/run_client/run_service/run_service_client.go
  backend/api/go_http_client/run_client/run_service/terminate_run_parameters.go
  backend/api/go_http_client/run_client/run_service/unarchive_run_parameters.go
  backend/api/go_http_client/run_model/api_list_runs_response.go
  backend/api/go_http_client/run_model/api_run.go
  backend/api/job.proto
  backend/api/pipeline.proto
  backend/api/run.proto
  backend/api/swagger/experiment.swagger.json
  backend/api/swagger/job.swagger.json
  backend/api/swagger/kfp_api_single_file.swagger.json
  backend/api/swagger/pipeline.swagger.json
  backend/api/swagger/run.swagger.json
Labels: lgtm, size/XL

#3842 [Backend] Fix user identity extraction logic in getUserIdentity()
  backend/src/apiserver/server/util.go
  backend/src/apiserver/server/util_test.go
Labels: approved, area/backend, cuj/multi-user, lgtm, size/M

#3879 SDK - Components - Stabilize JSON serialization by sorting keys
  sdk/python/kfp/components/_data_passing.py
  sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving.yaml
Labels: approved, area/sdk/components, lgtm, size/XS

#3882 SDK - Normalize line endings when calculating component hash
  sdk/python/kfp/components/_components.py
Labels: approved, area/sdk/components, lgtm, size/XS

#3883 Components - Added the pipeline component repository marker file
  components/pipeline_component_repository.yaml
Labels: approved, area/components, lgtm, size/XS

#3878 SDK - Client - Use temporary directory context for pipeline package
  sdk/python/kfp/_client.py
Labels: approved, area/sdk/client, lgtm, size/XS

#3754 Fix the missing description in the CreatePipelineAPI
  backend/src/apiserver/server/pipeline_server.go
  backend/src/apiserver/server/pipeline_server_test.go
Labels: approved, lgtm, ok-to-test, size/XS

#3850 Adds job_id parameter.
  components/gcp/container/component_sdk/python/kfp_component/google/ml_engine/_create_job.py
  components/gcp/container/component_sdk/python/kfp_component/google/ml_engine/_train.py
  components/gcp/container/component_sdk/python/tests/google/ml_engine/test__create_job.py
  components/gcp/container/component_sdk/python/tests/google/ml_engine/test__train.py
  components/gcp/ml_engine/train/README.md
  components/gcp/ml_engine/train/component.yaml
  components/gcp/ml_engine/train/sample.ipynb
Labels: approved, lgtm, ok-to-test, size/M

#3889 Move the minio artifact download under try block
  components/aws/sagemaker/tests/integration_tests/component_tests/test_workteam_component.py
Labels: approved, lgtm, ok-to-test, size/XS

#3890 [Samples] Change the data url to point to ml-pipeline instead of ml-pipeline-playground
  samples/core/AutoML tables/AutoML Tables - Retail product stockout prediction.ipynb
  samples/core/dataflow/dataflow.ipynb
  samples/core/exit_handler/exit_handler.py
  samples/core/iris/iris.py
  samples/core/parallel_join/parallel_join.py
  samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py
  samples/core/secret/secret.py
  samples/core/sequential/sequential.py
  samples/core/xgboost_training_cm/xgboost_training_cm.py
Labels: approved, lgtm, size/M

#3893 fix typo on sort order: 'des' --> 'desc'
  backend/api/experiment.proto
  backend/api/job.proto
  backend/api/pipeline.proto
  backend/api/run.proto
  sdk/python/kfp/_client.py
Labels: approved, lgtm, size/S

#3898 Docs - Added docs for kfp_server_api.models
  docs/source/kfp.client.rst
Labels: approved, area/docs, lgtm, size/XS

#3895 [Api] Regenerate clients after proto description des -> desc fix
  backend/api/go_http_client/experiment_client/experiment_service/list_experiment_parameters.go
  backend/api/go_http_client/job_client/job_service/list_jobs_parameters.go
  backend/api/go_http_client/pipeline_client/pipeline_service/list_pipeline_versions_parameters.go
  backend/api/go_http_client/pipeline_client/pipeline_service/list_pipelines_parameters.go
  backend/api/go_http_client/run_client/run_service/list_runs_parameters.go
  backend/api/python_http_client/docs/ExperimentServiceApi.md
  backend/api/python_http_client/docs/JobServiceApi.md
  backend/api/python_http_client/docs/PipelineServiceApi.md
  backend/api/python_http_client/docs/RunServiceApi.md
  backend/api/python_http_client/kfp_server_api/api/experiment_service_api.py
  backend/api/python_http_client/kfp_server_api/api/job_service_api.py
  backend/api/python_http_client/kfp_server_api/api/pipeline_service_api.py
  backend/api/python_http_client/kfp_server_api/api/run_service_api.py
  backend/api/swagger/experiment.swagger.json
  backend/api/swagger/job.swagger.json
  backend/api/swagger/kfp_api_single_file.swagger.json
  backend/api/swagger/pipeline.swagger.json
  backend/api/swagger/run.swagger.json
Labels: approved, lgtm, size/M

#3777 [Release] Automate release script for all the changes
  .gitignore
  .release.cloudbuild.yaml
  RELEASE.md
  components/release-in-place.sh
  components/release.sh
  hack/release-imp.sh
  hack/release.sh
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml
  manifests/gcp_marketplace/hack/release.sh
  manifests/kustomize/hack/release.sh
  sdk/hack/release.sh
Labels: approved, area/release, kind/misc, lgtm, size/L

#3899 Docs - Moved the kfp_server_api documentation to a separate page
  docs/source/kfp.client.rst
  docs/source/kfp.server_api.rst
Labels: area/docs, size/M

#3909 [Testing] Fix build failure because wcwidth LICENSE url changed
  components/third_party_licenses.csv
Labels: kind/misc, size/XS

#3910 [Release] Regenerate api clients on release
  backend/api/build_kfp_server_api_python_package.sh
  backend/api/generate_api.sh
  hack/check-release-needed-tools.sh
  hack/release-imp.sh
  hack/release.sh
Labels: area/release, kind/misc, size/M

#3884 SDK - Components - Added ComponentStore search
  sdk/python/kfp/components/_component_store.py
  sdk/python/kfp/components/_key_value_store.py
Labels: approved, area/sdk/components, lgtm, size/L

#3892 create cluster using 'cloud-platform' scope
  manifests/gcp_marketplace/cli.md
Labels: approved, lgtm, size/XS

#3918 [Release] Various fixes to release script
  .cloudbuild.yaml
  .release.cloudbuild.yaml
  RELEASE.md
  manifests/kustomize/hack/release.sh
  sdk/python/requirements.in
  sdk/python/setup.py
Labels: area/release, do-not-merge/hold, kind/misc, size/S

#3921 [Release] Fix missing $TAG_NAME in .cloudbuild.yaml
  .cloudbuild.yaml
Labels: area/release, kind/bug, size/XS

#3924 [Release] Fix $(cat VERSION) not in bash script
  .cloudbuild.yaml
Labels: area/release, kind/misc, size/M

#3925 Cherry pick #3924: [Release] Fix $(cat VERSION) not in bash script
  .cloudbuild.yaml
Labels: size/M

#3926 Add Bobgy to OWNERS
  OWNERS
Labels: approved, kind/process, lgtm, size/XS

#3940 Only pending or running workflows are considered not-final
  backend/src/common/util/workflow.go
Labels: approved, lgtm, size/XS

#3934 [SDK] Fixes the length of component digest label
  sdk/python/kfp/compiler/_default_transformers.py
Labels: approved, lgtm, size/XS

#3912 Fix #3906 - mount_pvc transform should ignore non-ContainerOps
  sdk/python/kfp/dsl/_pipeline.py
  sdk/python/kfp/onprem.py
Labels: approved, lgtm, size/S

#3946 Cherry picking #3934
  sdk/python/kfp/compiler/_default_transformers.py
Labels: approved, lgtm, size/XS

#3949 Automated cherry pick of #3926: Add Bobgy to OWNERS
  OWNERS
Labels: size/XS

#3957 CherryPick: Only pending or running workflows are considered not-final (#3940)
  backend/src/common/util/workflow.go
Labels: approved, lgtm, size/XS

#3958 [Format] Format yaml files that will be automated
  hack/format.sh
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml
  manifests/gcp_marketplace/hack/format.sh
  manifests/gcp_marketplace/schema.yaml
  manifests/kustomize/base/kustomization.yaml
  manifests/kustomize/env/gcp/inverse-proxy/kustomization.yaml
  manifests/kustomize/hack/format.sh
Labels: approved, area/engprod, kind/misc, lgtm, size/L

#3959 [Backend] Filter run on status
  backend/src/apiserver/model/BUILD.bazel
  backend/src/apiserver/model/run.go
  backend/src/apiserver/model/run_test.go
Labels: approved, lgtm, size/M

#3973 [AWS SageMaker] Update GroundTruth integration test timeout
  components/aws/sagemaker/tests/integration_tests/resources/config/image-classification-groundtruth/config.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#3956 SDK - Compiler - Made compiler compatible with @wraps
  sdk/python/kfp/compiler/compiler.py
Labels: approved, area/sdk/dsl/compiler, lgtm, size/XS

#3851 Update Dataflow component _client.py to use projects.locations.templates API endpoint
  components/gcp/container/component_sdk/python/kfp_component/google/dataflow/_client.py
Labels: approved, lgtm, size/XS

#3979 Move the MNIST sample from tutorials to contrib
  samples/contrib/mnist/00_Kubeflow_Cluster_Setup.ipynb
  samples/contrib/mnist/01_Lightweight_Python_Components.ipynb
  samples/contrib/mnist/02_Local_Development_with_Docker_Image_Components.ipynb
  samples/contrib/mnist/03_Reusable_Components.ipynb
  samples/contrib/mnist/04_Reusable_and_Pre-build_Components_as_Pipeline.ipynb
  samples/contrib/mnist/OWNERS
  samples/contrib/mnist/README.md
Labels: approved, lgtm, size/XS

#3876 [AWS SageMaker] Add integration test for sample pipeline train
  components/aws/sagemaker/codebuild/integration-test.buildspec.yml
  components/aws/sagemaker/tests/integration_tests/Dockerfile
  components/aws/sagemaker/tests/integration_tests/README.md
  components/aws/sagemaker/tests/integration_tests/component_tests/test_train_component.py
  components/aws/sagemaker/tests/integration_tests/resources/config/spot-sample-pipeline-training/config.yaml
  components/aws/sagemaker/tests/integration_tests/resources/definition/training_pipeline.py
  components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests
  samples/contrib/aws-samples/simple_train_pipeline/training-pipeline.py
Labels: approved, lgtm, size/M

#3858 [Backend][Mutli-user] Allow shared read in the special multi-user mode.
  backend/src/apiserver/common/config.go
  backend/src/apiserver/server/experiment_server.go
  backend/src/apiserver/server/job_server.go
  backend/src/apiserver/server/run_server.go
Labels: approved, lgtm, size/S

#3953 [Doc] Cherry pick process for release branch
  RELEASE.md
Labels: approved, area/docs, kind/misc, lgtm, size/S

#3978 [Manifest] Apply kustomize best practices to standalone manifest
  manifests/kustomize/base/argo/workflow-controller-configmap.yaml
  manifests/kustomize/base/cache-deployer/cluster-scoped/cache-deployer-clusterrolebinding.yaml
  manifests/kustomize/base/cache-deployer/cluster-scoped/cache-deployer-sa.yaml
  manifests/kustomize/base/cache-deployer/cluster-scoped/kustomization.yaml
  manifests/kustomize/base/cache-deployer/kustomization.yaml
  manifests/kustomize/base/cache/cache-deployment.yaml
  manifests/kustomize/base/kustomization.yaml
  manifests/kustomize/base/metadata/metadata-grpc-deployment.yaml
  manifests/kustomize/base/mysql/kustomization.yaml
  manifests/kustomize/base/mysql/mysql-configmap.yaml
  manifests/kustomize/base/params.yaml
  manifests/kustomize/base/pipeline-application.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
  manifests/kustomize/cluster-scoped-resources/kustomization.yaml
  manifests/kustomize/cluster-scoped-resources/namespace.yaml
  manifests/kustomize/cluster-scoped-resources/params.env
  manifests/kustomize/cluster-scoped-resources/params.yaml
  manifests/kustomize/env/gcp/cloudsql-proxy/cloudsql-proxy-deployment.yaml
  manifests/kustomize/env/gcp/gcp-configurations-patch.yaml
  manifests/kustomize/env/gcp/gcp-default-config/gcp-default-configmap.yaml
  manifests/kustomize/env/gcp/gcp-default-config/kustomization.yaml
  manifests/kustomize/env/gcp/kustomization.yaml
  manifests/kustomize/env/gcp/minio-gcs-gateway/minio-gcs-gateway-deployment.yaml
  manifests/kustomize/sample/cluster-scoped-resources/kustomization.yaml
  manifests/kustomize/sample/cluster-scoped-resources/params.env
  manifests/kustomize/sample/kustomization.yaml
Labels: approved, area/deployment/kubeflow, area/deployment/standalone, kind/misc, lgtm, size/L

#3987 chore(manifests): add missing port name and other cleanups
  manifests/kustomize/base/pipeline/ml-pipeline-ui-role.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-ui-service.yaml
  manifests/kustomize/env/platform-agnostic/minio/minio-service.yaml
  manifests/kustomize/env/platform-agnostic/mysql/mysql-service.yaml
Labels: approved, lgtm, size/S

#3992 Cache - Deployer should check whether the secret is installed
  backend/src/cache/deployer/deploy-cache-service.sh
Labels: approved, area/execution_cache, lgtm, size/S

#3994 test: use e2 machines for cost saving
  test/deploy-cluster.sh
  test/presubmit-tests.gke.sh
Labels: approved, lgtm, size/M

#3905 [AWS Sagemaker] aws-samples kmeans-hpo pipeline test
  components/aws/sagemaker/tests/integration_tests/component_tests/test_groundtruth_component.py
  components/aws/sagemaker/tests/integration_tests/component_tests/test_hpo_component.py
  components/aws/sagemaker/tests/integration_tests/component_tests/test_train_component.py
  components/aws/sagemaker/tests/integration_tests/component_tests/test_workteam_component.py
  components/aws/sagemaker/tests/integration_tests/environment.yml
  components/aws/sagemaker/tests/integration_tests/resources/config/aws-samples-hpo-spot-training/config.yaml
  components/aws/sagemaker/tests/integration_tests/resources/config/image-classification-groundtruth/config.yaml
  components/aws/sagemaker/tests/integration_tests/resources/definition/create_endpoint_pipeline.py
  components/aws/sagemaker/tests/integration_tests/resources/definition/create_model_pipeline.py
  components/aws/sagemaker/tests/integration_tests/resources/definition/groundtruth_pipeline.py
  components/aws/sagemaker/tests/integration_tests/resources/definition/hpo_pipeline.py
  components/aws/sagemaker/tests/integration_tests/resources/definition/transform_job_pipeline.py
  components/aws/sagemaker/tests/integration_tests/resources/definition/workteam_pipeline.py
  components/aws/sagemaker/tests/integration_tests/utils/__init__.py
  components/aws/sagemaker/tests/integration_tests/utils/kfp_client_utils.py
  samples/contrib/aws-samples/mnist-kmeans-sagemaker/kmeans-hpo-pipeline.py
Labels: approved, lgtm, size/L

#3981 [SDK/client] Fixes authentication refreshing mechanism
  sdk/python/kfp/_client.py
Labels: approved, lgtm, size/M

#3848 Fix/log unavailable warning
  frontend/mock-backend/mock-api-middleware.ts
  frontend/server/handlers/pod-logs.ts
  frontend/src/Css.tsx
  frontend/src/components/Banner.test.tsx
  frontend/src/components/Banner.tsx
  frontend/src/components/PodYaml.test.tsx
  frontend/src/components/PodYaml.tsx
  frontend/src/components/__snapshots__/Banner.test.tsx.snap
  frontend/src/lib/Apis.test.ts
  frontend/src/lib/Apis.ts
  frontend/src/pages/RunDetails.test.tsx
  frontend/src/pages/RunDetails.tsx
  frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
Labels: approved, lgtm, ok-to-test, size/L

#4004 Metadata Writer - Stopped using artifact properties
  backend/metadata_writer/src/metadata_helpers.py
Labels: approved, area/metadata-writer, lgtm, size/S

#3844 Components - CatBoost
  components/CatBoost/Predict_class_probabilities/from_CSV/component.py
  components/CatBoost/Predict_class_probabilities/from_CSV/component.yaml
  components/CatBoost/Predict_classes/from_CSV/component.py
  components/CatBoost/Predict_classes/from_CSV/component.yaml
  components/CatBoost/Predict_values/from_CSV/component.py
  components/CatBoost/Predict_values/from_CSV/component.yaml
  components/CatBoost/Train_classifier/from_CSV/component.py
  components/CatBoost/Train_classifier/from_CSV/component.yaml
  components/CatBoost/Train_regression/from_CSV/component.py
  components/CatBoost/Train_regression/from_CSV/component.yaml
  components/CatBoost/_samples/sample_pipeline.py
  components/CatBoost/convert_CatBoostModel_to_AppleCoreMLModel/component.py
  components/CatBoost/convert_CatBoostModel_to_AppleCoreMLModel/component.yaml
  components/CatBoost/convert_CatBoostModel_to_ONNX/component.py
  components/CatBoost/convert_CatBoostModel_to_ONNX/component.yaml
Labels: approved, area/components, lgtm, size/XXL

#4002 SDK - Simplified the style config
  .style.yapf
Labels: approved, area/sdk, lgtm, size/XS

#3995 doc(release): detailed release steps and commands
  RELEASE.md
Labels: approved, lgtm, size/M

#4006 Fix #3980 - mockapi tsconfig should reference root dir correctly
  frontend/mock-backend/tsconfig.json
Labels: approved, lgtm, size/XS

#4008 [Frontend] Enable pagination when expanding experiment in both the home page and…
  frontend/src/components/ExperimentList.tsx
  frontend/src/pages/ExperimentList.tsx
Labels: approved, area/frontend, cherrypick-approved, lgtm, size/XS

#3944 [AWS SageMaker] Processing job component
  components/aws/sagemaker/Changelog.md
  components/aws/sagemaker/Dockerfile
  components/aws/sagemaker/THIRD-PARTY-LICENSES.txt
  components/aws/sagemaker/batch_transform/component.yaml
  components/aws/sagemaker/common/_utils.py
  components/aws/sagemaker/common/process.template.yaml
  components/aws/sagemaker/deploy/component.yaml
  components/aws/sagemaker/ground_truth/component.yaml
  components/aws/sagemaker/hyperparameter_tuning/component.yaml
  components/aws/sagemaker/model/component.yaml
  components/aws/sagemaker/process/README.md
  components/aws/sagemaker/process/component.yaml
  components/aws/sagemaker/process/src/process.py
  components/aws/sagemaker/tests/integration_tests/README.md
  components/aws/sagemaker/tests/integration_tests/component_tests/test_processing_component.py
  components/aws/sagemaker/tests/integration_tests/resources/config/kmeans-algo-mnist-processing/config.yaml
  components/aws/sagemaker/tests/integration_tests/resources/definition/processing_pipeline.py
  components/aws/sagemaker/tests/integration_tests/scripts/kmeans_preprocessing.py
  components/aws/sagemaker/tests/integration_tests/utils/sagemaker_utils.py
  components/aws/sagemaker/tests/unit_tests/tests/test_process.py
  components/aws/sagemaker/train/component.yaml
  components/aws/sagemaker/workteam/component.yaml
Labels: approved, lgtm, size/XL

#3985 Components - Pandas - Transform_DataFrame
  components/pandas/Transform_DataFrame/_samples/sample_pipeline.py
  components/pandas/Transform_DataFrame/in_ApacheParquet_format/component.py
  components/pandas/Transform_DataFrame/in_ApacheParquet_format/component.yaml
  components/pandas/Transform_DataFrame/in_CSV_format/component.py
  components/pandas/Transform_DataFrame/in_CSV_format/component.yaml
Labels: approved, area/components, lgtm, size/L

#3976 SDK - Components - Added authentication support for component loading functions
  sdk/python/kfp/components/_component_store.py
  sdk/python/kfp/components/_components.py
Labels: approved, area/sdk/components, lgtm, size/S

#3928 SDK/CLI: Implement CLI pipeline list-versions command
  sdk/python/kfp/_client.py
  sdk/python/kfp/cli/pipeline.py
Labels: approved, lgtm, ok-to-test, size/M

#4010 [AWS SageMaker] Add missing import statement
  components/aws/sagemaker/hyperparameter_tuning/src/hyperparameter_tuning.py
Labels: approved, lgtm, ok-to-test, size/XS

#4011 [AWS SageMaker] Component 0.4.1 Release
  components/aws/sagemaker/Changelog.md
  components/aws/sagemaker/THIRD-PARTY-LICENSES.txt
  components/aws/sagemaker/batch_transform/component.yaml
  components/aws/sagemaker/deploy/component.yaml
  components/aws/sagemaker/ground_truth/component.yaml
  components/aws/sagemaker/hyperparameter_tuning/component.yaml
  components/aws/sagemaker/model/component.yaml
  components/aws/sagemaker/process/component.yaml
  components/aws/sagemaker/train/component.yaml
  components/aws/sagemaker/workteam/component.yaml
Labels: approved, lgtm, size/S

#3968 Update travis CI status badge to use .com version instead of outdated .org version
  README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#3982 MetadataStore:Update metadata grpc server image to use version 0.22.1
  .cloudbuild.yaml
  .release.cloudbuild.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/metadata.yaml
  manifests/kustomize/base/metadata/metadata-grpc-deployment.yaml
  test/tag_for_hosted.sh
Labels: approved, lgtm, size/S

#4012 [Cherrypick] Enable pagination when expanding experiment in both the home page and…
  frontend/src/components/ExperimentList.tsx
  frontend/src/pages/ExperimentList.tsx
Labels: approved, lgtm, size/XS

#4005 Reduce ttl of persisted final workflow to 1 day
  backend/Dockerfile.persistenceagent
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml
Labels: approved, area/development, lgtm, size/XS

#4007 doc(release): cherry pick process and PR template
  .github/pull_request_template.md
  RELEASE.md
Labels: approved, lgtm, size/S

#4018 chore: fix subprocess32 license url
  components/third_party_licenses.csv
Labels: approved, cherrypick-approved, lgtm, size/XS

#3930 SDK/CLI: Allow to use version properly with kfp run submit
  sdk/python/kfp/cli/run.py
Labels: approved, lgtm, ok-to-test, size/XS

#4015 chore(marketplace): fix version in release note
  manifests/gcp_marketplace/hack/release.sh
  manifests/gcp_marketplace/schema.yaml
Labels: approved, cherrypicked, lgtm, size/XS

#4027 Metadata-Writer: Updates metadata writer to use mlmd 0.22.0
  backend/metadata_writer/requirements.in
  backend/metadata_writer/requirements.txt
Labels: approved, cherrypick-approved, lgtm, size/XS

#4025 Docs - Show inherited members in the kfp.dsl docs
  docs/source/kfp.dsl.rst
Labels: approved, area/docs, lgtm, size/XS

#4014 chore(release): instructions for updating version in kubeflow.org
  RELEASE.md
Labels: approved, lgtm, size/M

#4029 chore: recommend cherrypick-approved label in PR template
  .github/pull_request_template.md
Labels: approved, lgtm, size/XS

#3954 [AWS SageMaker] Print SageMaker job logs in kfp UI
  components/aws/sagemaker/Changelog.md
  components/aws/sagemaker/THIRD-PARTY-LICENSES.txt
  components/aws/sagemaker/batch_transform/component.yaml
  components/aws/sagemaker/batch_transform/src/batch_transform.py
  components/aws/sagemaker/common/_utils.py
  components/aws/sagemaker/deploy/component.yaml
  components/aws/sagemaker/ground_truth/component.yaml
  components/aws/sagemaker/hyperparameter_tuning/component.yaml
  components/aws/sagemaker/model/component.yaml
  components/aws/sagemaker/process/component.yaml
  components/aws/sagemaker/process/src/process.py
  components/aws/sagemaker/train/component.yaml
  components/aws/sagemaker/train/src/train.py
  components/aws/sagemaker/workteam/component.yaml
Labels: approved, lgtm, ok-to-test, size/M

#3340 [SDK] Add list_pipeline_versions to kfp.Client
  sdk/python/kfp/_client.py
Labels: approved, lgtm, needs-ok-to-test, size/S

#4032 Components - CatBoost - Fixed small bug in sample
  components/CatBoost/_samples/sample_pipeline.py
Labels: approved, area/components, lgtm, size/XS

#4034 chore: improve writing for cherry pick process
  .github/pull_request_template.md
Labels: approved, cherrypick-approved, lgtm, size/S

#4037 Metadata Writer - Added timeouts
  backend/metadata_writer/src/metadata_writer.py
Labels: approved, area/metadata-writer, cherrypick-approved, lgtm, priority/p0, size/XS

#3900 better native-keras based sample
  backend/src/apiserver/config/sample_config.json
  frontend/src/config/sample_config_from_backend.json
  frontend/src/pages/GettingStarted.test.tsx
  frontend/src/pages/GettingStarted.tsx
  frontend/src/pages/__snapshots__/GettingStarted.test.tsx.snap
Labels: approved, cherrypick-approved, lgtm, size/L

#4039 Components - XGBoost - Parsing CSV using pandas
  components/XGBoost/Predict/component.py
  components/XGBoost/Predict/component.yaml
  components/XGBoost/Train/component.py
  components/XGBoost/Train/component.yaml
Labels: approved, area/components, lgtm, size/L

#4031 Components - Converters from ApacheParquet to CSV and TSV
  components/_converters/ApacheParquet/_samples/sample_pipeline.py
  components/_converters/ApacheParquet/to_CSV/component.py
  components/_converters/ApacheParquet/to_CSV/component.yaml
  components/_converters/ApacheParquet/to_TSV/component.py
  components/_converters/ApacheParquet/to_TSV/component.yaml
Labels: approved, area/components, lgtm, size/L

#4035 Components - XGBoost - Train and Predict from Apache Parquet
  components/XGBoost/Predict/from_ApacheParquet/component.py
  components/XGBoost/Predict/from_ApacheParquet/component.yaml
  components/XGBoost/Train/from_ApacheParquet/component.py
  components/XGBoost/Train/from_ApacheParquet/component.yaml
  components/XGBoost/_samples/sample_pipeline.py
Labels: approved, area/components, lgtm, size/L

#4042 Components - pandas - Transform DataFrame - Fixed transforms that replace dataframe
  components/pandas/Transform_DataFrame/_samples/sample_pipeline.py
  components/pandas/Transform_DataFrame/in_ApacheParquet_format/component.py
  components/pandas/Transform_DataFrame/in_ApacheParquet_format/component.yaml
  components/pandas/Transform_DataFrame/in_CSV_format/component.py
  components/pandas/Transform_DataFrame/in_CSV_format/component.yaml
Labels: approved, area/components, lgtm, size/M

#4050 Components - Calculate_regression_metrics
  components/ml_metrics/Calculate_regression_metrics/_samples/sample_pipleine.py
  components/ml_metrics/Calculate_regression_metrics/from_CSV/component.py
  components/ml_metrics/Calculate_regression_metrics/from_CSV/component.yaml
Labels: approved, area/components, lgtm, size/L

#4043 chore: set up stale bot to focus on important issues
  .github/stale.yml
Labels: approved, lgtm, lifecycle/frozen, size/S

#4052 [Backend] Bug fix: applying filter in listing versions
  backend/src/apiserver/storage/pipeline_store.go
  backend/src/apiserver/storage/pipeline_store_test.go
Labels: approved, area/backend, cherrypick-approved, lgtm, size/M

#4033 chore(release): set up conventional commit changelog tool. Part of #3920
  .github/pull_request_template.md
  CONTRIBUTING.md
  VERSION
  hack/check-release-needed-tools.sh
  hack/release-imp.sh
  hack/release.sh
  package-lock.json
  package.json
  release/OWNERS
  release/RELEASE.md
Labels: approved, cherrypick-approved, lgtm, size/XXL

#4047 doc(sdk/client): fix kfp-server-api py client's docstring format
  backend/api/python_http_client/kfp_server_api/api/experiment_service_api.py
  backend/api/python_http_client/kfp_server_api/api/job_service_api.py
  backend/api/python_http_client/kfp_server_api/api/pipeline_service_api.py
  backend/api/python_http_client/kfp_server_api/api/pipeline_upload_service_api.py
  backend/api/python_http_client/kfp_server_api/api/run_service_api.py
  backend/api/python_http_client/kfp_server_api/models/api_cron_schedule.py
  backend/api/python_http_client/kfp_server_api/models/api_experiment.py
  backend/api/python_http_client/kfp_server_api/models/api_get_template_response.py
  backend/api/python_http_client/kfp_server_api/models/api_job.py
  backend/api/python_http_client/kfp_server_api/models/api_list_experiments_response.py
  backend/api/python_http_client/kfp_server_api/models/api_list_jobs_response.py
  backend/api/python_http_client/kfp_server_api/models/api_list_pipeline_versions_response.py
  backend/api/python_http_client/kfp_server_api/models/api_list_pipelines_response.py
  backend/api/python_http_client/kfp_server_api/models/api_list_runs_response.py
  backend/api/python_http_client/kfp_server_api/models/api_parameter.py
  backend/api/python_http_client/kfp_server_api/models/api_periodic_schedule.py
  backend/api/python_http_client/kfp_server_api/models/api_pipeline.py
  backend/api/python_http_client/kfp_server_api/models/api_pipeline_runtime.py
  backend/api/python_http_client/kfp_server_api/models/api_pipeline_spec.py
  backend/api/python_http_client/kfp_server_api/models/api_pipeline_version.py
  backend/api/python_http_client/kfp_server_api/models/api_read_artifact_response.py
  backend/api/python_http_client/kfp_server_api/models/api_report_run_metrics_request.py
  backend/api/python_http_client/kfp_server_api/models/api_report_run_metrics_response.py
  backend/api/python_http_client/kfp_server_api/models/api_resource_key.py
  backend/api/python_http_client/kfp_server_api/models/api_resource_reference.py
  backend/api/python_http_client/kfp_server_api/models/api_run.py
  backend/api/python_http_client/kfp_server_api/models/api_run_detail.py
  backend/api/python_http_client/kfp_server_api/models/api_run_metric.py
  backend/api/python_http_client/kfp_server_api/models/api_status.py
  backend/api/python_http_client/kfp_server_api/models/api_trigger.py
  backend/api/python_http_client/kfp_server_api/models/api_url.py
  backend/api/python_http_client/kfp_server_api/models/protobuf_any.py
  backend/api/python_http_client/kfp_server_api/models/report_run_metrics_response_report_run_metric_result.py
  backend/api/python_http_client_template/api.mustache
  backend/api/python_http_client_template/model.mustache
Labels: approved, cherrypick-approved, lgtm, size/XXL

#4026 MetadataStore: Update to release metadata-envoy in each release
  .release.cloudbuild.yaml
  manifests/kustomize/base/kustomization.yaml
  manifests/kustomize/base/metadata/metadata-envoy-deployment.yaml
  test/cloudbuild/batch_build.yaml
  test/deploy-pipeline-lite.sh
Labels: approved, cherrypick-approved, lgtm, size/S

#3969 Docs - Mention the Bazel version requirements in the README.md
  backend/README.md
Labels: approved, lgtm, size/XS

#3999 Validate resourcekey to prevent apiserver being panic for invalid inputs
  backend/src/apiserver/server/pipeline_server.go
  backend/src/apiserver/server/pipeline_server_test.go
Labels: approved, area/backend, cherrypick-approved, lgtm, ok-to-test, size/S

#4053 SDK - Compiler - Fixed error message
  sdk/python/kfp/compiler/compiler.py
Labels: approved, area/sdk/dsl/compiler, lgtm, size/XS

#4057 SDK - Tests - Fixed two test failures in hermetic systems
  sdk/python/kfp/components_tests/test_components.py
Labels: approved, area/sdk/tests, lgtm, size/S

#4054 SDK - Components - Python - Switched the default base image to python 3.7
  sdk/python/kfp/components/_python_op.py
  sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving.yaml
Labels: approved, area/sdk, area/sdk/components, area/sdk/components/python_container_op, cherrypick-approved, lgtm, size/S

#3371 SDK - Compiler - Added support for volume-based data passing
  sdk/python/kfp/compiler/_data_passing_using_volume.py
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/dsl/_pipeline.py
  sdk/python/kfp/dsl/data_passing_methods.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/artifact_passing_using_volume.py
  sdk/python/tests/compiler/testdata/artifact_passing_using_volume.yaml
  sdk/python/tests/compiler/testdata/test_data/consume_2.component.yaml
  sdk/python/tests/compiler/testdata/test_data/process_2_2.component.yaml
  sdk/python/tests/compiler/testdata/test_data/produce_2.component.yaml
Labels: approved, area/sdk/dsl, area/sdk/dsl/compiler, lgtm, size/L

#4065 refactor(deployment): use minio artifact secret as single source of truth
  manifests/kustomize/base/argo/kustomization.yaml
  manifests/kustomize/base/argo/minio-artifact-secret.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-ui-deployment.yaml
  manifests/kustomize/env/gcp/minio-gcs-gateway/kustomization.yaml
  manifests/kustomize/env/gcp/minio-gcs-gateway/minio-artifact-secret.env
  manifests/kustomize/env/gcp/minio-gcs-gateway/minio-gcs-gateway-deployment.yaml
  manifests/kustomize/env/platform-agnostic/minio/kustomization.yaml
  manifests/kustomize/env/platform-agnostic/minio/minio-artifact-secret.env
  manifests/kustomize/env/platform-agnostic/minio/minio-deployment.yaml
Labels: approved, cherrypick-approved, lgtm, size/M

#3914 Components - Added more GCP BigQuery components
  components/gcp/bigquery/query/to_CSV/README.md
  components/gcp/bigquery/query/to_CSV/component.yaml
  components/gcp/bigquery/query/to_gcs/README.md
  components/gcp/bigquery/query/to_gcs/component.yaml
  components/gcp/bigquery/query/to_table/README.md
  components/gcp/bigquery/query/to_table/component.yaml
  components/gcp/container/Dockerfile
  components/gcp/container/component_sdk/python/kfp_component/google/bigquery/_query.py
Labels: approved, lgtm, size/XL

#4088 chore: Rollback telemetry related changes
  sdk/python/kfp/compiler/_default_transformers.py
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/compiler/main.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/add_pod_env.yaml
  sdk/python/tests/compiler/testdata/artifact_location.yaml
  sdk/python/tests/compiler/testdata/basic.yaml
  sdk/python/tests/compiler/testdata/basic_no_decorator.yaml
  sdk/python/tests/compiler/testdata/coin.yaml
  sdk/python/tests/compiler/testdata/compose.yaml
  sdk/python/tests/compiler/testdata/default_value.yaml
  sdk/python/tests/compiler/testdata/imagepullsecrets.yaml
  sdk/python/tests/compiler/testdata/input_artifact_raw_value.yaml
  sdk/python/tests/compiler/testdata/loop_over_lightweight_output.yaml
  sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving.yaml
  sdk/python/tests/compiler/testdata/param_op_transform.yaml
  sdk/python/tests/compiler/testdata/param_substitutions.yaml
  sdk/python/tests/compiler/testdata/pipelineparams.yaml
  sdk/python/tests/compiler/testdata/preemptible_tpu_gpu.yaml
  sdk/python/tests/compiler/testdata/recursive_do_while.yaml
  sdk/python/tests/compiler/testdata/recursive_while.yaml
  sdk/python/tests/compiler/testdata/resourceop_basic.yaml
  sdk/python/tests/compiler/testdata/sidecar.yaml
  sdk/python/tests/compiler/testdata/timeout.yaml
  sdk/python/tests/compiler/testdata/volume.yaml
  sdk/python/tests/compiler/testdata/volume_snapshotop_rokurl.yaml
  sdk/python/tests/compiler/testdata/volume_snapshotop_sequential.yaml
  sdk/python/tests/compiler/testdata/volumeop_basic.yaml
  sdk/python/tests/compiler/testdata/volumeop_dag.yaml
  sdk/python/tests/compiler/testdata/volumeop_parallel.yaml
  sdk/python/tests/compiler/testdata/volumeop_sequential.yaml
  sdk/python/tests/compiler/testdata/withitem_basic.yaml
  sdk/python/tests/compiler/testdata/withitem_nested.yaml
  sdk/python/tests/compiler/testdata/withparam_global.yaml
  sdk/python/tests/compiler/testdata/withparam_global_dict.yaml
  sdk/python/tests/compiler/testdata/withparam_output.yaml
  sdk/python/tests/compiler/testdata/withparam_output_dict.yaml
Labels: approved, lgtm, size/XL

#4072 refactor(deployment): move kustomization.yaml images to the lowest level package
  manifests/kustomize/base/cache-deployer/kustomization.yaml
  manifests/kustomize/base/cache/kustomization.yaml
  manifests/kustomize/base/kustomization.yaml
  manifests/kustomize/base/metadata/kustomization.yaml
  manifests/kustomize/base/metadata/metadata-grpc/kustomization.yaml
  manifests/kustomize/base/metadata/metadata-grpc/metadata-envoy-deployment.yaml
  manifests/kustomize/base/metadata/metadata-grpc/metadata-envoy-service.yaml
  manifests/kustomize/base/metadata/metadata-grpc/metadata-grpc-configmap.yaml
  manifests/kustomize/base/metadata/metadata-grpc/metadata-grpc-deployment.yaml
  manifests/kustomize/base/metadata/metadata-grpc/metadata-grpc-service.yaml
  manifests/kustomize/base/metadata/metadata-writer/kustomization.yaml
  manifests/kustomize/base/metadata/metadata-writer/metadata-writer-deployment.yaml
  manifests/kustomize/base/metadata/metadata-writer/metadata-writer-role.yaml
  manifests/kustomize/base/metadata/metadata-writer/metadata-writer-rolebinding.yaml
  manifests/kustomize/base/metadata/metadata-writer/metadata-writer-sa.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/hack/format.sh
  manifests/kustomize/hack/release.sh
Labels: approved, cherrypick-approved, lgtm, size/L

#4071 refactor(deployment): separate metadata-writer and metadata-grpc folders
  manifests/kustomize/base/metadata/kustomization.yaml
  manifests/kustomize/base/metadata/metadata-envoy-deployment.yaml
  manifests/kustomize/base/metadata/metadata-envoy-service.yaml
  manifests/kustomize/base/metadata/metadata-grpc-configmap.yaml
  manifests/kustomize/base/metadata/metadata-grpc-deployment.yaml
  manifests/kustomize/base/metadata/metadata-grpc-service.yaml
  manifests/kustomize/base/metadata/metadata-grpc/kustomization.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/base/pipeline/metadata-writer/kustomization.yaml
  manifests/kustomize/base/pipeline/metadata-writer/metadata-writer-deployment.yaml
  manifests/kustomize/base/pipeline/metadata-writer/metadata-writer-role.yaml
  manifests/kustomize/base/pipeline/metadata-writer/metadata-writer-rolebinding.yaml
  manifests/kustomize/base/pipeline/metadata-writer/metadata-writer-sa.yaml
  manifests/kustomize/hack/format.sh
  manifests/kustomize/hack/release.sh
Labels: approved, cherrypick-approved, cla: yes, lgtm, size/M

#4098 fix(backend): allow empty userid header prefix. Fixes #4091
  backend/src/apiserver/main.go
  backend/src/apiserver/server/auth_server_test.go
Labels: approved, cherrypick-approved, cla: yes, lgtm, size/S

#4064 test(sdk): Travis - Fixed pipeline validation
  .travis.yml
Labels: approved, area/testing, cherrypick-approved, cla: yes, lgtm, size/XS

#4067 Components - XGBoost - Added the recursive training pipeline
  components/XGBoost/_samples/recursive_training.py
Labels: approved, area/components, lgtm, size/M

#4103 test(sdk) Restored the ParallelFor compiler test data
  sdk/python/tests/compiler/testdata/artifact_passing_using_volume.yaml
  sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving.yaml
Labels: approved, area/sdk/tests, cherrypick-approved, cla: yes, lgtm, priority/p0, size/L

#4109 Fix(component): Update default TensorFlow version for Watson ML example
  components/ibm-components/watson/store/component.yaml
  components/ibm-components/watson/train/component.yaml
  components/ibm-components/watson/train/src/wml-train.py
  samples/contrib/ibm-samples/watson/watson_train_serve_pipeline.py
Labels: approved, cla: yes, lgtm, size/XS

#3369 Fix typo in error message
  sdk/python/kfp/_client.py
Labels: approved, lgtm, ok-to-test, size/XS

#3904 feat(backend): Make number of persistence worker goroutine configurable
  backend/Dockerfile.persistenceagent
  backend/src/agent/persistence/main.go
  manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml
Labels: approved, lgtm, ok-to-test, size/S

#4105 docs(release): introduce release schedule, refine instructions
  RELEASE.md
Labels: approved, cla: yes, lgtm, size/L

#4051 [AWS SageMaker] Add unit tests for cloudwatch logs
  components/aws/sagemaker/tests/unit_tests/run_all_tests.sh
  components/aws/sagemaker/tests/unit_tests/tests/test_batch_transform.py
  components/aws/sagemaker/tests/unit_tests/tests/test_deploy.py
  components/aws/sagemaker/tests/unit_tests/tests/test_ground_truth.py
  components/aws/sagemaker/tests/unit_tests/tests/test_hpo.py
  components/aws/sagemaker/tests/unit_tests/tests/test_model.py
  components/aws/sagemaker/tests/unit_tests/tests/test_process.py
  components/aws/sagemaker/tests/unit_tests/tests/test_train.py
  components/aws/sagemaker/tests/unit_tests/tests/test_utils.py
  components/aws/sagemaker/tests/unit_tests/tests/test_workteam.py
Labels: approved, cla: yes, lgtm, size/M

#4009 [AWS SageMaker] Processing job sample
  components/aws/sagemaker/README.md
  components/aws/sagemaker/tests/integration_tests/component_tests/test_hpo_component.py
  components/aws/sagemaker/tests/integration_tests/resources/config/aws-samples-hpo-spot-training/config.yaml
  samples/contrib/aws-samples/README.md
  samples/contrib/aws-samples/mnist-kmeans-sagemaker/README.md
  samples/contrib/aws-samples/mnist-kmeans-sagemaker/kmeans-hpo-pipeline.py
  samples/contrib/aws-samples/mnist-kmeans-sagemaker/kmeans_preprocessing.py
  samples/contrib/aws-samples/mnist-kmeans-sagemaker/mnist-classification-pipeline.py
  samples/contrib/aws-samples/simple_train_pipeline/README.md
Labels: approved, cla: yes, lgtm, size/XL
