Repository kubeflow/pipelines, pull requests merged in 2020-12, with the labels that each got.

#4818 fix(frontend): Fix the yaml cannot show in Safari browser issue. Fixes #4727
  frontend/src/pages/PipelineDetails.tsx
  frontend/src/pages/__snapshots__/PipelineDetails.test.tsx.snap
Labels: approved, cla: yes, lgtm, size/S

#4852 test: pin pip to fix a weird version resolution logic
  test/presubmit-tests-tfx.sh
Labels: approved, cla: yes, lgtm, size/XS

#4851 chore(sdk.v2): Error out on invalid pipeline name
  sdk/python/kfp/v2/compiler/compiler.py
  sdk/python/kfp/v2/compiler/compiler_test.py
  sdk/python/kfp/v2/compiler/compiler_utils.py
  sdk/python/kfp/v2/compiler/compiler_utils_test.py
Labels: approved, cla: yes, lgtm, size/M

#4845 [Doc] update docs that still refer to KFP latest SDK reference
  README.md
  docs/release/feature-stages.md
  sdk/python/kfp/dsl/_container_op.py
Labels: approved, cla: yes, lgtm, size/S

#4859 chore(release): upgrade mlmd to 0.25.1
  .cloudbuild.yaml
  .release.cloudbuild.yaml
  backend/metadata_writer/README.md
  backend/metadata_writer/requirements.in
  backend/metadata_writer/requirements.txt
  backend/update_requirements.sh
  manifests/kustomize/base/metadata/metadata-grpc-deployment.yaml
  test/tag_for_hosted.sh
Labels: approved, cla: yes, lgtm, size/M

#4864 chore: Add chensun to SDK owner
  sdk/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#4866 chore(release): update @kubeflow/frontend to include MLMD client upgrade to 0.25.1
  frontend/package-lock.json
  frontend/package.json
Labels: approved, cla: yes, lgtm, size/L

#4867 docs(release): add note for expected postsubmit failure in RELEASE.md
  RELEASE.md
Labels: approved, cla: yes, lgtm, size/XS

#4869 docs(release): updating release descriptions on step11
  RELEASE.md
Labels: approved, cla: yes, lgtm, size/XS

#4855 chore(sdk): bump sdk's dependency on kfp-server-api
  sdk/python/setup.py
Labels: approved, cla: yes, lgtm, size/XS

#4868 docs(release): introduce how to find cloudbuild status
  RELEASE.md
Labels: approved, cla: yes, lgtm, size/XS

#4737 chore(sdk): v2.components code cleanup
  sdk/python/kfp/v2/components/__init__.py
  sdk/python/kfp/v2/components/components.py
  sdk/python/kfp/v2/components/python_op.py
  sdk/python/kfp/v2/components/structures.py
  sdk/python/kfp/v2/dsl/_pipeline.py
  sdk/python/kfp/v2/dsl/component_bridge.py
Labels: approved, cla: yes, lgtm, size/XXL

#4870 chore(release): bump kfp sdk version to 1.1.2
  sdk/python/kfp/__init__.py
Labels: approved, cla: yes, lgtm, size/XS

#4881 [IR] Add deployment spec to IR spec.
  api/v2alpha1/pipeline_spec.proto
  api/v2alpha1/python/setup.py
Labels: approved, cla: yes, lgtm, size/XS

#4826 fix(components): Login to Dockerhub before running tests for Sa…
  components/aws/sagemaker/codebuild/integration-test.buildspec.yml
  components/aws/sagemaker/codebuild/unit-test.buildspec.yml
Labels: approved, area/components/aws/sagemaker, cla: yes, lgtm, size/XS

#4884 fix(backend): job api -- deletion/disabling should succeed when swf not found. Fixes #4871
  backend/src/apiserver/client/scheduled_workflow_fake.go
  backend/src/apiserver/client/swf.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/common/util/error.go
  backend/test/integration/job_api_test.go
Labels: approved, cla: yes, lgtm, size/L

#4883 chore: add OWNER file to api folder
  api/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#4882 chore: Bump kfp-pipeline-spec to 0.1.3.1
  api/v2alpha1/python/setup.py
Labels: approved, cla: yes, lgtm, size/XS

#4885 test: added kfp functional e2e test
  test/kfp-functional-test/README.md
  test/kfp-functional-test/constants.py
  test/kfp-functional-test/kfp-functional-test.sh
  test/kfp-functional-test/requirements.in
  test/kfp-functional-test/requirements.txt
  test/kfp-functional-test/run_kfp_functional_test.py
Labels: approved, cla: yes, lgtm, size/L

#4858 feat(sdk): add ability to set retry policy
  sdk/python/kfp/compiler/_op_to_template.py
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/tests/compiler/compiler_tests.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#4893 chore(backend): delete outdated backend/api/Makefile. Fixes #4717
  backend/api/Makefile
Labels: approved, cla: yes, lgtm, size/L

#4861 feat(sdk): Components - Restored stack traces in lightweight python components. Fixes #4273, #4849
  sdk/python/kfp/components/_python_op.py
  sdk/python/kfp/containers/_component_builder.py
  sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving.yaml
Labels: approved, area/sdk/components, cla: yes, lgtm, size/L

#4837 feat(sdk): Add settings of the dnsConfig field. Fixes #4836
  samples/core/dns_config/dns_config.py
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/dsl/_pipeline.py
  sdk/python/tests/compiler/compiler_tests.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#4896 docs(backend): clean up readme
  backend/README.md
Labels: approved, cla: yes, lgtm, size/S

#4895 feat(SDK): adds Artifact base class.
  sdk/python/kfp/v2/dsl/artifact.py
  sdk/python/kfp/v2/dsl/artifact_test.py
  sdk/python/requirements.in
  sdk/python/requirements.txt
Labels: approved, cla: yes, lgtm, size/XL

#4902 test(cache): fix cache deployer image build in apk add command
  backend/src/cache/deployer/Dockerfile
Labels: approved, cla: yes, lgtm, size/S

#4875 fix(frontend): Use task_display_name annotation when displaying run metrics
  frontend/src/lib/CompareUtils.test.ts
  frontend/src/lib/CompareUtils.ts
  frontend/src/lib/ParserUtils.ts
  frontend/src/lib/WorkflowParser.ts
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#4899 docs(sdk): update comments of _create_job_config
  sdk/python/kfp/_client.py
Labels: approved, cla: yes, lgtm, size/S

#4788 feat(sdk): allow calling GroupOp.after with multiple ops
  sdk/python/kfp/dsl/_ops_group.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#4907 fix(frontend): fixed getting executions failure. Fixes #4903
  frontend/package-lock.json
  frontend/package.json
Labels: approved, cla: yes, lgtm, size/XS

#4904 fix(sdk): make healthz exception visible in logs by default
  sdk/python/kfp/_client.py
Labels: approved, cla: yes, lgtm, size/XS

#4901 feat(sdk): Add artifact ontology and migrate compiler utils to onboard artifact types
  sdk/python/kfp/v2/compiler_cli_tests/test_data/component_yaml/fancy_trainer_component.yaml
  sdk/python/kfp/v2/compiler_cli_tests/test_data/component_yaml/ingestion_component.yaml
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_ontology.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_ontology.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_resource_spec.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_resource_spec.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_various_io_types.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/simple_pipeline_without_importer.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/two_step_pipeline_with_importer.json
  sdk/python/kfp/v2/dsl/artifact.py
  sdk/python/kfp/v2/dsl/artifact_test.py
  sdk/python/kfp/v2/dsl/ontology_artifacts.py
  sdk/python/kfp/v2/dsl/ontology_artifacts_test.py
  sdk/python/kfp/v2/dsl/serialization_utils.py
  sdk/python/kfp/v2/dsl/serialization_utils_test.py
  sdk/python/kfp/v2/dsl/type_utils.py
  sdk/python/kfp/v2/dsl/type_utils_test.py
Labels: approved, cla: yes, lgtm, size/L

#4909 chore(sdk): bump kfp-server-api dependency to >= 1.1.2
  sdk/python/setup.py
Labels: approved, cla: yes, lgtm, size/XS

#4820 fix(sdk): Do not wait for resource deletion
  sdk/python/kfp/dsl/_resource_op.py
  sdk/python/tests/dsl/resource_op_tests.py
  sdk/python/tests/dsl/volume_op_tests.py
Labels: approved, cla: yes, lgtm, size/M

#4916 chore(sample): Uncomment model deletion commands
  samples/core/ai_platform/ai_platform.ipynb
Labels: approved, cla: yes, lgtm, size/XS

#4913 chore(sdk): Add inputUri and outputUri placeholders in v1
  sdk/python/kfp/components/_components.py
  sdk/python/kfp/components/_structures.py
  sdk/python/kfp/components_tests/test_components.py
Labels: approved, cla: yes, lgtm, size/L

#4927 feat(backend): sync pipeline_spec.proto
  api/v2alpha1/pipeline_spec.proto
Labels: approved, cla: yes, lgtm, size/L

#4911 feat(backend): Bump Go SQL driver to v1.5.0. Fixes #4910
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/XS

#4928 chore(sdk): update requirements.txt
  sdk/python/requirements.in
  sdk/python/requirements.txt
Labels: approved, cla: yes, lgtm, size/XS

#4929 chore (sdk.v2): Error out on using InputPath placeholder for artifacts require importer.
  sdk/python/kfp/v2/compiler/compiler_test.py
  sdk/python/kfp/v2/dsl/component_bridge.py
Labels: approved, cla: yes, lgtm, size/M

#4930 docs(backend)update docs of deploying apiserver
  backend/README.md
Labels: approved, cla: yes, lgtm, size/XS

#4914 fix(backend): fixed validation logic and resource manager logic when creating job and run
  backend/src/apiserver/resource/client_manager_fake.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/resource/resource_manager_util.go
  backend/src/apiserver/resource/resource_manager_util_test.go
  backend/src/apiserver/server/job_server.go
  backend/src/apiserver/server/job_server_test.go
  backend/src/apiserver/server/run_server.go
  backend/src/apiserver/server/run_server_test.go
  backend/src/apiserver/server/test_util.go
  backend/src/apiserver/server/util.go
  backend/src/apiserver/server/util_test.go
Labels: approved, cla: yes, lgtm, size/XL

#4919 feat(frontend): Reorganize Experiments, Runs, and Archive pages. Fixes #4918
  frontend/src/components/Router.tsx
  frontend/src/components/SideNav.tsx
  frontend/src/components/__snapshots__/SideNav.test.tsx.snap
  frontend/src/lib/Buttons.ts
  frontend/src/pages/AllExperimentsAndArchive.test.tsx
  frontend/src/pages/AllExperimentsAndArchive.tsx
  frontend/src/pages/AllRunsAndArchive.test.jsx.tsx
  frontend/src/pages/AllRunsAndArchive.tsx
  frontend/src/pages/AllRunsList.tsx
  frontend/src/pages/ArchivedExperiments.tsx
  frontend/src/pages/ArchivedRuns.tsx
  frontend/src/pages/ExperimentList.tsx
  frontend/src/pages/__snapshots__/AllExperimentsAndArchive.test.tsx.snap
  frontend/src/pages/__snapshots__/AllRunsList.test.tsx.snap
  frontend/src/pages/__snapshots__/ArchivedExperiments.test.tsx.snap
  frontend/src/pages/__snapshots__/ArchivedRuns.test.tsx.snap
  frontend/src/pages/__snapshots__/ExperimentsAndRuns.test.tsx.snap
  test/frontend-integration-test/helloworld.spec.js
Labels: approved, cla: yes, lgtm, size/XL

#4912 fix(frontend): Change CachedIcon to something more intuitive
  frontend/src/icons/statusCached.tsx
  frontend/src/pages/Status.tsx
  frontend/src/pages/__snapshots__/Status.test.tsx.snap
Labels: approved, cla: yes, lgtm, size/M

#4938 fix(sdk): fixes typo of 'desc'.
  sdk/python/kfp/_client.py
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#4199 feat(compiler): add dsl operation for parallelism on sub dag level
  samples/core/parallelism_sub_dag/parallelism_sub_dag.py
  samples/core/parallelism_sub_dag_with_op_output/parallelism_sub_dag_with_op_output.py
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/dsl/__init__.py
  sdk/python/kfp/dsl/_ops_group.py
  test/sample-test/configs/parallelism_sub_dag.yaml
  test/sample_test.yaml
Labels: approved, cla: yes, lgtm, size/L

#4935 docs: Add the guidelines of writing UT of golang part in Contrubuting.md
  CONTRIBUTING.md
Labels: approved, cla: yes, lgtm, size/S
