Repository kubeflow/pipelines, pull requests merged in 2020-02, with the labels that each got.

#2951 [Frontend] Change Tab name from source to YAML
  frontend/src/pages/PipelineDetails.tsx
  frontend/src/pages/__snapshots__/PipelineDetails.test.tsx.snap
Labels: approved, lgtm, size/S

#2949 Bump TFX dependency to 0.21.0rc0
  backend/Dockerfile
  samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py
  samples/core/parameterized_tfx_oss/taxi_pipeline_notebook.ipynb
  test/sample-test/Dockerfile
Labels: approved, lgtm, size/L

#2944 Samples - Add and change preloaded samples
  backend/Dockerfile
  backend/src/apiserver/config/sample_config.json
  samples/tutorials/DSL - Control structures/DSL - Control structures.py
  samples/tutorials/Data passing in python components/Data passing in python components - Files.py
Labels: approved, area/samples, lgtm, size/L

#2955 [UI] Updating starting page UI links
  frontend/src/pages/GettingStarted.tsx
Labels: approved, lgtm, size/S

#2946 Visualizations - Updated the TFMA and TFDV versions
  backend/Dockerfile.visualization
  backend/src/apiserver/visualization/requirements.txt
  backend/src/apiserver/visualization/third_party_licenses.csv
  components/third_party_licenses.csv
Labels: approved, lgtm, size/M

#2953 Adding diagnose me component to XGboost sample
  components/diagnostics/diagnose_me/component.py
  components/diagnostics/diagnose_me/component.yaml
  samples/core/xgboost_training_cm/xgboost_training_cm.py
Labels: approved, lgtm, size/L

#2959 [Doc] Improve vscode settings documentation
  frontend/README.md
Labels: approved, area/docs, area/frontend, lgtm, size/XS

#2960 Release 85945e10920757efab999217c836403c024b09e3
  components/gcp/bigquery/query/README.md
  components/gcp/bigquery/query/component.yaml
  components/gcp/bigquery/query/sample.ipynb
  components/gcp/dataflow/launch_python/README.md
  components/gcp/dataflow/launch_python/component.yaml
  components/gcp/dataflow/launch_python/sample.ipynb
  components/gcp/dataflow/launch_template/README.md
  components/gcp/dataflow/launch_template/component.yaml
  components/gcp/dataflow/launch_template/sample.ipynb
  components/gcp/dataproc/create_cluster/README.md
  components/gcp/dataproc/create_cluster/component.yaml
  components/gcp/dataproc/create_cluster/sample.ipynb
  components/gcp/dataproc/delete_cluster/README.md
  components/gcp/dataproc/delete_cluster/component.yaml
  components/gcp/dataproc/delete_cluster/sample.ipynb
  components/gcp/dataproc/submit_hadoop_job/README.md
  components/gcp/dataproc/submit_hadoop_job/component.yaml
  components/gcp/dataproc/submit_hadoop_job/sample.ipynb
  components/gcp/dataproc/submit_hive_job/README.md
  components/gcp/dataproc/submit_hive_job/component.yaml
  components/gcp/dataproc/submit_hive_job/sample.ipynb
  components/gcp/dataproc/submit_pig_job/README.md
  components/gcp/dataproc/submit_pig_job/component.yaml
  components/gcp/dataproc/submit_pig_job/sample.ipynb
  components/gcp/dataproc/submit_pyspark_job/README.md
  components/gcp/dataproc/submit_pyspark_job/component.yaml
  components/gcp/dataproc/submit_pyspark_job/sample.ipynb
  components/gcp/dataproc/submit_spark_job/README.md
  components/gcp/dataproc/submit_spark_job/component.yaml
  components/gcp/dataproc/submit_spark_job/sample.ipynb
  components/gcp/dataproc/submit_sparksql_job/README.md
  components/gcp/dataproc/submit_sparksql_job/component.yaml
  components/gcp/dataproc/submit_sparksql_job/sample.ipynb
  components/gcp/ml_engine/batch_predict/README.md
  components/gcp/ml_engine/batch_predict/component.yaml
  components/gcp/ml_engine/batch_predict/sample.ipynb
  components/gcp/ml_engine/deploy/README.md
  components/gcp/ml_engine/deploy/component.yaml
  components/gcp/ml_engine/deploy/sample.ipynb
  components/gcp/ml_engine/train/README.md
  components/gcp/ml_engine/train/component.yaml
  components/gcp/ml_engine/train/sample.ipynb
  components/kubeflow/deployer/component.yaml
  components/kubeflow/dnntrainer/component.yaml
  components/local/confusion_matrix/component.yaml
  components/local/roc/component.yaml
  samples/core/ai_platform/ai_platform.ipynb
  samples/core/dataflow/dataflow.ipynb
  samples/core/kubeflow_tf_serving/kubeflow_tf_serving.ipynb
  samples/core/xgboost_training_cm/xgboost_training_cm.py
  samples/tutorials/mnist/04_Reusable_and_Pre-build_Components_as_Pipeline.ipynb
Labels: approved, lgtm, size/L

#2961 Bump version for release 0.2.1 of Pipelines
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml
  manifests/gcp_marketplace/schema.yaml
  manifests/kustomize/base/kustomization.yaml
  manifests/kustomize/base/pipeline-application.yaml
  sdk/python/kfp/__init__.py
Labels: approved, lgtm, size/S

#2957 Add support for automatic visualization of TFX artifacts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/apis/metadata/BUILD.bazel
  frontend/src/apis/metadata/metadata_store.proto
  frontend/src/apis/metadata/metadata_store_service.proto
  frontend/src/components/SideNav.tsx
  frontend/src/lib/OutputArtifactLoader.ts
  frontend/src/pages/ExecutionDetails.tsx
  frontend/src/pages/RunDetails.test.tsx
  frontend/src/pages/RunDetails.tsx
  frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
Labels: approved, lgtm, ok-to-test, size/XXL

#2968 pin envoy
  third_party/metadata_envoy/Dockerfile
Labels: approved, lgtm, size/XS

#2972 Fix third party license
  backend/src/apiserver/visualization/third_party_licenses.csv
Labels: approved, lgtm, size/XS

#2964 Clean up metric columns
  frontend/src/pages/AllRunsList.tsx
  frontend/src/pages/RunList.tsx
  frontend/src/pages/__snapshots__/AllRunsList.test.tsx.snap
Labels: approved, lgtm, size/XS

#2976 [Frontend] Use latest kf frontend with bug fixes
  frontend/package-lock.json
  frontend/package.json
Labels: approved, area/frontend, kind/bug, lgtm, priority/p0, size/S

#2975 [License] Another license fix
  backend/src/apiserver/visualization/third_party_licenses.csv
  components/third_party_licenses.csv
Labels: approved, lgtm, size/XS

#2980 fix for Init Action
  manifests/gcp_marketplace/deployer/Dockerfile
  manifests/gcp_marketplace/deployer/init_action.sh
  manifests/gcp_marketplace/deployer/overlay_deploy.sh
  manifests/gcp_marketplace/deployer/overlay_deploy_with_tests.sh
Labels: approved, lgtm, size/M

#2982 Another license fix
  components/third_party_licenses.csv
Labels: approved, lgtm, size/XS

#2986 [SDK] Fix CLI authentication
  sdk/python/kfp/_auth.py
Labels: approved, lgtm, size/XS

#2962 Update changelog for 0.2.1 release.
  CHANGELOG.md
Labels: approved, lgtm, size/M

#2984 Another fix of licenses
  components/third_party_licenses.csv
Labels: approved, lgtm, size/XS

#2988 bump version to 0.2.2
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml
  manifests/gcp_marketplace/schema.yaml
  manifests/kustomize/base/kustomization.yaml
  manifests/kustomize/base/pipeline-application.yaml
  sdk/python/kfp/__init__.py
Labels: approved, lgtm, size/S

#2989 better default bucket name, less resource request
  manifests/gcp_marketplace/deployer/Dockerfile
  manifests/gcp_marketplace/deployer/init_action.sh
  manifests/gcp_marketplace/schema.yaml
Labels: approved, lgtm, size/S

#2990 update changelog and document
  CHANGELOG.md
  manifests/kustomize/README.md
Labels: approved, lgtm, size/S

#2929 Include experiment ID as part of run table
  backend/src/apiserver/client_manager.go
  backend/src/apiserver/list/list.go
  backend/src/apiserver/model/run.go
  backend/src/apiserver/resource/model_converter.go
  backend/src/apiserver/resource/model_converter_test.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/storage/run_store.go
Labels: approved, lgtm, ok-to-test, size/L

#2833 [Sample] CI Sample: helloworld
  samples/contrib/versioned-pipeline-ci-samples/helloworld-ci-sample/README.md
  samples/contrib/versioned-pipeline-ci-samples/helloworld-ci-sample/cloudbuild.yaml
  samples/contrib/versioned-pipeline-ci-samples/helloworld-ci-sample/component.yaml
  samples/contrib/versioned-pipeline-ci-samples/helloworld-ci-sample/curl.bash
  samples/contrib/versioned-pipeline-ci-samples/helloworld-ci-sample/helloworld/Dockerfile
  samples/contrib/versioned-pipeline-ci-samples/helloworld-ci-sample/helloworld/helloworld.py
  samples/contrib/versioned-pipeline-ci-samples/helloworld-ci-sample/pipeline.py
Labels: approved, lgtm, ok-to-test, size/L

#3004 Fix issue with "grpc: received message larger than max ..."
  backend/src/apiserver/main.go
Labels: approved, lgtm, size/S

#3006 Add numerology to SDK owner
  sdk/OWNERS
Labels: approved, lgtm, size/XS

#3008 [Testing] Reduce flakiness caused by iam bindings
  test/deploy-pipeline-lite.sh
  test/install-argo.sh
  test/scripts/retry.sh
Labels: approved, area/engprod, area/testing, lgtm, size/M

#3001 Upload local file as new pipeline version Step 1
  backend/api/swagger/kfp_api_single_file.swagger.json
  backend/api/swagger/pipeline.upload.swagger.json
  backend/src/apiserver/main.go
  backend/src/apiserver/resource/client_manager_fake.go
  backend/src/apiserver/server/pipeline_upload_server.go
  backend/src/apiserver/server/pipeline_upload_server_test.go
  backend/src/apiserver/server/test/arguments_tarball/arguments-version.tar.gz
  backend/src/apiserver/server/util.go
  backend/src/common/client/api_server/pipeline_upload_client.go
  backend/src/common/client/api_server/pipeline_upload_client_fake.go
  backend/test/integration/job_api_test.go
  backend/test/integration/pipeline_api_test.go
  backend/test/integration/run_api_test.go
Labels: lgtm, size/L

#3012 [UI] Fix starting page casing
  frontend/src/pages/GettingStarted.tsx
Labels: approved, area/frontend, kind/bug, lgtm, size/XS

#3002 [Sample] Update notebook sample link
  backend/Dockerfile
  backend/src/apiserver/config/sample_config.json
Labels: approved, lgtm, size/XS

#2996 Allow blank port for minio client to work with S3
  backend/src/apiserver/client/minio.go
Labels: approved, lgtm, ok-to-test, size/S

#3010 Upload local file as new pipeline version Step 2 - Swagger generated code for UploadPipelineVersion method
  backend/api/go_http_client/pipeline_upload_client/pipeline_upload_service/BUILD.bazel
  backend/api/go_http_client/pipeline_upload_client/pipeline_upload_service/pipeline_upload_service_client.go
  backend/api/go_http_client/pipeline_upload_client/pipeline_upload_service/upload_pipeline_version_parameters.go
  backend/api/go_http_client/pipeline_upload_client/pipeline_upload_service/upload_pipeline_version_responses.go
  backend/api/go_http_client/pipeline_upload_model/BUILD.bazel
  backend/api/go_http_client/pipeline_upload_model/api_pipeline_version.go
  backend/api/go_http_client/pipeline_upload_model/api_relationship.go
  backend/api/go_http_client/pipeline_upload_model/api_resource_key.go
  backend/api/go_http_client/pipeline_upload_model/api_resource_reference.go
  backend/api/go_http_client/pipeline_upload_model/api_resource_type.go
Labels: approved, lgtm, size/XL

#3018 [Testing] Use full scope cluster for testing to reduce flakiness
  test/presubmit-tests-with-pipeline-deployment.sh
Labels: approved, area/engprod, area/testing, lgtm, size/XS

#3015 [UI] Fix side nav text alignment after adding start page
  frontend/src/components/SideNav.tsx
  frontend/src/lib/Flags.ts
Labels: approved, area/frontend, kind/bug, lgtm, size/S

#3009 [Backend] Use pod namespace as default when not in multi user mode
  backend/src/apiserver/client/BUILD.bazel
  backend/src/apiserver/client/argo.go
  backend/src/apiserver/client/argo_fake.go
  backend/src/apiserver/client/kubernetes_core_fake.go
  backend/src/apiserver/client_manager.go
  backend/src/apiserver/common/config.go
  backend/src/apiserver/resource/BUILD.bazel
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/server/BUILD.bazel
  backend/src/apiserver/server/test_util.go
Labels: approved, area/backend, kind/bug, lgtm, priority/p0, size/L

#2971 SDK - Components - create_graph_component_from_pipeline_func now returns a function
  sdk/python/kfp/components/_python_to_graph_component.py
Labels: approved, area/sdk/components, lgtm, size/S

#3016 [Backend] Improve parameter patching
  backend/build_api_server.sh
  backend/src/apiserver/main.go
  backend/src/apiserver/server/run_server.go
  backend/src/apiserver/server/run_server_test.go
  backend/src/apiserver/server/test_util.go
  backend/src/apiserver/server/util.go
  backend/src/apiserver/server/util_test.go
  samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py
  samples/core/parameterized_tfx_oss/taxi_pipeline_notebook.ipynb
  samples/core/xgboost_training_cm/xgboost_training_cm.py
Labels: approved, lgtm, size/L

#3003 Deduce proxy type from the presence of client_id
  sdk/python/kfp/_auth.py
  sdk/python/kfp/_client.py
Labels: approved, lgtm, size/S

#2868 Samples - Updated the Data passing in python tutorial
  samples/tutorials/Data passing in python components.ipynb
Labels: approved, area/samples/notebooks, lgtm, size/L

#3017 [Samples] Update TFX module file
  samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py
  samples/core/parameterized_tfx_oss/taxi_pipeline_notebook.ipynb
Labels: approved, lgtm, size/S

#3035 Fix build failure
  .travis.yml
Labels: approved, lgtm, size/XS

#2080 [api-server] Object store folder path is configurable and can work with AWS (secure and region flag, and IAM credentials)
  backend/src/apiserver/client/BUILD.bazel
  backend/src/apiserver/client/minio.go
  backend/src/apiserver/client_manager.go
  backend/src/apiserver/common/config.go
  backend/src/apiserver/config/config.json
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/server/pipeline_upload_server_test.go
  backend/src/apiserver/storage/BUILD.bazel
  backend/src/apiserver/storage/minio_client_fake.go
  backend/src/apiserver/storage/object_store.go
  backend/src/apiserver/storage/object_store_fake.go
  backend/src/apiserver/storage/object_store_test.go
  backend/src/apiserver/storage/object_store_util.go
Labels: approved, area/backend, lgtm, ok-to-test, size/L

#3029 SDK - Compiler - Fixed ParallelFor argument resolving
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/dsl/_for_loop.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/loop_over_lightweight_output.yaml
  sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving.py
  sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving.yaml
  sdk/python/tests/compiler/testdata/withparam_global.yaml
  sdk/python/tests/compiler/testdata/withparam_global_dict.yaml
  sdk/python/tests/compiler/testdata/withparam_output.yaml
  sdk/python/tests/compiler/testdata/withparam_output_dict.yaml
Labels: approved, area/sdk/dsl/compiler, lgtm, size/XL

#2994 [Testing]Add Dockerfile for KFP e2e test
  test/images/Dockerfile
  test/images/README.md
Labels: approved, lgtm, size/S

#3052 Adding auth list support for diagnose_me
  sdk/python/kfp/cli/diagnose_me/gcp.py
Labels: approved, lgtm, size/XS

#3044 updating links and service account message
  components/diagnostics/diagnose_me/component.py
  components/diagnostics/diagnose_me/component.yaml
Labels: approved, lgtm, size/S

#3026 Add visualizations for Schema and ExampleAnomalies
  frontend/src/lib/OutputArtifactLoader.ts
Labels: approved, lgtm, ok-to-test, size/L

#3019 [Testing] Use google/cloud-sdk:279.0.0 to resolve workload identity flakiness
  components/diagnostics/diagnose_me/component.py
  components/diagnostics/diagnose_me/component.yaml
  samples/core/exit_handler/exit_handler.py
  samples/core/kfp_env_validation/kfp_env_validation.ipynb
  samples/core/parallel_join/parallel_join.py
  samples/core/secret/secret.py
  samples/core/sequential/sequential.py
  samples/core/volume_snapshot_ops/volume_snapshot_ops.py
  sdk/python/tests/compiler/testdata/volume_snapshotop_sequential.py
  sdk/python/tests/compiler/testdata/volume_snapshotop_sequential.yaml
  test/build_image.yaml
  test/component_test.yaml
  test/e2e_test_gke_v2.yaml
  test/frontend-integration-test/Dockerfile
  test/frontend-integration-test/selenium-standalone-chrome-gcloud-nodejs.Docker/Dockerfile
  test/imagebuilder/Dockerfile
  test/presubmit-tests-with-pipeline-deployment.sh
  test/sample-test/Dockerfile
  test/sample-test/configs/xgboost_training_cm.config.yaml
  test/sample_test.yaml
Labels: approved, area/engprod, area/testing, lgtm, size/M

#3028 place holder for diagnose entry
  tools/diagnose/OWNERS
  tools/diagnose/kfp.sh
Labels: approved, lgtm, size/M

#3043 [UI] Circular progress for TFX visualization
  frontend/src/lib/OutputArtifactLoader.ts
  frontend/src/pages/ExecutionList.tsx
  frontend/src/pages/RunDetails.test.tsx
  frontend/src/pages/RunDetails.tsx
  frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
Labels: approved, area/frontend, kind/feature, lgtm, size/XL

#3053 [Test] Add docker daemon start in test base image
  test/images/Dockerfile
Labels: approved, lgtm, size/XS

#3040 Implement filtering in ListPipelines
  backend/src/apiserver/filter/filter.go
  backend/src/apiserver/filter/filter_test.go
  backend/src/apiserver/list/list.go
  backend/src/apiserver/storage/pipeline_store.go
  backend/src/apiserver/storage/pipeline_store_test.go
Labels: approved, area/backend, lgtm, size/L

#3041 Set auto-added artifacts optional in recurring run (job)
  backend/src/apiserver/resource/resource_manager.go
Labels: approved, lgtm, size/S

#3034 [Samples] Update preloaded samples' descriptions
  backend/src/apiserver/config/sample_config.json
Labels: approved, lgtm, size/XS

#2916 Updated the API reference comments
  backend/api/job.proto
  backend/api/pipeline.proto
Labels: approved, lgtm, ok-to-test, size/XS

#3030 add link to allow user easily report issue
  frontend/src/components/SideNav.tsx
  frontend/src/components/__snapshots__/SideNav.test.tsx.snap
Labels: approved, lgtm, size/L

#3027 add myself to manifest/sample/test owner
  manifests/kustomize/OWNERS
  samples/OWNERS
  test/OWNERS
Labels: approved, lgtm, size/XS

#3067 [Fix] Pin avro==1.9.1
  backend/Dockerfile
  backend/src/apiserver/visualization/requirements.txt
  backend/src/apiserver/visualization/third_party_licenses.csv
  test/sample-test/Dockerfile
Labels: approved, lgtm, size/XS

#3060 update TFDV to 0.21.1 which can work for Chrome 80
  backend/src/apiserver/visualization/requirements.txt
Labels: approved, lgtm, size/XS

#3038 Updates for getting started page
  frontend/src/pages/GettingStarted.tsx
Labels: approved, lgtm, size/S

#3059 [UI] Upload pipeline version from local package
  backend/src/apiserver/visualization/third_party_licenses.csv
  frontend/src/lib/Apis.ts
  frontend/src/lib/Buttons.ts
  frontend/src/pages/NewPipelineVersion.tsx
  frontend/src/pages/PipelineDetails.tsx
  frontend/src/pages/__snapshots__/NewPipelineVersion.test.tsx.snap
Labels: approved, area/frontend, kind/feature, lgtm, priority/p0, size/L

#3063 Fix Pipeline/Workspace field in ArtifactList table
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/ArtifactList.tsx
Labels: approved, area/front-end, lgtm, priority/p0, size/S

#3066 [Doc] Make it explicit that hosted beta does not require GCP SA
  backend/src/apiserver/config/sample_config.json
  samples/core/parameterized_tfx_oss/README.md
  samples/core/parameterized_tfx_oss/taxi_pipeline_notebook.ipynb
  samples/core/xgboost_training_cm/README.md
Labels: lgtm, size/S

#3072 update version from 0.2.2 to 0.2.3 for kfp
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml
  manifests/gcp_marketplace/schema.yaml
  manifests/kustomize/README.md
  manifests/kustomize/base/kustomization.yaml
  manifests/kustomize/base/pipeline-application.yaml
  sdk/python/kfp/__init__.py
Labels: approved, lgtm, size/M

#3062 [Component] Add quota check in diagnose me component.
  components/diagnostics/diagnose_me/component.py
  components/diagnostics/diagnose_me/component.yaml
Labels: approved, lgtm, size/XL

#3082 [UI] Visualization only loads on completed nodes
  frontend/src/pages/RunDetails.tsx
  frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
Labels: approved, area/frontend, kind/bug, lgtm, size/M

#3083 Pin Pyarrow version to 0.15.1 after we upgrade to use tfdv 0.21.1
  backend/src/apiserver/visualization/requirements.txt
Labels: lgtm, size/XS

#3075 quick fix for quota list
  components/diagnostics/diagnose_me/component.py
  components/diagnostics/diagnose_me/component.yaml
Labels: approved, lgtm, size/L

#3049 XGBoost demo - Removing unnecessary parameters and adding quota check.
  samples/core/xgboost_training_cm/README.md
  samples/core/xgboost_training_cm/xgboost_training_cm.py
  test/sample-test/configs/xgboost_training_cm.config.yaml
Labels: approved, lgtm, size/M

#3076 Samples - Add explanation about pipeline failing intentionally
  backend/src/apiserver/config/sample_config.json
  samples/tutorials/DSL - Control structures/DSL - Control structures.py
Labels: approved, area/samples, lgtm, size/XS

#3090 Fix api generation script
  backend/api/generate_api.sh
Labels: approved, lgtm, size/S

#3091 SDK - Fixed the broken kfp.gcp.use_preemptible_nodepool extension
  sdk/python/kfp/gcp.py
  sdk/python/tests/compiler/testdata/preemptible_tpu_gpu.yaml
Labels: approved, area/sdk, lgtm, size/XS

#3081 [Community] Improve BUG_REPORT.md
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
Labels: approved, lgtm, size/M

#3089 enable tfdv, remove hardcode as a sample for following PRs
  backend/src/apiserver/visualization/requirements.txt
  backend/src/apiserver/visualization/types/tfdv.py
  frontend/src/lib/OutputArtifactLoader.ts
Labels: approved, lgtm, size/L

#3086 [UI] deep links to pipeline details page from start page
  frontend/package-lock.json
  frontend/package.json
  frontend/scripts/sync-backend-sample-config.js
  frontend/src/TestUtils.tsx
  frontend/src/atoms/ExternalLink.tsx
  frontend/src/components/Router.tsx
  frontend/src/config/sample_config_from_backend.json
  frontend/src/pages/GettingStarted.test.tsx
  frontend/src/pages/GettingStarted.tsx
  frontend/src/pages/__snapshots__/GettingStarted.test.tsx.snap
  frontend/tsconfig.json
  frontend/tslint.json
Labels: approved, area/frontend, lgtm, size/XL

#3092 [Doc] Call out quota requirement in XGBoost sample
  samples/core/xgboost_training_cm/README.md
Labels: approved, lgtm, size/XS

#3093 XGBoost demo - change quota calculation
  samples/core/xgboost_training_cm/xgboost_training_cm.py
  test/sample-test/configs/xgboost_training_cm.config.yaml
Labels: approved, lgtm, size/XS

#2856 Backend - Removed Tensorflow from backend WORKSPACE
  WORKSPACE
Labels: approved, area/backend, lgtm, size/S

#3103 ml_engine component READMEs incorrect
  components/gcp/ml_engine/batch_predict/README.md
  components/gcp/ml_engine/deploy/README.md
Labels: approved, area/components, lgtm, ok-to-test, size/S

#3102 [Lineage] Update kubeflow/frontend to latest hash to pick up bug bash fixes
  frontend/package-lock.json
  frontend/package.json
Labels: approved, area/front-end, lgtm, priority/p0, size/S

#3107 SDK - Components - Fixed dict-style type annotations
  sdk/python/kfp/components/_components.py
  sdk/python/kfp/components/_data_passing.py
  sdk/python/kfp/components/_python_op.py
  sdk/python/tests/components/test_python_op.py
Labels: approved, area/sdk/components, lgtm, size/M

#3113 [UI] Clean up backstop js usages
  frontend/.gitignore
  frontend/Dockerfile
  frontend/backstop.json
  frontend/backstop.ts
  frontend/backstop_data/bitmaps_reference/pipelines_hover_on_first_row_0_document_0_.png
  frontend/backstop_data/bitmaps_reference/pipelines_initial_state_0_document_0_.png
  frontend/backstop_data/bitmaps_reference/pipelines_open_upload_dialog_0_document_0_.png
  frontend/backstop_data/bitmaps_reference/pipelines_select_multiple_rows_0_document_0_.png
  frontend/backstop_data/bitmaps_reference/pipelines_select_one_row_0_document_0_.png
  frontend/backstop_data/engine_scripts/imageStub.jpg
  frontend/backstop_data/engine_scripts/steps.js
  frontend/package-lock.json
  frontend/package.json
  frontend/tsconfig.json
  frontend/tslint.json
Labels: approved, area/engprod, area/frontend, lgtm, size/XL

#3094 SDK - Compiler - Add optional Argo validation
  sdk/python/kfp/compiler/compiler.py
Labels: approved, area/sdk/dsl/compiler, lgtm, size/M

#3111 TFMA auto-visualization for TFX components in KFP
  frontend/src/lib/OutputArtifactLoader.ts
Labels: approved, area/frontend, lgtm, size/M

#3096 Remove pinning avro-python3, because it is already fixed
  backend/Dockerfile
  backend/src/apiserver/visualization/requirements.txt
  test/sample-test/Dockerfile
Labels: approved, area/engprod, lgtm, size/XS

#3115 bump version to 0.2.4 and tiny BTW doc fix
  backend/src/apiserver/config/sample_config.json
  frontend/src/pages/GettingStarted.tsx
  frontend/src/pages/__snapshots__/GettingStarted.test.tsx.snap
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml
  manifests/gcp_marketplace/guide.md
  manifests/gcp_marketplace/schema.yaml
  manifests/kustomize/README.md
  manifests/kustomize/base/kustomization.yaml
  manifests/kustomize/base/pipeline-application.yaml
  sdk/python/kfp/__init__.py
Labels: approved, lgtm, size/M

#3116 [Visualization] Clean up full.tpl to improve vis loading time
  backend/src/apiserver/visualization/exporter.py
  backend/src/apiserver/visualization/templates/full.tpl
  frontend/server/app.ts
  test/cloudbuild/visualization.yaml
Labels: approved, area/backend, lgtm, size/M

#3117 [UI] Deduplicate requests to gke metadata
  frontend/src/components/Router.tsx
  frontend/src/components/__snapshots__/Router.test.tsx.snap
Labels: approved, area/frontend, kind/bug, lgtm, size/L

#3121 Bump TFX dependency
  backend/Dockerfile
  samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py
  samples/core/parameterized_tfx_oss/taxi_pipeline_notebook.ipynb
  test/sample-test/Dockerfile
Labels: approved, lgtm, size/L

#3122 SDK - Compiler - Fix incompatibility with python3.5
  sdk/python/kfp/compiler/compiler.py
Labels: approved, area/sdk/dsl/compiler, kind/bug, lgtm, size/XS

#3125 [Sample] typo fix
  samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py
Labels: approved, lgtm, size/XS

#3127 [Sample] update README
  samples/core/parameterized_tfx_oss/README.md
Labels: approved, lgtm, size/S

#3073 [Controller] Scheduled workflow supports catch up false
  backend/api/go_client/job.pb.go
  backend/api/go_http_client/job_client/job_service/job_service_client.go
  backend/api/go_http_client/job_model/api_job.go
  backend/api/go_http_client/pipeline_client/pipeline_service/pipeline_service_client.go
  backend/api/job.proto
  backend/api/swagger/job.swagger.json
  backend/api/swagger/kfp_api_single_file.swagger.json
  backend/api/swagger/pipeline.swagger.json
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/server/BUILD.bazel
  backend/src/crd/controller/scheduledworkflow/util/cron_schedule.go
  backend/src/crd/controller/scheduledworkflow/util/cron_schedule_test.go
  backend/src/crd/controller/scheduledworkflow/util/periodic_schedule.go
  backend/src/crd/controller/scheduledworkflow/util/periodic_schedule_test.go
  backend/src/crd/controller/scheduledworkflow/util/scheduled_workflow.go
  backend/src/crd/pkg/apis/scheduledworkflow/v1beta1/types.go
Labels: approved, lgtm, size/L

#3118 [UIServer] Add DISABLE_GKE_METADATA env flag to skip metadata retrieval.
  frontend/Dockerfile
  frontend/package.json
  frontend/server/app.test.ts
  frontend/server/app.ts
  frontend/server/configs.ts
  frontend/server/handlers/gke-metadata.ts
  frontend/server/package-lock.json
  frontend/server/package.json
Labels: approved, area/frontend, kind/feature, lgtm, size/XXL

#3135 [Test] Temporarily bypass TFX unittest
  .travis.yml
  backend/Dockerfile
  test/sample-test/Dockerfile
Labels: approved, lgtm, size/S

#3136 Update link to TFX demo in getting start page
  frontend/src/pages/GettingStarted.tsx
  frontend/src/pages/__snapshots__/GettingStarted.test.tsx.snap
Labels: lgtm, size/XS

#3129 [DB] Add NoCatchup field to Job db model
  backend/src/apiserver/model/job.go
  backend/src/apiserver/resource/model_converter.go
  backend/src/apiserver/resource/model_converter_test.go
  backend/src/apiserver/server/api_converter.go
  backend/src/apiserver/server/api_converter_test.go
  backend/src/apiserver/storage/job_store.go
  backend/src/apiserver/storage/job_store_test.go
  backend/src/common/util/scheduled_workflow.go
  test/cloudbuild/scheduledworkflow.yaml
Labels: approved, area/backend, lgtm, size/L

#3131 [UI] Scheduled workflow catchup=false option
  frontend/README.md
  frontend/src/apis/job/api.ts
  frontend/src/atoms/HelpButton.tsx
  frontend/src/components/Trigger.test.tsx
  frontend/src/components/Trigger.tsx
  frontend/src/components/__snapshots__/Trigger.test.tsx.snap
  frontend/src/lib/Apis.ts
  frontend/src/lib/RunUtils.ts
  frontend/src/pages/GettingStarted.test.tsx
  frontend/src/pages/NewRun.test.tsx
  frontend/src/pages/NewRun.tsx
  frontend/src/pages/RecurringRunDetails.test.tsx
  frontend/src/pages/RecurringRunDetails.tsx
  frontend/src/pages/__snapshots__/RecurringRunDetails.test.tsx.snap
Labels: approved, area/frontend, kind/feature, lgtm, size/XL

#3138 [Backend] Refactor integration tests, facilitate local testing
  backend/test/integration/README.md
  backend/test/integration/experiment_api_test.go
  backend/test/integration/flags.go
  backend/test/integration/job_api_test.go
  backend/test/integration/pipeline_api_test.go
  backend/test/integration/run_api_test.go
  backend/test/integration/run_tests_locally.sh
  backend/test/integration/visualization_api_test.go
Labels: approved, area/backend, area/docs, area/testing, lgtm, size/L

#3139 [Backend] swf catchup option integration tests
  backend/test/integration/BUILD.bazel
  backend/test/integration/job_api_test.go
Labels: approved, area/backend, area/testing, lgtm, size/L

#3142 [Frontend] Update contribution doc with start proxy instructions and npm daily practices
  frontend/README.md
  frontend/package.json
  frontend/scripts/start-proxies.ps1
  frontend/scripts/start-proxy-and-server.sh
  frontend/scripts/start-proxy.sh
Labels: approved, area/docs, area/frontend, lgtm, size/M

#3140 [frontend]: Use Promise.all to fetch clusterName and projectId
  frontend/src/pages/RunDetails.tsx
Labels: approved, lgtm, ok-to-test, size/XS

#3146 [Test] Turn back on TFX unit test
  .travis.yml
  backend/Dockerfile
  test/sample-test/Dockerfile
Labels: approved, lgtm, size/S

#3150 Update 'TFX demo link'
  frontend/src/pages/GettingStarted.tsx
  frontend/src/pages/__snapshots__/GettingStarted.test.tsx.snap
Labels: approved, lgtm, size/S

#3147 [Frontend] Pin links in getting started page when release
  frontend/Dockerfile
Labels: approved, lgtm, size/XS

#3159 [Frontend] Prepare snapshot updates for cra migration
  frontend/package.json
  frontend/src/__serializers__/mock-function.js
  frontend/src/atoms/Hr.tsx
  frontend/src/atoms/IconWithTooltip.tsx
  frontend/src/atoms/Input.tsx
  frontend/src/atoms/Separator.tsx
  frontend/src/atoms/__snapshots__/MD2Tabs.test.tsx.snap
  frontend/src/components/DetailsTable.tsx
  frontend/src/components/__snapshots__/CustomTable.test.tsx.snap
  frontend/src/components/__snapshots__/PlotCard.test.tsx.snap
  frontend/src/components/__snapshots__/Trigger.test.tsx.snap
  frontend/src/components/__snapshots__/UploadPipelineDialog.test.tsx.snap
  frontend/src/components/viewers/__snapshots__/VisualizationCreator.test.tsx.snap
  frontend/src/pages/__snapshots__/AllRunsList.test.tsx.snap
  frontend/src/pages/__snapshots__/Archive.test.tsx.snap
  frontend/src/pages/__snapshots__/Compare.test.tsx.snap
  frontend/src/pages/__snapshots__/ExperimentDetails.test.tsx.snap
  frontend/src/pages/__snapshots__/NewExperiment.test.tsx.snap
  frontend/src/pages/__snapshots__/NewPipelineVersion.test.tsx.snap
  frontend/src/pages/__snapshots__/NewRun.test.tsx.snap
  frontend/src/pages/__snapshots__/PipelineVersionList.test.tsx.snap
  frontend/src/pages/__snapshots__/RecurringRunDetails.test.tsx.snap
  frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
  frontend/src/pages/__snapshots__/RunList.test.tsx.snap
Labels: approved, area/engprod, area/frontend, lgtm, size/XXL

#3153 [UI] Update frontend/README.md
  frontend/README.md
Labels: approved, area/docs, area/frontend, lgtm, size/M

#3013 [Sample] CI Sample: mnist
  samples/contrib/versioned-pipeline-ci-samples/mnist-ci-sample/README.md
  samples/contrib/versioned-pipeline-ci-samples/mnist-ci-sample/cloudbuild.yaml
  samples/contrib/versioned-pipeline-ci-samples/mnist-ci-sample/create_pipeline_version_and_run.py
  samples/contrib/versioned-pipeline-ci-samples/mnist-ci-sample/pipeline.py
  samples/contrib/versioned-pipeline-ci-samples/mnist-ci-sample/tensorboard/Dockerfile
  samples/contrib/versioned-pipeline-ci-samples/mnist-ci-sample/tensorboard/component.yaml
  samples/contrib/versioned-pipeline-ci-samples/mnist-ci-sample/tensorboard/tensorboard.py
  samples/contrib/versioned-pipeline-ci-samples/mnist-ci-sample/train/Dockerfile
  samples/contrib/versioned-pipeline-ci-samples/mnist-ci-sample/train/component.yaml
  samples/contrib/versioned-pipeline-ci-samples/mnist-ci-sample/train/mnist.py
Labels: approved, lgtm, ok-to-test, size/L

#3160 Fix a missing query parameter in swagger json file for version upload api
  backend/api/go_http_client/pipeline_upload_client/pipeline_upload_service/upload_pipeline_version_parameters.go
  backend/api/swagger/kfp_api_single_file.swagger.json
  backend/api/swagger/pipeline.upload.swagger.json
Labels: lgtm, size/M

#2981 Updated with scheduling capability for kfp.Client
  sdk/python/kfp/_client.py
Labels: approved, area/sdk/client, lgtm, size/M

#3152 Add a message in 'Get Started Page'
  frontend/src/pages/GettingStarted.tsx
  frontend/src/pages/__snapshots__/GettingStarted.test.tsx.snap
Labels: approved, lgtm, size/S

#3144 Fix broken doc link
  backend/src/apiserver/config/sample_config.json
Labels: size/XS

#3151 [Test] Update doc about image position
  test/images/README.md
Labels: approved, lgtm, size/XS

#3126 SDK - Fix SDK on Python 3.8
  sdk/python/kfp/components/_dynamic.py
Labels: approved, area/sdk/components, lgtm, size/M

#3149 [Sample] Update doc in taxi pipeline demo
  samples/core/parameterized_tfx_oss/check_permission.png
  samples/core/parameterized_tfx_oss/taxi_pipeline_notebook.ipynb
Labels: approved, lgtm, size/M

#3163 Update frontend swagger generated code
  frontend/src/apis/pipeline/api.ts
Labels: approved, lgtm, size/XS

#3141 [MLMD][Lineage] Navigate to ArtifactDetails Overview on row click [long term]
  frontend/src/components/Router.tsx
  frontend/src/components/__snapshots__/Router.test.tsx.snap
  frontend/src/pages/ArtifactDetails.tsx
Labels: approved, area/frontend, lgtm, priority/p0, size/L

#3106 SDK - Reduce python component limitations - no import errors for cust…
  sdk/python/kfp/components/_python_op.py
  sdk/python/requirements.txt
  sdk/python/setup.py
  sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving.yaml
  sdk/python/tests/components/test_python_op.py
Labels: approved, area/sdk/components, lgtm, size/L

#3166 [Frontend] snapshot diff setup
  frontend/README.md
  frontend/package.json
  frontend/src/TestUtils.tsx
  frontend/src/components/SideNav.test.tsx
  frontend/src/components/__snapshots__/SideNav.test.tsx.snap
  frontend/src/components/viewers/Tensorboard.test.tsx
  frontend/src/components/viewers/__snapshots__/Tensorboard.test.tsx.snap
  frontend/src/pages/GettingStarted.test.tsx
  frontend/src/pages/__snapshots__/GettingStarted.test.tsx.snap
Labels: approved, area/engprod, area/frontend, lgtm, size/L

#3167 [UI] Always show stackdriver link in GKE
  frontend/src/TestUtils.tsx
  frontend/src/components/SideNav.test.tsx
  frontend/src/components/SideNav.tsx
  frontend/src/index.tsx
  frontend/src/lib/GkeMetadata.tsx
  frontend/src/lib/Utils.tsx
  frontend/src/pages/RunDetails.test.tsx
  frontend/src/pages/RunDetails.tsx
  frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
Labels: approved, area/frontend, kind/feature, lgtm, size/XL

#3154 [Frontend] Update deps to bring optional chaining js language feature
  frontend/.eslintrc.yaml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/apis/run/api.ts
  frontend/src/atoms/ExternalLink.tsx
  frontend/src/components/CompareTable.test.tsx
  frontend/src/components/CustomTableRow.test.tsx
  frontend/src/components/DetailsTable.test.tsx
  frontend/src/components/viewers/ConfusionMatrix.test.tsx
  frontend/src/components/viewers/PagedTable.test.tsx
  frontend/src/lib/CompareUtils.test.ts
  frontend/src/lib/OutputArtifactLoader.test.ts
  frontend/src/lib/StaticGraphParser.test.ts
  frontend/src/pages/AllRunsList.tsx
  frontend/src/pages/Compare.test.tsx
  frontend/src/pages/ExperimentDetails.test.tsx
  frontend/src/pages/ExperimentDetails.tsx
  frontend/src/pages/ExperimentList.tsx
  frontend/src/pages/GettingStarted.tsx
  frontend/src/pages/NewPipelineVersion.tsx
  frontend/src/pages/PipelineDetails.test.tsx
  frontend/src/pages/PipelineDetails.tsx
  frontend/src/pages/RunDetails.tsx
  frontend/src/pages/RunList.test.tsx
  frontend/tsconfig.json
Labels: approved, area/engprod, area/frontend, lgtm, size/L

#3145 [Backend] Fix parameter patching
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/resource/resource_manager_util.go
  backend/src/apiserver/server/run_server.go
  backend/src/apiserver/server/run_server_test.go
  backend/src/apiserver/server/util.go
  backend/src/common/util/workflow.go
Labels: lgtm, size/L

#3170 [Sample] Disable multi-threading for TFX demo notebook
  samples/core/parameterized_tfx_oss/taxi_pipeline_notebook.ipynb
Labels: approved, lgtm, size/XS

#3171 Upload pipeline version return a response with enum as string
  backend/src/apiserver/server/pipeline_upload_server.go
Labels: lgtm, size/XS

#3099 apiserver: Close rows before reusing tx
  backend/src/apiserver/storage/db_status_store.go
  backend/src/apiserver/storage/default_experiment_store.go
Labels: approved, lgtm, ok-to-test, size/S

#3175 start page updates according latest feedback
  frontend/src/Css.tsx
  frontend/src/components/Toolbar.tsx
  frontend/src/pages/GettingStarted.tsx
  frontend/src/pages/__snapshots__/GettingStarted.test.tsx.snap
Labels: approved, lgtm, size/L

#3174 Add integration tests for version related methods
  backend/src/common/client/api_server/pipeline_client.go
  backend/src/common/client/api_server/pipeline_upload_client.go
  backend/test/integration/BUILD.bazel
  backend/test/integration/pipeline_api_test.go
  backend/test/integration/pipeline_version_api_test.go
  go.mod
  go.sum
Labels: lgtm, size/L

#3176 Bump to latest kubeflow/frontend hash with many-to-many execution fix
  frontend/package-lock.json
  frontend/package.json
Labels: approved, area/frontend, lgtm, priority/p0, size/XS

#3177 [UI] Supports storage: "inline" for all types of visualizations
  frontend/src/lib/OutputArtifactLoader.test.ts
  frontend/src/lib/OutputArtifactLoader.ts
Labels: approved, area/frontend, kind/feature, lgtm, size/L

#3178 tiny changes to let user aware should use TF 2.1 Notebook instance
  frontend/src/pages/GettingStarted.tsx
  frontend/src/pages/__snapshots__/GettingStarted.test.tsx.snap
Labels: approved, lgtm, size/S

#3097 nit: Add BigQuery role
  manifests/gcp_marketplace/guide.md
Labels: approved, lgtm, ok-to-test, size/XS

#3179 Release 0.2.5 - e66dcb18607406330f953bf99b04fe7c3ed1a4a8
  backend/api/build_kfp_server_api_python_package.sh
  components/gcp/bigquery/query/README.md
  components/gcp/bigquery/query/component.yaml
  components/gcp/bigquery/query/sample.ipynb
  components/gcp/container/component_sdk/python/setup.py
  components/gcp/dataflow/launch_python/README.md
  components/gcp/dataflow/launch_python/component.yaml
  components/gcp/dataflow/launch_python/sample.ipynb
  components/gcp/dataflow/launch_template/README.md
  components/gcp/dataflow/launch_template/component.yaml
  components/gcp/dataflow/launch_template/sample.ipynb
  components/gcp/dataproc/create_cluster/README.md
  components/gcp/dataproc/create_cluster/component.yaml
  components/gcp/dataproc/create_cluster/sample.ipynb
  components/gcp/dataproc/delete_cluster/README.md
  components/gcp/dataproc/delete_cluster/component.yaml
  components/gcp/dataproc/delete_cluster/sample.ipynb
  components/gcp/dataproc/submit_hadoop_job/README.md
  components/gcp/dataproc/submit_hadoop_job/component.yaml
  components/gcp/dataproc/submit_hadoop_job/sample.ipynb
  components/gcp/dataproc/submit_hive_job/README.md
  components/gcp/dataproc/submit_hive_job/component.yaml
  components/gcp/dataproc/submit_hive_job/sample.ipynb
  components/gcp/dataproc/submit_pig_job/README.md
  components/gcp/dataproc/submit_pig_job/component.yaml
  components/gcp/dataproc/submit_pig_job/sample.ipynb
  components/gcp/dataproc/submit_pyspark_job/README.md
  components/gcp/dataproc/submit_pyspark_job/component.yaml
  components/gcp/dataproc/submit_pyspark_job/sample.ipynb
  components/gcp/dataproc/submit_spark_job/README.md
  components/gcp/dataproc/submit_spark_job/component.yaml
  components/gcp/dataproc/submit_spark_job/sample.ipynb
  components/gcp/dataproc/submit_sparksql_job/README.md
  components/gcp/dataproc/submit_sparksql_job/component.yaml
  components/gcp/dataproc/submit_sparksql_job/sample.ipynb
  components/gcp/ml_engine/batch_predict/README.md
  components/gcp/ml_engine/batch_predict/component.yaml
  components/gcp/ml_engine/batch_predict/sample.ipynb
  components/gcp/ml_engine/deploy/README.md
  components/gcp/ml_engine/deploy/component.yaml
  components/gcp/ml_engine/deploy/sample.ipynb
  components/gcp/ml_engine/train/README.md
  components/gcp/ml_engine/train/component.yaml
  components/gcp/ml_engine/train/sample.ipynb
  components/kubeflow/deployer/component.yaml
  components/kubeflow/dnntrainer/component.yaml
  components/local/confusion_matrix/component.yaml
  components/local/roc/component.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml
  manifests/gcp_marketplace/schema.yaml
  manifests/kustomize/README.md
  manifests/kustomize/base/kustomization.yaml
  manifests/kustomize/base/pipeline-application.yaml
  samples/core/ai_platform/ai_platform.ipynb
  samples/core/dataflow/dataflow.ipynb
  samples/core/kubeflow_tf_serving/kubeflow_tf_serving.ipynb
  samples/core/xgboost_training_cm/xgboost_training_cm.py
  samples/tutorials/mnist/04_Reusable_and_Pre-build_Components_as_Pipeline.ipynb
  sdk/python/kfp/__init__.py
Labels: approved, area/release, lgtm, size/L

#3180 [Release] 0.2.5 Update changelog
  CHANGELOG.md
Labels: size/L

#3181 add VERSION and submit-trigger to generate hosted images for each submit
  .cloudbuild.yaml
  VERSION
  release/tag_for_hosted.sh
Labels: approved, lgtm, size/M

#3173 Update to fix bug in kip.client for scheduling
  sdk/python/kfp/_client.py
Labels: approved, lgtm, size/XS

#3168 minio: Set secure=true to enable TLS by default
  backend/src/apiserver/client_manager.go
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
Labels: approved, lgtm, size/XS

#3183 [Frontend] Unpin notebook permalink when release
  frontend/Dockerfile
Labels: approved, lgtm, size/XS

#3188 remove the magic which update codes only when building a docker image…
  frontend/Dockerfile
Labels: approved, lgtm, size/XS

#3192 Revert "minio: Set secure=true to enable TLS by default"
  backend/src/apiserver/client_manager.go
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
Labels: size/XS

#3191 revert #3168 as it doesn't work for MKP, put myself to reviewer
  backend/OWNERS
  manifests/gcp_marketplace/OWNERS
Labels: approved, lgtm, size/XS
