Repository kubeflow/pipelines, pull requests merged in 2020-03, with the labels that each got.

#3196 [UI] Get execution name from name field
  frontend/src/pages/ExecutionList.tsx
Labels: approved, area/frontend, lgtm, size/XS

#3200 Fix presubmit sample tests base image
  test/sample-test/Dockerfile
Labels: approved, lgtm, size/XS

#3197 [UI] Better logging in UI server
  frontend/server/handlers/artifacts.ts
  frontend/server/server.ts
  frontend/server/utils.ts
Labels: approved, area/engprod, area/frontend, kind/misc, lgtm, size/S

#3209 Pin TFT to 0.21.0
  backend/Dockerfile
  test/sample-test/Dockerfile
Labels: approved, lgtm, size/XS

#3036 [Backend]Initial execution cache
  .cloudbuild.yaml
  .release.cloudbuild.yaml
  backend/Dockerfile.cacheserver
  backend/src/cache/OWNERS
  backend/src/cache/README.md
  backend/src/cache/admission.go
  backend/src/cache/admission_test.go
  backend/src/cache/deployer/Dockerfile
  backend/src/cache/deployer/cache-configmap.yaml.template
  backend/src/cache/deployer/deploy-cache-service.sh
  backend/src/cache/deployer/webhook-create-signed-cert.sh
  backend/src/cache/deployer/webhook-patch-ca-bundle.sh
  backend/src/cache/main.go
  backend/src/cache/mutation.go
  backend/src/cache/mutation_test.go
  manifests/kustomize/base/cache-deployer/cache-deployer-clusterrole.yaml
  manifests/kustomize/base/cache-deployer/cache-deployer-clusterrolebinding.yaml
  manifests/kustomize/base/cache-deployer/cache-deployer-job.yaml
  manifests/kustomize/base/cache-deployer/cache-deployer-sa.yaml
  manifests/kustomize/base/cache-deployer/kustomization.yaml
  manifests/kustomize/base/cache/cache-deployment.yaml
  manifests/kustomize/base/cache/cache-service.yaml
  manifests/kustomize/base/cache/kustomization.yaml
  test/build-images.sh
  test/cloudbuild/batch_build.yaml
  test/deploy-pipeline-lite.sh
  test/manifests/dev/kustomization.yaml
Labels: approved, area/backend, lgtm, size/XXL

#3186 [Tutorial] - Fixed lightweight component tutorial with bad metadata usage
  samples/tutorials/mnist/00_Kubeflow_Cluster_Setup.ipynb
  samples/tutorials/mnist/01_Lightweight_Python_Components.ipynb
Labels: approved, lgtm, size/M

#3201 [SDK] New fields for schedule pipeline
  frontend/src/components/Trigger.tsx
  frontend/src/components/__snapshots__/Trigger.test.tsx.snap
  sdk/python/kfp/_client.py
Labels: approved, area/sdk/client, kind/feature, lgtm, size/M

#3218 [Frontend] GKE metadata endpoint should fail when fetched response is not ok
  frontend/mock-backend/mock-api-middleware.ts
  frontend/server/app.test.ts
  frontend/server/handlers/gke-metadata.ts
Labels: approved, area/engprod, area/frontend, kind/bug, lgtm, size/M

#3161 backend: Pin python dependencies
  backend/Dockerfile
  backend/README.md
  backend/requirements.in
  backend/requirements.txt
  backend/update_requirements.sh
  test/sample-test/Dockerfile
  test/sample-test/README.md
  test/sample-test/requirements.in
  test/sample-test/requirements.txt
Labels: approved, lgtm, size/L

#3056 Fix config fieldname `PipelineFolder` to `PipelinePath`
  backend/src/apiserver/client_manager.go
  backend/src/apiserver/config/config.json
Labels: approved, lgtm, ok-to-test, size/XS

#3220 Bump TFX to 0.21.1
  backend/requirements.in
  backend/requirements.txt
  backend/update_requirements.sh
  samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py
  samples/core/parameterized_tfx_oss/taxi_pipeline_notebook.ipynb
  test/deploy-cluster.sh
  test/sample-test/requirements.in
  test/sample-test/requirements.txt
Labels: approved, lgtm, size/M

#3212 add an optional name for dsl.Condition (kubeflow#3210)
  sdk/python/kfp/dsl/_ops_group.py
  sdk/python/tests/dsl/ops_group_tests.py
Labels: approved, lgtm, ok-to-test, size/S

#3198 [Backend][Multi-user] Add resource reference to Experiment API
  backend/api/experiment.proto
  backend/api/go_client/experiment.pb.go
  backend/api/go_http_client/experiment_client/experiment_service/list_experiment_parameters.go
  backend/api/go_http_client/experiment_model/BUILD.bazel
  backend/api/go_http_client/experiment_model/api_experiment.go
  backend/api/go_http_client/experiment_model/api_relationship.go
  backend/api/go_http_client/experiment_model/api_resource_key.go
  backend/api/go_http_client/experiment_model/api_resource_reference.go
  backend/api/go_http_client/experiment_model/api_resource_type.go
  backend/api/swagger/experiment.swagger.json
  backend/api/swagger/kfp_api_single_file.swagger.json
Labels: approved, lgtm, size/XL

#3184 [Backend][Multi-user] Add 'Namespace' to Experiment data model
  backend/src/apiserver/client_manager.go
  backend/src/apiserver/model/experiment.go
  backend/src/apiserver/storage/experiment_store.go
  backend/src/apiserver/storage/experiment_store_test.go
Labels: approved, lgtm, size/M

#3240 Clean up kataras dependency
  WORKSPACE
  backend/src/common/util/BUILD.bazel
  backend/src/common/util/formatter_test.go
  go.mod
  go.sum
Labels: size/M

#3225 [UI] Human readable workflow task display names
  frontend/src/lib/ParserUtils.ts
  frontend/src/lib/StaticGraphParser.test.ts
  frontend/src/lib/StaticGraphParser.ts
  frontend/src/lib/WorkflowParser.test.ts
  frontend/src/lib/WorkflowParser.ts
Labels: approved, area/frontend, lgtm, size/M

#3231 retry pipeline always fail (#3230)
  samples/core/retry/retry.py
Labels: approved, lgtm, needs-ok-to-test, size/XS

#3239 [UI] Fix SideNav too tall when collapsed
  frontend/src/components/SideNav.tsx
Labels: approved, area/frontend, kind/bug, lgtm, size/XS

#2879 SDK/CLI: Implement CLI delete pipeline command
  sdk/python/kfp/__main__.py
  sdk/python/kfp/_client.py
  sdk/python/kfp/cli/pipeline.py
Labels: approved, lgtm, ok-to-test, size/S

#3237 [Manifest] fix version for MLMD store
  .release.cloudbuild.yaml
  manifests/kustomize/base/metadata/metadata-deployment.yaml
  test/deploy-pipeline-mkp-cli.sh
Labels: approved, lgtm, size/S

#3228 [Frontend] Fix the TFMA/TFDV viz behavior when caching is used.
  frontend/src/lib/OutputArtifactLoader.ts
Labels: approved, area/frontend, kind/bug, lgtm, size/XS

#3245 Fix ill-formed Cloud Build config
  .cloudbuild.yaml
Labels: approved, lgtm, size/S

#3189 Check Tensorboard Instance
  frontend/src/components/viewers/Tensorboard.test.tsx
  frontend/src/components/viewers/Tensorboard.tsx
  frontend/src/lib/Apis.test.ts
  frontend/src/lib/Apis.ts
Labels: approved, area/frontend, do-not-merge/hold, lgtm, size/L

#3213 SDK/DSL: Enable the deletion of a resource via ResourceOp method
  sdk/python/kfp/dsl/_resource_op.py
  sdk/python/tests/dsl/resource_op_tests.py
  sdk/python/tests/dsl/volume_op_tests.py
Labels: approved, lgtm, size/M

#3065 [Backend] Cache - pod filtering
  backend/src/cache/mutation.go
  backend/src/cache/mutation_test.go
Labels: approved, lgtm, size/M

#3224 [SDK] Use new released kfp-server-api package
  sdk/python/requirements.txt
  sdk/python/setup.py
Labels: approved, area/release, area/sdk/client, lgtm, size/XS

#3255 Bump TFX to 0.21.2
  backend/requirements.in
  backend/requirements.txt
  backend/src/apiserver/visualization/requirements.txt
  frontend/src/lib/OutputArtifactLoader.ts
  samples/core/parameterized_tfx_oss/README.md
  samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py
  samples/core/parameterized_tfx_oss/taxi_pipeline_notebook.ipynb
  test/sample-test/requirements.in
  test/sample-test/requirements.txt
Labels: approved, lgtm, size/L

#3258 SDK - Components - Make component structures hashable
  sdk/python/kfp/components/modelbase.py
Labels: approved, area/sdk/components, lgtm, size/XS

#3257 SDK - Tests - Testing command-line resolving explicitly
  sdk/python/tests/components/test_components.py
  sdk/python/tests/dsl/component_bridge_tests.py
  sdk/python/tests/dsl/main.py
Labels: approved, area/sdk/tests, lgtm, size/L

#3217 [Deployment] Add secure=false explicitly in manifests for better observability
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
Labels: approved, area/backend, area/deployment/marketplace, area/deployment/standalone, kind/bug, lgtm, size/XS

#3264 Remove backend unit tests from Travis config
  .travis.yml
Labels: do-not-merge/hold, lgtm, size/S

#3254 Added 'workgroup' as optional argument to athena component
  components/aws/athena/query/component.yaml
  components/aws/athena/query/src/query.py
Labels: approved, lgtm, ok-to-test, size/L

#3260 Update ai_platform.ipynb
  samples/core/ai_platform/ai_platform.ipynb
Labels: approved, lgtm, ok-to-test, size/XS

#3263 SDK - Components - Fixed handling collection return values
  sdk/python/kfp/components/_python_op.py
  sdk/python/tests/compiler/testdata/parallelfor_item_argument_resolving.yaml
  sdk/python/tests/components/test_python_op.py
Labels: approved, area/sdk/components, lgtm, size/M

#3119 TFX Iris sample
  backend/requirements.txt
  backend/src/apiserver/config/sample_config.json
  frontend/src/config/sample_config_from_backend.json
  frontend/src/pages/__snapshots__/GettingStarted.test.tsx.snap
  samples/core/iris/README.md
  samples/core/iris/iris.py
  test/sample-test/Dockerfile
  test/sample-test/configs/iris.config.yaml
  test/sample-test/requirements.txt
  test/sample-test/run_sample_test.py
  test/sample_test.yaml
Labels: approved, lgtm, size/L

#3267 SDK - Moved _dsl_bridge to dsl
  sdk/python/kfp/dsl/_component_bridge.py
  sdk/python/kfp/dsl/_pipeline.py
  sdk/python/tests/dsl/component_bridge_tests.py
Labels: approved, area/sdk/components, area/sdk/dsl, lgtm, size/S

#3261 add presto pipeline component
  components/presto/query/Dockerfile
  components/presto/query/component.yaml
  components/presto/query/src/program.py
Labels: approved, lgtm, needs-ok-to-test, size/L

#3235 Parametrize the image used for the Tensorboard viewer
  backend/src/crd/controller/viewer/reconciler/reconciler.go
  backend/src/crd/controller/viewer/reconciler/reconciler_test.go
  frontend/server/app.ts
  frontend/server/configs.ts
  frontend/server/handlers/tensorboard.ts
  frontend/server/k8s-helper.ts
Labels: approved, lgtm, ok-to-test, size/M

#3281 [Frontend] Fix reported vulnerabilities
  frontend/package-lock.json
  frontend/package.json
  frontend/server/package-lock.json
Labels: approved, area/engprod, area/frontend, lgtm, size/XL

#3282 [Testing] Recycle upgrade- clusters and reduce time lapse
  test/tools/project-cleaner/resource_spec.yaml
Labels: approved, area/engprod, area/testing, lgtm, size/XS

#3270 Add pipeline version to job/run integration test so that job/run is c…
  backend/test/integration/job_api_test.go
  backend/test/integration/run_api_test.go
  go.sum
Labels: do-not-merge/hold, lgtm, size/L

#3287 [SDK] Improve host name handling
  sdk/python/kfp/_client.py
Labels: approved, lgtm, size/S

#3252 [UI] Pass namespace to experiment api calls
  frontend/src/apis/experiment/api.ts
  frontend/src/pages/ExperimentList.test.tsx
  frontend/src/pages/ExperimentList.tsx
  frontend/src/pages/NewExperiment.test.tsx
  frontend/src/pages/NewExperiment.tsx
  frontend/src/pages/NewRun.test.tsx
  frontend/src/pages/NewRun.tsx
  frontend/src/pages/__snapshots__/ExperimentsAndRuns.test.tsx.snap
Labels: approved, area/frontend, lgtm, size/L

#3120 Backend - Validate compiled samples
  backend/Dockerfile
Labels: approved, area/backend, lgtm, size/XS

#3299 [Test] Switch Travis dependency to TF2
  .travis.yml
Labels: approved, lgtm, size/XS

#3243 [Backend][Multi-user] Add namespace to Experiment API implementation
  backend/src/apiserver/resource/BUILD.bazel
  backend/src/apiserver/resource/model_converter.go
  backend/src/apiserver/resource/model_converter_test.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/server/api_converter.go
  backend/src/apiserver/server/experiment_server.go
  backend/src/apiserver/server/experiment_server_test.go
  backend/src/apiserver/server/run_server_test.go
  backend/src/apiserver/server/test_util.go
  backend/src/apiserver/server/util_test.go
  backend/src/apiserver/storage/experiment_store.go
  backend/src/apiserver/storage/experiment_store_test.go
Labels: approved, lgtm, size/XL

#3285 Add Deletion button to archived runs
  frontend/src/lib/Buttons.ts
  frontend/src/pages/Archive.test.tsx
  frontend/src/pages/Archive.tsx
  frontend/src/pages/__snapshots__/Archive.test.tsx.snap
Labels: approved, lgtm, size/L

#3298 [Test] Use a flag to separate integration test from sample test
  test/sample_test.yaml
Labels: approved, lgtm, size/S

#3274 Update IBM Watson ML sample to use V4 api
  components/ibm-components/watson/deploy/Dockerfile
  components/ibm-components/watson/deploy/src/wml-deploy.py
  components/ibm-components/watson/store/Dockerfile
  components/ibm-components/watson/store/component.yaml
  components/ibm-components/watson/store/src/wml-store.py
  components/ibm-components/watson/train/Dockerfile
  components/ibm-components/watson/train/component.yaml
  components/ibm-components/watson/train/src/wml-train.py
  samples/contrib/ibm-samples/watson/credentials/creds.ini
  samples/contrib/ibm-samples/watson/watson_train_serve_pipeline.py
Labels: approved, lgtm, ok-to-test, size/L

#3307 [Test] expose integration test flag
  test/presubmit-tests-with-pipeline-deployment.sh
  test/sample_test.yaml
Labels: approved, lgtm, size/XS

#3297 [UI] Auto refresh/redirect experiment list/detail page when user selects a different namespace
  frontend/src/pages/ExperimentDetails.test.tsx
  frontend/src/pages/ExperimentDetails.tsx
  frontend/src/pages/ExperimentList.test.tsx
  frontend/src/pages/ExperimentList.tsx
Labels: approved, area/frontend, cuj/multi-user, lgtm, size/L

#3301 Enable archiving logs
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/argo.yaml
  manifests/kustomize/base/argo/workflow-controller-configmap.yaml
  manifests/kustomize/env/gcp/gcp-configurations-patch.yaml
  manifests/kustomize/namespaced/workflow-controller-configmap.yaml
Labels: approved, lgtm, size/S

#3305 [Backend] Always disable istio sidecar injection
  backend/src/apiserver/resource/resource_manager.go
Labels: approved, area/backend, cuj/multi-user, lgtm, size/XS

#3306 Remove unused parameter
  samples/core/exit_handler/exit_handler.py
Labels: approved, area/samples, lgtm, ok-to-test, size/XS

#3320 [UI] Delete manifest.json
  frontend/public/index.html
  frontend/public/static/manifest.json
Labels: approved, area/frontend, kind/bug, lgtm, size/S

#3304 [UI] Show step pod yaml and events in RunDetails page
  frontend/server/app.test.ts
  frontend/server/app.ts
  frontend/server/handlers/gke-metadata.ts
  frontend/server/handlers/pod-info.ts
  frontend/server/handlers/pod-logs.ts
  frontend/server/handlers/tensorboard.ts
  frontend/server/k8s-helper.ts
  frontend/server/proxy-middleware.ts
  frontend/src/TestUtils.tsx
  frontend/src/components/PodYaml.test.tsx
  frontend/src/components/PodYaml.tsx
  frontend/src/lib/Apis.ts
  frontend/src/pages/RunDetails.test.tsx
  frontend/src/pages/RunDetails.tsx
  frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-ui-role.yaml
Labels: approved, area/frontend, kind/feature, lgtm, size/XL

#3266 [Backend]Cache - Cache logic with db interaction
  backend/src/cache/client/kubernetes_core.go
  backend/src/cache/client/kubernetes_core_fake.go
  backend/src/cache/client/pod_fake.go
  backend/src/cache/client/sql.go
  backend/src/cache/client/sql_test.go
  backend/src/cache/client_manager.go
  backend/src/cache/deployer/Dockerfile
  backend/src/cache/main.go
  backend/src/cache/model/execution_cache.go
  backend/src/cache/mutation.go
  backend/src/cache/server/admission.go
  backend/src/cache/server/admission_test.go
  backend/src/cache/server/client_manager_fake.go
  backend/src/cache/server/mutation.go
  backend/src/cache/server/mutation_test.go
  backend/src/cache/server/watcher.go
  backend/src/cache/storage/db.go
  backend/src/cache/storage/db_fake.go
  backend/src/cache/storage/execution_cache_store.go
  backend/src/cache/storage/execution_cache_store_test.go
  manifests/kustomize/base/cache/cache-configmap.yaml
  manifests/kustomize/base/cache/cache-deployment.yaml
  manifests/kustomize/base/cache/cache-role.yaml
  manifests/kustomize/base/cache/cache-rolebinding.yaml
  manifests/kustomize/base/cache/cache-sa.yaml
  manifests/kustomize/base/cache/kustomization.yaml
Labels: approved, lgtm, size/XXL

#3318 SDK - Added support for maxCacheStaleness
  sdk/python/kfp/compiler/_op_to_template.py
  sdk/python/kfp/components/_structures.py
  sdk/python/kfp/components/structures/components.json_schema.json
  sdk/python/kfp/components/structures/components.json_schema.outline.yaml
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/components/test_graph_components.py
Labels: approved, area/sdk, lgtm, size/M

#3316 Update Watson ML example to take output param path
  components/ibm-components/watson/deploy/component.yaml
  components/ibm-components/watson/deploy/src/wml-deploy.py
  components/ibm-components/watson/store/component.yaml
  components/ibm-components/watson/store/src/wml-store.py
  components/ibm-components/watson/train/component.yaml
  components/ibm-components/watson/train/src/wml-train.py
  samples/contrib/ibm-samples/watson/watson_train_serve_pipeline.py
Labels: approved, lgtm, size/M

#3323 SDK - Moved python op pipeline compilation test to bridge tests
  sdk/python/tests/components/test_python_op.py
  sdk/python/tests/dsl/component_bridge_tests.py
Labels: approved, area/sdk/tests, lgtm, size/M

#3324 SDK - Moved the @python_component decorator test to dsl tests
  sdk/python/kfp/components/_python_op.py
  sdk/python/kfp/dsl/_component.py
  sdk/python/tests/components/test_python_op.py
  sdk/python/tests/dsl/component_tests.py
Labels: approved, area/sdk/tests, lgtm, size/M

#3327 Release be497983cda7a1d17f3883c67e39a969cf0868a9
  components/gcp/bigquery/query/README.md
  components/gcp/bigquery/query/component.yaml
  components/gcp/bigquery/query/sample.ipynb
  components/gcp/container/component_sdk/python/setup.py
  components/gcp/dataflow/launch_python/README.md
  components/gcp/dataflow/launch_python/component.yaml
  components/gcp/dataflow/launch_python/sample.ipynb
  components/gcp/dataflow/launch_template/README.md
  components/gcp/dataflow/launch_template/component.yaml
  components/gcp/dataflow/launch_template/sample.ipynb
  components/gcp/dataproc/create_cluster/README.md
  components/gcp/dataproc/create_cluster/component.yaml
  components/gcp/dataproc/create_cluster/sample.ipynb
  components/gcp/dataproc/delete_cluster/README.md
  components/gcp/dataproc/delete_cluster/component.yaml
  components/gcp/dataproc/delete_cluster/sample.ipynb
  components/gcp/dataproc/submit_hadoop_job/README.md
  components/gcp/dataproc/submit_hadoop_job/component.yaml
  components/gcp/dataproc/submit_hadoop_job/sample.ipynb
  components/gcp/dataproc/submit_hive_job/README.md
  components/gcp/dataproc/submit_hive_job/component.yaml
  components/gcp/dataproc/submit_hive_job/sample.ipynb
  components/gcp/dataproc/submit_pig_job/README.md
  components/gcp/dataproc/submit_pig_job/component.yaml
  components/gcp/dataproc/submit_pig_job/sample.ipynb
  components/gcp/dataproc/submit_pyspark_job/README.md
  components/gcp/dataproc/submit_pyspark_job/component.yaml
  components/gcp/dataproc/submit_pyspark_job/sample.ipynb
  components/gcp/dataproc/submit_spark_job/README.md
  components/gcp/dataproc/submit_spark_job/component.yaml
  components/gcp/dataproc/submit_spark_job/sample.ipynb
  components/gcp/dataproc/submit_sparksql_job/README.md
  components/gcp/dataproc/submit_sparksql_job/component.yaml
  components/gcp/dataproc/submit_sparksql_job/sample.ipynb
  components/gcp/ml_engine/batch_predict/README.md
  components/gcp/ml_engine/batch_predict/component.yaml
  components/gcp/ml_engine/batch_predict/sample.ipynb
  components/gcp/ml_engine/deploy/README.md
  components/gcp/ml_engine/deploy/component.yaml
  components/gcp/ml_engine/deploy/sample.ipynb
  components/gcp/ml_engine/train/README.md
  components/gcp/ml_engine/train/component.yaml
  components/gcp/ml_engine/train/sample.ipynb
  components/kubeflow/deployer/component.yaml
  components/kubeflow/dnntrainer/component.yaml
  components/local/confusion_matrix/component.yaml
  components/local/roc/component.yaml
  samples/core/ai_platform/ai_platform.ipynb
  samples/core/dataflow/dataflow.ipynb
  samples/core/kubeflow_tf_serving/kubeflow_tf_serving.ipynb
  samples/core/xgboost_training_cm/xgboost_training_cm.py
  samples/tutorials/mnist/04_Reusable_and_Pre-build_Components_as_Pipeline.ipynb
Labels: approved, lgtm, size/L

#3325 SDK - Tests - Moved imports to the start of the file
  sdk/python/tests/components/test_python_op.py
Labels: approved, area/sdk/tests, lgtm, size/S

#3319 SDK - Support kubernetes client v11
  sdk/python/kfp/compiler/_k8s_helper.py
  sdk/python/kfp/compiler/_op_to_template.py
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/kfp/dsl/_pipeline_param.py
  sdk/python/kfp/dsl/_resource_op.py
  sdk/python/setup.py
Labels: approved, area/sdk, lgtm, size/M

#3329 Bump version to 0.3.0
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml
  manifests/gcp_marketplace/schema.yaml
  manifests/kustomize/README.md
  manifests/kustomize/base/kustomization.yaml
  manifests/kustomize/base/pipeline-application.yaml
  sdk/python/kfp/__init__.py
  sdk/python/requirements.txt
  sdk/python/setup.py
Labels: approved, lgtm, size/L

#3331 Reduce steps for release cloud build yaml
  .release.cloudbuild.yaml
Labels: approved, lgtm, size/M

#3333 [Testing] Disable cache-deployer temporarily because it blocks upgrade tests
  test/manifests/dev/kustomization.yaml
Labels: approved, area/testing, kind/bug, lgtm, size/XS

#3272 [SDK][Multi-user] Add namespace to experiment SDK calls
  sdk/python/kfp/_client.py
Labels: approved, lgtm, size/M

#3349 Update CHANGELOG for 0.3.0
  CHANGELOG.md
Labels: approved, lgtm, size/M

#2992 [Frontend] Node server artifact handler supports preview and handles both archived and unarchived (gzip/tarball) artifacts (#2172)
  frontend/server/app.test.ts
  frontend/server/handlers/artifacts.ts
  frontend/server/minio-helper.test.ts
  frontend/server/minio-helper.ts
  frontend/server/package-lock.json
  frontend/server/package.json
  frontend/server/utils.test.ts
  frontend/server/utils.ts
  frontend/server/workflow-helper.test.ts
Labels: approved, area/frontend, kind/feature, lgtm, ok-to-test, priority/p1, size/XXL

#3348 Fix README formatting.
  manifests/kustomize/README.md
Labels: approved, lgtm, size/S

#3334 [UI Server] Blocks non public KFP report APIs
  frontend/server/app.test.ts
  frontend/server/app.ts
Labels: approved, area/frontend, cuj/multi-user, kind/feature, lgtm, size/M

#3330 Add hostNetwork for marketplace proxy-agent manifest
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/proxy.yaml
Labels: approved, area/deployment/marketplace, lgtm, size/XS

#3326 SDK - Tests - Improved tests for serializing lists containing objects
  sdk/python/tests/components/test_python_op.py
  sdk/python/tests/dsl/component_bridge_tests.py
Labels: approved, area/sdk/tests, lgtm, size/M

#3350 [UI] Stops experiment list from leaking previous error message
  frontend/src/pages/ExperimentList.test.tsx
  frontend/src/pages/ExperimentList.tsx
  frontend/src/pages/Page.tsx
Labels: approved, area/frontend, cuj/multi-user, kind/bug, lgtm, size/M

#3351 [UI] Add namespace filter for All and Archived Runs page
  frontend/src/index.tsx
  frontend/src/pages/AllRunsList.test.tsx
  frontend/src/pages/AllRunsList.tsx
  frontend/src/pages/Archive.test.tsx
  frontend/src/pages/Archive.tsx
  frontend/src/pages/RunList.test.tsx
  frontend/src/pages/RunList.tsx
  frontend/src/pages/__snapshots__/ExperimentsAndRuns.test.tsx.snap
Labels: approved, area/frontend, cuj/multi-user, kind/feature, lgtm, size/L

#3356 Fix Tensorboard viewer image parsing
  frontend/server/k8s-helper.ts
Labels: approved, lgtm, ok-to-test, size/XS

#3357 Integration test fix
  test/deploy-pipeline-mkp-cli.sh
  test/postsubmit-tests-with-pipeline-deployment.sh
Labels: approved, lgtm, size/XS

#3338 [Manifest] Cache - Fix upgrade manifest
  backend/src/cache/deployer/deploy-cache-service.sh
  manifests/kustomize/base/cache-deployer/cache-deployer-job.yaml
  manifests/kustomize/base/cache-deployer/cache-deployer-statefulset.yaml
  manifests/kustomize/base/cache-deployer/kustomization.yaml
  manifests/kustomize/base/cache/cache-deployment.yaml
Labels: approved, lgtm, size/M

#3341 [Backend][Multi-user] Add authorization check on ListExperiment
  backend/src/apiserver/server/experiment_server.go
  backend/src/apiserver/server/experiment_server_test.go
Labels: approved, lgtm, size/M

#3132 apiserver: Handle BucketExists() error
  backend/src/apiserver/client_manager.go
Labels: approved, lgtm, ok-to-test, size/XS

#3355 [UI] Tensorboard support for multi user
  frontend/scripts/start-proxy-and-server.sh
  frontend/server/app.test.ts
  frontend/server/handlers/tensorboard.ts
  frontend/server/k8s-helper.ts
  frontend/src/components/viewers/Tensorboard.test.tsx
  frontend/src/components/viewers/Tensorboard.tsx
  frontend/src/lib/Apis.test.ts
  frontend/src/lib/Apis.ts
  frontend/src/lib/OutputArtifactLoader.test.ts
  frontend/src/lib/OutputArtifactLoader.ts
  frontend/src/pages/Compare.tsx
  frontend/src/pages/RunDetails.tsx
Labels: approved, area/frontend, cuj/multi-user, kind/feature, lgtm, size/XL

#3365 [Test] Add argo retry in sample/integration tests to reduce flakiness.
  test/e2e_test_gke_v2.yaml
  test/sample_test.yaml
Labels: approved, lgtm, size/XS

#3108 Manifests: Rename metadata gRPC server's resources to metadata-grpc-*
  backend/metadata_writer/src/metadata_helpers.py
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/metadata.yaml
  manifests/kustomize/README.md
  manifests/kustomize/base/metadata/kustomization.yaml
  manifests/kustomize/base/metadata/metadata-configmap.yaml
  manifests/kustomize/base/metadata/metadata-envoy-deployment.yaml
  manifests/kustomize/base/metadata/metadata-envoy-service.yaml
  manifests/kustomize/base/metadata/metadata-grpc-deployment.yaml
  manifests/kustomize/base/metadata/metadata-grpc-service.yaml
Labels: approved, lgtm, size/M

#3021 [Sample] CI Sample: Kaggle
  samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/README.md
  samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/cloudbuild.yaml
  samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/create_pipeline_version_and_run.py
  samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/download_dataset/Dockerfile
  samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/download_dataset/component.yaml
  samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/download_dataset/download_data.py
  samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/pipeline.py
  samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/submit_result/Dockerfile
  samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/submit_result/component.yaml
  samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/submit_result/submit_result.py
  samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/train_model/Dockerfile
  samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/train_model/component.yaml
  samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/train_model/train.py
  samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/visualize_html/Dockerfile
  samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/visualize_html/component.yaml
  samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/visualize_html/visualize.py
  samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/visualize_table/Dockerfile
  samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/visualize_table/component.yaml
  samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/visualize_table/visualize.py
Labels: approved, lgtm, ok-to-test, size/XL

#3337 [Backend][Multi-user] Adjust/implement run api for multiuser support
  backend/src/apiserver/common/util.go
  backend/src/apiserver/common/util_test.go
  backend/src/apiserver/list/list.go
  backend/src/apiserver/list/list_test.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/server/run_server.go
  backend/src/apiserver/server/run_server_test.go
  backend/src/apiserver/server/test_util.go
  backend/src/apiserver/server/util.go
  backend/src/apiserver/server/util_test.go
  backend/src/apiserver/storage/run_store.go
Labels: approved, lgtm, size/XL

#3303 SDK - Added pinned dependency snapshot
  sdk/python/requirements.in
  sdk/python/requirements.txt
  sdk/python/setup.py
Labels: approved, area/sdk, lgtm, size/L

#3363 pass token outside of SDK for server-to-server case
  sdk/python/kfp/_client.py
Labels: approved, lgtm, size/M

#3396 Fix lstrip with regex bug in the KFP client
  sdk/python/kfp/_client.py
Labels: approved, lgtm, ok-to-test, size/XS

#3352 [Backend] Cache - Add cache_enabled label for cache filtering
  backend/src/apiserver/common/config.go
  backend/src/apiserver/config/config.json
  backend/src/apiserver/resource/resource_manager.go
  backend/src/common/util/consts.go
  backend/src/common/util/workflow.go
  backend/src/common/util/workflow_test.go
Labels: approved, lgtm, size/M

#3404 Testing - Upgraded GKE master version to fix tests
  test/deploy-cluster.sh
Labels: approved, area/testing, lgtm, size/XS
