Repository kubeflow/pipelines, pull requests merged in 2021-02, with the labels that each got.

#4917 chore(doc): update release doc with caveats on `release-on-tag` retry
  RELEASE.md
  retry-release-on-tag.png
  verify-retry-the-right-build.png
Labels: approved, cla: yes, lgtm, size/XS

#4995 feat(swf): Add a [[RunUUID]] macro
  backend/src/crd/controller/scheduledworkflow/util/parameter_formatter.go
  backend/src/crd/controller/scheduledworkflow/util/parameter_formatter_test.go
  backend/src/crd/controller/scheduledworkflow/util/scheduled_workflow.go
Labels: approved, cla: yes, lgtm, size/M

#5065 fix: upgrade some images to reduce vulnerabilities
  backend/Dockerfile.visualization
  proxy/Dockerfile
  third_party/metadata_envoy/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#5072 chore: update renovate.json5 - preserve semver range
  .github/renovate.json5
Labels: approved, cla: yes, size/XS

#5074 chore: change renovate config to rangeStrategy=update-lock file for npm
  .github/renovate.json5
Labels: approved, cla: yes, size/XS

#5075 chore: set npm rangeStrategy in separate rule
  .github/renovate.json5
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#5076 chore: remove webpack from dependency
  frontend/package-lock.json
  frontend/package.json
Labels: approved, cla: yes, lgtm, size/XXL

#4925 feat(frontend): Feature reduce pipeline graph. Fixes #4924
  frontend/src/Css.tsx
  frontend/src/atoms/CardTooltip.tsx
  frontend/src/atoms/HelpButton.tsx
  frontend/src/components/ReduceGraphSwitch.tsx
  frontend/src/lib/StaticGraphParser.test.ts
  frontend/src/lib/StaticGraphParser.ts
  frontend/src/pages/PipelineDetails.tsx
  frontend/src/pages/RunDetails.test.tsx
  frontend/src/pages/RunDetails.tsx
  frontend/src/pages/__snapshots__/PipelineDetails.test.tsx.snap
  frontend/src/pages/__snapshots__/RunDetails.test.tsx.snap
Labels: approved, area/frontend, cla: yes, lgtm, size/L

#5077 chore: Add zijianjoy as frontend reviewer
  frontend/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#5080 feat(API): Add TriggerPolicy to pipeline_spec
  api/v2alpha1/pipeline_spec.proto
Labels: approved, cla: yes, lgtm, size/S

#5081 release(sdk): Bump KFP SDK version to 1.4.0
  sdk/python/kfp/__init__.py
Labels: approved, cla: yes, lgtm, size/XS

#5082 chore: Improve the error message when incompatible placeholders are connected
  sdk/python/kfp/compiler/_data_passing_rewriter.py
  sdk/python/kfp/compiler/compiler.py
Labels: approved, cla: yes, lgtm, size/S

#5083 chore(sdk): Bring back kfp.v2.components as an alias to kfp.components
  sdk/python/kfp/v2/compiler/compiler_test.py
  sdk/python/kfp/v2/components/__init__.py
Labels: approved, cla: yes, lgtm, size/S

#4981 chore(sdk.v2): Migrate to the new IR with subdag support
  sdk/python/kfp/v2/compiler/compiler.py
  sdk/python/kfp/v2/compiler/compiler_utils.py
  sdk/python/kfp/v2/compiler/compiler_utils_test.py
  sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_after.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_concat_placeholder.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_if_placeholder.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_ontology.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_resource_spec.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_reused_component.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_various_io_types.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/simple_pipeline_without_importer.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/two_step_pipeline_with_importer.json
  sdk/python/kfp/v2/dsl/component_bridge.py
  sdk/python/kfp/v2/dsl/component_spec.py
  sdk/python/kfp/v2/dsl/component_spec_test.py
  sdk/python/kfp/v2/dsl/dsl_utils.py
  sdk/python/kfp/v2/dsl/dsl_utils_test.py
  sdk/python/kfp/v2/dsl/importer_node.py
  sdk/python/kfp/v2/dsl/importer_node_test.py
  sdk/python/setup.py
Labels: approved, cla: yes, lgtm, size/XXL

#5088 Update pipeline_spec.proto
  api/v2alpha1/pipeline_spec.proto
Labels: approved, cla: yes, lgtm, size/M

#5091 fix(samples): Remove broken xgboost sample
  backend/src/apiserver/config/sample_config.json
  frontend/src/config/sample_config_from_backend.json
  frontend/src/pages/GettingStarted.test.tsx
  frontend/src/pages/GettingStarted.tsx
  frontend/src/pages/__snapshots__/GettingStarted.test.tsx.snap
Labels: approved, cla: yes, lgtm, size/XL

#5096 release(api): Bump kfp-pipeline-spec version to 0.1.5
  api/v2alpha1/python/setup.py
Labels: approved, cla: yes, lgtm, size/XS

#5097 chore(sdk): add `absl-py` in kfp install_requires
  sdk/python/setup.py
Labels: approved, cla: yes, lgtm, size/XS

#5079 feat(sdk): Add v2 component to build_python_component
  sdk/python/kfp/components/_python_op.py
  sdk/python/kfp/containers/_component_builder.py
  sdk/python/kfp/containers/entrypoint.py
  sdk/python/kfp/containers/entrypoint_utils.py
  sdk/python/kfp/containers_tests/component_builder_test.py
  sdk/python/kfp/containers_tests/entrypoint_test.py
  sdk/python/kfp/containers_tests/testdata/expected_component.yaml
  sdk/python/kfp/containers_tests/testdata/test_source.py
  sdk/python/kfp/dsl/artifact.py
  sdk/python/tests/compiler/component_builder_test.py
Labels: approved, cla: yes, lgtm, size/XL

#5093 test: Temporarily disable XGBoost tests
  test/component_test.yaml
  test/sample_test.yaml
Labels: approved, cla: yes, lgtm, size/M

#5099 fix(sdk): Add back 'kfp.v2.components' as a package in setup.py
  sdk/python/setup.py
Labels: approved, cla: yes, lgtm, size/XS

#5105 chore(frontend): Add StefanoFioravanzo to reviewers
  frontend/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#5104 feat(sdk.v2): Update v2 compiler to support v2 component.
  sdk/python/kfp/v2/compiler/compiler.py
  sdk/python/kfp/v2/compiler/compiler_utils.py
  sdk/python/kfp/v2/compiler/compiler_utils_test.py
Labels: approved, cla: yes, lgtm, size/M

#5107 feat(sdk.v2): Allow set pipeline_root via @dsl.pipeline decorator. Make pipeline_root optional.
  sdk/python/kfp/dsl/_pipeline.py
  sdk/python/kfp/v2/compiler/compiler.py
  sdk/python/kfp/v2/compiler/compiler_test.py
  sdk/python/kfp/v2/compiler/main.py
  sdk/python/tests/compiler/testdata/uri_artifacts.py
Labels: approved, cla: yes, lgtm, size/L

#5078 chore: adds more Azure Approvers and Reviewers
  components/azure/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#5110 chore(backend): tidy go.mod & update tools.go & fix go vet
  backend/api/build_kfp_server_api_python_package.sh
  backend/src/common/util/pointer.go
  backend/src/common/util/workflow.go
  backend/src/common/util/workflow_test.go
  backend/src/crd/controller/scheduledworkflow/util/cron_schedule_test.go
  go.mod
  go.sum
  tools/metadatastore-upgrade/main.go
  tools/tools.go
Labels: approved, cla: yes, lgtm, size/L

#5113 chore(tfjob-launcher): Add gaocegege and NikeNano as approver
  components/kubeflow/launcher/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#5112 chore(backend): include protoc-gen-go-grpc as tools dependency and add go mod tidy check in CI
  go.mod
  test/presubmit-backend-test.sh
  tools/tools.go
Labels: approved, cla: yes, size/S

#4821 Add references for Tekton backend
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#5122 feat(sdk): Always add pipeline root as a pipeline parameter
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/components/_components.py
  sdk/python/kfp/components_tests/test_components.py
  sdk/python/kfp/dsl/__init__.py
  sdk/python/tests/compiler/testdata/uri_artifacts.yaml
Labels: approved, cla: yes, lgtm, size/L

#5040 feat(frontend): Show Archive tab for runs in Experiment Detail page
  frontend/src/pages/AllRunsAndArchive.test.tsx
  frontend/src/pages/ExperimentDetails.test.tsx
  frontend/src/pages/ExperimentDetails.tsx
  frontend/src/pages/RunListsRouter.test.tsx
  frontend/src/pages/RunListsRouter.tsx
  frontend/src/pages/__snapshots__/AllRunsAndArchive.test.tsx.snap
  frontend/src/pages/__snapshots__/ExperimentDetails.test.tsx.snap
Labels: approved, cla: yes, lgtm, size/XL

#5127 feat(sdk.v2): support dsl.Condition in v2.
  sdk/python/kfp/v2/compiler/compiler.py
  sdk/python/kfp/v2/compiler/compiler_test.py
  sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_condition.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_condition.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_nested_conditions.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_nested_conditions.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_ontology.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_resource_spec.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_various_io_types.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/simple_pipeline_without_importer.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/two_step_pipeline_with_importer.json
  sdk/python/kfp/v2/dsl/__init__.py
  sdk/python/kfp/v2/dsl/_ops_group.py
  sdk/python/kfp/v2/dsl/_pipeline.py
  sdk/python/kfp/v2/dsl/component_spec.py
  sdk/python/kfp/v2/dsl/component_spec_test.py
  sdk/python/kfp/v2/dsl/type_utils.py
  sdk/python/kfp/v2/dsl/type_utils_test.py
  sdk/python/setup.py
Labels: approved, cla: yes, lgtm, size/XXL

#5132 chore(release): Update RELEASE.md
  RELEASE.md
Labels: approved, cla: yes, lgtm, size/XS

#5135 chore(api): Fix kfp-pipeline-spec dependency. Fixes #5134
  api/v2alpha1/python/setup.py
Labels: approved, cla: yes, lgtm, size/XS

#5140 fix(samples): Update KFP version in sample to fix backslash recognization issue.
  samples/tutorials/Data passing in python components.ipynb
Labels: approved, cla: yes, lgtm, size/XS

#5143 feat(api): Update pipeline_spec.proto - Add metadata to ArtifactSpec
  api/v2alpha1/pipeline_spec.proto
Labels: approved, cla: yes, lgtm, size/M

#5144 release(api): Bump kfp-pipeline-spec version to 0.1.6
  api/v2alpha1/python/setup.py
Labels: approved, cla: yes, lgtm, size/XS

#4806 fix(components): fixes issues with tfjob launcher component.
  components/kubeflow/launcher/component.yaml
  components/kubeflow/launcher/sample.py
Labels: approved, cla: yes, lgtm, size/L

#5059 feat(components): Added support for specifying Min and Max replicas for inference services
  components/kubeflow/kfserving/component.yaml
  components/kubeflow/kfserving/src/kfservingdeployer.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#5120 fix(sdk): generate valid pipeline from non-ascii name. Fixes #5119
  sdk/python/kfp/compiler/compiler.py
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#5141 fix(frontend): Show recurring run display name rather than ID. Fix #1786
  frontend/src/lib/RunUtils.ts
  frontend/src/pages/RunList.test.tsx
  frontend/src/pages/RunList.tsx
  frontend/src/pages/__snapshots__/RunList.test.tsx.snap
Labels: approved, cla: yes, lgtm, size/L

#5150 chore(api): build api clients using a prebuilt image
  backend/api/Makefile
Labels: approved, cla: yes, lgtm, size/S

#5153 chore(sdk): allow serializing pipeline params with `typing` type hints
  sdk/python/kfp/components/_data_passing.py
  sdk/python/kfp/components_tests/test_data_passing.py
  sdk/python/kfp/components_tests/test_python_op.py
Labels: approved, cla: yes, lgtm, size/M

#5165 fix(samples): Update tfx image. Fixes #5137
  samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py
Labels: approved, cla: yes, lgtm, size/XS

#5163 feat(sdk): Refactor v2 component building
  sdk/python/kfp/components/_components.py
  sdk/python/kfp/components/_structures.py
  sdk/python/kfp/components/_yaml_utils.py
  sdk/python/kfp/components_tests/test_components.py
  sdk/python/kfp/containers/_component_builder.py
  sdk/python/kfp/containers/entrypoint.py
  sdk/python/kfp/containers_tests/testdata/expected_component.yaml
Labels: approved, cla: yes, lgtm, size/L

#5156 fix(backend): fixes sql error when deploy KFP in ANSI_QUOTES sql mode. Fixes #5121
  backend/src/apiserver/client_manager.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#4879 fix(components): Print logs for AWS SageMaker components
  components/aws/sagemaker/Changelog.md
  components/aws/sagemaker/THIRD-PARTY-LICENSES.txt
  components/aws/sagemaker/batch_transform/component.yaml
  components/aws/sagemaker/batch_transform/src/sagemaker_transform_component.py
  components/aws/sagemaker/create_simulation_app/component.yaml
  components/aws/sagemaker/delete_simulation_app/component.yaml
  components/aws/sagemaker/deploy/component.yaml
  components/aws/sagemaker/ground_truth/component.yaml
  components/aws/sagemaker/hyperparameter_tuning/component.yaml
  components/aws/sagemaker/model/component.yaml
  components/aws/sagemaker/process/component.yaml
  components/aws/sagemaker/process/src/sagemaker_process_component.py
  components/aws/sagemaker/rlestimator/component.yaml
  components/aws/sagemaker/simulation_job/component.yaml
  components/aws/sagemaker/simulation_job_batch/component.yaml
  components/aws/sagemaker/tests/unit_tests/tests/batch_transform/test_transform_component.py
  components/aws/sagemaker/tests/unit_tests/tests/process/test_process_component.py
  components/aws/sagemaker/tests/unit_tests/tests/train/test_train_component.py
  components/aws/sagemaker/train/component.yaml
  components/aws/sagemaker/workteam/component.yaml
Labels: approved, area/components/aws/sagemaker, cla: yes, lgtm, ok-to-test, size/M

#4983 feat(sdk): Add local runner which will run ops in docker or locally. Fixes #1138
  sdk/python/kfp/__init__.py
  sdk/python/kfp/_local_client.py
  sdk/python/kfp/_runners.py
  sdk/python/tests/local_runner_test.py
  test/presubmit-tests-sdk.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#5176 fix: upgrade tfx samples & deps to 0.27.0. Part of #5137
  backend/Dockerfile.visualization
  backend/requirements.in
  backend/requirements.txt
  backend/src/apiserver/visualization/requirements-test.txt
  backend/src/apiserver/visualization/requirements.in
  backend/src/apiserver/visualization/requirements.txt
  backend/src/apiserver/visualization/update_requirements.sh
  samples/core/iris/iris.py
  samples/core/parameterized_tfx_oss/taxi_pipeline_notebook.ipynb
Labels: approved, cla: yes, size/XL

#5179 test: fix tfx version consistently. Part of #5137
  sdk/python/requirements.in
  sdk/python/requirements.txt
  test/sample-test/README.md
  test/sample-test/hack/update_requirements.sh
  test/sample-test/requirements.in
  test/sample-test/requirements.txt
Labels: approved, cla: yes, size/L

#4479 Changes for kfserving 0.4.1
  components/kubeflow/kfserving/Dockerfile
  components/kubeflow/kfserving/component.yaml
  components/kubeflow/kfserving/src/kfservingdeployer.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#5185 chore(sdk.v2): Error out on input value being a combination of constant value and PipelineParam reference.
  sdk/python/kfp/v2/compiler/compiler_test.py
  sdk/python/kfp/v2/dsl/component_bridge.py
Labels: approved, cla: yes, lgtm, size/S

#5146 feat(sdk.v2): Implement AI Platform (Unified) Custom job component in KFP v2 SDK
  sdk/python/kfp/dsl/_component_bridge.py
  sdk/python/kfp/dsl/artifact.py
  sdk/python/kfp/v2/compiler/compiler.py
  sdk/python/kfp/v2/dsl/component_bridge.py
  sdk/python/kfp/v2/dsl/dsl_utils.py
  sdk/python/kfp/v2/dsl/dsl_utils_test.py
  sdk/python/kfp/v2/dsl/type_utils.py
  sdk/python/kfp/v2/dsl/type_utils_test.py
  sdk/python/kfp/v2/google/__init__.py
  sdk/python/kfp/v2/google/aiplatform.py
  sdk/python/kfp/v2/google/aiplatform_e2e_test.py
  sdk/python/kfp/v2/google/aiplatform_test.py
  sdk/python/kfp/v2/google/testdata/expected_custom_job_pipeline.json
  sdk/python/tests/dsl/ontology_artifacts_test.py
Labels: approved, cla: yes, lgtm, size/XXL

#5186 fix(frontend): example-validator visualization for TFX 0.27.0. Part of #5137
  frontend/src/lib/OutputArtifactLoader.ts
Labels: approved, cla: yes, lgtm, size/M

#5188 fix(cache): do not cache TFX pods for newer TFX versions. Part of #5137
  backend/src/cache/server/mutation.go
  backend/src/cache/server/mutation_test.go
Labels: approved, cla: yes, size/S

#5187 chore(sdk): update requirements.in to be in sync with setup.py
  sdk/python/requirements.in
  sdk/python/requirements.txt
  sdk/python/setup.py
Labels: approved, cla: yes, lgtm, size/M

#5189 fix(samples): remove TFX iris example. Part of #5137
  backend/src/apiserver/config/sample_config.json
  frontend/src/config/sample_config_from_backend.json
  frontend/src/pages/GettingStarted.test.tsx
  frontend/src/pages/GettingStarted.tsx
  frontend/src/pages/__snapshots__/GettingStarted.test.tsx.snap
  samples/core/iris/README.md
  samples/core/iris/iris.py
  test/sample-test/configs/iris.config.yaml
  test/sample-test/run_sample_test.py
  test/sample_test.yaml
Labels: approved, cla: yes, size/XL

#5192 chore(release): drastically make component release script faster
  components/release-in-place.sh
Labels: approved, cla: yes, size/S

#5191 fix(visualization): downgrade tfma to 0.26
  backend/src/apiserver/visualization/requirements.in
  backend/src/apiserver/visualization/requirements.txt
Labels: approved, cla: yes, size/M

#5162 feat(sdk.v2): Support dsl.ParallelFor in v2.
  sdk/python/kfp/dsl/_for_loop.py
  sdk/python/kfp/v2/compiler/compiler.py
  sdk/python/kfp/v2/compiler/compiler_test.py
  sdk/python/kfp/v2/compiler/compiler_utils.py
  sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_condition.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loop_output.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loop_output.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loop_parameter.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loop_parameter.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loop_static.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loop_static.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_nested_conditions.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_reused_component.json
  sdk/python/kfp/v2/dsl/_ops_group.py
  sdk/python/kfp/v2/dsl/component_bridge.py
  sdk/python/kfp/v2/dsl/component_spec.py
  sdk/python/kfp/v2/dsl/component_spec_test.py
  sdk/python/kfp/v2/dsl/container_op.py
  sdk/python/kfp/v2/dsl/dsl_utils.py
  sdk/python/kfp/v2/dsl/dsl_utils_test.py
Labels: approved, cla: yes, lgtm, size/XXL

#5174 chore(sdk): remove redundant method: `_pipelineparam_full_name()`
  sdk/python/kfp/compiler/compiler.py
Labels: approved, cla: yes, lgtm, size/S

#5070 <feat>[components]: Add pipeline component to schedule spark jobs in Azure Synapse
  components/azure/azuresynapse/runsparkjob/Dockerfile
  components/azure/azuresynapse/runsparkjob/README.md
  components/azure/azuresynapse/runsparkjob/component.yaml
  components/azure/azuresynapse/runsparkjob/sample.py
  components/azure/azuresynapse/runsparkjob/src/requirement.txt
  components/azure/azuresynapse/runsparkjob/src/spark_pool_config.yaml
  components/azure/azuresynapse/runsparkjob/src/submit_job.sh
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/L

#5195 chore(release): change all release scripts to run in docker
  Makefile
  RELEASE.md
  test/release/Dockerfile.release
  test/release/Makefile
  test/release/README.md
  test/release/bump-version-docker.sh
  test/release/bump-version-in-place.sh
  test/release/check-release-needed-tools.sh
  test/release/release.sh
Labels: approved, cla: yes, size/L

#5064 chore: Remove pip requirements from docker files
  backend/Dockerfile
  backend/Dockerfile.visualization
  components/arena/docker/requirements.txt
  components/gcp/container/Dockerfile
  components/gcp/container/requirements.txt
  components/ibm-components/ffdl/serve/Dockerfile
  components/ibm-components/ffdl/serve/requirements.txt
  components/ibm-components/ffdl/train/Dockerfile
  components/ibm-components/ffdl/train/requirements.txt
  components/ibm-components/watson/deploy/Dockerfile
  components/ibm-components/watson/deploy/requirements.txt
  components/ibm-components/watson/store/Dockerfile
  components/ibm-components/watson/store/requirements.txt
  components/ibm-components/watson/train/Dockerfile
  components/ibm-components/watson/train/requirements.txt
  components/kubeflow/dnntrainer/Dockerfile
  components/kubeflow/dnntrainer/requirements.txt
  components/kubeflow/kfserving/Dockerfile
  components/kubeflow/kfserving/requirements.txt
  components/kubeflow/launcher/Dockerfile
  components/kubeflow/launcher/requirements.txt
  components/local/base/Dockerfile
  components/local/base/requirements.txt
  components/presto/query/Dockerfile
  components/presto/query/requirements.txt
  components/sample/keras/train_classifier/Dockerfile
  components/sample/keras/train_classifier/requirements.txt
  proxy/Dockerfile
  proxy/requirements.txt
  samples/contrib/nvidia-resnet/components/preprocess/Dockerfile
  samples/contrib/nvidia-resnet/components/preprocess/requirements.txt
  samples/contrib/nvidia-resnet/components/train/Dockerfile
  samples/contrib/nvidia-resnet/components/train/requirements.txt
  samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/download_dataset/Dockerfile
  samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/download_dataset/requirements.txt
  samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/submit_result/Dockerfile
  samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/submit_result/requirements.txt
  samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/train_model/Dockerfile
  samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/train_model/requirements.txt
  samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/visualize_html/Dockerfile
  samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/visualize_html/requirements.txt
  samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/visualize_table/Dockerfile
  samples/contrib/versioned-pipeline-ci-samples/kaggle-ci-sample/visualize_table/requirements.txt
Labels: approved, cla: yes, lgtm, size/L

#4835 feat(backend): Added multi-user pipelines (UI + API); Fixes #4197
  backend/api/go_client/pipeline.pb.go
  backend/api/go_http_client/pipeline_client/pipeline_service/list_pipelines_parameters.go
  backend/api/go_http_client/pipeline_model/api_pipeline.go
  backend/api/go_http_client/pipeline_model/api_pipeline_version.go
  backend/api/pipeline.proto
  backend/api/python_http_client/docs/ApiPipeline.md
  backend/api/python_http_client/docs/PipelineServiceApi.md
  backend/api/python_http_client/kfp_server_api/api/pipeline_service_api.py
  backend/api/python_http_client/kfp_server_api/models/api_pipeline.py
  backend/api/python_http_client/test/test_api_list_pipelines_response.py
  backend/api/python_http_client/test/test_api_pipeline.py
  backend/api/swagger/kfp_api_single_file.swagger.json
  backend/api/swagger/pipeline.swagger.json
  backend/src/apiserver/client_manager.go
  backend/src/apiserver/common/const.go
  backend/src/apiserver/main.go
  backend/src/apiserver/model/pipeline.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/server/pipeline_server.go
  backend/src/apiserver/server/pipeline_server_test.go
  backend/src/apiserver/server/pipeline_upload_server.go
  backend/src/apiserver/server/pipeline_upload_server_test.go
  backend/src/apiserver/server/test_util.go
  backend/src/apiserver/storage/pipeline_store.go
  backend/src/apiserver/storage/pipeline_store_test.go
  backend/test/integration/pipeline_api_test.go
  backend/test/integration/pipeline_version_api_test.go
  manifests/kustomize/base/pipeline/multi-user/view-edit-roles.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#5158 fix(deployment): Updated the manifests with resource requests. Fixes #5148
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/argo.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/minio.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml
  manifests/kustomize/base/argo/workflow-controller-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-ui-deployment.yaml
  manifests/kustomize/env/azure/minio-azure-gateway/minio-azure-gateway-deployment.yaml
  manifests/kustomize/env/gcp/minio-gcs-gateway/minio-gcs-gateway-deployment.yaml
  manifests/kustomize/env/platform-agnostic/minio/minio-deployment.yaml
Labels: approved, cla: yes, lgtm, size/M
