Repository kubeflow/pipelines, pull requests merged in 2021-10, with the labels that each got.

#6621 refactor(backend): remove dep from model to common package
  backend/src/apiserver/common/const.go
  backend/src/apiserver/common/filter_context.go
  backend/src/apiserver/list/list.go
  backend/src/apiserver/list/list_test.go
  backend/src/apiserver/model/resource_reference.go
  backend/src/apiserver/model/resource_reference_test.go
  backend/src/apiserver/resource/model_converter.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/server/api_converter.go
  backend/src/apiserver/storage/resource_reference_store.go
Labels: lgtm, approved, size/L, cla: yes

#6597 feat(components/google-cloud): Add description for prep data for train component.
  components/google-cloud/google_cloud_pipeline_components/experimental/forecasting/prepare_data_for_train/component.yaml
Labels: lgtm, approved, size/M, cla: yes

#6630 feat(components): Adds Notebooks Executor API in the experimental components
  .gitignore
  components/google-cloud/dependencies.py
  components/google-cloud/google_cloud_pipeline_components/container/aiplatform/Dockerfile
  components/google-cloud/google_cloud_pipeline_components/container/aiplatform/cloudbuild.yaml
  components/google-cloud/google_cloud_pipeline_components/container/experimental/notebooks/__init__.py
  components/google-cloud/google_cloud_pipeline_components/container/experimental/notebooks/executor.py
  components/google-cloud/google_cloud_pipeline_components/experimental/notebooks/__init__.py
  components/google-cloud/google_cloud_pipeline_components/experimental/notebooks/executor/component.yaml
  components/google-cloud/google_cloud_pipeline_components/experimental/notebooks/executor/samples/runnables/parameters.yaml
  components/google-cloud/google_cloud_pipeline_components/experimental/notebooks/executor/samples/runnables/run_create_bucket.ipynb
  components/google-cloud/google_cloud_pipeline_components/experimental/notebooks/executor/samples/sample.ipynb
  components/google-cloud/tests/container/experimental/notebooks/test_executor.py
Labels: lgtm, approved, size/XL, cla: yes

#6474 chore(components/google-cloud): remove custom python package training op
  components/google-cloud/google_cloud_pipeline_components/aiplatform/__init__.py
Labels: lgtm, approved, size/XS, cla: yes

#6662 chore(api): Add default_value in ComponentInputsSpec.ParameterSpec and default_pipeline_root in PipelineSpec.
  api/v2alpha1/pipeline_spec.proto
Labels: lgtm, approved, size/XS, cla: yes

#6665 fix(components/google-cloud): Remove executor_input
  components/google-cloud/google_cloud_pipeline_components/experimental/custom_job/custom_job.py
  components/google-cloud/tests/experimental/custom_job/integration/test_custom_job_complie.py
  components/google-cloud/tests/experimental/custom_job/testdata/custom_job_container_component_pipeline.json
  components/google-cloud/tests/experimental/custom_job/testdata/custom_job_python_component_pipeline.json
  components/google-cloud/tests/experimental/custom_job/unit/test_custom_job.py
Labels: lgtm, approved, size/L, cla: yes

#6666 chore: Release KFP SDK and v2 launcher 1.8.4
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
  sdk/python/kfp/compiler/v2_compat.py
Labels: lgtm, approved, size/M, cla: yes

#6678 feat(components): bump kfp version
  components/google-cloud/dependencies.py
Labels: lgtm, size/XS, cla: yes

#6660 chore(components): Update model deploy doc
  components/google-cloud/google_cloud_pipeline_components/aiplatform/endpoint/deploy_model/component.yaml
Labels: lgtm, approved, size/M, cla: yes

#6677 fix(components/google-cloud): Set executor_input to empty for custom job
  components/google-cloud/google_cloud_pipeline_components/experimental/custom_job/custom_job.py
  components/google-cloud/tests/aiplatform/integration/test_components_compile.py
  components/google-cloud/tests/aiplatform/testdata/create_endpoint_pipeline.json
  components/google-cloud/tests/aiplatform/testdata/model_deploy_pipeline.json
  components/google-cloud/tests/aiplatform/testdata/model_export_pipeline.json
  components/google-cloud/tests/aiplatform/testdata/model_upload_pipeline.json
  components/google-cloud/tests/experimental/custom_job/integration/test_custom_job_complie.py
  components/google-cloud/tests/experimental/custom_job/testdata/custom_job_container_component_pipeline.json
  components/google-cloud/tests/experimental/custom_job/testdata/custom_job_python_component_pipeline.json
  components/google-cloud/tests/experimental/custom_job/unit/test_custom_job.py
Labels: approved, size/L, cla: yes

#6684 chore(api): release kfp-pipeline spec 0.1.12 and update golang generated code
  api/v2alpha1/go/pipelinespec/pipeline_spec.pb.go
  api/v2alpha1/python/setup.py
Labels: lgtm, approved, size/XXL, cla: yes

#6671 chore(components): Import module instead of functions; remove unneeded dependencies
  components/google-cloud/google_cloud_pipeline_components/aiplatform/utils.py
Labels: lgtm, approved, size/S, cla: yes

#6688 fix(components/google-cloud): REVERT - remove custom python package training op
  components/google-cloud/google_cloud_pipeline_components/aiplatform/__init__.py
Labels: lgtm, approved, size/XS, cla: yes

#6682 fix(sdk.v2): Fix executor getting None as value when float 0 is passed in. Fixes #6636
  sdk/RELEASE.md
  sdk/python/kfp/v2/components/executor.py
  sdk/python/kfp/v2/components/executor_test.py
Labels: lgtm, approved, size/M, cla: yes

#6409 feat(frontend): Allow setting s3 region for artifacts
  frontend/server/configs.ts
  frontend/server/integration-tests/artifact-get.test.ts
Labels: lgtm, approved, size/S, ok-to-test, cla: yes
