Repository kubeflow/pipelines, pull requests merged in 2021-08, with the labels that each got.

#5972 feat(sdk): add GPU runtime resource request and fix spelling in runtime_resouce_request. Fixes #4877. Fixes #1252
  samples/core/resource_spec/runtime_resource_request.py
  samples/core/resource_spec/runtime_resource_request_gpu.py
  sdk/python/kfp/compiler/_op_to_template.py
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/tests/compiler/compiler_tests.py
Labels: approved, cla: yes, lgtm, size/L

#6188 feat(components/google-cloud): Add NAB scoring to tfp_anomaly_detection
  components/google-cloud/google_cloud_pipeline_components/experimental/tensorflow_probability/anomaly_detection/component.yaml
  components/google-cloud/google_cloud_pipeline_components/experimental/tensorflow_probability/anomaly_detection/tfp_anomaly_detection.ipynb
  components/google-cloud/google_cloud_pipeline_components/experimental/tensorflow_probability/anomaly_detection/tfp_anomaly_detection.py
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XL

#6124 feat(sdk): Allow parametrization of ui_host in kfp.Client
  sdk/python/kfp/_client.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#6217 chore(frontend): Create a secret page for managing frontend features visibility. Fix #6073
  frontend/README.md
  frontend/src/components/Router.tsx
  frontend/src/components/__snapshots__/Router.test.tsx.snap
  frontend/src/features.ts
  frontend/src/pages/FrontendFeatures.tsx
Labels: approved, cla: yes, lgtm, size/L

#6136 chore(test): Automatic clean up periodic persistent disk. Fix #2523
  test/tools/project-cleaner/go.mod
  test/tools/project-cleaner/go.sum
  test/tools/project-cleaner/main.go
  test/tools/project-cleaner/resource_spec.yaml
Labels: approved, cla: yes, lgtm, size/XL

#6145 fix(sdk): google client, Enable to provide app engine region that scheduled job is created in
  sdk/python/kfp/v2/google/client/client.py
  sdk/python/kfp/v2/google/client/schedule.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#6213 fix(frontend): mock-backend didn't understand absolute path import in frontend/src/. Fix #6212
  frontend/mock-backend/tsconfig.json
  frontend/package-lock.json
  frontend/package.json
Labels: approved, cla: yes, lgtm, size/XL

#6206 chore(frontend): Create script to build pipeline_spec with protobuf.js. Fix #6205
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/scripts/pipelinespec_pbjs.js
  frontend/src/generated/pipeline_spec/pbjs_ml_pipelines.d.ts
  frontend/src/generated/pipeline_spec/pbjs_ml_pipelines.js
Labels: approved, cla: yes, lgtm, size/XXL

#6220 feat(sdk): update pipeline_spec.proto to add artifact schema version field
  api/v2alpha1/pipeline_spec.proto
Labels: approved, cla: yes, lgtm, size/XS

#6221 feat(api): Add PipelineTaskFinalStatus to pipeline_spec.proto
  api/v2alpha1/google/rpc/status.proto
  api/v2alpha1/pipeline_spec.proto
Labels: approved, cla: yes, lgtm, size/M

#6227 test: Remove upgrade command in project_cleaner
  test/tools/project-cleaner/project_cleaner.sh
Labels: approved, cla: yes, lgtm, size/S

#6228 feat: upgrade to argo v3.1.5-patch
  .cloudbuild.yaml
  .release.cloudbuild.yaml
  backend/third_party_licenses/apiserver.csv
  backend/third_party_licenses/cache_server.csv
  backend/third_party_licenses/persistence_agent.csv
  backend/third_party_licenses/swf.csv
  go.mod
  go.sum
  manifests/kustomize/third-party/argo/base/workflow-controller-deployment-patch.yaml
  test/install-argo-cli.sh
  test/tag_for_hosted.sh
  third_party/argo/Dockerfile.argoexec
  third_party/argo/Dockerfile.workflow-controller
  third_party/argo/VERSION
  third_party/argo/licenses-argoexec.csv
  third_party/argo/licenses-workflow-controller.csv
Labels: approved, cla: yes, lgtm, size/M

#6223 chore(api): Using Makefile to pull dependency proto
  api/Makefile
  api/README.md
  api/v2alpha1/google/rpc/status.proto
Labels: approved, cla: yes, lgtm, size/M

#6230 revert: "feat!: use argo emissary executor by default. Fixes #5718"
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/argo.yaml
  manifests/kustomize/third-party/argo/base/workflow-controller-configmap-patch.yaml
Labels: approved, cla: yes, lgtm, size/XS

#6218 feat(frontend): Select node using execution ID via router param in run detail page. Partial #5977
  frontend/src/components/Router.tsx
  frontend/src/components/__snapshots__/Router.test.tsx.snap
  frontend/src/mlmd/MlmdUtils.ts
  frontend/src/pages/RunDetails.test.tsx
  frontend/src/pages/RunDetails.tsx
Labels: approved, cla: yes, lgtm, size/M

#6229 chore(backend): pin sdk version to released version. Fixes #5689
  backend/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#6234 chore: update pipeline_spec.proto comments for `schema_title` format and sync the deprecation warning for `schema_uri`.
  api/v2alpha1/pipeline_spec.proto
Labels: approved, cla: yes, lgtm, size/S

#6222 chore(components/google-cloud): Clean up unit tests
  components/google-cloud/tests/aiplatform/test_componets_compile.py
  components/google-cloud/tests/experimental/remote/gcp_launcher/test_custom_job_remote_runner.py
  components/google-cloud/tests/presubmit.sh
Labels: approved, cla: yes, lgtm, size/M

#6203 feat(sdk): add_default_resource_spec container op transformer
  samples/core/resource_spec/resource_spec.py
  samples/core/visualization/tensorboard_minio.py
  samples/test/util.py
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/kfp/onprem.py
Labels: approved, cla: yes, lgtm, size/L

#6240 test(v2): build go images using ko. Fixes #6238
  sdk/python/kfp/compiler/testdata/v2_compatible_two_step_pipeline.yaml
  sdk/python/kfp/compiler/testdata/v2_compatible_two_step_pipeline_with_custom_launcher.yaml
  sdk/python/kfp/compiler/v2_compat.py
  v2/Makefile
  v2/README.md
  v2/cmd/launcher-v2/main.go
  v2/cmd/launcher/main.go
  v2/compiler/argo_test.go
  v2/compiler/container.go
  v2/compiler/dag.go
  v2/component/util.go
  v2/container/driver/Dockerfile
  v2/container/driver/Dockerfile.dev
  v2/container/launcher-v2/Dockerfile
  v2/container/launcher-v2/Dockerfile.dev
  v2/container/launcher/Dockerfile
  v2/container/launcher/Dockerfile.dev
  v2/container/launcher/mount_launcher.sh
  v2/test/Dockerfile
  v2/test/components/build_go.yaml
  v2/test/components/run_sample.yaml
  v2/test/presubmit-v2-go-test.sh
  v2/test/sample_test.py
  v2/test/scripts/install-docker-cred-gcr.sh
Labels: approved, cla: yes, lgtm, size/L

#6239 chore: update component owner file
  components/OWNERS
Labels: lgtm, approved, size/S, cla: yes

#6242 chore: Update package version for pipeline-spec release
  api/v2alpha1/python/setup.py
Labels: lgtm, approved, size/XS, cla: yes

#6245 chore: make directories before downloading api dependency proto
  api/Makefile
Labels: lgtm, approved, size/XS, cla: yes

#6202 feat(sdk): Enable the use of Executor from KFP package for v2 lightweight components
  samples/test/lightweight_python_functions_v2_pipeline.py
  samples/test/lightweight_python_functions_v2_with_outputs.py
  samples/test/metrics_visualization_v2.py
  sdk/python/kfp/compiler/testdata/v2_compatible_two_step_pipeline.yaml
  sdk/python/kfp/compiler/testdata/v2_compatible_two_step_pipeline_with_custom_launcher.yaml
  sdk/python/kfp/components/_python_op.py
  sdk/python/kfp/components/executor_main.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_pipeline.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_with_outputs.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_after.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_concat_placeholder.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_condition.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_custom_job_spec.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_exit_handler.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_if_placeholder.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_importer.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loop_output.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loop_parameter.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loop_static.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loops_and_conditions.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_metrics_outputs.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_nested_conditions.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_nested_conditions_yaml.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_nested_loops.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_ontology.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_params_containing_format.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_resource_spec.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_reused_component.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_various_io_types.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/two_step_pipeline.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/xgboost_sample_pipeline.json
  sdk/python/kfp/v2/dsl/component_decorator.py
  v2/test/Makefile
  v2/test/presubmit.sh
  v2/test/requirements.txt
  v2/test/sample_test.py
  v2/test/scripts/upload_gcs_blob.py
Labels: lgtm, approved, size/XL, cla: yes

#6247 test: Remove old v2 launcher building steps.
  v2/test/sample_test.py
Labels: lgtm, approved, size/XS, cla: yes

#6236 fix: fix a spelling error
  backend/src/crd/controller/scheduledworkflow/client/kube_client.go
  samples/core/caching/caching.ipynb
  samples/core/caching/caching_sample.py
Labels: lgtm, approved, size/S, ok-to-test, cla: yes

#6233 chore(frontend): Mock one v2 pipeline spec response. Fix #6232
  frontend/mock-backend/data/v2/pipeline/README.md
  frontend/mock-backend/data/v2/pipeline/mock_lightweight_python_functions_v2_pipeline.json
  frontend/mock-backend/fixed-data.ts
  frontend/mock-backend/mock-api-middleware.ts
Labels: lgtm, approved, size/L, cla: yes

#6248 feat(deployment): provide platform-agnostic-emissary and platform-agnostic-multi-user-emissary as options
  manifests/kustomize/README.md
  manifests/kustomize/env/platform-agnostic-emissary/kustomization.yaml
  manifests/kustomize/env/platform-agnostic-emissary/workflow-controller-configmap-patch.yaml
  manifests/kustomize/env/platform-agnostic-multi-user-emissary/kustomization.yaml
  manifests/kustomize/env/platform-agnostic-multi-user-emissary/workflow-controller-configmap-patch.yaml
  manifests/kustomize/hack/test.sh
Labels: lgtm, approved, size/L, cla: yes

#6224 fix(components/google-cloud): Add temporary work around for key not found during compile
  components/google-cloud/google_cloud_pipeline_components/experimental/custom_job/custom_job.py
  components/google-cloud/google_cloud_pipeline_components/experimental/remote/gcp_launcher/launcher.py
  components/google-cloud/tests/experimental/custom_job/test_custom_job.py
  components/google-cloud/tests/experimental/remote/gcp_launcher/test_launcher.py
Labels: lgtm, approved, size/M, cla: yes

#6246 feat(sdk.v2): Add HTML and Markdown artifact types
  sdk/python/kfp/dsl/io_types.py
  sdk/python/kfp/dsl/type_utils.py
  sdk/python/kfp/dsl/type_utils_test.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_various_io_types.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_various_io_types.py
Labels: lgtm, approved, size/M, cla: yes

#6210 feat(sdk.v2): Define BaseComponent, ComponentSpec, and PipelineTask.
  sdk/python/kfp/dsl/_component_bridge.py
  sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/experimental_v2_component.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/experimental_v2_component.py
  sdk/python/kfp/v2/components/experimental/__init__.py
  sdk/python/kfp/v2/components/experimental/base_component.py
  sdk/python/kfp/v2/components/experimental/base_component_test.py
  sdk/python/kfp/v2/components/experimental/component_spec.py
  sdk/python/kfp/v2/components/experimental/component_spec_test.py
  sdk/python/kfp/v2/components/experimental/pipeline_task.py
  sdk/python/requirements.in
  sdk/python/setup.py
Labels: lgtm, approved, size/XL, cla: yes

#6244 chore(components/google-cloud): Add seed to tfp_anomaly_detection
  components/google-cloud/google_cloud_pipeline_components/experimental/tensorflow_probability/anomaly_detection/tfp_anomaly_detection.ipynb
Labels: lgtm, approved, size/XS, ok-to-test, cla: yes

#6257 chore: release KFP SDK and v2 launcher 1.7.0
  sdk/python/kfp/__init__.py
  sdk/python/kfp/compiler/v2_compat.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_pipeline.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_with_outputs.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_custom_job_spec.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_exit_handler.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_importer.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_metrics_outputs.json
Labels: lgtm, approved, size/M, cla: yes

#6262 chore: update Dockerfile for SDK 1.7.0
  backend/Dockerfile
Labels: lgtm, approved, size/XS, cla: yes

#6258 feat(frontend): Prepare PipelineDetailPage to show different contents based on V1/V2 pipeline spec. Fix #6214
  frontend/src/TestUtils.ts
  frontend/src/components/Router.tsx
  frontend/src/components/SidePanel.tsx
  frontend/src/components/__snapshots__/Router.test.tsx.snap
  frontend/src/features.ts
  frontend/src/lib/Buttons.ts
  frontend/src/pages/PipelineDetails.test.tsx
  frontend/src/pages/PipelineDetails.tsx
  frontend/src/pages/PipelineDetailsV1.test.tsx
  frontend/src/pages/PipelineDetailsV1.tsx
  frontend/src/pages/PipelineList.test.tsx
  frontend/src/pages/PipelineList.tsx
  frontend/src/pages/__snapshots__/PipelineDetails.test.tsx.snap
  frontend/src/pages/v2/StaticCanvas.tsx
Labels: lgtm, approved, size/XXL, cla: yes

#6266 test: fix make push-launcher
  v2/Makefile
Labels: lgtm, approved, size/XS, cla: yes

#6267 docs: v2 compatible release instructions
  v2/README.md
Labels: lgtm, approved, size/M, cla: yes

#6219 chore(components/pytorch): Updating pytorch-kfp-component dependency list
  components/PyTorch/pytorch-kfp-components/setup.py
Labels: lgtm, approved, size/XS, ok-to-test, cla: yes

#6231 fix(components/pytorch): PyTorch Samples - Generating component.yaml using templates
  components/PyTorch/pytorch-kfp-components/templates/ax_complete_trials_component.yaml
  components/PyTorch/pytorch-kfp-components/templates/ax_generate_trials_component.yaml
  components/PyTorch/pytorch-kfp-components/templates/ax_train_component.yaml
  components/PyTorch/pytorch-kfp-components/templates/copy_component.yaml
  components/PyTorch/pytorch-kfp-components/templates/deploy_component.yaml
  components/PyTorch/pytorch-kfp-components/templates/minio_component.yaml
  components/PyTorch/pytorch-kfp-components/templates/prediction_component.yaml
  components/PyTorch/pytorch-kfp-components/templates/preprocess_component.yaml
  components/PyTorch/pytorch-kfp-components/templates/tensorboard_component.yaml
  components/PyTorch/pytorch-kfp-components/templates/train_component.yaml
  samples/contrib/pytorch-samples/Pipeline-Bert-Dist.ipynb
  samples/contrib/pytorch-samples/Pipeline-Bert.ipynb
  samples/contrib/pytorch-samples/Pipeline-Cifar10-Captum-Insights.ipynb
  samples/contrib/pytorch-samples/Pipeline-Cifar10-hpo.ipynb
  samples/contrib/pytorch-samples/Pipeline-Cifar10.ipynb
  samples/contrib/pytorch-samples/bert/pipeline.py
  samples/contrib/pytorch-samples/bert/template_mapping.json
  samples/contrib/pytorch-samples/build.sh
  samples/contrib/pytorch-samples/cifar10/ax_template_mapping.json
  samples/contrib/pytorch-samples/cifar10/cifar10_pre_process.py
  samples/contrib/pytorch-samples/cifar10/pipeline.py
  samples/contrib/pytorch-samples/cifar10/template_mapping.json
  samples/contrib/pytorch-samples/cifar10/yaml/pre_process/component.yaml
  samples/contrib/pytorch-samples/cluster_build.md
  samples/contrib/pytorch-samples/local_build.md
  samples/contrib/pytorch-samples/utils/__init__.py
  samples/contrib/pytorch-samples/utils/generate_templates.py
  samples/contrib/pytorch-samples/utils/template-generation.md
Labels: lgtm, approved, size/XXL, ok-to-test, cla: yes

#6265 chore(frontend): Integrate with tailwindcss. Fix #6264
  frontend/.gitignore
  frontend/craco.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Router.tsx
  frontend/src/components/SideNav.test.tsx
  frontend/src/components/SideNav.tsx
  frontend/src/components/__snapshots__/SideNav.test.tsx.snap
  frontend/src/index.tsx
  frontend/src/tailwind.css
  frontend/tailwind.config.js
Labels: lgtm, approved, size/XXL, cla: yes

#6251 feat(api): Add env variable in ContainerSpec
  api/v2alpha1/pipeline_spec.proto
Labels: lgtm, approved, size/S, cla: yes

#6263 test(sdk): restore a v2-compatible unit test
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/uri_artifacts.yaml
Labels: lgtm, approved, size/M, cla: yes

#6276 chore(sdk): Create RELEASE.md for future release documentations
  sdk/RELEASE.md
Labels: lgtm, approved, size/S, cla: yes

#6281 test(sdk): Ignore kfp sdk version when comparing golden
  sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
Labels: lgtm, approved, size/S, cla: yes

#6271 refactor(v2): save pipeline root to pipeline run context. Part of #6152
  v2/cmd/driver/main.go
  v2/cmd/launcher-v2/main.go
  v2/cmd/launcher/main.go
  v2/compiler/argo_test.go
  v2/compiler/container.go
  v2/component/launcher.go
  v2/component/launcher_v2.go
  v2/config/env.go
  v2/driver/driver.go
  v2/metadata/client.go
  v2/metadata/client_test.go
Labels: lgtm, approved, size/L, cla: yes

#6273 chore(frontend): Use protoc to compile IR to typescript definition. Fix #6272
  api/.gitignore
  frontend/README.md
  frontend/package.json
  frontend/scripts/pipelinespec.sh
  frontend/scripts/pipelinespec_pbjs.js
  frontend/src/generated/pipeline_spec/index.ts
  frontend/src/generated/pipeline_spec/pbjs_ml_pipelines.d.ts
  frontend/src/generated/pipeline_spec/pbjs_ml_pipelines.js
  frontend/src/generated/pipeline_spec/pipeline_spec_pb.d.ts
  frontend/src/generated/pipeline_spec/pipeline_spec_pb.js
Labels: lgtm, approved, size/XXL, cla: yes

#6268 fix(sdk): Relax the requirement that component inputs/outputs must appear on the command line.
  sdk/python/kfp/components/_python_op.py
  sdk/python/kfp/dsl/_component_bridge.py
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_pipeline.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_with_outputs.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_custom_job_spec.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_exit_handler.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_if_placeholder.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_importer.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_metrics_outputs.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/xgboost_sample_pipeline.json
Labels: lgtm, approved, size/L, cla: yes

#6286 chore(frontend): Fix gen license issues for master
  frontend/.gitignore
  frontend/README.md
  frontend/gen_licenses.js
  frontend/package-lock.json
  frontend/package.json
  frontend/third_party/once/LICENSE
  frontend/third_party/watchpack/LICENSE
Labels: lgtm, approved, size/L, ok-to-test, cla: yes

#6285 chore(v2): artifact passing via local path
  samples/test/two_step.py
  samples/test/two_step_test.py
  v2/Makefile
  v2/cmd/driver/main.go
  v2/cmd/launcher-v2/main.go
  v2/compiler/dag.go
  v2/component/launcher.go
  v2/component/launcher_v2.go
  v2/driver/driver.go
  v2/metadata/client.go
  v2/metadata/client_test.go
  v2/objectstore/object_store.go
Labels: lgtm, approved, size/XL, cla: yes

#6278 feat(frontend): Convert PipelineSpec to Staticflow for V2 pipeline. Fix #6270
  frontend/scripts/pipelinespec.sh
  frontend/src/data/test/v2_pipeline_def.ts
  frontend/src/generated/pipeline_spec/google/rpc/status_pb.d.ts
  frontend/src/generated/pipeline_spec/google/rpc/status_pb.js
  frontend/src/generated/pipeline_spec/index.ts
  frontend/src/lib/v2/StaticFlow.test.ts
  frontend/src/lib/v2/StaticFlow.ts
Labels: lgtm, approved, size/XL, cla: yes

#6297 chore(swf): fix recurring run + v2 compatible
  backend/src/crd/controller/scheduledworkflow/util/scheduled_workflow.go
  backend/src/crd/controller/scheduledworkflow/util/scheduled_workflow_test.go
Labels: lgtm, approved, size/XS, kind/bug, cla: yes

#6274 chore: stop releasing gcp components
  .cloudbuild.yaml
  .release.cloudbuild.yaml
  components/release-in-place.sh
  components/release.sh
Labels: lgtm, approved, size/XS, cla: yes

#6284 chore(frontend): Add storybook for component driven UI development and documentation. Fix #6283
  frontend/.gitignore
  frontend/.storybook/main.js
  frontend/.storybook/preview.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Css.tsx
  frontend/src/components/graph/ExecutionNode.tsx
  frontend/src/components/graph/ExecutionNodeFailed.tsx
  frontend/src/components/graph/ExecutionNodePending.tsx
  frontend/src/pages/v2/StaticCanvas.tsx
  frontend/src/stories/Button.stories.tsx
  frontend/src/stories/Button.tsx
  frontend/src/stories/Header.stories.tsx
  frontend/src/stories/Header.tsx
  frontend/src/stories/Introduction.stories.mdx
  frontend/src/stories/Page.stories.tsx
  frontend/src/stories/Page.tsx
  frontend/src/stories/assets/code-brackets.svg
  frontend/src/stories/assets/colors.svg
  frontend/src/stories/assets/comments.svg
  frontend/src/stories/assets/direction.svg
  frontend/src/stories/assets/flow.svg
  frontend/src/stories/assets/plugin.svg
  frontend/src/stories/assets/repo.svg
  frontend/src/stories/assets/stackalt.svg
  frontend/src/stories/button.css
  frontend/src/stories/header.css
  frontend/src/stories/page.css
  frontend/src/stories/v2/ExecutionNode.css
  frontend/src/stories/v2/ExecutionNode.stories.tsx
  frontend/tsconfig.json
Labels: lgtm, approved, size/XXL, cla: yes

#6316 chore: upgrade tfx to 1.0.0
  backend/Dockerfile
  backend/requirements.in
  backend/requirements.txt
  samples/core/parameterized_tfx_oss/README.md
  samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py
  samples/core/parameterized_tfx_oss/taxi_pipeline_notebook.ipynb
  sdk/python/requirements.in
  test/install-argo-cli.sh
  test/sample-test/Dockerfile
  test/sample-test/README.md
  test/sample-test/hack/update_requirements.sh
  test/sample-test/requirements.in
  test/sample-test/requirements.txt
Labels: lgtm, approved, size/XL, ok-to-test, cla: yes

#6300 chore(components/google-cloud): Add sample for Vertex AI custom job
  components/google-cloud/google_cloud_pipeline_components/experimental/custom_job/custom_job_sample.ipynb
Labels: lgtm, approved, size/L, cla: yes

#6320 fix(components/google-cloud): Fix parameter for TabularCreateDatasetOp breaks if it contains "="
  components/google-cloud/google_cloud_pipeline_components/remote/aiplatform/remote_runner.py
Labels: lgtm, approved, size/XS, cla: yes

#6325 fix(sdk): Fix compiler bug for legacy outputs mlpipeline-ui-metadata and mlpipeline-metrics. Fixes #6311
  sdk/python/kfp/dsl/_container_op.py
Labels: lgtm, approved, size/S, cla: yes

#6309 chore(deployment): gcp mkp - default pipeline root to gcs when configured
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/config-snapshot.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml
  manifests/gcp_marketplace/test/snapshot-base.yaml
  manifests/gcp_marketplace/test/snapshot-emissary.yaml
  manifests/gcp_marketplace/test/snapshot-managed-storage-with-db-prefix.yaml
  manifests/gcp_marketplace/test/snapshot-managed-storage.yaml
Labels: lgtm, approved, size/M, cla: yes

#6329 feat(backend/sdk): Rename `pipeline-output-directory` to `pipeline-root`. Fixes #6307
  backend/src/apiserver/resource/resource_manager_test.go
  samples/test/simple_pipeline_without_importer_test.py
  sdk/python/kfp/compiler/testdata/v2_compatible_two_step_pipeline.yaml
  sdk/python/kfp/compiler/testdata/v2_compatible_two_step_pipeline_with_custom_launcher.yaml
  sdk/python/kfp/dsl/__init__.py
  sdk/python/kfp/dsl/_component_bridge.py
  sdk/python/tests/compiler/testdata/uri_artifacts.yaml
Labels: lgtm, approved, size/L, cla: yes

#6334 chore(frontend): Use `gs://` instead of `gcs://` for artifact link text. Fix #6308
  frontend/src/components/ArtifactPreview.test.tsx
  frontend/src/components/ArtifactPreview.tsx
  frontend/src/components/MinioArtifactPreview.tsx
  frontend/src/components/tabs/InputOutputTab.test.tsx
  frontend/src/lib/Apis.test.ts
  frontend/src/lib/Apis.ts
Labels: lgtm, approved, size/S, cla: yes

#6326 chore: Fixes wrong Evaluator config.
  samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py
  samples/core/parameterized_tfx_oss/taxi_pipeline_notebook.ipynb
Labels: lgtm, approved, size/S, ok-to-test, cla: yes

#6333 feat: upgrade argo to v3.1.6
  .cloudbuild.yaml
  .release.cloudbuild.yaml
  backend/third_party_licenses/apiserver.csv
  backend/third_party_licenses/cache_server.csv
  backend/third_party_licenses/persistence_agent.csv
  backend/third_party_licenses/swf.csv
  backend/third_party_licenses/viewer.csv
  go-licenses.yaml
  go.mod
  go.sum
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/argo.yaml
  manifests/gcp_marketplace/test/snapshot-base.yaml
  manifests/gcp_marketplace/test/snapshot-emissary.yaml
  manifests/gcp_marketplace/test/snapshot-managed-storage-with-db-prefix.yaml
  manifests/gcp_marketplace/test/snapshot-managed-storage.yaml
  manifests/kustomize/env/platform-agnostic-multi-user-emissary/workflow-controller-configmap-patch.yaml
  manifests/kustomize/env/platform-agnostic-multi-user-pns/workflow-controller-configmap-patch.yaml
  manifests/kustomize/env/platform-agnostic-pns/workflow-controller-configmap-patch.yaml
  manifests/kustomize/third-party/argo/base/workflow-controller-configmap-patch.yaml
  manifests/kustomize/third-party/argo/base/workflow-controller-deployment-patch.yaml
  test/install-argo-cli.sh
  test/tag_for_hosted.sh
  third_party/argo/Dockerfile.argoexec
  third_party/argo/Dockerfile.workflow-controller
  third_party/argo/README.md
  third_party/argo/VERSION
  third_party/argo/go-licenses.yaml
  third_party/argo/licenses-argoexec.csv
  third_party/argo/licenses-workflow-controller.csv
Labels: lgtm, approved, size/XL, cla: yes

#6305 feat(components/google-cloud): Add vertex forecasting preprocessing and validation components.
  components/google-cloud/google_cloud_pipeline_components/experimental/forecasting/preprocess/component.yaml
  components/google-cloud/google_cloud_pipeline_components/experimental/forecasting/validate/component.yaml
Labels: lgtm, approved, size/M, ok-to-test, cla: yes

#6332 fix(sdk): pipeline name is required in v2 compatible mode. Fixes #6197
  samples/core/XGBoost/xgboost_sample.py
  sdk/python/kfp/compiler/compiler.py
Labels: lgtm, approved, size/XS, cla: yes

#6345 feat(components/google-cloud): Fix read the docs
  components/google-cloud/dependencies.py
Labels: lgtm, approved, size/XS, cla: yes

#6343 chore(sdk): Export all artifact types from io_types in `dsl` package.
  sdk/python/kfp/v2/dsl/__init__.py
Labels: lgtm, approved, size/XS, cla: yes

#6347 chore(frontend): Change from `name` to `display_name` for visualization. Fix #6346
  frontend/src/components/tabs/MetricsTab.test.tsx
  frontend/src/components/viewers/MetricsVisualizations.tsx
Labels: lgtm, approved, size/S, cla: yes

#6335 chore(sdk): Warn on container component without command. Fixes #4800
  sdk/python/kfp/components/_components.py
  sdk/python/kfp/components_tests/test_components.py
Labels: lgtm, approved, size/S, cla: yes

#6319 fix(frontend): Maximize width of HTML visualization. Partial #6296
  frontend/src/components/viewers/HTMLViewer.tsx
Labels: lgtm, approved, size/XS, cla: yes

#6340 chore(components/pytorch): Add sqlalchemy pacakge to ax
  components/PyTorch/pytorch-kfp-components/templates/ax_complete_trials_component.yaml
  components/PyTorch/pytorch-kfp-components/templates/ax_generate_trials_component.yaml
Labels: lgtm, approved, size/XS, ok-to-test, cla: yes

#6338 chore(components/pytorch): pytorch samples build fixes
  components/PyTorch/pytorch-kfp-components/setup.py
  components/PyTorch/pytorch-kfp-components/tox.ini
  samples/contrib/pytorch-samples/Dockerfile
  samples/contrib/pytorch-samples/requirements.txt
Labels: lgtm, approved, size/S, ok-to-test, cla: yes

#6330 fix(sdk): block dsl.importer usage in KFP OSS. Fixes: #6323
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/compiler/v2_compatible_compiler_test.py
  sdk/python/tests/compiler/compiler_tests.py
Labels: lgtm, approved, size/M, cla: yes

#6351 test: fix apt update "changed its 'Suite' value from 'stable' to 'oldstable'"
  proxy/Dockerfile
  test/api-integration-test/Dockerfile
  test/initialization-test/Dockerfile
  test/sample-test/Dockerfile
  test/sample-test/hack/update_requirements.sh
  test/sample-test/requirements.txt
Labels: lgtm, approved, area/testing, size/M, cla: yes

#6356 fix(Dockerfile): fixes the dockerfile by allowing `apt-get update` to ignore releaseinfo changes.
  components/aws/sagemaker/tests/integration_tests/Dockerfile
Labels: lgtm, approved, size/XS, cla: yes

#6355 chore(components/pytorch): Pytorch kfp components setup
  components/PyTorch/pytorch-kfp-components/setup.py
Labels: lgtm, approved, size/XS, ok-to-test, cla: yes

#6357 fix(components/google-cloud): Update dependancies min version
  components/google-cloud/dependencies.py
Labels: lgtm, approved, size/XS, cla: yes

#6348 fix(components/google-cloud): Undo fix for KFP compiler erroring with key not found
  components/google-cloud/google_cloud_pipeline_components/experimental/custom_job/custom_job.py
  components/google-cloud/tests/experimental/custom_job/test_custom_job.py
Labels: lgtm, approved, size/S, cla: yes

#6321 fix(components/google-cloud): Custom job container must use the same container as AIPlatform
  components/google-cloud/google_cloud_pipeline_components/experimental/custom_job/custom_job.py
  components/google-cloud/google_cloud_pipeline_components/experimental/remote/gcp_launcher/Dockerfile
  components/google-cloud/google_cloud_pipeline_components/experimental/remote/gcp_launcher/cloudbuild.yaml
  components/google-cloud/google_cloud_pipeline_components/remote/aiplatform/Dockerfile
  components/google-cloud/tests/experimental/custom_job/test_custom_job.py
Labels: lgtm, approved, size/M, cla: yes

#6344 fix(components/google-cloud): Google cloud pipeline components 0.1.4
  components/google-cloud/dependencies.py
Labels: lgtm, approved, size/XS, cla: yes

#6353 test(v2): add more samples. Part of #6150
  samples/core/output_a_directory/output_a_directory_test.py
  samples/test/after_test.py
  samples/test/config.yaml
  samples/test/lightweight_python_functions_v2_pipeline.py
  samples/test/lightweight_python_functions_v2_pipeline_test.py
  samples/test/lightweight_python_functions_v2_with_outputs.py
  samples/test/lightweight_python_functions_v2_with_outputs_test.py
  samples/test/metrics_visualization_v2_test.py
  samples/test/parameter_with_format_test.py
  samples/test/placeholder_concat_test.py
  samples/test/reused_component_test.py
  samples/test/two_step_with_uri_placeholder_test.py
  v2/component/launcher_v2.go
  v2/driver/driver.go
Labels: lgtm, approved, size/L, cla: yes

#6360 chore(components/pytorch): pytorch-kfp-components setup.py update
  components/PyTorch/pytorch-kfp-components/setup.py
Labels: lgtm, approved, size/XS, ok-to-test, cla: yes

#6359 fix(sdk): Ensure pip exists for lightweight Python-based components.
  sdk/python/kfp/compiler/testdata/v2_compatible_two_step_pipeline.yaml
  sdk/python/kfp/compiler/testdata/v2_compatible_two_step_pipeline_with_custom_launcher.yaml
  sdk/python/kfp/components/_python_op.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_pipeline.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_with_outputs.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_custom_job_spec.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_exit_handler.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_importer.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_metrics_outputs.json
Labels: lgtm, approved, size/M, cla: yes

#6352 fix(components/gcp): add explicit command for gcp components. Fixes #6252
  components/gcp/bigquery/query/to_CSV/component.yaml
  components/gcp/bigquery/query/to_table/component.yaml
  components/gcp/dataflow/launch_flex_template/component.yaml
  components/gcp/dataflow/launch_template/component.yaml
  components/gcp/dataproc/create_cluster/component.yaml
  components/gcp/dataproc/delete_cluster/component.yaml
  components/gcp/dataproc/submit_hadoop_job/component.yaml
  components/gcp/dataproc/submit_hive_job/component.yaml
  components/gcp/dataproc/submit_pig_job/component.yaml
  components/gcp/dataproc/submit_pyspark_job/component.yaml
  components/gcp/dataproc/submit_spark_job/component.yaml
  components/gcp/dataproc/submit_sparksql_job/component.yaml
  components/gcp/ml_engine/batch_predict/component.yaml
  components/google-cloud/google_cloud_pipeline_components/experimental/bigquery/query/to_gcs/component.yaml
  components/google-cloud/google_cloud_pipeline_components/experimental/bigquery/query/to_table/component.yaml
  components/google-cloud/google_cloud_pipeline_components/experimental/dataflow/launch_python/component.yaml
Labels: lgtm, approved, size/S, cla: yes

#6095 feat(sdk): Surface kubernetes configuration in container builder
  sdk/python/kfp/containers/_container_builder.py
  sdk/python/kfp/containers/_k8s_job_helper.py
Labels: lgtm, approved, size/S, ok-to-test, cla: yes

#6339 docs: Update README for emissary and KFP 1.7. Partial #6306
  README.md
Labels: lgtm, approved, size/XS, cla: yes

#6337 feat(frontend): Add KFPv2 and tutorial link in Get Started page. Partial #6306
  frontend/src/pages/GettingStarted.test.tsx
  frontend/src/pages/GettingStarted.tsx
  frontend/src/pages/__snapshots__/GettingStarted.test.tsx.snap
Labels: lgtm, approved, size/L, cla: yes

#6361 chore(v2): support output metadata file
  samples/test/lightweight_python_functions_v2_pipeline_test.py
  samples/test/lightweight_python_functions_v2_with_outputs_test.py
  samples/test/metrics_visualization_v2_test.py
  v2/Makefile
  v2/component/launcher.go
  v2/component/launcher_v2.go
Labels: lgtm, approved, size/M, cla: yes

#6349 test: Update visualization v2 to output HTML and Markdown. Partial #3970
  samples/test/metrics_visualization_v2.py
  samples/test/metrics_visualization_v2_test.py
Labels: lgtm, approved, size/M, cla: yes

#6342 feat: added namespace as cache scope
  backend/src/apiserver/server/task_server.go
  v2/cacheutils/cache.go
  v2/component/launcher.go
Labels: lgtm, approved, size/M, cla: yes

#6365 chore(components/google-cloud): Update GCPC SDK version
  components/google-cloud/RELEASE.md
  components/google-cloud/google_cloud_pipeline_components/version.py
Labels: lgtm, approved, size/XS, cla: yes

#6322 fix(components/google-cloud): Fix custom job container args order to align with BE contract
  components/google-cloud/google_cloud_pipeline_components/experimental/custom_job/custom_job.py
  components/google-cloud/tests/experimental/custom_job/test_custom_job.py
Labels: lgtm, approved, size/M, cla: yes

#5935 feat(components/google-cloud): Add user agent to the CustomJob request header
  components/google-cloud/google_cloud_pipeline_components/experimental/remote/gcp_launcher/custom_job_remote_runner.py
  components/google-cloud/tests/experimental/remote/gcp_launcher/test_custom_job_remote_runner.py
Labels: lgtm, approved, size/S, cla: yes

#6371 test(sdk): ignore kfp version in unit tests
  sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
Labels: lgtm, approved, size/S, cla: yes

#6369 chore: Release KFP SDK and v2 launcher 1.7.1
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
  sdk/python/kfp/compiler/v2_compat.py
Labels: lgtm, approved, size/M, cla: yes

#6373 chore: use a runtime parameter for pusher destination in the TFX example.
  samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py
  samples/core/parameterized_tfx_oss/taxi_pipeline_notebook.ipynb
Labels: lgtm, approved, size/M, ok-to-test, cla: yes

#6331 docs(gcp): ai platform pipelines use emissary tooltip update
  manifests/gcp_marketplace/schema.yaml
Labels: lgtm, approved, size/S, cla: yes

#6367 feat(frontend): Support v2 HTML/Markdown visualization. Fix #3970
  frontend/src/components/viewers/MetricsVisualizations.tsx
Labels: lgtm, approved, size/L, cla: yes

#6318 feat(frontend): Show V2 PipelineDetail page when pipelineSpec is v2. Fix #6303
  frontend/.eslintrc.yaml
  frontend/mock-backend/fixed-data.ts
  frontend/src/TestUtils.ts
  frontend/src/data/test/mock_lightweight_python_functions_v2_pipeline.json
  frontend/src/data/test/v2_pipeline_def.ts
  frontend/src/lib/v2/StaticFlow.test.ts
  frontend/src/lib/v2/StaticFlow.ts
  frontend/src/lib/v2/WorkflowUtils.ts
  frontend/src/pages/PipelineDetails.test.tsx
  frontend/src/pages/PipelineDetails.tsx
  frontend/src/pages/PipelineDetailsTest.test.tsx
  frontend/src/pages/PipelineDetailsV1.tsx
  frontend/src/pages/PipelineDetailsV2.test.tsx
  frontend/src/pages/PipelineDetailsV2.tsx
  frontend/src/pages/v2/StaticCanvas.tsx
Labels: lgtm, approved, size/XL, cla: yes

#6013 feat(google client): Enable to specify the service account to proxy function of scheduler in google client sdk
  sdk/python/kfp/v2/google/client/client.py
  sdk/python/kfp/v2/google/client/schedule.py
Labels: lgtm, approved, needs-ok-to-test, size/S, cla: yes

#6362 fix(manifests): replace argo ClusterRoleBinding namespace
  manifests/kustomize/third-party/argo/installs/cluster/kustomization.yaml
  manifests/kustomize/third-party/argo/installs/cluster/workflow-controller-clusterrolebinding-patch.json
Labels: lgtm, approved, needs-ok-to-test, size/S, cla: yes

#6376 feat: upgrade argo to v3.1.6-patch
  .cloudbuild.yaml
  .release.cloudbuild.yaml
  backend/Dockerfile
  manifests/kustomize/third-party/argo/base/workflow-controller-deployment-patch.yaml
  test/install-argo-cli.sh
  test/tag_for_hosted.sh
  third_party/argo/Dockerfile.argoexec
  third_party/argo/Dockerfile.workflow-controller
  third_party/argo/VERSION
Labels: lgtm, approved, size/M, cla: yes

#6363 chore(v2): support changing pipeline root
  samples/test/lightweight_python_functions_v2_with_outputs_test.py
  samples/test/two_step_with_uri_placeholder_test.py
  samples/test/util.py
  v2/cmd/compiler/main.go
  v2/compiler/argo.go
  v2/driver/driver.go
Labels: lgtm, approved, size/M, cla: yes

#6379 test: configure tfx sample push_destination arg
  test/sample-test/configs/parameterized_tfx_oss.config.yaml
Labels: size/XS, cla: yes

#6382 feat(components/google-cloud): Add methods for creating forecasting preprocessing and validation components
  components/google-cloud/google_cloud_pipeline_components/experimental/__init__.py
Labels: lgtm, approved, needs-ok-to-test, size/M, cla: yes

#6370 chore(components/google-cloud): Simplify auto generated API docs
  components/google-cloud/docs/source/google_cloud_pipeline_components.aiplatform.rst
  components/google-cloud/docs/source/google_cloud_pipeline_components.experimental.custom_job.rst
  components/google-cloud/docs/source/google_cloud_pipeline_components.experimental.remote.gcp_launcher.rst
  components/google-cloud/docs/source/google_cloud_pipeline_components.experimental.remote.rst
  components/google-cloud/docs/source/google_cloud_pipeline_components.experimental.rst
  components/google-cloud/docs/source/google_cloud_pipeline_components.experimental.tensorflow_probability.anomaly_detection.rst
  components/google-cloud/docs/source/google_cloud_pipeline_components.experimental.tensorflow_probability.rst
  components/google-cloud/docs/source/google_cloud_pipeline_components.rst
  components/google-cloud/docs/source/index.rst
  components/google-cloud/docs/source/modules.rst
Labels: lgtm, approved, size/L, cla: yes

#6368 feat(components/google-cloud): Include release notes in pypi
  components/google-cloud/README.md
  components/google-cloud/setup.py
Labels: lgtm, approved, size/L, cla: yes

#6381 feat(sample): Use TFX 1.2.0 for Taxi tips prediction sample. Partial #6138
  samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py
  samples/core/parameterized_tfx_oss/taxi_pipeline_notebook.ipynb
Labels: approved, size/M, cla: yes

#6261 feat(backend): Add pipeline version description to backend. Part of #6256
  backend/api/go_client/pipeline.pb.go
  backend/api/go_http_client/pipeline_model/api_pipeline_version.go
  backend/api/pipeline.proto
  backend/api/python_http_client/docs/ApiPipelineVersion.md
  backend/api/python_http_client/kfp_server_api/models/api_pipeline_version.py
  backend/api/python_http_client/test/test_api_list_pipeline_versions_response.py
  backend/api/python_http_client/test/test_api_list_pipelines_response.py
  backend/api/python_http_client/test/test_api_pipeline.py
  backend/api/python_http_client/test/test_api_pipeline_version.py
  backend/api/swagger/kfp_api_single_file.swagger.json
  backend/api/swagger/pipeline.swagger.json
  backend/src/apiserver/model/pipeline_version.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/server/api_converter.go
  backend/src/apiserver/server/api_converter_test.go
  backend/src/apiserver/storage/pipeline_store.go
  backend/src/apiserver/storage/pipeline_store_test.go
  frontend/README.md
  frontend/server/src/generated/apis/auth/api.ts
  frontend/src/apis/experiment/api.ts
  frontend/src/apis/job/api.ts
  frontend/src/apis/pipeline/api.ts
  frontend/src/apis/run/api.ts
  frontend/src/apis/visualization/api.ts
Labels: lgtm, approved, size/L, ok-to-test, cla: yes

#6386 chore: fix broken links
  backend/api/experiment.proto
  backend/api/job.proto
  backend/api/pipeline.proto
  backend/api/run.proto
  backend/api/task.proto
Labels: lgtm, approved, needs-ok-to-test, size/S, cla: yes

#6388 feat(frontend): integrate with TFX 1.2.0 metadata & visualization, no longer support previous versions. Part of #6138
  frontend/src/mlmd/MlmdUtils.test.ts
  frontend/src/mlmd/MlmdUtils.ts
Labels: lgtm, approved, size/S, cla: yes

#6391 fix(backend): recognize "sidecar.istio.io/inject" annotation to use Istio service mesh optionally. Fixes #6200
  backend/src/apiserver/resource/resource_manager.go
  backend/src/common/util/workflow.go
Labels: lgtm, approved, size/S, ok-to-test, cla: yes

#6396 fix(components/google-cloud): Fix FileNotFoundError when loading component yaml from file.
  components/google-cloud/google_cloud_pipeline_components/experimental/__init__.py
Labels: lgtm, approved, size/S, ok-to-test, cla: yes

#6403 chore(components/google-cloud): Update args and location of ForecastingPreprocessingOp and ForecastingValidationOp
  components/google-cloud/google_cloud_pipeline_components/experimental/__init__.py
  components/google-cloud/google_cloud_pipeline_components/experimental/forecasting/__init__.py
Labels: lgtm, approved, size/L, ok-to-test, cla: yes

#6401 chore: sync pipeline_spec to current version.
  api/v2alpha1/go/pipelinespec/pipeline_spec.pb.go
Labels: lgtm, approved, size/XXL, cla: yes

#6406 chore(sdk): clean up the unused arg in AIPlatformClient docstring.
  sdk/python/kfp/v2/google/client/client.py
Labels: lgtm, approved, size/XS, cla: yes

#6408 chore(frontend): Change edge type from animated to arrowclosed. Partial #6397
  frontend/src/lib/v2/StaticFlow.ts
Labels: lgtm, approved, size/S, cla: yes

#6407 feat(frontend): v2 Execution Node element. Partial #6280
  frontend/.storybook/preview.js
  frontend/README.md
  frontend/package.json
  frontend/src/Css.tsx
  frontend/src/TestUtils.ts
  frontend/src/components/graph/ExecutionNode.tsx
  frontend/src/lib/v2/StaticFlow.ts
  frontend/src/pages/v2/StaticCanvas.tsx
  frontend/src/stories/v2/ExecutionNode.stories.tsx
  frontend/tailwind.config.js
  frontend/tsconfig.json
Labels: lgtm, approved, size/L, cla: yes

#6395 feat(sdk): Add description to upload_pipeline_version in kfp. Part of #6256
  sdk/RELEASE.md
  sdk/python/kfp/_client.py
Labels: lgtm, approved, size/XS, needs-ok-to-test, cla: yes

#6413 feat(components/google-cloud): add project_id to the inputs of preprocessing component
  components/google-cloud/google_cloud_pipeline_components/experimental/forecasting/__init__.py
  components/google-cloud/google_cloud_pipeline_components/experimental/forecasting/preprocess/component.yaml
Labels: lgtm, approved, size/XS, ok-to-test, cla: yes

#6414 chore(components/pytorch): Update ax-hpo pytorch samples notebook
  samples/contrib/pytorch-samples/Pipeline-Cifar10-hpo.ipynb
  samples/contrib/pytorch-samples/screenshots/ax-best-parameters.png
  samples/contrib/pytorch-samples/screenshots/ax-complete-trials.png
  samples/contrib/pytorch-samples/screenshots/ax-hpo-pipeline.png
Labels: lgtm, approved, size/L, ok-to-test, cla: yes

#6366 feat(sdk): add default schema_version to pipeline
  sdk/python/kfp/compiler/testdata/v2_compatible_two_step_pipeline.yaml
  sdk/python/kfp/compiler/testdata/v2_compatible_two_step_pipeline_with_custom_launcher.yaml
  sdk/python/kfp/compiler/v2_compat.py
  sdk/python/kfp/dsl/component_spec_test.py
  sdk/python/kfp/dsl/type_utils.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/experimental_v2_component.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_pipeline.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_with_outputs.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_after.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_concat_placeholder.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_condition.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_importer.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loop_output.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loop_parameter.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loop_static.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loops_and_conditions.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_metrics_outputs.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_nested_conditions.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_nested_conditions_yaml.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_nested_loops.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_ontology.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_params_containing_format.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_resource_spec.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_reused_component.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_various_io_types.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/two_step_pipeline.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/xgboost_sample_pipeline.json
  sdk/python/kfp/v2/components/types/artifact_types.py
  sdk/python/kfp/v2/components/types/type_utils.py
  sdk/python/kfp/v2/components/types/type_utils_test.py
  sdk/python/requirements.in
  sdk/python/requirements.txt
  sdk/python/setup.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/testdata/uri_artifacts.yaml
Labels: lgtm, approved, size/L, cla: yes

#6405 feat(frontend): Add version description to pipelineVersionList. Part of #6256
  frontend/mock-backend/fixed-data.ts
  frontend/mock-backend/mock-api-middleware.ts
  frontend/src/pages/PipelineVersionList.test.tsx
  frontend/src/pages/PipelineVersionList.tsx
  frontend/src/pages/__snapshots__/PipelineVersionList.test.tsx.snap
Labels: lgtm, approved, size/XXL, ok-to-test, cla: yes

#6423 chore(components/pytorch): PyTorch samples README.md update
  samples/contrib/pytorch-samples/cluster_build.md
  samples/contrib/pytorch-samples/local_build.md
  samples/contrib/pytorch-samples/prerequisites.md
  samples/contrib/pytorch-samples/screenshots/tensorboard.png
Labels: lgtm, approved, size/S, ok-to-test, cla: yes

#6427 chore: GCP mkp does not default to root when the field is empty
  manifests/gcp_marketplace/schema.yaml
Labels: lgtm, approved, size/XS, cla: yes

#6422 feat(components): move dataflow/bq component to google-cloud
  components/gcp/bigquery/README.md
  components/gcp/dataflow/README.md
  components/google-cloud/google_cloud_pipeline_components/experimental/bigquery/query/to_CSV/README.md
  components/google-cloud/google_cloud_pipeline_components/experimental/bigquery/query/to_CSV/component.yaml
  components/google-cloud/google_cloud_pipeline_components/experimental/dataflow/launch_flex_template/component.yaml
  components/google-cloud/google_cloud_pipeline_components/experimental/dataflow/launch_template/component.yaml
Labels: lgtm, approved, size/L, cla: yes

#6461 feat(components/google-cloud): add preprocessing_bigquery_dataset to the inputs of preprocessing component
  components/google-cloud/google_cloud_pipeline_components/experimental/forecasting/__init__.py
  components/google-cloud/google_cloud_pipeline_components/experimental/forecasting/preprocess/component.yaml
Labels: lgtm, approved, needs-ok-to-test, size/S, cla: yes

#6454 chore(third_party): Add a script to update MLMD.
  third_party/ml-metadata/README.md
  third_party/ml-metadata/VERSION
  third_party/ml-metadata/update_version.sh
Labels: lgtm, approved, size/M, cla: yes

#6463 fix(components/google-cloud): Fix the keyword argument 'project_id' to 'project' after the yaml upd…
  components/google-cloud/google_cloud_pipeline_components/experimental/forecasting/__init__.py
Labels: lgtm, approved, size/XS, needs-ok-to-test, cla: yes

#6437 feat: upgrade MLMD to 1.2.0. Fix #6436
  .cloudbuild.yaml
  .release.cloudbuild.yaml
  backend/metadata_writer/requirements.in
  backend/metadata_writer/requirements.txt
  backend/requirements.in
  backend/requirements.txt
  backend/src/apiserver/visualization/requirements.txt
  frontend/scripts/replace_protos.js
  frontend/src/third_party/mlmd/generated/ml_metadata/proto/metadata_store_pb.d.ts
  frontend/src/third_party/mlmd/generated/ml_metadata/proto/metadata_store_pb.js
  manifests/kustomize/base/metadata/base/metadata-grpc-deployment.yaml
  test/sample-test/requirements.txt
  test/tag_for_hosted.sh
  third_party/ml-metadata/ml_metadata/proto/metadata_store.proto
  v2/Makefile
Labels: lgtm, approved, size/L, cla: yes

#6402 feat(api): Updates pipeline_spec.proto to use google.protobuf.Value
  api/v2alpha1/pipeline_spec.proto
Labels: lgtm, approved, size/M, cla: yes

#6468 revert: "feat(sdk): Add description to upload_pipeline_version in kfp. Part of #6256"
  sdk/python/kfp/_client.py
Labels: lgtm, approved, size/XS, cla: yes

#6404 feat(sdk): detail option to kfp run get. Fixes #6315
  sdk/python/kfp/cli/run.py
Labels: lgtm, approved, size/S, ok-to-test, cla: yes

#6473 fix: Rename 'python_module' to 'python_module_name' and fix type to str
  components/google-cloud/google_cloud_pipeline_components/aiplatform/utils.py
Labels: lgtm, approved, size/XS, cla: yes

#6462 chore(sdk): Add Alpha feature notice for local client
  sdk/python/kfp/_local_client.py
  sdk/python/kfp/_runners.py
Labels: lgtm, approved, size/S, cla: yes

#6471 feat(sdk.v2): Support `set_display_name` in v2.
  api/v2alpha1/pipeline_spec.proto
  sdk/python/kfp/dsl/_component_bridge.py
  sdk/python/kfp/v2/compiler/compiler.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/two_step_pipeline.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/two_step_pipeline.py
  sdk/python/kfp/v2/components/importer_node.py
  sdk/python/kfp/v2/components/importer_node_test.py
Labels: lgtm, approved, size/M, cla: yes

#6464 feat(components/google-cloud): Support Proto Plus serialization
  components/google-cloud/google_cloud_pipeline_components/aiplatform/utils.py
Labels: lgtm, approved, size/M, cla: yes

#6415 feat(v2): added importer support
  samples/test/cache_v2_test.py
  samples/test/config.yaml
  samples/test/two_step_test.py
  samples/test/two_step_with_uri_placeholder_test.py
  samples/v2/pipeline_with_importer.py
  samples/v2/pipeline_with_importer_test.py
  v2/Makefile
  v2/cmd/launcher-v2/main.go
  v2/compiler/argo.go
  v2/compiler/argo_test.go
  v2/compiler/container.go
  v2/compiler/executor.go
  v2/compiler/importer.go
  v2/compiler/testdata/importer.json
  v2/compiler/visitor.go
  v2/component/importer_launcher.go
  v2/component/launcher.go
  v2/component/launcher_v2.go
  v2/driver/driver.go
  v2/metadata/client.go
  v2/metadata/client_test.go
  v2/metadata/converter.go
  v2/objectstore/object_store.go
Labels: lgtm, approved, size/XXL, cla: yes

#6420 feat(frontend): SubDag Node and mock samples. Partial #6419. Fix #6302. Fix #6398
  frontend/mock-backend/data/v2/pipeline/pipeline_with_loops_and_conditions.json
  frontend/mock-backend/data/v2/pipeline/xgboost_sample_pipeline.json
  frontend/mock-backend/fixed-data.ts
  frontend/src/components/graph/Constants.ts
  frontend/src/components/graph/ExecutionNode.tsx
  frontend/src/components/graph/SubDagLayer.tsx
  frontend/src/components/graph/SubDagNode.tsx
  frontend/src/lib/v2/StaticFlow.ts
  frontend/src/pages/PipelineDetails.tsx
  frontend/src/pages/PipelineDetailsV2.tsx
  frontend/src/pages/v2/StaticCanvas.tsx
  frontend/src/stories/v2/SubDagNode.stories.tsx
Labels: lgtm, approved, size/XXL, cla: yes

#6441 chore(v2): support v2 makefile in mac
  v2/Makefile
  v2/README.md
Labels: lgtm, approved, size/S, cla: yes

#6418 feat(frontend): Add styling for Artifact Node. Partial #6280
  frontend/src/components/graph/ArtifactNode.tsx
  frontend/src/components/graph/ExecutionNode.tsx
  frontend/src/lib/v2/StaticFlow.ts
  frontend/src/stories/v2/ArtifactNode.stories.tsx
  frontend/tailwind.config.js
Labels: lgtm, approved, size/L, cla: yes

#6481 fix(components/google-cloud): Fix the default value of preprocessing_bigquery_dataset
  components/google-cloud/google_cloud_pipeline_components/experimental/forecasting/__init__.py
Labels: lgtm, approved, size/XS, needs-ok-to-test, cla: yes

#6456 chore(sdk): Import mock from stdlib and drop dependency.
  sdk/python/kfp/components_tests/test_components.py
  sdk/python/kfp/containers_tests/component_builder_test.py
  sdk/python/kfp/containers_tests/test_build_image_api.py
  sdk/python/kfp/v2/google/client/schedule_test.py
  sdk/python/requirements-test.txt
  sdk/python/setup.py
  sdk/python/tests/compiler/compiler_tests.py
  sdk/python/tests/compiler/component_builder_test.py
  sdk/python/tests/compiler/container_builder_test.py
Labels: lgtm, approved, size/S, ok-to-test, cla: yes

#6483 chore(components/google-cloud): Add model forecast documentation to Sphinx docs
  components/google-cloud/docs/source/google_cloud_pipeline_components.experimental.forecasting.rst
  components/google-cloud/docs/source/google_cloud_pipeline_components.experimental.rst
Labels: lgtm, approved, size/XS, cla: yes

#6482 chore(components/google-cloud): Update google-cloud-aiplatform min version to 1.4.0
  components/google-cloud/dependencies.py
Labels: lgtm, approved, size/XS, cla: yes
