Repository kubeflow/pipelines, pull requests merged in 2021-06, with the labels that each got.

#5761 fix(sdk, v2): Fix error when replica_count isn't set
  sdk/python/kfp/v2/google/experimental/custom_job.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#5766 chore: set up AUTHORS file. Fixes #5470
  AUTHORS
Labels: approved, cla: yes, lgtm, size/XS

#5731 feat(frontend): MetricsTab for NodeDetail, ROC Curve from MLMD custom property. Issue #5668
  frontend/package-lock.json
  frontend/package.json
  frontend/src/TestUtils.ts
  frontend/src/TestWrapper.tsx
  frontend/src/atoms/ErrorBoundary.tsx
  frontend/src/components/tabs/MetricsTab.test.tsx
  frontend/src/components/tabs/MetricsTab.tsx
  frontend/src/components/viewers/ROCCurve.tsx
  frontend/src/index.tsx
  frontend/src/lib/MlmdUtils.ts
  frontend/src/lib/OutputArtifactLoader.ts
  frontend/src/lib/v2/WorkflowUtils.test.ts
  frontend/src/lib/v2/WorkflowUtils.ts
  frontend/src/pages/RunDetails.tsx
Labels: approved, cla: yes, lgtm, size/XXL

#5697 feat(v2): enable v2 compatible mode in full Kubeflow with zero config. Fixes #5680
  v2/cmd/launch/main.go
  v2/component/launcher.go
  v2/objectstore/object_store.go
  v2/objectstore/object_store_test.go
Labels: approved, cla: yes, lgtm, size/L

#5776 test(samples): fix ai_platform.ipynb. Fixes #5775
  samples/core/ai_platform/ai_platform.ipynb
Labels: approved, cla: yes, lgtm, size/XS

#5777 fix(deployment): GCP AI Platform Pipelines -- correct default values when some fields left empty. Fixes #5717
  manifests/gcp_marketplace/chart/kubeflow-pipelines/values.yaml
  manifests/gcp_marketplace/schema.yaml
Labels: approved, cla: yes, lgtm, size/S

#5750 feat(deployment): configurable v2 compatible mode default pipeline root. Part of #5680. Fixes #5704
  manifests/kustomize/base/installs/generic/kustomization.yaml
  manifests/kustomize/base/installs/generic/params.yaml
  manifests/kustomize/base/installs/generic/pipeline-install-config.yaml
  manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/deployment.yaml
  manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/sync.py
  manifests/kustomize/base/pipeline/kfp-launcher-configmap.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/hack/test.sh
Labels: approved, cla: yes, lgtm, size/M

#5778 release(api): Bump kfp-pipeline-spec version to 0.1.8
  api/v2alpha1/python/setup.py
Labels: approved, cla: yes, lgtm, size/XS

#5770 fix(sdk.v2): fix metrics outputs populating to unblock pipeline run
  sdk/python/kfp/v2/compiler/compiler.py
  sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_metrics_outputs.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_metrics_outputs.py
Labels: approved, cla: yes, lgtm, size/L

#5772 fix(sdk): resolve pipeline_root and run_uid placeholders in container env
  sdk/python/kfp/compiler/_data_passing_rewriter.py
Labels: approved, cla: yes, lgtm, size/S

#5782 fix(sdk): Add http status code check for token requests. Fixes #4312
  sdk/python/kfp/_auth.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#5786 feat: update MLMD to 1.0.0
  .cloudbuild.yaml
  .release.cloudbuild.yaml
  backend/metadata_writer/requirements.in
  backend/metadata_writer/requirements.txt
  frontend/package-lock.json
  frontend/package.json
  manifests/kustomize/base/metadata/base/metadata-grpc-deployment.yaml
  test/tag_for_hosted.sh
  v2/Makefile
  v2/test/requirements.txt
Labels: approved, cla: yes, lgtm, size/M

#5781 feat(frontend): Support v2 confusion matrix visualization. Issue #5668
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/tabs/MetricsTab.test.tsx
  frontend/src/components/tabs/MetricsTab.tsx
  frontend/src/components/viewers/ConfusionMatrix.tsx
  frontend/src/components/viewers/MetricsVisualizations.tsx
Labels: approved, cla: yes, lgtm, size/XL

#5784 feat(sdk.v2): Support Exit handler in v2 compiler.
  sdk/python/kfp/v2/compiler/compiler.py
  sdk/python/kfp/v2/compiler/compiler_test.py
  sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_exit_handler.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_exit_handler.py
  sdk/python/requirements.in
  sdk/python/requirements.txt
  sdk/python/setup.py
Labels: approved, cla: yes, lgtm, size/L

#5796 release: KFP SDK and v2 launcher 1.6.3
  sdk/python/kfp/__init__.py
  sdk/python/kfp/compiler/v2_compat.py
Labels: approved, cla: yes, lgtm, size/XS

#5787 Update pipeline_spec.proto
  api/v2alpha1/pipeline_spec.proto
Labels: approved, cla: yes, lgtm, size/XS

#5799 chore: update python version for build.sh
  sdk/python/build.sh
Labels: approved, cla: yes, lgtm, size/XS

#5715 chore: add link and Python 3.8/3.9 classifiers to setup.py
  sdk/python/setup.py
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#5800 fix(scheduledworkflow): Set location to make CRON timezone work, Fixes #2653
  backend/Dockerfile.scheduledworkflow
  backend/src/crd/controller/scheduledworkflow/main.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#5780 feat(components): Adding Mar component for PyTorch - KFP
  components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/components/__init__.py
  components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/components/mar/__init__.py
  components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/components/mar/component.py
  components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/components/mar/executor.py
  components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/types/__init__.py
  components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/types/standard_component_specs.py
  components/PyTorch/pytorch-kfp-components/tests/test_mar_generation.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#5630 feat(components): PyTorch - Added the Create PyTorch Model Archive component
  components/PyTorch/Create_PyTorch_Model_Archive/component.yaml
  components/PyTorch/_samples/Train_fully-connected_network.pipeline.py
Labels: approved, area/components, cla: yes, lgtm, size/M

#5767 feat(components): Adding Trainer component for PyTorch - KFP
  components/PyTorch/pytorch-kfp-components/.gitignore
  components/PyTorch/pytorch-kfp-components/.pylintrc
  components/PyTorch/pytorch-kfp-components/LICENSE
  components/PyTorch/pytorch-kfp-components/README.md
  components/PyTorch/pytorch-kfp-components/pyproject.toml
  components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/.pylintrc
  components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/__init__.py
  components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/components/base/__init__.py
  components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/components/base/base_component.py
  components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/components/base/base_executor.py
  components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/components/trainer/__init__.py
  components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/components/trainer/component.py
  components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/components/trainer/executor.py
  components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/components/trainer/generic_executor.py
  components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/types/standard_component_specs.py
  components/PyTorch/pytorch-kfp-components/setup.cfg
  components/PyTorch/pytorch-kfp-components/setup.py
  components/PyTorch/pytorch-kfp-components/tests/iris/__init__.py
  components/PyTorch/pytorch-kfp-components/tests/iris/iris_classification.py
  components/PyTorch/pytorch-kfp-components/tests/iris/iris_data_module.py
  components/PyTorch/pytorch-kfp-components/tests/iris/iris_handler.py
  components/PyTorch/pytorch-kfp-components/tests/iris/iris_pytorch.py
  components/PyTorch/pytorch-kfp-components/tests/presubmit.sh
  components/PyTorch/pytorch-kfp-components/tests/run_tests.sh
  components/PyTorch/pytorch-kfp-components/tests/test_trainer.py
  components/PyTorch/pytorch-kfp-components/tox.ini
  samples/contrib/pytorch-samples/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#5808 feat(components): Adding Minio component for PyTorch - KFP
  components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/components/minio/__init__.py
  components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/components/minio/component.py
  components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/components/minio/executor.py
  components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/types/standard_component_specs.py
  components/PyTorch/pytorch-kfp-components/tests/test_minio.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#5810 feat(components): Adding Visualization component for PyTorch - KFP
  components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/components/visualization/__init__.py
  components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/components/visualization/component.py
  components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/components/visualization/executor.py
  components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/types/standard_component_specs.py
  components/PyTorch/pytorch-kfp-components/tests/test_visualization.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#5793 chore(launcher): move artifact metadata to metadata struct field. Fixes #5788
  samples/test/metrics_visualization_v2_test.py
  samples/test/two_step_test.py
  samples/test/util.py
  v2/component/runtime_info.go
Labels: approved, cla: yes, lgtm, size/L

#5802 test(v2): presubmit unit tests of v2
  v2/test/presubmit-v2-go-test.sh
Labels: approved, cla: yes, lgtm, size/M

#4495 refactor(components): De-hardcoded local output paths.
  components/deprecated/dataflow/predict/component.yaml
  components/deprecated/dataflow/tfma/component.yaml
  components/deprecated/dataflow/tft/component.yaml
  components/kubeflow/dnntrainer/component.yaml
  components/kubeflow/dnntrainer/src/trainer/task.py
  components/local/confusion_matrix/component.yaml
  components/local/confusion_matrix/src/confusion_matrix.py
  components/local/roc/component.yaml
  components/local/roc/src/roc.py
Labels: approved, area/components, cla: yes, lgtm, size/M

#5813 Update pipeline_spec.proto
  api/v2alpha1/pipeline_spec.proto
Labels: approved, cla: yes, lgtm, size/XS

#5811 feat(frontend): Support Scalar metrics in V2 compatible mode. Partial #5668
  frontend/src/components/tabs/MetricsTab.test.tsx
  frontend/src/components/viewers/MetricsVisualizations.tsx
Labels: approved, cla: yes, lgtm, size/L

#5823 chore: Update version for PyTorch KFP components 0.1.0.rc-1 release
  components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/__init__.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#5812 feat(components): Adding samples for PyTorch - KFP
  samples/contrib/pytorch-samples/Dockerfile-cpu
  samples/contrib/pytorch-samples/Dockerfile-gpu
  samples/contrib/pytorch-samples/Pipeline-Bert.ipynb
  samples/contrib/pytorch-samples/Pipeline-Cifar10.ipynb
  samples/contrib/pytorch-samples/README.md
  samples/contrib/pytorch-samples/bert/agnews_classification_pytorch.py
  samples/contrib/pytorch-samples/bert/bert-base-uncased-vocab.txt
  samples/contrib/pytorch-samples/bert/bert_datamodule.py
  samples/contrib/pytorch-samples/bert/bert_handler.py
  samples/contrib/pytorch-samples/bert/bert_pre_process.py
  samples/contrib/pytorch-samples/bert/bert_train.py
  samples/contrib/pytorch-samples/bert/index_to_name.json
  samples/contrib/pytorch-samples/bert/news_dataset.py
  samples/contrib/pytorch-samples/bert/pipeline.py
  samples/contrib/pytorch-samples/bert/sample.txt
  samples/contrib/pytorch-samples/bert/wrapper.py
  samples/contrib/pytorch-samples/bert/yaml/pre_process/component.yaml
  samples/contrib/pytorch-samples/bert/yaml/train/component.yaml
  samples/contrib/pytorch-samples/build.sh
  samples/contrib/pytorch-samples/cifar10/CIFAR10_Captum_Insights.png
  samples/contrib/pytorch-samples/cifar10/cifar10_datamodule.py
  samples/contrib/pytorch-samples/cifar10/cifar10_pre_process.py
  samples/contrib/pytorch-samples/cifar10/cifar10_pytorch.py
  samples/contrib/pytorch-samples/cifar10/cifar10_train.py
  samples/contrib/pytorch-samples/cifar10/class_mapping.json
  samples/contrib/pytorch-samples/cifar10/horse.png
  samples/contrib/pytorch-samples/cifar10/input.json
  samples/contrib/pytorch-samples/cifar10/kitten.png
  samples/contrib/pytorch-samples/cifar10/pipeline.py
  samples/contrib/pytorch-samples/cifar10/utils.py
  samples/contrib/pytorch-samples/cifar10/yaml/pre_process/component.yaml
  samples/contrib/pytorch-samples/cifar10/yaml/train/component.yaml
  samples/contrib/pytorch-samples/common/deploy/component.yaml
  samples/contrib/pytorch-samples/common/minio/component.yaml
  samples/contrib/pytorch-samples/common/minio/upload_to_minio.py
  samples/contrib/pytorch-samples/common/prediction/component.yaml
  samples/contrib/pytorch-samples/common/tensorboard/component.yaml
  samples/contrib/pytorch-samples/gen_image_timestamp.py
  samples/contrib/pytorch-samples/image.png
  samples/contrib/pytorch-samples/requirements.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#5822 chore: update deprecated download_as_string to download_as_bytes
  components/gcp/container/component_sdk/python/kfp_component/google/dataflow/_common_ops.py
  components/gcp/container/component_sdk/python/tests/google/dataflow/test__launch_python.py
  components/gcp/container/component_sdk/python/tests/google/dataflow/test__launch_template.py
  components/google-cloud/Optimizer/Add_measurement_for_trial/component.py
  components/google-cloud/Optimizer/Add_measurement_for_trial/component.yaml
  components/google-cloud/Optimizer/Create_study/component.py
  components/google-cloud/Optimizer/Create_study/component.yaml
  components/google-cloud/Optimizer/Suggest_parameter_sets_based_on_measurements/component.py
  components/google-cloud/Optimizer/Suggest_parameter_sets_based_on_measurements/component.yaml
  components/google-cloud/Optimizer/Suggest_trials/component.py
  components/google-cloud/Optimizer/Suggest_trials/component.yaml
  sdk/python/kfp/v2/google/client/client_utils.py
  sdk/python/kfp/v2/google/client/client_utils_test.py
Labels: approved, cla: yes, lgtm, size/M

#5827 chore: Add OWNERS for PyTorch KFP Components
  components/PyTorch/pytorch-kfp-components/OWNERS
  samples/contrib/pytorch-samples/OWNERS
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#5826 feat(samples): volume ops example to not use container op. Part of #5687
  samples/core/volume_ops/volume_ops.py
Labels: approved, cla: yes, lgtm, size/S

#5833 chore: PyTorch Samples - README.md update and notebook cleanup
  components/PyTorch/pytorch-kfp-components/README.md
  samples/contrib/pytorch-samples/Pipeline-Bert.ipynb
  samples/contrib/pytorch-samples/Pipeline-Cifar10-Captum-Insights.ipynb
  samples/contrib/pytorch-samples/Pipeline-Cifar10.ipynb
  samples/contrib/pytorch-samples/README.md
  samples/contrib/pytorch-samples/install-dependencies.sh
  samples/contrib/pytorch-samples/prerequisites.md
  samples/contrib/pytorch-samples/viz1.png
Labels: approved, cla: yes, lgtm, size/XXL

#5554 chore(components/google-cloud): Add ModelExport component
  components/google-cloud/dependencies.py
  components/google-cloud/google_cloud_pipeline_components/aiplatform/__init__.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#5824 refactor(frontend) Set 1 Hour as a default value for recurring pipeline runs
  frontend/src/components/Trigger.test.tsx
  frontend/src/components/Trigger.tsx
  frontend/src/components/__snapshots__/Trigger.test.tsx.snap
  frontend/src/pages/NewRun.test.tsx
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#5821 feat(components/google-cloud): Add components for AutoMLForecasting
  components/google-cloud/google_cloud_pipeline_components/aiplatform/__init__.py
Labels: approved, cla: yes, lgtm, size/M

#5447 feat(sdk): add runtime resource requests. Fixes #1956
  samples/core/resource_spec/runtime_resource_request.py
  samples/core/resource_spec/runtime_resource_request_test.py
  samples/test/config.yaml
  sdk/python/kfp/compiler/_op_to_template.py
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/tests/compiler/compiler_tests.py
Labels: approved, cla: yes, lgtm, size/L

#5828 feat(samples): update set parallelism limit example to not use container op. Part of #5687
  samples/core/pipeline_parallelism/pipeline_parallelism_limits.py
Labels: approved, cla: yes, lgtm, size/S

#5832 fix(sdk/compiler): v2 compat - fix mlpipeline-ui-metadata artifact. Part of #5666
  components/tensorflow/tensorboard/prepare_tensorboard/component.yaml
  samples/core/visualization/tensorboard_gcs.py
  samples/core/visualization/tensorboard_minio.py
  samples/core/visualization/tensorboard_minio_test.py
  sdk/python/kfp/dsl/_container_op.py
Labels: approved, cla: yes, lgtm, size/L

#5836 fix(launcher): duplicate input artifacts logged
  samples/test/lightweight_python_functions_v2_pipeline.py
  samples/test/lightweight_python_functions_v2_pipeline_test.py
  samples/test/util.py
  v2/metadata/client.go
  v2/test/presubmit-v2-go-test.sh
Labels: cla: yes, size/L

#5751 feat(sdk): set shell=False to run LocalClient both docker and local mode
  sdk/python/kfp/_local_client.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#5501 feat(sdk): Support launching Dataflow Flex templates from Kubeflow pipelines
  components/gcp/container/component_sdk/python/kfp_component/google/dataflow/__init__.py
  components/gcp/container/component_sdk/python/kfp_component/google/dataflow/_client.py
  components/gcp/container/component_sdk/python/kfp_component/google/dataflow/_launch_flex_template.py
  components/gcp/container/component_sdk/python/tests/google/dataflow/test__launch_flex_template.py
  components/gcp/dataflow/launch_flex_template/README.md
  components/gcp/dataflow/launch_flex_template/component.yaml
  components/gcp/dataflow/launch_flex_template/sample.ipynb
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#5845 test(v2): fixed presubmit v2 go test
  v2/component/runtime_info_test.go
  v2/test/presubmit-v2-go-test.sh
Labels: approved, cla: yes, lgtm, size/M

#5847 fix(frontend): Update instruction link in upload pipeline page.
  frontend/src/components/UploadPipelineDialog.tsx
  frontend/src/pages/NewPipelineVersion.tsx
Labels: approved, cla: yes, lgtm, size/S

#5842 chore(launcher): revert meadata to custom properties & artifact name -> event path
  samples/core/visualization/tensorboard_minio_test.py
  samples/test/lightweight_python_functions_v2_pipeline_test.py
  samples/test/metrics_visualization_v2_test.py
  samples/test/reused_component_test.py
  samples/test/two_step_test.py
  samples/test/util.py
  v2/component/launcher.go
  v2/component/runtime_info.go
  v2/component/runtime_info_test.go
  v2/metadata/client.go
Labels: approved, cla: yes, lgtm, size/L

#3965 feat(backend): workflow validation. Fixes #3526.
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/resource/test_util.go
  backend/src/apiserver/server/report_server_test.go
  backend/src/apiserver/server/run_server_test.go
  backend/src/apiserver/server/test_util.go
  backend/src/common/util/template_util.go
  backend/src/common/util/template_util_test.go
  go.sum
Labels: approved, area/backend, cla: yes, lgtm, size/L

#5732 feat(manifests): Expose sync.py frontend/visualization image as env var, add tests
  manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/requirements-dev.txt
  manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/run_tests.sh
  manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/sync.py
  manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/test_sync.py
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XL

#5860 fix(components/pytorch) Pytorch - Tensorboard Profiler fix
  components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/components/trainer/executor.py
  samples/contrib/pytorch-samples/Dockerfile-cpu
  samples/contrib/pytorch-samples/bert/agnews_classification_pytorch.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#5873 chore: update document for LAUNCHER_IMAGE_DEV
  v2/README.md
Labels: approved, cla: yes, lgtm, size/XS

#5849 chore(v2): generate cache key and hash key
  v2/cacheutils/cache.go
  v2/cacheutils/cache_test.go
  v2/cmd/launch/main.go
  v2/component/launcher.go
Labels: approved, cla: yes, lgtm, size/L

#5850 feat(components/pytorch): Add requirement for mar generation
  samples/contrib/pytorch-samples/Dockerfile-cpu
  samples/contrib/pytorch-samples/Dockerfile-gpu
  samples/contrib/pytorch-samples/Pipeline-Bert.ipynb
  samples/contrib/pytorch-samples/Pipeline-Cifar10-Captum-Insights.ipynb
  samples/contrib/pytorch-samples/Pipeline-Cifar10.ipynb
  samples/contrib/pytorch-samples/README.md
  samples/contrib/pytorch-samples/bert/agnews_classification_pytorch.py
  samples/contrib/pytorch-samples/bert/config.properties
  samples/contrib/pytorch-samples/bert/requirements.txt
  samples/contrib/pytorch-samples/cifar10/cifar10_pytorch.py
  samples/contrib/pytorch-samples/cifar10/config.properties
  samples/contrib/pytorch-samples/cifar10/requirements.txt
  samples/contrib/pytorch-samples/install-dependencies.sh
  samples/contrib/pytorch-samples/mino-secret.yaml
  samples/contrib/pytorch-samples/package.json
  samples/contrib/pytorch-samples/prerequisites.md
Labels: approved, cla: yes, lgtm, size/L

#4756 chore(components) - Add SageMaker component owners to AWS owners list
  components/aws/OWNERS
  components/aws/sagemaker/OWNERS
  samples/contrib/aws-samples/OWNERS
Labels: approved, cla: yes, lgtm, size/S

#5814 feat(components): Addressing Review comments on Trainer component for PyTorch - KFP
  components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/components/base/base_component.py
  components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/components/mar/executor.py
  components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/components/minio/executor.py
  components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/components/trainer/component.py
  components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/components/trainer/executor.py
  components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/components/trainer/generic_executor.py
  components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/types/standard_component_specs.py
  components/PyTorch/pytorch-kfp-components/setup.py
  components/PyTorch/pytorch-kfp-components/tests/test_minio.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#5856 feat(samples/pytorch): Adding compilation test for PyTorch samples KFP
  samples/contrib/pytorch-samples/compile_test.json
  samples/contrib/pytorch-samples/test_compile_yamls.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#5879 test(sdk/v2compat): reproduce v2 py component default value does not work
  samples/test/lightweight_python_functions_v2_pipeline.py
  samples/test/lightweight_python_functions_v2_pipeline_test.py
Labels: approved, cla: yes, lgtm, size/XS

#5884 chore(launcher): improve launcher logging & fix some error handling. Fixes #5882
  v2/cmd/launch/main.go
  v2/component/launcher.go
  v2/component/runtime_info.go
Labels: approved, cla: yes, lgtm, size/M

#5874 chore: add capri-xiyue to backend OWNERS
  backend/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#5883 feat(launcher): nested directory artifacts support in v2 compatible
  samples/core/output_a_directory/output_a_directory.py
  samples/core/output_a_directory/output_a_directory_test.py
  v2/component/launcher.go
Labels: approved, cla: yes, lgtm, size/L

#5862 doc: KFP 2021 roadmap
  ROADMAP.md
Labels: approved, cla: yes, lgtm, size/L

#5871 feat(component/pytorch) Custom handler for cifar10 example ,saves multiple explain attributions methods
  samples/contrib/pytorch-samples/Pipeline-Cifar10-Captum-Insights.ipynb
  samples/contrib/pytorch-samples/cifar10/cifar10_handler.py
  samples/contrib/pytorch-samples/cifar10/cifar10_pytorch.py
  samples/contrib/pytorch-samples/cifar10/classifier.py
  samples/contrib/pytorch-samples/cifar10/config.properties
  samples/contrib/pytorch-samples/cifar10/requirements.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#5899 fix(sdk compiler):Fix v2 compile for exit handler Fixes #5854
  sdk/python/kfp/v2/compiler/compiler.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_exit_handler.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_exit_handler.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#5891 chore: Change python/kfp/compiler and cli folders from relative to absolute path
  sdk/python/kfp/cli/cli.py
  sdk/python/kfp/cli/diagnose_me/dev_env.py
  sdk/python/kfp/cli/diagnose_me/dev_env_test.py
  sdk/python/kfp/cli/diagnose_me/gcp.py
  sdk/python/kfp/cli/diagnose_me/gcp_test.py
  sdk/python/kfp/cli/diagnose_me/kubernetes_cluster.py
  sdk/python/kfp/cli/diagnose_me/kubernetes_cluster_test.py
  sdk/python/kfp/cli/diagnose_me/utility_test.py
  sdk/python/kfp/cli/diagnose_me_cli.py
  sdk/python/kfp/cli/experiment.py
  sdk/python/kfp/cli/pipeline.py
  sdk/python/kfp/cli/run.py
  sdk/python/kfp/compiler/_default_transformers.py
  sdk/python/kfp/compiler/_k8s_helper.py
  sdk/python/kfp/compiler/_op_to_template.py
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/compiler/main.py
Labels: approved, cla: yes, lgtm, size/M

#5898 chore(frontend): Update react-scripts to v4.0.3. Fix #5794
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/ExperimentList.tsx
  frontend/src/lib/OutputArtifactLoader.test.ts
  frontend/src/pages/AllRecurringRunsList.test.tsx
  frontend/src/pages/AllRunsList.test.tsx
  frontend/src/pages/NewPipelineVersion.tsx
  frontend/src/pages/RunDetails.tsx
  frontend/tsconfig.json
Labels: approved, cla: yes, lgtm, size/XXL

#5903 fix(sdk): Fix default value of component input not picked up. Fixes #5880.
  samples/test/lightweight_python_functions_v2_pipeline.py
  samples/test/lightweight_python_functions_v2_pipeline_test.py
  sdk/python/kfp/dsl/_component_bridge.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_pipeline.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_pipeline.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/xgboost_sample_pipeline.json
Labels: approved, cla: yes, lgtm, size/L

#5892 feat(sdk): add timeout option to kfp run submit. Fixes #5806
  sdk/python/kfp/cli/run.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#5890 fix(components/google-cloud): Correct API reference doc link in README.md
  components/google-cloud/README.md
Labels: approved, cla: yes, lgtm, size/XS

#5894 fix(deployment): reduce artifact name collision rate under heavy load
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/argo.yaml
  manifests/gcp_marketplace/test/snapshot-base.yaml
  manifests/gcp_marketplace/test/snapshot-managed-storage-with-db-prefix.yaml
  manifests/gcp_marketplace/test/snapshot-managed-storage.yaml
  manifests/kustomize/third-party/argo/base/workflow-controller-configmap-patch.yaml
Labels: approved, cla: yes, lgtm, size/XL

#5870 fix(components/pytorch) Pytorch Lightning Arguments string pass through
  components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/components/utils/__init__.py
  components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/components/utils/argument_parsing.py
  samples/contrib/pytorch-samples/Pipeline-Bert.ipynb
  samples/contrib/pytorch-samples/Pipeline-Cifar10-Captum-Insights.ipynb
  samples/contrib/pytorch-samples/Pipeline-Cifar10.ipynb
  samples/contrib/pytorch-samples/bert/agnews_classification_pytorch.py
  samples/contrib/pytorch-samples/bert/pipeline.py
  samples/contrib/pytorch-samples/bert/yaml/train/component.yaml
  samples/contrib/pytorch-samples/build.sh
  samples/contrib/pytorch-samples/cifar10/cifar10_pytorch.py
  samples/contrib/pytorch-samples/cifar10/pipeline.py
  samples/contrib/pytorch-samples/cifar10/yaml/train/component.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#5911 chore(components/pytorch) [WIP] Updating docker image location - pytorch kfp samples
  samples/contrib/pytorch-samples/Pipeline-Bert.ipynb
  samples/contrib/pytorch-samples/Pipeline-Cifar10-Captum-Insights.ipynb
  samples/contrib/pytorch-samples/Pipeline-Cifar10.ipynb
  samples/contrib/pytorch-samples/bert/pipeline.py
  samples/contrib/pytorch-samples/bert/yaml/pre_process/component.yaml
  samples/contrib/pytorch-samples/bert/yaml/train/component.yaml
  samples/contrib/pytorch-samples/cifar10/pipeline.py
  samples/contrib/pytorch-samples/cifar10/yaml/pre_process/component.yaml
  samples/contrib/pytorch-samples/cifar10/yaml/train/component.yaml
  samples/contrib/pytorch-samples/common/minio/component.yaml
  samples/contrib/pytorch-samples/common/prediction/component.yaml
  samples/contrib/pytorch-samples/common/tensorboard/component.yaml
  samples/contrib/pytorch-samples/test_compile_yamls.py
Labels: approved, cla: yes, lgtm, size/M

#5909 feat(v2/dsl): support minio & s3 artifacts in v2 python component. Fixes #5838
  samples/test/lightweight_python_functions_v2_with_outputs_test.py
  sdk/python/kfp/components/executor_test.py
  sdk/python/kfp/dsl/io_types.py
  sdk/python/kfp/v2/compiler_cli_tests/README.md
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_pipeline.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_with_outputs.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_custom_job_spec.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_exit_handler.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_importer.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_metrics_outputs.json
  v2/component/launcher.go
  v2/test/requirements.txt
Labels: approved, cla: yes, lgtm, size/L

#5888 chore(components/google-cloud): Post release updates
  components/google-cloud/RELEASE.md
  components/google-cloud/container/aiplatform/cloudbuild.yaml
  components/google-cloud/google_cloud_pipeline_components/aiplatform/utils.py
  components/google-cloud/google_cloud_pipeline_components/version.py
Labels: approved, cla: yes, lgtm, size/S

#5805 feat(component): Add GCP launcher following the first party component interface
  components/google-cloud/container/gcp/Dockerfile
  components/google-cloud/container/gcp/launcher/custom_job.py
  components/google-cloud/container/gcp/launcher/launcher.py
  components/google-cloud/custom_job/component.yaml
Labels: approved, cla: yes, lgtm, size/L

#5916 chore: release KFP SDK and v2 launcher 1.6.4
  sdk/python/kfp/__init__.py
  sdk/python/kfp/compiler/v2_compat.py
Labels: approved, cla: yes, lgtm, size/XS

#5914 chore: fix broken ipynb notebook
  components/gcp/dataflow/launch_python/sample.ipynb
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#5859 feat(frontend) Support Input/Output from MLMD for V2-compatible. Fix #5670
  frontend/src/TestUtils.ts
  frontend/src/components/ArtifactPreview.test.tsx
  frontend/src/components/ArtifactPreview.tsx
  frontend/src/components/DetailsTable.test.tsx
  frontend/src/components/DetailsTable.tsx
  frontend/src/components/tabs/ExecutionTitle.test.tsx
  frontend/src/components/tabs/ExecutionTitle.tsx
  frontend/src/components/tabs/InputOutputTab.test.tsx
  frontend/src/components/tabs/InputOutputTab.tsx
  frontend/src/components/tabs/MetricsTab.tsx
  frontend/src/lib/Apis.ts
  frontend/src/lib/MetricUtils.ts
  frontend/src/lib/MlmdUtils.ts
  frontend/src/lib/RunUtils.ts
  frontend/src/lib/StaticGraphParser.ts
  frontend/src/pages/RunDetails.tsx
Labels: approved, cla: yes, lgtm, size/XXL

#5918 chore(components/pytorch) Cifar 10 example - Confusion matrix Fix
  samples/contrib/pytorch-samples/cifar10/cifar10_pytorch.py
Labels: approved, cla: yes, lgtm, size/XS

#5863 Fix(Components/pytorch): Add single docker file for cpu and gpu
  samples/contrib/pytorch-samples/Dockerfile
  samples/contrib/pytorch-samples/Dockerfile-cpu
  samples/contrib/pytorch-samples/Dockerfile-gpu
  samples/contrib/pytorch-samples/README.md
  samples/contrib/pytorch-samples/common/tensorboard/Dockerfile
Labels: approved, cla: yes, lgtm, size/L

#5905 chore(components/pytorch) Updating pytorch lightning version to 1.3.7
  components/PyTorch/pytorch-kfp-components/setup.py
  samples/contrib/pytorch-samples/bert/requirements.txt
  samples/contrib/pytorch-samples/cifar10/requirements.txt
  samples/contrib/pytorch-samples/requirements.txt
Labels: approved, cla: yes, lgtm, size/S

#5837 chore(components/google-cloud): Refer to Vertex AI instead of AI Platform (Unified)
  components/google-cloud/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#5936 feat(sample): Add markdown visualization example for v1 and v2 compatible
  samples/core/visualization/markdown.py
  samples/core/visualization/markdown_test.py
Labels: approved, cla: yes, lgtm, size/M

#5928 chore(samples/pytorch) - Build script fix - Updating Dockerfile name
  samples/contrib/pytorch-samples/bert/config.properties
  samples/contrib/pytorch-samples/build.sh
Labels: approved, cla: yes, lgtm, size/XS

#5938 feat(sample): Add HTML sample for v1/v2 visualization
  samples/core/visualization/hello-world.html
  samples/core/visualization/html.py
  samples/core/visualization/html_test.py
Labels: approved, cla: yes, lgtm, size/L

#5950 chore: configure semantic pull requests bot. Fixes #5942
  .github/semantic.yml
Labels: approved, cla: yes, lgtm, size/S

#5857 chore(v2): DB and API for creating/querying cache entries
  backend/api/go_client/task.pb.go
  backend/api/go_client/task.pb.gw.go
  backend/api/task.proto
  backend/src/apiserver/client_manager.go
  backend/src/apiserver/model/task.go
  backend/src/apiserver/resource/client_manager_fake.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/server/api_converter.go
  backend/src/apiserver/server/api_converter_test.go
  backend/src/apiserver/server/task_server.go
  backend/src/apiserver/storage/db_fake.go
  backend/src/apiserver/storage/pipeline_store_test.go
  backend/src/apiserver/storage/run_store_test.go
  backend/src/apiserver/storage/task_store.go
  backend/src/apiserver/storage/task_store_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#5958 chore(components/google-cloud): Update OWNERS
  components/google-cloud/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#5953 chore(components/google-cloud): Merge v0.1.2 API doc changes in master
  components/google-cloud/docs/source/google_cloud_pipeline_components.aiplatform.rst
Labels: approved, cla: yes, lgtm, size/XS
