Repository kubeflow/pipelines, pull requests merged in 2021-11, with the labels that each got.

#6843 test: skip archiving experiments because of perf problem
  test/kfp-functional-test/run_kfp_functional_test.py
Labels: size/XS, cla: yes

#6835 docs: Backend release doc update
  RELEASE.md
Labels: lgtm, approved, size/S, cla: yes

#6846 docs: Add instruction to update kfp test-infra
  RELEASE.md
Labels: lgtm, approved, size/XS, cla: yes

#6847 chore: update eks version to 1.18 for aws sagemaker integration tests
  components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests
Labels: lgtm, approved, size/XS, needs-ok-to-test, cla: yes

#6842 chore(release): bump version to 1.7.1 on master branch
  CHANGELOG.md
  VERSION
  backend/api/python_http_client/README.md
  backend/api/python_http_client/docs/ApiPipelineSpec.md
  backend/api/python_http_client/docs/ApiValue.md
  backend/api/python_http_client/docs/PipelineSpecRuntimeConfig.md
  backend/api/python_http_client/kfp_server_api/__init__.py
  backend/api/python_http_client/kfp_server_api/api_client.py
  backend/api/python_http_client/kfp_server_api/configuration.py
  backend/api/python_http_client/kfp_server_api/models/__init__.py
  backend/api/python_http_client/kfp_server_api/models/api_pipeline_spec.py
  backend/api/python_http_client/kfp_server_api/models/api_value.py
  backend/api/python_http_client/kfp_server_api/models/pipeline_spec_runtime_config.py
  backend/api/python_http_client/setup.py
  backend/api/python_http_client/test/test_api_job.py
  backend/api/python_http_client/test/test_api_list_jobs_response.py
  backend/api/python_http_client/test/test_api_list_runs_response.py
  backend/api/python_http_client/test/test_api_pipeline_spec.py
  backend/api/python_http_client/test/test_api_run.py
  backend/api/python_http_client/test/test_api_run_detail.py
  backend/api/python_http_client/test/test_api_value.py
  backend/api/python_http_client/test/test_pipeline_spec_runtime_config.py
  backend/api/swagger/kfp_api_single_file.swagger.json
  components/README.md
  components/gcp/container/component_sdk/python/setup.py
  components/kubeflow/deployer/component.yaml
  components/kubeflow/dnntrainer/component.yaml
  components/local/confusion_matrix/component.yaml
  components/local/roc/component.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml
  manifests/gcp_marketplace/schema.yaml
  manifests/kustomize/base/cache-deployer/kustomization.yaml
  manifests/kustomize/base/cache/kustomization.yaml
  manifests/kustomize/base/installs/generic/pipeline-install-config.yaml
  manifests/kustomize/base/metadata/base/kustomization.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/base/pipeline/metadata-writer/kustomization.yaml
  manifests/kustomize/env/gcp/inverse-proxy/kustomization.yaml
  samples/core/kubeflow_tf_serving/kubeflow_tf_serving.ipynb
  samples/core/xgboost_training_cm/xgboost_training_cm.py
Labels: lgtm, approved, size/XL, cla: yes

#6622 feat: allow the default-editor to edit argo workflows and fix bug #6649
  manifests/kustomize/base/installs/multi-user/view-edit-cluster-roles.yaml
Labels: lgtm, approved, size/S, ok-to-test, cla: yes

#6841 fix(sdk): Fix invalid doc example of python_component
  sdk/python/kfp/dsl/_component.py
Labels: lgtm, approved, size/XS, needs-ok-to-test, cla: yes

#6844 fix(sdk): fix cloud scheduler's job name
  sdk/python/kfp/v2/google/client/schedule.py
Labels: lgtm, approved, size/XS, ok-to-test, cherrypick-approved, cla: yes

#6851 chore(sdk): add deprecation warnings for v2
  sdk/python/kfp/v2/compiler/compiler.py
  sdk/python/kfp/v2/google/client/client.py
  sdk/python/kfp/v2/google/experimental/custom_job.py
Labels: lgtm, approved, size/S, cla: yes

#6853 chore(sdk): Release 1.8.8 off `sdk/release-1.8` branch
  sdk/RELEASE.md
Labels: lgtm, approved, size/M, cla: yes

#6852 chore(sdk): Cherry pick #6844 and #6851 to sdk/release-1.8 branch
  sdk/RELEASE.md
  sdk/python/kfp/v2/compiler/compiler.py
  sdk/python/kfp/v2/google/client/client.py
  sdk/python/kfp/v2/google/client/schedule.py
  sdk/python/kfp/v2/google/experimental/custom_job.py
Labels: lgtm, approved, size/M, cla: yes

#6854 chore(sdk): Release KFP SDK 1.8.8
  sdk/python/kfp/__init__.py
Labels: lgtm, approved, size/XS, cla: yes

#6807 chore(backend): Fix typo in log message
  backend/src/apiserver/client/swf.go
Labels: lgtm, approved, size/XS, needs-ok-to-test, cla: yes

#6752 docs(backend): fix incorrect maxNumViewers help text
  backend/src/crd/controller/viewer/main.go
Labels: lgtm, approved, size/XS, needs-ok-to-test, cla: yes

#6862 test: fix kubeflow-pipelines-tfx-python37 test
  test/presubmit-tests-tfx.sh
Labels: lgtm, approved, size/XS, cla: yes

#6859 fix(sdk): Make `Artifact` type be compatible with any sub-artifact types bidirectionally
  sdk/python/kfp/dsl/types.py
  sdk/python/kfp/v2/compiler/compiler_test.py
Labels: lgtm, approved, size/M, cherrypick-approved, cla: yes

#6864 chore(sdk): Release KFP SDK 1.8.9 off `sdk/release-1.8` branch
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
Labels: lgtm, approved, size/M, cherrypick-approved, cla: yes

#6865 chore: Cherry pick #6859 and #6864 to sdk/release-1.8 branch
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
  sdk/python/kfp/dsl/types.py
  sdk/python/kfp/v2/compiler/compiler_test.py
Labels: lgtm, approved, size/L, cla: yes

#6876 chore(components/google-cloud): merge release to branch google cloud pipeline components 0.2.0
  .readthedocs.yml
  components/google-cloud/RELEASE.md
  components/google-cloud/google_cloud_pipeline_components/aiplatform/batch_predict_job/component.yaml
  components/google-cloud/google_cloud_pipeline_components/aiplatform/endpoint/create_endpoint/component.yaml
  components/google-cloud/google_cloud_pipeline_components/aiplatform/endpoint/deploy_model/component.yaml
  components/google-cloud/google_cloud_pipeline_components/aiplatform/model/export_model/component.yaml
  components/google-cloud/google_cloud_pipeline_components/aiplatform/model/upload_model/component.yaml
  components/google-cloud/google_cloud_pipeline_components/aiplatform/utils.py
  components/google-cloud/google_cloud_pipeline_components/container/Dockerfile
  components/google-cloud/google_cloud_pipeline_components/container/cloudbuild.yaml
  components/google-cloud/google_cloud_pipeline_components/experimental/custom_job/component.yaml
  components/google-cloud/google_cloud_pipeline_components/experimental/dataflow/python_job/component.yaml
  components/google-cloud/google_cloud_pipeline_components/experimental/notebooks/executor/component.yaml
  components/google-cloud/google_cloud_pipeline_components/experimental/wait_gcp_resources/component.yaml
  components/google-cloud/google_cloud_pipeline_components/version.py
  docs/requirements.txt
Labels: size/M, cla: yes

#6866 chore(sdk): Remove redundant check in set_gpu_limit
  sdk/RELEASE.md
  sdk/python/kfp/dsl/_container_op.py
Labels: lgtm, approved, size/XS, cla: yes

#6886 chore(sdk): Remove sdk/python/kfp/v2/google directory for v2
  sdk/RELEASE.md
  sdk/python/MANIFEST.in
  sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_custom_job_spec.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_custom_job_spec.py
  sdk/python/kfp/v2/google/__init__.py
  sdk/python/kfp/v2/google/client/__init__.py
  sdk/python/kfp/v2/google/client/_cloud_function_templated_http_request.py
  sdk/python/kfp/v2/google/client/_cloud_function_templated_http_request_test.py
  sdk/python/kfp/v2/google/client/client.py
  sdk/python/kfp/v2/google/client/client_test.py
  sdk/python/kfp/v2/google/client/client_utils.py
  sdk/python/kfp/v2/google/client/client_utils_test.py
  sdk/python/kfp/v2/google/client/discovery/aiplatform_public_google_rest_v1beta1.json
  sdk/python/kfp/v2/google/client/runtime_config_builder.py
  sdk/python/kfp/v2/google/client/runtime_config_builder_test.py
  sdk/python/kfp/v2/google/client/schedule.py
  sdk/python/kfp/v2/google/client/schedule_test.py
  sdk/python/kfp/v2/google/client/testdata/pipeline1.json
  sdk/python/kfp/v2/google/client/testdata/pipeline1_request_body.json
  sdk/python/kfp/v2/google/client/testdata/pipeline1_request_body_final.json
  sdk/python/kfp/v2/google/client/testdata/pipeline_job.json
  sdk/python/kfp/v2/google/experimental/__init__.py
  sdk/python/kfp/v2/google/experimental/custom_job.py
  sdk/python/kfp/v2/google/experimental/custom_job_test.py
  sdk/python/requirements-test.txt
  sdk/python/requirements.in
  sdk/python/requirements.txt
  sdk/python/setup.py
Labels: lgtm, approved, size/XXL, cla: yes

#6907 test: temporarily test tfx against a release branch
  test/presubmit-tests-tfx.sh
Labels: lgtm, approved, size/XS, cla: yes

#6892 fix(deployment): the viewer controller does not work because of missing permissions
  manifests/kustomize/base/installs/multi-user/viewer-controller/cluster-role.yaml
Labels: lgtm, approved, size/XS, needs-ok-to-test, cla: yes

#6905 fix(sdk.v2): Fix regression on optional inputs
  sdk/RELEASE.md
  sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_pipeline.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/v2_component_with_optional_inputs.json
  sdk/python/kfp/v2/components/base_component.py
  sdk/python/kfp/v2/components/base_component_test.py
  sdk/python/kfp/v2/components/component_factory.py
  sdk/python/kfp/v2/components/structures.py
  sdk/python/kfp/v2/components/structures_test.py
Labels: lgtm, approved, size/L, cla: yes

#6882 fix(sdk): visualizations and metrics do not work with data_passing_methods
  sdk/python/kfp/compiler/_data_passing_using_volume.py
  sdk/python/tests/compiler/testdata/artifact_passing_using_volume.py
  sdk/python/tests/compiler/testdata/artifact_passing_using_volume.yaml
Labels: lgtm, approved, size/L, ok-to-test, cherrypick-approved, cla: yes

#6856 test: default to emissary executor
  test/manifests/dev/kustomization.yaml
  test/manifests/dev/workflow-controller-configmap-patch.yaml
Labels: lgtm, approved, size/S, cla: yes

#6921 test: Use cp when rsync is unnecessary. Install rsync otherwise.
  components/gcp/container/build_image.sh
  components/kubeflow/dnntrainer/build_image.sh
  components/kubeflow/launcher/build_image.sh
  components/kubeflow/pytorch-launcher/build_image.sh
  components/local/base/build_image.sh
Labels: lgtm, approved, size/S, cla: yes

#6904 feat(manifests): Add liveness Probe for cloud sql proxy. Fix #4973
  .cloudbuild.yaml
  .release.cloudbuild.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/mysql.yaml
  manifests/kustomize/env/gcp/cloudsql-proxy/cloudsql-proxy-deployment.yaml
  test/tag_for_hosted.sh
Labels: lgtm, approved, size/L, cla: yes

#6917 feat(sdk): ImporterSpec v2
  sdk/RELEASE.md
  sdk/python/kfp/v2/compiler/compiler.py
  sdk/python/kfp/v2/compiler/pipeline_spec_builder.py
  sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_importer.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_importer.py
  sdk/python/kfp/v2/components/importer_component.py
  sdk/python/kfp/v2/components/importer_node.py
  sdk/python/kfp/v2/components/importer_node_test.py
  sdk/python/kfp/v2/components/pipeline_task.py
  sdk/python/tests/compiler/compiler_tests.py
Labels: lgtm, approved, size/XL, cla: yes

#6909 feat(frontend): Upload V2 Pipelines. Fix PipelineSpec editor prettified view.
  frontend/mock-backend/data/v2/pipeline/mock_lightweight_python_functions_v2_pipeline.json
  frontend/mock-backend/data/v2/pipeline/mock_lightweight_python_functions_v2_pipeline_rev.json
  frontend/mock-backend/data/v2/pipeline/pipeline_with_loops_and_conditions.json
  frontend/mock-backend/data/v2/pipeline/xgboost_sample_pipeline.json
  frontend/src/components/tabs/StaticNodeDetailsV2.tsx
  frontend/src/data/test/mock_lightweight_python_functions_v2_pipeline.json
  frontend/src/data/test/pipeline_with_loops_and_conditions.json
  frontend/src/lib/v2/DynamicFlow.test.ts
  frontend/src/lib/v2/StaticFlow.test.ts
  frontend/src/lib/v2/WorkflowUtils.test.ts
  frontend/src/lib/v2/WorkflowUtils.ts
  frontend/src/pages/PipelineDetailsV2.tsx
Labels: lgtm, approved, size/XXL, cla: yes

#6933 chore: Update samples/OWNERS
  samples/OWNERS
Labels: lgtm, approved, size/XS, cla: yes

#6929 chore(v2): support pipeline parameter defaults + running specs directly
  v2/Makefile
  v2/cmd/compiler/main.go
  v2/compiler/argo.go
  v2/component/launcher_v2.go
Labels: lgtm, approved, size/L, cla: yes

#6918 chore: break out submitNextWorkflowIfNeeded clean up from #4752
  backend/src/crd/controller/scheduledworkflow/controller.go
  backend/src/crd/controller/scheduledworkflow/util/scheduled_workflow.go
  backend/src/crd/controller/scheduledworkflow/util/scheduled_workflow_test.go
Labels: lgtm, approved, size/M, cla: yes

#6932 test(sample): reenable samples tests run with V2_ENGINE mode
  samples/core/output_a_directory/output_a_directory_test.py
  samples/test/after.py
  samples/test/lightweight_python_functions_v2_pipeline_test.py
  samples/test/lightweight_python_functions_v2_with_outputs.py
  samples/test/lightweight_python_functions_v2_with_outputs_test.py
  samples/test/parameter_with_format_test.py
  samples/test/placeholder_concat.py
  samples/test/reused_component_test.py
  samples/test/two_step_test.py
  samples/test/two_step_with_uri_placeholder.py
  samples/test/util.py
  samples/v2/hello_world.py
  samples/v2/lightweight_python_functions_v2_pipeline/lightweight_python_functions_v2_pipeline.py
  samples/v2/pipeline_with_importer.py
  samples/v2/producer_consumer_param.py
Labels: lgtm, approved, size/L, cla: yes

#6937 fix(sdk.v2): Fix bug on executor input with default value.
  samples/test/lightweight_python_functions_v2_pipeline_test.py
  sdk/RELEASE.md
  sdk/python/kfp/v2/components/executor.py
  sdk/python/kfp/v2/components/executor_test.py
Labels: lgtm, approved, size/M, cla: yes

#6911 chore(sdk): Fix a warning message
  sdk/python/kfp/components/_python_op.py
Labels: lgtm, approved, size/XS, ok-to-test, cla: yes

#6943 test: clean up v2 compatible mode sample tests
  samples/core/XGBoost/xgboost_sample_test.py
  samples/core/condition/condition_test.py
  samples/core/condition/nested_condition_test.py
  samples/core/exit_handler/exit_handler_test.py
  samples/core/loop_output/loop_output_test.py
  samples/core/loop_parallelism/loop_parallelism_test.py
  samples/core/loop_parameter/loop_parameter_test.py
  samples/core/loop_static/loop_static_test.py
  samples/core/output_a_directory/output_a_directory.py
  samples/core/output_a_directory/output_a_directory_test.py
  samples/core/resource_spec/resource_spec_test.py
  samples/core/resource_spec/runtime_resource_request_test.py
  samples/core/use_run_info/use_run_id.py
  samples/core/use_run_info/use_run_id_test.py
  samples/core/visualization/confusion_matrix_test.py
  samples/core/visualization/html_test.py
  samples/core/visualization/markdown_test.py
  samples/core/visualization/roc_test.py
  samples/core/visualization/table_test.py
  samples/core/visualization/tensorboard_minio_test.py
  samples/test/after_test.py
  samples/test/cache_v2_compatible_test.py
  samples/test/fail_parameter_value_missing_test.py
  samples/test/fail_test.py
  samples/test/lightweight_python_functions_v2_pipeline_test.py
  samples/test/lightweight_python_functions_v2_with_outputs_test.py
  samples/test/metrics_visualization_v1_test.py
  samples/test/metrics_visualization_v2_test.py
  samples/test/parameter_with_format_test.py
  samples/test/placeholder_concat_test.py
  samples/test/placeholder_if_test.py
  samples/test/reused_component_test.py
  samples/test/two_step_test.py
  samples/test/two_step_with_uri_placeholder_test.py
  samples/test/util.py
Labels: lgtm, approved, size/XL, cla: yes

#6946 chore(sdk.v2): Add test sample for runtime placeholders
  sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_placeholders.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_placeholders.py
Labels: lgtm, approved, size/L, cla: yes

#6939 chore(sdk): allow google-auth < 3
  sdk/RELEASE.md
  sdk/python/requirements.in
  sdk/python/setup.py
Labels: lgtm, approved, size/XS, ok-to-test, cla: yes

#6950 test: temporarily test tfx against a release branch
  test/presubmit-tests-tfx.sh
Labels: lgtm, approved, size/XS, cla: yes

#6941 fix(sdk): refresh access token only when it expires. Fixes #6883
  sdk/python/kfp/_client.py
Labels: lgtm, approved, size/S, ok-to-test, cla: yes

#6952 fix(sdk): change otherwise to else in yaml
  sdk/RELEASE.md
  sdk/python/kfp/v2/components/pipeline_task_test.py
  sdk/python/kfp/v2/components/structures.py
  sdk/python/kfp/v2/components/structures_test.py
Labels: lgtm, approved, size/S, cla: yes

#6919 feat(sdk): add set_env_variable for Pipeline task
  sdk/RELEASE.md
  sdk/python/kfp/v2/compiler/compiler.py
  sdk/python/kfp/v2/compiler/pipeline_spec_builder.py
  sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_env.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_env.py
  sdk/python/kfp/v2/components/pipeline_task.py
  sdk/python/kfp/v2/components/pipeline_task_test.py
Labels: lgtm, approved, size/L, cla: yes

#6947 chore(sdk): Fix the warning message
  sdk/python/kfp/components/_python_op.py
Labels: lgtm, approved, size/XS, needs-ok-to-test, cla: yes

#6955 chore: Cherry pick #6941 to sdk/release-1.8 branch
  sdk/python/kfp/_client.py
Labels: lgtm, approved, needs-ok-to-test, size/S, cla: yes

#6957 fix(sdk.v2): Avoid pydantic union bug
  samples/test/lightweight_python_functions_v2_with_outputs_test.py
  sdk/RELEASE.md
  sdk/python/kfp/v2/components/structures.py
Labels: lgtm, approved, size/S, cla: yes

#6958 feat(sdk)!: Deprecate V2 compatible mode in v1 compiler
  sdk/RELEASE.md
  sdk/python/kfp/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
Labels: lgtm, approved, size/S, cla: yes

#6910 feat(backend): Upgrade MLMD to 1.4.0
  .cloudbuild.yaml
  .release.cloudbuild.yaml
  backend/metadata_writer/requirements.in
  backend/requirements.in
  backend/requirements.txt
  backend/src/apiserver/config/sample_config.json
  backend/src/apiserver/visualization/requirements.in
  backend/src/apiserver/visualization/requirements.txt
  frontend/src/config/sample_config_from_backend.json
  frontend/src/mlmd/LineageView.tsx
  frontend/src/mlmd/Utils.tsx
  frontend/src/pages/GettingStarted.test.tsx
  frontend/src/pages/GettingStarted.tsx
  frontend/src/pages/__snapshots__/GettingStarted.test.tsx.snap
  frontend/src/third_party/mlmd/generated/ml_metadata/proto/metadata_store_pb.d.ts
  frontend/src/third_party/mlmd/generated/ml_metadata/proto/metadata_store_pb.js
  frontend/src/third_party/mlmd/generated/ml_metadata/proto/metadata_store_service_grpc_web_pb.d.ts
  frontend/src/third_party/mlmd/generated/ml_metadata/proto/metadata_store_service_grpc_web_pb.js
  frontend/src/third_party/mlmd/generated/ml_metadata/proto/metadata_store_service_pb.d.ts
  frontend/src/third_party/mlmd/generated/ml_metadata/proto/metadata_store_service_pb.js
  manifests/kustomize/base/metadata/base/metadata-grpc-deployment.yaml
  test/sample-test/requirements.in
  test/sample-test/requirements.txt
  test/tag_for_hosted.sh
  third_party/ml-metadata/README.md
  third_party/ml-metadata/VERSION
  third_party/ml-metadata/ml_metadata/proto/metadata_store.proto
  third_party/ml-metadata/ml_metadata/proto/metadata_store_service.proto
  third_party/ml-metadata/update_version.sh
  v2/Makefile
Labels: lgtm, size/XXL, cla: yes

#6968 test(samples): fix xgboost sample OOM flakiness
  samples/core/XGBoost/xgboost_sample.py
Labels: lgtm, approved, size/XS, cla: yes

#6971 refactor(v2): migrate to MLMD go lib as a separate lib
  v2/component/importer_launcher.go
  v2/component/launcher.go
  v2/component/launcher_v2.go
  v2/driver/driver.go
  v2/go.mod
  v2/go.sum
  v2/metadata/client.go
  v2/metadata/client_test.go
  v2/metadata/converter.go
  v2/metadata/model.go
  v2/third_party/ml_metadata/metadata_source.pb.go
  v2/third_party/ml_metadata/metadata_store.pb.go
  v2/third_party/ml_metadata/metadata_store_service.pb.go
  v2/third_party/ml_metadata/metadata_store_service_grpc.pb.go
Labels: lgtm, approved, size/XXL, cla: yes

#6975 chore: update licenses
  go-licenses.yaml
Labels: size/XS, cla: yes

#6973 feat(frontend): Disable delete button if no pipeline version is not selected
  frontend/src/pages/PipelineDetails.test.tsx
  frontend/src/pages/PipelineDetails.tsx
Labels: lgtm, approved, size/S, cla: yes

#6908 chore: make the log message as an explicit non-error message
  v2/config/env.go
Labels: lgtm, approved, size/XS, needs-ok-to-test, cla: yes

#6978 fix(sdk): fix load_test
  sdk/RELEASE.md
  sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_concat_placeholder.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_if_placeholder.json
  sdk/python/kfp/v2/components/structures.py
  sdk/python/kfp/v2/components/yaml_component.py
Labels: lgtm, approved, size/L, cla: yes

#6650 test: clean up of api server tests
  backend/src/apiserver/server/experiment_server_test.go
  backend/src/apiserver/server/list_request_util.go
  backend/src/apiserver/server/pipeline_server_test.go
  backend/src/apiserver/server/pipeline_upload_server_test.go
  backend/src/apiserver/server/report_server_test.go
  backend/src/apiserver/server/run_server_test.go
  backend/src/apiserver/server/test_util.go
  backend/src/apiserver/server/util.go
  backend/src/apiserver/server/util_test.go
  backend/src/apiserver/storage/default_experiment_store.go
Labels: lgtm, approved, size/L, cla: yes

#6984 chore(mlmd): fix MLMD update scripts
  third_party/ml-metadata/update_version.sh
  v2/Makefile
  v2/test/requirements.txt
Labels: lgtm, approved, size/M, cla: yes

#6961 docs: Add more SDK badges
  README.md
Labels: lgtm, approved, size/XS, needs-ok-to-test, cla: yes

#6979 fix(sdk): fix resource spec test
  sdk/RELEASE.md
  sdk/python/kfp/v2/compiler/pipeline_spec_builder.py
  sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_ontology.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_resource_spec.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_resource_spec.py
Labels: lgtm, approved, size/XL, cla: yes

#6963 chore: consistent yapf style config for the entire repo
  .style.yapf
Labels: lgtm, approved, size/XS, cla: yes
