Repository kubeflow/pipelines, pull requests merged in 2021-05, with the labels that each got.

#5543 chore(v2): fix int/float parameter parsing with extra newline and fix reused_component sample
  samples/test/reused_component_test.py
  samples/test/util.py
  v2/cmd/launch/main.go
  v2/component/launcher.go
Labels: approved, cla: yes, lgtm, size/M

#5581 test(v2): fix kaniko component digest
  v2/test/components/kaniko.yaml
Labels: approved, cla: yes, lgtm, size/XS

#5580 chore(v2): include NOTICES in kfp-launcher image
  v2/go-mod-licenses.yaml
  v2/go.sum
  v2/launcher_container/Dockerfile
  v2/third_party/NOTICES/licenses.txt
  v2/third_party/license_info.csv
Labels: approved, cla: yes, lgtm, size/XXL

#5582 [SDK] Add pod labels for telemetry purpose
  sdk/python/kfp/compiler/_default_transformers.py
  sdk/python/kfp/compiler/compiler.py
  sdk/python/tests/compiler/compiler_tests.py
Labels: approved, area/sdk/dsl/compiler, cla: yes, lgtm, size/M

#5591 fix(v2):added double value
  samples/test/util.py
Labels: approved, cla: yes, lgtm, size/XS

#5592 feat: update MLMD to 0.30.0
  .cloudbuild.yaml
  .release.cloudbuild.yaml
  backend/metadata_writer/requirements.in
  backend/metadata_writer/requirements.txt
  manifests/kustomize/base/metadata/base/metadata-grpc-deployment.yaml
  test/tag_for_hosted.sh
  v2/Makefile
  v2/test/requirements.txt
Labels: approved, cla: yes, lgtm, size/M

#5495 feat(sdk.v2): support using placeholder class in custom job spec.
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/kfp/dsl/dsl_utils.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_custom_job_spec.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_custom_job_spec.py
  sdk/python/kfp/v2/google/aiplatform.py
Labels: approved, cla: yes, lgtm, size/L

#5595 chore(frontend): upgrade kubeflow/frontend lib
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/ResourceInfo.tsx
  frontend/src/lib/MlmdUtils.ts
Labels: approved, cla: yes, lgtm, size/M

#5571 Add OWNERS for v2 folder
  v2/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#5541 chore(samples): v2 compatible exit handler sample
  samples/core/exit_handler/exit_handler.py
  samples/core/exit_handler/exit_handler_test.py
  samples/test/legacy_exit_handler_test.py
  samples/test/util.py
Labels: approved, cla: yes, lgtm, size/L

#5603 feat(components/google-cloud): Add API documentation
  components/google-cloud/docs/Makefile
  components/google-cloud/docs/dependencies.rst
  components/google-cloud/docs/google_cloud_pipeline_components.aiplatform.rst
  components/google-cloud/docs/google_cloud_pipeline_components.rst
  components/google-cloud/docs/make.bat
  components/google-cloud/docs/modules.rst
  components/google-cloud/docs/requirements.txt
  components/google-cloud/docs/setup.rst
  components/google-cloud/docs/source/conf.py
  components/google-cloud/docs/source/index.rst
  components/google-cloud/docs/tests.aiplatform.rst
  components/google-cloud/docs/tests.rst
Labels: approved, cla: yes, lgtm, size/L

#5611 chore(components/google-cloud): Update API documentation
  components/google-cloud/docs/modules.rst
  components/google-cloud/docs/requirements.txt
  components/google-cloud/docs/source/index.rst
  components/google-cloud/docs/tests.aiplatform.rst
  components/google-cloud/docs/tests.rst
Labels: approved, cla: yes, lgtm, size/M

#5594 test(sdk.v2): update xgboost sample pipeline
  sdk/python/kfp/v2/compiler_cli_tests/test_data/xgboost_sample_pipeline.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/xgboost_sample_pipeline.py
Labels: approved, cla: yes, lgtm, size/M

#5583 Add configurable connection max lifetime for MySQL
  backend/src/apiserver/client_manager.go
  backend/src/apiserver/config/config.json
  manifests/kustomize/base/installs/generic/pipeline-install-config.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#5616 test: pin google-cloud-bigquery to fix TFX presubmit
  test/presubmit-tests-tfx.sh
Labels: approved, cla: yes, lgtm, size/XS

#5622 chore(components/google-cloud): Fix API documentation generator and API docs.
  components/google-cloud/docs/.readthedocs.yml
  components/google-cloud/docs/dependencies.rst
  components/google-cloud/docs/google_cloud_pipeline_components.aiplatform.rst
  components/google-cloud/docs/setup.rst
  components/google-cloud/docs/source/conf.py
  components/google-cloud/docs/source/google_cloud_pipeline_components.aiplatform.rst
  components/google-cloud/docs/source/google_cloud_pipeline_components.rst
  components/google-cloud/docs/source/index.rst
  components/google-cloud/docs/source/modules.rst
  components/google-cloud/google_cloud_pipeline_components/aiplatform/__init__.py
  components/google-cloud/google_cloud_pipeline_components/aiplatform/utils.py
  components/google-cloud/tests/__init__.py
  components/google-cloud/tests/aiplatform/__init__.py
  components/google-cloud/tests/aiplatform/test_componets_compile.py
  components/google-cloud/tests/aiplatform/test_utils.py
Labels: approved, cla: yes, lgtm, size/L

#5575 chore(v2): metrics_visualization_v2 sample + fixed output artifact path creation
  samples/test/config.yaml
  samples/test/metrics_visualization_v2.py
  samples/test/metrics_visualization_v2_test.py
  v2/component/launcher.go
Labels: approved, cla: yes, lgtm, size/L

#5628 test: Update test cases in presubmit-tests-tfx.sh
  test/presubmit-tests-tfx.sh
Labels: approved, cla: yes, lgtm, size/XS

#5623 chore(components): Goolge - AI Platform - Improved component generation
  components/google-cloud/google_cloud_pipeline_components/aiplatform/utils.py
Labels: approved, area/components, cla: yes, lgtm, size/L

#5625 feat(components/google-cloud):Add support for URI prefix
  components/google-cloud/google_cloud_pipeline_components/aiplatform/remote_runner.py
  components/google-cloud/google_cloud_pipeline_components/aiplatform/utils.py
  components/google-cloud/tests/aiplatform/test_remote_runner.py
Labels: approved, cla: yes, lgtm, size/L

#5636 chore(v2): added mlmd error logging
  v2/component/launcher.go
Labels: approved, cla: yes, lgtm, size/XS

#5604 feat(sdk.v2): Experimental custom job support.
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_custom_job_spec.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_custom_job_spec.py
  sdk/python/kfp/v2/google/aiplatform.py
  sdk/python/kfp/v2/google/aiplatform_e2e_test.py
  sdk/python/kfp/v2/google/aiplatform_test.py
  sdk/python/kfp/v2/google/experimental/__init__.py
  sdk/python/kfp/v2/google/experimental/custom_job.py
  sdk/python/kfp/v2/google/experimental/custom_job_test.py
  sdk/python/kfp/v2/google/testdata/expected_custom_job_pipeline.json
  sdk/python/setup.py
Labels: approved, cla: yes, lgtm, size/XXL

#5632 feat(sdk.v1): Add pipeline_root as an argument to client's public run methods.
  sdk/python/kfp/_client.py
Labels: approved, cla: yes, lgtm, size/M

#5639 test: Update presubmit-tests-tfx.sh to run tests from src root.
  test/presubmit-tests-tfx.sh
Labels: approved, cla: yes, lgtm, size/M

#5637 feat(components/google-cloud): Support input type union[str,list[str]]
  components/google-cloud/google_cloud_pipeline_components/aiplatform/remote_runner.py
Labels: approved, cla: yes, lgtm, size/S

#5641 docs(components/google-cloud): updates Google Cloud Pipeline components readme.md
  components/google-cloud/README.md
Labels: approved, cla: yes, lgtm, size/L

#5629 feat(v2): added client side mlmd retry
  v2/go.mod
  v2/go.sum
  v2/metadata/client.go
Labels: approved, cla: yes, lgtm, size/M

#5599 Support extra params for cache server db connection
  backend/src/cache/client_manager.go
  backend/src/cache/main.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#5648 release(sdk): release SDK 1.6.0-rc.0
  sdk/python/kfp/compiler/testdata/v2_compatible_two_step_pipeline.yaml
  sdk/python/kfp/compiler/v2_compat.py
Labels: cla: yes, size/XS

#5649 chore(components): TFX components - Updated to v0.29.0
  components/deprecated/tfx/Evaluator/component.py
  components/deprecated/tfx/Evaluator/component.yaml
  components/deprecated/tfx/Evaluator/with_URI_IO/component.py
  components/deprecated/tfx/Evaluator/with_URI_IO/component.yaml
  components/deprecated/tfx/ExampleGen/BigQueryExampleGen/component.py
  components/deprecated/tfx/ExampleGen/BigQueryExampleGen/component.yaml
  components/deprecated/tfx/ExampleGen/BigQueryExampleGen/with_URI_IO/component.py
  components/deprecated/tfx/ExampleGen/BigQueryExampleGen/with_URI_IO/component.yaml
  components/deprecated/tfx/ExampleGen/CsvExampleGen/component.py
  components/deprecated/tfx/ExampleGen/CsvExampleGen/component.yaml
  components/deprecated/tfx/ExampleGen/CsvExampleGen/with_URI_IO/component.py
  components/deprecated/tfx/ExampleGen/CsvExampleGen/with_URI_IO/component.yaml
  components/deprecated/tfx/ExampleGen/ImportExampleGen/component.py
  components/deprecated/tfx/ExampleGen/ImportExampleGen/component.yaml
  components/deprecated/tfx/ExampleGen/ImportExampleGen/with_URI_IO/component.py
  components/deprecated/tfx/ExampleGen/ImportExampleGen/with_URI_IO/component.yaml
  components/deprecated/tfx/ExampleValidator/component.py
  components/deprecated/tfx/ExampleValidator/component.yaml
  components/deprecated/tfx/ExampleValidator/with_URI_IO/component.py
  components/deprecated/tfx/ExampleValidator/with_URI_IO/component.yaml
  components/deprecated/tfx/SchemaGen/component.py
  components/deprecated/tfx/SchemaGen/component.yaml
  components/deprecated/tfx/SchemaGen/with_URI_IO/component.py
  components/deprecated/tfx/SchemaGen/with_URI_IO/component.yaml
  components/deprecated/tfx/StatisticsGen/component.py
  components/deprecated/tfx/StatisticsGen/component.yaml
  components/deprecated/tfx/StatisticsGen/with_URI_IO/component.py
  components/deprecated/tfx/StatisticsGen/with_URI_IO/component.yaml
  components/deprecated/tfx/Trainer/component.py
  components/deprecated/tfx/Trainer/component.yaml
  components/deprecated/tfx/Trainer/with_URI_IO/component.py
  components/deprecated/tfx/Trainer/with_URI_IO/component.yaml
  components/deprecated/tfx/Transform/component.py
  components/deprecated/tfx/Transform/component.yaml
  components/deprecated/tfx/Transform/with_URI_IO/component.py
  components/deprecated/tfx/Transform/with_URI_IO/component.yaml
  components/deprecated/tfx/_samples/TFX_Dataflow_pipeline.ipynb
  components/deprecated/tfx/_samples/TFX_pipeline.ipynb
Labels: approved, area/components, cla: yes, lgtm, size/XXL

#5650 fix(cli): update client to allow equal signs('=') in parameters. Fixes #5577
  sdk/python/kfp/cli/run.py
Labels: approved, cla: yes, lgtm, size/XS

#5657 chore(v2/release): update licenses for kfp-launcher
  v2/go-mod-licenses.yaml
  v2/third_party/NOTICES/licenses.txt
  v2/third_party/license_info.csv
Labels: cla: yes, size/L

#5654 chore(sdk.v2): remove "task-" prefix
  sdk/python/kfp/dsl/component_spec.py
  sdk/python/kfp/dsl/component_spec_test.py
  sdk/python/kfp/dsl/dsl_utils.py
  sdk/python/kfp/dsl/dsl_utils_test.py
  sdk/python/kfp/dsl/importer_node_test.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_pipeline.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_with_outputs.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_after.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_concat_placeholder.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_condition.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_custom_job_spec.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_if_placeholder.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_importer.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loop_output.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loop_parameter.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loop_static.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loops_and_conditions.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_nested_conditions.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_nested_conditions_yaml.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_nested_loops.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_ontology.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_params_containing_format.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_resource_spec.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_reused_component.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_various_io_types.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/two_step_pipeline.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/xgboost_sample_pipeline.json
Labels: cla: yes, lgtm, size/XL

#5643 feat: adds v2 SDK compatible version of component
  components/web/Download/component-sdk-v2.yaml
Labels: approved, cla: yes, lgtm, size/S

#5662 test: pin google-cloud-bigquery to make TFX presubmit work
  test/presubmit-tests-tfx.sh
Labels: approved, cla: yes, lgtm, size/XS

#5661 feat(sdk): Type checking to treat "explicit" generic artifact as any artifact type.
  sdk/python/kfp/dsl/types.py
  sdk/python/kfp/v2/compiler/compiler_test.py
Labels: approved, cla: yes, lgtm, size/L

#5658 chore(sdk): warn v2 compatible mode is Beta quality
  sdk/python/kfp/compiler/compiler.py
Labels: approved, cla: yes, lgtm, size/XS

#5287 feat(sdk): Introduce the token credentials interface. Part of #4683
  sdk/python/kfp/__init__.py
  sdk/python/kfp/_client.py
  sdk/python/kfp/_credentials.py
Labels: approved, cla: yes, lgtm, size/M

#5645 chore(components/google-cloud): Create Release Branch for Google cloud pipeline components 0.1.0
  .readthedocs.yml
  components/google-cloud/RELEASE.md
  components/google-cloud/container/aiplatform/Dockerfile
  components/google-cloud/container/aiplatform/cloudbuild.yaml
  components/google-cloud/google_cloud_pipeline_components/aiplatform/utils.py
  components/google-cloud/google_cloud_pipeline_components/version.py
  components/google-cloud/setup.py
Labels: approved, cla: yes, lgtm, size/M

#5665 feat(sdk.v2): Support bool, dict, list, JsonObject, and JsonArray type as parameter types
  sdk/python/kfp/components/_data_passing.py
  sdk/python/kfp/components/executor.py
  sdk/python/kfp/dsl/type_utils.py
  sdk/python/kfp/dsl/type_utils_test.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_pipeline.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_pipeline.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_with_outputs.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_custom_job_spec.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_importer.json
Labels: approved, cla: yes, lgtm, size/XL

#5677 feat(sdk.v2): Add Google AIPlatformClient
  sdk/python/MANIFEST.in
  sdk/python/kfp/v2/google/client/__init__.py
  sdk/python/kfp/v2/google/client/_cloud_function_templated_http_request.py
  sdk/python/kfp/v2/google/client/_cloud_function_templated_http_request_test.py
  sdk/python/kfp/v2/google/client/client.py
  sdk/python/kfp/v2/google/client/client_test.py
  sdk/python/kfp/v2/google/client/client_utils.py
  sdk/python/kfp/v2/google/client/client_utils_test.py
  sdk/python/kfp/v2/google/client/discovery/aiplatform_public_google_rest_v1beta1.json
  sdk/python/kfp/v2/google/client/runtime_config_builder.py
  sdk/python/kfp/v2/google/client/runtime_config_builder_test.py
  sdk/python/kfp/v2/google/client/schedule.py
  sdk/python/kfp/v2/google/client/schedule_test.py
  sdk/python/kfp/v2/google/client/testdata/pipeline1.json
  sdk/python/kfp/v2/google/client/testdata/pipeline1_request_body.json
  sdk/python/kfp/v2/google/client/testdata/pipeline1_request_body_final.json
  sdk/python/kfp/v2/google/client/testdata/pipeline_job.json
  sdk/python/requirements-test.txt
  sdk/python/requirements.in
  sdk/python/requirements.txt
  sdk/python/setup.py
  test/presubmit-tests-sdk.sh
Labels: approved, cla: yes, lgtm, size/XXL

#5678 release(sdk): Release KFP SDK 1.6.0
  sdk/python/kfp/__init__.py
Labels: approved, cla: yes, lgtm, size/XS

#5679 release(sdk): release SDK 1.6.1 with minor fix in AIPlatformClient
  sdk/python/kfp/__init__.py
  sdk/python/kfp/v2/google/client/client.py
Labels: cla: yes, size/XS

#5642 fix(sdk): Update documentation for cron_expression parameter to kfp.Client().create_recurring_run
  sdk/python/kfp/_client.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#5647 Update IR documentations
  api/v2alpha1/pipeline_spec.proto
Labels: approved, cla: yes, lgtm, size/M

#5682 release: KFP SDK and v2 launcher 1.6.2
  sdk/python/kfp/__init__.py
  sdk/python/kfp/compiler/testdata/v2_compatible_two_step_pipeline.yaml
  sdk/python/kfp/compiler/v2_compat.py
Labels: approved, cla: yes, lgtm, size/XS

#5698 sample: Update xgboost_sample.py to make it compatible in both v1 and v2.
  samples/core/XGBoost/xgboost_sample.py
Labels: approved, cla: yes, lgtm, size/XS

#5695 Fix pipelines with Kubeflow profile quota
  manifests/kustomize/third-party/argo/base/workflow-controller-configmap-patch.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#5646 fix(frontend): Update the link text to the GCP CAIP Notebook
  frontend/src/pages/GettingStarted.tsx
  frontend/src/pages/__snapshots__/GettingStarted.test.tsx.snap
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#5699 fix(sdk.v2): fix a small bug in `io_types.is_artifact_annotation()`
  sdk/python/kfp/dsl/io_types.py
  sdk/python/kfp/dsl/io_types_test.py
  sdk/python/kfp/dsl/metrics_utils_test.py
  sdk/python/kfp/dsl/test_data/expected_bulk_loaded_confusion_matrix.json
  sdk/python/kfp/dsl/test_data/expected_confusion_matrix.json
  sdk/python/kfp/dsl/test_data/expected_io_types_bulk_load_classification_metrics.json
  sdk/python/kfp/dsl/test_data/expected_io_types_classification_metrics.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_pipeline.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_with_outputs.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_custom_job_spec.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_importer.json
  sdk/python/tests/dsl/test_data/expected_bulk_loaded_classification_metrics.json
  sdk/python/tests/dsl/test_data/expected_classification_metrics.json
  sdk/python/tests/dsl/test_data/expected_complete_artifact.json
  sdk/python/tests/dsl/test_data/expected_dataset_artifact.json
  sdk/python/tests/dsl/test_data/expected_metrics.json
  sdk/python/tests/dsl/test_data/expected_model_artifact.json
  sdk/python/tests/dsl/test_data/expected_sliced_classification_metrics.json
Labels: approved, cla: yes, lgtm, size/L

#5464 Backend - Added modern time formatters
  backend/src/common/util/parameter_formatter.go
  backend/src/common/util/parameter_formatter_test.go
  go.mod
  go.sum
Labels: approved, area/backend, cla: yes, lgtm, size/M

#5696 test(sdk): v2 compatible UT to ignore launcher image label
  sdk/python/kfp/compiler/testdata/v2_compatible_two_step_pipeline.yaml
  sdk/python/kfp/compiler/v2_compatible_compiler_test.py
Labels: approved, cla: yes, lgtm, size/S

#5644 fix(components): Web - Download data - Fixed the image which does not support volumes
  components/web/Download/component.yaml
Labels: approved, area/components, cla: yes, lgtm, size/XS

#5702 fix(components): replace resource name class with vertex ai
  components/google-cloud/dependencies.py
  components/google-cloud/google_cloud_pipeline_components/aiplatform/remote_runner.py
  components/google-cloud/google_cloud_pipeline_components/aiplatform/utils.py
  components/google-cloud/google_cloud_pipeline_components/version.py
  components/google-cloud/tests/aiplatform/test_componets_compile.py
  components/google-cloud/tests/aiplatform/test_remote_runner.py
  components/google-cloud/tests/aiplatform/test_utils.py
Labels: approved, cla: yes, lgtm, size/M

#5719 chore: Adding chensun in samples/OWNERS
  samples/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#5385 feat(samples): sample with kfp.dsl.RUN_ID_PLACEHOLDER. Part of #4700
  samples/core/use_run_info/use_run_id.py
  samples/core/use_run_info/use_run_id_test.py
  samples/test/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#5713 chore(components/google-cloud): Post release clean up tasks
  components/google-cloud/RELEASE.md
  components/google-cloud/google_cloud_pipeline_components/version.py
  components/google-cloud/setup.py
Labels: approved, cla: yes, lgtm, size/S

#5720 refactor: update pipeline names in samples/core dir. Fixes #5683
  samples/core/ai_platform/ai_platform.ipynb
  samples/core/container_build/container_build.ipynb
  samples/core/dataflow/dataflow.ipynb
  samples/core/dns_config/dns_config.py
  samples/core/dsl_static_type_checking/dsl_static_type_checking.ipynb
  samples/core/execution_order/execution_order.py
  samples/core/exit_handler/exit_handler.py
  samples/core/helloworld/hello_world.py
  samples/core/imagepullsecrets/imagepullsecrets.py
  samples/core/kfp_env_validation/kfp_env_validation.ipynb
  samples/core/kubeflow_tf_serving/kubeflow_tf_serving.ipynb
  samples/core/lightweight_component/lightweight_component.ipynb
  samples/core/multiple_outputs/multiple_outputs.ipynb
  samples/core/output_a_directory/output_a_directory.py
  samples/core/parallel_join/parallel_join.py
  samples/core/pipeline_parallelism/pipeline_parallelism_limits.py
  samples/core/pipeline_transformers/pipeline_transformers.py
  samples/core/preemptible_tpu_gpu/preemptible_tpu_gpu.py
  samples/core/recursion/recursion.py
  samples/core/resource_ops/resource_ops.py
  samples/core/retry/retry.py
  samples/core/secret/secret.py
  samples/core/sequential/sequential.py
  samples/core/sidecar/sidecar.py
  samples/core/volume_ops/volume_ops.py
  samples/core/volume_snapshot_ops/volume_snapshot_ops.py
  samples/core/xgboost_training_cm/xgboost_training_cm.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#5585 fix(frontend): Truncate large Markdown file to prevent UI crashing. Fix #5513
  frontend/src/components/viewers/MarkdownViewer.test.tsx
  frontend/src/components/viewers/MarkdownViewer.tsx
Labels: approved, cla: yes, lgtm, size/M

#5716 feat(sdk): special handling for type annotation using `typing.Optional`
  sdk/python/kfp/components/_data_passing.py
  sdk/python/kfp/components/_python_op.py
  sdk/python/kfp/components/type_annotation_utils.py
  sdk/python/kfp/components/type_annotation_utils_test.py
  sdk/python/kfp/components_tests/test_data_passing.py
  sdk/python/kfp/dsl/type_utils.py
  sdk/python/tests/dsl/component_tests.py
Labels: approved, cla: yes, lgtm, size/L

#5733 chore: Adding ji-yaqi to API & SDK OWNERS files, remove inactive members.
  api/OWNERS
  sdk/OWNERS
Labels: approved, cla: yes, lgtm, size/S

#5735 chore(components): AWS SageMaker update eks cluster version for tests
  components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests
Labels: approved, cla: yes, lgtm, size/XS

#5738 fix(backend): Fixed workflow cannot be retried with node xxx in Omitted
  backend/src/apiserver/resource/resource_manager_util.go
  backend/src/apiserver/resource/resource_manager_util_test.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M

#5734 chore(components/google-cloud): update readme with link to samples & api docs
  components/google-cloud/README.md
  components/google-cloud/examples/README.md
Labels: approved, cla: yes, lgtm, size/XS

#5701 fix(frontend): Remove alphabetical sorting of the metrics column. Fixes #5215
  frontend/src/components/Metric.tsx
  frontend/src/components/__snapshots__/Metric.test.tsx.snap
  frontend/src/lib/RunUtils.ts
  frontend/src/pages/RunList.test.tsx
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#5739 chore: restore KFP SDK version to 1.6.2, decouple SDK release from KFP main release.
  sdk/python/kfp/__init__.py
  test/release/bump-version-in-place.sh
Labels: approved, cla: yes, lgtm, size/XS

#5742 Fix the cache-deployer to run as non root
  backend/src/cache/deployer/Dockerfile
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#5721 fix(components/google-cloud): update version to include google-cloud-aiplatform fix
  components/google-cloud/dependencies.py
Labels: approved, cla: yes, lgtm, size/XS

#5712 chore(components/google-cloud): Create Release Branch for Google cloud pipeline components 0.1.1
  .readthedocs.yml
  components/google-cloud/RELEASE.md
  components/google-cloud/container/aiplatform/Dockerfile
  components/google-cloud/container/aiplatform/cloudbuild.yaml
  components/google-cloud/google_cloud_pipeline_components/aiplatform/utils.py
  components/google-cloud/google_cloud_pipeline_components/version.py
  components/google-cloud/setup.py
Labels: approved, cla: yes, lgtm, size/S

#5747 chore: Adding chensun in KFP root OWNERS
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#5752 fix(sdk.v2): Fix the bug where string concat inside a loop may break compilation.
  sdk/python/kfp/dsl/_component_bridge.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_params_containing_format.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_params_containing_format.py
Labels: approved, cla: yes, lgtm, size/L

#5740 fix(sdk): Avoid inserting duplicate input parameters in v2 compatible mode.
  sdk/python/kfp/compiler/compiler.py
Labels: approved, cla: yes, lgtm, size/S

#4611 feat(sdk): Dropped support for Python 3.5. Fixes #4584
  sdk/python/setup.py
Labels: approved, area/sdk, cla: yes, lgtm, size/XS

#5725 fix(cli): handle when pipeline.paramters is None
  sdk/python/kfp/cli/pipeline.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#5759 feat(sdk): Better error message when compiling for v2. Fixes #5688, Fixes #5727
  samples/core/exit_handler/exit_handler.py
  samples/core/loop_parameter/loop_parameter.py
  samples/core/loop_static/loop_static.py
  sdk/python/kfp/_config.py
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/compiler/v2_compatible_compiler_test.py
  sdk/python/kfp/dsl/_component_bridge.py
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/kfp/v2/compiler/compiler.py
  sdk/python/kfp/v2/compiler/compiler_test.py
Labels: approved, cla: yes, lgtm, size/L
