Repository kubeflow/pipelines, pull requests merged in 2021-04, with the labels that each got.

#5406 fix(deployment): Manifests fixes for KF 1.3
  manifests/kustomize/base/installs/multi-user/api-service/deployment-patch.yaml
  manifests/kustomize/base/installs/multi-user/pipelines-ui/deployment-patch.yaml
  manifests/kustomize/base/installs/multi-user/virtual-service.yaml
  manifests/kustomize/env/platform-agnostic-multi-user-legacy/kustomization.yaml
  manifests/kustomize/env/platform-agnostic-multi-user/kustomization.yaml
  manifests/kustomize/third-party/argo/upstream/manifests/cluster-install/workflow-controller-rbac/kustomization.yaml
  manifests/kustomize/third-party/metacontroller/base/cluster-role-binding.yaml
  manifests/kustomize/third-party/metacontroller/base/crd.yaml
  manifests/kustomize/third-party/metacontroller/base/kustomization.yaml
  manifests/kustomize/third-party/metacontroller/base/service-account.yaml
  manifests/kustomize/third-party/metacontroller/base/stateful-set.yaml
Labels: approved, cla: yes, lgtm, size/L

#5407 fix(deployment): pipelines profile controller uses pipelines.kubeflow.org/enabled label
  manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/sync.py
Labels: cla: yes, size/S

#5410 chore(release): fix metadata release script and add presubmit
  .cloudbuild.yaml
  .release.cloudbuild.yaml
  manifests/kustomize/base/metadata/base/metadata-grpc-deployment.yaml
  manifests/kustomize/hack/format.sh
  manifests/kustomize/hack/presubmit.sh
  manifests/kustomize/hack/release.sh
  test/tag_for_hosted.sh
Labels: cla: yes, size/S

#5409 fix(deployment): fix default resource requests. Fixes #5148
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/argo.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/mysql.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/pipeline.yaml
  manifests/gcp_marketplace/test/snapshot-base.yaml
  manifests/gcp_marketplace/test/snapshot-managed-storage-with-db-prefix.yaml
  manifests/gcp_marketplace/test/snapshot-managed-storage.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-visualization-deployment.yaml
  manifests/kustomize/third-party/argo/base/workflow-controller-deployment-patch.yaml
  manifests/kustomize/third-party/minio/minio-deployment.yaml
  manifests/kustomize/third-party/mysql/mysql-deployment.yaml
  test/presubmit-tests-mkp.sh
Labels: approved, cla: yes, lgtm, size/M

#5412 fix(sdk): Support returning plain tuples in lightweight function components v2.
  sdk/python/kfp/components/executor.py
  sdk/python/kfp/components/executor_test.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_pipeline.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_with_outputs.json
Labels: approved, cla: yes, lgtm, size/XL

#5419 fix(sdk.v2): fix bug for component input parameter/artifact referencing
  sdk/python/kfp/dsl/component_spec.py
  sdk/python/kfp/dsl/component_spec_test.py
  sdk/python/kfp/v2/compiler/compiler.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_condition.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_condition.py
Labels: approved, cla: yes, lgtm, size/L

#5417 metadata-writer: Fix multi-user mode
  backend/metadata_writer/src/metadata_writer.py
Labels: approved, cla: yes, lgtm, size/S

#5416 fix(manifests): Multi-User manifests fixes for 1.3
  manifests/kustomize/base/installs/multi-user/istio-authorization-config.yaml
  manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/deployment.yaml
  manifests/kustomize/base/metadata/base/kustomization.yaml
  manifests/kustomize/base/metadata/base/metadata-envoy-deployment.yaml
  manifests/kustomize/base/metadata/base/metadata-grpc-deployment.yaml
  manifests/kustomize/base/metadata/base/metadata-grpc-sa.yaml
  manifests/kustomize/env/platform-agnostic-multi-user-legacy/kustomization.yaml
  manifests/kustomize/env/platform-agnostic-multi-user/kustomization.yaml
  manifests/kustomize/env/platform-agnostic/kustomization.yaml
  manifests/kustomize/third-party/minio/base/kustomization.yaml
  manifests/kustomize/third-party/minio/base/minio-deployment.yaml
  manifests/kustomize/third-party/minio/base/minio-pvc.yaml
  manifests/kustomize/third-party/minio/base/minio-service.yaml
  manifests/kustomize/third-party/minio/base/mlpipeline-minio-artifact-secret.yaml
  manifests/kustomize/third-party/minio/options/istio/istio-authorization-policy.yaml
  manifests/kustomize/third-party/minio/options/istio/kustomization.yaml
  manifests/kustomize/third-party/mysql/base/kustomization.yaml
  manifests/kustomize/third-party/mysql/base/mysql-deployment.yaml
  manifests/kustomize/third-party/mysql/base/mysql-pv-claim.yaml
  manifests/kustomize/third-party/mysql/base/mysql-service.yaml
  manifests/kustomize/third-party/mysql/base/mysql-serviceaccount.yaml
  manifests/kustomize/third-party/mysql/options/istio/istio-authorization-policy.yaml
  manifests/kustomize/third-party/mysql/options/istio/kustomization.yaml
Labels: approved, cla: yes, lgtm, size/L

#5418 fix(frontend): Avoid crashing, and show error message for invalid trigger date/time format. Fixes #5350
  frontend/src/components/Trigger.test.tsx
  frontend/src/components/Trigger.tsx
  frontend/src/components/__snapshots__/Trigger.test.tsx.snap
Labels: cla: yes, size/L

#5420 feat(deployment): Allow traffic to the API-Server if the identity header is not set
  manifests/kustomize/base/installs/multi-user/istio-authorization-config.yaml
Labels: cla: yes, size/XS

#5421 fix(sdk): Always create output paths for parameters in addition to artifacts in v2 Python components.
  sdk/python/kfp/components/executor.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_pipeline.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_with_outputs.json
  sdk/python/kfp/v2/dsl/__init__.py
Labels: approved, cla: yes, lgtm, size/L

#5395 test: refactor v2 sample test, move test samples to samples/test folder
  samples/test/README.md
  samples/test/config.yaml
  samples/test/fail.py
  samples/test/fail_test.py
  samples/test/two_step.py
  samples/test/two_step_test.py
  samples/test/util.py
  v2/test/README.md
  v2/test/components/run_sample.yaml
  v2/test/requirements.txt
  v2/test/sample_test.py
  v2/test/samples/README.md
  v2/test/samples/fail_test.py
  v2/test/samples/two_step_test.py
Labels: approved, cla: yes, lgtm, size/L

#5424 fix(backend): api server panics on workflow with parameter without value. Fixes #5423
  backend/src/common/util/workflow.go
  backend/src/common/util/workflow_test.go
Labels: approved, cla: yes, lgtm, size/L

#5326 chore(components): Fix typos in Great Expectations component
  components/great-expectations/validate/CSV/component.py
  components/great-expectations/validate/CSV/component.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#5365 feat(sdk/extensions): Add kfp.onprem.use_k8s_secret method that puts k8s secrets in env vars
  sdk/python/kfp/onprem.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#5391 components: Add package structure and base files for Google Cloud Components and Model builder SDK components
  components/google-cloud/OWNERS
  components/google-cloud/aiplatform/container/aiplatform/Dockerfile
  components/google-cloud/aiplatform/container/aiplatform/cloud_build.yaml
  components/google-cloud/aiplatform/examples/README.md
  components/google-cloud/aiplatform/sdk/LICENSE
  components/google-cloud/aiplatform/sdk/README.md
  components/google-cloud/aiplatform/sdk/dependencies.py
  components/google-cloud/aiplatform/sdk/google_cloud_components/__init__.py
  components/google-cloud/aiplatform/sdk/google_cloud_components/aiplatform/__init__.py
  components/google-cloud/aiplatform/sdk/google_cloud_components/aiplatform/remote_runner.py
  components/google-cloud/aiplatform/sdk/google_cloud_components/aiplatform/utils.py
  components/google-cloud/aiplatform/sdk/google_cloud_components/version.py
  components/google-cloud/aiplatform/sdk/setup.cfg
  components/google-cloud/aiplatform/sdk/setup.py
  components/google-cloud/aiplatform/sdk/tests/README.md
  components/google-cloud/src/google_cloud_components/__init__.py
Labels: approved, cla: yes, lgtm, size/XL

#4937 fix(components): Delete unused to_table component item
  components/gcp/bigquery/query/to_table/component.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#5250 fix(components): add bypass for BrokenPipeError in gcp ml engine client. Fixes #5085
  components/gcp/container/component_sdk/python/kfp_component/google/ml_engine/_client.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#5408 feat(frontend): Shorten output names
  frontend/src/lib/WorkflowParser.test.ts
  frontend/src/lib/WorkflowParser.ts
Labels: approved, area/frontend, cla: yes, lgtm, size/M

#5428 components: flattening the components/google-cloud/ sdk structure
  components/google-cloud/LICENSE
  components/google-cloud/README.md
  components/google-cloud/aiplatform/sdk/google_cloud_components/__init__.py
  components/google-cloud/container/aiplatform/Dockerfile
  components/google-cloud/container/aiplatform/cloud_build.yaml
  components/google-cloud/dependencies.py
  components/google-cloud/examples/README.md
  components/google-cloud/google_cloud_components/__init__.py
  components/google-cloud/google_cloud_components/aiplatform/__init__.py
  components/google-cloud/google_cloud_components/aiplatform/remote_runner.py
  components/google-cloud/google_cloud_components/aiplatform/utils.py
  components/google-cloud/google_cloud_components/version.py
  components/google-cloud/setup.cfg
  components/google-cloud/setup.py
  components/google-cloud/tests/README.md
Labels: approved, cla: yes, lgtm, size/S

#5430 feat(sdk.v2): use consistent argument name in v2 compiler
  sdk/python/kfp/v2/compiler/compiler.py
  sdk/python/kfp/v2/compiler/compiler_test.py
  sdk/python/kfp/v2/compiler/main.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_pipeline.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_with_outputs.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_after.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_concat_placeholder.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_condition.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_if_placeholder.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loop_output.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loop_parameter.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loop_static.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_nested_conditions.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_nested_conditions_yaml.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_ontology.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_params_containing_format.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_resource_spec.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_reused_component.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_various_io_types.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/simple_pipeline_without_importer.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/two_step_pipeline_with_importer.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/xgboost_sample_pipeline.py
Labels: approved, cla: yes, lgtm, size/M

#5437 chore(components): AWS SageMaker tests enable ssm on eks worker nodes
  components/aws/sagemaker/tests/integration_tests/Dockerfile
  components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests
Labels: approved, cla: yes, lgtm, size/XS

#5432 test: v2 sample test supports multiple test cases & internal endpoint
  samples/test/fail_test.py
  samples/test/two_step_test.py
  samples/test/util.py
  v2/test/Dockerfile
  v2/test/components/run_sample.yaml
  v2/test/sample_test.py
Labels: approved, cla: yes, lgtm, size/L

#5397 chore(components): Added request timeout to KFServing component
  components/kubeflow/kfserving/component.yaml
  components/kubeflow/kfserving/src/kfservingdeployer.py
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#5386 chore(components): Update README and reduce output size of KFServing component
  components/kubeflow/kfserving/README.md
  components/kubeflow/kfserving/src/kfservingdeployer.py
Labels: approved, cla: yes, lgtm, size/S

#5448 test(components): google-cloud-components - Add package build and load to presubmit tests
  components/google-cloud/dependencies.py
  components/google-cloud/tests/presubmit.sh
  components/google-cloud/tests/run_test.sh
Labels: approved, cla: yes, lgtm, size/S

#5379 chore(sdk): Refactored command-line resolving
  sdk/python/kfp/compiler/_data_passing_rewriter.py
  sdk/python/kfp/components/_components.py
  sdk/python/kfp/components_tests/test_components.py
  sdk/python/kfp/dsl/_component_bridge.py
  sdk/python/tests/dsl/component_bridge_tests.py
Labels: approved, area/sdk, cla: yes, lgtm, size/XL

#5442 feat(google_cloud_components sdk): Enable support for all components
  components/google-cloud/container/aiplatform/Dockerfile
  components/google-cloud/container/aiplatform/cloud_build.yaml
  components/google-cloud/container/aiplatform/cloudbuild.yaml
  components/google-cloud/dependencies.py
  components/google-cloud/google_cloud_components/aiplatform/__init__.py
  components/google-cloud/google_cloud_components/aiplatform/remote_runner.py
  components/google-cloud/google_cloud_components/aiplatform/utils.py
Labels: approved, cla: yes, lgtm, size/XL

#5445 feat(sdk.v2): surface metrics output artifacts to pipeline outputs
  sdk/python/kfp/dsl/artifact.py
  sdk/python/kfp/dsl/component_spec.py
  sdk/python/kfp/dsl/type_schemas/classification_metrics.yaml
  sdk/python/kfp/dsl/type_schemas/metrics.yaml
  sdk/python/kfp/dsl/type_utils.py
  sdk/python/kfp/dsl/type_utils_test.py
  sdk/python/kfp/v2/compiler/compiler.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_pipeline.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_pipeline.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_with_outputs.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_various_io_types.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_various_io_types.py
  sdk/python/tests/dsl/test_data/expected_bulk_loaded_classification_metrics.json
  sdk/python/tests/dsl/test_data/expected_classification_metrics.json
  sdk/python/tests/dsl/test_data/expected_metrics.json
Labels: approved, cla: yes, lgtm, size/XXL

#5454 feat(sdk.v2): Support setting custom job spec in v2.
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/dsl/_container_op.py
  sdk/python/kfp/v2/compiler/compiler.py
  sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_custom_job_spec.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_custom_job_spec.py
  sdk/python/kfp/v2/google/aiplatform.py
  sdk/python/kfp/v2/google/aiplatform_test.py
  sdk/python/kfp/v2/google/testdata/expected_custom_job_pipeline.json
Labels: approved, cla: yes, lgtm, size/L

#5451 chore(release): instructions for docker.sock: permission denied resolution
  RELEASE.md
Labels: cla: yes, size/XS

#5465 components: google-cloud-sdk - Updates based on changes to aiplatform.Datasets
  components/google-cloud/google_cloud_components/aiplatform/__init__.py
  components/google-cloud/google_cloud_components/aiplatform/remote_runner.py
  components/google-cloud/google_cloud_components/aiplatform/utils.py
Labels: approved, cla: yes, lgtm, size/L

#5459 components: google-cloud-sdk - Add build and install instructions in readme
  components/google-cloud/README.md
Labels: approved, cla: yes, lgtm, size/M

#5463 Fixes the Confusion Matrix storage format
  sdk/python/kfp/dsl/io_types.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_pipeline.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_with_outputs.json
  sdk/python/tests/dsl/io_types_test.py
  sdk/python/tests/dsl/test_data/expected_io_types_bulk_load_classification_metrics.json
  sdk/python/tests/dsl/test_data/expected_io_types_classification_metrics.json
Labels: approved, cla: yes, lgtm, size/XL

#5469 Use artifacts for resource name
  components/google-cloud/container/aiplatform/Dockerfile
  components/google-cloud/google_cloud_components/aiplatform/remote_runner.py
  components/google-cloud/google_cloud_components/aiplatform/utils.py
Labels: approved, cla: yes, lgtm, size/L

#5477 test: fix presubmit kubeflow-pipelines-tfx-python36
  test/presubmit-tests-tfx.sh
Labels: approved, cla: yes, lgtm, size/XS

#5479 test(frontend): Resolve locale issue in tests from machine other than US. Fix #5457
  frontend/package.json
Labels: approved, cla: yes, lgtm, size/XS

#5487 components: (google-cloud-sdk) Add supported OP names and description to readme.
  components/google-cloud/README.md
  components/google-cloud/google_cloud_components/aiplatform/__init__.py
Labels: approved, cla: yes, lgtm, size/M

#5481 components: (google-cloud-sdk) Updated the docstring to match the op method signature.
  components/google-cloud/google_cloud_components/aiplatform/utils.py
Labels: approved, cla: yes, lgtm, size/L

#5489 components: (google-cloud-sdk) Fix artifact FileNotFoundError
  components/google-cloud/google_cloud_components/aiplatform/remote_runner.py
Labels: approved, cla: yes, lgtm, size/XS

#5488 fix: pass in class directly
  components/google-cloud/google_cloud_components/aiplatform/__init__.py
  components/google-cloud/google_cloud_components/aiplatform/utils.py
Labels: approved, cla: yes, lgtm, size/M

#5458 feat(v2): Support v2 components in KFP v2-compatible mode.
  samples/test/config.yaml
  samples/test/lightweight_python_functions_v2_pipeline_test.py
  samples/test/lightweight_python_functions_v2_with_outputs_test.py
  samples/test/placeholder_concat.py
  samples/test/placeholder_concat_test.py
  sdk/python/kfp/compiler/_op_to_template.py
  sdk/python/kfp/compiler/testdata/v2_compatible_two_step_pipeline.yaml
  sdk/python/kfp/compiler/testdata/v2_compatible_two_step_pipeline_with_custom_launcher.yaml
  sdk/python/kfp/compiler/v2_compat.py
  sdk/python/kfp/dsl/_container_op.py
  v2/component/launcher.go
  v2/component/runtime_info.go
  v2/component/runtime_info_test.go
  v2/metadata/client.go
  v2/third_party/pipeline_spec/pipeline_spec.pb.go
Labels: approved, cla: yes, lgtm, size/XXL

#5472 chore(sdk.v2): Deprecate dsl.ontology_artifacts, and migrate to using dsl.io_types
  sdk/python/kfp/compiler/testdata/v2_compatible_two_step_pipeline.yaml
  sdk/python/kfp/compiler/testdata/v2_compatible_two_step_pipeline_with_custom_launcher.yaml
  sdk/python/kfp/containers_tests/entrypoint_test.py
  sdk/python/kfp/containers_tests/entrypoint_utils_test.py
  sdk/python/kfp/dsl/component_spec.py
  sdk/python/kfp/dsl/component_spec_test.py
  sdk/python/kfp/dsl/importer_node.py
  sdk/python/kfp/dsl/importer_node_test.py
  sdk/python/kfp/dsl/io_types.py
  sdk/python/kfp/dsl/ontology_artifacts.py
  sdk/python/kfp/dsl/type_schemas/confidence_metrics.yaml
  sdk/python/kfp/dsl/type_schemas/confusion_matrix.yaml
  sdk/python/kfp/dsl/type_schemas/dataset.yaml
  sdk/python/kfp/dsl/type_schemas/model.yaml
  sdk/python/kfp/dsl/type_schemas/sliced_classification_metrics.yaml
  sdk/python/kfp/dsl/type_utils.py
  sdk/python/kfp/dsl/type_utils_test.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_pipeline.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_with_outputs.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_ontology.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_resource_spec.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_various_io_types.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/simple_pipeline_without_importer.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/two_step_pipeline_with_importer.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/xgboost_sample_pipeline.json
  sdk/python/kfp/v2/google/aiplatform.py
  sdk/python/kfp/v2/google/aiplatform_test.py
  sdk/python/kfp/v2/google/testdata/expected_custom_job_pipeline.json
  sdk/python/tests/dsl/artifact_test.py
Labels: approved, cla: yes, lgtm, size/XXL

#5494 fix(sdk): Minor API fixes to Metrics classes.
  sdk/python/kfp/dsl/io_types.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_pipeline.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_with_outputs.json
  sdk/python/tests/dsl/io_types_test.py
Labels: approved, cla: yes, lgtm, size/XL

#5491 chore(components): Update XGBoost predict components output type.
  components/XGBoost/Predict/component.py
  components/XGBoost/Predict/component.yaml
  components/XGBoost/Predict/from_ApacheParquet/component.py
  components/XGBoost/Predict/from_ApacheParquet/component.yaml
Labels: approved, cla: yes, lgtm, size/XS

#5492 feat(sdk.v2): remove pipeline_root from compiler interface
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/dsl/_pipeline.py
  sdk/python/kfp/v2/compiler/compiler.py
  sdk/python/kfp/v2/compiler/compiler_test.py
  sdk/python/kfp/v2/compiler/main.py
  sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_pipeline.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_with_outputs.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_after.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_concat_placeholder.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_condition.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_custom_job_spec.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_if_placeholder.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_nested_conditions.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_nested_conditions_yaml.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_ontology.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_params_containing_format.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_resource_spec.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_reused_component.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_various_io_types.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/simple_pipeline_without_importer.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/two_step_pipeline_with_importer.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/xgboost_sample_pipeline.py
Labels: approved, cla: yes, lgtm, size/L

#5497 [google-cloud-components sdk] casting on remote runner
  components/google-cloud/google_cloud_components/aiplatform/remote_runner.py
Labels: approved, cla: yes, lgtm, size/M

#5498 [google-cloud-components] add encryption key support
  components/google-cloud/google_cloud_components/aiplatform/utils.py
Labels: approved, cla: yes, lgtm, size/XS

#5482 chore(frontend): fix import class mismatch. Fixes #5444
  frontend/mock-backend/mock-api-middleware.ts
  frontend/server/src/generated/apis/auth/api.ts
  frontend/src/apis/experiment/api.ts
  frontend/src/apis/job/api.ts
  frontend/src/apis/pipeline/api.ts
  frontend/src/apis/run/api.ts
  frontend/src/apis/visualization/api.ts
  frontend/src/components/ExperimentList.test.tsx
  frontend/src/components/ExperimentList.tsx
  frontend/src/pages/AllRunsList.test.tsx
  frontend/src/pages/AllRunsList.tsx
  frontend/src/pages/ArchivedExperiments.test.tsx
  frontend/src/pages/ArchivedExperiments.tsx
  frontend/src/pages/ArchivedRuns.test.tsx
  frontend/src/pages/ArchivedRuns.tsx
  frontend/src/pages/ExperimentDetails.test.tsx
  frontend/src/pages/ExperimentDetails.tsx
  frontend/src/pages/ExperimentList.test.tsx
  frontend/src/pages/ExperimentList.tsx
  frontend/src/pages/NewRun.test.tsx
  frontend/src/pages/NewRun.tsx
  frontend/src/pages/RunDetails.test.tsx
  frontend/src/pages/RunDetails.tsx
  frontend/src/pages/RunList.test.tsx
  frontend/src/pages/RunList.tsx
  frontend/src/pages/RunListsRouter.test.tsx
  frontend/src/pages/RunListsRouter.tsx
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#5043 feat(sdk): Introduce new environment variables for kfp oauth2 clients
  sdk/python/kfp/_client.py
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#5502 feat(sdk.v2): Support explicit importer
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/dsl/__init__.py
  sdk/python/kfp/dsl/_component_bridge.py
  sdk/python/kfp/dsl/importer_node.py
  sdk/python/kfp/dsl/importer_node_test.py
  sdk/python/kfp/dsl/type_utils.py
  sdk/python/kfp/v2/compiler/compiler.py
  sdk/python/kfp/v2/compiler/compiler_test.py
  sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_importer.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_importer.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_various_io_types.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_various_io_types.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/two_step_pipeline.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/two_step_pipeline.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/two_step_pipeline_with_importer.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/two_step_pipeline_with_importer.py
Labels: approved, cla: yes, lgtm, size/XXL

#5486 test(v2/samples): verify sample mlmd state
  samples/core/resource_spec/resource_spec_test.py
  samples/test/fail_parameter_value_missing_test.py
  samples/test/fail_test.py
  samples/test/legacy_exit_handler_test.py
  samples/test/lightweight_python_functions_v2_pipeline_test.py
  samples/test/lightweight_python_functions_v2_with_outputs_test.py
  samples/test/parameter_with_format_test.py
  samples/test/placeholder_concat_test.py
  samples/test/reused_component_test.py
  samples/test/simple_pipeline_without_importer_test.py
  samples/test/two_step.py
  samples/test/two_step_test.py
  samples/test/util.py
  samples/test/various_io_types_test.py
  v2/test/Dockerfile
  v2/test/Makefile
  v2/test/README.md
  v2/test/requirements.txt
Labels: approved, cla: yes, lgtm, size/L

#5499 [google-cloud-components] - update metadata for output
  components/google-cloud/google_cloud_components/aiplatform/remote_runner.py
  components/google-cloud/google_cloud_components/aiplatform/utils.py
Labels: approved, cla: yes, lgtm, size/M

#5392 chore(v2): added minio and s3 pipeline root support in v2 launcher
  samples/test/two_step_test.py
  sdk/python/kfp/compiler/_default_transformers.py
  v2/cmd/launch/main.go
  v2/component/launcher.go
  v2/component/launcher_test.go
  v2/go.mod
  v2/go.sum
  v2/launcher_container/Dockerfile
Labels: approved, cla: yes, lgtm, size/L

#5514 [google-cloud-components] - change name to google-cloud-pipeline-components
  components/google-cloud/OWNERS
  components/google-cloud/README.md
  components/google-cloud/container/aiplatform/Dockerfile
  components/google-cloud/dependencies.py
  components/google-cloud/google_cloud_pipeline_components/__init__.py
  components/google-cloud/google_cloud_pipeline_components/aiplatform/__init__.py
  components/google-cloud/google_cloud_pipeline_components/aiplatform/remote_runner.py
  components/google-cloud/google_cloud_pipeline_components/aiplatform/utils.py
  components/google-cloud/google_cloud_pipeline_components/version.py
  components/google-cloud/setup.py
  components/google-cloud/tests/__init__.py
  components/google-cloud/tests/aiplatform/__init__.py
  components/google-cloud/tests/presubmit.sh
Labels: approved, cla: yes, lgtm, size/M

#5455 DOCS url 404
  components/deprecated/tfx/ExampleValidator/component.py
  components/deprecated/tfx/ExampleValidator/component.yaml
Labels: approved, cla: yes, lgtm, size/S

#5520 test(components/google-cloud): Unit test for remote_runner module
  components/google-cloud/tests/aiplatform/test_remote_runner.py
  components/google-cloud/tests/aiplatform/test_utils.py
  components/google-cloud/tests/presubmit.sh
Labels: approved, cla: yes, lgtm, size/L

#5528 chore(components/google-cloud): update python-aiplatform dependency to pypi
  components/google-cloud/container/aiplatform/Dockerfile
  components/google-cloud/dependencies.py
Labels: approved, cla: yes, lgtm, size/XS

#5523 test(components/google-cloud): Add Unit tests for utils method
  components/google-cloud/google_cloud_pipeline_components/aiplatform/utils.py
  components/google-cloud/tests/aiplatform/test_utils.py
Labels: approved, cla: yes, lgtm, size/L

#5525 chore: remove cherry pick process from pull request template
  .github/pull_request_template.md
Labels: approved, cla: yes, lgtm, size/XS

#5517 chore(v2): use k8s client to get minio credential and record aws region in mlmd …
  v2/component/launcher.go
  v2/component/runtime_info.go
  v2/go.mod
  v2/go.sum
Labels: approved, cla: yes, lgtm, size/L

#5530 test(components/google-cloud): Add code coverage to presubmit tests.
  components/google-cloud/tox.ini
Labels: approved, cla: yes, lgtm, size/S

#5516 fix(sdk.v2): Fix loop subvar support and remove redundant loop iterator component.
  sdk/python/kfp/dsl/component_spec.py
  sdk/python/kfp/v2/compiler/compiler.py
  sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loop_output.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loop_parameter.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loop_static.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loops_and_conditions.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loops_and_conditions.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_nested_loops.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_nested_loops.py
Labels: approved, cla: yes, lgtm, size/XXL

#5527 chore(sdk.v2): Remove warning on missing pipeline root at compile time
  sdk/python/kfp/v2/compiler/compiler.py
  sdk/python/kfp/v2/compiler/compiler_test.py
Labels: approved, cla: yes, lgtm, size/S

#5532 fix(components): Update types for GCS components so it's compatible with v2.
  components/google-cloud/storage/download/component.yaml
  components/google-cloud/storage/download_blob/component.yaml
  components/google-cloud/storage/download_dir/component.yaml
  components/google-cloud/storage/list/component.yaml
  components/google-cloud/storage/upload_to_explicit_uri/component.yaml
  components/google-cloud/storage/upload_to_unique_uri/component.yaml
Labels: approved, cla: yes, lgtm, size/S

#5531 test(components/google-cloud): Add presubmit tests for compiling components
  components/google-cloud/tests/aiplatform/test_componets_compile.py
  components/google-cloud/tox.ini
Labels: approved, cla: yes, lgtm, size/L

#5456 feat(cache) : allow user to reset the node selector and affinity for cached steps. Fixes #4777
  backend/src/apiserver/config/config.json
  backend/src/cache/server/mutation.go
  backend/src/cache/server/mutation_test.go
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/cache.yaml
  manifests/gcp_marketplace/test/snapshot-base.yaml
  manifests/gcp_marketplace/test/snapshot-managed-storage-with-db-prefix.yaml
  manifests/kustomize/base/cache/cache-deployment.yaml
  manifests/kustomize/base/installs/generic/pipeline-install-config.yaml
Labels: approved, cla: yes, lgtm, size/M

#5522 fix(viewer): viewer crd controller panics using tensorboard image without tag. Part of #5471
  backend/src/crd/controller/viewer/reconciler/reconciler.go
  backend/src/crd/controller/viewer/reconciler/reconciler_test.go
Labels: approved, cla: yes, lgtm, size/M

#5538 chore(sdk.v2): Sort compilation output json to make it deterministic.
  sdk/python/kfp/v2/compiler/compiler.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_pipeline.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_with_outputs.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_after.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_concat_placeholder.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_condition.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_custom_job_spec.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_if_placeholder.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_importer.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loop_output.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loop_parameter.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loop_static.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_loops_and_conditions.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_nested_conditions.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_nested_conditions_yaml.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_nested_loops.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_ontology.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_params_containing_format.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_resource_spec.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_reused_component.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_various_io_types.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/two_step_pipeline.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/xgboost_sample_pipeline.json
Labels: approved, cla: yes, lgtm, size/XXL

#5536 feat(components/google-cloud): Use Kaniko for image build
  components/google-cloud/container/aiplatform/cloudbuild.yaml
Labels: approved, cla: yes, lgtm, size/XS

#5550 feat(components/google-cloud): Add version to package root
  components/google-cloud/google_cloud_pipeline_components/__init__.py
Labels: approved, cla: yes, lgtm, size/XS

#5546 chore(v2/launcher): fix race condition that causes intermittent AlreadyExists error
  v2/Makefile
  v2/go.mod
  v2/metadata/client.go
  v2/metadata/client_test.go
Labels: cla: yes, size/L

#5549 fix(sdk): Fix bug where empty string was not preserved as pipeline param default value.
  sdk/python/kfp/dsl/_pipeline_param.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_various_io_types.json
Labels: approved, cla: yes, lgtm, size/S

#5551 chore(sdk.v2): block recursive subgroup in v2.
  sdk/python/kfp/v2/compiler/compiler.py
Labels: approved, cla: yes, lgtm, size/XS

#5562 test: increase sample test timeout wait time.
  samples/test/util.py
  v2/test/sample_test.py
Labels: approved, cla: yes, lgtm, size/XS

#5563 test: add backoff retry to kfp api call
  samples/test/util.py
Labels: approved, cla: yes, lgtm, size/M

#5561 chore(sample): Update loop_parameter.py sample so it's compatible in both v1 and v2
  samples/core/loop_parameter/loop_parameter.py
  samples/core/loop_parameter/loop_parameter_test.py
Labels: approved, cla: yes, lgtm, size/M

#5557 feat(sdk.v2): Raise error on artifacts vs. parameters mismatch in v2.
  sdk/python/kfp/dsl/_component_bridge.py
  sdk/python/kfp/v2/compiler/compiler.py
  sdk/python/kfp/v2/compiler/compiler_test.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_various_io_types.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_various_io_types.py
Labels: approved, cla: yes, lgtm, size/L

#5566 chore(sdk.v2):add v2 compact metrics label
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/compiler/v2_compat.py
Labels: approved, cla: yes, lgtm, size/XS

#5568 fix(sdk): Update syntax for lightweight components v2.
  samples/test/lightweight_python_functions_v2_pipeline.py
  samples/test/lightweight_python_functions_v2_with_outputs.py
  sdk/python/kfp/components/_python_op.py
  sdk/python/kfp/components/executor.py
  sdk/python/kfp/components/executor_test.py
  sdk/python/kfp/dsl/io_types.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_pipeline.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_pipeline.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_with_outputs.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_with_outputs.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_importer.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_importer.py
  sdk/python/kfp/v2/dsl/__init__.py
  sdk/python/kfp/v2/dsl/component_decorator.py
  sdk/python/tests/dsl/io_types_test.py
Labels: approved, cla: yes, lgtm, size/L

#5567 chore(v2): add name as custom property of MLMD artifacts
  samples/test/two_step_test.py
  samples/test/util.py
  v2/component/runtime_info.go
  v2/component/runtime_info_test.go
Labels: approved, cla: yes, lgtm, size/L

#5574 fix(sdk): Fix a bug with creating dirname for parameter files in v2 lightweight components
  sdk/python/kfp/components/executor.py
  sdk/python/kfp/components/executor_test.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_pipeline.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/lightweight_python_functions_v2_with_outputs.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_importer.json
Labels: approved, cla: yes, lgtm, size/S

#5570 Add zijianjoy to frontend/OWNERS
  frontend/OWNERS
Labels: approved, cla: yes, lgtm, size/XS
