Repository kubeflow/pipelines, pull requests merged in 2022-06, with the labels that each got.

#7785 fix(test): Make exit handler test install KFP SDK from source
  samples/core/exit_handler/exit_handler_v2.py
Labels: lgtm, approved, size/XS

#7765 fix(sdk): fix load v1 if present placeholder
  sdk/python/kfp/components/structures.py
  sdk/python/kfp/components/structures_test.py
Labels: lgtm, approved, size/M

#7814 chore(sdk): bump kfp version to 2.0.0a5
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
Labels: lgtm, approved, size/XS

#7825 chore(sdk): use markdown for long description content type
  sdk/python/setup.py
Labels: lgtm, approved, size/XS

#7833 fix(frontend): Fix run comparison filter
  frontend/src/pages/RunList.test.tsx
  frontend/src/pages/RunList.tsx
Labels: lgtm, approved, size/M

#7847 fix(frontend) Regenerate the Typescript client library from swagger to match the backend changes in #7788
  frontend/src/apis/job/api.ts
  frontend/src/apis/run/api.ts
  frontend/src/components/NewRunParametersV2.tsx
  frontend/src/pages/NewRunV2.tsx
Labels: lgtm, approved, size/L

#7772 chore: update source for aws samples input data
  samples/contrib/aws-samples/mnist-kmeans-sagemaker/README.md
  samples/contrib/aws-samples/simple_train_pipeline/README.md
Labels: lgtm, approved, size/M, ok-to-test

#7852 fix(manifests): Update snapshot to 2.0.0-alpha.2
  manifests/gcp_marketplace/test/snapshot-base.yaml
  manifests/gcp_marketplace/test/snapshot-emissary.yaml
  manifests/gcp_marketplace/test/snapshot-managed-storage-with-db-prefix.yaml
  manifests/gcp_marketplace/test/snapshot-managed-storage.yaml
Labels: lgtm, approved, size/XS

#7843 feat(backend): use cert-manager for cache server cert
  manifests/kustomize/env/cert-manager/base/cache-cert-issuer.yaml
  manifests/kustomize/env/cert-manager/base/cache-cert.yaml
  manifests/kustomize/env/cert-manager/base/cache-webhook-config.yaml
  manifests/kustomize/env/cert-manager/base/kustomization.yaml
  manifests/kustomize/env/cert-manager/base/params.yaml
  manifests/kustomize/env/cert-manager/cluster-scoped-resources/kustomization.yaml
  manifests/kustomize/env/cert-manager/dev/delete-cache-deployer.yaml
  manifests/kustomize/env/cert-manager/dev/kustomization.yaml
  manifests/kustomize/env/cert-manager/dev/namespace.yaml
  manifests/kustomize/env/cert-manager/dev/params.yaml
  manifests/kustomize/env/cert-manager/platform-agnostic-multi-user/delete-cache-deployer.yaml
  manifests/kustomize/env/cert-manager/platform-agnostic-multi-user/kustomization.yaml
Labels: lgtm, approved, size/L

#7868 chore(sdk): fix component compilation test path
  sdk/python/kfp/components/structures_test.py
Labels: lgtm, approved, size/XS

#7881 chore: Pin golang version in `backend/Dockerfile.viewercontroller`
  backend/Dockerfile.viewercontroller
Labels: lgtm, approved, size/XS

#7844 feat(frontend): Update compare page and banner states based on run versions and count
  frontend/src/pages/Compare.test.tsx
  frontend/src/pages/Compare.tsx
  frontend/src/pages/CompareV1.test.tsx
  frontend/src/pages/CompareV1.tsx
Labels: lgtm, approved, size/L

#7776 fix(components): Preserve empty features in explanation_spec
  components/google-cloud/google_cloud_pipeline_components/container/v1/gcp_launcher/upload_model_remote_runner.py
Labels: size/XS, needs-ok-to-test, ready to pull

#7870 chore(sdk): Support loading v1 yaml with {executorInput: } placeholder
  sdk/python/kfp/components/component_factory.py
  sdk/python/kfp/components/placeholders.py
  sdk/python/kfp/components/placeholders_test.py
  sdk/python/kfp/components/structures.py
  sdk/python/kfp/components/structures_test.py
Labels: approved, size/M

#7871 test: Skip loading yaml component with v1 graph syntax
  components/test_load_all_components.sh
Labels: lgtm, approved, size/S

#7876 fix(backend): "Started at", "Finished at" and "Duration" display error.
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/server/run_server_test.go
  backend/src/apiserver/storage/run_store.go
  frontend/src/pages/RunDetailsV2.tsx
Labels: area/frontend, lgtm, approved, size/L, area/backend

#7872 fix(frontend): Fix Run Comparison refresh button
  frontend/src/pages/CompareV1.tsx
Labels: lgtm, approved, size/XS

#7882 feat(frontend): Create sections and run list for KFPv2 Run Comparison page
  frontend/src/components/CollapseButtonSingle.test.tsx
  frontend/src/components/CollapseButtonSingle.tsx
  frontend/src/pages/Compare.test.tsx
  frontend/src/pages/Compare.tsx
  frontend/src/pages/CompareV1.test.tsx
  frontend/src/pages/CompareV1.tsx
  frontend/src/pages/CompareV2.test.tsx
  frontend/src/pages/CompareV2.tsx
Labels: lgtm, approved, size/XL

#7554 feat(sdk): enable component compilation via component decorator
  sdk/RELEASE.md
  sdk/python/kfp/components/component_decorator.py
  sdk/python/kfp/components/component_decorator_test.py
Labels: lgtm, approved, size/M

#7908 feat(kfp): implement config file support for registry client
  sdk/python/kfp/registry/context/__init__.py
  sdk/python/kfp/registry/context/kfp_pkg_dev.json
  sdk/python/kfp/registry/registry_client.py
  sdk/python/kfp/registry/registry_client_test.py
Labels: lgtm, size/L

#7768 fix(backend): change downloaded IR from JSON to YAML. Fixes #7673
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/server/pipeline_upload_server_test.go
  backend/src/apiserver/server/test/v2-hello-world.json
  backend/src/apiserver/template/template.go
  backend/src/apiserver/template/template_test.go
  backend/src/apiserver/template/v2_template.go
  backend/test/integration/pipeline_api_test.go
  backend/test/integration/pipeline_version_api_test.go
  backend/test/resources/v2-hello-world.json
  backend/test/resources/v2-hello-world.yaml
Labels: lgtm, approved, size/XL

#7906 feat(frontend): Add ability to filter by visualization type
  frontend/src/pages/CompareV2.test.tsx
  frontend/src/pages/CompareV2.tsx
Labels: lgtm, approved, size/L

#7936 chore(sdk): Registry Client - default to read full spec of versions
  sdk/python/kfp/registry/context/kfp_pkg_dev.json
  sdk/python/kfp/registry/registry_client.py
  sdk/python/kfp/registry/registry_client_test.py
Labels: lgtm, approved, size/S

#7921 fix(sdk): fix extract docstring in load component
  sdk/python/kfp/compiler/_read_write_test_config.py
  sdk/python/kfp/components/structures.py
Labels: lgtm, approved, size/S

#7766 feat(backend): Expand ExecutionSpec Interface
  backend/src/apiserver/resource/model_converter.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/resource/resource_manager_util.go
  backend/src/apiserver/resource/resource_manager_util_test.go
  backend/src/apiserver/server/api_converter.go
  backend/src/apiserver/server/report_server.go
  backend/src/apiserver/server/report_server_test.go
  backend/src/apiserver/template/argo_template.go
  backend/src/apiserver/template/template.go
  backend/src/common/util/execution_spec.go
  backend/src/common/util/execution_spec_test.go
  backend/src/common/util/execution_status.go
  backend/src/common/util/workflow.go
  backend/src/common/util/workflow_test.go
  backend/third_party_licenses/cache_server.csv
  backend/third_party_licenses/persistence_agent.csv
Labels: lgtm, approved, size/XL

#7875 feat(sdk): add retry policy support for IR compilation support in kfp==1.8
  sdk/RELEASE.md
  sdk/python/kfp/v2/compiler/compiler.py
  sdk/python/kfp/v2/compiler/compiler_test.py
  sdk/python/kfp/v2/compiler/compiler_utils.py
  sdk/python/kfp/v2/compiler/compiler_utils_test.py
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_retry.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_retry.py
  sdk/python/requirements.in
Labels: lgtm, approved, size/L

#7913 feat(sdk): throw informative exception on uncalled @pipeline decorator
  sdk/python/kfp/components/pipeline_context.py
  sdk/python/kfp/components/pipeline_context_test.py
Labels: lgtm, approved, size/S

#7928 fix(sdk): fix placeholder read/write logic
  sdk/python/kfp/compiler/_read_write_test_config.py
  sdk/python/kfp/compiler/read_write_test.py
  sdk/python/kfp/components/component_factory.py
  sdk/python/kfp/components/pipeline_task.py
  sdk/python/kfp/components/placeholders.py
  sdk/python/kfp/components/structures.py
  sdk/python/kfp/components/structures_test.py
Labels: lgtm, approved, size/L

#7930 fix(sdk): fix ifpresent and concat placeholder compile
  sdk/python/kfp/compiler/_read_write_test_config.py
  sdk/python/kfp/compiler/test_data/pipelines/pipeline_with_concat_placeholder.yaml
  sdk/python/kfp/compiler/test_data/pipelines/pipeline_with_if_placeholder.yaml
  sdk/python/kfp/compiler/test_data/pipelines/xgboost_sample_pipeline.yaml
  sdk/python/kfp/components/pipeline_task.py
Labels: lgtm, approved, size/L

#7952 chore(sdk): bump kfp version to 2.0.0b0
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
Labels: lgtm, size/S

#7933 feat(frontend): Create two-level dropdown
  frontend/src/components/TwoLevelDropdown.test.tsx
  frontend/src/components/TwoLevelDropdown.tsx
Labels: lgtm, approved, size/L

#7948 feat(sdk): Add default registry context
  sdk/python/kfp/registry/context/default_pkg_dev.json
  sdk/python/kfp/registry/registry_client.py
  sdk/python/kfp/registry/registry_client_test.py
Labels: lgtm, approved, size/M

#7760 chore: fix link to pytest-xdist docs
  components/aws/sagemaker/tests/integration_tests/conftest.py
Labels: lgtm, approved, size/XS, ok-to-test

#7943 feat(frontend): Display multi-level dropdown on KFPv2 Run Comparison page
  frontend/src/components/TwoLevelDropdown.tsx
  frontend/src/pages/CompareV2.test.tsx
  frontend/src/pages/CompareV2.tsx
Labels: lgtm, approved, size/L
