Repository kubeflow/pipelines, pull requests merged in 2022-04, with the labels that each got.

#7499 feat(backend): support IR YAML format in API
  backend/src/apiserver/server/util.go
  backend/src/apiserver/template/template.go
  backend/src/apiserver/template/template_test.go
  backend/src/apiserver/template/v2_template.go
Labels: lgtm, approved, size/M, area/backend

#7493 chore(deps): Bump google-cloud-storage to 2.2.1
  sdk/RELEASE.md
  sdk/python/requirements.in
  sdk/python/requirements.txt
Labels: lgtm, approved, size/S, ok-to-test

#7500 fix(sdk): fix yaml support `create_run_from_pipeline_func`
  sdk/python/kfp/client/client.py
Labels: lgtm, approved, size/XS

#7502 chore(deps): Upgrade google-cloud-storage to v2
  sdk/RELEASE.md
  sdk/python/requirements.in
  sdk/python/requirements.txt
Labels: lgtm, approved, size/S, ok-to-test

#7451 chore(sdk): include typestub libraries in requirements-dev.txt
  sdk/python/requirements-dev.txt
Labels: lgtm, approved, size/XS

#7519 chore(sdk): release KFP SDK 2.0.0-alpha.2
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
Labels: lgtm, approved, size/S

#7508 feat(sdk)!: promote v2 compiler command and deprecate v1 command
  sdk/python/kfp/compiler_cli_tests/compiler_cli_tests.py
  sdk/python/setup.py
Labels: lgtm, approved, size/XS

#7520 chore(sdk): make field order in compile deterministic
  sdk/python/kfp/client/client.py
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/compiler_cli_tests/compiler_cli_tests.py
  sdk/python/kfp/compiler_cli_tests/test_data/lightweight_python_functions_v2_pipeline.yaml
  sdk/python/kfp/compiler_cli_tests/test_data/lightweight_python_functions_v2_with_outputs.yaml
  sdk/python/kfp/compiler_cli_tests/test_data/pipeline_with_after.yaml
  sdk/python/kfp/compiler_cli_tests/test_data/pipeline_with_concat_placeholder.yaml
  sdk/python/kfp/compiler_cli_tests/test_data/pipeline_with_condition.yaml
  sdk/python/kfp/compiler_cli_tests/test_data/pipeline_with_env.yaml
  sdk/python/kfp/compiler_cli_tests/test_data/pipeline_with_exit_handler.yaml
  sdk/python/kfp/compiler_cli_tests/test_data/pipeline_with_gcpc_types.yaml
  sdk/python/kfp/compiler_cli_tests/test_data/pipeline_with_if_placeholder.yaml
  sdk/python/kfp/compiler_cli_tests/test_data/pipeline_with_importer.yaml
  sdk/python/kfp/compiler_cli_tests/test_data/pipeline_with_loops.yaml
  sdk/python/kfp/compiler_cli_tests/test_data/pipeline_with_loops_and_conditions.yaml
  sdk/python/kfp/compiler_cli_tests/test_data/pipeline_with_metrics_outputs.yaml
  sdk/python/kfp/compiler_cli_tests/test_data/pipeline_with_nested_conditions.yaml
  sdk/python/kfp/compiler_cli_tests/test_data/pipeline_with_nested_conditions_yaml.yaml
  sdk/python/kfp/compiler_cli_tests/test_data/pipeline_with_nested_loops.yaml
  sdk/python/kfp/compiler_cli_tests/test_data/pipeline_with_ontology.yaml
  sdk/python/kfp/compiler_cli_tests/test_data/pipeline_with_params_containing_format.yaml
  sdk/python/kfp/compiler_cli_tests/test_data/pipeline_with_placeholders.yaml
  sdk/python/kfp/compiler_cli_tests/test_data/pipeline_with_resource_spec.yaml
  sdk/python/kfp/compiler_cli_tests/test_data/pipeline_with_reused_component.yaml
  sdk/python/kfp/compiler_cli_tests/test_data/pipeline_with_task_final_status.yaml
  sdk/python/kfp/compiler_cli_tests/test_data/pipeline_with_task_final_status_yaml.yaml
  sdk/python/kfp/compiler_cli_tests/test_data/pipeline_with_various_io_types.yaml
  sdk/python/kfp/compiler_cli_tests/test_data/two_step_pipeline.yaml
  sdk/python/kfp/compiler_cli_tests/test_data/v2_component_with_optional_inputs.yaml
  sdk/python/kfp/compiler_cli_tests/test_data/v2_component_with_pip_index_urls.yaml
  sdk/python/kfp/compiler_cli_tests/test_data/xgboost_sample_pipeline.yaml
  sdk/python/kfp/components/structures.py
  sdk/python/kfp/components/structures_test.py
  sdk/python/kfp/components/v1_structures.py
Labels: lgtm, approved, size/XXL

#7536 chore(sdk): stop using pydantic for serialization
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/components/structures.py
  sdk/python/kfp/components/structures_test.py
  sdk/python/kfp/deprecated/cli/components.py
  sdk/python/kfp/utils/__init__.py
  sdk/python/kfp/utils/ir_utils.py
  sdk/python/kfp/utils/ir_utils_test.py
  sdk/python/setup.py
Labels: lgtm, approved, size/L

#7548 chore(sdk): use setuptools.find_packages
  sdk/python/setup.py
Labels: lgtm, approved, size/S

#7537 feat(frontend): Support default feature flags update in localStorage. Fix #7379
  frontend/src/features.ts
Labels: lgtm, approved, size/S

#7563 feat(sdk): add .list_pipeline_versions and .unarchive_experiment methods to Client
  sdk/RELEASE.md
  sdk/python/kfp/client/client.py
Labels: lgtm, approved, size/M

#7570 fix(frontend): Update sample pipelines in mock-backend to use yaml format
  frontend/mock-backend/data/v2/pipeline/README.md
  frontend/mock-backend/data/v2/pipeline/lightweight_python_functions_v2_pipeline.json
  frontend/mock-backend/data/v2/pipeline/lightweight_python_functions_v2_pipeline_rev.yaml
  frontend/mock-backend/data/v2/pipeline/mock_lightweight_python_functions_v2_pipeline_rev.json
  frontend/mock-backend/data/v2/pipeline/pipeline_with_loops_and_conditions.yaml
  frontend/mock-backend/data/v2/pipeline/pipeline_with_various_io_types.yaml
  frontend/mock-backend/data/v2/pipeline/xgboost_sample_pipeline.yaml
  frontend/mock-backend/fixed-data.ts
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, size/XXL

#7575 chore(frontend): Add Joe Li to be reviewer of frontend.
  frontend/OWNERS
Labels: lgtm, approved, size/XS

#7558 chore(sdk): clean up v2 CLI
  mypy.ini
  sdk/python/kfp/cli/__main__.py
  sdk/python/kfp/cli/cli.py
  sdk/python/kfp/cli/components.py
  sdk/python/kfp/cli/components_test.py
  sdk/python/kfp/cli/diagnose_me/dev_env.py
  sdk/python/kfp/cli/diagnose_me/dev_env_test.py
  sdk/python/kfp/cli/diagnose_me/gcp.py
  sdk/python/kfp/cli/diagnose_me/gcp_test.py
  sdk/python/kfp/cli/diagnose_me/kubernetes_cluster.py
  sdk/python/kfp/cli/diagnose_me/kubernetes_cluster_test.py
  sdk/python/kfp/cli/diagnose_me/utility.py
  sdk/python/kfp/cli/diagnose_me/utility_test.py
  sdk/python/kfp/cli/diagnose_me_cli.py
  sdk/python/kfp/cli/experiment.py
  sdk/python/kfp/cli/output.py
  sdk/python/kfp/cli/pipeline.py
  sdk/python/kfp/cli/recurring_run.py
  sdk/python/kfp/cli/run.py
  sdk/python/requirements-dev.txt
  sdk/python/setup.py
Labels: lgtm, approved, size/L

#7581 feat(api): Update IR with RetryPolicy
  api/v2alpha1/pipeline_spec.proto
Labels: lgtm, approved, size/S

#7560 chore(sdk): use click for dsl-compile command
  samples/test/utils/kfp/samples/test/utils.py
  sdk/python/kfp/cli/compile.py
  sdk/python/kfp/compiler_cli_tests/compiler_cli_tests.py
  sdk/python/setup.py
Labels: lgtm, approved, size/L, do-not-merge/hold

#7559 chore(sdk): use click for kfp components commands
  sdk/python/kfp/cli/__main__.py
  sdk/python/kfp/cli/components.py
  sdk/python/kfp/cli/components_test.py
Labels: lgtm, approved, size/L, do-not-merge/hold

#7583 chore(frontend): KFPv2: Update KFP UI API version to the latest
  frontend/src/apis/experiment/api.ts
  frontend/src/apis/job/api.ts
  frontend/src/apis/pipeline/api.ts
  frontend/src/apis/run/api.ts
Labels: lgtm, approved, size/L

#7562 feat(sdk): add archive, unarchive, and delete run methods and tidy docstrings
  sdk/python/kfp/client/client.py
Labels: lgtm, approved, needs-ok-to-test, size/M

#7591 fix(frontend): Convert PipelineSpec format from json to yaml #7444
  frontend/src/components/tabs/StaticNodeDetailsV2.test.tsx
  frontend/src/components/tabs/StaticNodeDetailsV2.tsx
  frontend/src/data/test/lightweight_python_functions_v2_pipeline_rev.yaml
  frontend/src/data/test/mock_lightweight_python_functions_v2_pipeline.json
  frontend/src/data/test/pipeline_with_loops_and_conditions.json
  frontend/src/data/test/pipeline_with_loops_and_conditions.yaml
  frontend/src/lib/v2/DynamicFlow.test.ts
  frontend/src/lib/v2/StaticFlow.test.ts
  frontend/src/lib/v2/WorkflowUtils.test.ts
  frontend/src/lib/v2/WorkflowUtils.ts
  frontend/src/pages/PipelineDetails.tsx
  frontend/src/pages/PipelineDetailsTest.test.tsx
  frontend/src/pages/PipelineDetailsV2.test.tsx
  frontend/src/pages/PipelineDetailsV2.tsx
  frontend/src/pages/RunDetailsV2.test.tsx
  frontend/src/pages/RunDetailsV2.tsx
Labels: lgtm, approved, size/XXL

#7603 feat(sdk): use dsl noun group for compile CLI commands
  sdk/python/kfp/cli/cli.py
  sdk/python/kfp/cli/cli_test.py
  sdk/python/kfp/cli/dsl.py
  sdk/python/kfp/cli/dsl_compile.py
  sdk/python/kfp/compiler_cli_tests/README.md
  sdk/python/kfp/compiler_cli_tests/compiler_cli_tests.py
  sdk/python/setup.py
Labels: lgtm, approved, size/L

#7620 chore(frontend): Add Joe Li an approver of KFP frontend
  frontend/OWNERS
Labels: lgtm, approved, size/XS

#7612 chore(frontend): Update Pipeline Spec in TypeScript
  frontend/scripts/pipelinespec.sh
  frontend/src/generated/pipeline_spec/pipeline_spec.ts
  frontend/src/generated/pipeline_spec/pipeline_spec_pb.d.ts
  frontend/src/generated/pipeline_spec/pipeline_spec_pb.js
Labels: lgtm, approved, size/M

#7606 feat(sdk): add client methods to cli
  sdk/python/kfp/cli/experiment.py
  sdk/python/kfp/cli/pipeline.py
  sdk/python/kfp/cli/recurring_run.py
  sdk/python/kfp/cli/run.py
Labels: lgtm, approved, size/L

#7624 feat(frontend): Enable KFPv2 UI by default by creating a new feature key #7610
  frontend/src/features.ts
  frontend/src/lib/v2/WorkflowUtils.ts
  frontend/src/pages/PipelineDetails.tsx
  frontend/src/pages/PipelineDetailsTest.test.tsx
Labels: lgtm, approved, size/S

#7636 feat(frontend): Automatically fetch MLMD for Run status update in V2.
  frontend/src/pages/RunDetailsV2.tsx
Labels: lgtm, approved, size/XS

#7637 fix(frontend): Use yaml mode for PipelineSpec editor view
  frontend/src/pages/PipelineDetailsV2.tsx
Labels: lgtm, approved, size/XS

#7596 feat(conformance): Enable experiment API tests in KF mode.
  backend/src/common/client/api_server/experiment_client.go
  backend/src/common/client/api_server/job_client.go
  backend/src/common/client/api_server/pipeline_client.go
  backend/src/common/client/api_server/pipeline_upload_client.go
  backend/src/common/client/api_server/run_client.go
  backend/src/common/client/api_server/util.go
  backend/src/common/client/api_server/visualization_client.go
  backend/test/initialization/initialization_test.go
  backend/test/integration/experiment_api_test.go
  backend/test/integration/flags.go
  backend/test/integration/job_api_test.go
  backend/test/integration/run_api_test.go
  backend/test/integration/upgrade_test.go
  backend/test/test_utils.go
Labels: lgtm, approved, size/L

#7618 feat(sdk): improve cli help text
  sdk/RELEASE.md
  sdk/python/kfp/cli/cli.py
  sdk/python/kfp/cli/cli_test.py
  sdk/python/kfp/cli/component.py
  sdk/python/kfp/cli/diagnose_me_cli.py
  sdk/python/kfp/cli/dsl_compile.py
  sdk/python/kfp/cli/experiment.py
  sdk/python/kfp/cli/pipeline.py
  sdk/python/kfp/cli/recurring_run.py
  sdk/python/kfp/cli/run.py
  sdk/python/kfp/cli/utils/parsing.py
  sdk/python/kfp/cli/utils/parsing_test.py
  sdk/python/kfp/client/client.py
Labels: lgtm, approved, size/XL

#7628 feat(sdk): deprecate dsl-compile
  sdk/python/kfp/cli/cli_test.py
  sdk/python/kfp/cli/dsl_compile.py
Labels: lgtm, approved, size/XS

#7632 feat(sdk): Accept newer `typing-extensions` versions
  sdk/RELEASE.md
  sdk/python/requirements.in
Labels: lgtm, approved, size/XS, needs-ok-to-test
