Repository kubeflow/pipelines, pull requests merged in 2022-09, with the labels that each got.

#8221 chore(sdk): add script to check for unused imports
  sdk/python/requirements-dev.txt
  test/presubmit-isort-sdk.sh
Labels: lgtm, approved, size/XS

#8229 chore(sdk): bump kfp version to 2.0.0-beta.4
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
Labels: lgtm, approved, size/S

#8183 fix(sdk): fix dsl control flow docstrings
  sdk/python/kfp/components/tasks_group.py
Labels: lgtm, approved, size/S

#8212 feat(docs): use new sdk reference docs theme
  docs/_static/custom.css
  docs/conf.py
  docs/requirements.txt
Labels: lgtm, approved, size/M

#8239 fix(sdk): fix docs version reference
  docs/conf.py
Labels: lgtm, approved, size/XS

#7789 feat(sdk): migrate v1 auth to v2
  sdk/python/kfp/client/__init__.py
  sdk/python/kfp/client/client.py
  sdk/python/kfp/client/set_volume_credentials.py
  sdk/python/kfp/client/set_volume_credentials_test.py
  sdk/python/kfp/client/token_credentials_base.py
  sdk/python/kfp/client/token_credentials_base_test.py
Labels: lgtm, approved, size/L

#8142 feature(sdk): print links outside of ipython. Fixes #8141
  sdk/python/kfp/client/client.py
Labels: lgtm, approved, needs-ok-to-test, size/S

#8232 feat(sdk): add compilation logic for google artifact types (support custom artifact types pt. 2)
  samples/v2/pipeline_with_importer_test.py
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/compiler/pipeline_spec_builder.py
  sdk/python/kfp/compiler/pipeline_spec_builder_test.py
  sdk/python/kfp/components/component_factory.py
  sdk/python/kfp/components/executor.py
  sdk/python/kfp/components/graph_component.py
  sdk/python/kfp/components/importer_node.py
  sdk/python/kfp/components/pipeline_channel_test.py
  sdk/python/kfp/components/pipeline_task.py
  sdk/python/kfp/components/pipeline_task_test.py
  sdk/python/kfp/components/structures.py
  sdk/python/kfp/components/structures_test.py
  sdk/python/kfp/components/types/type_annotations.py
  sdk/python/kfp/components/types/type_annotations_test.py
  sdk/python/kfp/components/types/type_utils.py
  sdk/python/kfp/components/types/type_utils_test.py
  sdk/python/kfp/deprecated/dsl/component_spec.py
  sdk/python/kfp/deprecated/dsl/type_utils.py
  sdk/python/test_data/pipelines/pipeline_with_gcpc_types.py
  sdk/python/test_data/pipelines/pipeline_with_gcpc_types.yaml
  sdk/python/test_data/pipelines/pipeline_with_google_artifact_type.py
  sdk/python/test_data/pipelines/pipeline_with_google_artifact_type.yaml
  sdk/python/test_data/pipelines/pipeline_with_importer.yaml
  sdk/python/test_data/test_data_config.yaml
Labels: lgtm, approved, size/XXL

#8259 fix(sdk): keeping placeholder strings in command and args even if default value is set
  sdk/python/kfp/components/pipeline_task.py
  sdk/python/test_data/pipelines/xgboost_sample_pipeline.yaml
Labels: lgtm, approved, size/S

#8263 fix(sdk): make sdk installable with poetry
  sdk/python/setup.py
Labels: lgtm, approved, size/XS, ok-to-test

#8247 test(components): Added integration test for Sagemaker TrainingJob component v2.
  components/aws/sagemaker/tests/integration_tests/Dockerfile
  components/aws/sagemaker/tests/integration_tests/component_tests/test_v2_train_component.py
  components/aws/sagemaker/tests/integration_tests/conftest.py
  components/aws/sagemaker/tests/integration_tests/resources/config/ack-training-job/config.yaml
  components/aws/sagemaker/tests/integration_tests/resources/definition/trainingv2_pipeline.py
  components/aws/sagemaker/tests/integration_tests/scripts/ack-rbac.yaml
  components/aws/sagemaker/tests/integration_tests/scripts/generate_trust_policy
  components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests
  components/aws/sagemaker/tests/integration_tests/utils/ack_utils.py
Labels: approved, size/L, ok-to-test

#8233 feat(sdk): add runtime logic for custom artifact types (support for custom artifact types pt. 3)
  sdk/python/kfp/components/component_factory.py
  sdk/python/kfp/components/component_factory_test.py
  sdk/python/kfp/components/executor.py
  sdk/python/kfp/components/executor_test.py
  sdk/python/kfp/components/structures.py
  sdk/python/kfp/components/types/artifact_types.py
  sdk/python/kfp/components/types/artifact_types_test.py
  sdk/python/kfp/components/types/custom_artifact_types.py
  sdk/python/kfp/components/types/custom_artifact_types_test.py
  sdk/python/kfp/components/types/type_annotations.py
  sdk/python/kfp/components/types/type_annotations_test.py
  sdk/python/kfp/components/types/type_utils.py
  sdk/python/requirements.txt
  sdk/python/test_data/pipelines/pipeline_with_google_artifact_type.yaml
Labels: lgtm, approved, size/XXL

#8264 chore(components): Update scripts to use public ecr instead of docker
  components/aws/sagemaker/Dockerfile
  components/aws/sagemaker/TrainingJob/samples/mnist-kmeans-training/mnist-kmeans-training-pipeline.py
  components/aws/sagemaker/codebuild/deploy.buildspec.yml
  components/aws/sagemaker/codebuild/scripts/deploy.sh
  components/aws/sagemaker/codebuild/unit-test.buildspec.yml
  components/aws/sagemaker/common/generate_components.py
  components/aws/sagemaker/tests/integration_tests/utils/minio_utils.py
  components/aws/sagemaker/tests/unit_tests/Dockerfile
Labels: lgtm, approved, needs-ok-to-test, size/M

#8261 fix(backend): fix backward compatibility in scheduledworkflow
  backend/src/common/util/execution_spec.go
  backend/src/common/util/workflow.go
  backend/src/crd/controller/scheduledworkflow/util/scheduled_workflow.go
  backend/src/crd/pkg/apis/scheduledworkflow/v1beta1/types.go
Labels: lgtm, approved, size/M

#8272 fix(sdk): fix v1 output deserialization
  sdk/python/kfp/components/structures.py
Labels: lgtm, approved, size/XS, do-not-merge/hold

#8262 fix(sdk): Replace OOB authentication with loopback flow
  sdk/python/kfp/client/auth.py
  sdk/python/kfp/client/client.py
Labels: lgtm, approved, size/L

#8274 chore: Add PR 8262 to sdk/RELEASE.md
  sdk/RELEASE.md
Labels: lgtm, approved, size/XS

#8258 refactor(components): Open sourcing v2 AWS TrainingJob component.
  components/aws/sagemaker/.dockerignore
  components/aws/sagemaker/Changelog.md
  components/aws/sagemaker/README.md
  components/aws/sagemaker/THIRD-PARTY-LICENSES.v2.txt
  components/aws/sagemaker/TrainingJob/README.md
  components/aws/sagemaker/TrainingJob/component.yaml
  components/aws/sagemaker/TrainingJob/src/TrainingJob_component.py
  components/aws/sagemaker/TrainingJob/src/TrainingJob_request.yaml.tpl
  components/aws/sagemaker/TrainingJob/src/TrainingJob_spec.py
  components/aws/sagemaker/commonv2/__init__.py
  components/aws/sagemaker/commonv2/common_inputs.py
  components/aws/sagemaker/commonv2/sagemaker_component.py
  components/aws/sagemaker/commonv2/sagemaker_component_spec.py
  components/aws/sagemaker/commonv2/spec_input_parsers.py
  components/aws/sagemaker/requirements_v2.txt
  components/aws/sagemaker/tests/integration_tests/conftest.py
  components/aws/sagemaker/tests/integration_tests/resources/definition/trainingv2_pipeline.py
  components/aws/sagemaker/tests/integration_tests/utils/ack_utils.py
  components/aws/sagemaker/v2.Dockerfile
  components/aws/sagemaker/v2.Dockerfile.dockerignore
Labels: lgtm, approved, size/XXL, ok-to-test

#8271 chore(sdk): hide private methods in placeholders for simpler doc
  sdk/python/kfp/compiler/pipeline_spec_builder.py
  sdk/python/kfp/components/base_model.py
  sdk/python/kfp/components/base_model_test.py
  sdk/python/kfp/components/component_factory.py
  sdk/python/kfp/components/importer_node.py
  sdk/python/kfp/components/pipeline_task.py
  sdk/python/kfp/components/placeholders.py
  sdk/python/kfp/components/placeholders_test.py
  sdk/python/kfp/components/structures.py
Labels: lgtm, approved, size/L

#8275 fix(sdk): Add OOB fix for v1.8 from #8262
  sdk/RELEASE.md
  sdk/python/kfp/_auth.py
  sdk/python/kfp/_client.py
Labels: lgtm, approved, size/L

#7660 feat(sdk): enable dynamic importer metadata
  sdk/python/kfp/components/importer_node.py
  sdk/python/kfp/components/importer_node_test.py
  sdk/python/test_data/pipelines/pipeline_with_dynamic_importer_metadata.py
  sdk/python/test_data/pipelines/pipeline_with_dynamic_importer_metadata.yaml
  sdk/python/test_data/test_data_config.yaml
Labels: lgtm, approved, size/XL

#8273 fix(sdk): fix InputPath error in executor
  sdk/python/kfp/components/executor.py
  sdk/python/kfp/components/executor_test.py
Labels: lgtm, approved, size/L

#8279 feat(sdk): add workaround for google artifact (support custom artifact types pt. 4)
  sdk/python/kfp/components/executor.py
  sdk/python/kfp/components/executor_test.py
Labels: lgtm, approved, size/S

#8226 feat(sdk): add support for dynamic importer metadata in sdk v1
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_importer.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_importer.py
  sdk/python/kfp/v2/components/importer_node.py
  sdk/python/kfp/v2/components/importer_node_test.py
Labels: lgtm, approved, size/L

#8280 chore: Update sdk/OWNERS in sdk/release-1.8 branch
  sdk/OWNERS
Labels: lgtm, approved, size/XS

#8278 feat(frontend): v2 Dynamic Sub-DAG (I)
  frontend/src/components/graph/Constants.ts
  frontend/src/components/graph/SubDagNode.tsx
  frontend/src/components/tabs/RuntimeNodeDetailsV2.tsx
  frontend/src/icons/StopCircle.tsx
  frontend/src/lib/v2/DynamicFlow.ts
  frontend/src/lib/v2/StaticFlow.ts
  frontend/src/pages/RunDetailsV2.tsx
Labels: lgtm, approved, size/L

#8287 fix(backend): Fix "Unknown execution spec" error. Fixes #8256
  backend/src/apiserver/resource/resource_manager.go
Labels: lgtm, approved, size/XS

#8288 chore(sdk): 1.8.14 release
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
Labels: lgtm, approved, size/S

#8148 chore(components/pytorch) - Samples fix for PT and PTL Upgrade
  samples/contrib/pytorch-samples/Pipeline-Bert-Dist.ipynb
  samples/contrib/pytorch-samples/Pipeline-Bert.ipynb
  samples/contrib/pytorch-samples/Pipeline-Cifar10-Captum-Insights.ipynb
  samples/contrib/pytorch-samples/Pipeline-Cifar10-hpo.ipynb
  samples/contrib/pytorch-samples/Pipeline-Cifar10.ipynb
  samples/contrib/pytorch-samples/bert/agnews_classification_pytorch.py
  samples/contrib/pytorch-samples/cifar10/cifar10_datamodule.py
  samples/contrib/pytorch-samples/cifar10/cifar10_pytorch.py
  samples/contrib/pytorch-samples/cifar10/cifar10_train.py
  samples/contrib/pytorch-samples/cifar10/input.json
  samples/contrib/pytorch-samples/cifar10/requirements.txt
  samples/contrib/pytorch-samples/cluster_build.md
  samples/contrib/pytorch-samples/install-dependencies.sh
  samples/contrib/pytorch-samples/mino-secret.yaml
Labels: lgtm, approved, size/L

#8305 test(frontend): Enforce no warning standard in frontend development.
  frontend/package.json
  frontend/src/components/tabs/RuntimeNodeDetailsV2.tsx
Labels: lgtm, approved, size/XS

#8304 fix(frontend): Fix the issue when drawing dependentTask for task-to-task edges.
  frontend/src/lib/v2/StaticFlow.ts
Labels: lgtm, approved, size/S

#8309 chore(release): release sdk 2.0.0b5
  docs/conf.py
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
Labels: lgtm, approved, size/M

#8316 fix(sdk): fix NamedTuple output with Dict/List bug
  sdk/python/kfp/components/component_decorator_test.py
  sdk/python/kfp/components/component_factory.py
Labels: lgtm, approved, size/M
