Repository kubeflow/pipelines, pull requests merged in 2022-05, with the labels that each got.

#7647 feat(conformance): adapt pipeline API tests to KF environment
  backend/test/integration/pipeline_api_test.go
Labels: lgtm, approved, size/M

#7653 feat(conformance): adapt pipeline version API tests to run in KF
  backend/test/integration/pipeline_version_api_test.go
Labels: lgtm, approved, size/M

#7639 feat(sdk): use custom basemodel and remove pydantic
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/components/base_component.py
  sdk/python/kfp/components/base_component_test.py
  sdk/python/kfp/components/base_model.py
  sdk/python/kfp/components/base_model_test.py
  sdk/python/kfp/components/pipeline_task.py
  sdk/python/kfp/components/structures.py
  sdk/python/kfp/components/structures_test.py
  sdk/python/requirements.in
  sdk/python/requirements.txt
Labels: lgtm, approved, size/XXL

#7578 fix(backend): fix simple loop bug
  backend/src/v2/driver/driver.go
  samples/core/loop_static/loop_static_test.py
  samples/core/loop_static/loop_static_v2.py
Labels: lgtm, approved, size/M

#7642 Pipeline level exit handler and v2 test
  backend/src/v2/Makefile
  backend/src/v2/cmd/compiler/main.go
  backend/src/v2/compiler/argocompiler/dag.go
  samples/core/exit_handler/exit_handler_test.py
  samples/core/exit_handler/exit_handler_v2.py
  samples/core/loop_static/loop_static_v2.py
Labels: lgtm, approved, size/M

#7658 feat(conformance): adapt run api tests to KF env
  backend/test/integration/experiment_api_test.go
  backend/test/integration/run_api_test.go
  backend/test/test_utils.go
Labels: lgtm, approved, size/L

#7668 fix(sdk): some cli fixes
  sdk/python/kfp/cli/component.py
  sdk/python/kfp/cli/component_test.py
  sdk/python/kfp/cli/dsl_compile.py
  sdk/python/kfp/cli/experiment.py
  sdk/python/kfp/cli/pipeline.py
  sdk/python/kfp/cli/recurring_run.py
  sdk/python/kfp/cli/run.py
Labels: lgtm, approved, size/L

#7670 feat(conformance): adapt remaining tests to KF env
  backend/src/common/client/api_server/visualization_client.go
  backend/test/integration/job_api_test.go
  backend/test/integration/run_api_test.go
  backend/test/integration/upgrade_test.go
  backend/test/integration/visualization_api_test.go
  backend/test/test_utils.go
Labels: lgtm, approved, size/L

#7675 chore(sdk): 2.0.0-alpha.3 release
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
Labels: lgtm, size/S

#7531 feat(backend): Add ExecutionSpec Interface
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/resource/resource_manager_util.go
  backend/src/apiserver/template/argo_template.go
  backend/src/apiserver/template/template.go
  backend/src/apiserver/template/v2_template.go
  backend/src/common/util/execution_spec.go
  backend/src/common/util/execution_spec_test.go
  backend/src/common/util/execution_status.go
  backend/src/common/util/scheduled_workflow.go
  backend/src/common/util/workflow.go
  backend/src/common/util/workflow_test.go
  backend/third_party_licenses/cache_server.csv
  backend/third_party_licenses/persistence_agent.csv
  backend/third_party_licenses/swf.csv
Labels: lgtm, approved, size/L

#7597 feat(sdk): Implement Registry client
  sdk/RELEASE.md
  sdk/python/kfp/registry/__init__.py
  sdk/python/kfp/registry/registry_client.py
  sdk/python/kfp/registry/registry_client_test.py
Labels: lgtm, approved, size/XL

#7659 feat(sdk): make client return values consistent
  sdk/python/kfp/client/client.py
Labels: lgtm, approved, size/L

#7694 chore(sdk): use unittest.mock instead of mock
  sdk/python/kfp/registry/registry_client_test.py
Labels: lgtm, approved, size/XS

#7538 fix(cache): Change kfp cache cert names to match cert-manager
  backend/src/cache/main.go
Labels: lgtm, approved, size/S

#7704 feat(IR): add is_optional to ParameterSpec proto
  api/v2alpha1/pipeline_spec.proto
Labels: lgtm, approved, size/S

#7712 feat(sdk): compile JSON with formatting
  sdk/python/kfp/utils/ir_utils.py
  sdk/python/kfp/utils/ir_utils_test.py
Labels: lgtm, approved, size/M

#7722 fix(sdk): fix CLI upload pipeline version
  sdk/python/kfp/cli/pipeline.py
Labels: lgtm, approved, size/M

#7580 feat(sdk): enable compilation of primitive components
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/compiler/pipeline_spec_builder.py
  sdk/python/kfp/compiler/pipeline_spec_builder_test.py
  sdk/python/kfp/components/base_component_test.py
  sdk/python/kfp/components/pipeline_context.py
  sdk/python/kfp/components/pipeline_context_test.py
  sdk/python/kfp/components/pipeline_task.py
  sdk/python/kfp/components/structures.py
  sdk/python/kfp/components/types/type_utils.py
  sdk/python/kfp/components/types/type_utils_test.py
  sdk/python/kfp/components/yaml_component_test.py
Labels: lgtm, approved, size/XXL

#7713 feat(sdk): validate pipeline resource name before submission
  sdk/python/kfp/cli/pipeline.py
  sdk/python/kfp/client/client.py
  sdk/python/kfp/client/client_test.py
Labels: lgtm, approved, size/M

#7734 feat(api): add runtime_config.parameter_values with string typed values
  backend/api/go_client/pipeline_spec.pb.go
  backend/api/go_http_client/job_model/pipeline_spec_runtime_config.go
  backend/api/go_http_client/run_model/pipeline_spec_runtime_config.go
  backend/api/pipeline_spec.proto
  backend/api/python_http_client/docs/PipelineSpecRuntimeConfig.md
  backend/api/python_http_client/kfp_server_api/models/pipeline_spec_runtime_config.py
  backend/api/python_http_client/test/test_api_job.py
  backend/api/python_http_client/test/test_api_list_jobs_response.py
  backend/api/python_http_client/test/test_api_list_runs_response.py
  backend/api/python_http_client/test/test_api_pipeline_spec.py
  backend/api/python_http_client/test/test_api_run.py
  backend/api/python_http_client/test/test_api_run_detail.py
  backend/api/python_http_client/test/test_pipeline_spec_runtime_config.py
  backend/api/swagger/job.swagger.json
  backend/api/swagger/kfp_api_single_file.swagger.json
  backend/api/swagger/run.swagger.json
Labels: lgtm, approved, size/L

#7737 fix(frontend): Change "Layer" to unclickable.
  frontend/src/components/graph/SubDagLayer.tsx
  frontend/src/lib/Buttons.ts
  frontend/src/pages/__snapshots__/ArchivedRuns.test.tsx.snap
Labels: lgtm, approved, size/XS

#7749 chore: Add KFP 2022 Roadmap
  ROADMAP.md
Labels: lgtm, approved, size/S

#7736 chore: bump kfp-pipeline-spec to 0.1.15
  api/v2alpha1/python/setup.py
Labels: lgtm, approved, size/XS

#7635 docs: fix rds documentation link
  manifests/kustomize/env/aws/README.md
Labels: lgtm, approved, size/XS

#7754 fix(ir): fix kfp-pipeline-spec proto imports
  api/v2alpha1/cache_key.proto
  api/v2alpha1/pipeline_spec.proto
Labels: lgtm, approved, size/XS

#7752 chore: Update ROADMAP.md
  ROADMAP.md
Labels: lgtm, approved, size/XS

#7687 refactor(sdk): move placeholder logic to structures
  sdk/python/kfp/compiler/pipeline_spec_builder.py
  sdk/python/kfp/components/component_factory.py
  sdk/python/kfp/components/importer_node.py
  sdk/python/kfp/components/pipeline_task.py
  sdk/python/kfp/components/placeholders.py
  sdk/python/kfp/components/placeholders_test.py
  sdk/python/kfp/components/structures.py
  sdk/python/kfp/components/structures_test.py
Labels: lgtm, approved, size/L

#7762 chore: fix link for installing kubeflow on AWS
  samples/contrib/aws-samples/README.md
Labels: lgtm, approved, size/XS, needs-ok-to-test

#7739 feat(sdk)!: make CLI output consistent, readable, and usable
  sdk/RELEASE.md
  sdk/python/kfp/cli/dsl_compile.py
  sdk/python/kfp/cli/experiment.py
  sdk/python/kfp/cli/output.py
  sdk/python/kfp/cli/pipeline.py
  sdk/python/kfp/cli/recurring_run.py
  sdk/python/kfp/cli/run.py
  sdk/python/requirements-dev.txt
  sdk/python/requirements.in
  sdk/python/requirements.txt
Labels: lgtm, approved, size/XL

#7532 fix(backend): fixes healthz response by adding json content type. Fixes #7525
  backend/src/apiserver/main.go
  backend/src/common/client/api_server/healthz_client.go
  backend/test/integration/healthz_api_test.go
Labels: lgtm, approved, size/L, ok-to-test

#7741 feat[deployment]: add startup probe to pipeline API deployment
  manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
Labels: lgtm, approved, size/S, ok-to-test

#7773 fix(frontend): Move all V2 flag check to V2_ALPHA
  frontend/src/lib/v2/WorkflowUtils.ts
  frontend/src/pages/NewRunSwitcher.tsx
  frontend/src/pages/PipelineDetails.tsx
Labels: lgtm, approved, size/XS

#7775 chore(sdk): Update OWNERS
  sdk/OWNERS
Labels: lgtm, approved, size/XS

#7689 feat(sdk): enable read in component using IR
  sdk/python/kfp/components/component_factory.py
  sdk/python/kfp/components/pipeline_task.py
  sdk/python/kfp/components/pipeline_task_test.py
  sdk/python/kfp/components/structures.py
  sdk/python/kfp/components/structures_test.py
  sdk/python/kfp/components/types/type_utils.py
  sdk/python/kfp/components/yaml_component_test.py
Labels: lgtm, approved, size/XXL

#7690 feat(sdk): only use IR when saving component
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/components/pipeline_task_test.py
  sdk/python/kfp/components/structures.py
  sdk/python/kfp/components/structures_test.py
  sdk/python/kfp/utils/__init__.py
  sdk/python/kfp/utils/ir_utils.py
  sdk/python/kfp/utils/ir_utils_test.py
Labels: lgtm, approved, size/L

#7771 chore(sdk): 2.0.0-alpha.4 release
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
Labels: lgtm, approved, size/S

#7780 chore(sdk): add README with project description for PyPI (v1.x)
  sdk/python/README.md
  sdk/python/setup.py
Labels: lgtm, size/M

#7804 feat(IR): adds IteratorPolicy to PipelineTaskSpec proto for support of parallelism setting on ParallelFor
  api/v2alpha1/pipeline_spec.proto
Labels: lgtm, approved, size/S, ok-to-test

#7806 chore(api): Update OWNERS
  api/OWNERS
Labels: lgtm, approved, size/XS

#7801 chore(sdk): accept newer `typing-extensions` versions
  sdk/RELEASE.md
  sdk/python/requirements.in
  sdk/python/requirements.txt
  sdk/python/setup.py
Labels: lgtm, approved, size/M

#7807 chore: bump kfp-pipeline-spec minor version to 0.1.16
  api/v2alpha1/python/setup.py
Labels: lgtm, approved, size/XS, needs-ok-to-test
