Repository kubeflow/pipelines, pull requests merged in 2022-02, with the labels that each got.

#7237 chore: Update sdk/README.md
  sdk/README.md
Labels: lgtm, approved, size/XS

#7223 fix(sdk): Add in filter to list_pipeline_versions SDK method
  sdk/RELEASE.md
  sdk/python/kfp/_client.py
Labels: lgtm, approved, size/L

#7174 fix(sdk): add verify_ssl to kfp client, fixes #4569
  sdk/RELEASE.md
  sdk/python/kfp/_client.py
Labels: lgtm, approved, size/S, ok-to-test

#7239 feat(sdk): Add `enable_job` method to client
  sdk/RELEASE.md
  sdk/python/kfp/_client.py
Labels: lgtm, approved, size/S, ok-to-test

#7227 fix(frontend): fixes link to Vertex AI workbench in GettingStarted page.
  frontend/src/pages/GettingStarted.tsx
  frontend/src/pages/__snapshots__/GettingStarted.test.tsx.snap
Labels: lgtm, approved, size/XS, ok-to-test

#7252 fix(manifests): Use number for cloudsql liveness port
  manifests/kustomize/env/gcp/cloudsql-proxy/cloudsql-proxy-deployment.yaml
Labels: lgtm, approved, size/XS

#7262 chore: update backend/OWNERS
  backend/OWNERS
Labels: lgtm, approved, size/XS

#7256 chore: update eks version to 1.19 for aws sagemaker integration tests
  components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests
Labels: lgtm, approved, size/XS, ok-to-test

#7267 fix(backend): Fix v1 caching to read Argo template from container env. Fixes #7266
  backend/metadata_writer/src/metadata_writer.py
  backend/src/cache/server/mutation.go
  backend/src/cache/server/mutation_test.go
  backend/src/cache/server/watcher.go
Labels: lgtm, approved, size/M

#7273 fix(backend): make cache-deployer generate CSR using kubelet-serving signerName
  backend/src/cache/deployer/webhook-create-signed-cert.sh
Labels: lgtm, approved, size/XS

#7277 chore: Update bump-version-in-place.sh
  test/release/bump-version-in-place.sh
Labels: lgtm, approved, size/XS

#7278 chore(release): bump version to 1.8.0-rc.2 on master branch
  CHANGELOG.md
  VERSION
Labels: lgtm, approved, size/M

#7276 chore: skip building KFP sdk and python components in cloudbuild
  .cloudbuild.yaml
  .release.cloudbuild.yaml
Labels: lgtm, approved, size/L

#7147 feat(backend): Forbid unarchive runs that belog to archived experiment
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/common/util/error.go
Labels: lgtm, approved, size/M

#7155 fix(backend): missing permissions for scheduled workflows
  manifests/kustomize/base/installs/multi-user/scheduled-workflow/cluster-role.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-scheduledworkflow-role.yaml
Labels: lgtm, approved, size/XS

#7284 chore: fix broken link in README.md
  README.md
Labels: lgtm, approved, size/XS

#7293 chore(release): bump version to 1.8.0-rc.3 on master branch
  CHANGELOG.md
  VERSION
  backend/api/python_http_client/README.md
  backend/api/python_http_client/kfp_server_api/__init__.py
  backend/api/python_http_client/kfp_server_api/api_client.py
  backend/api/python_http_client/kfp_server_api/configuration.py
  backend/api/python_http_client/setup.py
  backend/api/swagger/kfp_api_single_file.swagger.json
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml
  manifests/gcp_marketplace/schema.yaml
  manifests/gcp_marketplace/test/snapshot-base.yaml
  manifests/gcp_marketplace/test/snapshot-emissary.yaml
  manifests/gcp_marketplace/test/snapshot-managed-storage-with-db-prefix.yaml
  manifests/gcp_marketplace/test/snapshot-managed-storage.yaml
  manifests/kustomize/base/cache-deployer/kustomization.yaml
  manifests/kustomize/base/cache/kustomization.yaml
  manifests/kustomize/base/installs/generic/pipeline-install-config.yaml
  manifests/kustomize/base/metadata/base/kustomization.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/base/pipeline/metadata-writer/kustomization.yaml
  manifests/kustomize/env/gcp/inverse-proxy/kustomization.yaml
Labels: lgtm, approved, size/M

#7306 chore: Update sdk/OWNERS
  sdk/OWNERS
Labels: lgtm, approved, size/XS

#7004 feat(backend): add new endpoint that get pipeline by name
  backend/api/go_client/pipeline.pb.go
  backend/api/go_client/pipeline.pb.gw.go
  backend/api/go_http_client/pipeline_client/pipeline_service/get_pipeline_by_name_parameters.go
  backend/api/go_http_client/pipeline_client/pipeline_service/get_pipeline_by_name_responses.go
  backend/api/go_http_client/pipeline_client/pipeline_service/pipeline_service_client.go
  backend/api/pipeline.proto
  backend/api/swagger/kfp_api_single_file.swagger.json
  backend/api/swagger/pipeline.swagger.json
  backend/src/apiserver/model/pipeline.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/server/pipeline_server.go
  backend/src/apiserver/server/pipeline_server_test.go
  backend/src/apiserver/storage/pipeline_store.go
  backend/src/apiserver/storage/pipeline_store_test.go
Labels: lgtm, approved, size/XXL, cla: yes

#7303 feat(sdk)!: drop support for python 3.6
  RELEASE.md
  sdk/RELEASE.md
  sdk/python/requirements.in
  sdk/python/setup.py
Labels: lgtm, approved, size/S

#7313 chore(sdk): bump version to 2.0.0-alpha.0
  sdk/python/kfp/__init__.py
  sdk/python/kfp/v2/compiler_cli_tests/compiler_cli_tests.py
Labels: lgtm, approved, size/XS

#7199 fix(backend): AIP-5634: Add in LRU cache and temp file rotation for metadata-writer. Relates to #4347
  backend/metadata_writer/requirements.in
  backend/metadata_writer/requirements.txt
  backend/metadata_writer/src/metadata_writer.py
Labels: lgtm, approved, size/M, area/backend

#7311 fix(backend): Update composite-controller.yaml to fix https://github.com/kubeflow/manifests/issues/2133
  manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/composite-controller.yaml
Labels: lgtm, approved, size/XS

#7318 chore(release): bump version to 1.8.0 on master branch
  CHANGELOG.md
  VERSION
  backend/api/python_http_client/README.md
  backend/api/python_http_client/docs/PipelineServiceApi.md
  backend/api/python_http_client/kfp_server_api/__init__.py
  backend/api/python_http_client/kfp_server_api/api/pipeline_service_api.py
  backend/api/python_http_client/kfp_server_api/api_client.py
  backend/api/python_http_client/kfp_server_api/configuration.py
  backend/api/python_http_client/setup.py
  backend/api/python_http_client/test/test_pipeline_service_api.py
  backend/api/swagger/kfp_api_single_file.swagger.json
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml
  manifests/gcp_marketplace/schema.yaml
  manifests/gcp_marketplace/test/snapshot-base.yaml
  manifests/gcp_marketplace/test/snapshot-emissary.yaml
  manifests/gcp_marketplace/test/snapshot-managed-storage-with-db-prefix.yaml
  manifests/gcp_marketplace/test/snapshot-managed-storage.yaml
  manifests/kustomize/base/cache-deployer/kustomization.yaml
  manifests/kustomize/base/cache/kustomization.yaml
  manifests/kustomize/base/installs/generic/pipeline-install-config.yaml
  manifests/kustomize/base/metadata/base/kustomization.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/base/pipeline/metadata-writer/kustomization.yaml
  manifests/kustomize/env/gcp/inverse-proxy/kustomization.yaml
Labels: lgtm, approved, size/XL

#7298 chore: upgrade to helm 3
  manifests/gcp_marketplace/test/presubmit.sh
  manifests/gcp_marketplace/test/snapshot-base.yaml
  manifests/gcp_marketplace/test/snapshot-emissary.yaml
  manifests/gcp_marketplace/test/snapshot-managed-storage-with-db-prefix.yaml
  manifests/gcp_marketplace/test/snapshot-managed-storage.yaml
  manifests/gcp_marketplace/test/snapshots.sh
Labels: lgtm, approved, size/XXL

#7314 chore(sdk): Fix a minor bug in task final status test sample
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_task_final_status.json
  sdk/python/kfp/v2/compiler_cli_tests/test_data/pipeline_with_task_final_status.py
Labels: lgtm, approved, size/XS

#7337 fix(backend): Read env var for default service account in multi-user mode. Fix #7336
  backend/src/apiserver/common/config.go
  backend/src/apiserver/config/config.json
  backend/src/apiserver/server/run_server_test.go
  backend/src/apiserver/template/template.go
Labels: lgtm, approved, size/M

#7342 fix(samples): Replace deprecated tfx kubeflow example
  samples/core/tfx-oss/TFX Example.ipynb
Labels: lgtm, approved, size/S, ok-to-test

#7353 chore(release): bump version to 1.8.1 on master branch
  CHANGELOG.md
  VERSION
  backend/api/python_http_client/README.md
  backend/api/python_http_client/kfp_server_api/__init__.py
  backend/api/python_http_client/kfp_server_api/api_client.py
  backend/api/python_http_client/kfp_server_api/configuration.py
  backend/api/python_http_client/setup.py
  backend/api/swagger/kfp_api_single_file.swagger.json
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml
  manifests/gcp_marketplace/schema.yaml
  manifests/gcp_marketplace/test/snapshot-base.yaml
  manifests/gcp_marketplace/test/snapshot-emissary.yaml
  manifests/gcp_marketplace/test/snapshot-managed-storage-with-db-prefix.yaml
  manifests/gcp_marketplace/test/snapshot-managed-storage.yaml
  manifests/kustomize/base/cache-deployer/kustomization.yaml
  manifests/kustomize/base/cache/kustomization.yaml
  manifests/kustomize/base/installs/generic/pipeline-install-config.yaml
  manifests/kustomize/base/metadata/base/kustomization.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/base/pipeline/metadata-writer/kustomization.yaml
  manifests/kustomize/env/gcp/inverse-proxy/kustomization.yaml
Labels: lgtm, approved, size/M
