Repository kubeflow/pipelines, pull requests merged in 2022-07, with the labels that each got.

#7975 chore: update EKS version and increase the EKS cluster creation timeout
  components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests
Labels: lgtm, approved, size/XS

#7976 chore: update the eksctl version required for latest eks version
  components/aws/sagemaker/tests/integration_tests/Dockerfile
Labels: lgtm, approved, size/XS

#7964 chore: standardize bug report issue template
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
Labels: lgtm, approved, needs-ok-to-test, size/M

#7919 feat(frontend) Convert string-type RuntimeConfig parameters to real-type (currently support num, bool, str)
  frontend/src/components/NewRunParametersV2.test.tsx
  frontend/src/components/NewRunParametersV2.tsx
Labels: lgtm, approved, size/L

#7993 chore(sdk): bump kfp version to 2.0.0b1
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
Labels: lgtm, approved, size/S

#7988 test(samples): skip concat placeholder test
  samples/test/config.yaml
Labels: lgtm, approved, size/XS

#7966 feat(frontend): Display two-panel layout and confusion matrices
  frontend/src/components/TwoLevelDropdown.tsx
  frontend/src/components/viewers/MetricsVisualizations.tsx
  frontend/src/pages/CompareV2.test.tsx
  frontend/src/pages/CompareV2.tsx
Labels: lgtm, approved, size/L

#7899 chore: Update oidc commands to include region and add brackets for trust policy
  samples/contrib/aws-samples/README.md
Labels: lgtm, approved, size/XS, ok-to-test

#7615 chore(components/pytorch):kserve migration
  components/PyTorch/pytorch-kfp-components/pytorch_kfp_components/__init__.py
  components/PyTorch/pytorch-kfp-components/templates/deploy_component.yaml
  components/PyTorch/pytorch-kfp-components/templates/prediction_component.yaml
  components/PyTorch/pytorch-kfp-components/tests/test_compile_yamls.py
  samples/contrib/pytorch-samples/Dockerfile
  samples/contrib/pytorch-samples/Pipeline-Bert-Dist.ipynb
  samples/contrib/pytorch-samples/Pipeline-Bert.ipynb
  samples/contrib/pytorch-samples/Pipeline-Cifar10-Captum-Insights.ipynb
  samples/contrib/pytorch-samples/Pipeline-Cifar10-hpo.ipynb
  samples/contrib/pytorch-samples/Pipeline-Cifar10.ipynb
  samples/contrib/pytorch-samples/README.md
  samples/contrib/pytorch-samples/bert/bert_handler.py
  samples/contrib/pytorch-samples/bert/config.properties
  samples/contrib/pytorch-samples/bert/pipeline.py
  samples/contrib/pytorch-samples/bert/sample.txt
  samples/contrib/pytorch-samples/cifar10/config.properties
  samples/contrib/pytorch-samples/cifar10/pipeline.py
  samples/contrib/pytorch-samples/cifar10/tobytes.py
  samples/contrib/pytorch-samples/install-dependencies.sh
  samples/contrib/pytorch-samples/prerequisites.md
  samples/contrib/pytorch-samples/requirements.txt
Labels: lgtm, approved, size/XXL

#7981 feat(frontend): Display HTML and Markdown files
  frontend/src/components/viewers/HTMLViewer.tsx
  frontend/src/components/viewers/MarkdownViewer.tsx
  frontend/src/components/viewers/MetricsVisualizations.tsx
  frontend/src/pages/CompareV2.test.tsx
  frontend/src/pages/CompareV2.tsx
Labels: lgtm, approved, size/L

#7946 feat(backend): update minio-go to support irsa
  backend/src/apiserver/client/minio.go
  backend/src/apiserver/client_manager.go
  backend/src/apiserver/storage/minio_client.go
  backend/src/apiserver/storage/minio_client_fake.go
  backend/src/apiserver/storage/object_store.go
  backend/src/apiserver/storage/object_store_test.go
  backend/third_party_licenses/apiserver.csv
  go.mod
  go.sum
Labels: lgtm, approved, size/M, ok-to-test

#7991 feat(frontend) Support LIST, STRUCT type in RuntimeConfig parameters
  frontend/src/components/NewRunParametersV2.test.tsx
  frontend/src/components/NewRunParametersV2.tsx
Labels: lgtm, approved, size/L

#7867 feat(sdk): add retry policy support to kfp v2
  sdk/RELEASE.md
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/compiler/pipeline_spec_builder.py
  sdk/python/kfp/compiler/test_data/pipelines/pipeline_with_retry.py
  sdk/python/kfp/compiler/test_data/pipelines/pipeline_with_retry.yaml
  sdk/python/kfp/components/pipeline_task.py
  sdk/python/kfp/components/structures.py
  sdk/python/kfp/components/structures_test.py
  sdk/python/requirements.in
Labels: lgtm, approved, size/L

#8004 chore(sdk): Bump SDK version to 1.8.13
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
Labels: lgtm, approved, size/S

#7826 chore(sdk): use markdown for long description content type v1
  sdk/python/setup.py
Labels: lgtm, approved, size/XS

#7979 chore(test): add test infra mysql run cleanup script
  test/tools/clean-mysql-runs/README.md
  test/tools/clean-mysql-runs/clean-mysql-runs.sh
  test/tools/clean-mysql-runs/delete_old_runs.py
  test/tools/clean-mysql-runs/truncate_cache.sql
Labels: lgtm, approved, size/L

#7989 feat(frontend): Add loading and error states for HTML and Markdown displays
  frontend/src/components/Banner.tsx
  frontend/src/pages/CompareV2.test.tsx
  frontend/src/pages/CompareV2.tsx
Labels: lgtm, approved, size/L

#7912 feat(sdk/client): implements overriding caching options at submission
  sdk/RELEASE.md
  sdk/python/kfp/client/client.py
  sdk/python/kfp/client/client_test.py
Labels: lgtm, approved, size/M, ok-to-test

#8016 fix(components): Pin pip version to fix apache-beam[gcp] installation issue
  components/gcp/container/Dockerfile
Labels: lgtm, approved, size/XS

#8010 chore: Avoid duplicate go-licenses tool installation instructions
  backend/README.md
Labels: lgtm, approved, size/XS

#8017 fix: Update mysql image to fix CVE-2022-1292
  .cloudbuild.yaml
  .release.cloudbuild.yaml
  manifests/kustomize/third-party/mysql/base/mysql-deployment.yaml
  test/tag_for_hosted.sh
Labels: lgtm, approved, size/S

#8018 fix: Update GCP marketplace deployer base image
  manifests/gcp_marketplace/deployer/Dockerfile
Labels: lgtm, approved, size/XS

#7802 chore(sdk): update contributing guidelines/tests
  .pre-commit-config.yaml
  sdk/CONTRIBUTING.md
  sdk/python/requirements-dev.txt
  test/presubmit-docformatter-sdk.sh
  test/presubmit-isort-sdk.sh
  test/presubmit-yapf-sdk.sh
Labels: lgtm, approved, size/L

#8022 test: update Argo cli version in sample test
  test/sample-test/Dockerfile
Labels: lgtm, approved, size/XS

#7985 fix(components): fix launch_crd.py to be compatible with kubernetes python SDK API. Fixes #7984
  components/kubeflow/common/launch_crd.py
Labels: lgtm, approved, size/S, ok-to-test

#8025 chore(backend): Use cloud sdk from GCR as base image for cache deployer
  backend/src/cache/deployer/Dockerfile
Labels: lgtm, approved, size/XS

#8028 chore: Update RELEASE.md
  RELEASE.md
Labels: lgtm, approved, size/XS

#8003 feat(frontend): Show error message for invalid input or missing parameters.
  frontend/src/components/NewRunParametersV2.test.tsx
  frontend/src/components/NewRunParametersV2.tsx
  frontend/src/pages/NewRunV2.tsx
Labels: lgtm, approved, size/L

#8030 test(sdk): fix v2 sample test dependency resolution
  backend/src/v2/test/Dockerfile
  backend/src/v2/test/requirements-runner.txt
Labels: lgtm, approved, size/XS

#8024 feat(frontend): Add parent labels to the Compare Table
  frontend/src/components/CompareTable.test.tsx
  frontend/src/components/CompareTable.tsx
  frontend/src/pages/CompareV2.tsx
Labels: lgtm, approved, size/M

#8045 chore: add the missing `.isort.cfg` file
  .isort.cfg
Labels: lgtm, approved, size/XS

#8040 fix(sdk): fixes kfp.components module type annotations, docstrings, and string/bytes processing
  sdk/python/kfp/components/yaml_component.py
  sdk/python/kfp/components/yaml_component_test.py
Labels: lgtm, approved, size/M

#8042 add kfp v2 api reference docs
  docs/_config.yml
  docs/_static/favicon.ico
  docs/_static/kubeflow.png
  docs/conf.py
  docs/config/volume-support.md
  docs/index.rst
  docs/release/feature-stages.md
  docs/release/versioning-policy.md
  docs/requirements.txt
  docs/source/cli.rst
  docs/source/client.rst
  docs/source/compiler.rst
  docs/source/components.rst
  docs/source/dsl.rst
  docs/source/kfp.client.rst
  docs/source/kfp.compiler.rst
  docs/source/kfp.components.rst
  docs/source/kfp.components.structures.kubernetes.rst
  docs/source/kfp.components.structures.rst
  docs/source/kfp.containers.rst
  docs/source/kfp.dsl.rst
  docs/source/kfp.dsl.types.rst
  docs/source/kfp.extensions.rst
  docs/source/kfp.rst
  docs/source/kfp.server_api.rst
  docs/source/registry.rst
  sdk/python/README.md
  sdk/python/kfp/client/__init__.py
  sdk/python/kfp/compiler/__init__.py
  sdk/python/kfp/components/__init__.py
  sdk/python/kfp/dsl/__init__.py
  sdk/python/kfp/registry/__init__.py
Labels: lgtm, approved, size/XL

#8036 feat(frontend): Add KFPv2 namespace check
  frontend/src/components/viewers/MetricsDropdown.tsx
  frontend/src/pages/Compare.tsx
  frontend/src/pages/CompareV1.test.tsx
  frontend/src/pages/CompareV1.tsx
  frontend/src/pages/CompareV2.test.tsx
  frontend/src/pages/CompareV2.tsx
Labels: lgtm, approved, size/L

#8048 fix(sdk): fixes requirements.txt discovery for sdk api reference docs
  .readthedocs.yml
  docs/requirements.txt
Labels: lgtm, approved, size/XS

#8046 feat(frontend): Display ROC curve
  frontend/src/components/viewers/MetricsDropdown.test.tsx
  frontend/src/components/viewers/MetricsVisualizations.tsx
  frontend/src/pages/CompareV2.test.tsx
  frontend/src/pages/CompareV2.tsx
Labels: lgtm, approved, size/L

#8047 chore(sdk): add github release script
  sdk/hack/github_release.sh
  sdk/hack/release.sh
Labels: lgtm, approved, size/M

#8057 docs(sdk): refresh SDK public API docstrings
  .pre-commit-config.yaml
  docs/source/dsl.rst
  sdk/python/kfp/__init__.py
  sdk/python/kfp/cli/utils/parsing_test.py
  sdk/python/kfp/client/__init__.py
  sdk/python/kfp/client/client.py
  sdk/python/kfp/compiler/__init__.py
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/compiler/pipeline_spec_builder.py
  sdk/python/kfp/components/__init__.py
  sdk/python/kfp/components/base_component.py
  sdk/python/kfp/components/component_decorator.py
  sdk/python/kfp/components/importer_node.py
  sdk/python/kfp/components/pipeline_channel.py
  sdk/python/kfp/components/pipeline_context.py
  sdk/python/kfp/components/pipeline_task.py
  sdk/python/kfp/components/pipeline_task_test.py
  sdk/python/kfp/components/python_component.py
  sdk/python/kfp/components/structures.py
  sdk/python/kfp/components/task_final_status.py
  sdk/python/kfp/components/tasks_group.py
  sdk/python/kfp/components/types/artifact_types.py
  sdk/python/kfp/components/types/type_annotations.py
  sdk/python/kfp/components/yaml_component.py
  sdk/python/kfp/dsl/__init__.py
  sdk/python/kfp/registry/__init__.py
  sdk/python/kfp/registry/registry_client.py
Labels: lgtm, approved, size/XXL

#8026 feat(frontend): Display scalar metrics table
  frontend/src/components/viewers/MetricsDropdown.test.tsx
  frontend/src/components/viewers/MetricsDropdown.tsx
  frontend/src/lib/v2/CompareUtils.test.ts
  frontend/src/lib/v2/CompareUtils.ts
  frontend/src/mlmd/MlmdUtils.ts
  frontend/src/pages/CompareV2.test.tsx
  frontend/src/pages/CompareV2.tsx
Labels: lgtm, approved, size/L

#8029 feat(frontend): Display metrics loading and error states
  frontend/src/components/Banner.tsx
  frontend/src/components/viewers/MetricsDropdown.test.tsx
  frontend/src/components/viewers/MetricsDropdown.tsx
  frontend/src/lib/v2/CompareUtils.ts
  frontend/src/pages/CompareV2.test.tsx
  frontend/src/pages/CompareV2.tsx
Labels: lgtm, approved, size/L

#8069 fix(frontend) Missing parameter in the input/output tab of Run details side panel
  frontend/src/components/tabs/InputOutputTab.test.tsx
  frontend/src/components/tabs/InputOutputTab.tsx
Labels: lgtm, approved, size/L

#8023 chore(backend): modify default_experiments and db_statuses tables to have primary keys. Fixes #8014
  backend/src/apiserver/model/db_status.go
  backend/src/apiserver/model/default_experiment.go
Labels: lgtm, approved, size/XS, needs-ok-to-test

#8070 chore: Disable renovatebot
  .github/renovate.json5
Labels: lgtm, approved, size/XS

#8072 chore: Update issue template.
  .github/ISSUE_TEMPLATE/BUG_BACKEND.md
  .github/ISSUE_TEMPLATE/BUG_FRONTEND.md
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/BUG_SDK.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
Labels: lgtm, approved, size/S

#8044 feat(sdk): Allow artifact inputs in pipeline definition.
  sdk/RELEASE.md
  sdk/python/kfp/compiler/compiler.py
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/compiler/pipeline_spec_builder.py
  sdk/python/kfp/compiler/test_data/components/unsupported/artifact_consumer.py
  sdk/python/kfp/compiler/test_data/components/unsupported/output_named_tuple.py
  sdk/python/kfp/compiler/test_data/components/unsupported/train.py
  sdk/python/kfp/compiler/test_data/pipelines/pipeline_with_various_io_types.py
  sdk/python/kfp/compiler/test_data/pipelines/pipeline_with_various_io_types.yaml
  sdk/python/kfp/components/pipeline_channel.py
  sdk/python/kfp/components/structures.py
Labels: lgtm, approved, size/L

#8077 feat(frontend) Show PipelineSpec from an existing Run
  frontend/src/components/PipelineSpecTabContent.tsx
  frontend/src/pages/PipelineDetailsV1.tsx
  frontend/src/pages/PipelineDetailsV2.tsx
  frontend/src/pages/RunDetailsV2.test.tsx
  frontend/src/pages/RunDetailsV2.tsx
Labels: lgtm, approved, size/L
