Repository kubeflow/pipelines, pull requests merged in 2022-10, with the labels that each got.

#8270 feat(backend) add maximum_cache_staleness and default_cache_staleness
  backend/src/cache/server/mutation.go
  backend/src/cache/server/watcher.go
  backend/src/cache/storage/execution_cache_store.go
  backend/src/cache/storage/execution_cache_store_test.go
  manifests/kustomize/base/cache/cache-deployment.yaml
  manifests/kustomize/base/installs/generic/pipeline-install-config.yaml
Labels: lgtm, approved, size/L

#8293 chore(components/pytorch) - fix url paths
  samples/contrib/pytorch-samples/Pipeline-Cifar10-Captum-Insights.ipynb
  samples/contrib/pytorch-samples/Pipeline-Cifar10.ipynb
Labels: lgtm, approved, size/XS

#8331 test: Upgrade kfp version in sagemaker component test
  components/aws/sagemaker/tests/integration_tests/Dockerfile
  components/aws/sagemaker/tests/integration_tests/environment.yml
  components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests
Labels: lgtm, approved, needs-ok-to-test, size/S

#8342 chore: update kserve component owners
  components/kserve/OWNERS
  components/kubeflow/kfserving/OWNERS
Labels: lgtm, approved, size/XS

#8346 test: Make ephemeral sagemaker component tests more stable
  components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests
Labels: lgtm, approved, size/XS, needs-ok-to-test

#8326 feat(frontend): Complete Sub-DAG implementation in KFPv2.
  frontend/src/components/graph/Constants.ts
  frontend/src/components/graph/ExecutionNode.tsx
  frontend/src/components/graph/SubDagNode.tsx
  frontend/src/components/tabs/RuntimeNodeDetailsV2.tsx
  frontend/src/lib/v2/DynamicFlow.test.ts
  frontend/src/lib/v2/DynamicFlow.ts
  frontend/src/lib/v2/StaticFlow.ts
  frontend/src/pages/RunDetailsV2.tsx
  frontend/src/pages/v2/DagCanvas.tsx
Labels: lgtm, approved, size/L

#8361 fix(sdk): Fix PyPi typo in cli/component docstring
  sdk/python/kfp/cli/component.py
Labels: lgtm, approved, size/XS

#8359 fix(sdk): Fix "No KFP components found in file" error. Fixes #8353
  sdk/python/kfp/cli/component.py
Labels: lgtm, approved, size/XS

#8354 fix(frontend): Surface output artifact of a SubDAG by reading subtask
  frontend/src/components/graph/Constants.ts
  frontend/src/lib/v2/DynamicFlow.ts
  frontend/src/lib/v2/StaticFlow.ts
Labels: lgtm, approved, size/M

#8351 fix(backend): Upgrade mysql to 8.0.26
  .cloudbuild.yaml
  .release.cloudbuild.yaml
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/mysql.yaml
  manifests/gcp_marketplace/test/snapshot-base.yaml
  manifests/gcp_marketplace/test/snapshot-emissary.yaml
  manifests/gcp_marketplace/test/snapshot-managed-storage-with-db-prefix.yaml
  manifests/gcp_marketplace/test/snapshot-managed-storage.yaml
  manifests/kustomize/third-party/mysql/base/mysql-deployment.yaml
  test/tag_for_hosted.sh
Labels: lgtm, approved, size/L

#8369 chore: Update backend/OWNERS
  backend/OWNERS
Labels: lgtm, approved, size/XS

#8368 fix(backend): Fix user cache setting P0D ignored by cache server. Fixes #8366
  backend/src/cache/server/mutation.go
  backend/src/cache/server/watcher.go
Labels: lgtm, approved, size/XS

#8336 fix(components): make inputs.model_artifact_url optional in sagemaker model component
  components/aws/sagemaker/Changelog.md
  components/aws/sagemaker/THIRD-PARTY-LICENSES.txt
  components/aws/sagemaker/batch_transform/README.md
  components/aws/sagemaker/batch_transform/component.yaml
  components/aws/sagemaker/batch_transform/src/sagemaker_transform_component.py
  components/aws/sagemaker/create_simulation_app/component.yaml
  components/aws/sagemaker/delete_simulation_app/component.yaml
  components/aws/sagemaker/deploy/component.yaml
  components/aws/sagemaker/ground_truth/component.yaml
  components/aws/sagemaker/ground_truth/src/sagemaker_ground_truth_component.py
  components/aws/sagemaker/hyperparameter_tuning/component.yaml
  components/aws/sagemaker/hyperparameter_tuning/src/sagemaker_tuning_component.py
  components/aws/sagemaker/model/README.md
  components/aws/sagemaker/model/component.yaml
  components/aws/sagemaker/model/src/sagemaker_model_component.py
  components/aws/sagemaker/process/component.yaml
  components/aws/sagemaker/process/src/sagemaker_process_component.py
  components/aws/sagemaker/requirements.txt
  components/aws/sagemaker/rlestimator/component.yaml
  components/aws/sagemaker/simulation_job/component.yaml
  components/aws/sagemaker/simulation_job/src/robomaker_simulation_job_component.py
  components/aws/sagemaker/simulation_job_batch/component.yaml
  components/aws/sagemaker/tests/unit_tests/tests/batch_transform/test_transform_component.py
  components/aws/sagemaker/tests/unit_tests/tests/model/test_model_component.py
  components/aws/sagemaker/train/component.yaml
  components/aws/sagemaker/train/src/sagemaker_training_component.py
  components/aws/sagemaker/workteam/component.yaml
Labels: lgtm, approved, needs-ok-to-test, size/L

#8343 fix(frontend): Use browser-compatible atob instead of Buffer for frontend graph decompression. Fixes #7655
  frontend/src/lib/Utils.tsx
Labels: area/frontend, lgtm, approved, size/XS, ok-to-test

#8371 fix(sdk): Allow using cli `kfp dsl compile` to compile components
  sdk/python/kfp/cli/compile_.py
  sdk/python/kfp/cli/compile_test.py
  sdk/python/kfp/components/pipeline_context.py
  sdk/python/kfp/components/pipeline_context_test.py
Labels: lgtm, approved, size/L

#8372 fix(sdk): fix `kfp component build` only produces empty requirements.txt
  sdk/python/kfp/cli/component.py
  sdk/python/kfp/cli/component_test.py
  sdk/python/kfp/components/component_factory.py
Labels: lgtm, approved, size/M

#8337 chore(sdk): improve KFP SDK reference documentation
  docs/conf.py
  docs/index.rst
  docs/requirements.txt
  docs/source/client.rst
  docs/source/compiler.rst
  docs/source/components.rst
  docs/source/dsl.rst
  docs/source/kfp.rst
  docs/source/registry.rst
  sdk/python/kfp/components/__init__.py
  sdk/python/kfp/components/executor_test.py
  sdk/python/kfp/components/types/custom_artifact_types_test.py
  sdk/python/kfp/components/types/type_annotations.py
  sdk/python/kfp/components/types/type_annotations_test.py
  sdk/python/kfp/dsl/__init__.py
  sdk/python/kfp/registry/__init__.py
Labels: lgtm, approved, size/L

#8367 fix(sdk): Throw exception for component parameter named Output
  sdk/python/kfp/components/component_factory.py
  sdk/python/kfp/components/component_factory_test.py
Labels: lgtm, approved, size/S

#8373 chore(release): release sdk 2.0.0b6
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
Labels: lgtm, approved, size/S

#8303 feat(samples): Full Kubeflow E2E sample using KFPv2.
  samples/contrib/kubeflow-e2e-mnist/OWNERS
  samples/contrib/kubeflow-e2e-mnist/kubeflow-e2e-mnist-kfpv2.ipynb
Labels: lgtm, approved, size/XL

#8384 fix(frontend): Create recurring run by default from recurring run entry point
  frontend/src/lib/Buttons.ts
  frontend/src/pages/AllRecurringRunsList.test.tsx
  frontend/src/pages/AllRecurringRunsList.tsx
Labels: lgtm, approved, size/M

#8383 feat(sdk): add --build-image option to 'kfp components build' to allow users to skip docker build. Fixes #8382 for 1.8
  sdk/python/kfp/cli/components.py
  sdk/python/kfp/cli/components_test.py
Labels: lgtm, approved, size/S, ok-to-test

#8387 feat(sdk): add --build-image option to 'kfp components build' to allow users to skip docker build. Fixes #8382 for 2.0
  sdk/python/kfp/cli/component.py
  sdk/python/kfp/cli/component_test.py
Labels: lgtm, approved, size/M, ok-to-test

#8375 feat(backend): Include namespace in Pipeline API model. Part of #4197
  backend/src/apiserver/server/api_converter.go
Labels: lgtm, approved, size/S

#8389 Test: Update pytest xdist dependency in Sagemaker KFP integration test
  components/aws/sagemaker/tests/integration_tests/environment.yml
  components/aws/sagemaker/tests/integration_tests/resources/config/ack-training-job/config.yaml
Labels: lgtm, approved, size/XS, needs-ok-to-test

#8393 feat(components): add KServe component flag to disable storing CRD status into output parameters
  components/kserve/component.yaml
  components/kserve/src/kservedeployer.py
Labels: lgtm, approved, size/M
