Repository kubeflow/pipelines, pull requests merged in 2023-05, with the labels that each got.

#9265 feature(frontend) Support Logs tab in KFP v2
  frontend/src/components/tabs/RuntimeNodeDetailsV2.test.tsx
  frontend/src/components/tabs/RuntimeNodeDetailsV2.tsx
  frontend/src/pages/RunDetailsV2.tsx
Labels: lgtm, approved, size/L

#9280 fix(frontend): Redirect to recurring run list after creating v1 recurring run.
  frontend/src/pages/NewRun.test.tsx
  frontend/src/pages/NewRun.tsx
Labels: lgtm, approved, size/XS

#9283 chore(frontend): Generate TypeScript client for updated pipeline_spec.proto
  frontend/src/generated/pipeline_spec/google/protobuf/duration.ts
  frontend/src/generated/pipeline_spec/pipeline_spec.ts
  frontend/src/generated/pipeline_spec/pipeline_spec_pb.d.ts
  frontend/src/generated/pipeline_spec/pipeline_spec_pb.js
Labels: lgtm, approved, size/XXL

#9246 fix(backend): Fix timestamp in task store, add disabled unit test
  backend/src/apiserver/storage/task_store.go
  backend/src/apiserver/storage/task_store_test.go
Labels: lgtm, approved, size/L

#9288 chore(frontend): Generate TypeScript client for Kubernetes_executor_config
  frontend/README.md
  frontend/package.json
  frontend/scripts/k8splatformspec.sh
  frontend/src/generated/platform_spec/kubernetes_platform/google/protobuf/struct.ts
  frontend/src/generated/platform_spec/kubernetes_platform/index.ts
  frontend/src/generated/platform_spec/kubernetes_platform/kubernetes_executor_config.ts
  frontend/src/generated/platform_spec/kubernetes_platform/kubernetes_executor_config_pb.d.ts
  frontend/src/generated/platform_spec/kubernetes_platform/kubernetes_executor_config_pb.js
Labels: lgtm, approved, size/XXL

#9290 fix(backend): fix launcher importer error
  backend/src/apiserver/template/template_test.go
  backend/src/v2/compiler/argocompiler/argo.go
  backend/src/v2/compiler/argocompiler/testdata/create_mount_delete_dynamic_pvc.yaml
  backend/src/v2/compiler/argocompiler/testdata/hello_world.yaml
  backend/src/v2/compiler/argocompiler/testdata/importer.yaml
  backend/src/v2/component/importer_launcher.go
  backend/src/v2/metadata/client.go
Labels: lgtm, approved, size/M, area/backend

#9243 feat(components): Sagemaker V2 Hosting components and tests
  components/aws/sagemaker/Changelog.md
  components/aws/sagemaker/Endpoint/README.md
  components/aws/sagemaker/Endpoint/component.yaml
  components/aws/sagemaker/Endpoint/src/Endpoint_component.py
  components/aws/sagemaker/Endpoint/src/Endpoint_request.yaml.tpl
  components/aws/sagemaker/Endpoint/src/Endpoint_spec.py
  components/aws/sagemaker/EndpointConfig/README.md
  components/aws/sagemaker/EndpointConfig/component.yaml
  components/aws/sagemaker/EndpointConfig/src/EndpointConfig_component.py
  components/aws/sagemaker/EndpointConfig/src/EndpointConfig_request.yaml.tpl
  components/aws/sagemaker/EndpointConfig/src/EndpointConfig_spec.py
  components/aws/sagemaker/Model/README.md
  components/aws/sagemaker/Model/component.yaml
  components/aws/sagemaker/Model/src/Model_component.py
  components/aws/sagemaker/Model/src/Model_request.yaml.tpl
  components/aws/sagemaker/Model/src/Model_spec.py
  components/aws/sagemaker/README.md
  components/aws/sagemaker/THIRD-PARTY-LICENSES.v2.txt
  components/aws/sagemaker/TrainingJob/component.yaml
  components/aws/sagemaker/TrainingJob/src/TrainingJob_component.py
  components/aws/sagemaker/TrainingJob/src/TrainingJob_spec.py
  components/aws/sagemaker/commonv2/__init__.py
  components/aws/sagemaker/commonv2/sagemaker_component.py
  components/aws/sagemaker/requirements_v2.txt
  components/aws/sagemaker/tests/integration_tests/component_tests/test_deploy_component.py
  components/aws/sagemaker/tests/integration_tests/component_tests/test_v2_hosting.py
  components/aws/sagemaker/tests/integration_tests/component_tests/test_v2_train_component.py
  components/aws/sagemaker/tests/integration_tests/pytest.ini
  components/aws/sagemaker/tests/integration_tests/resources/config/ack-hosting-update/config.yaml
  components/aws/sagemaker/tests/integration_tests/resources/config/ack-hosting/config.yaml
  components/aws/sagemaker/tests/integration_tests/resources/definition/create_hosting_v2_pipeline.py
  components/aws/sagemaker/tests/integration_tests/resources/definition/update_hosting_v2_pipeline.py
  components/aws/sagemaker/tests/integration_tests/utils/ack_utils.py
  components/aws/sagemaker/tests/integration_tests/utils/sagemaker_utils.py
Labels: lgtm, approved, size/XXL

#9287 [WIP] test: Add v2 upgrade test
  backend/test/v2/integration/upgrade_test.go
  test/api-integration-test/run_test.sh
  test/e2e_test_gke_v2.yaml
  test/upgrade-tests.sh
Labels: lgtm, approved, size/XL

#9296 chore(frontend): Abstract the logic of retrieving pipeline definition in multi-doc yaml file.
  frontend/src/data/test/create_mount_delete_dynamic_pvc.yaml
  frontend/src/generated/pipeline_spec/index.ts
  frontend/src/lib/v2/WorkflowUtils.test.ts
  frontend/src/lib/v2/WorkflowUtils.ts
Labels: lgtm, approved, size/L

#9314 test(components): fix Sagemaker component shallow canary
  components/aws/sagemaker/tests/integration_tests/component_tests/test_v2_hosting.py
  components/aws/sagemaker/tests/integration_tests/utils/sagemaker_utils.py
Labels: lgtm, approved, size/XS

#9297 fix(conformance): enable healthz test in full Kubeflow.
  backend/src/common/client/api_server/v1/healthz_client.go
  backend/test/integration/healthz_api_test.go
Labels: lgtm, approved, size/M

#9315 chore: Update frontend image
  frontend/Dockerfile
Labels: lgtm, approved, size/XS

#9307 chore: upgrade proxy agent image
  proxy/Dockerfile
Labels: lgtm, approved, size/XS

#9232 feat(backend): avoid downcast and use ExecutionSpec if possible
  backend/src/apiserver/server/api_converter.go
  backend/src/apiserver/server/api_converter_test.go
  backend/src/apiserver/server/report_server.go
  backend/src/common/util/execution_status.go
  backend/src/common/util/workflow.go
Labels: lgtm, approved, size/M

#9325 chore(sdk): release KFP SDK 2.0.0b16
  docs/conf.py
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
Labels: lgtm, approved, size/S, do-not-merge/hold

#9328 fix(sdk): fix appengine import error in KFP SDK v1
  sdk/RELEASE.md
  sdk/python/requirements.in
  sdk/python/requirements.txt
  sdk/python/setup.py
Labels: lgtm, approved, size/XS

#9329 chore(sdk): release KFP SDK 1.8.21
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
Labels: lgtm, size/S

#9317 chore(backend): Add 503 error to the backend
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/common/util/error.go
Labels: lgtm, approved, size/M

#9286 fix(backend): Allow empty namespace and remove default namespace. Fixes #8945. Fixes #8897. Fixes #8854.
  backend/src/apiserver/list/list.go
  backend/src/apiserver/main.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/server/api_converter.go
  backend/src/apiserver/server/api_converter_test.go
  backend/src/apiserver/server/api_util_test.go
  backend/src/apiserver/server/experiment_server_test.go
  backend/src/apiserver/server/fakes_test.go
  backend/src/apiserver/server/job_server.go
  backend/src/apiserver/server/job_server_test.go
  backend/src/apiserver/server/pipeline_server.go
  backend/src/apiserver/server/pipeline_server_test.go
  backend/src/apiserver/server/pipeline_upload_server_test.go
  backend/src/apiserver/server/run_server.go
  backend/src/apiserver/server/run_server_test.go
  backend/src/apiserver/server/visualization_server_test.go
  backend/src/apiserver/storage/db.go
  backend/src/apiserver/storage/db_test.go
  backend/src/apiserver/storage/experiment_store.go
  backend/src/apiserver/storage/job_store.go
  backend/src/apiserver/storage/pipeline_store.go
  backend/src/apiserver/storage/task_store.go
Labels: lgtm, approved, size/XXL

#9331 fix(components): Changing path for model
  components/aws/sagemaker/Changelog.md
  components/aws/sagemaker/Endpoint/component.yaml
  components/aws/sagemaker/EndpointConfig/component.yaml
  components/aws/sagemaker/Modelv2/README.md
  components/aws/sagemaker/Modelv2/component.yaml
  components/aws/sagemaker/Modelv2/src/Model_component.py
  components/aws/sagemaker/Modelv2/src/Model_request.yaml.tpl
  components/aws/sagemaker/Modelv2/src/Model_spec.py
  components/aws/sagemaker/THIRD-PARTY-LICENSES.v2.txt
  components/aws/sagemaker/TrainingJob/component.yaml
  components/aws/sagemaker/tests/integration_tests/resources/definition/create_hosting_v2_pipeline.py
  components/aws/sagemaker/tests/integration_tests/resources/definition/update_hosting_v2_pipeline.py
Labels: lgtm, approved, size/S

#9334 fix(frontend): Logs details is not changed when selected other execution node.
  frontend/src/components/tabs/RuntimeNodeDetailsV2.tsx
Labels: lgtm, approved, size/XS

#9335 fix(frontend): Parameter field is missing when creating run from run list
  frontend/src/pages/NewRun.tsx
  test/frontend-integration-test/helloworld.spec.js
Labels: lgtm, approved, size/XS

#9341 chore(repo): Add SECURITY.md. Fixes #9319.
  SECURITY.md
Labels: lgtm, approved, size/XS

#9339 fix(frontend): Incorrect run type after pipeline is selected
  frontend/src/pages/NewRun.tsx
  frontend/src/pages/NewRunV2.tsx
Labels: lgtm, approved, size/S

#9344 fix(frontend): Buttons dislocated in narrow toolbar
  frontend/src/components/Toolbar.tsx
Labels: lgtm, approved, size/XS

#9342 fix(frontend): Failed pipeline version creation should not generate an empty pipeline.
  frontend/src/lib/Apis.ts
  frontend/src/pages/NewPipelineVersion.test.tsx
  frontend/src/pages/NewPipelineVersion.tsx
Labels: lgtm, approved, size/L

#9318 feature(frontend): Support volume mounts in KFP v2
  frontend/src/components/tabs/RuntimeNodeDetailsV2.test.tsx
  frontend/src/components/tabs/RuntimeNodeDetailsV2.tsx
  frontend/src/components/tabs/StaticNodeDetailsV2.tsx
  frontend/src/generated/platform_spec/kubernetes_platform/index.ts
  frontend/src/lib/v2/NodeUtils.tsx
  frontend/src/lib/v2/WorkflowUtils.test.ts
  frontend/src/lib/v2/WorkflowUtils.ts
  frontend/src/pages/RunDetailsV2.tsx
Labels: lgtm, approved, size/L

#9355 chore: release KFP SDK 2.0.0-beta.17
  docs/conf.py
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
  sdk/python/kfp/client/client.py
  sdk/python/requirements.in
  sdk/python/requirements.txt
Labels: lgtm, approved, size/S

#9332 fix(conformance): enable healthz test in full Kubeflow. (#9297)
  backend/src/common/client/api_server/healthz_client.go
  backend/test/integration/healthz_api_test.go
Labels: lgtm, approved, size/M

#9253 feat(components): SageMaker V2 model monitor component and testing
  components/aws/sagemaker/DataQualityJobDefinition/README.md
  components/aws/sagemaker/DataQualityJobDefinition/component.yaml
  components/aws/sagemaker/DataQualityJobDefinition/src/DataQualityJobDefinition_component.py
  components/aws/sagemaker/DataQualityJobDefinition/src/DataQualityJobDefinition_request.yaml.tpl
  components/aws/sagemaker/DataQualityJobDefinition/src/DataQualityJobDefinition_spec.py
  components/aws/sagemaker/ModelBiasJobDefinition/README.md
  components/aws/sagemaker/ModelBiasJobDefinition/component.yaml
  components/aws/sagemaker/ModelBiasJobDefinition/src/ModelBiasJobDefinition_component.py
  components/aws/sagemaker/ModelBiasJobDefinition/src/ModelBiasJobDefinition_request.yaml.tpl
  components/aws/sagemaker/ModelBiasJobDefinition/src/ModelBiasJobDefinition_spec.py
  components/aws/sagemaker/ModelExplainabilityJobDefinition/README.md
  components/aws/sagemaker/ModelExplainabilityJobDefinition/component.yaml
  components/aws/sagemaker/ModelExplainabilityJobDefinition/src/ModelExplainabilityJobDefinition_component.py
  components/aws/sagemaker/ModelExplainabilityJobDefinition/src/ModelExplainabilityJobDefinition_request.yaml.tpl
  components/aws/sagemaker/ModelExplainabilityJobDefinition/src/ModelExplainabilityJobDefinition_spec.py
  components/aws/sagemaker/ModelQualityJobDefinition/README.md
  components/aws/sagemaker/ModelQualityJobDefinition/component.yaml
  components/aws/sagemaker/ModelQualityJobDefinition/src/ModelQualityJobDefinition_component.py
  components/aws/sagemaker/ModelQualityJobDefinition/src/ModelQualityJobDefinition_request.yaml.tpl
  components/aws/sagemaker/ModelQualityJobDefinition/src/ModelQualityJobDefinition_spec.py
  components/aws/sagemaker/MonitoringSchedule/README.md
  components/aws/sagemaker/MonitoringSchedule/component.yaml
  components/aws/sagemaker/MonitoringSchedule/src/MonitoringSchedule_component.py
  components/aws/sagemaker/MonitoringSchedule/src/MonitoringSchedule_request.yaml.tpl
  components/aws/sagemaker/MonitoringSchedule/src/MonitoringSchedule_spec.py
  components/aws/sagemaker/README.md
  components/aws/sagemaker/tests/integration_tests/component_tests/test_v2_monitoring_job_definition_component.py
  components/aws/sagemaker/tests/integration_tests/component_tests/test_v2_monitoring_schedule_component.py
  components/aws/sagemaker/tests/integration_tests/conftest.py
  components/aws/sagemaker/tests/integration_tests/resources/config/v2-monitoring-job-data-quality/config.yaml
  components/aws/sagemaker/tests/integration_tests/resources/config/v2-monitoring-job-model-bias/config.yaml
  components/aws/sagemaker/tests/integration_tests/resources/config/v2-monitoring-job-model-explainability/config.yaml
  components/aws/sagemaker/tests/integration_tests/resources/config/v2-monitoring-job-model-quality/config.yaml
  components/aws/sagemaker/tests/integration_tests/resources/config/v2-monitoring-schedule-update/config.yaml
  components/aws/sagemaker/tests/integration_tests/resources/config/v2-monitoring-schedule/config.yaml
  components/aws/sagemaker/tests/integration_tests/resources/definition/data_quality_job_defi_v2_pipeline.py
  components/aws/sagemaker/tests/integration_tests/resources/definition/model_bias_job_defi_v2_pipeline.py
  components/aws/sagemaker/tests/integration_tests/resources/definition/model_explainability_job_defi_v2_pipeline.py
  components/aws/sagemaker/tests/integration_tests/resources/definition/model_quality_job_defi_v2_pipeline.py
  components/aws/sagemaker/tests/integration_tests/resources/definition/monitoring_schedule_update_v2_pipeline.py
  components/aws/sagemaker/tests/integration_tests/resources/definition/monitoring_schedule_v2_pipeline.py
  components/aws/sagemaker/tests/integration_tests/utils/__init__.py
  components/aws/sagemaker/tests/integration_tests/utils/ack_utils.py
  components/aws/sagemaker/tests/integration_tests/utils/sagemaker_utils.py
  components/aws/sagemaker/tests/unit_tests/tests/MonitoringSchedule/test_MonitoringSchedule_component.py
  components/aws/sagemaker/tests/unit_tests/tests/MonitoringSchedule/test_MonitoringSchedule_spec.py
Labels: lgtm, approved, size/XXL, needs-ok-to-test

#9368 feat(components): SageMaker V2 model monitor component release
  components/aws/sagemaker/Changelog.md
  components/aws/sagemaker/DataQualityJobDefinition/component.yaml
  components/aws/sagemaker/Endpoint/component.yaml
  components/aws/sagemaker/Endpoint/src/Endpoint_component.py
  components/aws/sagemaker/EndpointConfig/component.yaml
  components/aws/sagemaker/EndpointConfig/src/EndpointConfig_component.py
  components/aws/sagemaker/ModelBiasJobDefinition/component.yaml
  components/aws/sagemaker/ModelExplainabilityJobDefinition/component.yaml
  components/aws/sagemaker/ModelQualityJobDefinition/component.yaml
  components/aws/sagemaker/Modelv2/component.yaml
  components/aws/sagemaker/Modelv2/src/Model_component.py
  components/aws/sagemaker/MonitoringSchedule/component.yaml
  components/aws/sagemaker/THIRD-PARTY-LICENSES.v2.txt
  components/aws/sagemaker/TrainingJob/component.yaml
  components/aws/sagemaker/TrainingJob/src/TrainingJob_component.py
Labels: lgtm, approved, needs-ok-to-test, size/M

#9304 fix(backend): change format of some backend error message
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/template/template.go
  backend/src/apiserver/template/v2_template.go
Labels: lgtm, approved, size/M, area/backend

#9388 chore: Create and use license-compliance driver and launcher images
  backend/Dockerfile.driver
  backend/Dockerfile.launcher
  backend/src/apiserver/template/template_test.go
  backend/src/v2/compiler/argocompiler/argo.go
  backend/src/v2/compiler/argocompiler/testdata/create_mount_delete_dynamic_pvc.yaml
  backend/src/v2/compiler/argocompiler/testdata/hello_world.yaml
  backend/src/v2/compiler/argocompiler/testdata/importer.yaml
  backend/third_party_licenses/driver.csv
  backend/third_party_licenses/launcher.csv
Labels: lgtm, approved, size/L

#9374 fix(backend): Add pipeline spec name validation and relax display name validation
  backend/src/apiserver/common/utils.go
  backend/src/apiserver/common/utils_test.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/server/pipeline_server.go
  backend/src/apiserver/server/pipeline_server_test.go
  backend/src/apiserver/server/pipeline_upload_server_test.go
  backend/test/integration/pipeline_api_test.go
  backend/test/integration/pipeline_version_api_test.go
Labels: lgtm, approved, size/L

#9383 fix(frontend): Rename button in pipeline/run details side panel
  frontend/src/components/tabs/RuntimeNodeDetailsV2.tsx
  frontend/src/components/tabs/StaticNodeDetailsV2.test.tsx
  frontend/src/components/tabs/StaticNodeDetailsV2.tsx
Labels: lgtm, approved, size/XS

#9379 fix(frontend): No values in "Finished at" & "Duration" when run is finished
  frontend/src/pages/RunDetailsV2.tsx
Labels: lgtm, approved, size/S

#9380 fix(frontend): Remove redundant "(optional)" text in the optional input fields.
  frontend/src/pages/NewExperiment.tsx
  frontend/src/pages/NewPipelineVersion.tsx
  frontend/src/pages/NewRun.tsx
  frontend/src/pages/NewRunV2.tsx
  frontend/src/pages/__snapshots__/NewExperiment.test.tsx.snap
  frontend/src/pages/__snapshots__/NewPipelineVersion.test.tsx.snap
  frontend/src/pages/__snapshots__/NewRun.test.tsx.snap
Labels: lgtm, approved, size/M

#9381 fix(frontend): Change the empty message of archived experiment list.
  frontend/src/components/ExperimentList.tsx
  frontend/src/components/__snapshots__/ExperimentList.test.tsx.snap
Labels: lgtm, approved, size/S

#9382 fix(frontend): Make the hover text for "Archive" button more informative
  frontend/src/lib/Buttons.ts
  frontend/src/pages/__snapshots__/AllRunsList.test.tsx.snap
  frontend/src/pages/__snapshots__/ExperimentDetails.test.tsx.snap
Labels: lgtm, approved, size/S

#9373 fix(backend): Fix authorization logic and remove redundant DB calls
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/server/experiment_server.go
  backend/src/apiserver/server/experiment_server_test.go
  backend/src/apiserver/server/job_server.go
  backend/src/apiserver/server/job_server_test.go
  backend/src/apiserver/server/pipeline_server.go
  backend/src/apiserver/server/run_server.go
  backend/src/apiserver/server/run_server_test.go
Labels: lgtm, approved, size/L

#9400 chore: Remove unused binaries in cache-deployer, add curl license
  backend/src/cache/deployer/Dockerfile
  third_party/license.txt
Labels: lgtm, approved, size/M

#9080 feat(sdk): support writing `TASK_FINAL_STATUS` parameter type
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/compiler/pipeline_spec_builder.py
  sdk/python/test_data/pipelines/pipeline_as_exit_task.yaml
  sdk/python/test_data/pipelines/pipeline_with_task_final_status.yaml
  sdk/python/test_data/pipelines/pipeline_with_task_final_status_yaml.yaml
Labels: lgtm, approved, size/M

#9390 fix(sdk): fix compilation of boolean constant passed to component
  sdk/RELEASE.md
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/compiler/pipeline_spec_builder.py
Labels: lgtm, approved, size/M

#9378 feature(frontend): Flatten and paginate the execution list
  frontend/src/pages/ExecutionList.test.tsx
  frontend/src/pages/ExecutionList.tsx
Labels: lgtm, approved, size/L

#9399 fix(frontend): Momentary "No graph to show" when pipeline/graph is loading.
  frontend/src/pages/PipelineDetails.tsx
Labels: lgtm, approved, size/S

#9401 fix(frontend): Filter of pipeline selector in create new run page is broken.
  frontend/src/components/CustomTable.tsx
  frontend/src/pages/ResourceSelector.tsx
  frontend/src/pages/__snapshots__/ResourceSelector.test.tsx.snap
Labels: lgtm, approved, size/M

#9370 feature(frontend): Flatten and paginate the artifact list
  frontend/src/pages/ArtifactList.test.tsx
  frontend/src/pages/ArtifactList.tsx
Labels: lgtm, approved, size/L

#9387 fix(frontend) Format container information in pipeline details side panel
  frontend/src/components/tabs/StaticNodeDetailsV2.test.tsx
  frontend/src/components/tabs/StaticNodeDetailsV2.tsx
  frontend/src/generated/pipeline_spec/index.ts
  frontend/src/lib/v2/WorkflowUtils.test.ts
  frontend/src/lib/v2/WorkflowUtils.ts
Labels: lgtm, approved, size/L

#9404 fix(frontend): Show summary button and summary card in pipeline details is disappeared.
  frontend/src/pages/PipelineDetails.tsx
Labels: lgtm, approved, size/S

#9397 fix(backend): prepublish execution in the driver for create/delete pvc
  backend/src/apiserver/template/template_test.go
  backend/src/v2/compiler/argocompiler/argo.go
  backend/src/v2/compiler/argocompiler/testdata/create_mount_delete_dynamic_pvc.yaml
  backend/src/v2/compiler/argocompiler/testdata/hello_world.yaml
  backend/src/v2/compiler/argocompiler/testdata/importer.yaml
  backend/src/v2/config/env.go
  backend/src/v2/driver/driver.go
Labels: lgtm, approved, size/L, area/backend

#9408 chore: add license field to frontend/package.json
  frontend/package.json
Labels: lgtm, approved, size/XS

#9407 fix(sdk): Optimize wait_for_run_completion sdk function to skip an extra wait
  sdk/python/kfp/client/client.py
Labels: lgtm, approved, size/XS

#9082 feat(sdk): support compiling components with `dsl.PipelineTaskFinalStatus` type
  sdk/RELEASE.md
  sdk/python/kfp/compiler/pipeline_spec_builder.py
  sdk/python/kfp/components/structures.py
  sdk/python/kfp/components/types/type_utils.py
  sdk/python/test_data/components/component_with_task_final_status.py
  sdk/python/test_data/components/component_with_task_final_status.yaml
  sdk/python/test_data/test_data_config.yaml
Labels: lgtm, approved, size/L

#9398 chore(components): Update Sagemaker sample to use v2 Hosting components
  samples/contrib/aws-samples/mnist-kmeans-sagemaker/README.md
  samples/contrib/aws-samples/mnist-kmeans-sagemaker/mnist-classification-pipeline.py
Labels: lgtm, approved, size/M

#9384 test(component): Update integration test for Model Monitor component
  components/aws/sagemaker/tests/integration_tests/component_tests/test_v2_monitoring_job_definition_component.py
  components/aws/sagemaker/tests/integration_tests/component_tests/test_v2_monitoring_schedule_component.py
  components/aws/sagemaker/tests/integration_tests/utils/kfp_client_utils.py
Labels: lgtm, approved, needs-ok-to-test, size/L

#9423 docs(sdk): add dsl placeholder exports
  sdk/python/kfp/dsl/__init__.py
Labels: lgtm, approved, size/XS

#9405 chore(components): Add sample for Sagemaker Model Monitor component
  samples/contrib/aws-samples/README.md
  samples/contrib/aws-samples/hosting_model_monitor_pipeline/README.md
  samples/contrib/aws-samples/hosting_model_monitor_pipeline/hosting_model_monitor_pipeline.py
  samples/contrib/aws-samples/hosting_model_monitor_pipeline/model-monitor/baselining/data_quality/constraints.json
  samples/contrib/aws-samples/hosting_model_monitor_pipeline/model-monitor/baselining/data_quality/statistics.json
  samples/contrib/aws-samples/hosting_model_monitor_pipeline/requirements.txt
Labels: lgtm, approved, size/XXL, needs-ok-to-test

#9422 test: remove test dependency on driver/launcher images
  backend/src/apiserver/template/template_test.go
  backend/src/v2/compiler/argocompiler/argo_test.go
  backend/src/v2/compiler/argocompiler/testdata/create_mount_delete_dynamic_pvc.yaml
  backend/src/v2/compiler/argocompiler/testdata/hello_world.yaml
  backend/src/v2/compiler/argocompiler/testdata/importer.yaml
Labels: lgtm, approved, size/M, area/backend

#9432 chore: Add more licenses for cache-deployer image
  third_party/license.txt
Labels: lgtm, approved, size/XL

#9429 chore(sdk): release KFP SDK 2.0.0-rc.1
  docs/conf.py
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
  sdk/python/requirements.in
  sdk/python/requirements.txt
Labels: lgtm, approved, size/S

#9435 docs(sdk): normalize docs dropdown format for rc
  docs/conf.py
Labels: size/XS

#9436 docs(sdk): fix branch tag in dropdown
  docs/conf.py
Labels: size/XS

#9437 chore(sdk): loosen pyyaml version requirement
  sdk/RELEASE.md
  sdk/python/requirements.in
  sdk/python/setup.py
Labels: lgtm, approved, size/XS

#7862 chore: update KServe component to support 0.8.0
  components/kserve/Dockerfile
  components/kserve/README.md
  components/kserve/component.yaml
  components/kserve/requirements.txt
  components/kserve/src/kservedeployer.py
Labels: lgtm, approved, size/S, ok-to-test

#9444 chore(sdk): release KFP SDK 1.8.22
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
Labels: lgtm, approved, size/S

#9428 chore(backend): Add golangci-lint and pre-commit config
  .golangci.yaml
  .pre-commit-config.yaml
  backend/README.md
Labels: lgtm, approved, size/M

#9446 chore(components): Update KServe component to 0.10.1 for kubeflow 1.7 support
  components/kserve/README.md
  components/kserve/component.yaml
  components/kserve/requirements.txt
  components/kserve/src/kservedeployer.py
Labels: lgtm, approved, size/S

#9440 feature(frontent): Support both "Flat" and "Group" view for Execution list
  frontend/src/components/Router.tsx
  frontend/src/pages/ExecutionList.test.tsx
  frontend/src/pages/ExecutionList.tsx
  frontend/src/pages/ExecutionListSwitcher.tsx
  frontend/src/pages/ExecutionListSwticher.test.tsx
Labels: lgtm, approved, size/L

#9433 feat(frontend): make container name configurable
  frontend/server/app.ts
  frontend/server/configs.ts
  frontend/server/handlers/pod-logs.ts
  frontend/server/k8s-helper.ts
  frontend/server/workflow-helper.test.ts
  frontend/server/workflow-helper.ts
Labels: lgtm, approved, size/M

#9425 chore: change sample PVC access modes to ReadWriteOnce
  backend/src/apiserver/server/test/pipeline_with_volume.yaml
  backend/src/apiserver/template/testdata/pipeline_with_volume.yaml
  backend/src/v2/compiler/argocompiler/testdata/create_mount_delete_dynamic_pvc.yaml
  backend/src/v2/compiler/testdata/create_mount_delete_dynamic_pvc.json
  frontend/src/data/test/create_mount_delete_dynamic_pvc.yaml
  kubernetes_platform/python/README.md
  kubernetes_platform/python/test/snapshot/data/create_mount_delete_dynamic_pvc.py
  kubernetes_platform/python/test/snapshot/data/create_mount_delete_dynamic_pvc.yaml
  kubernetes_platform/python/test/snapshot/data/create_mount_delete_existing_pvc.py
  kubernetes_platform/python/test/snapshot/data/create_mount_delete_existing_pvc.yaml
  kubernetes_platform/python/test/snapshot/data/create_mount_delete_existing_pvc_from_task_output.py
  kubernetes_platform/python/test/snapshot/data/create_mount_delete_existing_pvc_from_task_output.yaml
Labels: lgtm, approved, size/M, area/kubernetes_platform

#9416 fix(backend): Add creation of pipeline and pipeline version atomically
  backend/api/v2beta1/go_client/pipeline.pb.go
  backend/api/v2beta1/go_client/pipeline.pb.gw.go
  backend/api/v2beta1/go_http_client/pipeline_client/pipeline_service/create_pipeline_and_version_parameters.go
  backend/api/v2beta1/go_http_client/pipeline_client/pipeline_service/create_pipeline_and_version_responses.go
  backend/api/v2beta1/go_http_client/pipeline_client/pipeline_service/pipeline_service_client.go
  backend/api/v2beta1/go_http_client/pipeline_model/v2beta1_create_pipeline_and_version_request.go
  backend/api/v2beta1/go_http_client/pipeline_model/v2beta1_pipeline_version.go
  backend/api/v2beta1/pipeline.proto
  backend/api/v2beta1/python_http_client/README.md
  backend/api/v2beta1/python_http_client/docs/PipelineServiceApi.md
  backend/api/v2beta1/python_http_client/kfp_server_api/api/pipeline_service_api.py
  backend/api/v2beta1/python_http_client/test/test_pipeline_service_api.py
  backend/api/v2beta1/swagger/kfp_api_single_file.swagger.json
  backend/api/v2beta1/swagger/pipeline.swagger.json
  backend/src/apiserver/server/pipeline_server.go
  backend/src/apiserver/server/pipeline_server_test.go
  backend/src/common/client/api_server/v2/pipeline_client.go
  backend/src/common/client/api_server/v2/pipeline_client_fake.go
  backend/test/v2/integration/pipeline_api_test.go
Labels: lgtm, approved, size/XXL

#9450 fix(frontend): Incorrect page title after switching to another pipeline version.
  frontend/src/pages/PipelineDetails.tsx
Labels: lgtm, approved, size/S

#9402 test(components): Check the Sagemaker component output rather than Controller
  components/aws/sagemaker/tests/integration_tests/component_tests/test_v2_hosting.py
  components/aws/sagemaker/tests/integration_tests/component_tests/test_v2_train_component.py
Labels: lgtm, approved, size/M

#9417 docs(components): Update Sagemaker Component Readme
  components/aws/sagemaker/README.md
Labels: lgtm, approved, needs-ok-to-test, size/L

#9458 fix(frontend): Parameter is missing in run creation page. Closes #9441
  frontend/src/pages/NewExperiment.test.tsx
  frontend/src/pages/NewExperiment.tsx
Labels: lgtm, approved, size/S

#9478 chore: prefix sdk release tags with `sdk-`
  sdk/hack/github_release.sh
Labels: lgtm, approved, size/XS

#9477 chore: exclude `sdk-` tags when preparing base deployment for upgrade test
  test/deploy-pipeline-lite.sh
  test/upgrade-tests.sh
Labels: lgtm, approved, size/XS

#9481 fix(sdk): relax executor type checking
  sdk/RELEASE.md
  sdk/python/kfp/components/executor.py
  sdk/python/kfp/components/executor_test.py
Labels: lgtm, approved, size/M

#9473 fix(backend): upgrade to `gopkg.in/yaml.v3` to fix boolean support. Fixes #9451
  backend/src/apiserver/template/template.go
  backend/src/apiserver/template/template_test.go
  backend/src/apiserver/template/testdata/hello_world.yaml
  backend/src/apiserver/template/v2_template.go
  backend/src/v2/metadata/client.go
  backend/third_party_licenses/apiserver.csv
  backend/third_party_licenses/cache_server.csv
  backend/third_party_licenses/persistence_agent.csv
  backend/third_party_licenses/swf.csv
  backend/third_party_licenses/viewer.csv
  go.mod
  go.sum
Labels: lgtm, approved, size/L

#9509 chore: temporarily disable frontend license tool
  frontend/Dockerfile
Labels: lgtm, approved, size/XS

#9497 fix(frontend): Run name should be empty if no pipeline is selected
  frontend/src/pages/NewRun.tsx
Labels: lgtm, approved, size/XS

#9461 feature(frontend): Support non-English characters and special characters in pipeline "display" name
  frontend/src/pages/NewPipelineVersion.test.tsx
  frontend/src/pages/NewPipelineVersion.tsx
Labels: lgtm, approved, size/M

#9467 fix(frontend): Toolbar in pipeline details (from run) should only have "Clone run" button
  frontend/src/pages/PipelineDetails.test.tsx
  frontend/src/pages/PipelineDetails.tsx
Labels: lgtm, approved, size/M

#9463 fix(frontend): Incorrect selected version in summary card
  frontend/src/pages/PipelineDetails.tsx
  frontend/src/pages/PipelineDetailsV2.test.tsx
Labels: lgtm, approved, size/L

#9499 fix(frontend): Choose button is disable even if pipeline is already selected (after uploading a new pipeline)
  frontend/src/pages/NewRun.test.tsx
  frontend/src/pages/NewRun.tsx
Labels: lgtm, approved, size/M

#9511 fix(frontend): Make pipeline definition in YAML tab more readable
  frontend/src/components/PipelineSpecTabContent.tsx
Labels: lgtm, approved, size/S

#9519 fix(frontend): Unexpected page crash when clicking artifact node.
  frontend/src/components/ArtifactPreview.test.tsx
  frontend/src/components/ArtifactPreview.tsx
  frontend/src/components/tabs/RuntimeNodeDetailsV2.tsx
Labels: lgtm, approved, size/S

#9502 feat(backend): Implement aws-go-sdk crendentials to support IRSA for s3 in V2
  backend/src/v2/objectstore/object_store.go
Labels: lgtm, approved, size/M

#9513 fix(backend): publish launcher execution even if it fails
  backend/src/v2/compiler/argocompiler/argo.go
  backend/src/v2/component/launcher_v2.go
Labels: lgtm, approved, size/M, area/backend
