Repository kubeflow/pipelines, pull requests merged in 2023-10, with the labels that each got.

#10054 docs(sdk): use build.os
  .readthedocs.yml
Labels: lgtm, size/XS

#10034 chore(sdk): wrap conditional branch groups in outer pipeline
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/compiler/pipeline_spec_builder.py
  sdk/python/kfp/dsl/tasks_group.py
  sdk/python/test_data/pipelines/if_elif_else.yaml
  sdk/python/test_data/pipelines/if_elif_else_complex.py
  sdk/python/test_data/pipelines/if_elif_else_complex.yaml
  sdk/python/test_data/pipelines/if_else.yaml
Labels: lgtm, approved, size/XL

#10062 chore(component): Update KServe component to support Kubeflow 1.8
  components/kserve/README.md
  components/kserve/component.yaml
  components/kserve/requirements.txt
Labels: lgtm, approved, size/XS

#10044 Intel oneAPI XGBoost daal4py example pipeline
  samples/contrib/intel-oneapi-samples/README.md
  samples/contrib/intel-oneapi-samples/assets/intel-xgb-d4p-pipeline-roc-curve.png
  samples/contrib/intel-oneapi-samples/assets/intel-xgb-d4p-pipeline.png
  samples/contrib/intel-oneapi-samples/assets/logo-classicblue-800px.png
  samples/contrib/intel-oneapi-samples/intel_xgboost_daal4py_pipeline.py
Labels: lgtm, approved, needs-ok-to-test, size/XL

#10064 chore: Update OWNERS
  backend/OWNERS
  kubernetes_platform/OWNERS
  test/OWNERS
Labels: lgtm, approved, size/XS

#10069 fix(sdk): fix incorrect sub-DAG output type when using `dsl.Collected`
  sdk/RELEASE.md
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/compiler/pipeline_spec_builder.py
  sdk/python/test_data/pipelines/if_elif_else_complex.yaml
  sdk/python/test_data/pipelines/parallelfor_fan_in/conditional_producer_and_consumers.yaml
  sdk/python/test_data/pipelines/parallelfor_fan_in/nested_with_parameters.yaml
  sdk/python/test_data/pipelines/parallelfor_fan_in/parameters_complex.yaml
  sdk/python/test_data/pipelines/parallelfor_fan_in/parameters_simple.yaml
  sdk/python/test_data/pipelines/parallelfor_fan_in/pipeline_producer_consumer.yaml
Labels: lgtm, approved, size/L

#10070 chore(sdk): clean up compiler_test.py
  sdk/python/kfp/compiler/compiler_test.py
Labels: lgtm, approved, size/L

#10072 chore(backend): Update driver and launcher license files
  backend/Makefile
  backend/third_party_licenses/driver.csv
  backend/third_party_licenses/launcher.csv
Labels: lgtm, approved, size/M

#9576 feat(backend): Added metrics to be collected from failed/successful workflows
  backend/src/apiserver/main.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/server/api_util_test.go
  backend/src/apiserver/server/experiment_server_test.go
  backend/src/apiserver/server/fakes_test.go
  backend/src/apiserver/server/job_server_test.go
  backend/src/apiserver/server/pipeline_server_test.go
  backend/src/apiserver/server/pipeline_upload_server_test.go
  backend/src/apiserver/server/run_server.go
  backend/src/apiserver/server/run_server_test.go
  backend/src/apiserver/server/visualization_server_test.go
  backend/src/common/util/metrics.go
  backend/third_party_licenses/apiserver.csv
  backend/third_party_licenses/cache_server.csv
  backend/third_party_licenses/driver.csv
  backend/third_party_licenses/launcher.csv
  backend/third_party_licenses/persistence_agent.csv
  backend/third_party_licenses/swf.csv
  backend/third_party_licenses/viewer.csv
  go.mod
  go.sum
Labels: lgtm, approved, size/L, ok-to-test

#10076 feat(backend): Update driver and launcher images
  backend/Dockerfile.driver
  backend/Dockerfile.launcher
  backend/src/v2/compiler/argocompiler/argo.go
Labels: lgtm, approved, size/XS

#10094 fix(sdk): Fix OOB for IPython and refactor. Closes #10075.
  sdk/python/kfp/client/auth.py
  sdk/python/kfp/client/auth_test.py
  sdk/python/kfp/client/client.py
  sdk/python/kfp/client/client_test.py
Labels: lgtm, approved, size/L

#10101 chore(sdk): Improve a message printed for users. Closes #10100
  sdk/python/kfp/client/auth.py
Labels: lgtm, approved, size/XS

#10099 fix(frontend): Replace twitter artifactory endpoint with npm endpoint.
  frontend/.nvmrc
  frontend/package-lock.json
Labels: lgtm, approved, size/XS

#10116 fix(sdk): fix bug when `dsl.importer` argument is provided by loop variable
  sdk/RELEASE.md
  sdk/python/kfp/compiler/pipeline_spec_builder.py
  sdk/python/kfp/dsl/for_loop.py
  sdk/python/kfp/dsl/importer_node_test.py
Labels: lgtm, approved, size/L

#9932 feat(sdk): support a Pythonic artifact authoring style
  sdk/RELEASE.md
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/dsl/__init__.py
  sdk/python/kfp/dsl/component_factory.py
  sdk/python/kfp/dsl/executor.py
  sdk/python/kfp/dsl/executor_test.py
  sdk/python/kfp/dsl/types/artifact_types.py
  sdk/python/kfp/dsl/types/artifact_types_test.py
  sdk/python/kfp/dsl/types/type_annotations.py
  sdk/python/kfp/dsl/types/type_annotations_test.py
  sdk/python/test_data/pipelines/pythonic_artifact_with_single_return.py
  sdk/python/test_data/pipelines/pythonic_artifact_with_single_return.yaml
  sdk/python/test_data/pipelines/pythonic_artifacts_with_list_of_artifacts.py
  sdk/python/test_data/pipelines/pythonic_artifacts_with_list_of_artifacts.yaml
  sdk/python/test_data/pipelines/pythonic_artifacts_with_multiple_returns.py
  sdk/python/test_data/pipelines/pythonic_artifacts_with_multiple_returns.yaml
  sdk/python/test_data/test_data_config.yaml
  test/sdk-execution-tests/requirements.txt
  test/sdk-execution-tests/sdk_execution_tests.py
Labels: lgtm, approved, size/XXL

#10124 docs(sdk): add KFP SDK reference docs local build script
  docs/build_docs_locally.sh
Labels: lgtm, approved, size/S

#10128 chore(sdk): add test for key error bug resolved in #10067
  sdk/python/kfp/compiler/compiler_test.py
Labels: lgtm, approved, size/S

#10020 chore(frontend): update all references to python 3.9
  frontend/mock-backend/data/v2/pipeline/lightweight_python_functions_v2_pipeline.json
  frontend/mock-backend/data/v2/pipeline/lightweight_python_functions_v2_pipeline_rev.yaml
  frontend/mock-backend/data/v2/pipeline/pipeline_with_loops_and_conditions.json
  frontend/mock-backend/data/v2/pipeline/pipeline_with_loops_and_conditions.yaml
  frontend/mock-backend/data/v2/pipeline/protobuf_value_params_v2.json
  frontend/mock-backend/data/v2/pipeline/xgboost_sample_pipeline.json
  frontend/mock-backend/data/v2/pipeline/xgboost_sample_pipeline.yaml
  frontend/src/components/tabs/StaticNodeDetailsV2.test.tsx
  frontend/src/data/test/create_mount_delete_dynamic_pvc.yaml
  frontend/src/data/test/lightweight_python_functions_v2_pipeline_rev.yaml
  frontend/src/data/test/pipeline_with_loops_and_conditions.yaml
  frontend/src/data/test/xgboost_sample_pipeline.yaml
  frontend/src/lib/v2/WorkflowUtils.test.ts
Labels: lgtm, approved, size/L

#10136 feat(components) Extend kserve component
  components/kserve/README.md
  components/kserve/component.yaml
  components/kserve/src/kservedeployer.py
Labels: lgtm, approved, size/M, ok-to-test

#10139 chore(sdk): add Python 3.7 EOL notice
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
  sdk/python/kfp/dsl/component_factory.py
  sdk/python/kfp/dsl/component_factory_test.py
  sdk/python/kfp/init_test.py
Labels: lgtm, approved, size/M

#10159 chore(sdk): Remove the ` (<type>)`from docstring args.
  sdk/python/kfp/compiler/read_write_test.py
Labels: lgtm, approved, size/S

#10160 chore(sdk): add pytest.ini file
  pytest.ini
Labels: lgtm, approved, size/XS

#10158 fix(sdk): type annotation for client credentials
  sdk/python/kfp/client/client.py
Labels: lgtm, approved, size/XS

#10161 chore(sdk): fix local test failure
  sdk/python/kfp/cli/component_test.py
Labels: lgtm, approved, size/XS

#10162 feat(backend): Support consuming parent DAG input artifact
  backend/src/v2/driver/driver.go
Labels: lgtm, approved, size/S

#10164 feat(backend): Update driver and launcher images
  backend/src/v2/compiler/argocompiler/argo.go
Labels: lgtm, approved, size/XS

#10167 chore(sdk): release KFP SDK 2.4.0
  docs/conf.py
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
Labels: lgtm, approved, size/S

#10170 docs(sdk): fix readthedocs build error
  .readthedocs.yml
Labels: lgtm, approved, size/XS

#10173 docs(sdk): fix readthedocs build error, additional changes
  .readthedocs.yml
Labels: lgtm, approved, size/XS
