Repository kubeflow/pipelines, pull requests merged in 2023-09, with the labels that each got.

#9948 chore(frontend): Refactor NewExperiment to functional component
  frontend/src/pages/NewExperiment.tsx
  frontend/src/pages/functional_components/NewExperimentFC.test.tsx
  frontend/src/pages/functional_components/NewExperimentFC.tsx
Labels: lgtm, approved, size/XL

#9896 chore(sdk): release kfp sdk 2.1.3
  docs/OWNERS
  docs/conf.py
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
  sdk/python/kfp/dsl/component_factory_test.py
Labels: lgtm, approved, size/M, ok-to-test

#9959 chore(sdk): remove old file
  sdk/python/install_from_source.sh
Labels: lgtm, approved, size/XS

#9957 feat(backend): enforce SA Token based auth b/w Persistence Agent and Pipeline API Server
  backend/src/agent/persistence/client/fake_namespace.go
  backend/src/agent/persistence/client/kubernetes_core.go
  backend/src/agent/persistence/client/kubernetes_core_fake.go
  backend/src/agent/persistence/client/pipeline_client.go
  backend/src/agent/persistence/client/pipeline_client_fake.go
  backend/src/agent/persistence/main.go
  backend/src/agent/persistence/persistence_agent.go
  backend/src/agent/persistence/worker/metrics_reporter.go
  backend/src/agent/persistence/worker/metrics_reporter_test.go
  backend/src/agent/persistence/worker/persistence_worker_test.go
  backend/src/agent/persistence/worker/workflow_saver.go
  backend/src/agent/persistence/worker/workflow_saver_test.go
  backend/src/common/util/execution_status.go
  backend/src/common/util/workflow.go
  backend/third_party_licenses/persistence_agent.csv
  manifests/kustomize/base/installs/multi-user/persistence-agent/cluster-role.yaml
  manifests/kustomize/base/installs/multi-user/persistence-agent/deployment-patch.yaml
  manifests/kustomize/base/installs/multi-user/persistence-agent/kustomization.yaml
  manifests/kustomize/base/installs/multi-user/persistence-agent/params.env
  manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-role.yaml
Labels: lgtm, approved, size/L

#9894 feat(sdk): support dsl.If, dsl.Elif, and dsl.Else
  sdk/RELEASE.md
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/compiler/compiler_utils.py
  sdk/python/kfp/compiler/pipeline_spec_builder.py
  sdk/python/kfp/dsl/__init__.py
  sdk/python/kfp/dsl/pipeline_channel.py
  sdk/python/kfp/dsl/pipeline_context.py
  sdk/python/kfp/dsl/tasks_group.py
  sdk/python/kfp/dsl/tasks_group_test.py
  sdk/python/test_data/pipelines/if_elif_else.py
  sdk/python/test_data/pipelines/if_elif_else.yaml
  sdk/python/test_data/pipelines/if_elif_else_complex.py
  sdk/python/test_data/pipelines/if_elif_else_complex.yaml
  sdk/python/test_data/pipelines/if_else.py
  sdk/python/test_data/pipelines/if_else.yaml
  sdk/python/test_data/test_data_config.yaml
Labels: lgtm, approved, size/XXL

#9951 chore(frontend): Improve structure of NewExperimentFC.
  frontend/src/pages/NewRun.test.tsx
  frontend/src/pages/functional_components/NewExperimentFC.tsx
Labels: lgtm, approved, size/M

#9982 fix(sdk): fix --no-deps flag usage
  sdk/python/kfp/dsl/component_factory.py
  sdk/python/kfp/dsl/component_factory_test.py
  sdk/python/test_data/components/add_numbers.yaml
  sdk/python/test_data/components/component_with_metadata_fields.yaml
  sdk/python/test_data/components/component_with_pip_install.yaml
  sdk/python/test_data/components/component_with_task_final_status.yaml
  sdk/python/test_data/components/concat_message.yaml
  sdk/python/test_data/components/container_io.yaml
  sdk/python/test_data/components/container_no_input.yaml
  sdk/python/test_data/components/container_with_artifact_output.yaml
  sdk/python/test_data/components/container_with_concat_placeholder.yaml
  sdk/python/test_data/components/container_with_if_placeholder.yaml
  sdk/python/test_data/components/container_with_placeholder_in_fstring.yaml
  sdk/python/test_data/components/containerized_python_component.yaml
  sdk/python/test_data/components/dict_input.yaml
  sdk/python/test_data/components/identity.yaml
  sdk/python/test_data/components/input_artifact.yaml
  sdk/python/test_data/components/nested_return.yaml
  sdk/python/test_data/components/output_metrics.yaml
  sdk/python/test_data/components/preprocess.yaml
  sdk/python/test_data/pipelines/component_with_optional_inputs.yaml
  sdk/python/test_data/pipelines/component_with_pip_index_urls.yaml
  sdk/python/test_data/pipelines/components_with_optional_artifacts.yaml
  sdk/python/test_data/pipelines/if_elif_else.yaml
  sdk/python/test_data/pipelines/if_elif_else_complex.yaml
  sdk/python/test_data/pipelines/if_else.yaml
  sdk/python/test_data/pipelines/lightweight_python_functions_pipeline.yaml
  sdk/python/test_data/pipelines/lightweight_python_functions_with_outputs.yaml
  sdk/python/test_data/pipelines/parallelfor_fan_in/artifacts_complex.yaml
  sdk/python/test_data/pipelines/parallelfor_fan_in/artifacts_simple.yaml
  sdk/python/test_data/pipelines/parallelfor_fan_in/conditional_producer_and_consumers.yaml
  sdk/python/test_data/pipelines/parallelfor_fan_in/nested_with_parameters.yaml
  sdk/python/test_data/pipelines/parallelfor_fan_in/parameters_complex.yaml
  sdk/python/test_data/pipelines/parallelfor_fan_in/parameters_simple.yaml
  sdk/python/test_data/pipelines/parallelfor_fan_in/pipeline_producer_consumer.yaml
  sdk/python/test_data/pipelines/pipeline_as_exit_task.yaml
  sdk/python/test_data/pipelines/pipeline_in_pipeline.yaml
  sdk/python/test_data/pipelines/pipeline_in_pipeline_complex.yaml
  sdk/python/test_data/pipelines/pipeline_in_pipeline_loaded_from_yaml.yaml
  sdk/python/test_data/pipelines/pipeline_with_condition.yaml
  sdk/python/test_data/pipelines/pipeline_with_dynamic_importer_metadata.yaml
  sdk/python/test_data/pipelines/pipeline_with_env.yaml
  sdk/python/test_data/pipelines/pipeline_with_exit_handler.yaml
  sdk/python/test_data/pipelines/pipeline_with_google_artifact_type.yaml
  sdk/python/test_data/pipelines/pipeline_with_importer.yaml
  sdk/python/test_data/pipelines/pipeline_with_loops.yaml
  sdk/python/test_data/pipelines/pipeline_with_loops_and_conditions.yaml
  sdk/python/test_data/pipelines/pipeline_with_metadata_fields.yaml
  sdk/python/test_data/pipelines/pipeline_with_metrics_outputs.yaml
  sdk/python/test_data/pipelines/pipeline_with_multiple_exit_handlers.yaml
  sdk/python/test_data/pipelines/pipeline_with_nested_conditions.yaml
  sdk/python/test_data/pipelines/pipeline_with_nested_loops.yaml
  sdk/python/test_data/pipelines/pipeline_with_outputs.yaml
  sdk/python/test_data/pipelines/pipeline_with_parallelfor_parallelism.yaml
  sdk/python/test_data/pipelines/pipeline_with_params_containing_format.yaml
  sdk/python/test_data/pipelines/pipeline_with_placeholders.yaml
  sdk/python/test_data/pipelines/pipeline_with_retry.yaml
  sdk/python/test_data/pipelines/pipeline_with_task_final_status.yaml
  sdk/python/test_data/pipelines/pipeline_with_task_using_ignore_upstream_failure.yaml
  sdk/runtime_tests/test_data/pipeline_with_task_final_status.yaml
Labels: lgtm, approved, size/XL

#9984 chore(sdk): release KFP SDK 2.2.0
  docs/conf.py
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
Labels: lgtm, approved, size/S

#9988 test: fix sdk execution test
  sdk/python/test_data/test_data_config.yaml
  test/sdk-execution-tests/sdk_execution_tests.py
Labels: lgtm, approved, size/XS

#9720 Fix(frontend): content is not available
  frontend/src/lib/v2/DynamicFlow.test.ts
  frontend/src/lib/v2/DynamicFlow.ts
Labels: lgtm, approved, size/M, ok-to-test

#9990 chore(sdk): refactor python component executor
  sdk/python/kfp/dsl/executor.py
Labels: lgtm, approved, size/L

#10005 chore(sdk): test observability, refactorings, and cleanup
  sdk/python/kfp/cli/utils/aliased_plurals_group.py
  sdk/python/kfp/cli/utils/deprecated_alias_group.py
  sdk/python/kfp/client/auth.py
  sdk/python/kfp/compiler/pipeline_spec_builder.py
  sdk/python/kfp/compiler/read_write_test.py
  sdk/python/kfp/dsl/component_factory.py
  sdk/python/kfp/dsl/structures.py
  sdk/python/kfp/dsl/types/custom_artifact_types.py
  sdk/python/kfp/dsl/types/type_annotations.py
  sdk/python/kfp/dsl/types/type_annotations_test.py
  sdk/python/kfp/dsl/types/type_utils.py
  sdk/python/test_data/pipelines/pipeline_with_google_artifact_type.py
Labels: lgtm, approved, size/L

#10010 feat(sdk): support `PipelineTaskFinalStatus` in tasks that use `.ignore_upstream_failure()`
  sdk/RELEASE.md
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/compiler/pipeline_spec_builder.py
  sdk/python/kfp/dsl/pipeline_task.py
  sdk/python/kfp/dsl/types/type_utils.py
Labels: lgtm, approved, size/L

#10009 fix(backend): update requirements scripts
  backend/Dockerfile.visualization
  backend/README.md
  backend/metadata_writer/Dockerfile
  backend/metadata_writer/README.md
  backend/metadata_writer/requirements.txt
  backend/metadata_writer/update_requirements.sh
  backend/requirements.txt
  backend/src/apiserver/visualization/requirements-test.txt
  backend/src/apiserver/visualization/requirements.in
  backend/src/apiserver/visualization/requirements.txt
  backend/src/apiserver/visualization/update_requirements.sh
  backend/update_requirements.sh
  hack/update-all-requirements.sh
  hack/update-requirements.sh
Labels: lgtm, approved, size/XL

#10023 chore: fix go mod file
  go.sum
Labels: size/XS

#10024 chore(sdk): release KFP SDK 2.3.0
  docs/conf.py
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
Labels: lgtm, approved, size/S

#9946 fix(backend): OutPutPath dir creation mode Fixes #7629
  backend/src/v2/component/launcher_v2.go
Labels: lgtm, approved, size/XS, ok-to-test

#9968 fix(backend): Sync scheduled workflows v1 if APIVersion and Kind are missing. Fixes #9809
  backend/src/agent/persistence/client/scheduled_workflow_client.go
  backend/src/common/util/scheduled_workflow.go
Labels: lgtm, approved, size/S, ok-to-test
