Repository kubeflow/pipelines, pull requests merged in 2023-07, with the labels that each got.

#9498 chore(components): Move openvino components and samples to the right locations.
  components/contrib/openvino/model_convert/README.md
  components/contrib/openvino/model_convert/containers/Dockerfile
  components/contrib/openvino/model_convert/containers/convert_model.py
  components/contrib/openvino/ovms-deployer/README.md
  components/contrib/openvino/ovms-deployer/containers/Dockerfile
  components/contrib/openvino/ovms-deployer/containers/apply_template.py
  components/contrib/openvino/ovms-deployer/containers/classes.py
  components/contrib/openvino/ovms-deployer/containers/deploy.sh
  components/contrib/openvino/ovms-deployer/containers/evaluate.py
  components/contrib/openvino/ovms-deployer/containers/ovms.j2
  components/contrib/openvino/ovms-deployer/containers/requirements.txt
  components/contrib/openvino/predict/README.md
  components/contrib/openvino/predict/containers/Dockerfile
  components/contrib/openvino/predict/containers/classes.py
  components/contrib/openvino/predict/containers/predict.py
  components/contrib/openvino/predict/containers/requirements.txt
  components/contrib/openvino/tf-slim/README.md
  components/contrib/openvino/tf-slim/containers/Dockerfile
  components/contrib/openvino/tf-slim/containers/slim_model.py
  samples/contrib/openvino/deployer/README.md
  samples/contrib/openvino/deployer/component.yaml
  samples/contrib/openvino/deployer/deployer.png
  samples/contrib/openvino/deployer/deployer.py
  samples/contrib/openvino/model_optimizer/README.md
  samples/contrib/openvino/model_optimizer/convert_model_pipeline.py
  samples/contrib/openvino/predict/README.md
  samples/contrib/openvino/predict/numpy_predict.py
  samples/contrib/openvino/tf-slim/README.md
  samples/contrib/openvino/tf-slim/demo_pipeline1.png
  samples/contrib/openvino/tf-slim/demo_pipeline2.png
  samples/contrib/openvino/tf-slim/demo_pipeline3.png
  samples/contrib/openvino/tf-slim/tf-slim.py
Labels: lgtm, approved, size/XS

#9705 test: Use GKE stable release channel to unblock presubmit tests. Fixes #9704. Part of #9706.
  test/deploy-cluster.sh
Labels: lgtm, approved, size/XS

#9694 chore(frontend): Remove redundant handleVersionSelected helper function
  frontend/src/pages/PipelineDetails.tsx
Labels: lgtm, approved, size/M

#9697 fix(frontend): Recurring run card in experiment details page
  frontend/src/pages/ExperimentDetails.tsx
  frontend/src/pages/__snapshots__/ExperimentDetails.test.tsx.snap
Labels: lgtm, approved, size/L

#9693 chore(frontend): Refactor resource selector for sharable usage in both v1 and v2
  frontend/src/components/PipelinesDialog.tsx
  frontend/src/components/PipelinesDialogV2.tsx
  frontend/src/pages/NewRun.test.tsx
  frontend/src/pages/NewRun.tsx
  frontend/src/pages/NewRunV2.tsx
  frontend/src/pages/ResourceSelector.test.tsx
  frontend/src/pages/ResourceSelector.tsx
  frontend/src/pages/ResourceSelectorV2.test.tsx
  frontend/src/pages/ResourceSelectorV2.tsx
  frontend/src/pages/__snapshots__/ResourceSelectorV2.test.tsx.snap
Labels: lgtm, approved, size/L

#9680 fix(backend): Fix performance issue within a mysql request
  backend/src/apiserver/storage/db.go
  backend/src/apiserver/storage/db_test.go
  backend/src/apiserver/storage/experiment_store.go
Labels: lgtm, approved, size/L

#9581 feat(manifests): Add a postgresql deployment manifest in third-party folder
  manifests/kustomize/third-party/postgresql/README.md
  manifests/kustomize/third-party/postgresql/base/kustomization.yaml
  manifests/kustomize/third-party/postgresql/base/pg-deployment.yaml
  manifests/kustomize/third-party/postgresql/base/pg-pvc.yaml
  manifests/kustomize/third-party/postgresql/base/pg-secret.yaml
  manifests/kustomize/third-party/postgresql/base/pg-service.yaml
  manifests/kustomize/third-party/postgresql/base/pg-serviceaccount.yaml
Labels: lgtm, approved, size/L

#9725 fix(components): fix parent_model ignored in ModelUploadOp
  components/google-cloud/google_cloud_pipeline_components/v1/model/upload_model/component.yaml
Labels: lgtm, approved, size/XS

#9742 chore(sdk): resolve mypy finding
  sdk/python/kfp/compiler/pipeline_spec_builder.py
Labels: lgtm, approved, size/XS, ok-to-test

#9730 fix(backend) Replace LEFT with INNER JOIN when Archive Experiment
  backend/src/apiserver/storage/db.go
  backend/src/apiserver/storage/db_test.go
  backend/src/apiserver/storage/experiment_store.go
Labels: lgtm, approved, size/XS

#9749 test(components): fix k8s_client 401 unauthorized error
  components/aws/sagemaker/tests/integration_tests/component_tests/test_v2_hosting.py
  components/aws/sagemaker/tests/integration_tests/component_tests/test_v2_monitoring_job_definition_component.py
  components/aws/sagemaker/tests/integration_tests/component_tests/test_v2_monitoring_schedule_component.py
  components/aws/sagemaker/tests/integration_tests/component_tests/test_v2_train_component.py
  components/aws/sagemaker/tests/integration_tests/utils/ack_utils.py
Labels: lgtm, approved, needs-ok-to-test, size/M

#9728 chore(frontend): Avoid redundant v2 API call in PipelineDetails.
  frontend/src/pages/PipelineDetails.test.tsx
  frontend/src/pages/PipelineDetails.tsx
Labels: lgtm, approved, size/L

#9782 chore(sdk): release KFP SDK 2.1.0
  docs/conf.py
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/compiler/read_write_test.py
  sdk/python/requirements.in
Labels: lgtm, approved, size/M

#9785 fix(sdk): various kfp-dsl fixes
  sdk/python/kfp-dsl/kfp/dsl/structures.py
  sdk/python/kfp-dsl/kfp/dsl/types/type_utils.py
  sdk/python/kfp-dsl/runtime_tests/execute_commands_args_test.py
  sdk/python/kfp-dsl/setup.py
  test/presubmit-test-kfp-dsl-runtime-code.sh
Labels: lgtm, approved, size/L

#9787 chore(sdk): release KFP SDK 2.1.1
  docs/conf.py
  sdk/RELEASE.md
  sdk/python/kfp-dsl/setup.py
  sdk/python/kfp/__init__.py
  sdk/python/requirements.in
Labels: lgtm, approved, size/S

#9797 chore(sdk): release KFP SDK 2.1.2
  docs/conf.py
  sdk/RELEASE.md
  sdk/python/kfp-dsl/setup.py
  sdk/python/kfp/__init__.py
  sdk/python/requirements.in
Labels: lgtm, approved, size/S
