Repository kubeflow/pipelines, pull requests merged in 2023-04, with the labels that each got.

#9095 Revert "chore(sdk): update compiler type annotations"
  sdk/python/kfp/compiler/compiler.py
Labels: lgtm, approved, size/XS

#9097 fix(backend): Add pipeline_id to pipeline_source in Run and RecurringRun
  backend/api/v2beta1/go_client/recurring_run.pb.go
  backend/api/v2beta1/go_client/run.pb.go
  backend/api/v2beta1/go_http_client/recurring_run_model/v2beta1_pipeline_version_reference.go
  backend/api/v2beta1/go_http_client/recurring_run_model/v2beta1_recurring_run.go
  backend/api/v2beta1/go_http_client/run_model/v2beta1_pipeline_version_reference.go
  backend/api/v2beta1/go_http_client/run_model/v2beta1_run.go
  backend/api/v2beta1/python_http_client/README.md
  backend/api/v2beta1/python_http_client/docs/V2beta1PipelineVersion.md
  backend/api/v2beta1/python_http_client/docs/V2beta1PipelineVersionReference.md
  backend/api/v2beta1/python_http_client/docs/V2beta1RecurringRun.md
  backend/api/v2beta1/python_http_client/docs/V2beta1Run.md
  backend/api/v2beta1/python_http_client/kfp_server_api/__init__.py
  backend/api/v2beta1/python_http_client/kfp_server_api/models/__init__.py
  backend/api/v2beta1/python_http_client/kfp_server_api/models/v2beta1_pipeline_version.py
  backend/api/v2beta1/python_http_client/kfp_server_api/models/v2beta1_pipeline_version_reference.py
  backend/api/v2beta1/python_http_client/kfp_server_api/models/v2beta1_recurring_run.py
  backend/api/v2beta1/python_http_client/kfp_server_api/models/v2beta1_run.py
  backend/api/v2beta1/python_http_client/test/test_v2beta1_list_pipeline_versions_response.py
  backend/api/v2beta1/python_http_client/test/test_v2beta1_list_recurring_runs_response.py
  backend/api/v2beta1/python_http_client/test/test_v2beta1_list_runs_response.py
  backend/api/v2beta1/python_http_client/test/test_v2beta1_pipeline_version.py
  backend/api/v2beta1/python_http_client/test/test_v2beta1_pipeline_version_reference.py
  backend/api/v2beta1/python_http_client/test/test_v2beta1_recurring_run.py
  backend/api/v2beta1/python_http_client/test/test_v2beta1_run.py
  backend/api/v2beta1/recurring_run.proto
  backend/api/v2beta1/run.proto
  backend/api/v2beta1/swagger/kfp_api_single_file.swagger.json
  backend/api/v2beta1/swagger/recurring_run.swagger.json
  backend/api/v2beta1/swagger/run.swagger.json
  backend/src/apiserver/model/pipeline_spec.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/server/api_converter.go
  backend/src/apiserver/server/api_converter_test.go
Labels: lgtm, approved, size/XXL

#9072 fix(backend): support reading large doc from URL; Fixes #7652
  backend/src/apiserver/server/pipeline_server_test.go
  backend/src/apiserver/server/test/xgboost_sample_pipeline.yaml
  backend/src/apiserver/server/util.go
  backend/src/apiserver/server/util_test.go
Labels: lgtm, approved, size/XL, area/backend

#9101 chore(frontend): Change pipeline_version_id field in run / recurring run
  frontend/src/pages/NewRunSwitcher.tsx
  frontend/src/pages/NewRunV2.test.tsx
  frontend/src/pages/NewRunV2.tsx
  frontend/src/pages/PipelineDetails.test.tsx
  frontend/src/pages/PipelineDetails.tsx
  frontend/src/pages/RecurringRunDetailsRouter.tsx
  frontend/src/pages/RecurringRunDetailsV2.test.tsx
  frontend/src/pages/RunDetailsRouter.tsx
  frontend/src/pages/RunList.test.tsx
  frontend/src/pages/RunList.tsx
Labels: lgtm, approved, size/L

#9089 fix(backend): Remove resource from workflow-controller-configmap. Closes #9087
  manifests/kustomize/third-party/argo/base/workflow-controller-configmap-patch.yaml
Labels: lgtm, approved, size/XS

#9104 fix(api): Fix pipeline.upload.swagger.json
  backend/api/v2beta1/go_http_client/pipeline_upload_client/pipeline_upload_service/upload_pipeline_responses.go
  backend/api/v2beta1/go_http_client/pipeline_upload_client/pipeline_upload_service/upload_pipeline_version_parameters.go
  backend/api/v2beta1/go_http_client/pipeline_upload_client/pipeline_upload_service/upload_pipeline_version_responses.go
  backend/api/v2beta1/go_http_client/pipeline_upload_model/api_parameter.go
  backend/api/v2beta1/go_http_client/pipeline_upload_model/api_pipeline.go
  backend/api/v2beta1/go_http_client/pipeline_upload_model/api_pipeline_version.go
  backend/api/v2beta1/go_http_client/pipeline_upload_model/api_relationship.go
  backend/api/v2beta1/go_http_client/pipeline_upload_model/api_resource_key.go
  backend/api/v2beta1/go_http_client/pipeline_upload_model/api_resource_reference.go
  backend/api/v2beta1/go_http_client/pipeline_upload_model/api_resource_type.go
  backend/api/v2beta1/go_http_client/pipeline_upload_model/api_status.go
  backend/api/v2beta1/go_http_client/pipeline_upload_model/googlerpc_status.go
  backend/api/v2beta1/go_http_client/pipeline_upload_model/v2beta1_pipeline.go
  backend/api/v2beta1/go_http_client/pipeline_upload_model/v2beta1_pipeline_version.go
  backend/api/v2beta1/go_http_client/pipeline_upload_model/v2beta1_url.go
  backend/api/v2beta1/python_http_client/README.md
  backend/api/v2beta1/python_http_client/docs/ApiParameter.md
  backend/api/v2beta1/python_http_client/docs/ApiPipeline.md
  backend/api/v2beta1/python_http_client/docs/ApiPipelineVersion.md
  backend/api/v2beta1/python_http_client/docs/ApiRelationship.md
  backend/api/v2beta1/python_http_client/docs/ApiResourceKey.md
  backend/api/v2beta1/python_http_client/docs/ApiResourceReference.md
  backend/api/v2beta1/python_http_client/docs/ApiResourceType.md
  backend/api/v2beta1/python_http_client/docs/ApiStatus.md
  backend/api/v2beta1/python_http_client/docs/ApiUrl.md
  backend/api/v2beta1/python_http_client/docs/PipelineUploadServiceApi.md
  backend/api/v2beta1/python_http_client/kfp_server_api/__init__.py
  backend/api/v2beta1/python_http_client/kfp_server_api/api/pipeline_upload_service_api.py
  backend/api/v2beta1/python_http_client/kfp_server_api/models/__init__.py
  backend/api/v2beta1/python_http_client/kfp_server_api/models/api_parameter.py
  backend/api/v2beta1/python_http_client/kfp_server_api/models/api_pipeline.py
  backend/api/v2beta1/python_http_client/kfp_server_api/models/api_pipeline_version.py
  backend/api/v2beta1/python_http_client/kfp_server_api/models/api_relationship.py
  backend/api/v2beta1/python_http_client/kfp_server_api/models/api_resource_key.py
  backend/api/v2beta1/python_http_client/kfp_server_api/models/api_resource_reference.py
  backend/api/v2beta1/python_http_client/kfp_server_api/models/api_resource_type.py
  backend/api/v2beta1/python_http_client/kfp_server_api/models/api_status.py
  backend/api/v2beta1/python_http_client/kfp_server_api/models/api_url.py
  backend/api/v2beta1/python_http_client/test/test_api_parameter.py
  backend/api/v2beta1/python_http_client/test/test_api_pipeline.py
  backend/api/v2beta1/python_http_client/test/test_api_pipeline_version.py
  backend/api/v2beta1/python_http_client/test/test_api_relationship.py
  backend/api/v2beta1/python_http_client/test/test_api_resource_key.py
  backend/api/v2beta1/python_http_client/test/test_api_resource_reference.py
  backend/api/v2beta1/python_http_client/test/test_api_resource_type.py
  backend/api/v2beta1/python_http_client/test/test_api_status.py
  backend/api/v2beta1/python_http_client/test/test_api_url.py
  backend/api/v2beta1/swagger/kfp_api_single_file.swagger.json
  backend/api/v2beta1/swagger/pipeline.upload.swagger.json
Labels: lgtm, approved, size/XXL

#9111 chore(components): add test image cache
  components/aws/sagemaker/codebuild/integration-test.buildspec.yml
  components/aws/sagemaker/tests/integration_tests/Dockerfile
  components/aws/sagemaker/tests/integration_tests/resources/config/ack-training-job/config.yaml
  components/aws/sagemaker/tests/integration_tests/resources/config/rlestimator-training/config.yaml
  components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests
Labels: lgtm, approved, size/M

#9066 chore(sdk): release KFP SDK 1.8.20
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
Labels: lgtm, approved, size/S

#9120 chore: release kfp-pipeline-spec 0.2.2
  api/.gitignore
  api/v2alpha1/python/setup.py
Labels: lgtm, approved, size/XS

#9123 chore(frontend): Integrate pipeline / pipeline version functions with KFP v2 API
  frontend/src/components/PipelinesDialogV2.test.tsx
  frontend/src/components/PipelinesDialogV2.tsx
  frontend/src/components/navigators/PipelineVersionCard.test.tsx
  frontend/src/components/navigators/PipelineVersionCard.tsx
  frontend/src/lib/Apis.ts
  frontend/src/lib/Buttons.ts
  frontend/src/lib/ResourceConverter.tsx
  frontend/src/pages/GettingStarted.test.tsx
  frontend/src/pages/GettingStarted.tsx
  frontend/src/pages/NewPipelineVersion.test.tsx
  frontend/src/pages/NewPipelineVersion.tsx
  frontend/src/pages/NewRunSwitcher.tsx
  frontend/src/pages/NewRunV2.test.tsx
  frontend/src/pages/NewRunV2.tsx
  frontend/src/pages/PipelineDetails.test.tsx
  frontend/src/pages/PipelineDetails.tsx
  frontend/src/pages/PipelineDetailsTest.test.tsx
  frontend/src/pages/PipelineDetailsV2.tsx
  frontend/src/pages/PipelineList.test.tsx
  frontend/src/pages/PipelineList.tsx
  frontend/src/pages/PipelineVersionList.test.tsx
  frontend/src/pages/PipelineVersionList.tsx
  frontend/src/pages/PrivateAndSharedPipelines.test.tsx
  frontend/src/pages/RecurringRunDetailsRouter.tsx
  frontend/src/pages/RecurringRunDetailsV2.test.tsx
  frontend/src/pages/ResourceSelectorV2.test.tsx
  frontend/src/pages/ResourceSelectorV2.tsx
  frontend/src/pages/RunDetailsRouter.tsx
  frontend/src/pages/RunList.test.tsx
  frontend/src/pages/RunList.tsx
  frontend/src/pages/__snapshots__/GettingStarted.test.tsx.snap
  frontend/src/pages/__snapshots__/ResourceSelectorV2.test.tsx.snap
  test/frontend-integration-test/helloworld.spec.js
Labels: lgtm, approved, size/XXL

#9124 chore(frontend): Integrate experiment and run (cross-functionality call) with v2 API
  frontend/src/components/ExperimentList.test.tsx
  frontend/src/components/ExperimentList.tsx
  frontend/src/pages/ExperimentList.test.tsx
  frontend/src/pages/ExperimentList.tsx
  frontend/src/pages/NewRunSwitcher.tsx
  frontend/src/pages/NewRunV2.test.tsx
  frontend/src/pages/NewRunV2.tsx
  frontend/src/pages/PipelineDetails.test.tsx
  frontend/src/pages/PipelineDetails.tsx
  frontend/src/pages/PipelineDetailsV2.test.tsx
  frontend/src/pages/RecurringRunDetailsV2.test.tsx
  frontend/src/pages/RecurringRunDetailsV2.tsx
  frontend/src/pages/RecurringRunList.test.tsx
  frontend/src/pages/RecurringRunList.tsx
  frontend/src/pages/RunDetailsV2.test.tsx
  frontend/src/pages/RunDetailsV2.tsx
  frontend/src/pages/RunList.test.tsx
  frontend/src/pages/RunList.tsx
Labels: lgtm, approved, size/L

#9088 feat(backend): add support for resource requests. Closes #7047. Closes #6354.
  backend/src/apiserver/template/template_test.go
  backend/src/v2/compiler/argocompiler/argo.go
  backend/src/v2/compiler/argocompiler/testdata/create_mount_delete_dynamic_pvc.yaml
  backend/src/v2/compiler/argocompiler/testdata/hello_world.yaml
  backend/src/v2/compiler/argocompiler/testdata/importer.yaml
  backend/src/v2/driver/driver.go
  backend/src/v2/driver/driver_test.go
  backend/third_party_licenses/apiserver.csv
  go.mod
  go.sum
  samples/core/resource_spec/resource_spec_v2.py
Labels: approved, size/L

#9128 fix(backend): Set status when converting API recurring run to internal representation
  backend/src/apiserver/server/api_converter.go
  backend/src/apiserver/server/api_converter_test.go
Labels: lgtm, approved, size/S

#9131 feat(sdk): support direct indexing into top-level of artifact metadata struct in Container Components
  sdk/RELEASE.md
  sdk/python/kfp/components/placeholders.py
  sdk/python/kfp/components/placeholders_test.py
Labels: lgtm, approved, size/M

#9067 docs(sdk): add KFP SDK 1.8.20 reference docs
  docs/conf.py
Labels: lgtm, approved, size/XS

#9105 chore(sdk): set private _ir_type attribute on InputValuePlaceholder
  sdk/python/kfp/components/component_factory.py
  sdk/python/kfp/components/container_component_decorator_test.py
Labels: lgtm, approved, size/M, ok-to-test

#9118 fix(backend): Fix missing parameters in jobs and recurring runs. Closes #9012.
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/server/api_converter.go
  backend/src/apiserver/server/api_converter_test.go
  backend/src/apiserver/server/report_server.go
  backend/src/apiserver/storage/job_store.go
  backend/src/apiserver/storage/job_store_test.go
  backend/src/apiserver/template/argo_template.go
  backend/src/apiserver/template/template.go
  backend/src/apiserver/template/template_test.go
  backend/src/apiserver/template/v2_template.go
  backend/src/common/util/scheduled_workflow.go
  backend/src/common/util/scheduled_workflow_test.go
Labels: lgtm, approved, size/L

#9134 feat(sdk): Support PIPELINE_ROOT_PLACEHOLDER
  sdk/python/kfp/dsl/__init__.py
Labels: lgtm, approved, size/S

#9141 chore: make a more testable volume sample
  kubernetes_platform/python/test/snapshot/data/create_mount_delete_dynamic_pvc.py
  kubernetes_platform/python/test/snapshot/data/create_mount_delete_dynamic_pvc.yaml
Labels: lgtm, approved, size/L

#9112 feat(SDK)!: SDK client v2beta1 API integration. Fixes #8706
  sdk/python/kfp/cli/experiment.py
  sdk/python/kfp/cli/output.py
  sdk/python/kfp/cli/pipeline.py
  sdk/python/kfp/cli/recurring_run.py
  sdk/python/kfp/cli/run.py
  sdk/python/kfp/client/client.py
  sdk/python/kfp/client/client_test.py
  sdk/python/requirements.in
  sdk/python/requirements.txt
Labels: lgtm, size/XL

#9140 feat(sdk): Support submitting pipeline with platform config.
  sdk/python/kfp/client/client.py
  sdk/python/kfp/client/client_test.py
Labels: lgtm, size/L

#9144 chore: release SDK 2.0.0b14
  docs/conf.py
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
  sdk/python/kfp/client/client.py
Labels: lgtm, size/M

#9148 chore(sdk): add kfp-kubernetes documentation to PyPI
  kubernetes_platform/python/README.md
  kubernetes_platform/python/setup.py
Labels: lgtm, approved, size/S

#9152 chore(sdk): add kfp-kubernetes as kfp extras_require
  sdk/python/setup.py
Labels: lgtm, approved, size/XS

#9157 fix(sdk): fixes module not found error for containerized python components. Fixes #8385
  sdk/RELEASE.md
  sdk/python/kfp/cli/component_test.py
  sdk/python/kfp/components/utils.py
Labels: lgtm, approved, size/S, ok-to-test

#9138 chore: Update RELEASE.md
  RELEASE.md
Labels: lgtm, approved, size/XS

#9153 feat(sdk): support `display_name` and `description` in `@dsl.pipeline` decorator
  sdk/RELEASE.md
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/components/component_factory.py
  sdk/python/kfp/components/graph_component.py
  sdk/python/kfp/components/pipeline_context.py
  sdk/python/test_data/pipelines/pipeline_with_nested_conditions_yaml.py
  sdk/python/test_data/pipelines/pipeline_with_nested_conditions_yaml.yaml
  sdk/python/test_data/pipelines/pipeline_with_ontology.yaml
  sdk/python/test_data/pipelines/pipeline_with_resource_spec.yaml
Labels: lgtm, approved, size/L

#9164 chore(tests): Disable samples in e2e testing
  test/e2e_test_gke_v2.yaml
Labels: lgtm, approved, size/M

#9002 test: added verify_func in TestCase
  samples/test/parameter_with_format_test.py
Labels: lgtm, approved, size/XS, ok-to-test

#9132 feat(backend): Add nodeSelector support. Closes #8959.
  backend/src/apiserver/template/template_test.go
  backend/src/v2/cmd/driver/main.go
  backend/src/v2/compiler/argocompiler/argo.go
  backend/src/v2/compiler/argocompiler/dag.go
  backend/src/v2/compiler/argocompiler/proto_test.go
  backend/src/v2/compiler/argocompiler/testdata/create_mount_delete_dynamic_pvc.yaml
  backend/src/v2/compiler/argocompiler/testdata/hello_world.yaml
  backend/src/v2/compiler/argocompiler/testdata/importer.yaml
  backend/src/v2/compiler/visitor.go
  backend/src/v2/driver/driver.go
  backend/src/v2/driver/driver_test.go
Labels: lgtm, approved, size/L

#9150 fix(backend): fix volume bug
  backend/src/apiserver/template/template_test.go
  backend/src/v2/compiler/argocompiler/argo.go
  backend/src/v2/compiler/argocompiler/testdata/create_mount_delete_dynamic_pvc.yaml
  backend/src/v2/compiler/argocompiler/testdata/hello_world.yaml
  backend/src/v2/compiler/argocompiler/testdata/importer.yaml
  backend/src/v2/driver/driver.go
  backend/src/v2/driver/driver_test.go
  samples/test/config.yaml
  samples/v2/pipeline_with_volume.py
  samples/v2/pipeline_with_volume_test.py
Labels: lgtm, approved, size/L, area/backend

#9169 chore(testing): Enable samples in e2e tests with v1 kfp SDK
  samples/core/exit_handler/exit_handler.py
  samples/core/parallel_join/parallel_join.py
  samples/core/recursion/recursion.py
  samples/core/sequential/sequential.py
  samples/core/volume_ops/volume_ops.py
  test/e2e_test_gke_v2.yaml
  test/sample-test/Dockerfile
  test/sample-test/check_notebook_results.py
  test/sample-test/run_resnet_cmle_test.py
  test/sample-test/run_sample_test.py
  test/sample-test/sample_test_launcher.py
Labels: lgtm, approved, size/M

#9178 feat(backend): support secrets
  backend/src/v2/driver/driver.go
  backend/src/v2/driver/driver_test.go
  samples/test/config.yaml
  samples/v2/pipeline_with_secret_as_env.py
  samples/v2/pipeline_with_secret_as_env_test.py
  samples/v2/pipeline_with_secret_as_volume.py
  samples/v2/pipeline_with_secret_as_volume_test.py
Labels: lgtm, approved, size/L, area/backend

#9181 fix(frontend): Replace obsoleted hyperlinks in new pipeline page.
  frontend/src/components/UploadPipelineDialog.tsx
Labels: lgtm, approved, size/XS

#9184 chore(backend): change optional parameter enforce rule
  backend/src/apiserver/template/template_test.go
  backend/src/v2/compiler/argocompiler/argo.go
  backend/src/v2/compiler/argocompiler/testdata/create_mount_delete_dynamic_pvc.yaml
  backend/src/v2/compiler/argocompiler/testdata/hello_world.yaml
  backend/src/v2/compiler/argocompiler/testdata/importer.yaml
  backend/src/v2/driver/driver.go
Labels: lgtm, approved, size/S, area/backend

#9180 test(components): Add shallow_canary marker
  components/aws/sagemaker/tests/integration_tests/component_tests/test_deploy_component.py
  components/aws/sagemaker/tests/integration_tests/component_tests/test_v2_train_component.py
  components/aws/sagemaker/tests/integration_tests/pytest.ini
Labels: lgtm, approved, needs-ok-to-test, size/S

#9186 fix(sdk): fix handling of PipelineTaskFinalStatus in ir_type_ attribute hack
  sdk/python/kfp/components/component_factory.py
  sdk/python/kfp/components/container_component_decorator_test.py
Labels: lgtm, approved, size/S

#9191 fix(SDK): fix `client.run_pipeline` with `pipeline_id` and `version_id` gives error
  sdk/python/kfp/client/client.py
Labels: lgtm, approved, size/XS

#9197 fix(api): Regenerate v2beta1 API
  backend/api/v2beta1/go_client/auth.pb.gw.go
  backend/api/v2beta1/go_client/experiment.pb.gw.go
  backend/api/v2beta1/go_client/healthz.pb.gw.go
  backend/api/v2beta1/go_client/pipeline.pb.gw.go
  backend/api/v2beta1/go_client/recurring_run.pb.gw.go
  backend/api/v2beta1/go_client/report.pb.gw.go
  backend/api/v2beta1/go_client/run.pb.gw.go
  backend/api/v2beta1/go_client/visualization.pb.gw.go
  backend/api/v2beta1/go_http_client/pipeline_model/protobuf_list_value.go
  backend/api/v2beta1/go_http_client/pipeline_model/protobuf_struct.go
  backend/api/v2beta1/go_http_client/pipeline_model/protobuf_value.go
  backend/api/v2beta1/go_http_client/pipeline_model/v2beta1_pipeline_version.go
  backend/api/v2beta1/go_http_client/recurring_run_model/protobuf_list_value.go
  backend/api/v2beta1/go_http_client/recurring_run_model/protobuf_struct.go
  backend/api/v2beta1/go_http_client/recurring_run_model/protobuf_value.go
  backend/api/v2beta1/go_http_client/recurring_run_model/v2beta1_recurring_run.go
  backend/api/v2beta1/go_http_client/recurring_run_model/v2beta1_runtime_config.go
  backend/api/v2beta1/go_http_client/run_model/protobuf_list_value.go
  backend/api/v2beta1/go_http_client/run_model/protobuf_struct.go
  backend/api/v2beta1/go_http_client/run_model/protobuf_value.go
  backend/api/v2beta1/go_http_client/run_model/v2beta1_run.go
  backend/api/v2beta1/go_http_client/run_model/v2beta1_runtime_config.go
  backend/api/v2beta1/python_http_client/README.md
  backend/api/v2beta1/python_http_client/docs/ProtobufListValue.md
  backend/api/v2beta1/python_http_client/docs/ProtobufStruct.md
  backend/api/v2beta1/python_http_client/docs/ProtobufValue.md
  backend/api/v2beta1/python_http_client/docs/V2beta1PipelineVersion.md
  backend/api/v2beta1/python_http_client/docs/V2beta1RecurringRun.md
  backend/api/v2beta1/python_http_client/docs/V2beta1Run.md
  backend/api/v2beta1/python_http_client/docs/V2beta1RuntimeConfig.md
  backend/api/v2beta1/python_http_client/kfp_server_api/__init__.py
  backend/api/v2beta1/python_http_client/kfp_server_api/models/__init__.py
  backend/api/v2beta1/python_http_client/kfp_server_api/models/protobuf_list_value.py
  backend/api/v2beta1/python_http_client/kfp_server_api/models/protobuf_struct.py
  backend/api/v2beta1/python_http_client/kfp_server_api/models/protobuf_value.py
  backend/api/v2beta1/python_http_client/kfp_server_api/models/v2beta1_pipeline_version.py
  backend/api/v2beta1/python_http_client/kfp_server_api/models/v2beta1_recurring_run.py
  backend/api/v2beta1/python_http_client/kfp_server_api/models/v2beta1_run.py
  backend/api/v2beta1/python_http_client/kfp_server_api/models/v2beta1_runtime_config.py
  backend/api/v2beta1/python_http_client/test/test_protobuf_list_value.py
  backend/api/v2beta1/python_http_client/test/test_protobuf_struct.py
  backend/api/v2beta1/python_http_client/test/test_protobuf_value.py
  backend/api/v2beta1/python_http_client/test/test_v2beta1_list_pipeline_versions_response.py
  backend/api/v2beta1/python_http_client/test/test_v2beta1_list_recurring_runs_response.py
  backend/api/v2beta1/python_http_client/test/test_v2beta1_list_runs_response.py
  backend/api/v2beta1/python_http_client/test/test_v2beta1_pipeline_version.py
  backend/api/v2beta1/python_http_client/test/test_v2beta1_recurring_run.py
  backend/api/v2beta1/python_http_client/test/test_v2beta1_run.py
  backend/api/v2beta1/python_http_client/test/test_v2beta1_runtime_config.py
  backend/api/v2beta1/swagger/kfp_api_single_file.swagger.json
  backend/api/v2beta1/swagger/pipeline.swagger.json
  backend/api/v2beta1/swagger/recurring_run.swagger.json
  backend/api/v2beta1/swagger/run.swagger.json
Labels: lgtm, approved, size/XXL

#9198 fix(release): Update release image with the latest api-generator
  backend/api/Makefile
  test/release/Dockerfile.release
  test/release/Makefile
  test/release/bump-version-docker.sh
  test/release/check-release-needed-tools.sh
Labels: lgtm, approved, size/S

#9156 feat(sdk): support extracting input/output descriptions from component/pipeline docstrings
  sdk/RELEASE.md
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/compiler/pipeline_spec_builder.py
  sdk/python/kfp/components/component_factory.py
  sdk/python/kfp/components/structures.py
  sdk/python/test_data/components/component_with_metadata_fields.py
  sdk/python/test_data/components/component_with_metadata_fields.yaml
  sdk/python/test_data/pipelines/pipeline_with_metadata_fields.py
  sdk/python/test_data/pipelines/pipeline_with_metadata_fields.yaml
  sdk/python/test_data/test_data_config.yaml
Labels: lgtm, approved, size/XL

#9218 chore(sdk): release KFP SDK 2.0.0b15
  docs/conf.py
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
Labels: lgtm, approved, size/S

#9202 fix(frontend): Parameter field is missing after choosing another v2 pipeline
  frontend/src/pages/NewRunV2.test.tsx
  frontend/src/pages/NewRunV2.tsx
Labels: lgtm, approved, size/M

#9204 test: Upgrade package versions and remove dependency on "sagemaker-sample-data-<region>" bucket
  components/aws/sagemaker/tests/integration_tests/component_tests/test_deploy_component.py
  components/aws/sagemaker/tests/integration_tests/requirements.txt
  components/aws/sagemaker/tests/integration_tests/resources/config/ack-training-job/config.yaml
  components/aws/sagemaker/tests/integration_tests/resources/config/assume-role-processing/config.yaml
  components/aws/sagemaker/tests/integration_tests/resources/config/kmeans-algo-mnist-processing/config.yaml
  components/aws/sagemaker/tests/integration_tests/resources/config/kmeans-mnist-endpoint/config.yaml
  components/aws/sagemaker/tests/integration_tests/resources/config/kmeans-mnist-update-endpoint/config.yaml
Labels: lgtm, approved, needs-ok-to-test, size/S

#9189 fix(backend): Cleanup pipeline creation and upload logic
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/server/pipeline_server.go
  backend/src/apiserver/server/pipeline_server_test.go
  backend/src/apiserver/server/pipeline_upload_server.go
  backend/src/apiserver/storage/pipeline_store.go
  backend/src/apiserver/storage/pipeline_store_test.go
Labels: lgtm, approved, size/XL

#9212 fix(sdk): allow user to choose platform for component container build. Fixes #8883
  sdk/python/kfp/cli/component.py
  sdk/python/kfp/cli/component_test.py
Labels: lgtm, approved, size/S, ok-to-test

#9236 test: fix "ValueError: Unsupported region". Only populate necessary values for shallow_canary
  components/aws/sagemaker/tests/integration_tests/component_tests/test_deploy_component.py
  components/aws/sagemaker/tests/integration_tests/component_tests/test_v2_train_component.py
  components/aws/sagemaker/tests/integration_tests/utils/__init__.py
Labels: lgtm, approved, needs-ok-to-test, size/S

#9217 fix(frontend): Render run parameters in run details tab.
  frontend/src/pages/RunDetailsV2.test.tsx
  frontend/src/pages/RunDetailsV2.tsx
Labels: lgtm, approved, size/M

#9231 fix(frontend): Missing pipeline info while cloning recurring run.
  frontend/src/pages/NewRunV2.tsx
Labels: lgtm, approved, size/XS

#9245 fix(backend): Add upsert for SQLite and MySQL dialects
  backend/src/apiserver/storage/db.go
  backend/src/apiserver/storage/db_test.go
  backend/src/apiserver/storage/task_store.go
Labels: lgtm, approved, size/M

#9228 feat(backend): add parameter verification before submitting the workflow
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/server/job_server_test.go
  backend/src/apiserver/server/pipeline_upload_server_test.go
  backend/src/apiserver/server/run_server_test.go
  backend/src/apiserver/template/template_test.go
  backend/src/apiserver/template/testdata/hello_world.yaml
  backend/src/apiserver/template/v2_template.go
Labels: lgtm, approved, size/L, area/backend

#9255 fix(frontend): fail to clone SDK-created run / recurring run
  frontend/src/pages/NewRunSwitcher.tsx
  frontend/src/pages/NewRunV2.test.tsx
Labels: lgtm, approved, size/L

#9192 fix(frontend): Render graph for yaml file containing platform_spec
  frontend/src/lib/v2/WorkflowUtils.ts
Labels: lgtm, approved, size/S
