Repository kubeflow/pipelines, pull requests merged in 2023-11, with the labels that each got.

#10205 fix(backend): Pipeline and PipelineVersion Description column value should be optional.
  backend/src/apiserver/model/pipeline.go
  backend/src/apiserver/model/pipeline_version.go
Labels: lgtm, approved, size/XS, ok-to-test

#10218 chore(sdk): update CONTRIBUTING.md testing instructions
  sdk/CONTRIBUTING.md
Labels: lgtm, approved, size/XS

#10199 chore(manifest): Update application-crd-controller image to fix CVEs
  manifests/kustomize/third-party/application/application-controller-deployment.yaml
Labels: lgtm, approved, size/S

#10247 chore(sdk): nest requests_toolbelt import
  sdk/python/kfp/client/auth.py
Labels: lgtm, approved, size/XS

#10234 feat(sdk): add local execution config #localexecution
  sdk/python/kfp/local/__init__.py
  sdk/python/kfp/local/config.py
  sdk/python/kfp/local/config_test.py
Labels: lgtm, approved, size/L

#10240 feat(sdk): add executor output path and executor input message placeholders
  sdk/RELEASE.md
  sdk/python/kfp/dsl/__init__.py
  sdk/python/kfp/dsl/component_factory.py
  sdk/python/kfp/dsl/placeholders.py
  sdk/python/kfp/dsl/placeholders_test.py
  sdk/python/kfp/dsl/structures.py
  sdk/python/kfp/dsl/structures_test.py
Labels: lgtm, approved, size/M

#10227 frontend: Add an option to specify useSSL variable for aws
  frontend/server/configs.ts
  frontend/server/integration-tests/artifact-get.test.ts
Labels: lgtm, approved, size/XS

#10257 feat(sdk): support `.after()` referencing task in `ParallelFor` group
  sdk/RELEASE.md
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/compiler/compiler_utils.py
  sdk/python/test_data/pipelines/cross_loop_after_topology.py
  sdk/python/test_data/pipelines/cross_loop_after_topology.yaml
  sdk/python/test_data/test_data_config.yaml
Labels: lgtm, approved, size/XXL

#10272 chore(sdk): support Python 3.12
  api/v2alpha1/python/setup.py
  kubernetes_platform/python/setup.py
  kubernetes_platform/python/test/snapshot/data/create_mount_delete_dynamic_pvc.yaml
  kubernetes_platform/python/test/snapshot/data/create_mount_delete_existing_pvc.yaml
  kubernetes_platform/python/test/snapshot/data/create_mount_delete_existing_pvc_from_task_output.yaml
  kubernetes_platform/python/test/snapshot/data/node_selector.yaml
  kubernetes_platform/python/test/snapshot/data/secret_as_env.yaml
  kubernetes_platform/python/test/snapshot/data/secret_as_vol.yaml
  kubernetes_platform/python/test/snapshot/read_write_test.py
  sdk/RELEASE.md
  sdk/python/kfp/dsl/types/type_utils_test.py
  sdk/python/setup.py
Labels: lgtm, approved, size/L

#10276 fix(frontend): Support running old v1 pipeline. Fix #10153
  frontend/src/pages/NewRunSwitcher.tsx
  frontend/src/pages/NewRunV2.test.tsx
  frontend/src/pages/PipelineDetails.test.tsx
  frontend/src/pages/PipelineDetails.tsx
Labels: lgtm, approved, size/L
