Repository kubeflow/pipelines, pull requests merged in 2023-02, with the labels that each got.

#8597 fix(frontend): preserve run parameters on pipeline version change for cloned runs. Fixes #4944
  frontend/src/lib/Utils.test.ts
  frontend/src/lib/Utils.tsx
  frontend/src/pages/NewRun.tsx
Labels: lgtm, approved, size/M, ok-to-test

#8787 fix(frontend): Disable choosing pipeline version if pipeline is empty.
  frontend/src/pages/NewRun.test.tsx
  frontend/src/pages/NewRun.tsx
  frontend/src/pages/__snapshots__/NewRun.test.tsx.snap
Labels: lgtm, approved, size/M

#8793 fix(frontend): Change the pipeline description field as optional.
  frontend/src/pages/NewPipelineVersion.tsx
  frontend/src/pages/__snapshots__/NewPipelineVersion.test.tsx.snap
Labels: lgtm, approved, size/XS

#8631 feat(sdk): support for fan-in from `dsl.ParallelFor`
  sdk/RELEASE.md
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/compiler/compiler_utils.py
  sdk/python/kfp/compiler/compiler_utils_test.py
  sdk/python/kfp/compiler/pipeline_spec_builder.py
  sdk/python/kfp/compiler/pipeline_spec_builder_test.py
  sdk/python/kfp/components/for_loop.py
  sdk/python/kfp/components/structures.py
  sdk/python/kfp/dsl/__init__.py
  sdk/python/test_data/pipelines/parallelfor_fan_in/conditional_producer_and_consumers.py
  sdk/python/test_data/pipelines/parallelfor_fan_in/conditional_producer_and_consumers.yaml
  sdk/python/test_data/pipelines/parallelfor_fan_in/fan_in_complex.py
  sdk/python/test_data/pipelines/parallelfor_fan_in/fan_in_complex.yaml
  sdk/python/test_data/pipelines/parallelfor_fan_in/nested_with_parameters.py
  sdk/python/test_data/pipelines/parallelfor_fan_in/nested_with_parameters.yaml
  sdk/python/test_data/pipelines/parallelfor_fan_in/pipeline_producer_consumer.py
  sdk/python/test_data/pipelines/parallelfor_fan_in/pipeline_producer_consumer.yaml
  sdk/python/test_data/pipelines/parallelfor_fan_in/simple_with_parameters.py
  sdk/python/test_data/pipelines/parallelfor_fan_in/simple_with_parameters.yaml
  sdk/python/test_data/test_data_config.yaml
Labels: lgtm, approved, size/XXL

#8809 chore(sdk): fix isort version in pre-commit
  .pre-commit-config.yaml
Labels: size/XS

#8805 fix(backend): fix run, job from empty manifest. Closes #8802.
  backend/src/apiserver/resource/resource_manager.go
  backend/test/integration/pipeline_api_test.go
  backend/test/integration/upgrade_test.go
Labels: lgtm, approved, size/L

#8804 fix(backend): add retry run in v2 api. Fixes #8735
  backend/api/v2beta1/go_client/run.pb.go
  backend/api/v2beta1/go_client/run.pb.gw.go
  backend/api/v2beta1/go_http_client/run_client/run_service/retry_run_parameters.go
  backend/api/v2beta1/go_http_client/run_client/run_service/retry_run_responses.go
  backend/api/v2beta1/go_http_client/run_client/run_service/run_service_client.go
  backend/api/v2beta1/python_http_client/README.md
  backend/api/v2beta1/python_http_client/docs/RunServiceApi.md
  backend/api/v2beta1/python_http_client/kfp_server_api/api/run_service_api.py
  backend/api/v2beta1/python_http_client/test/test_run_service_api.py
  backend/api/v2beta1/run.proto
  backend/api/v2beta1/swagger/kfp_api_single_file.swagger.json
  backend/api/v2beta1/swagger/run.swagger.json
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/server/run_server.go
  backend/src/apiserver/server/run_server_test.go
Labels: lgtm, approved, size/XXL, area/backend

#8806 test(frontend): upgrade frontend integration test dependencies and base image.
  test/frontend-integration-test/Dockerfile
  test/frontend-integration-test/helloworld.spec.js
  test/frontend-integration-test/package-lock.json
  test/frontend-integration-test/package.json
  test/frontend-integration-test/selenium-standalone-chrome-gcloud-nodejs.Docker/Dockerfile
  test/frontend-integration-test/wdio.conf.js
Labels: lgtm, approved, size/XXL

#8813 fix(test): fix missing test dependencies
  backend/src/v2/test/requirements.txt
Labels: lgtm, approved, size/XS

#8819 fix(release): Add v1 and v2 proto generation. Closes #8818
  test/release/bump-version-in-place.sh
Labels: lgtm, approved, size/XS

#8821 chore(test): create test cluster in us-west1-b
  test/deploy-cluster.sh
  test/test-prep.sh
  test/tools/project-cleaner/resource_spec.yaml
Labels: size/XS

#8814 chore(backend): update v2 images for beta release
  backend/src/apiserver/template/template_test.go
  backend/src/v2/compiler/argocompiler/argo.go
  backend/src/v2/compiler/argocompiler/testdata/hello_world.yaml
  backend/src/v2/compiler/argocompiler/testdata/importer.yaml
Labels: lgtm, approved, size/S

#8822 chore(sdk): Pin kfp-server-api to an exact version
  sdk/python/requirements.in
  sdk/python/requirements.txt
Labels: size/XS

#8823 chore(sdk): release KFP SDK 2.0.0b12
  docs/conf.py
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
Labels: lgtm, size/S

#8829 test: install compatible `kfp-server-api` and `kfp` packages
  backend/api/v1beta1/python_http_client/setup.py
  test/sample-test/Dockerfile
Labels: lgtm, approved, size/XS

#8828 Update API references and readme. Closes #8723
  backend/api/README.md
Labels: lgtm, approved, size/M

#8836 feat(sdk): deprecate .set_gpu_limit in favor of .set_accelerator_limit
  sdk/RELEASE.md
  sdk/python/kfp/components/pipeline_task.py
  sdk/python/kfp/components/pipeline_task_test.py
  sdk/python/test_data/pipelines/pipeline_with_resource_spec.py
Labels: lgtm, approved, size/M

#8810 fix(frontend): Remove the "finished at" information for artifact node.
  frontend/src/components/tabs/RuntimeNodeDetailsV2.tsx
Labels: lgtm, approved, size/XS

#8824 fix(frontend): Change the prompt and error message of parameter field into more readable text
  frontend/src/components/NewRunParametersV2.test.tsx
  frontend/src/components/NewRunParametersV2.tsx
Labels: lgtm, approved, size/M

#8834 chore(frontend): Generate TypeScript v2 API client
  frontend/.eslintrc.yaml
  frontend/README.md
  frontend/package.json
  frontend/server/src/generated/apisv2beta1/auth/.gitignore
  frontend/server/src/generated/apisv2beta1/auth/.swagger-codegen-ignore
  frontend/server/src/generated/apisv2beta1/auth/.swagger-codegen/VERSION
  frontend/server/src/generated/apisv2beta1/auth/api.ts
  frontend/server/src/generated/apisv2beta1/auth/configuration.ts
  frontend/server/src/generated/apisv2beta1/auth/custom.d.ts
  frontend/server/src/generated/apisv2beta1/auth/git_push.sh
  frontend/server/src/generated/apisv2beta1/auth/index.ts
  frontend/src/apisv2beta1/experiment/.gitignore
  frontend/src/apisv2beta1/experiment/.swagger-codegen-ignore
  frontend/src/apisv2beta1/experiment/.swagger-codegen/VERSION
  frontend/src/apisv2beta1/experiment/api.ts
  frontend/src/apisv2beta1/experiment/configuration.ts
  frontend/src/apisv2beta1/experiment/custom.d.ts
  frontend/src/apisv2beta1/experiment/git_push.sh
  frontend/src/apisv2beta1/experiment/index.ts
  frontend/src/apisv2beta1/filter/.gitignore
  frontend/src/apisv2beta1/filter/.swagger-codegen-ignore
  frontend/src/apisv2beta1/filter/.swagger-codegen/VERSION
  frontend/src/apisv2beta1/filter/api.ts
  frontend/src/apisv2beta1/filter/configuration.ts
  frontend/src/apisv2beta1/filter/custom.d.ts
  frontend/src/apisv2beta1/filter/git_push.sh
  frontend/src/apisv2beta1/filter/index.ts
  frontend/src/apisv2beta1/pipeline/.gitignore
  frontend/src/apisv2beta1/pipeline/.swagger-codegen-ignore
  frontend/src/apisv2beta1/pipeline/.swagger-codegen/VERSION
  frontend/src/apisv2beta1/pipeline/api.ts
  frontend/src/apisv2beta1/pipeline/configuration.ts
  frontend/src/apisv2beta1/pipeline/custom.d.ts
  frontend/src/apisv2beta1/pipeline/git_push.sh
  frontend/src/apisv2beta1/pipeline/index.ts
  frontend/src/apisv2beta1/recurringrun/.gitignore
  frontend/src/apisv2beta1/recurringrun/.swagger-codegen-ignore
  frontend/src/apisv2beta1/recurringrun/.swagger-codegen/VERSION
  frontend/src/apisv2beta1/recurringrun/api.ts
  frontend/src/apisv2beta1/recurringrun/configuration.ts
  frontend/src/apisv2beta1/recurringrun/custom.d.ts
  frontend/src/apisv2beta1/recurringrun/git_push.sh
  frontend/src/apisv2beta1/recurringrun/index.ts
  frontend/src/apisv2beta1/run/.gitignore
  frontend/src/apisv2beta1/run/.swagger-codegen-ignore
  frontend/src/apisv2beta1/run/.swagger-codegen/VERSION
  frontend/src/apisv2beta1/run/api.ts
  frontend/src/apisv2beta1/run/configuration.ts
  frontend/src/apisv2beta1/run/custom.d.ts
  frontend/src/apisv2beta1/run/git_push.sh
  frontend/src/apisv2beta1/run/index.ts
  frontend/src/apisv2beta1/visualization/.gitignore
  frontend/src/apisv2beta1/visualization/.swagger-codegen-ignore
  frontend/src/apisv2beta1/visualization/.swagger-codegen/VERSION
  frontend/src/apisv2beta1/visualization/api.ts
  frontend/src/apisv2beta1/visualization/configuration.ts
  frontend/src/apisv2beta1/visualization/custom.d.ts
  frontend/src/apisv2beta1/visualization/git_push.sh
  frontend/src/apisv2beta1/visualization/index.ts
Labels: lgtm, approved, size/XXL

#8839 fix(proxy): fixes typo
  proxy/attempt-register-vm-on-proxy.sh
Labels: lgtm, approved, size/XS, needs-ok-to-test

#8838 feat(sdk): Ignore upstream failure
  sdk/RELEASE.md
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/compiler/pipeline_spec_builder.py
  sdk/python/kfp/components/pipeline_task.py
  sdk/python/test_data/pipelines/pipeline_with_task_using_ignore_upstream_failure.py
  sdk/python/test_data/pipelines/pipeline_with_task_using_ignore_upstream_failure.yaml
  sdk/python/test_data/test_data_config.yaml
Labels: lgtm, approved, size/L

#7715 fix(deployment): fix custom namespace for viewer crd deployment. Fixes #7714
  manifests/kustomize/base/pipeline/ml-pipeline-viewer-crd-deployment.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#8841 chore(test): revert api changes to deprecated client
  backend/api/v1beta1/python_http_client/setup.py
  backend/src/v2/test/Dockerfile
  backend/src/v2/test/sample-test.sh
  sdk/python/kfp/deprecated/_client.py
  test/sample-test/Dockerfile
Labels: lgtm, size/M

#8848 fix(sdk): Add outputDefinitions of root pipeline to compiled components IR YAML file
  sdk/RELEASE.md
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/components/structures.py
  sdk/python/test_data/components/add_numbers.yaml
  sdk/python/test_data/components/concat_message.yaml
  sdk/python/test_data/components/container_io.yaml
  sdk/python/test_data/components/container_no_input.yaml
  sdk/python/test_data/components/container_with_artifact_output.yaml
  sdk/python/test_data/components/container_with_concat_placeholder.yaml
  sdk/python/test_data/components/container_with_if_placeholder.yaml
  sdk/python/test_data/components/container_with_placeholder_in_fstring.yaml
  sdk/python/test_data/components/identity.yaml
  sdk/python/test_data/components/nested_return.yaml
  sdk/python/test_data/components/output_metrics.yaml
  sdk/python/test_data/components/preprocess.yaml
Labels: lgtm, approved, size/L

#8856 Add GCPC 1.0.39 release commit
  components/google-cloud/RELEASE.md
  components/google-cloud/google_cloud_pipeline_components/experimental/automl/forecasting/bqml_arima_predict_pipeline.json
  components/google-cloud/google_cloud_pipeline_components/experimental/automl/forecasting/bqml_arima_train_pipeline.json
  components/google-cloud/google_cloud_pipeline_components/experimental/automl/forecasting/prophet_predict_pipeline.json
  components/google-cloud/google_cloud_pipeline_components/experimental/automl/forecasting/prophet_trainer_pipeline.json
  components/google-cloud/google_cloud_pipeline_components/experimental/automl/tabular/automl_tabular_pipeline.json
  components/google-cloud/google_cloud_pipeline_components/experimental/automl/tabular/tabnet_hyperparameter_tuning_job_pipeline.json
  components/google-cloud/google_cloud_pipeline_components/experimental/automl/tabular/tabnet_trainer_pipeline.json
  components/google-cloud/google_cloud_pipeline_components/experimental/automl/tabular/wide_and_deep_hyperparameter_tuning_job_pipeline.json
  components/google-cloud/google_cloud_pipeline_components/experimental/automl/tabular/wide_and_deep_trainer_pipeline.json
Labels: approved, needs-ok-to-test, size/M

#8855 chore(sdk): bump JsonSchema pinned version to >=3.0.1,<5. Fixes #8648
  sdk/RELEASE.md
  sdk/python/requirements.in
  sdk/python/setup.py
Labels: size/XS, ok-to-test

#8859 fix(backend): Allow empty namespace in pipelines. Fixes #8840.
  backend/src/apiserver/server/api_converter.go
  backend/src/apiserver/server/api_converter_test.go
Labels: lgtm, approved, size/M

#8484 feat(sdk): support input list of artifacts in Custom Container Components [lists of artifacts support pt. 4]
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/compiler/pipeline_spec_builder.py
  sdk/python/kfp/components/component_factory.py
  sdk/python/kfp/components/component_factory_test.py
  sdk/python/kfp/components/container_component_artifact_channel_test.py
  sdk/python/kfp/components/placeholders.py
  sdk/python/kfp/components/placeholders_test.py
  sdk/python/kfp/components/structures.py
Labels: lgtm, approved, size/L

#8857 fix(backend): Add default values to timestamps. Fixes #8845
  backend/src/apiserver/model/job.go
  backend/src/apiserver/model/task.go
  backend/src/apiserver/storage/experiment_store.go
  backend/src/apiserver/storage/job_store.go
  backend/src/apiserver/storage/pipeline_store.go
  backend/src/apiserver/storage/run_store.go
  backend/src/apiserver/storage/task_store.go
Labels: lgtm, approved, size/M

#8860 chore(backend): update v2 images
  backend/src/apiserver/template/template_test.go
  backend/src/v2/compiler/argocompiler/argo.go
  backend/src/v2/compiler/argocompiler/testdata/hello_world.yaml
  backend/src/v2/compiler/argocompiler/testdata/importer.yaml
Labels: lgtm, approved, size/S

#8865 chore(sdk): release 1.8.19
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
Labels: size/S

#8866 chore(sdk): add 1.8.19 docs
  docs/conf.py
Labels: size/XS

#8831 feat(frontend): Support namespaced pipelines from the UI. Closes #5084
  frontend/src/atoms/MD2Tabs.tsx
  frontend/src/atoms/__snapshots__/MD2Tabs.test.tsx.snap
  frontend/src/components/PipelinesDialog.test.tsx
  frontend/src/components/PipelinesDialog.tsx
  frontend/src/components/PrivateSharedSelector.test.tsx
  frontend/src/components/PrivateSharedSelector.tsx
  frontend/src/components/Router.tsx
  frontend/src/components/SideNav.test.tsx
  frontend/src/components/SideNav.tsx
  frontend/src/components/UploadPipelineDialog.test.tsx
  frontend/src/components/UploadPipelineDialog.tsx
  frontend/src/components/__snapshots__/PipelinesDialog.test.tsx.snap
  frontend/src/components/__snapshots__/PrivateSharedSelector.test.tsx.snap
  frontend/src/components/__snapshots__/SideNav.test.tsx.snap
  frontend/src/components/__snapshots__/UploadPipelineDialog.test.tsx.snap
  frontend/src/index.tsx
  frontend/src/lib/Apis.ts
  frontend/src/lib/BuildInfo.tsx
  frontend/src/pages/NewPipelineVersion.test.tsx
  frontend/src/pages/NewPipelineVersion.tsx
  frontend/src/pages/NewRun.tsx
  frontend/src/pages/NewRunV2.tsx
  frontend/src/pages/PipelineList.test.tsx
  frontend/src/pages/PipelineList.tsx
  frontend/src/pages/PrivateAndSharedPipelines.test.tsx
  frontend/src/pages/PrivateAndSharedPipelines.tsx
  frontend/src/pages/ResourceSelector.tsx
  frontend/src/pages/__snapshots__/NewPipelineVersion.test.tsx.snap
  frontend/src/pages/__snapshots__/NewRun.test.tsx.snap
  frontend/src/pages/__snapshots__/PipelineList.test.tsx.snap
  frontend/src/pages/__snapshots__/PrivateAndSharedPipelines.test.tsx.snap
Labels: lgtm, approved, size/XXL

#8808 feat(sdk): support fan-in artifacts from `dsl.ParallelFor`
  sdk/RELEASE.md
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/compiler/compiler_utils.py
  sdk/python/kfp/compiler/compiler_utils_test.py
  sdk/python/kfp/compiler/pipeline_spec_builder.py
  sdk/python/kfp/components/base_component.py
  sdk/python/kfp/components/component_factory.py
  sdk/python/kfp/components/component_factory_test.py
  sdk/python/kfp/components/container_component.py
  sdk/python/kfp/components/for_loop.py
  sdk/python/kfp/components/graph_component.py
  sdk/python/kfp/components/pipeline_channel.py
  sdk/python/kfp/components/pipeline_channel_test.py
  sdk/python/kfp/components/pipeline_task.py
  sdk/python/kfp/components/pipeline_task_test.py
  sdk/python/kfp/components/placeholders.py
  sdk/python/kfp/components/python_component.py
  sdk/python/kfp/components/structures.py
  sdk/python/kfp/components/types/type_utils.py
  sdk/python/kfp/components/types/type_utils_test.py
  sdk/python/test_data/pipelines/parallelfor_fan_in/artifacts_complex.py
  sdk/python/test_data/pipelines/parallelfor_fan_in/artifacts_complex.yaml
  sdk/python/test_data/pipelines/parallelfor_fan_in/artifacts_simple.py
  sdk/python/test_data/pipelines/parallelfor_fan_in/artifacts_simple.yaml
  sdk/python/test_data/pipelines/parallelfor_fan_in/parameters_complex.py
  sdk/python/test_data/pipelines/parallelfor_fan_in/parameters_complex.yaml
  sdk/python/test_data/pipelines/parallelfor_fan_in/parameters_simple.py
  sdk/python/test_data/pipelines/parallelfor_fan_in/parameters_simple.yaml
  sdk/python/test_data/test_data_config.yaml
Labels: lgtm, approved, size/XXL

#8862 chore(frontend): Support v1 and v2 API request simultaneously in the frontend server
  frontend/server/app.ts
  frontend/server/configs.ts
Labels: lgtm, approved, size/M

#8879 fix(sdk): fix bug when passing data between tasks using f-strings
  sdk/RELEASE.md
  sdk/python/kfp/compiler/pipeline_spec_builder.py
  sdk/python/test_data/pipelines/pipeline_with_params_containing_format.yaml
Labels: lgtm, approved, size/S

#8880 fix(sdk): fix unknown artifact string in dsl.OutputPath/dsl.InputPath
  sdk/python/kfp/components/component_factory_test.py
  sdk/python/kfp/components/types/type_annotations.py
Labels: lgtm, approved, size/M

#8885 fix(sdk): Fix environment variable set in component yaml lost during compilation. Fixes #8884
  sdk/RELEASE.md
  sdk/python/kfp/components/structures.py
  sdk/python/kfp/components/structures_test.py
  sdk/python/test_data/pipelines/pipeline_with_env.py
  sdk/python/test_data/pipelines/pipeline_with_env.yaml
Labels: lgtm, approved, size/M

#8864 chore(frontend): Integrate the experiment-only functions with KFP v2 API
  frontend/src/components/ExperimentList.test.tsx
  frontend/src/components/ExperimentList.tsx
  frontend/src/lib/Apis.ts
  frontend/src/lib/Buttons.ts
  frontend/src/pages/ArchivedExperiments.test.tsx
  frontend/src/pages/ArchivedExperiments.tsx
  frontend/src/pages/ExperimentDetails.test.tsx
  frontend/src/pages/ExperimentDetails.tsx
  frontend/src/pages/ExperimentList.test.tsx
  frontend/src/pages/ExperimentList.tsx
  frontend/src/pages/NewExperiment.test.tsx
  frontend/src/pages/NewExperiment.tsx
  frontend/src/pages/__snapshots__/ArchivedExperiments.test.tsx.snap
Labels: lgtm, approved, size/L

#8886 feat(backend): add support for environment variables. Fixes #8704
  backend/src/v2/driver/driver.go
  samples/test/config.yaml
  samples/v2/pipeline_with_env.py
  samples/v2/pipeline_with_env_test.py
Labels: lgtm, approved, size/L, area/backend

#8887 fix(sdk): fix attribute error for Containerized Python Components
  sdk/RELEASE.md
  sdk/python/kfp/components/executor.py
Labels: lgtm, approved, size/S

#8904 chore(sdk): release SDK 2.0.0b13
  docs/conf.py
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
Labels: lgtm, approved, size/S

#8901 fix(backend): Add ListAllRuns endpoint
  backend/api/v2beta1/go_client/run.pb.go
  backend/api/v2beta1/go_client/run.pb.gw.go
  backend/api/v2beta1/go_http_client/run_client/run_service/list_all_runs_parameters.go
  backend/api/v2beta1/go_http_client/run_client/run_service/list_all_runs_responses.go
  backend/api/v2beta1/go_http_client/run_client/run_service/run_service_client.go
  backend/api/v2beta1/run.proto
  backend/api/v2beta1/swagger/kfp_api_single_file.swagger.json
  backend/api/v2beta1/swagger/run.swagger.json
  backend/src/apiserver/server/run_server.go
Labels: lgtm, approved, size/XL

#8903 fix(backend): Add checking for state change in state history
  backend/src/apiserver/storage/run_store.go
  backend/src/apiserver/storage/run_store_test.go
  backend/src/apiserver/storage/task_store.go
Labels: lgtm, approved, size/M
