Repository kubeflow/pipelines, pull requests merged in 2024-04, with the labels that each got.

#10652 chore(components): Update kserve component to v0.12.0
  components/kserve/Dockerfile
  components/kserve/README.md
  components/kserve/component.yaml
  components/kserve/requirements.txt
Labels: lgtm, approved, size/XS

#10550 fix(Backend + SDK): Add missing optional field to SecretAsVolume and …
  backend/src/v2/driver/driver.go
  backend/src/v2/driver/driver_test.go
  backend/third_party_licenses/apiserver.csv
  backend/third_party_licenses/driver.csv
  go.mod
  go.sum
  kubernetes_platform/python/README.md
  kubernetes_platform/python/kfp/kubernetes/config_map.py
  kubernetes_platform/python/kfp/kubernetes/secret.py
  kubernetes_platform/python/test/snapshot/data/config_map_as_vol.yaml
  kubernetes_platform/python/test/snapshot/data/secret_as_vol.yaml
  kubernetes_platform/python/test/unit/test_config_map.py
  kubernetes_platform/python/test/unit/test_image_pull_secrets.py
  kubernetes_platform/python/test/unit/test_node_selector.py
  kubernetes_platform/python/test/unit/test_pod_metadata.py
  kubernetes_platform/python/test/unit/test_secret.py
  kubernetes_platform/python/test/unit/test_tolerations.py
  kubernetes_platform/python/test/unit/test_volume.py
Labels: lgtm, approved, size/L, ok-to-test

#10618 chore: Update argo images to 3.4.16
  third_party/argo/VERSION
  third_party/argo/imp-1-update-notices.sh
  third_party/argo/licenses-argoexec.csv
  third_party/argo/licenses-workflow-controller.csv
Labels: lgtm, approved, size/L

#10659 chore(sample): add note about secret needing to be pre-created
  samples/v2/pipeline_with_secret_as_env.py
  samples/v2/pipeline_with_secret_as_volume.py
Labels: lgtm, approved, needs-ok-to-test, size/S

#10680 Chore(components): Clean up old ibm components
  components/ibm-components/README.md
  components/ibm-components/commons/config/Dockerfile
  components/ibm-components/commons/config/component.yaml
  components/ibm-components/commons/config/src/config.py
  components/ibm-components/ffdl/serve/Dockerfile
  components/ibm-components/ffdl/serve/README.md
  components/ibm-components/ffdl/serve/component.yaml
  components/ibm-components/ffdl/serve/requirements.txt
  components/ibm-components/ffdl/serve/src/app.py
  components/ibm-components/ffdl/serve/src/kube/seldon.json
  components/ibm-components/ffdl/serve/src/serve.py
  components/ibm-components/ffdl/train/Dockerfile
  components/ibm-components/ffdl/train/README.md
  components/ibm-components/ffdl/train/component.yaml
  components/ibm-components/ffdl/train/requirements.txt
  components/ibm-components/ffdl/train/src/train.py
  components/ibm-components/spark/data_preprocess_spark/Dockerfile
  components/ibm-components/spark/data_preprocess_spark/component.yaml
  components/ibm-components/spark/data_preprocess_spark/src/data_preprocess_spark.py
  components/ibm-components/spark/store_spark_model/Dockerfile
  components/ibm-components/spark/store_spark_model/component.yaml
  components/ibm-components/spark/store_spark_model/src/store_spark_model.py
  components/ibm-components/spark/train_spark/Dockerfile
  components/ibm-components/spark/train_spark/component.yaml
  components/ibm-components/spark/train_spark/src/spark-submit.sh
  components/ibm-components/spark/train_spark/src/train_spark.py
  components/ibm-components/spark/train_spark/src/wrapper.py
  components/ibm-components/watson/deploy/Dockerfile
  components/ibm-components/watson/deploy/component.yaml
  components/ibm-components/watson/deploy/requirements.txt
  components/ibm-components/watson/deploy/src/wml-deploy.py
  components/ibm-components/watson/manage/monitor_fairness/Dockerfile
  components/ibm-components/watson/manage/monitor_fairness/component.yaml
  components/ibm-components/watson/manage/monitor_fairness/src/monitor_fairness.py
  components/ibm-components/watson/manage/monitor_quality/Dockerfile
  components/ibm-components/watson/manage/monitor_quality/component.yaml
  components/ibm-components/watson/manage/monitor_quality/src/monitor_quality.py
  components/ibm-components/watson/manage/subscribe/Dockerfile
  components/ibm-components/watson/manage/subscribe/component.yaml
  components/ibm-components/watson/manage/subscribe/src/subscribe.py
  components/ibm-components/watson/store/Dockerfile
  components/ibm-components/watson/store/component.yaml
  components/ibm-components/watson/store/requirements.txt
  components/ibm-components/watson/store/src/wml-store.py
  components/ibm-components/watson/train/Dockerfile
  components/ibm-components/watson/train/component.yaml
  components/ibm-components/watson/train/requirements.txt
  components/ibm-components/watson/train/src/wml-train.py
Labels: lgtm, approved, size/XXL

#10605 feat(sdk+backend): Add support for generic ephemeral volume
  backend/src/v2/driver/driver.go
  backend/src/v2/driver/driver_test.go
  backend/third_party_licenses/apiserver.csv
  backend/third_party_licenses/cache_server.csv
  backend/third_party_licenses/driver.csv
  backend/third_party_licenses/launcher.csv
  backend/third_party_licenses/persistence_agent.csv
  backend/third_party_licenses/swf.csv
  backend/third_party_licenses/viewer.csv
  go.mod
  go.sum
  kubernetes_platform/python/README.md
  kubernetes_platform/python/kfp/kubernetes/__init__.py
  kubernetes_platform/python/kfp/kubernetes/volume.py
  kubernetes_platform/python/test/snapshot/data/general_ephemeral_volume.py
  kubernetes_platform/python/test/snapshot/data/general_ephemeral_volume.yaml
  kubernetes_platform/python/test/unit/test_node_selector.py
  kubernetes_platform/python/test/unit/test_volume.py
Labels: lgtm, approved, size/XL, ok-to-test

#10689 chore(backend): Promote @rimolive as the backend reviewer
  backend/OWNERS
Labels: lgtm, approved, size/XS

#10692 chore(sdk): release `kfp-kubernetes` 1.2.0
  kubernetes_platform/python/docs/conf.py
  kubernetes_platform/python/kfp/kubernetes/__init__.py
  kubernetes_platform/python/setup.py
Labels: lgtm, approved, size/S

#10693 chore(sdk): make `kfp-kubernetes` release instructions public
  kubernetes_platform/python/RELEASE.md
Labels: lgtm, approved, size/M

#10671 chore(kfp-kubernetes): change type of affinity weight to int32
  kubernetes_platform/go/kubernetesplatform/kubernetes_executor_config.pb.go
  kubernetes_platform/proto/kubernetes_executor_config.proto
Labels: lgtm, approved, size/S, ok-to-test

#10678 feat(backend): Merge kfp-tekton backend code
  backend/Dockerfile
  backend/Dockerfile.cacheserver
  backend/Dockerfile.conformance
  backend/Dockerfile.driver
  backend/Dockerfile.launcher
  backend/Dockerfile.persistenceagent
  backend/Dockerfile.scheduledworkflow
  backend/Dockerfile.viewercontroller
  backend/src/agent/persistence/client/pipeline_client.go
  backend/src/agent/persistence/main.go
  backend/src/agent/persistence/worker/swf_saver.go
  backend/src/apiserver/client/argo_fake.go
  backend/src/apiserver/client_manager/client_manager.go
  backend/src/apiserver/main.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/server/api_converter.go
  backend/src/apiserver/server/report_server.go
  backend/src/apiserver/template/argo_template.go
  backend/src/apiserver/template/template_test.go
  backend/src/apiserver/template/v2_template.go
  backend/src/common/util/execution_client.go
  backend/src/common/util/execution_spec.go
  backend/src/common/util/execution_spec_test.go
  backend/src/common/util/pipelinerun.go
  backend/src/common/util/workflow.go
  backend/src/crd/controller/scheduledworkflow/util/scheduled_workflow.go
  backend/src/crd/pkg/apis/scheduledworkflow/v1beta1/types.go
  backend/src/v2/compiler/tektoncompiler/common.go
  backend/src/v2/compiler/tektoncompiler/container.go
  backend/src/v2/compiler/tektoncompiler/dag.go
  backend/src/v2/compiler/tektoncompiler/importer.go
  backend/src/v2/compiler/tektoncompiler/proto.go
  backend/src/v2/compiler/tektoncompiler/tekton.go
  backend/src/v2/compiler/tektoncompiler/tekton_test.go
  backend/src/v2/compiler/tektoncompiler/testdata/condition_ir.yaml
  backend/src/v2/compiler/tektoncompiler/testdata/exit_handler.yaml
  backend/src/v2/compiler/tektoncompiler/testdata/exit_handler_ir.yaml
  backend/src/v2/compiler/tektoncompiler/testdata/hello_world.yaml
  backend/src/v2/compiler/tektoncompiler/testdata/importer.yaml
  backend/src/v2/compiler/tektoncompiler/testdata/loop_static.yaml
  backend/src/v2/compiler/tektoncompiler/testdata/loop_static_ir.yaml
  backend/src/v2/compiler/tektoncompiler/testdata/mnist_pipeline.yaml
  backend/src/v2/compiler/tektoncompiler/testdata/mnist_pipeline_ir.yaml
  backend/src/v2/compiler/tektoncompiler/testdata/nestedloop.yaml
  backend/src/v2/compiler/tektoncompiler/testdata/nestedloop_ir.yaml
  backend/src/v2/compiler/tektoncompiler/testdata/pod_metadata.yaml
  backend/src/v2/component/launcher_v2.go
  backend/src/v2/component/launcher_v2_test.go
  backend/src/v2/driver/driver.go
  backend/src/v2/objectstore/object_store.go
  backend/third_party_licenses/apiserver.csv
  backend/third_party_licenses/cache_server.csv
  backend/third_party_licenses/driver.csv
  backend/third_party_licenses/launcher.csv
  backend/third_party_licenses/persistence_agent.csv
  backend/third_party_licenses/swf.csv
  go.mod
  go.sum
Labels: lgtm, approved, size/XXL

#10625 feat(backend): add namespace & prefix scoped credentials to kfp-launcher config for object store paths
  backend/src/v2/component/importer_launcher.go
  backend/src/v2/component/launcher_v2.go
  backend/src/v2/component/launcher_v2_test.go
  backend/src/v2/config/env.go
  backend/src/v2/config/env_test.go
  backend/src/v2/config/gcs.go
  backend/src/v2/config/minio.go
  backend/src/v2/config/s3.go
  backend/src/v2/config/testdata/provider_cases.yaml
  backend/src/v2/driver/driver.go
  backend/src/v2/metadata/client.go
  backend/src/v2/metadata/client_fake.go
  backend/src/v2/metadata/client_test.go
  backend/src/v2/objectstore/config.go
  backend/src/v2/objectstore/object_store.go
  backend/src/v2/objectstore/object_store_test.go
  go.mod
Labels: lgtm, approved, size/XXL

#10733 chore(backend): update kfp launcher and driver images
  backend/src/v2/compiler/argocompiler/container.go
Labels: size/XS

#10767 chore: Update RELEASE.md
  RELEASE.md
Labels: lgtm, approved, size/XS
