Repository kubeflow/pipelines, pull requests merged in 2024-07, with the labels that each got.

#10932 test: kubeflow-pipeline-upgrade-test migrated to GitHub Actions
  .github/workflows/upgrade-test.yml
  test/e2e_test_gke_v2.yaml
  test/upgrade-tests.sh
Labels: lgtm, approved, size/L

#10972 test: Migrate Frontend tests to a GHA Workflow
  .github/workflows/frontend.yml
Labels: lgtm, approved, size/M

#10859 test: install kfp on github periodic functional tests workflow
  .github/workflows/periodic.yml
  test/kfp-functional-test/kfp-functional-test.sh
Labels: lgtm, approved, size/S, ok-to-test

#10930 chore: Add an option to re-run GHA workflows
  .github/workflows/rerun-pr-jobs.yaml
Labels: lgtm, approved, size/S

#10984 test: Moved KFP backend visualization tests to GitHub Actions
  .github/workflows/backend-visualization.yml
Labels: lgtm, approved, size/S

#10989 test: Migrate KFP SDK Upgrade Test to GHA
  .github/workflows/sdk-upgrade.yml
Labels: lgtm, approved, size/S

#10991 test: Migrate KFP SDK Runtime Code Test to GHA
  .github/workflows/kfp-sdk-runtime-tests.yml
Labels: lgtm, approved, size/M

#10892 feat(kubernetes_platform): Add empty dir mount
  kubernetes_platform/go/kubernetesplatform/kubernetes_executor_config.pb.go
  kubernetes_platform/proto/kubernetes_executor_config.proto
Labels: lgtm, approved, size/XL, ok-to-test

#10975 test: Migrate KFP SDK Execution Tests to GHA
  .github/workflows/sdk-execution.yml
  test/presubmit-sdk-execution-tests.sh
Labels: lgtm, approved, size/M

#10924 test: Removed mkp tests
  manifests/gcp_marketplace/test/presubmit.sh
  manifests/gcp_marketplace/test/snapshot-base.yaml
  manifests/gcp_marketplace/test/snapshot-emissary.yaml
  manifests/gcp_marketplace/test/snapshot-managed-storage-with-db-prefix.yaml
  manifests/gcp_marketplace/test/snapshot-managed-storage.yaml
  manifests/gcp_marketplace/test/snapshots.sh
  manifests/gcp_marketplace/test/values-base.yaml
  manifests/gcp_marketplace/test/values-emissary.yaml
  manifests/gcp_marketplace/test/values-managed-storage-with-db-prefix.yaml
  manifests/gcp_marketplace/test/values-managed-storage.yaml
  test/cloudbuild/mkp_verify.yaml
  test/deploy-pipeline-mkp-cli.sh
  test/images/Dockerfile
  test/images/README.md
  test/postsubmit-tests-with-pipeline-deployment.sh
  test/presubmit-tests-mkp.sh
Labels: lgtm, approved, size/XXL

#11005 fix(sdk): Throw 'exit_task cannot depend on any other tasks.' error when an ExitHandler has a parameter dependent on other task
  sdk/python/kfp/dsl/tasks_group.py
Labels: lgtm, approved, size/S

#10895 fix(docs): add note about protoc dependency and version
  kubernetes_platform/README.md
Labels: lgtm, approved, size/XS, ok-to-test

#11042 chore: Adding @gregsheremeta to SDK reviewers.
  sdk/OWNERS
Labels: lgtm, approved, size/XS

#11043 chore: Adding @HumairAK to backend and frontend reviewers
  backend/OWNERS
  frontend/OWNERS
Labels: lgtm, approved, size/XS

#11031 fix(docs): IR -> Pipeline Spec
  sdk/python/kfp/cli/dsl.py
Labels: lgtm, approved, size/XS

#11032 test: Migrate miscellaneous SDK tests to GHA Workflow
  .github/workflows/sdk-component-yaml.yml
  .github/workflows/sdk-docformatter.yml
  .github/workflows/sdk-isort.yml
Labels: lgtm, approved, size/L

#11044 chore: Adding @gregsheremeta to SDK reviewers (kubernetes_platform)
  kubernetes_platform/OWNERS
Labels: lgtm, approved, size/XS

#11037 test: Migrate KFP SDK Tests to GHA
  .github/workflows/kfp-sdk-tests.yml
  sdk/python/kfp/cli/component_test.py
Labels: lgtm, approved, size/M

#11045 chore: adding @hbelmiro to kubernetes_platform/OWNERS
  kubernetes_platform/OWNERS
Labels: lgtm, approved, size/XS

#10926 test: Moved kfp-kubernetes-execution-tests to GitHub Actions
  .github/workflows/kfp-kubernetes-execution-tests.yml
  kubernetes_platform/python/generate_proto.py
  kubernetes_platform/python/test/snapshot/test_data_config.yaml
  test/presubmit-kfp-kubernetes-execution-tests.sh
Labels: lgtm, approved, size/L

#11046 add dev docs for kfp/sdk
  api/Makefile
  kubernetes_platform/Makefile
  sdk/CONTRIBUTING.md
Labels: lgtm, approved, size/M

#11048 test: Moved kubeflow-pipelines-samples-v2 to GitHub Actions
  .github/workflows/kfp-samples.yml
  backend/src/v2/test/Makefile
  backend/src/v2/test/requirements-sample-test.txt
  backend/src/v2/test/sample-test.sh
  backend/src/v2/test/sample_test.py
  samples/v2/sample_test.py
Labels: lgtm, approved, size/L

#11006 test: Add script and GitHub Action for kfp-kubernetes-library
  .github/workflows/kfp-kubernetes-library-test.yaml
  test/presubmit-test-kfp-kubernetes-library.sh
Labels: approved, size/M
