Repository kubeflow/pipelines, pull requests merged in 2024-06, with the labels that each got.

#10864 chore: Change command to apply manifests in the docs
  backend/src/v2/test/README.md
  manifests/kustomize/README.md
  manifests/kustomize/env/aws/README.md
  manifests/kustomize/sample/README.md
  manifests/kustomize/sample/kustomization.yaml
Labels: lgtm, approved, size/S

#10669 fix(manifests): Move metacontroller to the top in kustmization.yaml
  manifests/kustomize/env/platform-agnostic-multi-user-legacy/kustomization.yaml
  manifests/kustomize/env/platform-agnostic-multi-user/kustomization.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#10871 test: Migrate Backend tests to a GHA workflow
  .github/workflows/presubmit-backend.yml
  test/presubmit-backend-test.sh
Labels: lgtm, approved, size/M

#10857 feat(backend): mount EmptyDir volumes for launcher write locations
  backend/src/v2/compiler/argocompiler/container.go
  backend/src/v2/compiler/argocompiler/testdata/create_mount_delete_dynamic_pvc.yaml
  backend/src/v2/compiler/argocompiler/testdata/create_pod_metadata.yaml
  backend/src/v2/compiler/argocompiler/testdata/hello_world.yaml
Labels: lgtm, approved, size/L

#10887 test: migrate kubeflow-pipeline-e2e-test to GitHub Actions
  .github/workflows/e2e-test.yaml
  backend/test/initialization/initialization_test.go
  backend/test/integration/experiment_api_test.go
  backend/test/integration/healthz_api_test.go
  backend/test/integration/job_api_test.go
  backend/test/integration/pipeline_api_test.go
  backend/test/integration/pipeline_version_api_test.go
  backend/test/integration/run_api_test.go
  backend/test/integration/upgrade_test.go
  backend/test/integration/visualization_api_test.go
  backend/test/test_utils.go
  backend/test/v2/initialization/initialization_test.go
  backend/test/v2/integration/experiment_api_test.go
  backend/test/v2/integration/healthz_api_test.go
  backend/test/v2/integration/pipeline_api_test.go
  backend/test/v2/integration/pipeline_version_api_test.go
  backend/test/v2/integration/recurring_run_api_test.go
  backend/test/v2/integration/run_api_test.go
  backend/test/v2/integration/upgrade_test.go
  backend/test/v2/test_utils.go
  scripts/deploy/github/forward-port.sh
  test/api-integration-test/Dockerfile
  test/api-integration-test/OWNERS
  test/api-integration-test/run_test.sh
  test/e2e_test_gke_v2.yaml
  test/frontend-integration-test/helloworld.spec.js
  test/initialization-test/Dockerfile
  test/initialization-test/OWNERS
  test/initialization-test/run_test.sh
  test/sample-test/Dockerfile
  test/sample-test/constants.py
  test/sample-test/sample_test_launcher.py
Labels: lgtm, approved, size/XL

#10890 fix(kubernetes_platform): fix api-generator docker mount for SELinux
  kubernetes_platform/Makefile
Labels: lgtm, approved, size/XS, ok-to-test

#10941 chore: Updated Python image to 3.8 in backend/Dockerfile
  backend/Dockerfile
Labels: lgtm, approved, size/XS

#10943 Expose starry_net yaml to GitHub
  components/google-cloud/google_cloud_pipeline_components/_implementation/starry_net/evaluation/evaluation.yaml
  components/google-cloud/google_cloud_pipeline_components/_implementation/starry_net/upload_model/upload_model.yaml
Labels: lgtm, approved, size/L

#10940 chore(sdk): release KFP SDK 2.8.0
  docs/versions.json
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
Labels: lgtm, approved, size/S

#10945 chore: Upgrade Python version to 3.8 in readthedocs config
  .readthedocs.yml
Labels: lgtm, approved, size/XS

#10787 feat(frontend&backend): Add UI support for object store customization and prefixes
  backend/src/v2/component/importer_launcher.go
  backend/src/v2/component/launcher_v2.go
  backend/src/v2/config/env.go
  backend/src/v2/metadata/client.go
  backend/src/v2/metadata/client_fake.go
  backend/src/v2/objectstore/config.go
  backend/src/v2/objectstore/object_store.go
  frontend/server/aws-helper.test.ts
  frontend/server/aws-helper.ts
  frontend/server/handlers/artifacts.ts
  frontend/server/integration-tests/artifact-get.test.ts
  frontend/server/k8s-helper.ts
  frontend/server/minio-helper.test.ts
  frontend/server/minio-helper.ts
  frontend/server/utils.ts
  frontend/server/workflow-helper.ts
  frontend/src/components/ArtifactPreview.tsx
  frontend/src/components/MinioArtifactPreview.tsx
  frontend/src/components/tabs/InputOutputTab.tsx
  frontend/src/components/tabs/RuntimeNodeDetailsV2.tsx
  frontend/src/components/viewers/MetricsVisualizations.tsx
  frontend/src/lib/Apis.test.ts
  frontend/src/lib/Apis.ts
  frontend/src/lib/OutputArtifactLoader.test.ts
  frontend/src/lib/OutputArtifactLoader.ts
  frontend/src/mlmd/MlmdUtils.ts
  frontend/src/pages/RunList.test.tsx
Labels: lgtm, approved, size/XL

#10956 docs(backend): Remove deprecated v2 compatibility mode docs
  backend/src/v2/README.md
Labels: lgtm, approved, size/M

#10911 Upgrade go version to 1.21
  .github/workflows/backend.yml
  api/go.mod
  backend/api/Dockerfile
  go.mod
  go.sum
  kubernetes_platform/go.mod
  kubernetes_platform/go.sum
  test/tools/project-cleaner/go.mod
  third_party/ml-metadata/go.mod
  third_party/ml-metadata/go.sum
Labels: lgtm, approved, size/M

#10963 chore: Added @rimolive, @hbelmiro and @DharmitD as approvers and reviewers for GitHub Actions
  .github/OWNERS
  scripts/OWNERS
  test/OWNERS
Labels: lgtm, approved, size/S

#10961 test: Migrate KFP SDK YAPF test to a GHA Workflow
  .github/workflows/sdk-yapf.yml
Labels: lgtm, approved, size/M
