Repository kubeflow/pipelines, pull requests merged in 2024-10, with the labels that each got.

#10790 feat(backend): Remove PipelineSpec Template storage from ObjStore responsibilies. Fixes #10509
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/server/fakes_test.go
  backend/src/apiserver/server/pipeline_upload_server_test.go
Labels: lgtm, approved, size/L

#11243 fix(backend): randomizing output uri path to avoid overwriting. Fixes #10186
  backend/src/v2/driver/driver.go
Labels: lgtm, approved, size/XS, ok-to-test

#11270 correct lastrun unittest timestamps
  backend/src/apiserver/server/experiment_server_test.go
Labels: lgtm, approved, size/XS

#11276 chore(doc): Update kfp-kubenetes release instructions.
  kubernetes_platform/python/RELEASE.md
Labels: lgtm, approved, size/S

#11281 fix(backend): set default value to true for ForcePathStyle
  backend/src/v2/objectstore/config.go
Labels: lgtm, approved, size/XS, needs-ok-to-test

#11284 feat(workflows): use built images in Github workflows
  scripts/deploy/github/build-images.sh
  scripts/deploy/github/deploy-kfp.sh
  scripts/deploy/github/kfp-readiness/wait_for_pods.py
Labels: lgtm, approved, size/M, ok-to-test

#11262 test: Integrate Git Hub Action Results into Tide
  .github/workflows/add-ci-passed-label.yml
  .github/workflows/ci-checks.yml
Labels: lgtm, approved, size/L, ok-to-test

#11297 Revert "chore(deps): bump golang.org/x/net from 0.0.0-20210726213435-…
  test/tools/project-cleaner/go.mod
  test/tools/project-cleaner/go.sum
Labels: lgtm, approved, size/M, ci-passed

#11298 chore: update SinglePlatformSpec and ComponentSpec for Vertex Platform speci…
  api/v2alpha1/pipeline_spec.proto
Labels: lgtm, approved, size/XS, ci-passed

#11299 feat: add fields in SinglePlatformSpec
  api/v2alpha1/pipeline_spec.proto
Labels: lgtm, approved, size/XS, ci-passed

#11295 test: Resolve ci-check failures in long-running CI tests
  .github/workflows/add-ci-passed-label.yml
  .github/workflows/ci-checks.yml
Labels: lgtm, approved, size/M, ok-to-test, ci-passed

#11300 test: Fix failing SDK tests by creating Python virtual environment
  test/presubmit-tests-sdk.sh
Labels: lgtm, approved, size/XS, ok-to-test

#11294 feat(testing): use kustomize to patch deployments before deploy
  .github/actions/kfp-cluster/action.yml
  .github/actions/kfp-tekton-cluster/action.yml
  .github/resources/manifests/argo/kustomization.yaml
  .github/resources/manifests/argo/overlays/apiserver-env.yaml
  .github/resources/manifests/tekton/kustomization.yaml
  .github/resources/scripts/build-images.sh
  .github/resources/scripts/deploy-kfp-tekton.sh
  .github/resources/scripts/deploy-kfp.sh
  .github/resources/scripts/e2e-test.sh
  .github/resources/scripts/forward-port.sh
  .github/resources/scripts/helper-functions.sh
  .github/resources/scripts/kfp-readiness/wait_for_pods.py
  .github/resources/scripts/re-tag.sh
  .github/resources/scripts/test-dynamic-loop.sh
  .github/resources/scripts/test-env.sh
  .github/resources/scripts/test-flip-coin.sh
  .github/resources/scripts/test-pipeline.sh
  .github/resources/scripts/test-secret-as-env.sh
  .github/resources/scripts/test-secret-as-volume.sh
  .github/resources/scripts/test-static-loop.sh
  .github/resources/scripts/test-volume.sh
  .github/workflows/backend.yml
  .github/workflows/e2e-test.yml
  .github/workflows/kfp-kubernetes-execution-tests.yml
  .github/workflows/kfp-samples.yml
  .github/workflows/kubeflow-pipelines-integration-v2.yml
  .github/workflows/sdk-execution.yml
  .github/workflows/upgrade-test.yml
  scripts/OWNERS
Labels: lgtm, approved, size/L, ok-to-test, ci-passed

#11306 test: Disabled ci-check and add-ci-passed-label workflows.
  .github/workflows/add-ci-passed-label.yml.disabled
  .github/workflows/ci-checks.yml.disabled
Labels: lgtm, approved, size/XS

#11320 test: Enabled ci-check and add-ci-passed-label workflows
  .github/workflows/add-ci-passed-label.yml
  .github/workflows/ci-checks.yml
Labels: lgtm, approved, size/XS, ok-to-test

#11322 fix(tests): remove redundant integration test wf
  .github/workflows/kfp-samples.yml
  .github/workflows/kubeflow-pipelines-integration-v2.yml
  backend/src/v2/test/integration-test.sh
Labels: lgtm, approved, size/M, ok-to-test, ci-passed

#11317 adding chore as a new template. Fixes #11263
  .github/ISSUE_TEMPLATE/CHORE.md
Labels: lgtm, approved, size/S, ci-passed

#11332 Add-Create-Experiment-button-when-selecting-experiement-final
  frontend/src/pages/NewRunV2.tsx
  frontend/src/pages/functional_components/NewExperimentFC.tsx
Labels: lgtm, approved, size/L, ci-passed

#11333 feat(api): add PipelineConfig to api to re-implement pipeline-level config
  api/v2alpha1/go/pipelinespec/pipeline_spec.pb.go
  api/v2alpha1/pipeline_spec.proto
Labels: lgtm, approved, size/XXL, ci-passed

#11326 feat(component): execute in a virtual env
  components/google-cloud/RELEASE.md
  sdk/python/kfp/dsl/component_decorator.py
  sdk/python/kfp/dsl/component_factory.py
  sdk/python/test_data/components/component_with_pip_install_in_venv.py
  sdk/python/test_data/components/component_with_pip_install_in_venv.yaml
Labels: lgtm, approved, size/L, ok-to-test, ci-passed

#11112 feat(sdk): add PipelineConfig to DSL to re-implement pipeline-level config
  sdk/python/kfp/compiler/pipeline_spec_builder.py
  sdk/python/kfp/dsl/__init__.py
  sdk/python/kfp/dsl/component_factory.py
  sdk/python/kfp/dsl/graph_component.py
  sdk/python/kfp/dsl/pipeline_config.py
  sdk/python/kfp/dsl/pipeline_context.py
Labels: lgtm, approved, size/M, ci-passed

#11337 chore: fix release note
  components/google-cloud/RELEASE.md
  sdk/RELEASE.md
Labels: lgtm, approved, size/XS, ci-passed

#11342 chore(backend): typo in max concurrency error text
  backend/src/apiserver/server/api_converter.go
  backend/src/apiserver/server/job_server_test.go
Labels: lgtm, approved, size/XS, needs-ok-to-test

#11196 feat(backend): implement subdag output resolution
  backend/src/v2/component/launcher_v2.go
  backend/src/v2/driver/driver.go
  backend/src/v2/metadata/client.go
  backend/src/v2/metadata/client_fake.go
  backend/src/v2/metadata/client_test.go
  backend/src/v2/objectstore/object_store.go
  samples/v2/sample_test.py
  samples/v2/subdagio/__init__.py
  samples/v2/subdagio/artifact.py
  samples/v2/subdagio/artifact_cache.py
  samples/v2/subdagio/mixed_parameters.py
  samples/v2/subdagio/multiple_artifacts_namedtuple.py
  samples/v2/subdagio/multiple_parameters_namedtuple.py
  samples/v2/subdagio/parameter.py
  samples/v2/subdagio/parameter_cache.py
  samples/v2/subdagio/parameter_oneof.py
  sdk/python/kfp/compiler/pipeline_spec_builder.py
Labels: lgtm, approved, size/XXL
