Repository kubeflow/pipelines, pull requests merged in 2024-09, with the labels that each got.

#11162 test: Improvements to wait_for_pods function
  .github/workflows/backend.yml
  .github/workflows/e2e-test.yml
  .github/workflows/kfp-kubernetes-execution-tests.yml
  .github/workflows/kfp-samples.yml
  .github/workflows/kubeflow-pipelines-integration-v2.yml
  .github/workflows/periodic.yml
  .github/workflows/sdk-execution.yml
  .github/workflows/upgrade-test.yml
  scripts/deploy/github/deploy-kfp-tekton.sh
  scripts/deploy/github/deploy-kfp.sh
  scripts/deploy/github/helper-functions.sh
  scripts/deploy/github/kfp-readiness/wait_for_pods.py
Labels: lgtm, approved, size/L

#11096 fix(frontend): fixes filter pipeline text box shows error when typing anything in it. Fixes #10241
  frontend/src/pages/ResourceSelector.tsx
  frontend/src/pages/__snapshots__/ResourceSelector.test.tsx.snap
Labels: lgtm, approved, size/XS, ok-to-test

#11059 correct artifact preview behavior in UI
  frontend/server/app.ts
  frontend/server/configs.ts
  frontend/server/handlers/artifacts.ts
  frontend/server/integration-tests/artifact-get.test.ts
  frontend/server/minio-helper.ts
  manifests/kustomize/base/pipeline/ml-pipeline-ui-deployment.yaml
Labels: lgtm, approved, size/L

#11176 chore: Added DCO link to PR template
  .github/pull_request_template.md
Labels: lgtm, approved, size/XS

#11177 chore(backend): Update driver and launcher licenses
  backend/third_party_licenses/driver.csv
  backend/third_party_licenses/launcher.csv
Labels: lgtm, approved, size/L

#11178 chore(backend): update driver and launcher default images
  backend/src/v2/compiler/argocompiler/container.go
Labels: lgtm, approved, size/XS

#11179 chore: Add instructions for releasing driver and launcher images
  RELEASE.md
Labels: lgtm, approved, size/S

#11158 test: Fixed `kfp-runtime-tests` to run on master branch
  sdk/runtime_tests/execute_commands_args_test.py
Labels: lgtm, approved, size/S

#11169 (fix): reduce executor logs
  backend/src/v2/component/launcher_v2.go
  backend/src/v2/driver/driver.go
Labels: lgtm, approved, size/XS

#11180 chore: add PaulinaPacyna and ouadakarim as reviewers
  OWNERS
Labels: lgtm, approved, size/XS

#11157 test: Move run-all-gcpc-modules to GitHub Actions
  .github/workflows/gcpc-modules-tests.yml
  test/presubmit-test-run-all-gcpc-modules.sh
Labels: lgtm, approved, size/M, ok-to-test

#11151 fix(sdk): Kfp support for pip trusted host
  sdk/python/kfp/cli/component.py
  sdk/python/kfp/cli/component_test.py
  sdk/python/kfp/dsl/component_decorator.py
  sdk/python/kfp/dsl/component_factory.py
  sdk/python/kfp/dsl/component_factory_test.py
Labels: lgtm, approved, size/L

#11079 chore(sdk): Loosening kubernetes dependency constraint
  sdk/python/requirements.in
  sdk/python/requirements.txt
  test/presubmit-test-kfp-kubernetes-library.sh
Labels: lgtm, approved, size/M, ok-to-test

#10973 chore: Remove unwanted Frontend test files
  frontend/package.json
  frontend/scripts/get-coveralls-repo-token.js
  frontend/scripts/report-coveralls.sh
Labels: lgtm, approved, size/M, Stale

#11175 fix(ui): fixes empty string value in pipeline parameters
  frontend/src/components/NewRunParametersV2.tsx
Labels: lgtm, approved, size/XS, ok-to-test

#11182 chore(backend): update driver and launcher default images
  backend/src/v2/compiler/argocompiler/container.go
Labels: lgtm, approved, size/XS

#11183 chore: Update RELEASE.md to remove obsolete instructions
  RELEASE.md
Labels: lgtm, approved, size/XS

#11189 chore: Release kfp-pipeline-spec 0.4.0
  api/v2alpha1/python/setup.py
Labels: lgtm, approved, size/XS

#11190 chore: release kfp-kubernetes 1.3.0
  kubernetes_platform/python/docs/conf.py
  kubernetes_platform/python/kfp/kubernetes/__init__.py
Labels: lgtm, approved, size/S

#11191 chore: update kfp-kubernetes release scripts and instructions
  kubernetes_platform/python/RELEASE.md
  kubernetes_platform/python/create_release_branch.sh
  kubernetes_platform/python/release.sh
Labels: lgtm, approved, size/S

#11192 feat(sdk)!: Pin kfp-pipeline-spec==0.4.0, kfp-server-api>=2.1.0,<2.4.0
  sdk/python/kfp/client/client.py
  sdk/python/kfp/client/client_test.py
  sdk/python/requirements.in
  sdk/python/requirements.txt
Labels: lgtm, approved, size/L

#11193 chore(sdk): release KFP SDK 2.9.0
  docs/versions.json
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
Labels: lgtm, approved, size/S

#11152 replaced deprecated image repos with registry.k8s.io
  backend/src/apiserver/config/config.json
  backend/src/cache/server/mutation.go
  backend/src/cache/server/mutation_test.go
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/cache.yaml
  manifests/kustomize/base/installs/generic/pipeline-install-config.yaml
  manifests/kustomize/base/installs/generic/postgres/pipeline-install-config.yaml
  samples/core/resource_ops/resource_ops.py
  samples/test/placeholder_concat.py
  samples/test/placeholder_if.py
  samples/test/placeholder_if_v2.py
Labels: lgtm, approved, size/S

#11207 chore(docs): clean up kfp-kubernetes documentation index page
  kubernetes_platform/python/README.md
  kubernetes_platform/python/docs/conf.py
Labels: lgtm, approved, size/M

#11215 chore: move release instruction screenshots out of root directory
  RELEASE.md
  images/release-status-check.png
  images/retry-release-on-tag.png
  images/verify-retry-the-right-build.png
Labels: lgtm, approved, size/XS

#11214 fix(ui): Fixes V1 Run detail unnecessary reloading. Fixes #10590
  frontend/src/pages/RunDetails.tsx
  frontend/src/pages/RunDetailsRouter.tsx
Labels: lgtm, approved, size/S, ok-to-test

#11130 fix(frontend): first time choosing a pipeline definition is VERY slow. Fixes #10897
  frontend/src/pages/NewRunSwitcher.tsx
Labels: lgtm, approved, size/XS, ok-to-test

#11216 chore: clean up obsolete requirements.txt under root directory
  requirements.txt
Labels: lgtm, approved, size/L

#11221 chore: fix CI by adding a dependency of python/sdk for the e2e-test
  sdk/python/test_data/pipelines/xgboost_sample_pipeline.py
  sdk/python/test_data/pipelines/xgboost_sample_pipeline.yaml
Labels: lgtm, approved, size/XXL

#11147 refactor: fix invalid escape sequences
  .pre-commit-config.yaml
  backend/src/apiserver/visualization/types/tfdv.py
  components/aws/athena/query/src/query.py
  components/google-cloud/google_cloud_pipeline_components/container/v1/aiplatform/remote_runner.py
  components/google-cloud/google_cloud_pipeline_components/v1/hyperparameter_tuning_job/component.py
  proxy/get_proxy_url.py
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/deprecated/compiler/v2_compatible_compiler_test.py
  sdk/python/kfp/deprecated/components/type_annotation_utils.py
  sdk/python/kfp/deprecated/components_tests/test_python_op.py
  sdk/python/kfp/deprecated/dsl/_ops_group.py
  sdk/python/kfp/dsl/executor.py
  sdk/python/kfp/dsl/for_loop.py
  sdk/python/kfp/dsl/placeholders_test.py
  sdk/python/kfp/dsl/tasks_group_test.py
  sdk/python/kfp/dsl/types/type_annotations.py
  sdk/python/kfp/local/config_test.py
  test/sample-test/sample_test_launcher.py
  test/sample-test/unittests/utils_tests.py
Labels: lgtm, approved, size/M, ok-to-test

#11097 feat(sdk): support dynamic machine type parameters in pipeline task setters
  sdk/RELEASE.md
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/compiler/pipeline_spec_builder.py
  sdk/python/kfp/dsl/pipeline_task.py
  sdk/python/kfp/dsl/pipeline_task_test.py
  sdk/python/kfp/dsl/structures.py
  sdk/python/test_data/pipelines/pipeline_with_resource_spec.yaml
  sdk/python/test_data/pipelines/pipeline_with_string_machine_fields_pipeline_input.py
  sdk/python/test_data/pipelines/pipeline_with_string_machine_fields_pipeline_input.yaml
  sdk/python/test_data/pipelines/pipeline_with_string_machine_fields_task_output.py
  sdk/python/test_data/pipelines/pipeline_with_string_machine_fields_task_output.yaml
Labels: lgtm, approved, size/XL

#11231 fix(backend): upgrade PyYMAL to fix metadata_writer build error
  backend/metadata_writer/requirements.in
  backend/metadata_writer/requirements.txt
Labels: lgtm, approved, size/M

#11242 chore: Remove PaulinaPacyna from reviewers
  OWNERS
Labels: lgtm, approved, size/XS

#11244 test: Fixed kubeflow-pipelines-integration-v2 workflow
  .github/workflows/kubeflow-pipelines-integration-v2.yml
Labels: lgtm, approved, size/XS

#11222 feat(sdk): Allow disabling default caching via a CLI flag and env var
  sdk/python/kfp/cli/cli_test.py
  sdk/python/kfp/cli/compile_.py
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/dsl/base_component.py
  sdk/python/kfp/dsl/pipeline_context.py
  sdk/python/kfp/dsl/pipeline_task.py
Labels: lgtm, approved, size/L

#11163 feat(frontend/backend): Allow the ability to sort experiments by last run creation. Fixes #10884
  backend/api/v2beta1/experiment.proto
  backend/api/v2beta1/go_client/experiment.pb.go
  backend/api/v2beta1/go_http_client/experiment_model/v2beta1_experiment.go
  backend/api/v2beta1/swagger/experiment.swagger.json
  backend/api/v2beta1/swagger/kfp_api_single_file.swagger.json
  backend/src/apiserver/model/experiment.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/server/api_converter.go
  backend/src/apiserver/server/api_converter_test.go
  backend/src/apiserver/server/experiment_server_test.go
  backend/src/apiserver/storage/experiment_store.go
  backend/src/apiserver/storage/experiment_store_test.go
  frontend/src/lib/Apis.ts
  frontend/src/pages/ExperimentList.tsx
  frontend/src/pages/__snapshots__/ExperimentList.test.tsx.snap
Labels: lgtm, approved, size/XL, ok-to-test

#11253 chore: adding HumairAK to root OWNERS
  OWNERS
Labels: lgtm, approved, size/XS

#11246 feat(backend): add configurable S3 path style support
  backend/src/v2/config/env_test.go
  backend/src/v2/config/s3.go
  backend/src/v2/config/testdata/provider_cases.yaml
  backend/src/v2/objectstore/config.go
  backend/src/v2/objectstore/object_store.go
  backend/src/v2/objectstore/object_store_test.go
Labels: lgtm, approved, size/L, ok-to-test

#11256 chore: adding @hbelmiro to backend reviewers
  backend/OWNERS
Labels: lgtm, approved, size/XS

#11257 chore: pinned estroz/rerun-actions version
  .github/workflows/rerun-pr-jobs.yml
Labels: lgtm, approved, size/XS
