Repository kubeflow/pipelines, pull requests merged in 2024-12, with the labels that each got.

#11424 fix(backend): return error properly
  backend/src/v2/driver/driver.go
Labels: lgtm, approved, size/XS, ok-to-test

#11349 feat(component): Created Snowflake data unload component
  components/snowflake/component.yaml
  components/snowflake/snowflake_unload_data.py
Labels: lgtm, approved, needs-ok-to-test, size/L

#11356 fix(sdk): Add error handling. Fixes #11164
  sdk/RELEASE.md
  sdk/python/kfp/cli/component.py
  sdk/python/kfp/cli/component_test.py
Labels: lgtm, approved, size/M, ok-to-test, ci-passed

#11425 fix(backend): remove unused function argument
  backend/src/v2/driver/driver.go
Labels: lgtm, approved, size/XS, ok-to-test

#11427 chore: Fix pr-commands.yml to enable /ok-to-test alongside other commands
  .github/workflows/pr-commands.yml
Labels: lgtm, approved, size/XS

#11392 fix(sdk): Backport fixes in kubeflow/pipelines#11075
  sdk/RELEASE.md
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/compiler/compiler_utils.py
  sdk/python/kfp/compiler/pipeline_spec_builder.py
  sdk/python/test_data/pipelines/pipeline_with_resource_spec.yaml
Labels: lgtm, approved, size/L, ci-passed

#10798 feat(backend): Add Parallelism Limit to ParallelFor tasks. Fixes #8718
  backend/src/v2/compiler/argocompiler/argo_test.go
  backend/src/v2/compiler/argocompiler/dag.go
  backend/src/v2/compiler/argocompiler/testdata/multiple_parallel_loops.yaml
  backend/src/v2/compiler/testdata/multiple_parallel_loops.json
Labels: lgtm, approved, size/XL, ok-to-test, ci-passed

#11404 feat(sdk/backend): enable parameterization of container images
  backend/src/v2/driver/driver.go
  backend/src/v2/driver/util.go
  backend/src/v2/driver/util_test.go
  sdk/RELEASE.md
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/compiler/pipeline_spec_builder.py
  sdk/python/kfp/dsl/pipeline_task.py
Labels: lgtm, approved, size/L, ci-passed

#11434 feat: Introduce cache_key for cache key customization
  api/v2alpha1/pipeline_spec.proto
  api/v2alpha1/python/setup.py
Labels: lgtm, approved, size/XS

#11437 chore: add adr template/docs
  CONTRIBUTING.md
  adrs/KFP-ADR-0001-use-architecture-decision-records-for-kfp.md
  adrs/OWNERS
  adrs/README.md
  adrs/template.md
Labels: lgtm, approved, size/L

#11443 fix(backend): Allow initializing the Kubernetes client with a kubeconfig
  backend/src/apiserver/client/argo.go
  backend/src/apiserver/client/swf.go
  backend/src/apiserver/client/util.go
  backend/src/cache/client/kubernetes_core.go
  backend/src/common/util/execution_client.go
  backend/src/common/util/service.go
  backend/src/v2/driver/driver.go
Labels: lgtm, approved, size/M, ok-to-test

#11447 chore(sdk): Upgrade kfp-pipeline-spec to 0.6.0 (#11434)
  sdk/python/requirements.in
  sdk/python/requirements.txt
Labels: lgtm, approved, size/XS

#11451 chore(sdk): release kfp sdk 2.11.0
  docs/versions.json
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
Labels: lgtm, approved, size/S

#11450 chore: Added Kubernetes 1.30 and 1.31 to e2e tests
  .github/actions/kfp-cluster/action.yml
  .github/workflows/e2e-test.yml
Labels: lgtm, approved, size/M

#11459 chore: Add instructions to develop the API server locally with kind
  .github/workflows/kfp-samples.yml
  .github/workflows/upgrade-test.yml
  .gitignore
  backend/Makefile
  backend/README.md
  manifests/kustomize/env/dev-kind/forward-local-api-endpoint.yaml
  manifests/kustomize/env/dev-kind/kustomization.yaml
  tools/kind/kind-config.yaml
Labels: lgtm, approved, size/L, ok-to-test

#11463 chore: Added Kubernetes 1.30 and 1.31 to other tests
  .github/workflows/kfp-kubernetes-execution-tests.yml
  .github/workflows/periodic.yml
  .github/workflows/sdk-execution.yml
Labels: lgtm, approved, size/S

#11445 chore: Update test READMEs to reflect correct information on testing workflows
  samples/test/README.md
  sdk/python/test_data/README.md
  test/README.md
  test/kfp-functional-test/README.md
Labels: lgtm, approved, size/L

#11474 chore: Update image for metacontroller
  manifests/kustomize/third-party/metacontroller/base/stateful-set.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#11475 fix(backend): modelToCRDTrigger was not including periodic schedule correctly
  backend/src/apiserver/model/cron_schedule.go
  backend/src/apiserver/model/job.go
  backend/src/apiserver/model/periodic_schedule.go
  backend/src/apiserver/template/template.go
Labels: lgtm, approved, size/L

#11448 fix(backend): upgrade various old dependencies
  backend/src/agent/persistence/worker/persistence_worker.go
  backend/src/agent/persistence/worker/persistence_worker_test.go
  backend/src/apiserver/storage/job_store_test.go
  backend/src/common/util/execution_client.go
  backend/src/common/util/pipelinerun.go
  backend/src/common/util/scheduled_workflow_test.go
  backend/src/common/util/workflow.go
  backend/src/crd/controller/scheduledworkflow/util/scheduled_workflow.go
  backend/src/crd/controller/scheduledworkflow/util/scheduled_workflow_test.go
  backend/src/crd/controller/viewer/main.go
  backend/src/crd/pkg/apis/scheduledworkflow/v1beta1/types.go
  backend/src/v2/driver/driver.go
  backend/src/v2/driver/driver_test.go
  backend/src/v2/expression/expression.go
  backend/third_party_licenses/apiserver.csv
  backend/third_party_licenses/cache_server.csv
  backend/third_party_licenses/driver.csv
  backend/third_party_licenses/launcher.csv
  backend/third_party_licenses/persistence_agent.csv
  backend/third_party_licenses/swf.csv
  backend/third_party_licenses/viewer.csv
  go.mod
  go.sum
Labels: lgtm, approved, size/XXL

#11462 chore: Add securitycontext for PSS PoC (rootless Kubeflow)
  manifests/kustomize/base/cache/cache-deployment.yaml
  manifests/kustomize/base/metadata/base/metadata-envoy-deployment.yaml
  manifests/kustomize/base/metadata/base/metadata-grpc-deployment.yaml
  manifests/kustomize/base/pipeline/metadata-writer/metadata-writer-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-scheduledworkflow-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-ui-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-viewer-crd-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-visualization-deployment.yaml
  manifests/kustomize/third-party/argo/base/workflow-controller-deployment-patch.yaml
  manifests/kustomize/third-party/metacontroller/base/stateful-set.yaml
  manifests/kustomize/third-party/minio/base/minio-deployment.yaml
  manifests/kustomize/third-party/mysql/base/mysql-deployment.yaml
Labels: lgtm, approved, size/L, ok-to-test

#11482 chore(deps): bump golang.org/x/crypto from 0.22.0 to 0.31.0
  backend/third_party_licenses/apiserver.csv
  backend/third_party_licenses/cache_server.csv
  backend/third_party_licenses/driver.csv
  backend/third_party_licenses/launcher.csv
  backend/third_party_licenses/persistence_agent.csv
  backend/third_party_licenses/swf.csv
  backend/third_party_licenses/viewer.csv
  go.mod
  go.sum
Labels: lgtm, approved, size/L

#11488 test: fixes SDK tests
  .github/workflows/kfp-sdk-tests.yml
  test/presubmit-tests-sdk.sh
Labels: lgtm, approved, size/XS

#11491 chore(tests): fixed conflicting artifacts names
  .github/workflows/periodic.yml
Labels: lgtm, approved, size/XS
