Repository kubeflow/pipelines, pull requests merged in 2024-08, with the labels that each got.

#11062 fix: Incorrect typing in samples/cores/loop_parallism and fixing loop_parameter examples
  samples/core/loop_parallelism/loop_parallelism.py
  samples/core/loop_parameter/loop_parameter.py
Labels: lgtm, approved, size/XS, ok-to-test

#11072 chore: Fixed e2e tests
  .github/workflows/e2e-test.yaml
Labels: lgtm, approved, size/M

#11075 feat(api): Add new ResourceSpec proto fields to support dynamic values.
  api/v2alpha1/pipeline_spec.proto
Labels: lgtm, approved, size/M

#11013 docs: Fix environment variables names
  kubernetes_platform/python/README.md
Labels: lgtm, approved, size/XS

#10979 feat(backend): move comp logic to workflow params
  backend/src/v2/compiler/argocompiler/argo.go
  backend/src/v2/compiler/argocompiler/container.go
  backend/src/v2/compiler/argocompiler/testdata/create_mount_delete_dynamic_pvc.yaml
  backend/src/v2/compiler/argocompiler/testdata/create_pod_metadata.yaml
  backend/src/v2/compiler/argocompiler/testdata/hello_world.yaml
  backend/src/v2/compiler/argocompiler/testdata/importer.yaml
Labels: lgtm, approved, size/L, ok-to-test

#10978 chore: Upgrade Argo to v3.4.17 (fixes #10977)
  .cloudbuild.yaml
  .release.cloudbuild.yaml
  backend/Dockerfile
  backend/src/common/types.go
  backend/third_party_licenses/apiserver.csv
  backend/third_party_licenses/cache_server.csv
  backend/third_party_licenses/driver.csv
  backend/third_party_licenses/launcher.csv
  backend/third_party_licenses/persistence_agent.csv
  backend/third_party_licenses/swf.csv
  backend/third_party_licenses/viewer.csv
  go.mod
  go.sum
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/argo.yaml
  manifests/kustomize/third-party/argo/base/workflow-controller-configmap-patch.yaml
  manifests/kustomize/third-party/argo/base/workflow-controller-deployment-patch.yaml
  manifests/kustomize/third-party/argo/upstream/manifests/Kptfile
  manifests/kustomize/third-party/argo/upstream/manifests/namespace-install/kustomization.yaml
  manifests/kustomize/third-party/argo/upstream/manifests/quick-start/base/kustomization.yaml
  manifests/kustomize/third-party/argo/upstream/manifests/quick-start/minimal/kustomization.yaml
  manifests/kustomize/third-party/argo/upstream/manifests/quick-start/mysql/kustomization.yaml
  manifests/kustomize/third-party/argo/upstream/manifests/quick-start/postgres/kustomization.yaml
  manifests/kustomize/third-party/argo/upstream/manifests/quick-start/sso/kustomization.yaml
  test/install-argo-cli.sh
  test/tag_for_hosted.sh
  third_party/argo/Dockerfile.argoexec
  third_party/argo/Dockerfile.workflow-controller
  third_party/argo/README.md
  third_party/argo/VERSION
  third_party/argo/licenses-argoexec.csv
  third_party/argo/licenses-workflow-controller.csv
Labels: lgtm, approved, size/XL

#11066 test: Moved kubeflow-pipelines-manifests to GitHub Actions
  .github/workflows/kubeflow-pipelines-manifests.yml
  manifests/kustomize/hack/presubmit.sh
Labels: lgtm, approved, size/M, ok-to-test

#11100 fix: re-enable exit hanler test.
  .github/workflows/e2e-test.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#11010 fix(frontend): retrieve archived logs from correct location
  frontend/server/configs.ts
  frontend/server/handlers/pod-logs.ts
  frontend/server/workflow-helper.test.ts
  frontend/server/workflow-helper.ts
  frontend/src/components/tabs/RuntimeNodeDetailsV2.tsx
  frontend/src/lib/Apis.test.ts
  frontend/src/lib/Apis.ts
  frontend/src/pages/RunDetails.test.tsx
  frontend/src/pages/RunDetails.tsx
Labels: lgtm, approved, size/L

#11115 test: Fail fast when image build fails on tests #11102
  scripts/deploy/github/build-images.sh
Labels: lgtm, approved, size/S, ok-to-test

#11067 Fix view edit cluster roles
  manifests/kustomize/base/installs/multi-user/view-edit-cluster-roles.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#11131 chore: Adding @DharmitD to SDK reviewers
  kubernetes_platform/OWNERS
  sdk/OWNERS
Labels: lgtm, approved, size/XS

#11125 test: Kubeflow Pipelines V2 integration Tests
  .github/workflows/kubeflow-pipelines-integration-v2.yml
  backend/src/v2/test/Makefile
  backend/src/v2/test/requirements.txt
  backend/src/v2/test/scripts/upload_gcs_blob.py
Labels: lgtm, approved, size/M

#11103 chore: Add make targets for building driver and launcher images
  backend/Makefile
Labels: lgtm, approved, size/S

#10913 feat(Backend + SDK): Update kfp backend and kubernetes sdk to support EmptyDir
  backend/src/v2/driver/driver.go
  backend/src/v2/driver/driver_test.go
  backend/third_party_licenses/apiserver.csv
  backend/third_party_licenses/driver.csv
  go.mod
  go.sum
  kubernetes_platform/python/kfp/kubernetes/__init__.py
  kubernetes_platform/python/kfp/kubernetes/empty_dir.py
  kubernetes_platform/python/test/snapshot/data/empty_dir_mounts.py
  kubernetes_platform/python/test/snapshot/data/empty_dir_mounts.yaml
  kubernetes_platform/python/test/unit/test_empty_dir_mounts.py
Labels: lgtm, approved, size/L, ok-to-test

#11108 docs:fixing broken links in readme
  README.md
Labels: lgtm, approved, size/S, ok-to-test

#11138 Fix: Basic sample tests - sequential is flaky
  .github/workflows/e2e-test.yml
  scripts/deploy/github/build-images.sh
  scripts/deploy/github/forward-port.sh
  test/sample-test/requirements.in
  test/sample-test/requirements.txt
  test/sample-test/run_sample_test.py
  test/sample-test/sample_test_launcher.py
Labels: lgtm, approved, size/L

#11098 chore: Wrapped "Failed GetContextByTypeAndName" error for better troubleshooting
  backend/src/v2/metadata/client.go
Labels: lgtm, approved, size/XS
