Repository kubeflow/pipelines, pull requests merged in 2024-02, with the labels that each got.

#10440 feat(sdk): support local execution of pipelines in pipelines
  sdk/RELEASE.md
  sdk/python/kfp/local/dag_orchestrator.py
  sdk/python/kfp/local/pipeline_orchestrator.py
  sdk/python/kfp/local/pipeline_orchestrator_test.py
Labels: lgtm, approved, size/L

#10430 fix(backend): correct run field map col names
  backend/src/apiserver/model/run.go
  backend/src/apiserver/model/task.go
  backend/src/apiserver/storage/default_experiment_store_test.go
  backend/src/apiserver/storage/job_store_test.go
  backend/src/apiserver/storage/run_store_test.go
  backend/src/apiserver/storage/task_store_test.go
Labels: lgtm, approved, size/M, ok-to-test

#10441 feat(sdk): Support dsl.ParallelFor over list of Artifacts
  sdk/RELEASE.md
  sdk/python/kfp/compiler/compiler_utils.py
  sdk/python/kfp/compiler/pipeline_spec_builder.py
  sdk/python/kfp/dsl/for_loop.py
  sdk/python/kfp/dsl/for_loop_test.py
  sdk/python/kfp/dsl/pipeline_channel.py
  sdk/python/kfp/dsl/tasks_group.py
  sdk/python/kfp/dsl/tasks_group_test.py
  sdk/python/test_data/pipelines/pipeline_with_parallelfor_list_artifacts.py
  sdk/python/test_data/pipelines/pipeline_with_parallelfor_list_artifacts.yaml
  sdk/python/test_data/test_data_config.yaml
Labels: lgtm, approved, size/XL

#10410 feat(kubernetes_platform): Update kubernetes_platform go package to include ImagePullSecrets
  kubernetes_platform/go/kubernetesplatform/kubernetes_executor_config.pb.go
  kubernetes_platform/proto/kubernetes_executor_config.proto
Labels: lgtm, approved, size/L, ok-to-test

#10416 feat(kubernetes_platform): Update kubernetes_platform go package to include imagePullPolicy.
  kubernetes_platform/go/kubernetesplatform/kubernetes_executor_config.pb.go
  kubernetes_platform/proto/kubernetes_executor_config.proto
Labels: lgtm, approved, size/L, ok-to-test

#10436 fix(sdk): fixes type issues for ParallelFor. Fixes #9366
  sdk/RELEASE.md
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/dsl/for_loop.py
  sdk/python/kfp/dsl/for_loop_test.py
  sdk/python/kfp/dsl/types/type_utils.py
  sdk/python/kfp/dsl/types/type_utils_test.py
  sdk/python/test_data/pipelines/pipeline_with_parallelfor_parallelism.py
  sdk/python/test_data/pipelines/pipeline_with_parallelfor_parallelism.yaml
Labels: lgtm, approved, size/XL

#10452 fix(sdk): fix bug where `dsl.OneOf` with multiple consumers cannot be compiled
  sdk/RELEASE.md
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/compiler/compiler_utils.py
Labels: lgtm, approved, size/M

#10427 feat(Backend + SDK): Update kfp backend and kubernetes sdk to support ImagePullSecrets
  backend/src/v2/driver/driver.go
  backend/src/v2/driver/driver_test.go
  backend/third_party_licenses/driver.csv
  go.mod
  go.sum
  kubernetes_platform/python/kfp/kubernetes/__init__.py
  kubernetes_platform/python/kfp/kubernetes/image.py
  kubernetes_platform/python/test/snapshot/data/image_pull_secrets.py
  kubernetes_platform/python/test/snapshot/data/image_pull_secrets.yaml
  kubernetes_platform/python/test/unit/test_image_pull_secrets.py
Labels: lgtm, approved, size/L, ok-to-test

#10439 Fix(backend): fix timeout for internal server error. Fixes #10267
  backend/src/apiserver/resource/resource_manager.go
Labels: lgtm, approved, size/XS, ok-to-test

#10268 fix(backend): get pipeline by name is broken due to version typo, Fixes #9940
  backend/src/apiserver/server/pipeline_server.go
Labels: lgtm, approved, size/XS, ok-to-test

#10400 feat(kubernetes_platform): Update kubernetes_platform go package to include ConfigMaps as volumes and as env variables.
  kubernetes_platform/go/kubernetesplatform/kubernetes_executor_config.pb.go
  kubernetes_platform/proto/kubernetes_executor_config.proto
Labels: lgtm, approved, size/XL, ok-to-test

#10393 feat(Backend + SDK): Update kfp backend and kubernetes sdk to support pod labels and annotations
  backend/src/v2/compiler/argocompiler/argo_test.go
  backend/src/v2/compiler/argocompiler/container.go
  backend/src/v2/compiler/argocompiler/container_test.go
  backend/src/v2/compiler/argocompiler/dag.go
  backend/src/v2/compiler/argocompiler/testdata/create_pod_metadata.yaml
  backend/src/v2/compiler/testdata/create_pod_metadata.json
  backend/third_party_licenses/apiserver.csv
  kubernetes_platform/python/README.md
  kubernetes_platform/python/kfp/kubernetes/__init__.py
  kubernetes_platform/python/kfp/kubernetes/pod_metadata.py
  kubernetes_platform/python/test/unit/test_pod_metadata.py
Labels: lgtm, approved, size/XL

#10464 feat(kubernetes_platform): Add ActiveDeadlineSeconds(timeout) to the kubernetes platform spec
  kubernetes_platform/go/kubernetesplatform/kubernetes_executor_config.pb.go
  kubernetes_platform/proto/kubernetes_executor_config.proto
Labels: lgtm, approved, size/L

#10225 test(components): Reduce sagemaker component test flakiness
  components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests
Labels: lgtm, approved, size/S

#10461 chore(sdk): release KFP SDK 2.7.0
  docs/conf.py
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
Labels: lgtm, size/S

#10485 feat(kubernetes_platform): Add k8s FieldPath as env to the kubernetes_platform
  kubernetes_platform/go/kubernetesplatform/kubernetes_executor_config.pb.go
  kubernetes_platform/proto/kubernetes_executor_config.proto
Labels: lgtm, approved, size/L

#10490 chore: Add Tomcli as a backend approver
  backend/OWNERS
Labels: lgtm, approved, size/XS

#10482 chore(README): Update Kubeflow Pipelines on Tekton blog
  README.md
Labels: lgtm, approved, size/XS

#10459 fix(backend): fixes "cannot save parameter" error message. Fixes #9678
  backend/src/v2/cmd/driver/execution_paths.go
  backend/src/v2/cmd/driver/main.go
  backend/src/v2/cmd/driver/main_test.go
Labels: lgtm, approved, size/L, ok-to-test

#10471 feat(Backend + SDK): Update kfp backend and kubernetes sdk to support tolerations
  backend/src/v2/driver/driver.go
  backend/src/v2/driver/driver_test.go
  backend/third_party_licenses/apiserver.csv
  backend/third_party_licenses/driver.csv
  go.mod
  go.sum
  kubernetes_platform/python/kfp/kubernetes/__init__.py
  kubernetes_platform/python/kfp/kubernetes/toleration.py
  kubernetes_platform/python/test/snapshot/data/toleration.py
  kubernetes_platform/python/test/snapshot/data/toleration.yaml
  kubernetes_platform/python/test/unit/test_tolerations.py
Labels: lgtm, approved, size/L, ok-to-test

#10494 fix(sdk): Prevents dsl.ParallelFor over single parameter from compiling.
  sdk/RELEASE.md
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/dsl/for_loop.py
  sdk/python/kfp/dsl/for_loop_test.py
  sdk/python/kfp/dsl/types/type_utils_test.py
Labels: lgtm, approved, size/M

#10531 test: Add ParallelFor compile test over single artifact.
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/dsl/for_loop.py
  sdk/python/kfp/dsl/for_loop_test.py
Labels: lgtm, approved, size/S
