Repository kubeflow/pipelines, pull requests merged in 2025-05, with the labels that each got.

#11888 feat(backend): Allow the launcher command to be configurable
  backend/src/v2/compiler/argocompiler/argo.go
  backend/src/v2/compiler/argocompiler/container.go
  backend/src/v2/compiler/argocompiler/importer.go
Labels: lgtm, approved, size/M

#11725 feat(backend/sdk): enable dsl.Collected for parameters & artifacts
  backend/src/v2/component/launcher_v2.go
  backend/src/v2/driver/driver.go
  backend/src/v2/metadata/client.go
  samples/v2/collected_artifacts.py
  samples/v2/collected_parameters.py
  samples/v2/sample_test.py
  sdk/python/kfp/dsl/executor.py
Labels: lgtm, approved, size/XL

#11891 fix(sdk): fix pip install for dev
  sdk/python/requirements-dev.txt
Labels: lgtm, approved, size/XS

#11894 chore: Adding Adopters file for CNCF graduation
  ADOPTERS.md
Labels: lgtm, approved, size/XS

#11898 chore: handle empty tolerations dict/lists parrameterization
  backend/src/v2/driver/driver.go
  backend/src/v2/driver/driver_test.go
Labels: lgtm, approved, size/M

#11831 feat(backend): add the option to enable/disable cache globally
  .github/actions/kfp-cluster/action.yml
  .github/resources/manifests/argo/overlays/cache-disabled/cache-env.yaml
  .github/resources/manifests/argo/overlays/cache-disabled/kustomization.yaml
  .github/resources/scripts/deploy-kfp.sh
  .github/workflows/e2e-test.yml
  backend/src/apiserver/main.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/server/pipeline_upload_server_test.go
  backend/src/apiserver/template/argo_template.go
  backend/src/apiserver/template/template.go
  backend/src/apiserver/template/template_test.go
  backend/src/apiserver/template/v2_template.go
  backend/src/apiserver/webhook/pipelineversion_webhook.go
  backend/src/common/client/api_server/v1/pipeline_client.go
  backend/src/v2/cacheutils/cache.go
  backend/src/v2/cacheutils/cache_test.go
  backend/src/v2/cmd/compiler/main.go
  backend/src/v2/cmd/driver/main.go
  backend/src/v2/cmd/launcher-v2/main.go
  backend/src/v2/compiler/argocompiler/argo.go
  backend/src/v2/compiler/argocompiler/argo_test.go
  backend/src/v2/compiler/argocompiler/container.go
  backend/src/v2/compiler/argocompiler/dag.go
  backend/src/v2/compiler/argocompiler/importer.go
  backend/src/v2/compiler/argocompiler/testdata/hello_world_cache_disabled.yaml
  backend/src/v2/component/launcher_v2.go
  backend/src/v2/driver/driver.go
  backend/src/v2/driver/driver_test.go
  backend/src/v2/metadata/client_test.go
  backend/src/v2/metadata/testutils/test_utils.go
  backend/test/integration/pipeline_api_test.go
  backend/test/integration/pipeline_version_api_test.go
  backend/test/integration/upgrade_test.go
  backend/test/v2/integration/cache_test.go
  backend/test/v2/integration/flags.go
  kubernetes_platform/python/test/snapshot/data/create_mount_delete_existing_pvc.py
  kubernetes_platform/python/test/snapshot/data/create_mount_delete_existing_pvc.yaml
  kubernetes_platform/python/test/snapshot/data/create_mount_delete_existing_pvc_from_task_output.py
  kubernetes_platform/python/test/snapshot/data/create_mount_delete_existing_pvc_from_task_output.yaml
Labels: lgtm, approved, size/XXL

#11755 feat(frontend): Add "Always Use Latest Version" option for recurring runs (fixes #11581)
  frontend/src/pages/NewRunV2.test.tsx
  frontend/src/pages/NewRunV2.tsx
Labels: lgtm, approved, size/L, ok-to-test

#11900 add maintainer to kfp
  OWNERS
Labels: lgtm, approved, size/XS

#11896 chore: correct broken links in README.md
  README.md
Labels: lgtm, approved, size/XS, ok-to-test

#11903 fix(sdk): Resolves issue when using ParallelFor with param and depending tasks
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/compiler/compiler_utils.py
Labels: lgtm, approved, size/S, ok-to-test

#11884 feat(backend): Add migration script to create Pipeline and PipelineVersion objects from the database to Kubernetes API
  tools/k8s-native/README.md
  tools/k8s-native/migration.py
Labels: lgtm, approved, size/L

#11905 chore: Add IBM Research Foundation Model Data Engineering team
  ADOPTERS.md
Labels: lgtm, approved, size/XS

#11911 chore(tests): fix KFP SDK tests
  test/presubmit-tests-sdk.sh
Labels: lgtm, approved, size/XS

#11907 feat(backend): Add CLI flags to support Kubernetes native API implementation
  backend/src/apiserver/client_manager/client_manager.go
  backend/src/apiserver/common/config.go
  backend/src/apiserver/main.go
Labels: lgtm, approved, size/S

#11916 chore(test): Update cache test timeout and polling intervals
  backend/test/v2/integration/cache_test.go
Labels: lgtm, approved, size/XS

#11875 docs(KEP): Propose a new pipeline run workspace feature
  hack/update-toc.sh
  proposals/11551-kubernetes-native-api/README.md
  proposals/11875-pipeline-workspace/README.md
Labels: lgtm, approved, size/XL

#11917 chore(backend): upgrade mysql to 8.4
  developer_guide.md
  manifests/kustomize/third-party/mysql/base/mysql-deployment.yaml
Labels: lgtm, approved, size/S

#11830 chore: Enable go fmt as a lint check for Go code
  .github/workflows/pre-commit.yml
  .golangci.yaml
  .pre-commit-config.yaml
  backend/Makefile
  backend/src/agent/persistence/client/token_refresher.go
  backend/src/agent/persistence/worker/metrics_reporter_test.go
  backend/src/apiserver/config/config.go
  backend/src/apiserver/config/config_test.go
  backend/src/apiserver/config/proxy/config.go
  backend/src/apiserver/config/proxy/config_test.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/server/experiment_server_test.go
  backend/src/apiserver/server/fakes_test.go
  backend/src/apiserver/server/report_server.go
  backend/src/apiserver/server/run_server_test.go
  backend/src/apiserver/storage/default_experiment_store_test.go
  backend/src/apiserver/storage/job_store_test.go
  backend/src/apiserver/storage/pipeline_store.go
  backend/src/apiserver/template/template_test.go
  backend/src/apiserver/template/v2_template.go
  backend/src/cache/client_manager.go
  backend/src/common/client/api_server/v1/pipeline_client_fake.go
  backend/src/common/client/api_server/v1/pipeline_upload_client_fake.go
  backend/src/common/util/json.go
  backend/src/common/util/scheduled_workflow_test.go
  backend/src/crd/controller/scheduledworkflow/util/scheduled_workflow_test.go
  backend/src/crd/controller/viewer/main.go
  backend/src/crd/controller/viewer/reconciler/reconciler_test.go
  backend/src/crd/kubernetes/v2beta1/pipelineversion_types.go
  backend/src/v2/cacheutils/cache.go
  backend/src/v2/cacheutils/cache_test.go
  backend/src/v2/cmd/compiler/main.go
  backend/src/v2/cmd/driver/main_test.go
  backend/src/v2/cmd/launcher-v2/main.go
  backend/src/v2/compiler/argocompiler/argo.go
  backend/src/v2/compiler/argocompiler/argo_test.go
  backend/src/v2/compiler/argocompiler/dag.go
  backend/src/v2/compiler/argocompiler/importer.go
  backend/src/v2/config/env_test.go
  backend/src/v2/config/gcs.go
  backend/src/v2/config/s3.go
  backend/src/v2/driver/cache.go
  backend/src/v2/driver/container.go
  backend/src/v2/driver/dag.go
  backend/src/v2/driver/driver.go
  backend/src/v2/driver/driver_test.go
  backend/src/v2/driver/k8s.go
  backend/src/v2/driver/k8s_test.go
  backend/src/v2/driver/resolve.go
  backend/src/v2/driver/root_dag.go
  backend/src/v2/driver/util.go
  backend/src/v2/driver/util_test.go
  backend/src/v2/metadata/client_test.go
  backend/src/v2/metadata/testutils/test_utils.go
  backend/src/v2/objectstore/object_store_test.go
  backend/test/v2/integration/cache_test.go
  backend/test/v2/integration/proxy_test.go
  tools/tools.go
Labels: lgtm, approved, size/L, ok-to-test

#11910 chore(test): fixed log collection in tests
  .github/workflows/e2e-test.yml
  .github/workflows/kfp-kubernetes-execution-tests.yml
  .github/workflows/kfp-samples.yml
  .github/workflows/sdk-execution.yml
  .github/workflows/upgrade-test.yml
Labels: lgtm, approved, size/L

#11921 feat(proto): Add WorkspaceConfig and KubernetesWorkspaceConfig message types to pipeline_spec proto
  api/v2alpha1/go/pipelinespec/pipeline_spec.pb.go
  api/v2alpha1/pipeline_spec.proto
Labels: lgtm, approved, size/XL

#11925 - fix(launcher): missing executorInput parameter values caused by {{$}} evaluation order
  backend/src/v2/component/launcher_v2.go
  backend/src/v2/component/launcher_v2_test.go
Labels: lgtm, approved, size/L, ok-to-test

#11926 chore(ci): clean up unnecessary parentheses and fix the formatting of the CI files
  .github/actions/kfp-cluster/action.yml
  .github/workflows/e2e-test.yml
  .github/workflows/kfp-kubernetes-execution-tests.yml
  .github/workflows/kfp-samples.yml
  .github/workflows/kfp-webhooks.yml
  .github/workflows/sdk-execution.yml
  .github/workflows/upgrade-test.yml
Labels: lgtm, approved, size/L, ok-to-test

#11919 docs: add GoLand-specific configs to backend Readme
  backend/README.md
Labels: lgtm, approved, needs-ok-to-test, size/M

#11942 fix(tests): free up space in kfp samples test workflow
  .github/workflows/kfp-samples.yml
Labels: lgtm, approved, size/XS, needs-ok-to-test

#11945 chore: Nest sdk docs
  .readthedocs.yml
  docs/OWNERS
  docs/sdk/Architecture.md
  docs/sdk/Makefile
  docs/sdk/_static/custom.css
  docs/sdk/_static/favicon.ico
  docs/sdk/_static/kubeflow.png
  docs/sdk/build_docs_locally.sh
  docs/sdk/conf.py
  docs/sdk/index.rst
  docs/sdk/make.bat
  docs/sdk/requirements.txt
  docs/sdk/source/cli.rst
  docs/sdk/source/client.rst
  docs/sdk/source/compiler.rst
  docs/sdk/source/components.rst
  docs/sdk/source/dsl.rst
  docs/sdk/source/genai.rst
  docs/sdk/source/installation.rst
  docs/sdk/source/kfp.rst
  docs/sdk/source/local.rst
  docs/sdk/source/overview.rst
  docs/sdk/source/quickstart.rst
  docs/sdk/source/registry.rst
  docs/sdk/versions.json
Labels: lgtm, approved, size/S
