Repository kubeflow/pipelines, pull requests merged in 2025-09, with the labels that each got.

#12197 Add VaniHaripriya as a reviewer for SDK and backend
  backend/OWNERS
  sdk/OWNERS
Labels: lgtm, approved, size/XS

#12152 docs(KEP): adding test plan for to validate different argo workflow controller versions
  proposals/support_different_argo_wf_versions_testplan/different_aw_test_plan.md
Labels: lgtm, approved, size/M

#12213 chore(backend): correct node id for metrics reporting
  backend/src/agent/persistence/worker/metrics_reporter_test.go
  backend/src/common/util/workflow.go
Labels: lgtm, approved, size/M

#12185 feat(sdk/backend): Support forwarding task configuration to external workloads
  .github/workflows/kfp-samples.yml
  .github/workflows/readthedocs-builds.yml
  .github/workflows/sdk-upgrade.yml
  api/v2alpha1/go/pipelinespec/pipeline_spec.pb.go
  api/v2alpha1/pipeline_spec.proto
  backend/src/v2/driver/container.go
  backend/src/v2/driver/driver.go
  backend/src/v2/driver/driver_test.go
  backend/src/v2/driver/k8s.go
  backend/src/v2/driver/k8s_test.go
  backend/src/v2/driver/resolve.go
  backend/test/proto_tests/testdata/generated-1791485/pipeline_spec.json
  samples/v2/sample_test.py
  samples/v2/task_config.py
  sdk/python/kfp/compiler/pipeline_spec_builder.py
  sdk/python/kfp/compiler/pipeline_spec_builder_test.py
  sdk/python/kfp/dsl/__init__.py
  sdk/python/kfp/dsl/component_decorator.py
  sdk/python/kfp/dsl/component_factory.py
  sdk/python/kfp/dsl/component_task_config.py
  sdk/python/kfp/dsl/executor.py
  sdk/python/kfp/dsl/structures.py
  sdk/python/kfp/dsl/task_config.py
  sdk/python/kfp/dsl/types/type_utils.py
Labels: lgtm, approved, size/XXL

#12223 fix(CI): Fix test-config sample CI failure
  samples/v2/task_config.py
Labels: lgtm, approved, size/XS

#12225 fix(ui): Disable caching for AWS credential files
  frontend/server/minio-helper.ts
Labels: lgtm, approved, size/XS, needs-ok-to-test

#12221 chore: add Sophotech to adopters list
  ADOPTERS.md
Labels: lgtm, approved, needs-ok-to-test, size/S

#12226 docs: Add pipeline flow details to contribution
  docs/contributing/anatomy.md
  docs/contributing/pipeline-flow.png
Labels: lgtm, approved, size/S, ok-to-test

#12242 feat: Make artifact proxy opt-in via ARTIFACTS_PROXY_ENABLED configuration
  manifests/kustomize/base/installs/generic/pipeline-install-config.yaml
  manifests/kustomize/base/installs/generic/postgres/pipeline-install-config.yaml
  manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/deployment.yaml
  manifests/kustomize/base/installs/multi-user/pipelines-ui/deployment-patch.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-ui-deployment.yaml
Labels: lgtm, approved, size/M

#12253 chore: update mlmd removal proto/schema design
  proposals/12147-mlmd-removal/protos/artifacts.proto
  proposals/12147-mlmd-removal/protos/runs.json
  proposals/12147-mlmd-removal/protos/runs.proto
  proposals/12147-mlmd-removal/schema_changes.sql
Labels: lgtm, approved, size/XL

#12256 feat(backend): Add support for Pythonic artifacts
  backend/src/v2/driver/driver.go
  samples/v2/pythonic_artifacts_test_pipeline.py
  samples/v2/sample_test.py
Labels: lgtm, approved, size/M

#12261 fix(manifests): Fix a typo in the multi-user roles
  manifests/kustomize/base/installs/multi-user/view-edit-cluster-roles.yaml
Labels: lgtm, approved, size/XS

#12257 chore(frontend): Increase node version to 22.19.0
  frontend/.nvmrc
  frontend/CONTRIBUTING.md
  frontend/Dockerfile
Labels: lgtm, approved, size/S, ok-to-test

#12270 chore(frontend): remediate CVE-2023-36665 and CVE-2022-25878 protobufjs
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, size/S, ok-to-test

#12273 fix(CI): Build the generator and release images on pushes
  .github/workflows/build-tools-images.yml
  api/Makefile
  backend/api/Dockerfile
  backend/api/Makefile
  backend/api/README.md
  kubernetes_platform/Makefile
  sdk/Makefile
  test/release/Dockerfile.release
  test/release/Makefile
  test/release/bump-version-docker.sh
  test/release/release.sh
Labels: lgtm, approved, size/L

#12281 feat(backend): adding a retry logic to object store s3 configuration
  backend/src/v2/config/env.go
  backend/src/v2/config/env_test.go
  backend/src/v2/config/s3.go
  backend/src/v2/objectstore/config.go
  backend/src/v2/objectstore/object_store.go
  backend/src/v2/objectstore/object_store_test.go
  go.mod
Labels: lgtm, approved, size/L

#12280 chore(frontend): Remediating vulns in frontend package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/viewers/Tensorboard.test.tsx
Labels: lgtm, approved, size/XXL, ok-to-test

#12238 doc: Add a KEP for Jupyter notebook components
  proposals/12238-notebook-component/README.md
Labels: lgtm, approved, size/L

#12045 feat: bump express version
  frontend/server/app.ts
  frontend/server/integration-tests/artifact-proxy.test.ts
  frontend/server/minio-helper.test.ts
  frontend/server/package-lock.json
  frontend/server/package.json
Labels: lgtm, approved, size/XXL, ok-to-test

#11340 feat(SDK): Add SemaphoreKey and MutexName fields to DSL
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/compiler/pipeline_spec_builder.py
  sdk/python/kfp/dsl/pipeline_config.py
Labels: lgtm, approved, size/L, ci-passed

#12297 chore: Replace sdk in pipeline files
  .github/actions/test-and-report/action.yml
  backend/src/common/client/api_server/util.go
  backend/test/config/flags.go
  backend/test/end2end/e2e_suite_test.go
  backend/test/end2end/pipeline_e2e_test.go
  backend/test/end2end/utils/e2e_utils.go
  backend/test/test_utils/pipeline_utils.go
  backend/test/test_utils/test_utils.go
  backend/test/v2/api/integration_suite_test.go
  backend/test/v2/api/pipeline_run_api_test.go
Labels: lgtm, approved, size/L
