Repository kubeflow/pipelines, pull requests merged in 2025-08, with the labels that each got.

#12101 fix(backend): omit unknown fields in json marshaling
  backend/src/apiserver/common/utils.go
  backend/src/apiserver/main.go
  backend/src/apiserver/server/experiment_server_test.go
  backend/test/integration/job_api_test.go
  backend/test/integration/run_api_test.go
  backend/test/integration/upgrade_test.go
Labels: lgtm, approved, size/L

#12080 Address review comments from PR #11965
  .github/actions/kfp-cluster/action.yml
  .github/resources/manifests/argo/overlays/multi-user/apiserver-env.yaml
  .github/resources/manifests/argo/overlays/multi-user/kustomization.yaml
  .github/resources/manifests/argo/overlays/no-proxy-minio/apiserver-env.yaml
  .github/resources/manifests/argo/overlays/no-proxy-minio/kustomization.yaml
  .github/resources/manifests/argo/overlays/no-proxy-minio/workflow-disable-logs-patch.yaml
  .github/resources/manifests/argo/overlays/proxy/proxy-env.yaml
  .github/resources/scripts/deploy-kfp.sh
  .github/resources/scripts/free-disk-space.sh
  .github/workflows/e2e-seaweedfs-test.yml
  .github/workflows/e2e-test.yml
  .github/workflows/kfp-samples.yml
  backend/Dockerfile
  backend/metadata_writer/src/metadata_helpers.py
  backend/src/apiserver/client_manager/client_manager.go
  backend/src/apiserver/config/proxy/config.go
  backend/src/v2/cacheutils/cache.go
  backend/src/v2/metadata/env.go
  backend/src/v2/objectstore/config.go
  manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
  manifests/kustomize/env/platform-agnostic-minio/kustomization.yaml
  manifests/kustomize/third-party/minio/base/kustomization.yaml
  manifests/kustomize/third-party/minio/base/minio-deployment.yaml
  manifests/kustomize/third-party/minio/base/minio-pvc.yaml
  manifests/kustomize/third-party/minio/base/minio-service.yaml
  manifests/kustomize/third-party/minio/base/mlpipeline-minio-artifact-secret.yaml
  manifests/kustomize/third-party/minio/options/istio/istio-authorization-policy.yaml
  manifests/kustomize/third-party/minio/options/istio/kustomization.yaml
  manifests/kustomize/third-party/seaweedfs/PSS_baseline_enable.sh
  manifests/kustomize/third-party/seaweedfs/PSS_restricted_enable.sh
  manifests/kustomize/third-party/seaweedfs/base/seaweedfs/seaweedfs-create-admin-user-job.yaml
  manifests/kustomize/third-party/seaweedfs/pipelines_swfs_install.sh
  manifests/kustomize/third-party/seaweedfs/port_forward_gateway.sh
  samples/v2/sample_test.py
  test/seaweedfs/kubeflow-edit-clusterrole.yaml
  test/seaweedfs/test_pipeline_v1_seaweedfs.py
  test/seaweedfs/test_pipeline_v2_seaweedfs.py
Labels: size/XL

#12035 docs(KEP): K8s native api test plan (WIP)
  proposals/11551-kubernetes-native-api/TestPlan.md
Labels: lgtm, approved, needs-ok-to-test, size/M

#12114 chore: update sphinx deps
  docs/sdk/requirements.txt
Labels: lgtm, approved, size/XS

#12115 chore: ignore adding pb2.py files for kfp-k8s docs
  kubernetes_platform/python/create_release_branch.sh
Labels: lgtm, approved, size/XS

#12107 Fix samples-test workflow
  .github/workflows/kfp-samples.yml
  samples/v2/sample_test.py
Labels: size/M

#12120 update kfp server api for kfp sdk
  sdk/python/kfp/client/client.py
  sdk/python/kfp/version.py
  sdk/python/requirements.in
  sdk/python/requirements.txt
  test/sample-test/requirements.in
  test/sample-test/requirements.txt
Labels: lgtm, approved, size/S

#12124 chore: Add security context at pod level for workflow-controller
  manifests/kustomize/third-party/argo/base/workflow-controller-deployment-patch.yaml
Labels: lgtm, approved, size/S

#12129 add more considerations for proposal readme
  proposals/README.md
Labels: lgtm, approved, size/XS

#12078 feat(backend/sdk): define and use dsl.WORKSPACE_PATH_PLACEHOLDER for workspace access
  backend/src/v2/compiler/visitor.go
  backend/src/v2/component/constants.go
  backend/src/v2/driver/driver.go
  backend/src/v2/driver/driver_test.go
  backend/src/v2/driver/resolve.go
  proposals/11875-pipeline-workspace/README.md
  samples/v2/pipeline_with_workspace.py
  samples/v2/sample_test.py
  sdk/python/kfp/dsl/__init__.py
  sdk/python/kfp/dsl/constants.py
  sdk/python/kfp/local/config.py
  sdk/python/kfp/local/config_test.py
  sdk/python/kfp/local/pipeline_orchestrator.py
  sdk/python/kfp/local/pipeline_orchestrator_test.py
  sdk/python/kfp/local/placeholder_utils.py
  sdk/python/kfp/local/placeholder_utils_test.py
Labels: lgtm, approved, size/XL

#12142 docs: add pipeline anatomy documentation
  docs/contributing/anatomy.md
Labels: lgtm, approved, size/M

#12013 chore(backend): migrate GORM v1 to v2
  backend/src/apiserver/client/sql.go
  backend/src/apiserver/client_manager/client_manager.go
  backend/src/apiserver/client_manager/client_manager_test.go
  backend/src/apiserver/client_manager/dialect.go
  backend/src/apiserver/client_manager/dialect_test.go
  backend/src/apiserver/model/db_status.go
  backend/src/apiserver/model/default_experiment.go
  backend/src/apiserver/model/experiment.go
  backend/src/apiserver/model/job.go
  backend/src/apiserver/model/pipeline.go
  backend/src/apiserver/model/pipeline_spec.go
  backend/src/apiserver/model/pipeline_version.go
  backend/src/apiserver/model/resource_reference.go
  backend/src/apiserver/model/run.go
  backend/src/apiserver/model/runtime_config.go
  backend/src/apiserver/model/task.go
  backend/src/apiserver/server/api_converter.go
  backend/src/apiserver/server/api_converter_test.go
  backend/src/apiserver/server/experiment_server.go
  backend/src/apiserver/server/experiment_server_test.go
  backend/src/apiserver/server/pipeline_server_test.go
  backend/src/apiserver/server/pipeline_upload_server.go
  backend/src/apiserver/server/pipeline_upload_server_test.go
  backend/src/apiserver/server/run_server.go
  backend/src/apiserver/server/run_server_test.go
  backend/src/apiserver/storage/db_fake.go
  backend/src/apiserver/storage/experiment_store.go
  backend/src/apiserver/validation/length.go
  backend/src/apiserver/validation/length_test.go
  backend/src/cache/client_manager.go
  backend/src/cache/model/execution_cache.go
  backend/src/cache/server/client_manager_fake.go
  backend/src/cache/storage/db.go
  backend/src/cache/storage/db_fake.go
  backend/src/cache/storage/execution_cache_store.go
  backend/src/cache/storage/execution_cache_store_test.go
  go.mod
  go.sum
  manifests/kustomize/third-party/mysql/base/mysql-deployment.yaml
Labels: lgtm, approved, size/XXL, ok-to-test

#12125 feat: Updated dockerfile to support Power
  frontend/Dockerfile
Labels: lgtm, approved, size/XS, ok-to-test

#12156 chore: Update seaweedfs pvc volume size
  manifests/kustomize/third-party/seaweedfs/base/seaweedfs/seaweedfs-pvc.yaml
Labels: lgtm, approved, size/XS

#12147 propose removing mlmd from kfp
  proposals/12147-mlmd-removal/README.md
  proposals/12147-mlmd-removal/design-details.md
  proposals/12147-mlmd-removal/protos/artifacts.proto
  proposals/12147-mlmd-removal/protos/runs.json
  proposals/12147-mlmd-removal/protos/runs.proto
  proposals/12147-mlmd-removal/schema_changes.sql
Labels: lgtm, approved, size/XXL

#12160 fix(docs): Fix local development after the SeaweedFS migration
  backend/README.md
  manifests/kustomize/env/dev-kind/kustomization.yaml
Labels: lgtm, approved, size/M

#12162 fix(backend): Fix mutating webhook when pipeline name label value is too long
  .github/workflows/upgrade-test.yml
  backend/src/apiserver/webhook/pipelineversion_webhook.go
  backend/src/apiserver/webhook/pipelineversion_webhook_test.go
Labels: lgtm, approved, size/M

#12177 fix(docs): Fix driver remote debugging instructions
  backend/Makefile
  backend/README.md
Labels: lgtm, approved, size/XS

#12173 feat(frontend): Add custom credential provider
  frontend/server/minio-helper.test.ts
  frontend/server/minio-helper.ts
Labels: lgtm, approved, needs-ok-to-test, size/M

#12181 fix(CI): Fix a variable reference typo in the GitHub workflow
  .github/actions/kfp-cluster/action.yml
Labels: lgtm, approved, size/XS

#12151 test: Run e2e CI tests using various versions of AWF. Fixes #12150
  .github/actions/kfp-cluster/action.yml
  .github/resources/scripts/deploy-kfp.sh
  .github/workflows/e2e-test.yml
  .github/workflows/kfp-samples.yml
Labels: lgtm, approved, size/L

#12189 fix(backend): Add support for additional filters on the Kubernetes native API
  backend/src/apiserver/filter/filter.go
  backend/src/apiserver/filter/filter_test.go
  backend/src/crd/kubernetes/v2beta1/pipeline_types.go
  backend/src/crd/kubernetes/v2beta1/pipelineversion_types.go
Labels: lgtm, approved, size/L

#12190 docs: Document the supported Argo Workflows versions
  .github/scripts/verify-argo-matrix.py
  .github/workflows/docs-freshness.yml
  README.md
  third_party/argo/README.md
Labels: lgtm, approved, size/L

#12192 [release-2.14] Cherry-pick Kubernetes native API bug fixes
  backend/src/apiserver/filter/filter.go
  backend/src/apiserver/filter/filter_test.go
  backend/src/apiserver/storage/pipeline_store_kubernetes.go
  backend/src/apiserver/webhook/pipelineversion_webhook.go
  backend/src/apiserver/webhook/pipelineversion_webhook_test.go
  backend/src/crd/kubernetes/v2beta1/pipeline_types.go
  backend/src/crd/kubernetes/v2beta1/pipelineversion_types.go
  backend/src/crd/kubernetes/v2beta1/pipelineversion_types_test.go
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/compiler/pipeline_spec_builder.py
  tools/k8s-native/migration.py
Labels: lgtm, approved, size/XL

#12194 CI: Add back a workflow to build release images
  .github/workflows/image-builds-release.yml
  RELEASE.md
Labels: lgtm, approved, size/M

#12196 fix(CI): Push built container images on the master branch
  .github/workflows/image-builds-master.yml
Labels: lgtm, approved, size/XS

#12163 refactor(backend): introduce dialect-aware LargeText and replace longtext (+call-site type adjustments). Part of #12063
  backend/src/apiserver/config/config.go
  backend/src/apiserver/model/common.go
  backend/src/apiserver/model/pipeline.go
  backend/src/apiserver/model/pipeline_spec.go
  backend/src/apiserver/model/pipeline_version.go
  backend/src/apiserver/model/resource_reference.go
  backend/src/apiserver/model/run.go
  backend/src/apiserver/model/runtime_config.go
  backend/src/apiserver/model/task.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/server/api_converter.go
  backend/src/apiserver/server/fakes_test.go
  backend/src/apiserver/server/pipeline_server.go
  backend/src/apiserver/server/pipeline_server_test.go
  backend/src/apiserver/server/pipeline_upload_server.go
  backend/src/apiserver/server/pipeline_upload_server_test.go
  backend/src/apiserver/storage/job_store.go
  backend/src/apiserver/storage/pipeline_store.go
  backend/src/apiserver/storage/pipeline_store_kubernetes_test.go
  backend/src/apiserver/storage/pipeline_store_test.go
  backend/src/apiserver/storage/resource_reference_store.go
  backend/src/apiserver/storage/resource_reference_store_test.go
  backend/src/apiserver/storage/run_store.go
  backend/src/apiserver/storage/task_store.go
  backend/src/apiserver/template/argo_template.go
  backend/src/apiserver/template/template.go
  backend/src/apiserver/template/template_test.go
  backend/src/apiserver/template/v2_template.go
  backend/src/common/client/api_server/v2/pipeline_upload_client_kubernetes.go
  backend/src/crd/kubernetes/v2beta1/pipeline_types.go
  backend/src/crd/kubernetes/v2beta1/pipelineversion_types.go
  backend/src/crd/kubernetes/v2beta1/pipelineversion_types_test.go
  backend/test/v2/integration/pipeline_api_test.go
Labels: lgtm, approved, size/XL, ok-to-test
