Repository kubeflow/pipelines, pull requests merged in 2025-06, with the labels that each got.

#11951 docs(frontend): Added clean up section to openshift docs
  manifests/kustomize/env/openshift/README.md
Labels: lgtm, approved, size/XS, needs-ok-to-test

#11934 feat(sdk): update PipelineConfig to reflect new workspace Protobuf changes
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/compiler/pipeline_spec_builder.py
  sdk/python/kfp/dsl/__init__.py
  sdk/python/kfp/dsl/pipeline_config.py
Labels: lgtm, approved, size/L

#11955 feat(frontend) Use native k8s probes for pipeline-ui
  manifests/kustomize/base/pipeline/ml-pipeline-ui-deployment.yaml
Labels: lgtm, approved, size/S, ok-to-test, ci-passed

#11953 feat(backend/sdk): support PipelineTaskFinalStatus input
  backend/src/v2/compiler/argocompiler/argo_test.go
  backend/src/v2/compiler/argocompiler/dag.go
  backend/src/v2/compiler/argocompiler/testdata/final_status_state.yaml
  backend/src/v2/compiler/testdata/final_status_state.json
  backend/src/v2/driver/driver_test.go
  backend/src/v2/driver/resolve.go
  samples/v2/pipeline_with_input_status_state.py
  samples/v2/sample_test.py
  sdk/RELEASE.md
  sdk/python/kfp/dsl/executor.py
Labels: lgtm, approved, size/XL

#11854 test(backend): Add unit test for NewLauncherV2
  backend/src/v2/client_manager/client_manager.go
  backend/src/v2/client_manager/client_manager_fake.go
  backend/src/v2/cmd/launcher-v2/main.go
  backend/src/v2/component/launcher_v2.go
  backend/src/v2/component/launcher_v2_test.go
Labels: lgtm, approved, size/L, ok-to-test

#11977 user master for dev manifests
  manifests/kustomize/env/dev/api-server-patch.yaml
  manifests/kustomize/env/dev/kustomization.yaml
Labels: lgtm, approved, size/M

#11995 chore: update workflows to test proto changes in ci
  .github/workflows/e2e-test.yml
  .github/workflows/gcpc-modules-tests.yml
  .github/workflows/kfp-kubernetes-execution-tests.yml
  .github/workflows/kfp-kubernetes-library-test.yml
  .github/workflows/kfp-samples.yml
  .github/workflows/kfp-sdk-tests.yml
  .github/workflows/sdk-execution.yml
  backend/src/v2/test/sample-test.sh
  test/presubmit-tests-sdk.sh
Labels: lgtm, approved, size/L

#11998 fix(apiserver): fix typos in resource_manager.go:
  backend/src/apiserver/resource/resource_manager.go
Labels: lgtm, approved, size/S

#12005 chore(backend): upgrade minio-go to v7
  backend/src/apiserver/client/minio.go
  backend/src/apiserver/client_manager/client_manager.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/server/run_server_test.go
  backend/src/apiserver/storage/minio_client.go
  backend/src/apiserver/storage/minio_client_fake.go
  backend/src/apiserver/storage/object_store.go
  backend/src/apiserver/storage/object_store_test.go
  go.mod
  go.sum
Labels: lgtm, approved, size/L, ci-passed

#12003 chore(backend): Fixed warnings in Dockerfiles
  backend/Dockerfile
  backend/Dockerfile.driver
  backend/Dockerfile.launcher
  backend/Dockerfile.persistenceagent
  backend/Dockerfile.scheduledworkflow
Labels: lgtm, approved, size/M

#12011 chore(docs): change adrs to kep in contrib doc
  CONTRIBUTING.md
Labels: lgtm, approved, size/XS

#12009 feat(docs): erdiagram of kfp-db
  docs/diagram/.gitignore
  docs/diagram/Makefile
  docs/diagram/kfp-db.mmd
Labels: lgtm, approved, needs-ok-to-test, size/L

#12006 feat(sdk): Add Support for Docker Container Run Arguments
  sdk/python/kfp/local/config.py
  sdk/python/kfp/local/config_test.py
  sdk/python/kfp/local/docker_task_handler.py
Labels: lgtm, approved, size/L, ok-to-test
