Repository kubeflow/pipelines, pull requests merged in 2025-01, with the labels that each got.

#11496 chore(test): Fix SDK tests
  .github/workflows/kfp-samples.yml
  .github/workflows/kfp-sdk-tests.yml
Labels: lgtm, approved, size/XS

#11480 chore(backend): Fixed namespace in job creation
  backend/src/apiserver/resource/resource_manager.go
Labels: lgtm, approved, size/S

#11481 chore(backend): Fixed ServiceAccount in job creation
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/template/template_test.go
  backend/src/apiserver/template/v2_template.go
Labels: lgtm, approved, size/M

#11469 fix(backend): Synced ScheduledWorkflow CRs on apiserver startup
  backend/src/apiserver/client/scheduled_workflow_fake.go
  backend/src/apiserver/list/list.go
  backend/src/apiserver/list/list_test.go
  backend/src/apiserver/main.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
Labels: lgtm, approved, size/L

#11473 chore(deps): Update client-go and controller-runtime
  .github/workflows/backend.yml
  .github/workflows/presubmit-backend.yml
  backend/Dockerfile
  backend/Dockerfile.cacheserver
  backend/Dockerfile.conformance
  backend/Dockerfile.driver
  backend/Dockerfile.launcher
  backend/Dockerfile.persistenceagent
  backend/Dockerfile.scheduledworkflow
  backend/Dockerfile.viewercontroller
  backend/api/Dockerfile
  backend/src/agent/persistence/client/scheduled_workflow_client.go
  backend/src/agent/persistence/client/workflow_client.go
  backend/src/agent/persistence/main.go
  backend/src/agent/persistence/persistence_agent.go
  backend/src/agent/persistence/worker/persistence_worker.go
  backend/src/agent/persistence/worker/persistence_worker_test.go
  backend/src/crd/controller/scheduledworkflow/client/swf_client.go
  backend/src/crd/controller/scheduledworkflow/client/workflow_client.go
  backend/src/crd/controller/scheduledworkflow/controller.go
  backend/src/crd/controller/scheduledworkflow/main.go
  backend/third_party_licenses/apiserver.csv
  backend/third_party_licenses/cache_server.csv
  backend/third_party_licenses/driver.csv
  backend/third_party_licenses/launcher.csv
  backend/third_party_licenses/persistence_agent.csv
  backend/third_party_licenses/swf.csv
  backend/third_party_licenses/viewer.csv
  go.mod
  go.sum
  hack/install-go-licenses.sh
Labels: lgtm, approved, size/XXL, ok-to-test

#11501 feat(sdk/backend): Add support for placeholders in resource limits
  backend/src/v2/driver/driver.go
  backend/src/v2/driver/driver_test.go
  backend/third_party_licenses/apiserver.csv
  backend/third_party_licenses/driver.csv
  backend/third_party_licenses/launcher.csv
  go.mod
  go.sum
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/compiler/compiler_utils.py
  sdk/python/kfp/compiler/pipeline_spec_builder.py
  sdk/python/test_data/pipelines/pipeline_with_resource_spec.yaml
Labels: lgtm, approved, size/L

#11499 chore: Add instructions to remote debug the Driver pods
  .gitignore
  backend/Dockerfile.driver
  backend/Makefile
  backend/README.md
  backend/src/v2/compiler/argocompiler/argo.go
  backend/src/v2/compiler/argocompiler/container.go
  backend/src/v2/compiler/argocompiler/dag.go
Labels: lgtm, approved, size/L

#11470 fix(backend): Use an Argo Workflow exit lifecycle hook for exit handlers
  .github/workflows/e2e-test.yml
  backend/src/v2/compiler/argocompiler/argo_test.go
  backend/src/v2/compiler/argocompiler/common.go
  backend/src/v2/compiler/argocompiler/container.go
  backend/src/v2/compiler/argocompiler/dag.go
  backend/src/v2/compiler/argocompiler/testdata/exit_handler.yaml
  backend/src/v2/compiler/testdata/Makefile
  backend/src/v2/compiler/testdata/exit_handler.json
  test/sample-test/run_sample_test.py
  test/sample-test/sample_test_launcher.py
Labels: lgtm, approved, size/XL, ok-to-test

#11507 nominate approver & reviewer for backend
  backend/OWNERS
Labels: lgtm, approved, size/XS

#11508 nominate reviewers for backend
  backend/OWNERS
Labels: lgtm, approved, size/XS

#11493 fix(frontend): Detailed information of nodes is not displayed when clicking the node. Fixes #11325
  frontend/src/pages/PipelineDetailsV2.tsx
  frontend/src/pages/RunDetailsV2.tsx
  frontend/src/pages/v2/DagCanvas.tsx
Labels: lgtm, approved, size/M

#11519 Fix the failing exit handler SDK execution tests
  .github/workflows/sdk-execution.yml
  sdk/python/test_data/test_data_config.yaml
  test/sdk-execution-tests/sdk_execution_tests.py
Labels: lgtm, approved, size/XS

#11514 chore: Address CVEs
  .github/workflows/frontend.yml
  backend/src/apiserver/visualization/exporter.py
  backend/src/apiserver/visualization/requirements.in
  backend/src/apiserver/visualization/requirements.txt
  backend/src/apiserver/visualization/snapshots/snap_test_exporter.py
  backend/src/apiserver/visualization/templates/basic.tpl
  backend/third_party_licenses/apiserver.csv
  backend/third_party_licenses/cache_server.csv
  backend/third_party_licenses/driver.csv
  backend/third_party_licenses/launcher.csv
  backend/third_party_licenses/persistence_agent.csv
  backend/third_party_licenses/swf.csv
  backend/third_party_licenses/viewer.csv
  components/contrib/openvino/ovms-deployer/containers/requirements.txt
  frontend/Dockerfile
  frontend/mock-backend/package-lock.json
  frontend/package-lock.json
  frontend/package.json
  frontend/server/package-lock.json
  frontend/server/package.json
  frontend/src/pages/NewRun.test.tsx
  frontend/src/pages/PipelineDetails.test.tsx
  go.mod
  go.sum
  hack/update-requirements.sh
  test/tools/project-cleaner/go.mod
  test/tools/project-cleaner/go.sum
  third_party/ml-metadata/go.mod
  third_party/ml-metadata/go.sum
Labels: lgtm, approved, size/XXL

#11522 add remaining dockerfiles to build workflow
  .github/workflows/image-builds.yml
Labels: lgtm, approved, size/S

#11524 fix(frontend): Fix the frontend image build with Node 22
  frontend/Dockerfile
  frontend/server/package-lock.json
  frontend/server/package.json
Labels: lgtm, approved, size/XL, ci-passed

#11525 fix(frontend): Fix the frontend image build with Node 22 (#11524)
  frontend/Dockerfile
  frontend/server/package-lock.json
  frontend/server/package.json
Labels: lgtm, approved, size/XL

#11526 chore: switch to using gh container registry in manifests
  backend/src/v2/compiler/argocompiler/container.go
  manifests/kustomize/base/cache-deployer/cache-deployer-deployment.yaml
  manifests/kustomize/base/cache-deployer/kustomization.yaml
  manifests/kustomize/base/cache/cache-deployment.yaml
  manifests/kustomize/base/cache/kustomization.yaml
  manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/sync.py
  manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/test_sync.py
  manifests/kustomize/base/metadata/base/kustomization.yaml
  manifests/kustomize/base/metadata/base/metadata-envoy-deployment.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/base/pipeline/metadata-writer/kustomization.yaml
  manifests/kustomize/base/pipeline/metadata-writer/metadata-writer-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-scheduledworkflow-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-ui-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-viewer-crd-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-visualization-deployment.yaml
  manifests/kustomize/env/gcp/inverse-proxy/kustomization.yaml
  manifests/kustomize/env/gcp/inverse-proxy/proxy-deployment.yaml
Labels: lgtm, approved, size/M

#11527 chore: switch to using gh container registry in manifests (#11526)
  backend/src/v2/compiler/argocompiler/container.go
  manifests/kustomize/base/cache-deployer/cache-deployer-deployment.yaml
  manifests/kustomize/base/cache-deployer/kustomization.yaml
  manifests/kustomize/base/cache/cache-deployment.yaml
  manifests/kustomize/base/cache/kustomization.yaml
  manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/sync.py
  manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/test_sync.py
  manifests/kustomize/base/metadata/base/kustomization.yaml
  manifests/kustomize/base/metadata/base/metadata-envoy-deployment.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/base/pipeline/metadata-writer/kustomization.yaml
  manifests/kustomize/base/pipeline/metadata-writer/metadata-writer-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-scheduledworkflow-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-ui-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-viewer-crd-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-visualization-deployment.yaml
  manifests/kustomize/env/gcp/inverse-proxy/kustomization.yaml
  manifests/kustomize/env/gcp/inverse-proxy/proxy-deployment.yaml
Labels: lgtm, approved, size/M, ci-passed

#11411 fix(backend): Fix enable_caching issues when handling PVC creation/deletion
  backend/src/v2/driver/driver.go
  samples/v2/Makefile
  samples/v2/pipeline_with_volume_no_cache.py
  samples/v2/pipeline_with_volume_no_cache_test.py
Labels: lgtm, approved, size/L, ci-passed

#11528 chore: switch release/api generator images to ghcr
  api/Makefile
  backend/api/Dockerfile
  backend/api/Makefile
  backend/api/README.md
  backend/src/v2/README.md
  kubernetes_platform/Makefile
  test/release/Dockerfile.release
  test/release/Makefile
  test/release/README.md
  test/release/bump-version-docker.sh
  test/release/release.sh
Labels: lgtm, approved, size/M, ci-passed

#11530 switch release/api generator images to ghcr (#11528)
  api/Makefile
  backend/api/Dockerfile
  backend/api/Makefile
  backend/api/README.md
  backend/src/v2/README.md
  kubernetes_platform/Makefile
  test/release/Dockerfile.release
  test/release/Makefile
  test/release/README.md
  test/release/bump-version-docker.sh
  test/release/release.sh
Labels: lgtm, approved, size/M, ci-passed

#11529 test: fix CI failure by upgrading upload-artifact version
  .github/workflows/ci-checks.yml
Labels: lgtm, approved, size/XS

#11531 chore(release): bumped version to 2.4.0
  CHANGELOG.md
  VERSION
  backend/api/v1beta1/python_http_client/README.md
  backend/api/v1beta1/python_http_client/kfp_server_api/__init__.py
  backend/api/v1beta1/python_http_client/kfp_server_api/api_client.py
  backend/api/v1beta1/python_http_client/kfp_server_api/configuration.py
  backend/api/v1beta1/python_http_client/setup.py
  backend/api/v1beta1/swagger/kfp_api_single_file.swagger.json
  backend/api/v2beta1/go_client/experiment.pb.go
  backend/api/v2beta1/go_http_client/experiment_model/v2beta1_experiment.go
  backend/api/v2beta1/python_http_client/README.md
  backend/api/v2beta1/python_http_client/docs/V2beta1Experiment.md
  backend/api/v2beta1/python_http_client/kfp_server_api/__init__.py
  backend/api/v2beta1/python_http_client/kfp_server_api/api_client.py
  backend/api/v2beta1/python_http_client/kfp_server_api/configuration.py
  backend/api/v2beta1/python_http_client/kfp_server_api/models/v2beta1_experiment.py
  backend/api/v2beta1/python_http_client/setup.py
  backend/api/v2beta1/python_http_client/test/test_v2beta1_experiment.py
  backend/api/v2beta1/python_http_client/test/test_v2beta1_list_experiments_response.py
  backend/api/v2beta1/swagger/experiment.swagger.json
  backend/api/v2beta1/swagger/kfp_api_single_file.swagger.json
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml
  manifests/gcp_marketplace/schema.yaml
  manifests/kustomize/base/installs/generic/pipeline-install-config.yaml
Labels: lgtm, approved, size/L

#11490 feat(docs): Add architecture diagram
  README.md
  docs/Architecture.md
  images/README.md
  images/kfp-cluster-wide-architecture.drawio.xml
  images/kfp-cluster-wide-architecture.png
Labels: lgtm, approved, size/L

#11538 chore: Remove ouadakarim from Kubeflow Pipelines reviewers
  OWNERS
Labels: lgtm, approved, size/XS

#11549 fix(backend): removed old version comment
  backend/src/v2/README.md
Labels: lgtm, approved, size/XS, needs-ok-to-test

#11535 feat(docs): Replace ADRs with KEPs for documentation
  adrs/KFP-ADR-0001-use-architecture-decision-records-for-kfp.md
  adrs/OWNERS
  adrs/README.md
  adrs/template.md
  hack/update-toc.sh
  proposals/0000-kep-process/README.md
  proposals/NNNN-kep-template/README.md
Labels: lgtm, approved, size/XL

#11518 fix(frontend): fixes Default pipeline input params are missing from the GUI. Fixes #11515
  frontend/src/components/NewRunParametersV2.tsx
Labels: lgtm, approved, size/XS

#11547 fix(sdk): dsl.component docstring typo
  sdk/python/kfp/dsl/component_decorator.py
Labels: lgtm, approved, size/XS, ok-to-test

#10762 chore: bump requests-toolbelt to 1.0.0
  sdk/python/requirements.in
  sdk/python/requirements.txt
Labels: lgtm, approved, size/M, ok-to-test, ci-passed

#11553 feat(backend): add support for uploading new sample pipeline vers
  backend/src/apiserver/config/config.go
  backend/src/apiserver/config/config_test.go
  backend/src/apiserver/config/sample_config.json
  backend/src/apiserver/config/testdata/sample_pipeline.yaml
  backend/src/apiserver/main.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/storage/pipeline_store.go
Labels: lgtm, approved, size/XL

#11537 Fix typo in documentation for contribution and developer guide
  README.md
Labels: lgtm, approved, size/XS, ok-to-test

#11521 fix: Update broken api-connect link
  backend/src/v2/README.md
  samples/test/utils/kfp/samples/test/utils.py
  sdk/python/kfp/cli/utils/parsing_test.py
  sdk/python/kfp/client/client.py
Labels: lgtm, approved, size/XS, ok-to-test

#11545 chore(test): Fixed namespace in tests
  .github/workflows/e2e-test.yml
  .github/workflows/upgrade-test.yml
  backend/test/integration/db_test.go
Labels: lgtm, approved, size/S

#11511 docs(backend): improved backend README
  backend/README.md
Labels: lgtm, approved, size/M, ok-to-test

#11564 fix(CI): Use the correct image registry for replacements in integration tests
  .github/resources/manifests/argo/kustomization.yaml
  .github/resources/manifests/tekton/kustomization.yaml
  .github/resources/scripts/build-images.sh
  .github/resources/scripts/kfp-readiness/wait_for_pods.py
  backend/Dockerfile
Labels: lgtm, approved, size/M

#11384 feat(api): Add SemaphoreKey and MutexName fields to proto
  api/v2alpha1/go/pipelinespec/pipeline_spec.pb.go
  api/v2alpha1/pipeline_spec.proto
Labels: lgtm, approved, size/M, ok-to-test, ci-passed

#11560 feat(backend): Allow recurring runs to always use the latest pipeline version
  .gitignore
  backend/README.md
  backend/api/Makefile
  backend/api/README.md
  backend/api/v1beta1/job.proto
  backend/api/v2beta1/go_client/recurring_run.pb.go
  backend/api/v2beta1/go_client/run.pb.go
  backend/api/v2beta1/go_http_client/recurring_run_model/v2beta1_pipeline_version_reference.go
  backend/api/v2beta1/go_http_client/run_model/v2beta1_pipeline_version_reference.go
  backend/api/v2beta1/go_http_client/run_model/v2beta1_run.go
  backend/api/v2beta1/recurring_run.proto
  backend/api/v2beta1/run.proto
  backend/api/v2beta1/swagger/kfp_api_single_file.swagger.json
  backend/api/v2beta1/swagger/recurring_run.swagger.json
  backend/api/v2beta1/swagger/run.swagger.json
  backend/src/apiserver/client/sql.go
  backend/src/apiserver/client_manager/client_manager.go
  backend/src/apiserver/model/pipeline_spec.go
  backend/src/apiserver/resource/resource_manager.go
  backend/src/apiserver/resource/resource_manager_test.go
  backend/src/apiserver/server/api_converter.go
  backend/src/apiserver/server/job_server.go
  backend/src/apiserver/server/job_server_test.go
  backend/src/apiserver/template/argo_template.go
  backend/src/apiserver/template/template.go
  backend/src/apiserver/template/v2_template.go
  backend/src/common/util/service.go
  backend/src/crd/controller/scheduledworkflow/controller.go
  backend/src/crd/controller/scheduledworkflow/main.go
  backend/src/crd/controller/scheduledworkflow/util/scheduled_workflow.go
  backend/src/crd/pkg/apis/scheduledworkflow/v1beta1/types.go
  backend/test/v2/integration/recurring_run_api_test.go
  manifests/kustomize/base/installs/multi-user/scheduled-workflow/cluster-role.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-scheduledworkflow-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-scheduledworkflow-role.yaml
Labels: lgtm, approved, size/XL

#11577 chore(deps): replace deprecated ioutil with os and io in tests
  backend/src/apiserver/server/api_util_test.go
  backend/src/apiserver/server/pipeline_server_test.go
  backend/src/apiserver/server/util.go
  backend/src/apiserver/server/util_test.go
  backend/src/apiserver/server/visualization_server.go
  backend/src/apiserver/template/template_test.go
  backend/src/cache/server/admission.go
  backend/src/common/client/api_server/util.go
  backend/src/common/util/tgz.go
  backend/src/v2/cmd/compiler/main.go
  backend/src/v2/cmd/driver/main.go
  backend/src/v2/compiler/argocompiler/argo_test.go
  backend/src/v2/compiler/tektoncompiler/tekton_test.go
  backend/src/v2/compiler/visitor_test.go
  backend/src/v2/component/launcher_v2.go
  backend/src/v2/config/env.go
  backend/src/v2/objectstore/object_store.go
  backend/test/integration/job_api_test.go
  backend/test/integration/pipeline_api_test.go
  backend/test/integration/pipeline_version_api_test.go
  backend/test/integration/run_api_test.go
  backend/test/integration/upgrade_test.go
  backend/test/v2/integration/pipeline_version_api_test.go
  backend/test/v2/integration/recurring_run_api_test.go
  backend/test/v2/integration/run_api_test.go
  backend/test/v2/integration/upgrade_test.go
  test/tools/project-cleaner/main.go
Labels: lgtm, approved, size/L, ok-to-test
