Repository kubeflow/pipelines, pull requests merged in 2025-03, with the labels that each got.

#11719 remove unused function
  backend/src/v2/compiler/argocompiler/container.go
Labels: lgtm, approved, size/XS

#11682 fix(frontend): compatibility with pod_names v1
  frontend/src/lib/Utils.tsx
Labels: lgtm, approved, size/XS

#11669 Chore: fix the PPC image for the dockerhub ratelimit and add the securitycontext
  manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/deployment.yaml
Labels: lgtm, approved, size/S

#11718 chore(release): bumped version to 2.4.1
  CHANGELOG.md
  VERSION
  backend/api/v1beta1/python_http_client/README.md
  backend/api/v1beta1/python_http_client/kfp_server_api/__init__.py
  backend/api/v1beta1/python_http_client/kfp_server_api/api_client.py
  backend/api/v1beta1/python_http_client/kfp_server_api/configuration.py
  backend/api/v1beta1/python_http_client/setup.py
  backend/api/v1beta1/swagger/kfp_api_single_file.swagger.json
  backend/api/v2beta1/python_http_client/README.md
  backend/api/v2beta1/python_http_client/kfp_server_api/__init__.py
  backend/api/v2beta1/python_http_client/kfp_server_api/api_client.py
  backend/api/v2beta1/python_http_client/kfp_server_api/configuration.py
  backend/api/v2beta1/python_http_client/setup.py
  backend/api/v2beta1/swagger/kfp_api_single_file.swagger.json
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/application.yaml
  manifests/gcp_marketplace/schema.yaml
  manifests/kustomize/base/cache-deployer/kustomization.yaml
  manifests/kustomize/base/cache/kustomization.yaml
  manifests/kustomize/base/installs/generic/pipeline-install-config.yaml
  manifests/kustomize/base/metadata/base/kustomization.yaml
  manifests/kustomize/base/pipeline/kustomization.yaml
  manifests/kustomize/base/pipeline/metadata-writer/kustomization.yaml
  manifests/kustomize/env/gcp/inverse-proxy/kustomization.yaml
Labels: lgtm, approved, size/M

#11672 feat(backend): Add types for KFP Kubernete Native API
  .gitignore
  backend/src/crd/kubernetes/Makefile
  backend/src/crd/kubernetes/v2beta1/groupversion_info.go
  backend/src/crd/kubernetes/v2beta1/pipeline_types.go
  backend/src/crd/kubernetes/v2beta1/pipelineversion_types.go
  backend/src/crd/kubernetes/v2beta1/zz_generated.deepcopy.go
  manifests/kustomize/base/crds/kustomization.yaml
  manifests/kustomize/base/crds/pipelines.kubeflow.org_pipelines.yaml
  manifests/kustomize/base/crds/pipelines.kubeflow.org_pipelineversions.yaml
Labels: lgtm, approved, size/XL

#11737 chore(frontend): update kubernetes client version to 0.12.1
  frontend/.nvmrc
  frontend/README.md
  frontend/server/integration-tests/tensorboard.test.ts
  frontend/server/k8s-helper.ts
  frontend/server/package-lock.json
  frontend/server/package.json
  frontend/server/workflow-helper.ts
Labels: lgtm, approved, size/XL

#11734 fix: minio fsgroup for popular clusters
  manifests/kustomize/third-party/minio/base/minio-deployment.yaml
Labels: lgtm, approved, size/XS

#11750 Fix Istio sidecar injection by moving from annotations to labels
  manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/deployment.yaml
  manifests/kustomize/base/metadata/base/metadata-envoy-deployment.yaml
  manifests/kustomize/base/metadata/overlays/db/metadata-db-deployment.yaml
  manifests/kustomize/base/metadata/overlays/postgres/metadata-db-deployment.yaml
  manifests/kustomize/third-party/metacontroller/base/stateful-set.yaml
Labels: lgtm, approved, size/S, ok-to-test

#11743 docs(ui): add multi-user proxy instructions
  frontend/README.md
  frontend/src/index.tsx
Labels: lgtm, approved, size/M

#11759 chore(backend): Allow specification of image registry when building images
  backend/Makefile
Labels: lgtm, approved, size/S

#11071 fix(sdk): avoid conflicting component names in DAG when reusing pipelines
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/compiler/pipeline_spec_builder.py
Labels: lgtm, approved, size/M, ok-to-test

#11767 bug(backend,sdk): Use a valid path separator for Modelcar imports
  backend/src/v2/component/launcher_v2.go
  backend/src/v2/driver/driver_test.go
  sdk/python/kfp/dsl/types/artifact_types.py
  sdk/python/kfp/dsl/types/artifact_types_test.py
Labels: lgtm, approved, size/S

#11758 feat(proto): Add TTL fields to KFP IR yaml proto
  api/v2alpha1/go/pipelinespec/pipeline_spec.pb.go
  api/v2alpha1/pipeline_spec.proto
Labels: lgtm, approved, size/S

#11772 fix(CI) Github action is vulnerable to code execution via `comment body`
  .github/workflows/pr-commands.yml
Labels: lgtm, approved, size/XS, ok-to-test

#11751 Fix PSS restricted warnings
  manifests/kustomize/base/cache/cache-deployment.yaml
  manifests/kustomize/base/metadata/base/metadata-grpc-deployment.yaml
  manifests/kustomize/base/pipeline/metadata-writer/metadata-writer-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-persistenceagent-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-scheduledworkflow-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-ui-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-viewer-crd-deployment.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-visualization-deployment.yaml
  manifests/kustomize/third-party/argo/upstream/manifests/base/workflow-controller/workflow-controller-deployment.yaml
  manifests/kustomize/third-party/minio/base/minio-deployment.yaml
  manifests/kustomize/third-party/mysql/base/mysql-deployment.yaml
Labels: lgtm, approved, size/M, ok-to-test

#11773 test: Fixed and improved log collection
  .github/resources/scripts/collect-logs.sh
  .github/workflows/kfp-samples.yml
Labels: lgtm, approved, size/S

#11776 fix(backend): Include missing go.mod for cacheserver/viewercontroller images
  backend/Dockerfile.cacheserver
  backend/Dockerfile.viewercontroller
Labels: lgtm, approved, size/XS

#11775 test: Fixed `collect-logs.sh` path
  .github/workflows/e2e-test.yml
Labels: lgtm, approved, size/S

#11770 feat(backend/sdk): Add input parameterization for various k8s resources
  .github/workflows/kfp-samples.yml
  backend/src/v2/driver/driver.go
  backend/src/v2/driver/driver_test.go
  backend/src/v2/driver/util.go
  backend/src/v2/test/sample-test.sh
  kubernetes_platform/go/kubernetesplatform/kubernetes_executor_config.pb.go
  kubernetes_platform/proto/kubernetes_executor_config.proto
  kubernetes_platform/python/kfp/kubernetes/__init__.py
  kubernetes_platform/python/kfp/kubernetes/common.py
  kubernetes_platform/python/kfp/kubernetes/config_map.py
  kubernetes_platform/python/kfp/kubernetes/image.py
  kubernetes_platform/python/kfp/kubernetes/node_selector.py
  kubernetes_platform/python/kfp/kubernetes/secret.py
  kubernetes_platform/python/kfp/kubernetes/toleration.py
  kubernetes_platform/python/kfp/kubernetes/volume.py
  kubernetes_platform/python/test/snapshot/data/config_map_as_env.yaml
  kubernetes_platform/python/test/snapshot/data/config_map_as_vol.yaml
  kubernetes_platform/python/test/snapshot/data/create_mount_delete_dynamic_pvc.yaml
  kubernetes_platform/python/test/snapshot/data/create_mount_delete_existing_pvc.yaml
  kubernetes_platform/python/test/snapshot/data/create_mount_delete_existing_pvc_from_task_output.yaml
  kubernetes_platform/python/test/snapshot/data/empty_dir_mounts.yaml
  kubernetes_platform/python/test/snapshot/data/field_path_as_env.yaml
  kubernetes_platform/python/test/snapshot/data/general_ephemeral_volume.yaml
  kubernetes_platform/python/test/snapshot/data/image_pull_secrets.yaml
  kubernetes_platform/python/test/snapshot/data/node_selector.yaml
  kubernetes_platform/python/test/snapshot/data/secret_as_env.yaml
  kubernetes_platform/python/test/snapshot/data/secret_as_vol.yaml
  kubernetes_platform/python/test/snapshot/data/timeout.yaml
  kubernetes_platform/python/test/snapshot/data/toleration.yaml
  kubernetes_platform/python/test/unit/test_config_map.py
  kubernetes_platform/python/test/unit/test_empty_dir_mounts.py
  kubernetes_platform/python/test/unit/test_image_pull_secrets.py
  kubernetes_platform/python/test/unit/test_node_selector.py
  kubernetes_platform/python/test/unit/test_pod_metadata.py
  kubernetes_platform/python/test/unit/test_secret.py
  kubernetes_platform/python/test/unit/test_tolerations.py
  kubernetes_platform/python/test/unit/test_volume.py
  samples/v2/pipeline_with_secret_as_env.py
  samples/v2/pipeline_with_secret_as_volume.py
  samples/v2/pre-requisites/test-secrets.yaml
  samples/v2/sample_test.py
  test/tools/project-cleaner/go.mod
Labels: lgtm, approved, size/XXL

#11777 chore(backend): refactor driver tests
  backend/src/v2/driver/driver_test.go
Labels: lgtm, approved, size/M

#11774 feat(backend): Create a validating webhook for the PipelineVersion kind
  .github/resources/scripts/deploy-kfp-tekton.sh
  .github/resources/scripts/deploy-kfp.sh
  backend/Makefile
  backend/README.md
  backend/src/agent/persistence/main.go
  backend/src/apiserver/client_manager/client_manager.go
  backend/src/apiserver/common/config.go
  backend/src/apiserver/common/utils.go
  backend/src/apiserver/main.go
  backend/src/apiserver/webhook/pipelineversion_webhook.go
  backend/src/apiserver/webhook/pipelineversion_webhook_test.go
  backend/src/crd/controller/scheduledworkflow/main.go
  backend/src/crd/pkg/signals/signal.go
  backend/src/crd/pkg/signals/signal_posix.go
  go.mod
  manifests/kustomize/base/installs/multi-user/api-service/cluster-role.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-apiserver-role.yaml
  manifests/kustomize/base/webhook/kustomization.yaml
  manifests/kustomize/base/webhook/params.yaml
  manifests/kustomize/base/webhook/pipelineversion-validating-webhook-config.yaml
  manifests/kustomize/env/cert-manager/base-webhook-certs/kfp-api-cert-issuer.yaml
  manifests/kustomize/env/cert-manager/base-webhook-certs/kfp-api-cert.yaml
  manifests/kustomize/env/cert-manager/base-webhook-certs/kustomization.yaml
  manifests/kustomize/env/cert-manager/base-webhook-certs/params.yaml
  manifests/kustomize/env/cert-manager/platform-agnostic-k8s-native/kustomization.yaml
  manifests/kustomize/env/cert-manager/platform-agnostic-k8s-native/patches/deployment.yaml
  manifests/kustomize/env/cert-manager/platform-agnostic-k8s-native/patches/service.yaml
  manifests/kustomize/env/cert-manager/platform-agnostic-k8s-native/patches/validating-webhook.yaml
  manifests/kustomize/env/cert-manager/platform-agnostic-multi-user-k8s-native/kustomization.yaml
  manifests/kustomize/env/cert-manager/platform-agnostic-multi-user-k8s-native/patches/deployment.yaml
  manifests/kustomize/env/cert-manager/platform-agnostic-multi-user-k8s-native/patches/service.yaml
  manifests/kustomize/env/cert-manager/platform-agnostic-multi-user-k8s-native/patches/validating-webhook.yaml
  manifests/kustomize/env/dev-kind/forward-local-api-endpoint.yaml
  manifests/kustomize/env/dev-kind/kustomization.yaml
  tools/kind/Dockerfile.webhook-proxy
  tools/kind/webhook-proxy-nginx.conf
  tools/kind/webhook-proxy.yaml
Labels: lgtm, approved, size/XXL

#11779 test: Added the result of `kubectl get pods` to logs when waiting for pods to get ready
  .github/resources/scripts/kfp-readiness/wait_for_pods.py
Labels: lgtm, approved, size/S

#11780 chore(backend): upgade go and deps
  backend/Dockerfile
  backend/Dockerfile.cacheserver
  backend/Dockerfile.conformance
  backend/Dockerfile.driver
  backend/Dockerfile.launcher
  backend/Dockerfile.persistenceagent
  backend/Dockerfile.scheduledworkflow
  backend/Dockerfile.viewercontroller
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#11753 fix(metadata-writer): use mlmd_store.get_context_types() instead of workaround
  backend/metadata_writer/src/metadata_helpers.py
Labels: lgtm, approved, size/XS, ok-to-test
