Repository kubeflow/pipelines, pull requests merged in 2025-04, with the labels that each got.

#11784 chore(test): Replaced the unmaintained rerun action
  .github/workflows/rerun-pr-jobs.yml
Labels: lgtm, approved, size/XS

#11786 chore(test): Bumped ubuntu runner to 24.04 in rerun-pr-jobs.yml
  .github/workflows/rerun-pr-jobs.yml
Labels: lgtm, approved, size/XS

#11783 chore: Upgrade Argo Workflows to v3.5.14, use Argo-provided images
  .cloudbuild.yaml
  .release.cloudbuild.yaml
  backend/Dockerfile
  backend/Dockerfile.driver
  backend/Dockerfile.launcher
  backend/Dockerfile.persistenceagent
  backend/src/common/types.go
  go.mod
  go.sum
  manifests/gcp_marketplace/chart/kubeflow-pipelines/templates/argo.yaml
  manifests/kustomize/third-party/argo/base/workflow-controller-configmap-patch.yaml
  manifests/kustomize/third-party/argo/base/workflow-controller-deployment-patch.yaml
  manifests/kustomize/third-party/argo/upstream/manifests/Kptfile
  manifests/kustomize/third-party/argo/upstream/manifests/base/crds/full/argoproj.io_clusterworkflowtemplates.yaml
  manifests/kustomize/third-party/argo/upstream/manifests/base/crds/full/argoproj.io_cronworkflows.yaml
  manifests/kustomize/third-party/argo/upstream/manifests/base/crds/full/argoproj.io_workflowartifactgctasks.yaml
  manifests/kustomize/third-party/argo/upstream/manifests/base/crds/full/argoproj.io_workfloweventbindings.yaml
  manifests/kustomize/third-party/argo/upstream/manifests/base/crds/full/argoproj.io_workflows.yaml
  manifests/kustomize/third-party/argo/upstream/manifests/base/crds/full/argoproj.io_workflowtaskresults.yaml
  manifests/kustomize/third-party/argo/upstream/manifests/base/crds/full/argoproj.io_workflowtasksets.yaml
  manifests/kustomize/third-party/argo/upstream/manifests/base/crds/full/argoproj.io_workflowtemplates.yaml
  manifests/kustomize/third-party/argo/upstream/manifests/base/crds/minimal/argoproj.io_workflowtaskresults.yaml
  manifests/kustomize/third-party/argo/upstream/manifests/base/workflow-controller/workflow-controller-deployment.yaml
  manifests/kustomize/third-party/argo/upstream/manifests/cluster-install/workflow-controller-rbac/workflow-controller-clusterrole.yaml
  manifests/kustomize/third-party/argo/upstream/manifests/namespace-install/kustomization.yaml
  manifests/kustomize/third-party/argo/upstream/manifests/quick-start/base/agent-role.yaml
  manifests/kustomize/third-party/argo/upstream/manifests/quick-start/base/artifactgc-role.yaml
  manifests/kustomize/third-party/argo/upstream/manifests/quick-start/base/kustomization.yaml
  manifests/kustomize/third-party/argo/upstream/manifests/quick-start/base/overlays/argo-server-deployment.yaml
  manifests/kustomize/third-party/argo/upstream/manifests/quick-start/base/prometheus/prometheus-deployment.yaml
  manifests/kustomize/third-party/argo/upstream/manifests/quick-start/minimal/kustomization.yaml
  manifests/kustomize/third-party/argo/upstream/manifests/quick-start/mysql/kustomization.yaml
  manifests/kustomize/third-party/argo/upstream/manifests/quick-start/postgres/kustomization.yaml
  manifests/kustomize/third-party/argo/upstream/manifests/quick-start/sso/dex/kustomization.yaml
  manifests/kustomize/third-party/argo/upstream/manifests/quick-start/sso/kustomization.yaml
  test/install-argo-cli.sh
  test/tag_for_hosted.sh
  third_party/argo/Dockerfile.argoexec
  third_party/argo/Dockerfile.workflow-controller
  third_party/argo/README.md
  third_party/argo/VERSION
  third_party/argo/imp-1-update-notices.sh
  third_party/argo/imp-2-build-push-images.sh
  third_party/argo/licenses-argoexec.csv
  third_party/argo/licenses-workflow-controller.csv
  third_party/argo/release.sh
Labels: lgtm, approved, size/XXL

#11782 feat(backend): Add a mutating webhook for the PipelineVersion kind
  .github/resources/manifests/kubernetes-native/kustomization.yaml
  .github/resources/manifests/kubernetes-native/overlays/apiserver-env.yaml
  .github/resources/scripts/deploy-kfp.sh
  .github/workflows/kfp-webhooks.yml
  backend/src/apiserver/main.go
  backend/src/apiserver/webhook/pipelineversion_webhook.go
  backend/src/apiserver/webhook/pipelineversion_webhook_test.go
  backend/test/integration/Makefile
  backend/test/integration/README.md
  backend/test/integration/webhook_test.go
  manifests/kustomize/base/webhook/kustomization.yaml
  manifests/kustomize/base/webhook/params.yaml
  manifests/kustomize/base/webhook/pipelineversion-mutating-webhook-config.yaml
  manifests/kustomize/env/cert-manager/platform-agnostic-k8s-native/kustomization.yaml
  manifests/kustomize/env/cert-manager/platform-agnostic-k8s-native/patches/deployment.yaml
  manifests/kustomize/env/cert-manager/platform-agnostic-k8s-native/patches/mutating-webhook.yaml
  manifests/kustomize/env/cert-manager/platform-agnostic-multi-user-k8s-native/kustomization.yaml
  manifests/kustomize/env/cert-manager/platform-agnostic-multi-user-k8s-native/patches/deployment.yaml
  manifests/kustomize/env/cert-manager/platform-agnostic-multi-user-k8s-native/patches/mutating-webhook.yaml
  manifests/kustomize/env/dev-kind/kustomization.yaml
  test/sdk-execution-tests/sdk_execution_tests.py
Labels: lgtm, approved, size/L

#11792 increase stale action timers
  .github/workflows/stale.yml
Labels: lgtm, approved, size/XS

#11735 fix(sdk): allow google-cloud-storage < 4
  sdk/RELEASE.md
  sdk/python/requirements.in
  sdk/python/requirements.txt
Labels: lgtm, approved, size/M, ok-to-test

#11794 fix(local): warn about oci:// not supported too
  sdk/python/kfp/dsl/types/artifact_types.py
  sdk/python/kfp/local/importer_handler.py
Labels: lgtm, approved, size/M, ok-to-test

#11788 Handle optional pipeline inputs in the driver
  backend/src/v2/compiler/argocompiler/argo.go
  backend/src/v2/driver/driver.go
  samples/v2/component_with_optional_inputs.py
  samples/v2/component_with_optional_inputs_test.py
Labels: lgtm, approved, size/M

#11796 chore(test): Removed the no longer needed rerun-pr-jobs.yml
  .github/workflows/rerun-pr-jobs.yml
Labels: lgtm, approved, size/S

#11795 docs: mention that `set_container_image` works with dynamic images
  sdk/python/kfp/dsl/pipeline_task.py
Labels: lgtm, approved, needs-ok-to-test, size/S

#11798 fix setup env for kfp k8s lib tests
  .github/workflows/kfp-kubernetes-library-test.yml
  test/presubmit-test-kfp-kubernetes-library.sh
Labels: lgtm, approved, size/M

#11762 feat(backend): implement logs as artifacts
  .pre-commit-config.yaml
  backend/src/v2/cmd/driver/main.go
  backend/src/v2/cmd/launcher-v2/main.go
  backend/src/v2/compiler/argocompiler/container.go
  backend/src/v2/compiler/argocompiler/dag.go
  backend/src/v2/compiler/argocompiler/importer.go
  backend/src/v2/component/launcher_v2.go
  backend/src/v2/component/launcher_v2_test.go
  backend/src/v2/driver/driver.go
  backend/src/v2/driver/driver_test.go
  manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
Labels: lgtm, approved, size/L

#11668 chore: Fix typos
  api/v2alpha1/go/pipelinespec/pipeline_spec.pb.go
  api/v2alpha1/pipeline_spec.proto
  backend/src/agent/persistence/worker/metrics_reporter.go
  backend/src/agent/persistence/worker/persistence_worker.go
  backend/src/agent/persistence/worker/persistence_worker_test.go
  backend/src/apiserver/server/api_converter_test.go
  backend/src/apiserver/template/v2_template.go
  backend/src/apiserver/visualization/server.py
  backend/src/common/client/api_server/v1/run_client.go
  backend/src/common/client/api_server/v1/visualization_client.go
  backend/src/common/util/execution_spec.go
  backend/src/common/util/parameter_formatter_test.go
  backend/src/crd/controller/scheduledworkflow/controller.go
  backend/src/crd/pkg/apis/scheduledworkflow/v1beta1/types.go
  backend/src/crd/samples/scheduledworkflow/parameterized.yaml
Labels: lgtm, approved, size/M, ok-to-test

#11807 Revert "feat(backend): implement logs as artifacts (#11762)"
  .pre-commit-config.yaml
  backend/src/v2/cmd/driver/main.go
  backend/src/v2/cmd/launcher-v2/main.go
  backend/src/v2/compiler/argocompiler/container.go
  backend/src/v2/compiler/argocompiler/dag.go
  backend/src/v2/compiler/argocompiler/importer.go
  backend/src/v2/component/launcher_v2.go
  backend/src/v2/component/launcher_v2_test.go
  backend/src/v2/driver/driver.go
  backend/src/v2/driver/driver_test.go
  manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
Labels: lgtm, approved, size/L

#11533 update driver & launcher image handling
  backend/src/v2/compiler/argocompiler/container.go
  manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
  manifests/kustomize/hack/release.sh
Labels: lgtm, approved, size/M

#11809 feat(backend): implement logs as artifacts + CI updates
  .github/workflows/kfp-kubernetes-execution-tests.yml
  .github/workflows/sdk-execution.yml
  .pre-commit-config.yaml
  backend/src/v2/cmd/driver/main.go
  backend/src/v2/cmd/launcher-v2/main.go
  backend/src/v2/compiler/argocompiler/container.go
  backend/src/v2/compiler/argocompiler/dag.go
  backend/src/v2/compiler/argocompiler/importer.go
  backend/src/v2/component/launcher_v2.go
  backend/src/v2/component/launcher_v2_test.go
  backend/src/v2/driver/driver.go
  backend/src/v2/driver/driver_test.go
  manifests/kustomize/base/pipeline/ml-pipeline-apiserver-deployment.yaml
  test/sdk-execution-tests/sdk_execution_tests.py
Labels: lgtm, approved, size/XL

#11816 chore(tests): remove unused logic
  .github/workflows/sdk-execution.yml
  test/sdk-execution-tests/sdk_execution_tests.py
Labels: lgtm, approved, size/S

#11818 fix(tests): free up space in some test runners
  .github/workflows/kfp-kubernetes-execution-tests.yml
  .github/workflows/sdk-execution.yml
Labels: lgtm, approved, size/S

#11820 fix(docs): Use the latest driver and launcher images in the dev environment
  backend/README.md
Labels: lgtm, approved, size/XS

#11821 fix(backend): Fix run submissions with OwnerReferencesPermissionEnforcement on
  manifests/kustomize/base/installs/multi-user/api-service/cluster-role.yaml
  manifests/kustomize/base/pipeline/ml-pipeline-apiserver-role.yaml
Labels: lgtm, approved, size/S

#11819 fix(deps): widen urllib3 upper bound to <3.0.0
  sdk/python/requirements.in
  sdk/python/requirements.txt
Labels: lgtm, approved, size/XS, ok-to-test

#11824 fix(docs): Remove Podman as backend README pre-req
  backend/README.md
Labels: lgtm, approved, size/XS, ok-to-test

#11806 chore(test): Improved path filtering in the CI
  .github/workflows/backend-visualization.yml
  .github/workflows/e2e-test.yml
  .github/workflows/frontend.yml
  .github/workflows/gcpc-modules-tests.yml
  .github/workflows/kfp-kubernetes-library-test.yml
  .github/workflows/kfp-samples.yml
  .github/workflows/kfp-sdk-runtime-tests.yml
  .github/workflows/kfp-sdk-tests.yml
  .github/workflows/kfp-webhooks.yml
  .github/workflows/kubeflow-pipelines-manifests.yml
  .github/workflows/presubmit-backend.yml
  .github/workflows/sdk-component-yaml.yml
  .github/workflows/sdk-docformatter.yml
  .github/workflows/sdk-execution.yml
  .github/workflows/sdk-isort.yml
  .github/workflows/sdk-upgrade.yml
  .github/workflows/sdk-yapf.yml
  .github/workflows/upgrade-test.yml
  .github/workflows/validate-generated-files.yml
Labels: lgtm, approved, size/M

#11827 chore: update release notes
  .cloudbuild.yaml
  .release.cloudbuild.yaml
  RELEASE.md
  images/build-images.png
  images/release-status-check.png
Labels: lgtm, approved, size/XXL

#11543 chore: Add the OpenSSF Best Practices badge
  README.md
Labels: lgtm, approved, size/XS

#11836 fix component retry test
  backend/src/v2/compiler/argocompiler/argo_test.go
  backend/src/v2/compiler/argocompiler/testdata/hello_world_with_retry.yaml
Labels: lgtm, approved, needs-ok-to-test, size/L

#11834 chore(backend): Optimized Dockerfiles
  backend/Dockerfile
  backend/Dockerfile.persistenceagent
  backend/Dockerfile.scheduledworkflow
  backend/Dockerfile.visualization
Labels: lgtm, approved, size/M

#11839 fix(sdk): Add SDK support for setting resource limits on older KFP versions
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/compiler/compiler_utils.py
  sdk/python/kfp/compiler/pipeline_spec_builder.py
  sdk/python/test_data/pipelines/pipeline_with_resource_spec.yaml
Labels: lgtm, approved, size/L

#11842 add missing release note updates to sdk main branch
  sdk/RELEASE.md
Labels: lgtm, approved, size/XS

#11841 fix(backend): fixed Dockerfile
  backend/Dockerfile.visualization
Labels: lgtm, approved, size/XS

#11845 chore(sdk): update go toolchain patch
  api/go.mod
  go.mod
  kubernetes_platform/go.mod
  kubernetes_platform/go.sum
Labels: lgtm, approved, size/L

#11844 chore(backend): fixed support for Podman in Makefile
  backend/Makefile
  backend/README.md
Labels: lgtm, approved, size/S

#11843 chore(sdk): release kfp sdk 2.12.2
  docs/versions.json
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
Labels: lgtm, approved, size/S

#11853 chore: (cherry-pick) Add SDK support for setting resource limits on older KFP versions
  .github/workflows/kfp-kubernetes-execution-tests.yml
  .github/workflows/sdk-execution.yml
  docs/versions.json
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
  sdk/python/kfp/compiler/compiler_test.py
  sdk/python/kfp/compiler/compiler_utils.py
  sdk/python/kfp/compiler/pipeline_spec_builder.py
  sdk/python/test_data/pipelines/pipeline_with_resource_spec.yaml
Labels: lgtm, approved, size/L

#11870 chore(sdk): kfp and kfp-kubernetes 2.13 & 1.5
  docs/versions.json
  kubernetes_platform/python/docs/conf.py
  kubernetes_platform/python/kfp/kubernetes/__init__.py
  sdk/RELEASE.md
  sdk/python/kfp/__init__.py
Labels: lgtm, approved, size/M

#11871 update release doc paths & make script executable
  RELEASE.md
  kubernetes_platform/python/create_release_branch.sh
  kubernetes_platform/python/release.sh
Labels: lgtm, approved, size/XS

#11878 Correct 2.5.x change log
  CHANGELOG.md
Labels: lgtm, approved, size/M

#11881 feat(backend): Add the Kubernetes native pipeline store
  .github/actions/kfp-cluster/action.yml
  .github/resources/manifests/argo/overlays/kubernetes-native/apiserver-env.yaml
  .github/resources/manifests/argo/overlays/kubernetes-native/kustomization.yaml
  .github/resources/manifests/kubernetes-native/overlays/proxy/kustomization.yaml
  .github/resources/manifests/kubernetes-native/overlays/proxy/proxy-env.yaml
  .github/resources/scripts/deploy-kfp.sh
  .github/workflows/e2e-test.yml
  .github/workflows/kfp-webhooks.yml
  .github/workflows/validate-generated-files.yml
  backend/src/apiserver/client_manager/client_manager.go
  backend/src/apiserver/config/config.go
  backend/src/apiserver/config/config_test.go
  backend/src/apiserver/filter/filter.go
  backend/src/apiserver/main.go
  backend/src/apiserver/resource/client_manager_fake.go
  backend/src/apiserver/storage/experiment_store.go
  backend/src/apiserver/storage/experiment_store_test.go
  backend/src/apiserver/storage/job_store.go
  backend/src/apiserver/storage/job_store_test.go
  backend/src/apiserver/storage/pipeline_store_kubernetes.go
  backend/src/apiserver/storage/pipeline_store_kubernetes_test.go
  backend/src/apiserver/storage/resource_reference_store.go
  backend/src/apiserver/storage/resource_reference_store_test.go
  backend/src/apiserver/storage/run_store.go
  backend/src/apiserver/storage/run_store_test.go
  backend/src/apiserver/webhook/pipelineversion_webhook.go
  backend/src/crd/kubernetes/v2beta1/pipeline_types.go
  backend/src/crd/kubernetes/v2beta1/pipelineversion_types.go
  backend/test/v2/integration/flags.go
  backend/test/v2/integration/pipeline_api_test.go
  backend/test/v2/integration/pipeline_version_api_test.go
  frontend/src/pages/NewPipelineVersion.tsx
  manifests/kustomize/base/crds/pipelines.kubeflow.org_pipelines.yaml
  manifests/kustomize/base/crds/pipelines.kubeflow.org_pipelineversions.yaml
  manifests/kustomize/env/cert-manager/platform-agnostic-k8s-native/kustomization.yaml
  manifests/kustomize/env/cert-manager/platform-agnostic-k8s-native/patches/role.yaml
  manifests/kustomize/env/cert-manager/platform-agnostic-k8s-native/patches/service.json
  manifests/kustomize/env/cert-manager/platform-agnostic-k8s-native/patches/service.yaml
  manifests/kustomize/env/cert-manager/platform-agnostic-multi-user-k8s-native/kustomization.yaml
  manifests/kustomize/env/cert-manager/platform-agnostic-multi-user-k8s-native/patches/role.yaml
  manifests/kustomize/env/cert-manager/platform-agnostic-multi-user-k8s-native/patches/service.json
  manifests/kustomize/env/cert-manager/platform-agnostic-multi-user-k8s-native/patches/service.yaml
Labels: lgtm, approved, size/XXL

#11883 fix(backend): Stop logging the strack trace on benign user errors
  backend/src/common/util/error.go
Labels: lgtm, approved, size/XS
